### ISSUE TITLE
Kafka broker configuration is not consistent across the kafka source and sink

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1004]
This is feedback from a production user:

> It would be nice if the brokers were specified in the same way with the kafka sink and the kafka source.. Right now, one of them is a comma separated string and the other is actually broken out in square brackets.

Basically, the `kafka` source takes a comma-separated list of `bootstrap_servers` and the `kafka` sink takes a proper array. I prefer the array unless there is a limitation to doing so.

**Comment by friedroman** [comment]
Hey. To give a little bit of feedback from a longtime Kafka user but just looking at vector as a big fan of Rust - I would strongly prefer you leave the most commonly used comma separated single string value as common configuration.
This is how you pass configuration to Kafka consumer or producer on multiple platforms including to my knowledge Java [Producer](https://kafka.apache.org/090/documentation.html#producerconfigs) and [Consumer](https://kafka.apache.org/090/documentation.html#newconsumerconfigs) as well as what most other platform's clients are based on - C/C++ library [librdkafka](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md). And perhaps most importantly for ease of migration keeping in mind scope overlap - [Kafka Connect](https://kafka.apache.org/090/documentation.html#connectconfigs)
Keeping it CSV will make writing and migrating configuration easier, will enable to use same values for multiple systems in configuration management systems like ansible or puppet.
Please consider this when choosing the common configuration format.

**Comment by lukesteensen** [comment]
That's a good point, thanks @friedroman! Consistency with the rest of the kafka ecosystem is probably the best way to go here.
