### ISSUE TITLE
Support reopening the daemons log files without restart

### ISSUE THREAD

**Issue by grddev** [timberio/vector#1008]
I'm trying to write a logrotate configuration for vector itself, but it seems the HUP signal does not reopen its log file. While both a copytruncate configuration and restarting the vector daemon works well, it would be nicer if the log files could be reopened without the extra work.

**Comment by lukesteensen** [comment]
Hi @grddev! Could you provide some more information about how you're running vector?

The vector process itself does not log directly to a file (unless you're talking about a pipeline with a file sink), so normally it's your process manager that would have the open handle to the log file.

**Comment by grddev** [comment]
Ah, I see I mixed things up. The output was actually redirected in an init script. For the benefit of anyone else similarly confused in the future and searching for an answer here, the following question and answers would likely be helpful https://superuser.com/questions/291368/log-rotation-of-stdout.
