### ISSUE TITLE
Clarify behavior of  `start_at_beginning` option

### ISSUE THREAD

**Issue by lukesteensen** [timberio/vector#1020]
The docs for `start_at_beginning` currently read:

```
  # When `true` Vector will read from the beginning of new files, when `false`
  # Vector will only read new data added to the file.
```

The actual behavior is a little more complex. Where Vector starts reading a file depends on a number of factors:

1. Was this file last modified more than `ignore_older_than` seconds ago?
2. Did we find the file at startup or did it appear while we were already running?
3. Do we have a checkpoint stored for this file?
4. `start_at_beginning`

The full truth table is then as follows:

Old | Startup | Checkpoint | `start_at_beginning` | Result
-- | -- | -- | -- | --
Y | - | - | - | End
N | Y | Y | Y | Beginning
N | Y | Y | N | Checkpoint
N | Y | N | Y | Beginning
N | Y | N | N | Beginning
N | N | Y | Y | Checkpoint
N | N | Y | N | Checkpoint
N | N | N | Y | Beginning
N | N | N | N | Beginning

As you can see, the only time `start_at_beginning` actually makes a difference is for a young file at startup for which we already have a checkpoint stored. This feels quite limited and is maybe not the behavior we want. Row five (`NYNN`) should probably start at the end of the file, and there's a case for row nine (`NNNN`) to do so as well.

Even if we don't change the behavior at all, it would probably be best to include some of this information in the docs.

**Comment by binarylogic** [comment]
Yeah, this is definitely surprising.

> Row five (NYNN) should probably start at the end of the file
> and there's a case for row nine (NNNN) to do so as well.

I agree with both. I'd like to make this change. IMO `start_at_beginning = false` should always start at the end of newly recognized files (no checkpoint).

**Comment by LucioFranco** [comment]
I think changing the behavior of this makes sense. After talking with @lukesteensen for now we will just update the docs to be clear in #1523 but since this change is more nuanced we will want to think about how to change the code in a way that keeps the truth table stable.

**Comment by LucioFranco** [comment]
Moving forward to fix this issue we should refactor https://github.com/timberio/vector/blob/master/lib/file-source/src/file_server.rs#L307 to accept a `SeekFrom` enum that is set to `End(0)` if `start_at_beginning` is `false` and if the file has not been check pointed yet.

**Comment by binarylogic** [comment]
@lukesteensen it looks like #6178 closes this? Reopen if I'm mistaken.
