### ISSUE TITLE
Version mismatch in binary output

### ISSUE THREAD

**Issue by jamtur01** [timberio/vector#1021]
I installed the 0.5.0 RPM or Debian packages from GitHub and I see:

```
ubuntu@ip-10-0-1-211:~$ vector
Oct 11 23:01:04.346  INFO vector: Log level "info" is enabled.
Oct 11 23:01:04.346  INFO vector: Loading config. path="/etc/vector/vector.toml"
Oct 11 23:01:04.348  INFO vector: Vector is starting. version="0.4.0-dev" git_version="v0.5.0" released="Thu, 10 Oct 2019 18:39:52 GMT" arch="x86_64"
Oct 11 23:01:04.348  INFO vector::topology: Running healthchecks.
Oct 11 23:01:04.349  INFO vector::topology: Starting source "in"
Oct 11 23:01:04.349  INFO vector::topology: Starting sink "out"
Oct 11 23:01:04.349  INFO healthcheck{name=out}: vector::topology::builder: Healthcheck: Passed.
Oct 11 23:01:04.349  INFO source{name="in"}: vector::sources::stdin: Capturing STDIN
```

When I run it. I see `version="0.4.0-dev"` and `git_version="v0.5.0"` -> Is this a bug or should I expect the versions to vary?

**Comment by binarylogic** [comment]
Thanks, @jamtur01, and sorry about that. I opened https://github.com/timberio/vector/issues/1010 to address this.

**Comment by jamtur01** [comment]
As an aside - the asset names in the GH release also changed between 0.4.0 and 0.5.0.

0.4.0: https://github.com/timberio/vector/releases/download/v0.4.0/vector-0.4.0-amd64.deb

0.5.0: https://github.com/timberio/vector/releases/download/v0.5.0/vector-amd64.deb

Not particularly important but annoying for folks building Docker images or configuration management modules, etc.

Thanks.

**Comment by binarylogic** [comment]
Apologies for that! We've been working out kinks in the release process. Minus this issue, I believe everything should be resolved. The asset names won't be changing again. Thanks for letting us know.
