### ISSUE TITLE
Send aggregated histograms to Datadog

### ISSUE THREAD

**Issue by loony-bean** [timberio/vector#1027]
Datadog histograms aggregation is [made by DogStatsD](https://docs.datadoghq.com/developers/faq/data-aggregation-with-dogstatsd-threadstats/#aggregation-rules-per-metric-type) before data is sent to the DD API endpoint.

Possible solution might be calculating multiple metrics, such as _min_, _max_, _avg_, etc, from batches of histogram values, and sending them out from the sink.

At first glance such aggregated histograms looks similar to Prometheus [summary metric type](https://prometheus.io/docs/concepts/metric_types/#summary), so there might be some generalised solution.

Blocked by #1026, #976
Rel #967

**Comment by lukesteensen** [comment]
That lines up with what it seems like [veneur](https://github.com/stripe/veneur#by-metric-type-behavior) does, which makes sense.
