### ISSUE TITLE
Spec out the "Improve setup & debugging" project

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1030]
Before we begin work on https://github.com/timberio/vector/milestone/19, I'd like to do the following:

- [ ] Remove any currently assigned issues we do not want to do.
- [ ] Add any issues we're missing.
- [ ] Shape all issues so they are ready to be worked on.
- [ ] Agree on a delivery date & schedule presentation.

I'd like to limit this project to 4 weeks, which would put us into the second week of November.

**Comment by Jeffail** [comment]
Improvement ideas added to: https://github.com/timberio/vector/issues/98
^ Becomes a dependency of: https://github.com/timberio/vector/issues/658

**Comment by Jeffail** [comment]
Added: https://github.com/timberio/vector/issues/1039

**Comment by binarylogic** [comment]
After going over everything with @Jeffail, it became clear we should break this down into separate focused projects. It's important that we optimize for single use cases as they can be unfocused in aggregate. That said, a good paradigm to think about this is the user lifecycle:

1. Initial evaluation
2. Local development & testing
3. Deployment (includes checks / verification)
4. Monitoring
5. Remote debugging

For this project we should focus on 2 (Local development & testing), and then create follow up projects for each of these phases. I'll be updating the roadmap, as well as the issues contained in this milestone unless anyone objects.

To clarify the goal of this project, it's to go from a blank Vector config to working production Vector config as quickly and easily as possible without the need to "test in production".

**Comment by binarylogic** [comment]
This is done:

1. I updated the milestone to be focused on 2 above (Local development & testing).
2. I removed any issues not relevant.
3. I also create https://github.com/timberio/vector/milestone/24 to represent an observability project.
4. I also updated the roadmap with https://timber.productboard.com/feature-board/867981-vector/features/3132692/detail and https://timber.productboard.com/feature-board/867981-vector/features/3132718/detail.
