### ISSUE TITLE
Basic_auth in http sink

### ISSUE THREAD

**Issue by soufiane-bouchaara** [timberio/vector#1040]
Hi,

When enabling basic_auth in HTTP sink , I keep receiving the following error : 
``
ERROR vector: Configuration error: unknown field `basic_auth` for key `sinks.http`
`` 
Here's  my config file :

```

sources.apache_logs]
  type         = "file"
  include      = ["/var/log/httpd/error_log","/var/log/httpd/access_log"]    
  ignore_older = 86400
  

[transforms.log_transformer]
  type = "json_parser" # must be: "json_parser"
  inputs = ["apache_logs"]

[sinks.http]
  type  = "http"
  inputs = ["log_transformer"]
  uri = "https://domain.com/logstash/xxxxx"
  encoding = "text" 
  healthcheck_uri = "https://domain.com/logstash/_health"
  
  [sinks.http.basic_auth]
    user = "xxx"
    password = "xxxx"

[sinks.out]
    inputs = ["log_transformer"]
    type = "console"
```

**Comment by soufiane-bouchaara** [comment]
After removing  [sinks.http.basic_auth] and adding directly user and password to [sinks.http], the issue was resolved, 
Can you please update the documentation ?

**Comment by binarylogic** [comment]
Apologies @soufiane-bouchaara, thanks for reporting.

@lukesteensen shouldn't this be nested under the `basic_auth` table? This was added in:

https://github.com/timberio/vector/pull/94/files#diff-75c76412401a1e8914185ac186f764f2R16

**Comment by lukesteensen** [comment]
@binarylogic The `flatten` attribute above the field means that its fields get inlined, so you don't have to deal with a nested table.

**Comment by binarylogic** [comment]
Ah, that's my fault then. Although, I do like the table. I'll add a follow up issue and update the docs.

**Comment by lukesteensen** [comment]
Yeah, I'm fine with it working either way. I think I generally leaned towards flattening to keep the user-facing structure simpler, but nested tables are becoming more of a norm.

**Comment by binarylogic** [comment]
On second thought, I'd like to remove the flattening here since the `elasticsearch` and `clickhouse` sinks currently do not flatten these options. I'd prefer that we keep this consistent, and in general, we're moving towards nesting similar options.

**Comment by binarylogic** [comment]
Hi @soufiane-bouchaara, we just made a number of changes to our configuration that should help clarify and simplify the options. You should be able to accomplish this with:

```toml
[sinks.http]
  type  = "http"
  auth.strategy = "basic"
  auth.username = "username"
  auth.password = "password"
```
