### ISSUE TITLE
Automatic directory creation with file sink

### ISSUE THREAD

**Issue by foamkeen** [timberio/vector#1043]
It would be very useful if the file sink supported automatic directory creation.
Then it could be possible to use configuration like:
`path = "/data/logs/{{ application_name }}/{{environment}}/{{logtype}}-%Y-%m-%d.log"`
without the need to create all the directories beforehand (which in case of dynamic environments is not even possible).

**Comment by binarylogic** [comment]
Thanks, @foamkeen, agree! We'll add it to our roadmap.
