### ISSUE TITLE
File source stops following the file under a symlink on rotation

### ISSUE THREAD

**Issue by foamkeen** [timberio/vector#1053]
There appears to be a bug in file source. When trying to rotate a file under a symlink Vector reports this in the log:
`WARN source{name="kubernetes"}:file_server: file_source::file_watcher: Found line that exceeds max_line_bytes; discarding. rate_limit_secs=30`
and just hangs.

All the lines in the test log are much shorter than `max_line_bytes` value.
Here is the source configuration:
```
[sources.kubernetes]
  type                = "file"
  include             = ["/logs/links/*.log"]
  data_dir            = "/var/lib/vector"
```
In `/logs/links/` directory there is a single symlink pointing to `../files/log` which I'm rotating with `mv log log.0` command.

Please let me know if you need any additional info to reproduce the issue I'm facing.

**Comment by binarylogic** [comment]
Thanks, @foamkeen, appreciate you reporting. We haven't actually tested symlinks in the file source, I wasn't aware that was desirable. Could you share why you're doing this so we can better understand the use case? Thanks!

**Comment by foamkeen** [comment]
Sure, I'm trying to use Vector as a logging agent on a Kubernetes node where container logs are located as symbolic links in `/var/log/containers` and are being rotated by Docker by simply moving underlying files from time to time. So that's the setup I was trying to simulate with my symlink and `mv`.

**Comment by binarylogic** [comment]
Got it! Just for reference, would https://github.com/timberio/vector/pull/893 be something you'd use instead once it's merged?

**Comment by foamkeen** [comment]
Yes, probably native Kubernetes source would be something more suitable for the job.

**Comment by lukesteensen** [comment]
I haven't been able to reproduce this so far, so I'm curious if there's anything else in your environment that could be causing the difference. Here's what I'm doing:

`vector.toml`:
```toml
[sources.file]             
type = "file"              
include = ["link.log"]     
data_dir = "vector_data"   
                           
[sinks.con]                
inputs = ["file"]          
type = "console"           
encoding = "text"             
```

`test.sh`:
```bash
#!/bin/bash                                    
                                               
set -o errexit                                 
set -o nounset                                 
set -o pipefail                                
                                               
rm -rf link.log file.log file.log0 vector_data 
mkdir vector_data                              
                                               
echo "Start vector now..."                     
sleep 5                                        
                                               
echo "Creating file and symlink"               
touch file.log                                 
ln -s file.log link.log                        
                                               
sleep 2                                        
                                               
echo "Writing to file"                         
man bash | head -n 20 >> link.log              
                                               
sleep 2                                        
                                               
echo "Rotating file"                           
mv file.log file.log0                          
                                               
sleep 2                                        
                                               
echo "Writing to file again"                   
man cat | head -n 20 >> link.log
```

The behavior is the same whether I write to the symlink (`link.log`) or the file itself (`file.log`).

A couple of questions to try to help narrow it down:
1. Are you seeing this only after a rotation? That is, are you getting data normally before the first rotation?
2. If you're in a containerized environment, are you mounting both the directory with the symlinks and the directory with the log files consistently relative to each other? If they're across different volumes, it's possible the symlink ends up pointing somewhere else from the container's point of view.

I can think of a few ways we could potentially improve symlink handling, but I'd like to understand what's currently failing here before implementing any changes.

Thanks again for the report, @foamkeen!

**Comment by foamkeen** [comment]
I'm sorry, it appears that there is something with the way Docker for Mac mounts directories inside the Docker VM (I was running Vector inside a container). I'm not able to reproduce the issue in a VM (or doing the `mv` command inside the container itself).

Issue is only reproducible if I do `mv` command on my host machine. So I suppose this particular issue can be closed, sorry to bother you.
