### ISSUE TITLE
Use most recent/portable versions of LevelDB and Snappy dependencies

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#1056]
Currently the most recent version of `leveldb-sys` crate that we use for disk buffers depends on LevelDB 1.18. The latest upstream release of LevelDB is 1.22 ([changelog](https://github.com/google/leveldb/releases)).

In particular, version 1.21 added native Windows support, which could be very useful for #880.

Also, as mentioned in #1054, the version 1.1.2 of [Snappy](https://github.com/google/snappy) used by `leveldb-sys` has an Autotools-based build scripts, which make it less flexible about cross-compilation (in particular, a special flag has to be passed to the configure script, and `levelb-sys` build script doesn't support passing it). The most recent version 1.1.7 of Snappy supports CMake, which supports reading of build configuration from environment variables, so updating it could have simplified building for ARM.

Thus, it would be helpful to have an updated version of `leveldb-sys` crate supporting most recent versions of LevelDB and Snappy in order to support more targets.

**Comment by LucioFranco** [comment]
Just to note the author of `leveldb` has offered to give us access to the repo and apply these changes so that we are not blocked.

**Comment by binarylogic** [comment]
It sounds like we should definitely do this.

@LucioFranco can you have him give us access? Is there any we didn't take him up on that?

**Comment by LucioFranco** [comment]
@binarylogic I say let us discuss this more on Monday but I was not sure if we wanted to take up more work with `leveldb` yet so I wanted to have a discussion with the rest of the team before we commit to something like this. If we agree I will shoot an email over to the author.

**Comment by binarylogic** [comment]
What is the alternative? I do not want to block this issue to move off of leveldb. Moving off of leveldb will likely be a larger project addressed in https://github.com/timberio/vector/milestone/23; it is not something I want to rush or do haphazardly.

**Comment by binarylogic** [comment]
@a-rodin just documenting a discussion in Slack. We'd like to just fork the `leveldb-sys` repo for now and make the changes. We will get the team added as contributors so that we have commit rights to the repo.

**Comment by a-rodin** [comment]
Note that we also need to add CMake to list of our development requirements, as newer versions of LevelDB use it as the build system.

**Comment by a-rodin** [comment]
I think that for now we can keep the same version of `leveldb-sys` crate to not require everyone to install CMake, but use updated `leveldb` crate from our fork which can be compiled on ARM.
