### ISSUE TITLE
Improve `docker` source container filters

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#1057]
# Motivation

Improve how users are able to filter which containers the `docker` source should attach itself too to collect logs. Currently, only `include_containers` and `include_labels` are available config options when using the `docker` source. This is limiting since the `include_containers` option only allows one to specify a generated container id and not say an image name that is pre-defined and static.

# Proposal

Provide an additional list of container filters that would allow users to filter out unwanted containers via more options like image name, container name, etc.

# Specification

To close this issue we should add the following options to the `docker` source:

- [ ] `include_images` which should be an `AND` operation with the rest of the filters and should only allow containers with the provided image to pass.
- [x] `include_names` which should be an `AND` operation with the rest of the filters and should only allow containers with the provided container name to pass.
- [ ] `include_created_before`/`include_created_after` this should work like the ones above but filter on the created_at value given back by docker.

@ktff I know you mentioned before that `shiplift` was missing a few additional filters. This change may require us to add a few more things to this library.

**Comment by ktff** [comment]
> I know you mentioned before that `shiplift` was missing a few additional filters. 

@LucioFranco The missing filters are an optimization, and some of them were implemented in `shiplift`, just not released. But this high level of filtering we can do on `vector` side without any noticeable performance cost.

**Comment by ktff** [comment]
@LucioFranco `include_containers` actually supports both container id and container name filtering at the same time, so `include_names` is done, but the documentation needs to be updated.

**Comment by binarylogic** [comment]
@ktff thanks. I've updated the docs to note that `include_containers` accepts both IDs and names. We just need to 2 other filters outlined above.
