### ISSUE TITLE
Add the ability to filter containers in the `kubernetes` source

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#1059]
# Motivation

As a user, I would like to filter out certain pods from getting their logs scraped by Vector.

# Proposal

We should provide a set of filters that allow a user to filter on the container name or pod uid.

# Specification

Filter which log files the `kubernetes` source picks up. We should provide the following filters.

- [ ] `include_container_names` which should only allow the source to pick up container names that start with the provided strings.
- [ ] `include_pod_uids` which should be an `AND` operation with the other filters and should only allow pods with a `pod_uid` that starts with ones provided.
- [ ] `include_namespaces` which should be an `AND` operation with the other filters and should only allow pods within the included namespaces. (this might depend on verifying if the way kubernetes creates its files names will be forwards compatible)
- [ ] `include_images` which should be an `AND` operation with the other filters and should only allow pods with an image that starts with one of the provided images.

These options should all be possible based on the current implementation of the `kuberenetes` source in #893.

**Comment by ktff** [comment]
Blocked on #1060

**Comment by ktff** [comment]
@LucioFranco so with #1060 done, `include_container_names`, `include_pod_uids`, and `include_namespaces` filtering, can be done on best effort basis. But for `include_images` filter, source doesn't have the necessary information, only after #1072 transform will we have the `image` information. 

So I see two option:
 1. Remove `include_images` filter altogether, and leave it to the user to use appropriate filter. This kind of filtering could be supported more ergonomically with a set based filtering transform.
 2. Add it with #1072 transform.
      


Option 1. seems like the best.  Although it's rather unfortunate, as filtering by image seems quite useful.

**Comment by tigerwings** [comment]
The current implementation excludes kube-system by default. On the contrary, we are mostly interested in these logs. Could the `Kubernetes source` include it by default and filter it out if necessary?

**Comment by ktff** [comment]
@tigerwings for general, most frequent use case, excluding `kube-system` by default is preferred, but with merger of #1501 it will be possible to include `kube-system` namespace to get those logs. 

So if you need only `kube-system`, #1501 will work fine. But if you also want to listen for other namespaces, they will need to be included. 

As this is somewhat of a roundabout way of doing things, in the future, we will probably add `exclude_namespaces` option which will have `kube-system` as one of the default values. Then, your use case will be supported without limitations.
