### ISSUE TITLE
Improve `kubernetes` source event metadata

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#1060]
# Motivation

As a user, I want more base knowledge of what container's my logs are coming from without needing to query the kube api separately.

# Proposal

Use the items we filter on from #1059 to provide more metadata.

# Specification

We should provide additional metadata that is available when scraping logs from each node's filesystem. The following metadata should be provided.

- [ ] `namespace` should contain the namespace folder these logs were pulled from.
- [ ] `image` should contain the container image name. @ktff I'm not sure if this is already accomplished via the `container_name` field already?

This also will aide in future metadata enrichment issues where we may need to use the pod's namespace to find more metadata.

As well as metadata as stated in this [comment](https://github.com/timberio/vector/issues/814#issuecomment-544944999) we will need to also filter out EKS system logs like what we do for the `kube-system` namespace.

**Comment by binarylogic** [comment]
Don't we need a lot more metadata than this? And didn't we already spec this out in the original k8s issue? See "Enrichment" in https://github.com/timberio/vector/issues/260.

**Comment by LucioFranco** [comment]
@binarylogic so this is metadata that we can pull without needing to talk to the kube api. I am writing a follow up issue around enriching with labels etc that must come from the kube api. That will be a separate transform while these will come from the source.

**Comment by ktff** [comment]
> image should contain the container image name. @ktff I'm not sure if this is already accomplished via the container_name field already?

@LucioFranco `container_name` has value of `spec:containers:name` field from .yaml configuration.


> so this is metadata that we can pull without needing to talk to the kube api

I thought that also for `namespace` that was embedded into `podUID`, but that was implementation dependent. For example `podUID` in AWS EKS doesn't contain `namespace` nor anything else recognizable.

**Comment by binarylogic** [comment]
@ktff would you change the proposed spec in the original issue description? If so, I want to make sure that's accurate.

**Comment by ktff** [comment]
> @ktff would you change the proposed spec in the original issue description? If so, I want to make sure that's accurate.

@binarylogic I am not sure I understand what you mean by that.

This specification is good as it is. It is just that I think that it will be necessary to communicate with kube api to get this information. 

And by original spec, I presume you mean #260. Regarding "Enrichment", #893 doesn't support `labels`, and `instance_number` turned out to be useless information, so it isn't collected. So, yes, this could/should be updated to remove any confusion. I'll do this either way.

**Comment by linc01n** [comment]
I have a ugly way to pull that information out. I use a lua transform to parse the `config.v2.json`  and add it to the log event.

**Comment by LucioFranco** [comment]
@ktff yeah so pod_uid we are not gonna be able to use that. But I was curious if we could use the path the log file is in. From what I saw it contains both the namespace and the image name?

**Comment by ktff** [comment]
@linc01n could you point to some documentation or some other place where you found it? It would be great if there is a well defined file with this information. 

---

>  But I was curious if we could use the path the log file is in.

@LucioFranco by current specification [v1alpha2](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/cri-api/pkg/apis/runtime/v1alpha2), the path to log file looks like `/var/log/pods/<podUID>/<containerName>/<Instance#>.log`. The namespace and image name that are being seen are a part of podUID in some implementations, and in some not, as it is not defined in the specification.

**Comment by linc01n** [comment]
It is docker specific. https://medium.com/@felipedutratine/docker-internal-files-to-debug-your-container-8f316b454ae6
I can't seems to find it from docker doc.

**Comment by ktff** [comment]
Then we can't use it, as this issue requires portable and more long term source of information. 
But, thanks for mentioning it.

**Comment by LucioFranco** [comment]
@ktff ah you're right, this is unfortunate :(

**Comment by LucioFranco** [comment]
For this implementation, I suggest we follow the regex solution proposed here https://github.com/timberio/vector/issues/1072#issuecomment-545652380.
