### ISSUE TITLE
Reusable configuration macros / snippets

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1061]
This is a follow up to https://github.com/timberio/vector/issues/832#issuecomment-543094365. @Jeffail had a good idea to define reusable "snippets" that could be included across multiple pipelines. I won't repeat his example here, but before we begin work we should agree on a spec.

**Comment by binarylogic** [comment]
We're deferring this issue until we have more demand. If you find this useful please let us know.

**Comment by binarylogic** [comment]
Closing this in favor of https://github.com/timberio/vector/issues/1061

**Comment by MOZGIII** [comment]
> Closing this in favor of #1061

But this one is #1061 :confused:

**Comment by MOZGIII** [comment]
Must be #1445
