### ISSUE TITLE
Add deployment documentation around `kubernetes`

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#1070]
We should provide thorough deployment guides around how to deploy vector onto a kube cluster. There should be two general sections, one section should provide information on how to get logs from your pods into vector, the second section should explain suggested ways to deploy a vector processing pipeline onto a kube cluster. This second section kind of relates to #768 since the operator would automate this for you.

## Deployment Guides

- [ ]  `per node` deployment model should explain the current example that we have in #893. This deploys a version of vector with each physical kube node. It will then use the filesystem to collect logs.

- [ ] `sidecar` this should follow the model of running vector as a "sidecar" container to each selected pod. I'm not sure exactly yet what the best approach to this is yet but it should follow a similar model to what `linkerd` does.

## Pipeline Guides

I am open to different guides here but a common one might be something like deploying vector and kafka to a kube cluster. I think it would be very handy to provide ready made kube configs and a simple guide to show users how to get started.

**Comment by binarylogic** [comment]
Closing in favor of https://github.com/timberio/vector/issues/1450.

/cc @ktff
