### ISSUE TITLE
Support more community integrations

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#1071]
As we expand our kubernetes support we should look into supporting integrations with different tools that live on top of kubernetes. This issue is a tracker issue for different communities we may want to reach out too and be involved in.

- [`rudr`](https://github.com/oam-dev/rudr)
- [`helm`](https://github.com/helm/helm)

**Comment by binarylogic** [comment]
Closing in favor of https://github.com/timberio/vector/issues/1398 and https://github.com/timberio/vector/issues/1397

**Comment by ChethanUK** [comment]
@binarylogic What about dapr.io?
