### ISSUE TITLE
Generalize internal HTTP server

### ISSUE THREAD

**Issue by Jeffail** [timberio/vector#1075]
Vector currently runs its own HTTP server endpoint for exposing metrics. We should generalise this server to allow us to add endpoints for other purposes (https://github.com/timberio/vector/issues/1039, https://github.com/timberio/vector/issues/1073).

The interface for adding endpoints should allow us to provide a description of what the endpoint is for. Then perhaps we could also add an endpoint `/endpoints` that returns a list of available endpoints, maybe something like:

```sh
$ curl http://localhost:1234/endpoints | jq '.'
{
  "/endpoints": "this endpoint",
  "/metrics": "returns service metrics for prometheus to scrape",
  "/config/json": "returns a JSON representation of the loaded configuration"
}
```

**Comment by Jeffail** [comment]
Another consideration is that some endpoints might be useful for debugging/testing Vector configs, but not desired in production environments (`/config` or `/stacktrace`, for example) so we should probably have two tiers of endpoint, one which is general and another which is for debugging. We could allow users to enable debugging endpoints with a flag (with a warning log on start up to prevent accidental enabling in prod).

We could potentially expand that to make all debug tier endpoints namespaces under `/debug`, for example the config endpoint might be `/debug/config/json`.

**Comment by binarylogic** [comment]
I think this all makes sense. The concern around `/config` for production environments is that it could expose secrets, correct? Why wouldn't we want to allow `/stacktrace` for production though?

**Comment by Jeffail** [comment]
Just throwing it out there as a possibility. If there's a performance impact on providing the `/stacktrace` endpoint then we might not want to have it enabled it in prod. I'm also not sure we'd want to namespace endpoints with `/debug`.

**Comment by binarylogic** [comment]
@leebenson putting this on your radar since you're working through this.
