### ISSUE TITLE
Add CI check to enforce new versioning strategy

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1083]
This is a follow-up task for https://github.com/timberio/vector/pull/1044#issuecomment-545442114.

The proposed versioning strategy has us bumping the version after a relevant change is merged into `master`. This avoids the need to guess the next version, allowing up to bump the patch, minor, or major version based on the previous change. Unfortunately, this requires a human to remember to bump the version. To avoid this we should add a CI check that enforces this. It should do the following:

1. Look at the changes since the last release and determine the appropriate version bump based on the conventional commit spec.
2. Compare the expected version against the current `Cargo.toml` version.
3. If there is a difference, fail the check.

**Comment by binarylogic** [comment]
@a-rodin do you want to take a stab at this? It should be fairly simple:

1. Grab all commits since the last release: `git log vX.X.X...HEAD --pretty=format:'%s'`
2. `/^feat/` = minor, `/^enhancement/` = patch, `!:` = major.

I'm sure you'll have a better strategy than this, but hopefully, that helps.

**Comment by a-rodin** [comment]
@binarylogic I'll try to add this check.
