### ISSUE TITLE
Test shutdown works via `topology::stop`

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#1089]
It would be handy to be able to test that `topology::stop` works as intended. I'm not sure what the best approach would be here.

@lukesteensen suggested we use something like https://docs.rs/assert_cmd/0.11.1/assert_cmd/ that we could use to run a debug binary of vector and see if it closes with the proper exit codes.

I am open to other suggestions.

**Comment by binarylogic** [comment]
@LucioFranco is this still relevant given Spencer's recent work?

**Comment by LucioFranco** [comment]
I think this could be useful if we framed this as an external test. Aka if I were a user using this does vector shutdown as I expect.

**Comment by binarylogic** [comment]
If I recall Spencer added a [comprehensive test](https://github.com/timberio/vector/pull/1994#discussion_r392522471) and I wanted to make sure that didn't cover it. Is what you're describing better served in the [test harness](https://github.com/timberio/vector-test-harness)?

**Comment by LucioFranco** [comment]
Probably, I think this fits in with our reliability checker luke wrote? Not sure, but something external like what the test harness does would be ideal. But yes, what spencer wrote there is great but doesn't cover what this issue wanted.

**Comment by ktff** [comment]
An integration test with suggested `assert_cmd` would cover the whole shutdown procedure, and would be simpler than in test harness.

But, by adding `graceful_shutdown_correctness` test to test harness, we would have one more correctness check to show although it wouldn't be a differential check since all of the others also have it. 

So I would say, it comes to if we want that extra correctness check or not.

**Comment by binarylogic** [comment]
> An integration test with suggested assert_cmd would cover the whole shutdown procedure, and would be simpler than in test harness.

That sounds good to me. Let's defer the test harness until we feel a need.

**Comment by ktff** [comment]
Note: 
This should test shutdown procedure with all sources so to test if they are all listening `ShutdownSignal`.
