### ISSUE TITLE
Refactor the tower request configuration in sinks

### ISSUE THREAD

**Issue by bruceg** [timberio/vector#1090]
Similar to #955, many of the sinks use a similar configuration structure for batching based on Tower (`aws_cloudwatch_logs`, `aws_cloudwatch_metrics`, `aws_kinesis_streams`, `aws_s3`, `clickhouse`, `datadog_metrics`, `elasticsearch`, `http`, and `splunk_hec`). These would benefit from merging the common code and configuration structure to ensure the options names and usage don't diverge.

**Comment by binarylogic** [comment]
Big 👍 on this. This should also reduce the boilerplate code for new sink contributions, correct?

Ref #1022, #1023, #1024.

**Comment by bruceg** [comment]
It should reduce boilerplate code, yes, which was how I saw it.

**Comment by bruceg** [comment]
While working on this, I realized all of the sinks that would use it have slightly different defaults for most of the settings (only `request_rate_limit_duration_secs` and `request_retry_backoff_secs` were the same across all sinks). Do we want to try to unify the defaults, or do they need to be kept due to the diverse nature of the sinks?

**Comment by LucioFranco** [comment]
@bruceg they are unique per sink to follow their service defaults. So this probably means we can't use the `impl Default` for it :(

serde does have an attribute you can use to set the "default" impl of a funciton that might work?

**Comment by bruceg** [comment]
That's what I figured. I don't think the serde default attribute will help, since I'm explicitly trying to unify the config structure (and also the implementations), but that would need to be set separately for each config.

**Comment by LucioFranco** [comment]
@bruceg this should work https://serde.rs/container-attrs.html#default--path

**Comment by bruceg** [comment]
@lukesteensen Lucio said you had more experience with serde and might know.

For this refactoring, I have created two separate structs, one for the two batching parameters, and another for all the `request_*` settings. Each sink has different defaults for these, so we can't use a centralized defaults. Additionally, all of the fields are optional.

Lucio suggested using `#[serde(defaults = "default_batch")]` in each sink to set the values of both fields of the batch (for example). However, if only one of the fields is present in the config, the default is not used for either, so that won't work. See https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1252ab40064efc315c1321e909d1efaa

I had written a custom `unwrap_or` function for the struct that would take the defaults as a parameter. It's a little clunky, but it has the added benefit of being able to output a new struct that has the seconds parameters converted into `Duration`.

Lucio however further suggested that a custom deserializer might be an option. This seems overkill just for setting defaults on a struct, but I might not be understanding what he is suggesting.

What do you think?

**Comment by lukesteensen** [comment]
I would probably go in the same direction it sounds like you are. We could have a raw version of each struct where all fields are optional and more stringly-typed, and then a "validated" version where everything is filled in and properly typed. 

Something along the lines of:

```rust
struct RawOpts {
    foo: Option<String>,
}

struct Opts {
    foo: Duration,
}

impl RawOpts {
    fn merge(self, defaults: Opts) -> Opts {
        ...
    }
}
```

I don't think that's any more boilerplate than custom deserialization, and it's quite a bit simpler. I actually wouldn't be surprised if there were some little proc macro crate that generated this type of pattern somewhere.

**Comment by binarylogic** [comment]
@bruceg is there anything left on this issue? Can we close it?

**Comment by lukesteensen** [comment]
All that's left is to unflatten.
