### ISSUE TITLE
Update docs to not indicate that we do dynamic encoding

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#1117]
I've found two places so far in the docs that state that we do dynamic encoding. We no longer do this but I am not sure where this template is being added.

- https://docs.vector.dev/usage/configuration/sinks/aws_s3#dynamic-encoding
- https://docs.vector.dev/usage/configuration/sinks/file#dynamic-encoding

**Comment by binarylogic** [comment]
Did you look at the latest version of the docs? I'm pretty sure we already removed this.

**Comment by LucioFranco** [comment]
@binarylogic I don't see them anymore in the generated docs in the repo but they are on the live docs. 👍 I assume next tag they will go away.
