### ISSUE TITLE
Retries in S3 sink can get new key names

### ISSUE THREAD

**Issue by lukesteensen** [timberio/vector#1127]
Object key names created by the S3 sink can incorporate a timestamp that means they are not generated deterministically from the batch content. This is fine in isolation but causes a problem when combined with the fact that keys are regenerated when a request retries.

If a request is made to S3 to write a given batch, it will very occasionally return an error when the write actually succeeded. This will lead to a retry, which can cause a new key to be generated. If that retry also succeeds, we will have two objects in S3 with different keys but identical content.

The proper behavior here would be to ensure that all retries are sending identical requests to S3, including the key. This would make our retries idempotent and remove this possibility for duplicate data.

**Comment by lukesteensen** [comment]
I don't think we'd have to touch batching. We could split the S3 service in two, one that generates the request and another that sends it, and then only wrap the inner sender with the retry service.

**Comment by LucioFranco** [comment]
@lukesteensen actually what would be really nice would be to write a middleware `Map` service that we could then place at the top of the service stack.

```rust
        let svc = ServiceBuilder::new()
			.map(create_request) 
            .concurrency_limit(in_flight_limit)
            .rate_limit(rate_limit_num, Duration::from_secs(rate_limit_duration))
            .retry(policy)
            .timeout(Duration::from_secs(timeout))
            .service(s3);

fn create_request(req: PartitionInnerBuffer<Vec<u8>, Bytes>) -> PutObjectRequest {
	// We could prob fold generate key into this
	// etc
}
```

This will ensure the key generation happens before it hits the retry service.

**Comment by LucioFranco** [comment]
I would also love to have this in `tower` itself, we could PR it there and I can publish a new version ASAP.

**Comment by lukesteensen** [comment]
Would that basically be a `service_fn`/`Layer` combo thing? Seems a little funky to "map" a service, but yeah that's the idea.

**Comment by LucioFranco** [comment]
it would be a service like and its layer would just be a wrapper around the map fn

```rust
impl<S, R1, R2, F> Service<R1> for Map<F> 
where
	S: Service<R2>,
	F: Fn(R1) -> R2,
{ .. }
``` 

I think this should work with the service builder since it doesnt have any specific bounds on requests per layer.

Some prior art from linkerd:

https://github.com/linkerd/linkerd2-proxy/blob/d213c1373f1f5ec479a59a0a388d4373dcb3cde4/linkerd/stack/src/map_target.rs

**Comment by binarylogic** [comment]
@LucioFranco I've assigned this to you. This is high-ish priority. Thanks.

**Comment by JeanMertz** [comment]
Hey @LucioFranco, I was getting familiar with Vector and saw this issue, given that I've wanted a reason to get familiar with Tower for a while, I figured I'd give that `Map` service a try (https://github.com/tower-rs/tower/pull/365).

If you've already been working on this offline, or had a different approach in mind, no worries, just ignore my PR, it was mostly to get familiar with the request/response flow in Tower in the first place.

**Comment by LucioFranco** [comment]
@JeanMertz hi! I opened a PR against vector with it for now. Tower for the moment will be influx while we update it to `std::future::Future`.

**Comment by JeanMertz** [comment]
Ah yes, I see the PR now. Awesome. I totally missed that one 👍
