### ISSUE TITLE
Follow Debian package description guidelines for Debian package

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#1131]
Currently the description of Vector Debian package includes the raw Markdown content of `README.md` file, which is long and hard to read on a terminal screen when doing something like `apt-cache show vector`.

There are [guidelines for Debian package descriptions](https://www.debian.org/doc/debian-policy/ch-binary.html#the-description-of-a-package), which recommend to set the first line to a single-line description and the rest of the description to a few paragraphs giving an idea of what the package is doing.

In order to not have duplicated documentation strings scattered over the repository, I propose to

* Read the description of Vector's GitHub repository during the build and use it as a single-line description for the Debian package. Currently it is
    ```
    A High-Performance, Logs, Metrics, & Events Router
    ```
* Automatically extract plain-text introduction from `README.md` and use it as the extended description. It can be extracted using [`cmark-gfm`](https://packages.debian.org/buster/cmark-gfm) and `sed` as
    ```sh
    cmark-gfm README.md --to commonmark | sed '/^## /Q' | cmark-gfm --to plaintext | fmt -uw 80
    ````
    which currently results into
    ```
    Vector is a high-performance observability data router. It makes collecting,
    transforming, and sending logs, metrics, and events easy. It decouples data
    collection & routing from your services, giving you control and data ownership,
    among many other benefits.

    Built in Rust, Vector places high-value on performance, correctness,
    and operator friendliness. It compiles to a single static binary and is
    designed to be deployed across your entire infrastructure, serving both as
    a light-weight agent and a highly efficient service, making the process of
    getting data from A to B simple and unified.
    ```

**Comment by binarylogic** [comment]
👍 works for me.

> Read the description of Vector's GitHub repository during the build and use it as a single-line description for the Debian package. Currently it is 

We also have this in the `Cargo.toml` file, if that makes it easier. That should avoid a network request.

**Comment by a-rodin** [comment]
Closed in https://github.com/timberio/vector/pull/1247.
