### ISSUE TITLE
Cleanup remaining debt around explicit/implicit structuring

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1143]
Now that https://github.com/timberio/vector/pull/894 is merged, to my knowledge, we no longer require the [`explicit` field](https://github.com/timberio/vector/blob/d9550711ebcc3bd1033b4985efb3af469e8a4384/src/event/mod.rs#L175) on log vents. If this is actually true, we should remove it and consider removing the entire concept of implicit/explicit field insertions.

**Comment by MOZGIII** [comment]
I was quite confused with the `explicit` flag being there, and I don't understand the semantics of it. I looked into the #894, but still don't get the purpose of the flag, so I'd say there's no reason not to get rid of it - but take it with a grain of salt, since I didn't read the whole codebase yet. :)

**Comment by lukesteensen** [comment]
The original intent of the flag was to help us match users' expectations in which fields would show up by default in sink outputs.

For example, if we added a `host` field as part of the `tcp` source automatically, that wouldn't necessarily map to a user expecting their events to now be "structured" and be output with multiple fields vs the raw data. On the other hand, if the user configured a regex parser that extracted a number of fields, they'd likely expect those fields to be represented in the output.

It was a heuristic and not a terribly good one. There were plenty of situations that would still lead to unexpected output, and worse, it would make the output format potentially differ across events in the same pipeline. We decided it was strictly better to require users to specify the encoding they wanted for each sink.

I was surprised to see the field still sticking around, as I thought we'd removed all traces by now. We should definitely do so, as it no longer serves a purpose beyond confusing new contributors.

**Comment by MOZGIII** [comment]
I'm looking forward to it. For now, I have to do this to ensure that hidden `explicit` flag is preserved: https://github.com/timberio/vector/pull/1504/commits/2911419ed75c41366721148f708cb89865653703

**Comment by binarylogic** [comment]
I'm not sure if I fully follow. But are you requesting to re-assign this issue to yourself? @a-rodin do you have any objections to that? I want to make sure that won't mess with the work you're doing in https://github.com/timberio/vector/milestone/23 .

**Comment by MOZGIII** [comment]
Well, I didn't mean to request to reassign it, since I'm busy with the `merge` feature. Although, I don't mind taking care of this too afterwards :smile:

**Comment by binarylogic** [comment]
No, that's fine. I just wanted to clarify. I'll leave it assigned to @a-rodin.
