### ISSUE TITLE
Show messages about unused components as warnings instead of errors

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#1182]
Currently messages about components without outputs are shown in Vector's log as errors:

```Nov 14 14:29:02.096 ERROR vector::topology: Configuration warning: Transform "tf2" has no outputs```

In my opinion, it should rather be a warning instead of an error. The case of unused components seems to me similar to unused variables, which are shown as warnings in Rust.

**Comment by binarylogic** [comment]
Noting, #1519 might have been resolved with this warning.

**Comment by Jeffail** [comment]
Closing as we have this covered https://github.com/timberio/vector/issues/414
