### ISSUE TITLE
Support ARMv8

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1194]
This is something I've noticed looking at various IOT documentation. This appears to be a new architecture, and I do not see anything about it in the Rust documentation. But since we support ARMv7 I'm wondering if this will be much easier.

**Comment by a-rodin** [comment]
In Rust ARMv8 architecture is called AArch64, so this is a duplicate of #1190. Support for it is implemented in #1193 and is ready to be merged.

**Comment by binarylogic** [comment]
Nice! I'll close then.
