### ISSUE TITLE
New `metric_to_log` transform

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1199]
I can see use cases where users would want to ingest raw metric data into an events/log database. Providing a simple way for users to convert metric to log data would allow them to use these storages. For example, sending metrics data to S3 for archival and then using Athena to query it.

**Comment by thethomp** [comment]
I can confirm my team has use cases for this, and would love to see this feature come to life :)

**Comment by binarylogic** [comment]
Hi @thethomp, I agree. I've assigned this. We'll likely get to it next week. Thanks for the feedback.

**Comment by drunkirishcoder** [comment]
We have a use case that needs this. If no one is working on it, I wouldn't mind giving this a try.

**Comment by binarylogic** [comment]
@drunkirishcoder please do. Feel free to hop in our chat if you have any questions.

**Comment by drunkirishcoder** [comment]
any thoughts on the log document format? or just let serde serialize the metric as is?
