### ISSUE TITLE
json_parser ... arrays?

### ISSUE THREAD

**Issue by cetanu** [timberio/vector#1204]
Hello,

I have a TCP source that is sending data like:

```
[{"hello": {"name": "world"}, {"hello": {"name": "vector"}]
```

Is the json_parser capable of parsing this into a field?

I just want the log to end up something like:

```
{"message": [{"hello": {"name": "world"}, {"hello": {"name": "vector"}]}
```

So far I don't seem to get any logs coming through

**Comment by lukesteensen** [comment]
Unfortunately, our internal data model doesn't currently support arrays and the json parser transform currently assumes that the parsed messages will be objects.

We are working to expand our data model (#704), and once that's done we will be making a pass through our transforms to remove these kinds of limitations.

**Comment by cetanu** [comment]
Sounds good, I was able to remove the brackets using lua for my particular use-case which I find acceptable. I will close this in the meantime
