### ISSUE TITLE
http sink encoding - json vs ndjson

### ISSUE THREAD

**Issue by cetanu** [timberio/vector#1209]
Hello

I notice that the http sink has only ndjson/text encodings available, and in particular that when using ndjson, vector adds a `content-type` header with the value `application/x-ndjson`

This produces some undesired behavior in my environment, where particular applications don't expect or correctly handle this header, or newline-delimited JSON

Is it worth me making a PR to add an option for vanilla JSON?

**Comment by lukesteensen** [comment]
We actually have a PR in progress to add exactly that (#1174).

**Comment by cetanu** [comment]
Ah, nice. Apologies for not searching 😓

**Comment by lukesteensen** [comment]
No worries! Thanks for letting us know that it's something people want :smile:
