### ISSUE TITLE
Allow unvendoring dependencies

### ISSUE THREAD

**Issue by thoughtpolice** [timberio/vector#1238]
Recent changes to 0.6.0 have caused `openssl-sys` to start vendoring a copy of OpenSSL itself. This is now unilateral.

I would like to relieve this restriction, and allow a feature flag to use the system openssl when depending on the `openssl` crate, if possible.

The reasoning is ultimately quite simple: I maintain the Vector package for [NixOS](https://nixos.org), and these changes cause a bundled copy of OpenSSL to be used, which we *generally* try to avoid, especially for security critical and widely used libraries. Now, NixOS makes it very *easy* to safely vendor dependencies, so that isn't the problem; it's more a one of logistics.

Notably, our version of OpenSSL has patches/enhancements to better fit in with our environment, such as patches to fix certificate store locations, etc. And also, NixOS has very austere build requirements, so many packages won't build without some help (we patch them to remove often implicit, undocumented assumptions, and OpenSSL, rdkafka, etc are no different). Therefore, for most purposes, it really *is* technically -- not just philosophically -- important to use our own versions a lot of the time.

I understand the motivation to make Vector easier to compile on more platforms vis-a-vis vendoring. I'm completely happy if an `unvendored` feature could be added, off by default, that would allow system-wide libraries to be used, if possible, by distro maintainers such as myself. At the moment, I currently have a patch that simply turns off the `vendored` flag to the openssl crate (and I speculate I will not be the last maintainer to need this.)

**Comment by lukesteensen** [comment]
Makes sense to me! We really appreciate the work to maintain the Nix package and definitely don't want to make that more difficult than it needs to be.

@a-rodin Do you think it'd be much work to add such a feature?

**Comment by a-rodin** [comment]
Not sure that we can add a feature for _unvendoring_ OpenSSL due to way Cargo features work. However, _vendoring_ could be easily made optional by exposing `openssl/vendored` feature, which can still be enabled by default. https://github.com/timberio/vector/pull/1239 does it.
