### ISSUE TITLE
Re-enable buffering tests on all platforms

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#1253]
Currently this test is enabled only on Unix platforms (see https://github.com/timberio/vector/pull/1205#issuecomment-557081933):

https://github.com/timberio/vector/blob/f9c486ce4abcd77cf61ddc7fe2fadb4aeae3b806/tests/buffering.rs#L13-L88 

The problem with it is that the first 10 messages which are stored to the disk buffer are consumed, but the last 10 messages are lost, so this assertion fails: https://github.com/timberio/vector/blob/f9c486ce4abcd77cf61ddc7fe2fadb4aeae3b806/tests/buffering.rs#L87

@LucioFranco suggested in https://github.com/timberio/vector/pull/1219#issuecomment-558161354 that resolving some futures on Windows might require reactors or timers. It is possible that problems with this test have the same nature, however I was not able to isolate them because `rt::block_on` call is there in this case.

**Comment by LucioFranco** [comment]
@a-rodin I don't think this one is related to that panic. This may seem like either a difference in the leveldb implementation? I am not sure would have to inspect the source a bit more. But this should _not_ be related to a missing reactor/timer issue.

**Comment by a-rodin** [comment]
@LucioFranco LevelDB seems to be working as it should because all buffered messages are delivered. The problem is with subsequent messages, which are sent here

https://github.com/timberio/vector/blob/f9c486ce4abcd77cf61ddc7fe2fadb4aeae3b806/tests/buffering.rs#L74-L76

They are not delivered. That is what makes me think that the problem is somehow related to Tokio or maybe TCP source.

**Comment by LucioFranco** [comment]
The root cause of this issue turns out to be a slow clean up of an already used fd on windows when rebinding the second topology for this test.

```
Jan 03 16:10:46.104 ERROR source{name=in type=tcp}: vector::sources::util::tcp: Failed to bind to listener socket: Only one usage of each socket address (protocol/network address/port) is normally permitted. (os error 10048)
Jan 03 16:10:46.104 ERROR vector::topology: Unhandled error

```

**Comment by LucioFranco** [comment]
#1474 now enables all buffering tests on windows.
