### ISSUE TITLE
Include a comment indicating that a file is auto-generated to auto-generated files

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#1256]
It would be nice to have a comment in the beginning of each of auto-generated files in the repository saying something like

```
This file is auto-generated from <filename.erb>, do not edit it by hand.
```

These notices could have been particularly helpful for new contributors.

However, it looks like the largest difficulty with adding it is automatically choosing comment syntax, which varies over different file types.

**Comment by withnuchu** [comment]
[file-tag: code-generated-file-0e476c4d-65fd-4ff9-b65c-09a2bc7fb2a8]
