### ISSUE TITLE
Tests involving crash handling fail in CI

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#1258]
Tests `test_source_panic`/`test_sink_panic` and `test_source_error`/`test_sink_error` sometimes fail in CI, example: https://app.circleci.com/jobs/github/timberio/vector/42481.

It looks like the problem appeared after upgrade to Rust 1.39, but it is not clear what causes it yet.

Might be related to https://github.com/timberio/vector/issues/1257.

**Comment by binarylogic** [comment]
Closing since we have not seen this lately

**Comment by binarylogic** [comment]
Reopening, `test_source_error` is still failing:

https://circleci.com/gh/timberio/vector/94083?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
