### ISSUE TITLE
Elasticsearch docs have incorrect option names

### ISSUE THREAD

**Issue by lukesteensen** [timberio/vector#1262]
The actual ES config options are given here:

https://github.com/timberio/vector/blob/57434aa05893d89300cee34f7aa2be7c6be7405b/src/sinks/elasticsearch.rs#L48-L54

The options listed in the config are here:

https://github.com/timberio/vector/blob/57434aa05893d89300cee34f7aa2be7c6be7405b/.meta/sinks/elasticsearch.toml#L12-L17

There are four that do not match, but it seems that the docs generation system assumes these options are the same for all sinks and it's not clear how to correct the docs for this sink alone.

**Comment by binarylogic** [comment]
Got it. @LucioFranco any idea why this sink deviates? @bruceg, https://github.com/timberio/vector/pull/1187 should fix this, correct?

**Comment by LucioFranco** [comment]
Looks like the docs are just wrong there? They are all prefixed with `request_*` and #1187 shoudln't have any user facing changes.

**Comment by lukesteensen** [comment]
Yeah, as far as I can tell they've always been named this way and the docs have always been wrong. It could be different just because it was the first sink where we introduced these options.
