### ISSUE TITLE
Metric encoding in the `console` sink

### ISSUE THREAD

**Issue by loony-bean** [timberio/vector#1266]
The `encoding.codec` config parameter (Text/Json) of `console` sink is required but has no effect for metrics.

I wander if we could utilise this parameter somehow? @lukesteensen maybe you'll have some ideas.

**Comment by binarylogic** [comment]
Yeah, I'm curious if could adopt a text-based format. Really the `text` format is designed for humans, so anything that describes the metric in a readable fashion is fine with me.

**Comment by lukesteensen** [comment]
Yes, the idea of `Text` is just something that humans can easily read. With logs, printing out the `message` field is an easy way to get that, but it wasn't as obvious for metrics since there is no real equivalent. We could come up with an easily readable text representation of them, but I'm not sure how much benefit there would be over JSON.

**Comment by lukesteensen** [comment]
It may actually be worth reconsidering the log side of things as well, since there are more cases now where the `message` field will be empty (JSON inputs, parsing where we drop the original field, etc).

**Comment by loony-bean** [comment]
Hmm, maybe we could add `message` field into metrics?

We'll keep the original `glork:320|ms` (or `rpc_duration_seconds_count{service="a"} 2693`) form of the metrics for anyone interested downstream.

Also it will make out log and metric data models a bit closer.

**Comment by lukesteensen** [comment]
We could keep the raw version, but even then I'm not sure we'd always end up with something human-readable. It would depend on the source and it might be more confusing if different metrics would come out formatted differently.

**Comment by loony-bean** [comment]
I believe convenient text format with good UX (with ability to `grep`, etc) should look a lot like Prometheus exposition format, but enhanced with Vector features like incremental metrics. Unfortunately such format does not exist, so I think we can  use some mechanical json -> yaml conversion for now, just not to overcomplicate.

**Comment by binarylogic** [comment]
@bruceg, I'm assigning this to you since I think it's a good tool to have while you're working on host-level metrics. It'll also get your familiar with the metrics data model.
