### ISSUE TITLE
Add SASL authentication to kafka_sink

### ISSUE THREAD

**Issue by 0x003e** [timberio/vector#1277]
Hello,

Some people need SASL Authentification on Kafka:

  * feat(kafka sink): Add support for SASL 
  * docs: https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md
   >
security.protocol | * | plaintext, ssl, **sasl_plaintext**, **sasl_ssl** | plaintext | high | Protocol used to communicate with brokers. Type: enum value
-- | -- | -- | -- | -- | --

https://github.com/0x003e/vector/commit/06082930aae5dc1c689c0fe7a5e1b500cd49c896#diff-3380bc35763ec3d083d279f313dfa4f4R135

**Comment by binarylogic** [comment]
Added in https://github.com/timberio/vector/pull/2897.
