### ISSUE TITLE
Redo the "Getting Started" guide

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1280]
Our [Getting Started guide](https://vector.dev/docs/setup/guides/getting-started) is the most important guide since we use it as a Call-To-Action and a means to onboard users. I'd like to redo this guide because it was initially rushed when we were launching Vector; I'm not sure it's still accurate or even works.

The goal of this guide is to demonstrate Vector working as easily and quickly as possible. We want to overemphasize the simplicity of setting up Vector and leave them with the fundamentals necessary to perform their own tests.

### Requirements

- [ ] It should introduce the user to the basic Vector concepts (sources, transforms, sinks)
- [ ] It should introduce the user to the Vector data model and how it changes as it flows through Vector.
- [ ] Input during the test should be manually driven to allow for different input values to be tested.
- [ ] Ideally, the guide would use the `console` sink in some way so that the user knows how to debug/print data as it flows through Vector. (I wish there was an easier/better way to do this).
- [ ] Should end with a "next steps" section that directs the user to other guides or sections.
- [ ] Should includes a "Get help" section with community resources (chat, github, troubleshooting guide, etc).

### Ideas

1. Should this guide use Docker since it sidesteps installation and is simpler?
2. The input should ideally be user-driven since that'll allow them to try out different input.
3. Is there anything we can do to further improve this guide? Illustrations, special format or styling, etc. I definitely do not want to overthink this, but I think it's worth taking this one step further given how front-and-center were putting it.
4. How about a Video? If this is too simple then it might not be worth it, but I like it just for the human aspect and as an opportunity to introduce them to the basic concepts.

### Inspiration

1.  https://ksqldb.io/quickstart.html
    * I like the step-by-step / column format. It makes the guide feel less daunting than a wall of text.
2.  https://ksqldb.io/overview.html
    * I like the video.
3.  https://docs.mongodb.com/manual/tutorial/getting-started/
    * The interactive shell / demo is cool.
4. https://trello.com/en-US/guide
    * This is an interesting format as it lets the user jump through guides as they progress. I could see us linking to a similar page with our guides on it (Vector Concepts, Your first pipeline, Parsing, Debugging, etc).

**Comment by Jeffail** [comment]
Keeping this open for a little longer. I think the current rewrite is enough and we should try not to bloat it with more information, but some things remaining to consider:

- Make a video version and embed it at the top as an alternative to having to read
- Add some social links at the bottom

The next guide linked at the bottom takes users to unit tests, which given that's quite an advanced feature we ought to consider swapping it with troubleshooting (which can be made to give a shout out to unit tests). I don't think this is worth doing until it's polished for new users (https://github.com/timberio/vector/issues/1300 would help).
