### ISSUE TITLE
Enhancement: validate sub command defaults to standard configuration path

### ISSUE THREAD

**Issue by danpalmer** [timberio/vector#1310]
I just ran `vector validate` and expected to see some output, but everything ran successfully, no output. All good!

Unfortunately I realised a few minutes later that the config was indeed invalid, and that `vector validate` by default will do nothing.

I think a more useful default, and one that may be safer with newer users, would be to default to the default configuration path if none is provided. I don't believe there's a use-case for running validate against no configuration files, so this seems like it would be beneficial.

**Comment by Jeffail** [comment]
Hey @danpalmer, thanks for raising this. The `test` subcommand works the same way so I'll update that at the same time.

The original intent was for zero arguments to cause an error. I think it's also reasonable to target the default config, and given that was your first intuition let's go with that.

Also if you have any other thoughts about these new subcommands I'd love to hear them.

**Comment by danpalmer** [comment]
The idea of erroring with no arguments sounds like a good option too. 

I think there’s some nicer ergonomics to behaving in the same was as the main server command with respect to config files, same argument name, same error cases, etc. 

I don’t feel strongly though!
