### ISSUE TITLE
Bug: "datadog" sink is documented as "datadog_metrics"

### ISSUE THREAD

**Issue by danpalmer** [timberio/vector#1311]
In all the documentation I've seen, and in the in-progress 0.6.0 changelog, I've seen this new sink referred to as `datadog_metrics`, however when running `vector validate` I get the following output:

```
Dec 04 16:34:48.239 ERROR vector: Configuration error: unknown variant `datadog_metrics`, expected one of `aws_cloudwatch_logs`, `aws_cloudwatch_metrics`, `aws_kinesis_streams`, `aws_s3`, `blackhole`, `clickhouse`, `console`, `datadog`, `elasticsearch`, `file`, `http`, `kafka`, `prometheus`, `splunk_hec`, `statsd`, `tcp`, `vector` for key `sinks.datadog_out`
```

This suggests that it should be `datadog` instead.

**Comment by binarylogic** [comment]
@loony-bean do you mind renaming this accordingly? Thanks.
