### ISSUE TITLE
timestamp is null for statsd

### ISSUE THREAD

**Issue by jogster** [timberio/vector#1347]
Hi, I cannot figure out how to set the timestamp - I am stuck and can't move forward...

# Input data
echo "latency:3.1|h|#name:foo,category:bar" | nc -w 1 -u 127.0.0.1 8126

# Input data
Dec 10 20:04:48.745  INFO source{name="statsd"}: vector::sources::statsd: listening. addr=127.0.0.1:8126 type="udp"
{"type":"histogram","name":"latency","val":3.1,"sample_rate":1,"timestamp":null,"tags":{"name":"foo","category":"bar"}}

# vector.toml:
[sources.statsd]
  type = "statsd"
  address = "127.0.0.1:8126"
  timestamp = "2019-11-01T21:15:47+00:00"
[sinks.out]
  inputs = ["statsd"]
  type   = "console"

**Comment by loony-bean** [comment]
Hi @jogster! Thanks for input. Could you help me understand the use case better?

StatsD protocol [is designed](https://github.com/statsd/statsd/issues/279) to not carry timestamp information, and `null` is meant to be interpreted by the downstream consumers as now() (time of arrival).

For instance, in Datadog sink `null` is replaced by now() before data is sent out to the API, and in CloudWatch sink `null` is simply passed to the API because the API does the work for us:
> If you do not provide a time stamp, CloudWatch creates a time stamp for you based on the time the data point was received.

**Comment by binarylogic** [comment]
Thanks @loony-bean . Before we close this I'd like to include that in the `statsd` sink documentation.

**Comment by jogster** [comment]
hi @loony-bean thanks for the quick answer. Is there any reason to include the timestamp on the metric description at all? I am hoping to use the prometheus sink and save the data into victoriametrics. Would the prometheus sink add timestamps?

In that case does it make sense for me to add a timestamp as a tag of my own if i ever need the origination time?

**Comment by loony-bean** [comment]
@jogster As far as I'm concerned, Prometheus does not support client-side timestamps. There's a [discussion](https://github.com/prometheus/node_exporter/pull/769#issuecomment-380980122) around this topic in the community. 

So I assume that VictoriaMetrics might be able to put timestamps during Prometheus scraping (/cc @valyala)

Using tags for storing volatile information such as timestamps is not recommended. Usually tags store service/region/environment information, for instance to provide an aggregated view on what's happening in some service across all hosts or inside a particular group of hosts.

Are you working with historical data having some past events?

**Comment by jogster** [comment]
@loony-bean - that is a very good point - I do not need timestamps. I don't have historical data so auto-generated timstamps are is fine.

I have got the prometheus sink working fine - originally I thought VictoriaMetrics would be able to scrape this Sink, but it appears that it needs metrics to be written to it and can be driven through the prometheus_write mechanism.  I ended up running a prometheus server and will have to implement a write from that to VictoriaMetrics.

Is there any way for the prometheus sink to output as a prometheus write?

**Comment by valyala** [comment]
> So I assume that VictoriaMetrics might be able to put timestamps during Prometheus scraping

VictoriaMetrics doesn't scrape Prometheus. Instead, Prometheus sends scraped data to VictoriaMetrics via [remote_write API](https://prometheus.io/docs/prometheus/latest/storage/#remote-storage-integrations). This is basically snappy-compressed protobuf messages over http. See https://github.com/prometheus/prometheus/tree/master/prompb .

> Is there any way for the prometheus sink to output as a prometheus write?

I think the following feature request should cover this case - https://github.com/timberio/vector/issues/1343 .

**Comment by loony-bean** [comment]
@valyala This is very helpful, thank you!
