### ISSUE TITLE
Requesting feedback for v0.6.0

### ISSUE THREAD

**Issue by Jeffail** [timberio/vector#1380]
Vector v0.6.0 came with [many new goodies](https://vector.dev/releases/0.6.0), if you're using, intending to use, or were deterred from using any of these features then we'd love to hear your general thoughts and feedback in the comments.

We're especially interested in hearing about your experiences with the new subcommands `validate`, `generate`, `list` and `test`. Some of these commands are experimental and your feedback can help us steer their future direction.

**Comment by binarylogic** [comment]
Closing this since we're about to release 0.7.0
