### ISSUE TITLE
New `nats` sink

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1399]
NATS is an open-source messaging system in CNCF. I'd like to create a sink that flushes logs events to a NATS system.

**Comment by binarylogic** [comment]
Noting, @derekcollison [mentioned](https://twitter.com/derekcollison/status/1208042607328350209?s=20) that Nats will be creating an official Rust client. We should take that into consideration before starting development.

**Comment by derekcollison** [comment]
Yes we will be. There are some good ones now too that you can use in the interim.

**Comment by cristaloleg** [comment]
Any updates one this? Especially after an official release 😉 https://github.com/nats-io/nats.rs

**Comment by derekcollison** [comment]
The rust client is quickly becoming a top tier client.

**Comment by lukesteensen** [comment]
We would love to have both a source and sink for NATS, but it's unfortunately not currently a priority for any of our team members.

We will get there eventually, but I'd definitely encourage anyone interested to open a PR in the meantime! We're always happy to help guide new contributors.

**Comment by erhlee-bird** [comment]
Hey all, I've started a pull request on my current stab at making a NATS sink. Any oversight and feedback would be greatly appreciated!
