### ISSUE TITLE
`splunk_hec` source rename `line` field to `message`

### ISSUE THREAD

**Issue by ktff** [timberio/vector#1409]
### Description
When `splunk_hec` source receives event as a `string` it will emit it under `message` field, and it is the same case when using `raw` mode. But when it receives event as an `json` object it will just add it to Event as it is. This causes for the message to be added under different named field. In for us most important case of Docker/ECS , it will be emitted under `line` field.

Renaming `line` to `message` filed would make `splunk_hec` source behave more consistent.

### Behavior
When `splunk_hec` source receives event as an `json` object, rename field `line` to `message`.

**Comment by binarylogic** [comment]
@ktff is this also the case for any of the fields list here?

https://vector.dev/docs/about/data-model/log/#schema

**Comment by ktff** [comment]
@binarylogic good question. 

Currently

|   	| Raw | Inline | Json	|
|---	|---	|---	|---	|
| `message` | ✓  | ✓  |  x 	|
| `host` | o	| o 	| o  	|
| `timestamp` | x  | o	| o   	|

✓- ok
x - not present
o - optional, client doesn't need to provide it for it to be a valid `splunk` log

To answer your question, no, but ,since we are already going beyond what regular splunk hec server does, we could do this better.

`message` can be enhanced with the mentioned.

`host`, we can't do to much about it.

 `timestamp`, we could add our own timestamp when it isn't present.

So if we change `message` and  `timestamp` accordingly, we would have

|   	| Raw | Inline | Json	|
|---	|---	|---	|---	|
| `message` | ✓  | ✓  |  ✓ 	|
| `host` | o	| o 	| o  	|
| `timestamp` | ✓  | ✓	| ✓   	|

Although Docker/ECS actually only use Inline and Json formats, and always provide `timestamp` and `host`, I am still for changing `timestamp` for uniformity reasons. 

@binarylogic so if you are for it, I'll open a separate issue for changing `timestamp`.

**Comment by binarylogic** [comment]
Thanks! I thought `timestamp` was a required field. So yes, we should set `timestamp` if it is not present.

Re: `host`, we should also set that to the upstream client, if possible. Do you know if the default log format coming from ECS will provide this?

**Comment by ktff** [comment]
Ok, I'll open a separate issue for `timestamp`.

So, although Splunk HEC api doesn't require neither `host` nor `timestamp` to be specified, Docker/ECS will provide both `host` and `timestamp`. I can say this because Docker is so serious in being it so that users can't configure `splunk log driver` in ways that would change that. For example, although  `splunk log driver` can be configured to use `raw` mode, in actuality it is mapped to `inline` mode, while `inline` and `json` configuration both map to `json` mode.
