### ISSUE TITLE
Add `compression` option to relevant sinks

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1411]
This can significantly increase throughput. I decided to open a single issue because I have a feeling code will be shared across these sinks. Note, the `aws_s3` sink currently implements compression, so maybe we can reuse that code?

## Requirements

- [ ] Add `compression` (`gzip`) option to the `aws_kinesis_streams` sink
- [ ] Add `compression` (`gzip`) option to the `aws_kinesis_firehose` sink
- [ ] Add `compression` (`gzip`) option to the `http` sink
- [ ] Add `compression` (`gzip`) option to the `elasticsearch` sink
- [ ] Add `compression` (`gzip`) option to the `kafka` sink

Bonus points:

- [ ] Additionally support the `lz4` compression format.

**Comment by MarkusTeufelberger** [comment]
Also nice to have would be compression support for the `file` sink and `zstd` compression (including the ability to set compression levels). Bonus points for handling size batching after compression.

**Comment by fanatid** [comment]
`aws_kinesis_streams` and `aws_kinesis_firehose` should able handle `gzip` with rusoto starting from `0.43.0-beta.1` (currently vector use `0.41.0`).
From [CHANGELOG](https://github.com/rusoto/rusoto/blob/master/CHANGELOG.md): 
`Encode request payload optionally with Gzip`.
But on migrating on tokio@0.2 encode was removed, so I created PR with fix: https://github.com/rusoto/rusoto/pull/1757

`http`, `elasticsearch` and `kafka` already support `gzip`.
