### ISSUE TITLE
Windows build steps are failing

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1412]
It seems like the `core` crate is no longer available for Windows?

```
error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-pc-windows-msvc` target may not be installed
```

For example:

https://circleci.com/gh/timberio/vector/63431?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by a-rodin** [comment]
It looks like `rustup` init script changed and installs target`x86_64-pc-windows-gnu` instead of `x86_64-pc-windows-msvc` by default. I’m going to set the target explicitly to fix this.
