### ISSUE TITLE
Ensure that helper scripts have consistent formatting using a CI check

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#1423]
It would be nice to have a CI check which would ensure that our helper scripts (`.sh`, `.rb`, `.js`, etc) have consistent formatting rules, namely:

* indentation type;
* tab size;
* line ending;
* other rules, possibly file-specific.

See also https://github.com/timberio/vector/pull/1421. 

If we proceed with this, we need to agree about the actual rules and the tools for checking them first.

**Comment by binarylogic** [comment]
Closed in https://github.com/timberio/vector/pull/2482
