### ISSUE TITLE
TCP and vector sinks don't detect disconnects

### ISSUE THREAD

**Issue by anton-ryzhov** [timberio/vector#1429]
Currently TCP and vector sinks only writes data into socket and never reads. When remote side (the receiver) closes the connection it sends FIN which could be "read" by the sender (sink) to detect graceful disconnection.

Because of that some logs are sent to closed the socket and got lost:
1. Remote side closes the connection (sends FIN).
2. Sink sends next portion of data, this data is written to the outgoing buffer, `send` syscall ends with success. Vector removes this data from the buffer.
3. Data is sent to remote side by the OS, remote side responds with RST in best case.
4. Sink sends next portion of data, but OS now knows that socket is closed. So `send` ends with `EPIPE`, vector finally detects disconnection.

By reading the socket you can detect disconnection much faster, on the 1 step. This will decrease probability of losing data and will make connections handling more responsive.

Of course only [acknowledgements](https://github.com/timberio/vector/issues/492) could make delivery guaranteed.

TCP keepalive also can improve connection tracking.

**Comment by binarylogic** [comment]
Thanks @anton-ryzhov, I agree, we'll see if we can implement this.
