### ISSUE TITLE
Easy to build sinks for services

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1434]
Following up on https://github.com/timberio/vector/issues/1260#issuecomment-566284159, I'd like to provide a way to quickly and easily build sinks for a variety of sources. These sinks might wrap the `http` sink, the `socket` sink, or the `syslog` sink. The advantage over configuring these sinks directly is:

1. We can manage rate-limit, batch sizes, etc. Making it easier to get setup.
2. Partnership opportunities, co-marketing, etc.

Before we start, I'd like to create a light specification so we can agree on how this will work.

## Follow-Up Tasks

- [ ] Redefine the `newrelic_logs` sink to use this?
- [x] Close #1000

**Comment by LucioFranco** [comment]
This is done, here is the next step https://github.com/timberio/vector/issues/1659 that describes what sinks are left to upgrade to our new `HttpSink` setup.
