### ISSUE TITLE
Consider ordered data structure for metric tags

### ISSUE THREAD

**Issue by loony-bean** [timberio/vector#1439]
Currently metric tags are stored as `<HashMap<String, String>`, because most of the time the order of tags is not important. However order becomes crucial when metrics are serialised, deduplicated, or merged, and there are already multiple [places](https://github.com/timberio/vector/pull/1264#discussion_r358527199) where we have to explicitly copy and sort tags.

It would be good to consider some alternatives to`HashMap` such as `IndexMap` or `BTreeMap` or a simple `Vec` to avoid extra work when working with tags.

**Comment by a-rodin** [comment]
This seems to be closely related to https://github.com/timberio/vector/issues/1428.

**Comment by a-rodin** [comment]
As noted by @lukesteensen, we need to chose `BTreeMap` over `IndexedMap` here because it would ensure that the deduplication happens even if the tags were inserted in different order.

**Comment by loony-bean** [comment]
JFYI
One interesting feature of StatsD protocol is that it allows something like multi-value tags. Reportedly this also works in DataDog, and I'm seeing this in tests (like [here](https://github.com/DataDog/datadogpy/blob/master/tests/integration/api/test_api.py#L51) or [here](https://github.com/DataDog/datadogpy/blob/master/tests/integration/dogshell/test_dogshell.py#L85)).
