### ISSUE TITLE
Support multiple configuration files in the CLI

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1445]
This issue represents the simple change to allow for multiple configuration files to be specified. The idea is to load all configurations before processing. This allows the user to build a single mono-configuration file or break it up how they please. We should support the [glob syntax](https://en.wikipedia.org/wiki/Glob_(programming)) as well as multiple flags:

### Global syntax

```bash
vector --config /etc/vector/*.toml
```

or

```bash
vector --config /etc/vector/**/*.toml
```

### Multiple flags

```bash
vector --config vector1.toml --config vector2.toml
```

### Requirements

- [ ] Config files should be deduped before processing.

**Comment by Jeffail** [comment]
https://github.com/timberio/vector/pull/1725
