### ISSUE TITLE
Add tests for `journald` source which would try to load `libsystemd`

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#1464]
Currently all tests for `journald` source use function `run_journald` which mocks journal without loading `libsystemd`.

We need some integration tests which would attempt to load `libsystemd` to ensure that the source actually works on the given platform.

**Comment by bruceg** [comment]
This should be fairly straightforward to add to `lib/journald`. I can take a stab at doing it there if you'd like. We might have to add a new feature for this though to prevent test failures where journald support is not possible.

**Comment by a-rodin** [comment]
In the light of https://github.com/timberio/vector/issues/1473 it is not clear would we stick with the current approach to communication with `journald` or not. So I'm closing this for now.

**Comment by bruceg** [comment]
This is closed because of #1473
