### ISSUE TITLE
Transforms `add_field` and `add_tag` should have an override setting

### ISSUE THREAD

**Issue by Jeffail** [timberio/vector#1468]
Currently both the `add_field` and `add_tag` transforms will override current fields/tags. It would be nice to be able to disable this behavior because in some situations we might simply want to set a default value when it's not present in an event.

We could do this easily by just adding an `override` field that's `true` by default. Alternatively we could allow users to specify both override and non-override fields and tags by adding another array called `optional_fields` and `optional_tags`, or something (maybe `passive_fields` etc).

**Comment by binarylogic** [comment]
@Hoverbear this looks like a pretty simple change. I wouldn't mind resolving this while you're working through the schema changes. Let me know if I'm overstating the simplicity and we can defer it.
