### ISSUE TITLE
Use the `stable` rust compiler on windows

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#1480]
## Problem

Currently, we require the `nightly` rust compiler to compile vector on windows due to the need of the `windows_by_handle` feature https://github.com/rust-lang/rust/issues/63010. This is our only blocker for using the stable compiler on window.

## Proposal

The `windows_by_handle` feature is only a couple of lines implemented in `libstd` and its is only a nightly feature to ensure the code can be stabilized into `libstd`. Because we don't have the same requirements we should vendor this code into vector in its own crate in the `lib` directory. Doing this will allow us to use the `stable` compiler.

cc @a-rodin

**Comment by Hoverbear** [comment]
Looks like the only use in Vector is: https://github.com/timberio/vector/blob/b290ceb2aee4242834d434a4bd092fe2a0cece3b/lib/file-source/src/metadata_ext.rs#L23-L30.

Is it better expand this module's code, or create a new module which `file-source` should depend on?

**Comment by LucioFranco** [comment]
@Hoverbear what ever you think is easiest :)
