### ISSUE TITLE
Ensure the `cloudwatch_logs` sink follows event requirements

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#1483]
Cloudwatch log's `PutLogEvents` endpoint has a few requirements that we should ensure we follow or enforce. Listed below are the main ones:

- [ ] None of the log events in the batch can be more than 2 hours in the future.
- [ ] None of the log events in the batch can be older than 14 days or older than the retention period of the log group.
- [x] The log events in the batch must be in chronological ordered by their timestamp
- [ ] A batch of log events in a single request cannot span more than 24 hours. Otherwise, the operation fails.

For the first two we should ensure that if a subset of the logs sent contains invalid logs that the valid ones are still accepted. In this case we don't need to change our implementation since rejected logs still count as a successful request.

The 3rd one, I am not totally sure how we should solve this but it seems like it wants us to sort them but that sounds a bit more expensive than what we may want to do?

This last one can only happen when you hit a break in logs such that you get some logs that are older and some that are younger, this might happen when you restart vector after a long crash. This can't happen normally due to batch timeouts. This might be something we want to enforce but sounds like it may introduce some complex logic to where we would need to split outgoing batches into two separate ones.

**Comment by binarylogic** [comment]
> The 3rd one, I am not totally sure how we should solve this but it seems like it wants us to sort them but that sounds a bit more expensive than what we may want to do?

What's the consequence of not doing this? We should be testing these things if we're going deviate, otherwise we need to follow the API rules.

**Comment by LucioFranco** [comment]
@binarylogic I want to say in the past from what I've seen in my testing, cw will reject the subset of logs that are not ordered and accept the ones that are in order. Though, I don't think we've yet seen this even happen so I'm not totally sure. Would be good to test to see what the actual behavior is.

**Comment by binarylogic** [comment]
Noting. We have a user that effectively cannot use CloudWatch logs because we are not implementing this behavior. @LucioFranco the rules of this change seem fairly simple. How difficult would this be to implement given your recent sink changes?

**Comment by MOZGIII** [comment]
The main issue with CloudWatch is usually that logs aren’t ordered within a single request. The rest of the requirements are important to, but the unordered events issue occurs almost every time unless is’s addressed.

**Comment by LucioFranco** [comment]
Looks like sorting the events should be easy and we already do this in the loki sink https://github.com/timberio/vector/blob/master/src/sinks/loki.rs#L186.

The first two I think we could do pretty easily but would just drop events. The last one seems odd but again could probably be done as well in the same type of filter pass.
