### ISSUE TITLE
Support all socket types in the statsd source/sink

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1484]
I'm opening this issue based on user feedback in our chat room:

> Alternatively - it might be nice if the statsd source/sink could support TCP as well as UDP to allow plugging across a network.

I'm unsure if we want to do this, but it might be simpler with the changes happening in #1404 and #1355.

**Comment by loony-bean** [comment]
And maybe [UDS](https://docs.datadoghq.com/developers/dogstatsd/unix_socket/?tab=docker)?

**Comment by binarylogic** [comment]
@juchiast I've assigned you to this issue since it more accurately represents wrapping the `socket` sink.

**Comment by juchiast** [comment]
Hi @binarylogic , can you point me to some documentation about the field `namespace = "service"`? I'm not sure why it is there, why some sinks have it and some do not.
