### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by GildedHonour** [timberio/vector#1490]
Whom could I discuss with contributing to the project?

**Comment by a-rodin** [comment]
Hi @GildedHonour, thank you for being interested in contributing to Vector. You can ask questions related to contribution in the [chat](https://chat.vector.dev/). See https://vector.dev/community/ for details.

**Comment by binarylogic** [comment]
Yes, we'd love for you to contribute. Don't hesitate to reach out on chat if you need help. I'd also take a look at https://github.com/timberio/vector/blob/master/CONTRIBUTING.md.

**Comment by GildedHonour** [comment]
I've sent 2 private mesages to binarylogic, at gitter, regarding contributions. No reply.  

Idiocy.
