### ISSUE TITLE
Writing external plugin?

### ISSUE THREAD

**Issue by oleewere** [timberio/vector#1500]
Is there any recommended way (maybe some documentation) how to write a plugin outside of this repo for vector (like with fluentd), or the only recommended ways to ask a sink here or create PR against vector repo

**Comment by lukesteensen** [comment]
We don't currently have a way for Vector to load sources or sinks that are written outside of this repo. This is something we plan to do eventually but it's still in the design phase.

Could you share a little more about what you'd like to accomplish with an external plugin? Collecting different use cases is very helpful as we try to figure out a design that will work well.

In the meantime, feel free to open an issue here requesting the sink you have in mind, and PRs are always welcome as well!

**Comment by oleewere** [comment]
let's say i have a private endpoint/mechanism for processing data which is not really fit in the source code or too specific to use built-in plugins like the http ones (more custom logic there, like specific request signing etc.) - I have an example like this.

for supporting plugins like that it would be enough if i would have something like that: "ok, i have my plugin code here... I need to compile vector with that specific command and I have the binary that I need"

(btw: I ended up to look at this tool first because i got some memory leak issues + missing features with different azure storage fluentd plugins for azure datalake storage gen2 - that was caused by azure sdk+ruby http client, so i took a look maybe there is some tool out there which has it, but in the end I have already re-implemented the azure storage fluentd plugin with using gen2 api against libcurl and not with ruby http client....but overall i would say could be useful on your side to support something like adls gen2, as it has append operation as well, which can be useful if someone use that as a blob storage)

you can close this issue if you think, it can be considered only as a question.
