### ISSUE TITLE
Docker: use shiplift's since instead of manually filtering the logs

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#1506]
As I start `vector` with the docker source and a container that has a huge amount of logs I see a considerable delay before logs start to arrive at `vector`.
I stumbled upon it when I was doing some testing for my feature (#1504) and made a container that logs 16kb every second - and I left it running for a couple of hours.

I found out that it's a know issue (https://github.com/timberio/vector/issues/1057#issuecomment-544231124). The fix was not available at the time, but it's now trivial to use a proper API. Not sure if it'd solve the issue though, but at least we won't have to do the filtering ourselves.

The relevant code where we'd apply the fix is here:
https://github.com/timberio/vector/blob/76686d512e98e0228c65426bffe8f18c1a33ba8f/src/sources/docker.rs#L499-L506

We'd also have to do a cleanup for the filtering logic that'd become obsolete.

**Comment by binarylogic** [comment]
This makes sense to me. cc @LucioFranco @ktff for approval.

**Comment by ktff** [comment]
If they have added the support, then I am all for it. And regarding the delay, it's cause is probably the `.since(info.log_since())` that you commented, because without it, vector will receive older logs that it filters out, before getting current logs, causing the delay.
