### ISSUE TITLE
LogEvent cleanup

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#1507]
I was reading the code and realized we have `LogEvent::into_value` and `LogEvent::remove`, that are practically the same. We should deprecate one of them.

**Comment by a-rodin** [comment]
They are different, `LogEvent::into_value` takes ownership of `self`, but `LogEvent::remove` just borrows it.

**Comment by MOZGIII** [comment]
Oh, my bad.

**Comment by a-rodin** [comment]
Actually, they can be deduplicated, as the ownership difference is not really important here and mutable reference can be used in both of the cases. Thanks for pointing it out!
