### ISSUE TITLE
Batches that enforce both byte size and quantity limits

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1517]
Our sinks enforce either a batch size based on quantity _or_ byte size. We need the ability to apply both limits for some sinks. Specifically, the `aws_kinesis_streams` and `aws_kinesis_firehose` sinks:

* `aws_kinesis_streams`: 500 quantity, 5mib for the entire request
* `aws_kinesis_firehose`: 500 quantity, 4mib for the entire request

Failing to support both limits means we could end up with requests that exceed one but not the other.

**Comment by bruceg** [comment]
FTR I have run into this with some of the GCP sinks as well. When this is completed, the limits on those sinks will need to be reviewed.

**Comment by binarylogic** [comment]
This was resolved in https://github.com/timberio/vector/pull/3147
