### ISSUE TITLE
Feature request: ability to expose vector metrics to sink

### ISSUE THREAD

**Issue by afoninsky** [timberio/vector#1518]
When building complex pipelines based on logs/metrics - vector itself becomes a target for observability. For example, it would be useful to expose amount of events (incoming, parsed, outgoing) - display them on graphs, create alerts, etc.

Perhaps, any workaround already exists?

**Comment by binarylogic** [comment]
Hey @afoninsky, absolutely! This is _very_ important and it's on our roadmap to 1.0. @lukesteensen is working on this and we've opened https://github.com/timberio/vector/milestone/24 to represent the project. We'll update as we make progress. Thanks for the feedback.

**Comment by afoninsky** [comment]
Ok then, I see according issue, will close this. Thank you :)
