### ISSUE TITLE
New `humio_logs` sink

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1531]
A simple HTTP based sinks that sends log data to the Humio log service. This should use the structured data endpoint:

https://docs.humio.com/api/ingest/#structured-data

**Comment by binarylogic** [comment]
@LucioFranco I was speaking with @gburd (Humio engineer) and he was interested in helping out / reviewing the code when ready. Just wanted to get him in the conversation.

**Comment by LucioFranco** [comment]
Great! This is next up on my docket, the current plan is to directly wrap out `splunk_hec` sink and provide easy configuration for humio. I'll give you a tag on the PR once its up @gburd, thanks!
