### ISSUE TITLE
Add a new option for specifying indexed fields to `splunk_hec` sink

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#1534]
This issue discusses the problem of allowing users of `spunk_hec` sink to use indexed fields after we remove explicit fields. It also shows a closely related issue of duplication in the data we send to Splunk, which can be resolved alongside the first issue.

## Introduction

As we are removing distinction between explicit and implicit events, it becomes impossible to use [indexed fields extraction](https://docs.splunk.com/Documentation/Splunk/8.0.1/Data/IFXandHEC) in Splunk. There is no way for the sink to distinguish between fields which need to go to the index and the fields which need not.

## Example 1

Let's suppose that there is the following event:

```json
{
    "message": "X",
    "custom_field": "Y"
}
```

Here `message` is a "ordinary" field and `custom_field` is a field which should be part of the index. In the old terminology `message` is an implicit field and `custom_field` is an explicit field.

Before #1530 is merged, Vector would send the event above to Splunk like this:

```json
{
  "event": {
    "message": "X",
    "custom_field": "Y"
  },
  "fields": {
    "custom_field": "Y"
  },
  "time": 1579181077
}
```

So `fields` contains explicit fields and `event` contains both explicit and implicit fields. Note that there seems to be duplication, as examples in Splunk docs say that it is enough to put `custom_field` only to `fields`.

## Proposed configuration changes and behavior

I propose to

1. Introduce a new configuration option `index_fields` to the `splunk_hec` sink, which would contain an array of fields which need to be indexed fields.

2. Send fields which are present in the event and are listed in the `indexed_fields` array as part of `fields` object and all other fields as part of `event` object.

## Example 2

For the event from example 1 and the following configuration

```toml
[sinks.splunk_hec]
type = "splink_hec"
indexed_fields = ["custom_field"]
...
```

the data sent to Splunk would look like

```json
{
  "event": {
    "message": "X"
  },
  "fields": {
    "custom_field": "Y"
  },
  "time": 1579181077
}
```

**Comment by binarylogic** [comment]
This sounds good. For example 2, what happens if `index_fields = []`? Will `custom_field` show up in the `event` document?

**Comment by a-rodin** [comment]
> For example 2, what happens if `index_fields = []`? Will `custom_field` show up in the `event` document?

Yes, it would show in `event`.
