### ISSUE TITLE
Failed to parse timestamp: 1970-01-01

### ISSUE THREAD

**Issue by mhf-ir** [timberio/vector#1544]
```
root@ubuntu-test:~# vector --version
vector 0.7.0-nightly (g41be43d x86_64-unknown-linux-musl 2020-01-18)
root@ubuntu-test:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Focal Fossa (development branch)
Release:	20.04
Codename:	focal
root@ubuntu-test:~# vector --version
vector 0.7.0-nightly (g41be43d x86_64-unknown-linux-musl 2020-01-18)
root@ubuntu-test:~# vector test 1.toml 
Running 1.toml tests
root@ubuntu-test:~# cat 1.toml 
data_dir = "/tmp/vector"

[sources.ss11]
  # REQUIRED
  type = "journald" # example, must be: "journald"
  # units = []
  # current_boot_only = true # default

[sinks.out]
    inputs = ["ss11"]
    type = "console"
    encoding = "json"
root@ubuntu-test:~# vector --config 1.toml 
Jan 19 04:17:15.137  INFO vector: Log level "info" is enabled.
Jan 19 04:17:15.137  INFO vector: Loading config. path="1.toml"
Jan 19 04:17:15.139  INFO vector: Vector is starting. version="0.7.0" git_version="v0.6.0-155-g41be43d" released="Sat, 18 Jan 2020 11:24:13 +0000" arch="x86_64"
Jan 19 04:17:15.140  INFO vector::topology: Running healthchecks.
Jan 19 04:17:15.140  INFO vector::topology: Starting source "ss11"
Jan 19 04:17:15.140  INFO vector::topology: Starting sink "out"
Jan 19 04:17:15.140  INFO vector::topology::builder: Healthcheck: Passed.
Jan 19 04:17:15.140  INFO source{name=ss11 type=journald}: vector::sources::journald: Starting journald server.
Failed to parse timestamp: 1970-01-01
^CJan 19 04:17:16.682  INFO vector: Shutting down.
root@ubuntu-test:~# journalctl
-- Logs begin at Tue 2020-01-14 03:18:38 +0330, end at Sun 2020-01-19 04:17:01 +0330. --
Jan 14 03:18:38 ubuntu-test kernel: Linux version 5.4.0-9-generic (buildd@lcy01-amd64-023) (gcc version 9.2.1 20191130 (Ubuntu 9.2.1-21ubuntu1)) #12-Ubuntu SMP Mon Dec 16 22:34:19 UTC 2019 (Ubuntu 5.4.0-9.12-ge>
Jan 14 03:18:38 ubuntu-test kernel: Command line: BOOT_IMAGE=/vmlinuz-5.4.0-9-generic root=UUID=1072eb2b-fdbc-4049-8c24-10c535d75bc1 ro splash quiet
Jan 14 03:18:38 ubuntu-test kernel: KERNEL supported cpus:
Jan 14 03:18:38 ubuntu-test kernel:   Intel GenuineIntel
Jan 14 03:18:38 ubuntu-test kernel:   AMD AuthenticAMD
Jan 14 03:18:38 ubuntu-test kernel:   Hygon HygonGenuine
Jan 14 03:18:38 ubuntu-test kernel:   Centaur CentaurHauls
Jan 14 03:18:38 ubuntu-test kernel:   zhaoxin   Shanghai  
Jan 14 03:18:38 ubuntu-test kernel: x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating point registers'
Jan 14 03:18:38 ubuntu-test kernel: x86/fpu: Supporting XSAVE feature 0x002: 'SSE registers'
Jan 14 03:18:38 ubuntu-test kernel: x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers'
Jan 14 03:18:38 ubuntu-test kernel: x86/fpu: xstate_offset[2]:  576, xstate_sizes[2]:  256
Jan 14 03:18:38 ubuntu-test kernel: x86/fpu: Enabled xstate features 0x7, context size is 832 bytes, using 'standard' format.
Jan 14 03:18:38 ubuntu-test kernel: BIOS-provided physical RAM map:
Jan 14 03:18:38 ubuntu-test kernel: BIOS-e820: [mem 0x0000000000000000-0x000000000009fbff] usable
Jan 14 03:18:38 ubuntu-test kernel: BIOS-e820: [mem 0x000000000009fc00-0x000000000009ffff] reserved
Jan 14 03:18:38 ubuntu-test kernel: BIOS-e820: [mem 0x00000000000f0000-0x00000000000fffff] reserved
Jan 14 03:18:38 ubuntu-test kernel: BIOS-e820: [mem 0x0000000000100000-0x000000003ffeffff] usable
Jan 14 03:18:38 ubuntu-test kernel: BIOS-e820: [mem 0x000000003fff0000-0x000000003fffffff] ACPI data
Jan 14 03:18:38 ubuntu-test kernel: BIOS-e820: [mem 0x00000000fec00000-0x00000000fec00fff] reserved
```

And more important think i think you will need to add specific Ubuntu testing environment. That's required as most important distro.

**Comment by binarylogic** [comment]
Thanks @mhf-ir. @bruceg @a-rodin notice that the timestamp `1970-01-01` fails to parse, I assume this is happening during ingestion of the data within the `journald` source? This seems odd to me, like it is not recognizing a timestamp properly since that is the start of unix epoch.

**Comment by a-rodin** [comment]
> notice that the timestamp `1970-01-01` fails to parse, I assume this is happening during ingestion of the data within the `journald` source? This seems odd to me, like it is not recognizing a timestamp properly since that is the start of unix epoch.

I suspect the reason is that `1970-01-01` is parsed in the local timezone, which has offset `+0330`, and thus the corresponding Unix timestamp is negative.

**Comment by a-rodin** [comment]
@mhf-ir
> And more important think i think you will need to add specific Ubuntu testing environment. That's required as most important distro.

Thank you for the suggestion. Actually, our `test-stable` test suite in CI runs on Ubuntu 16.04, so the issue is probably not Ubuntu-specific, but most likely related to the timezone settings outlined in my previous comment.

**Comment by mhf-ir** [comment]
@a-rodin Thanks.
For testing CI I suggest add Ubuntu 18 and even 20 (focal) this will be the next generation Server OS. That i test on it for next infrastructure Platform.

**Comment by bruceg** [comment]
Could we see your Vector config file? It's not clear where a formatted timestamp is being parsed. The timestamps from journald are parsed as an integer number of microseconds, so formats like `1970-01-01` would fail for that reason. Also, the output of `journalctl --output=json | grep 1970-01-01` would be interesting. If it's more than a handful of lines, truncate it or paste it to a gist.

**Comment by mhf-ir** [comment]
Seems be different on kernel or other logs:
https://paste.ubuntu.com/p/zn7ssjGW6n/
https://paste.ubuntu.com/p/gKVSM8rg6V/

**Comment by bruceg** [comment]
Ah, I just realized the problem is not in the output that `journalctl` is giving us, but rather the command-line option we are passing to it. To test this quickly, on line 209 of `src/sources/journald.rs`, change `1970` to `2000`, rebuild, and rerun.

**Comment by mhf-ir** [comment]
Set timezone UTC time on server, problem solved.

**Comment by binarylogic** [comment]
Noting, we should still raise the date from `01-01-1970` to resolve this going forward.
