### ISSUE TITLE
Upgrade `rdkafka` to the current stable version 0.23.1

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#1547]
Ref https://github.com/timberio/vector/pull/1063#issuecomment-573505370, https://github.com/timberio/vector/pull/1520.

Related to https://github.com/timberio/vector/issues/1142.

**Comment by binarylogic** [comment]
This is part of the "Tokio 0.2" project because upgrading `rdkafka` is blocked by this transition (from what I understand).
