### ISSUE TITLE
Change execution model for `lua` transform

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#1549]
In order to do #616, I propose to slightly change the execution model of our `lua` tranform.

Instead of re-evaluating the user-provided source each time it is executed, it is possible to create a function with the body containing the code, and then call this function in the same runtime when we do the transform.

It would allow us to:

1. Ensure that the given code is valid Lua code.
2. Allow the user to keep state between events.
3. Possibly improve performance by avoiding need to parse the Lua code on each evaluation.

However, it might break some existing code, but it should

**Comment by lukesteensen** [comment]
I think this is definitely a good improvement.

We should make sure to think about how exactly it could break existing code and call that out in the release notes, but my guess is that it won't be a big problem.

We should also use our Lua benchmark to validate the expected performance improvement :smile:
