### ISSUE TITLE
Support metrics events in `lua` transform

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1563]
This came up in conversation with a couple of important Vector users. They want the ability to access metrics data in the `lua` transform. Specifically, they want the ability to add/remove/rename tags. This presents a couple of interesting questions:

1. How can a transform accept and output multiple event types?
2. How do we develop a LUA API that can accomplish all data formats?

**Comment by binarylogic** [comment]
Yep. I'm curious what @lukesteensen thinks. We should definitely agree on the approach before proceeding since this is more of a general topology design question.

**Comment by lukesteensen** [comment]
This is something we can do without changing the existing type system at all.

The existing `input_type` and `output_type` methods we require on every `TransformConfig` have access to all of the config's values. That means we can add a configuration option to the lua transform that indicates whether it should work on logs or metrics. We can then match on that option both in the type declaration methods and the actual transform implementation.

There are definitely a lot of type system improvements we can make overall that could improve this area, but I think we're actually in a pretty good spot for this particular case.

**Comment by synepolskyi** [comment]
Plus for the idea!
We are currently running the scheme "Kafka Source -> Transform Lua -> Transform Log_to_metric -> Prometheus Sink", but this scheme doesn't allow us to manage dynamic labels (tags), different types, etc.

It would be great to do the things in Lua and receive a metric on output.

**Comment by binarylogic** [comment]
Thanks @synepolskyi, we're working on finalizing the API in https://github.com/timberio/vector/pull/1962. Feel free to weigh in if you have any comments about our approach there.
