### ISSUE TITLE
Support metrics in the `ec2_metadata` transform

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1582]
We should be able to support metrics in the `ec2_metadata` transform by adding metric labels. I'm unsure if this should be supported in the same transform or a different one given that the fields can be configured.

**Comment by binarylogic** [comment]
@a-rodin I'm adding this to your project because I think it overlaps some with some of your data processing work. Specifically, supporting metrics in the `lua` transform since that'll be the first transform we support both event types. I'm curious how we will handle these types of use cases. If this turns out to include work not related to your project we can remove it.

**Comment by jszwedko** [comment]
Just noting that a user requested this in discord: https://discord.com/channels/742820443487993987/759154784309215252/830797070868414505

**Comment by jszwedko** [comment]
Closed by https://github.com/timberio/vector/pull/8157
