### ISSUE TITLE
Vector.dev should use the latest `v*` branch

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1594]
Currently, vector.dev reflects the state of the `master` branch. This is problematic because our docs do not coincide with the latest version of Vector. It also does not reflect patch releases that are made on these branches (as is the case with `0.7.1`). I was aware of this caveat when we switched the website to Docusaurus 2.0 because the benefits outweighed the downsides. And at the time Docusaurus was working on versioned documentation. Unfortunately, their approach does not lean into git and instead implements [its own system of nested folders](https://v2.docusaurus.io/docs/versioning/). I thought this was odd and I think we're much better served to configure Netlify to deploy vector.dev from the latest `v*` branch.

This should be done ASAP given that the website does not reflect the latest release (0.7.1).

**Comment by jregistr** [comment]
Ah, glad I found this. I've gotten quite a few `unknown field` errors running validate. This explains it!

**Comment by binarylogic** [comment]
Sorry, @jregistr! I am working on it as I write this. It's a little more challenging than it sohuld be, but we'll have this corrected soon.

**Comment by jregistr** [comment]
No worries!  I understand 😄. I was able to run the docs locally for the latest tag and continue my testing.

**Comment by binarylogic** [comment]
This is done.
