### ISSUE TITLE
Transforms as tasks

### ISSUE THREAD

**Issue by lukesteensen** [timberio/vector#1598]
# Motivation

The current `Transform` trait is quite simple: https://github.com/timberio/vector/blob/eab9ea663dd5bc52a4db4c99aa1518454d026a29/src/transforms/mod.rs#L24-L32

This lets us map and filter, derive many events from one, etc. But it has a big limitation when it comes to aggregation.

By modeling transforms as functions, they are only ever triggered by the arrival of an incoming event. This means that any data buffered in a transform's internal state is reliant on the arrival of a new event to be operated on again. Since data arrival is unpredictable, we have to assume that new data could never come, leaving that stashed state to sit indefinitely.

The most basic problem this causes is when the new data never comes, Vector is shut down, and that stashed data is lost. This happens because there is no mechanism for flushing that internal state.

It's also a problem if you want to do windowed aggregation or limit how long intermediate data can be buffered. Such functionality would require some way to trigger the transform once a certain amount of time has passed, giving it the chance to output events in the absence of an incoming one.

Some transform ideas that are affected by this limitation are #1329, #1437, and #1488.

# Potential solutions

At a high level, we would want an option to define a transform as (roughly) `Fn(Stream<Event>) -> Stream<Event>`. This lift from events to streams of events currently happens in topology building: https://github.com/timberio/vector/blob/eab9ea663dd5bc52a4db4c99aa1518454d026a29/src/topology/builder.rs#L165-L171

Theoretically, we could push that logic into a new defaulted method on `Transform`:

```rust
fn transform_stream(
    self,
    input_rx: Receiver<Event>,
) -> Box<dyn Stream<Item = crate::Event, Error = ()> + Send> {
    Box::new(
        input_rx
            .map(move |event| {
                let mut output = Vec::with_capacity(1);
                self.transform_into(&mut output, event);
                futures::stream::iter_ok(output.into_iter())
            })
            .flatten(),
    )
}
```

This would then give transform authors the ability to implement this method themselves with all the freedom of the `Stream` API.

Unfortunately, taking ownership of `self` here gets us into the world of dynamically sized types and object safety, and this simple implementation does not compile. It's possible that someone with a deeper knowledge of this area of Rust would have a trick to solve this, but it feels somewhat fundamental to me.

If that approach is not viable (or otherwise undesirable), the alternative is to put that logic onto another trait that gets implemented for each transform. Currently, the only one of those that exists is `TransformConfig`.

One strategy that does work is to extend `TransformConfig` to handle this logic:

```rust
type EventStream = Box<dyn Stream<Item = crate::Event, Error = ()> + Send>;

pub trait TransformConfig: core::fmt::Debug {
    fn build(&self, exec: TaskExecutor) -> crate::Result<Box<dyn transforms::Transform>>;

    // NEW
    fn build_stream(
        &self,
        exec: TaskExecutor,
        input_rx: Receiver<Event>,
    ) -> crate::Result<EventStream> {
        let mut transform = self.build(exec)?;

        Ok(Box::new(
            input_rx
                .map(move |event| {
                    let mut output = Vec::with_capacity(1);
                    transform.transform_into(&mut output, event);
                    futures::stream::iter_ok(output.into_iter())
                })
                .flatten(),
        ))
    }
    ...
}
```

This is conceptually a little funky because it completely cuts out the actual `Transform` trait, which would not be used at all for "transforms" implemented via `build_stream`. This could potentially be smoothed over with some creative renaming.

Finally, another option would be to remodel the existing traits a bit more deeply. We could potentially push the existing `Transform` trait down to something like `TransformFn` (or even try to use the normal `Fn` traits), and make a new `Transform` trait that operated at this higher task level. We could also try a setup where instead of `TransformConfig::build(&self) -> Transform`, we do something more like `Transform::build(TransformConfig) -> Self` and a blanket impl for `TransformFn`/`FnWhatever`.

**Comment by binarylogic** [comment]
Excellent write up. It sounds like we should package this with one of the transforms you referenced? If not, I'm curious how you're thinking about prioritizing this.

**Comment by LucioFranco** [comment]
Great write up! 

One thought that occurred to me is that basically we want to detect when our stream that we are wrapping is closed.

Basically, we have a stack:

Source > Stream<Event>
   |
Transform > Stream<Event>

which ends up looking like `Transform<Source>` and we want to detect when our inner stream (the source) is closed aka its poll method returns `None`?

If this assumption is correct, then could we update `transform` to be `transform(event: Option<Event>) -> Option<Event>`? This would allow us to detect when the stream is ending to tell us to flush our buffer. 

Looking at the map implementation which we basically use, it looks like it just maps over the option which means that if None is produced the map combinator will never know that it ended before it gets dropped. https://docs.rs/futures/0.1.29/src/futures/stream/map.rs.html#79

This change seems like it would reduce complexity while also providing us with the needed changes.

The other use case I can think of is dealing with timers and flushing a transform on a timer like we do with batches. In this case I think we could potentially just let a user `poll` a timeout within the map fn which is already on task. I _think_ this should work well enough for what we need. We may need some extra state but would again reduce complexity.
