### ISSUE TITLE
Re-enable kubernetes tests in CI

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#1635]
Currently, we have Kubernetes tests disabled in CI because we were running out of resources and hitting continuous etcdserver timeouts. I suggest we re enable Kubernetes by hosting a small single node cluster somewhere on EC2 that our CI machines can connect too.

**Comment by LucioFranco** [comment]
Moving forward here I think we should attempt to also test against at least three versions of kube. `1.13`, `1.14` and the latest version which now is `1.17`.

cc @Hoverbear you may have some other ideas as well.

**Comment by ktff** [comment]
Also, to remove the need for [manually updating test image](https://github.com/timberio/vector/issues/260#issuecomment-565836899), which is easy to forget, we should locally build an image of tested version of Vector, make it available to Kubernetes cluster, and pass the image name to the tests over environment variable.

**Comment by binarylogic** [comment]
@ktff this seems like a somewhat important issue. Would you mind working on re-enabling this? We're also moving towards Github Actions so it might be worth adding it as a Github Action instead of in Circle.
