### ISSUE TITLE
Provide package archives for vector (APT/YUM)

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#1643]
We already ship `.deb` and `.rpm` packages, we should also provide `APT` and `YUM` repos.

I don't know much about `yum`, but as for `apt`, we could offer a PPA for Ubuntu via the https://launchpad.net service.

It's easy to package rust projects with [`debcargo`](https://crates.io/crates/debcargo). Going that route will, however, require us to also package all the dependencies - as required by the [Debian Rust Packaging Policy](https://wiki.debian.org/Teams/RustPackaging/Policy). It's a bit troublesome, however it brings us the closest to the shipping vector to the official Debian package repos.

**Comment by Hoverbear** [comment]
I'd love to take this, would anyone be opposed?

**Comment by binarylogic** [comment]
Nope! Go for it. And for some context: #862, #199, #963, #962.

**Comment by MOZGIII** [comment]
By the way, we should also consider [openSUSE Build Service](https://build.opensuse.org/). It's also pretty good, since it can build and ship `deb` and `rpm` - and for Debian (+Ubuntu), Fedora (+CentOS, RHEL and Scientific Linux) and openSUSE itself. And we can also self host it (if we have to).
Here's a wine project there for example: https://build.opensuse.org/project/show/Emulators:Wine
