### ISSUE TITLE
New `schema` transform

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#165]
I'm throwing this up so we can start thinking about it and fleshing out its requirements. This is still very early and high level, the details are expected to change and evolve as we gain consensus.

## Use Case

As a user, I want to enforce a consistent schema across my data so that consumers of my data do not break and I can take advantage of sinks that require schemas.

## Hand Wavy Requirements

These are very high level. I expect many of these to change or be dropped entirely.

- It should allow for static defined schemas.
- It should allow for dynamic schemas.
- It should consistently coerce fields into the same type. If a field `foo` is sent as a `string`, `foo` should always be a string or it should be dropped.
- It should allow for nested columns.
- It should clean up stale columns over time.
- It should allow for a configurable column limit, dropping columns after the limit is hit.
- Schemas should be source specific? Sink specific? Part of the topology as a transform?

**Comment by a-rodin** [comment]
One way to implement this proposal is to add a [JSON schema](https://json-schema.org) transform, which would take JSON schema (either from an embedded string or from a file) and reject events that don't pass the validation.

With this approach the requirements would be satisfied as following:

| Requirement | Support |
|--------------|---------|
| It should allow for static defined schemas. | ✅ |
| It should allow for dynamic schemas. | ? |
| It should consistently coerce fields into the same type. If a field foo is sent as a string, foo should always be a string or it should be dropped. | ✅ |
| It should allow for nested columns. | ✅ |
| It should clean up stale columns over time. | ? |
| It should allow for a configurable column limit, dropping columns after the limit is hit. | ✅ via [maxProperties](http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.5.1) |
| Schemas should be source specific? Sink specific? Part of the topology as a transform? | transform? |

I would like to have more context about dynamic schemas and clean up of stale columns to understand can these be supported with the approach with JSON schema or not.

I think the cleanest way to implement this is as a transform that can be added to the topology. We could add it to sources/transforms/sinks, but it would make number of options for all sources/transforms/sinks larger, so for now I can't see any benefit of doing it in comparison to having it as a separate transform.

**Comment by binarylogic** [comment]
Definitely, I like it. If we did implement this I'd prefer that we name it something more specific (`json_schema`).

Bonus points if we can load the schema from a URL. That would be an interesting follow-up feature.

**Comment by Hoverbear** [comment]
We could build this into the JSON parser:

```toml
[transforms.parse]
  inputs = ["application"]
  type = "json_parser"
  schema = "./schemas/message.json"
  drop_invalid = true
```

**Comment by Hoverbear** [comment]
This is also related to #751 since it's doing roughly the same thing with a different service.

**Comment by Hoverbear** [comment]
@binarylogic Do you have an opinion on a `json_schema` transform vs integrating this into the `json_parser`? Does JSON schema work for you?

**Comment by binarylogic** [comment]
Yeah, that's an interesting question. You could make the same code for encoding at the sink level, which is related to your protobuf work (#1472). Ex:

```toml
[sinks.archive]
  type = "aws_s3"
  sinks.encoding.type = "protobuf"
  sinks.encoding.schema = "/path/to/protobuf"
```

For consistency reasons I think your `json_parser` proposal makes sense, but only if we're planning to do this with encoding as well.

**Comment by a-rodin** [comment]
I actually like the idea of implementing it as a part of `json_parser` because it make it possible to use [f5-json-schema](https://github.com/KayEss/json-schema)or [JSON schema validator for modern C++](https://github.com/pboettch/json-schema-validator) which implement a newer version of schema than the `valico` Rust crate.

**Comment by Hoverbear** [comment]
@binarylogic Some questions before we can consider this ready to work on:

* You specified you'd like this to be part of `encoding` in some comments. Can you confirm you'd like this to apply as broadly as #1915 ?
* Should this apply for sinks and sources? Or just sinks?
* I feel like we are satisfied with the idea of using a JSON schema for the first pass here? If so, should we make the `schema` field only supported by `json` style encodings?
* Should we support a `on_failed_match` field which supports `"drop"` or `"coerce"` options?

**Comment by binarylogic** [comment]
We're deferring this until its purpose becomes more clear. With the addition of the new `encoding.only_fields` and `encoding.except_fields` options, the `coercer` `drop_unspecified`, and the upcoming WASM runtime. I'm not sure we'll need this.

**Comment by binarylogic** [comment]
I'm closing this since our solution to schemas will likely be in source and sinks, in the form of read/write schemas. Vector take an unopinionated stance on schemas and aims to enable any schema the user desires.
