### ISSUE TITLE
Fix nightly builds on CI

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#1661]
Will fill this out with more information once I find it but currently our nightly builds have stopped working since the 27th and we should ensure that they are still working.

**Comment by binarylogic** [comment]
I've resolved this. It was an issue with the `verify-nixos` job.

**Comment by LucioFranco** [comment]
Looks like nightly builds are still failing reference https://github.com/timberio/vector/issues/1436#issuecomment-583424429

**Comment by anton-ryzhov** [comment]
https://packages.timber.io/vector/nightly/latest/
![image](https://user-images.githubusercontent.com/556933/74045699-882d1280-49cd-11ea-9e24-9fcc08db1ef6.png)

**Comment by binarylogic** [comment]
Resolved via https://github.com/timberio/vector/pull/1760
