### ISSUE TITLE
Make `vector generate` shell friendly

### ISSUE THREAD

**Issue by Hoverbear** [timberio/vector#1684]
We can use `vector generate` to create template configurations for Vector. 

This is quite useful for quickly building out configurations without needing to scour the docs!

Here's some examples:

```bash
$ vector generate "|json_parser"
$ vector generate "stdin||http"
$ vector generate "||file,http"
```

You may notice all of these examples require quotes! This is because `|` is a "pipe" in a shell, and redirects output.

This command is still experimental, and it's syntax is not stabilized. We can consider adding a new recommended syntax, and deprecate the old format.

Some possibilities:

```bash
$ vector generate stdin+json_parser+console
$ vector generate stdin/json_parser/console
$ vector generate --sources stdin --transforms json_parser --sinks console
```

cc @a-rodin @Jeffail

**Comment by a-rodin** [comment]
Ultimately this could have been solved as a side effect of doing https://github.com/timberio/vector/issues/1328 or https://github.com/timberio/vector/issues/1327 in conjunction with something like https://github.com/timberio/vector/issues/1653. So if we had a terse and expressive  language to describe the topology, an expression in such a language could also have been used as a command line argument to scaffold the config.

But those are much larger issues, so I don't mean that this proposal should be blocked by them.
