### ISSUE TITLE
"Strategies For Developing Complex Vector Config Files" guide

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1693]
As part of wrapping up the [Improve Configuration Development](https://github.com/timberio/vector/milestone/27) project we should deliver a complete guide on how to develop and maintain complex Vector configuration files. We should agree on a rough outline first. Guides should always be progressive, starting simple and progressing into more complex strategies. For example:

1. Generating/Scaffolding config files
2. Manual Testing
3. Unit Testing
4. Pipelines
5. Multiple configuration files

**Comment by Jeffail** [comment]
Draft here: https://github.com/timberio/vector/pull/1774
