### ISSUE TITLE
Support DOT as a config file format

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#1699]
This proposal is closely related to  #1327 and #1679.

The idea is to support [DOT](https://en.wikipedia.org/wiki/DOT_(graph_description_language)) as an alternative config file format for Vector.

DOT allows to describe directed graphs and attributes of nodes in these graphs, which means that it suites quite well the need to describe Vector's topologies. Most of the popular text editors support syntax highlighting for it either natively or through extensions. A topology described in this format can be visualized right away by any Graphviz-compatible visualizer.

I made PR #1698 which shows how our example configs could have been translated to DOT file format. There is also an [example of one of the configs from that PR](https://dreampuf.github.io/GraphvizOnline/#%23%20Prometheus%20sink%20example%0A%23%20------------------------------------------------------------------------------%0A%23%20Parsing%20logs%20as%20metrics%20and%20exposing%20into%20Prometheus%0A%0Adigraph%20%7B%0A%0A%20%20data_dir%20%3D%20%22%2Fvar%2Flib%2Fvector%22%0A%20%20%0A%20%20subgraph%20sources%20%7B%0A%20%20%20%20%23%20Ingest%0A%20%20%20%20file%20%5B%0A%20%20%20%20%20%20type%20%3D%20%22file%22%0A%20%20%20%20%20%20include%20%3D%20%22sample.log%22%0A%20%20%20%20%20%20start_at_beginning%20%3D%20true%0A%20%20%20%20%5D%0A%20%20%7D%0A%20%20%0A%20%20subgraph%20transforms%20%7B%0A%20%20%20%20%23%20Structure%20and%20parse%20the%20data%0A%20%20%20%20regex_parser%20%5B%0A%20%20%20%20%20%20type%20%3D%20%22regex_parser%22%0A%20%20%20%20%20%20regex%20%3D%20%22%5E(%3FP%3Chost%3E%5B%5Cw%5C.%5D%2B)%20-%20(%3FP%3Cuser%3E%5B%5Cw-%5D%2B)%20%5C%5B(%3FP%3Ctimestamp%3E.*)%5C%5D%20%5C%22(%3FP%3Cmethod%3E%5B%5Cw%5D%2B)%20(%3FP%3Cpath%3E.*)%5C%22%20(%3FP%3Cstatus%3E%5B%5Cd%5D%2B)%20(%3FP%3Cbytes_out%3E%5B%5Cd%5D%2B)%24%22%0A%20%20%20%20%5D%0A%20%20%20%20%0A%20%20%20%20%23%20Transform%20into%20metrics%0A%20%20%20%20log_to_metric%20%5B%0A%20%20%20%20%20%20type%20%3D%20%22log_to_metric%22%0A%20%20%20%20%5D%0A%20%20%20%20%0A%20%20%20%20subgraph%20%22log_to_metric.metrics%22%20%7B%0A%20%20%20%20%20%20subgraph%20%7B%0A%20%20%20%20%20%20%20%20type%20%3D%20%22counter%22%0A%20%20%20%20%20%20%20%20field%20%3D%20%22message%22%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20subgraph%20%7B%0A%20%20%20%20%20%20%20%20type%20%3D%20%22counter%22%0A%20%20%20%20%20%20%20%20increment_by_value%20%3D%20true%0A%20%20%20%20%20%20%20%20field%20%3D%20%22bytes_out%22%0A%20%20%20%20%20%20%20%20name%20%3D%20%22bytes_out_total%22%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20subgraph%20%7B%0A%20%20%20%20%20%20%20%20type%20%3D%20%22gauge%22%0A%20%20%20%20%20%20%20%20field%20%3D%20%22bytes_out%22%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20subgraph%20%7B%0A%20%20%20%20%20%20%20%20type%20%3D%20%22set%22%0A%20%20%20%20%20%20%20%20field%20%3D%20%22user%22%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20subgraph%20%7B%0A%20%20%20%20%20%20%20%20type%20%3D%20%22histogram%22%0A%20%20%20%20%20%20%20%20field%20%3D%20%22bytes_out%22%0A%20%20%20%20%20%20%20%20name%20%3D%20%22bytes_out_histogram%22%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%0A%20%20subgraph%20sinks%20%7B%0A%20%20%20%20%23%20Output%20data%0A%20%20%20%20%0A%20%20%20%20console_metrics%20%5B%0A%20%20%20%20%20%20type%20%3D%20%22console%22%0A%20%20%20%20%20%20encoding%20%3D%20%22json%22%0A%20%20%20%20%5D%0A%20%20%20%20%0A%20%20%20%20console_logs%20%5B%0A%20%20%20%20%20%20type%20%3D%20%22console%22%0A%20%20%20%20%20%20encoding%20%3D%20%22text%22%0A%20%20%20%20%5D%0A%20%20%20%20%0A%20%20%20%20prometheus%20%5B%0A%20%20%20%20%20%20type%20%3D%20%22prometheus%22%0A%20%20%20%20%20%20namespace%20%3D%20%22vector%22%0A%20%20%20%20%20%20buckets%20%3D%20%220.0%2C10.0%2C100.0%2C1000.0%2C10000.0%2C100001.0%22%0A%20%20%20%20%5D%0A%20%20%7D%0A%20%20%0A%20%20%23%20Set%20up%20the%20data%20flow%0A%20%20file%20-%3E%20regex_parser%20-%3E%20log_to_metric%20-%3E%20prometheus%0A%20%20log_to_metric%20-%3E%20console_metrics%0A%20%20regex_parser%20-%3E%20console_logs%0A%7D) in an [open source](https://github.com/dreampuf/GraphvizOnline) online editor and visualizer for DOT files.

Caveats:
* The data types support is less rich than in TOML, so all values would be strings. However, because of Rust's strong type system, this seems to be not an issue, as there are almost no ambiguities possible. Arrays can be encoded as strings with separators (for example, comma-separated strings) and nested structures as subgraphs (see configs for metrics transforms for examples).

**Comment by lukesteensen** [comment]
There's a lot to like about this! It's really interesting to see an example of what config could look like in a language that's actually designed to express graphs.

That being said, my initial reaction is that DOT is a little bit too "weird" of a format to ask our users to write themselves. I'm personally familiar with it, but usually only as an intermediate output of a tool that's designed to feed into `graphviz` (which is a great feature idea for Vector). I don't know if enough users are familiar with writing DOT files manually for the choice to be worthwhile.

Similar to my comment on #1679, I think it's valuable to compare the pros and cons of this proposal against some theoretical purpose-built language we implement (probably with strong influences from DOT and bash).

**Comment by jamtur01** [comment]
+1 to being able to output .dot graphs of Vector configurations. Puppet does this and its really useful to reason about configurations.

**Comment by lukesteensen** [comment]
@jamtur01 Very much agree. I've opened a new issue to represent that work.

I'm going to go ahead and close this issue, since I see no plausible future where we decide to switch to DOT as our config file input format.
