### ISSUE TITLE
Allow sink building to be a future

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#170]
This change is to allow the building of a sink to be done in future. This adds a few benefits, mainly, it adds the benefits to fetch the current `DefaultExecutor::current` and spawn off of that. This is useful for many things mostly running transports but for things that need to maintain state, like the cloudwatch sink would either need to use `Arc<Mutex<State>>` or use a channel which would require knowledge of the current executor to spawn the task into the background.

cc @lukesteensen

**Comment by binarylogic** [comment]
I believe this was done in https://github.com/timberio/vector/pull/3066.
