### ISSUE TITLE
Support running Kubernetes tests using `kind`

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#1700]
[kind](https://kind.sigs.k8s.io/) is a tool for running Kubernetes inside Docker. As far as I understood it, it connects to Docker engine through a socket and starts Kubernetes processes inside Docker containers.

I think it might be great to be able to run Kubernetes tests this way, started them using a `docker-compose.yml` file like other Vector tests (see #1663).

@LucioFranco what do you think?

**Comment by LucioFranco** [comment]
@a-rodin we already use kind and unfortunately its been very slow. Last I debugged I kept running into `etcdserver: timeout` errors with kind 1.14 and 1.17.

So I think our best route for kube is to host it on our own node where we can ensure that its not overloaded.

**Comment by a-rodin** [comment]
@LucioFranco do you think these errors could have been avoided if it was just running on a large VM in a cloud (say, 64 cores / 64 GB of RAM, SSD volumes)?

**Comment by LucioFranco** [comment]
@a-rodin probably I'm just not sure of the noise levels of the circleci machines.

**Comment by binarylogic** [comment]
We should be able to test this with `kind` on a large enough machine. We'll be moving to GH actions with custom runners, so we can use whatever machine size we want.

**Comment by MOZGIII** [comment]
I'm planning to use `minikube` at CI - it supports running cluster in docker now. It internally reuses `kind` parts.
There's even a Github Action for `minikube` that takes care of preparing the runtime for us.
