### ISSUE TITLE
Vector should shut down when stdin is closed and it's the only source

### ISSUE THREAD

**Issue by lukesteensen** [timberio/vector#1702]
Logically, if the only source in a vector topology is `stdin` and the process's STDIN has been closed, Vector should finish processing all the existing events in the pipeline and gracefully shutdown since there is no possibility for further events.

I can't quite tell why, but this is not the current behavior. The `stdin` source itself seems to finish properly, and I would expect that the close of its channel would cause that to cascade through all the downstream components. It's possible we're retaining an additional `Sender` for the connecting channels somewhere, maybe to support config reloading?

**Comment by binarylogic** [comment]
@stbrody if we decide to proceed with the "Simplify Shutdown" project this issue is related.

**Comment by Hoverbear** [comment]
Should vector shut down if all sources are closed?

**Comment by lukesteensen** [comment]
> Should vector shut down if all sources are closed?

I think so, with the caveat that most sources probably can't be "closed" in the way that stdin can. Servers, for example, can't know that they'll never receive another connection.

**Comment by binarylogic** [comment]
Just adding a note. I want to make sure this does not shut down Vector when te config is reloaded.

**Comment by ktff** [comment]
With the new shutdown, this is still an issue.
