### ISSUE TITLE
More clearly define component purpose/concern boundaries

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1731]
Something that continually comes up in conversation, especially as we get closer to 1.0, is

**What constitutes a new component vs extending an existing component?**

For example:

* Is a `shape` transform better then three `add_fields`, `remove_fields`, and `rename_fields` transforms? 
* Is a `parser` transform better than an unbounded number of `*_parser` transforms?
* And finally, when we do add options into sources/sinks vs creating a new transform? Ex: `decode = "json"` vs a `json_parser` transform?

Where we draw this line is at the heart of this issue.

We'd benefit from defining some guidelines and principles that we can lean on to answer this question. Similar to the [checklist](https://github.com/timberio/vector/blob/master/CONTRIBUTING.md#sink-healthchecks) we created for building healthchecks in sinks.

### Why?

1. Consistency = better UX.
2. It'll reduce breaking changes, especially if we're wavering on this over time.
3. It'll reduce internal friction and communication overhead.

### Goals

1. Reduce the cognitive overhead a user has when surveying Vector's available components.
2. Progressively introduce the user to more advanced features.
3. Avoid fragmentation. Consolidation is likely to increase the usage and stability of components.

### Thoughts

It's important that we don't conflate how we organize Vector's components with how we present them to the user. I'm talking both about the TOML syntax we expose and how our documentation is structured. It's very likely that we can solve this with a better higher-level syntax, like the ones proposed in (#1679 and #1328). Then Vector feels more like a bash style program, or even a programming language, where you chain small purpose-driven commands together.

### Specific Questions

1. Is a `shape` transform better than the `add_fields`, `remove_fields`, and `rename_fields` trasnforms?
2. Is a `shape` transform better than a simple, chainable high-level syntax, where the `add_fields`, `remove_fields`, and `rename_fields` trasnforms could easily be chained? Like the one proposed in #1679.
3. Is a `parser` transform better than a `json_parser`, `regex_parser`, `grok_parser`, `split`, etc?
4. Are `encoding.whitelist` and `encoding.blacklist` (in sinks) better than a transform that does that same?
5. Is a `decode.format` source option better than a `parser` transform? 

Noting, these don't have to be black and white, we can offer both.

### Tasks

- [ ] Add this to the `CONTRIBUTING.md` guide.
- [ ] Open follow up issues to clean up areas we violate these new rules.

**Comment by Hoverbear** [comment]
I was mentioned to @binarylogic that we could reasonably support a transform like:

```toml
[transforms.rework]
inputs = [ "foo" ]
[[transforms.rework.steps.0]]
rename = "foo"
to = "bar"
[[transforms.rework.steps.1]]
drop = ["dogs", "foxes"]
[[transforms.rework.steps.1]]
add = [["yay", "{{bar}}"], ["day", "{{bar}}"]]

[transforms.rework_simple]
inputs = [ "foo" ]
rename = "foo"
to = "bar"
```

And had some concerns that this might be becoming a monolithic transform. :classical_building:

**Comment by binarylogic** [comment]
I updated the original issue with more [deep thoughts](https://www.nbc.com/saturday-night-live/video/deep-thoughts-evening-sky/n10134).

**Comment by Hoverbear** [comment]
So deep 
![image](https://user-images.githubusercontent.com/130903/73967485-d73f4e80-48cc-11ea-98d6-8f41ba3e8479.png)

**Comment by Hoverbear** [comment]
Decoupling the `encoding` from sinks and sources may grant us some composability in the future. We could even still support the old syntax and alias it to `sink|*_parser|` internally.

**Comment by anton-ryzhov** [comment]
> 1. Is a shape transform better than the add_fields, remove_fields, and rename_fields trasnforms?

Current way of defining pipelines makes them too long with so granulay transforms. I'd prefer to have one transform for that 4 things (+copy field).

> 4. Are encoding.whitelist and encoding.blacklist (in sinks) better than a transform that does that same?

Is it related to https://github.com/timberio/vector/issues/1448 ? Then it can't be implemented in transform because sink will need that fields to route events, but shouldn't encode them into payload.

**Comment by binarylogic** [comment]
Closing this in favor of #3119 and #3341. In general, simple parsing and mapping operations will be covered by the new `remap` transform. Specialized transforms can still exist where it makes sense (ex: `geoip` transform).
