### ISSUE TITLE
Tls doesn't work with separate file for private key

### ISSUE THREAD

**Issue by ktff** [timberio/vector#1748]
While testing  #1746, a `TLS` configuration error occurred:

```
Normal(ErrorStack([Error { code: 218529960, library: "asn1 encoding routines", function: "asn1_check_tlen", reason: "wrong tag", file: "crypto/asn1/tasn_dec.c", line: 1130 }, Error { code: 218595386, library: "asn1 encoding routines", function: "asn1_item_embed_d2i", reason: "nested asn1 error", file: "crypto/asn1/tasn_dec.c", line: 290, data: "Type=PKCS12" }]))
```

Traced it down to this [line](https://github.com/timberio/vector/blob/master/src/sinks/util/tls.rs#L112) .
By my understanding this should be `if options.key_path.is_none() {` so to try out building `Identity` with a public key in `crt_path` and a private key in `key_path`.

Currently #1746 is using fixed version and it works.

**Comment by binarylogic** [comment]
@bruceg worked on some of the TLS changes, so he should be able to take a look.

**Comment by bruceg** [comment]
You are absolutely correct, that is an untested typo. I will work up a test to go with the obvious patch to fix it.
