### ISSUE TITLE
The `vector test` command does not require tests or warn that no tests were found

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1756]
```
➜ vector test
Running /etc/vector/vector.toml tests
```

We should error or note that there aren't any tests.

**Comment by Jeffail** [comment]
I've already added a warning https://github.com/timberio/vector/pull/1739/commits/5addaea1eb820cc6420977d55f20ca43dd331768 to state that no tests were run. But I'm wondering if it's worth extending the message to something like `No tests were found, for guidance check out https://vector.dev/docs/setup/guides/unit-testing/`. More verbose == more annoying in CI logs when the user already knows (like maybe they're running `vector test ./somewhere/*.toml` and know there are some files without tests), but it's also nice to send users directly to where they can learn more.

**Comment by binarylogic** [comment]
Yeah, I don't think that's necessary just yet. I have https://github.com/timberio/vector/issues/978 open which could be used to solve that. It also wouldn't be bad to include that in the command's description. The URL is so long though :/ .

**Comment by Hoverbear** [comment]
We can use [Netlify redirects](https://docs.netlify.com/routing/redirects/) to create some shortlinks ala `vector.dev/@/testing` or whatnot.

**Comment by binarylogic** [comment]
Yep. I'm closing this for now since there is proper messaging.
