### ISSUE TITLE
Transform `geoip` example not very useful

### ISSUE THREAD

**Issue by Hoverbear** [timberio/vector#1763]
Currently, checking the [`geoip`](https://vector.dev/docs/reference/transforms/geoip/#output) docs, a reader finds this example of the output:

![image](https://user-images.githubusercontent.com/130903/74179573-9314bc80-4bf2-11ea-9e95-1c0acaaedac2.png)

I propose we use a proper example here. Users may wish to know the schema of this and use it as part of templating later

Can we use the `geoip` of https://vector.dev or something?

Related to #1214

**Comment by binarylogic** [comment]
Hm, that's definitely a bug. I'll get this fixed.
