### ISSUE TITLE
Reapproach file checkpointing strategy

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1779]
## Context

The `file` source was one of our first components and has undergone a number of changes since we created Vector. This is especially true for the checkpointing feature. When we first set out to build the checkpointing feature we were unsure how we wanted to persist a checkpoint's state. There were discussions to use `leveldb` for this since it was being used for our disk buffers, but there were also discussions to replace `leveldb` with something else (due to the now moot complexity and performance issues). Now, with the benefit of hindsight, we should reapproach our checkpointing strategy to solve issues users are reporting.

## Problem

The `file` source checkpointing strategy has the following problems:

1. Checkpoint files are not cleaned up (#1427).
2. The individual checkpoint file strategy is not optimally efficient (https://github.com/timberio/vector/issues/1427#issuecomment-583447232).

## Proposals

I'd like for us to agree on a new direction. A couple of ideas to get things started:

1. Using a single file to store all checkpoint positions. This was recommended by @anton-ryzhov via https://github.com/timberio/vector/issues/1427#issuecomment-583447232.
2. Using `leveldb` since we seem to be committed to it.
3. Proposing an alternative solution, something specifically designed for persisting state across Vector, such as SQLite (not used for disk buffering, obviously).

**Comment by binarylogic** [comment]
@lukesteensen I need you to weigh in with anything you're thinking so I can delegate this.

**Comment by lukesteensen** [comment]
I think the simplest improvement would be to migrate to a single JSON file per-source. This is likely the smallest change from where we are now and gives us pretty much all of the benefits.

In the longer term, we'll likely come up with a more reusable system for giving components access to namespaced persistent state, but I don't think we need to block these user-facing improvements on figuring that out.
