### ISSUE TITLE
Move tests which require presence of `/etc/resolv.conf` file behind a feature flag

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#1803]
Currently many of our tests rely on presence of file `/etc/resolv.conf` which is used by `trust-dns-resolver` [here](https://github.com/bluejekyll/trust-dns/blob/c877d7611d7d2b4ff4094b4a2c017df3ff2cb4f0/crates/resolver/src/system_conf/unix.rs#L29-L31).

This causes `cargo test` fail with `No such file or directory` error if there is no such file. It is problematic because it makes it impossible to enable running tests as part of building of `vector` package on NixOS, see https://github.com/NixOS/nixpkgs/pull/79224.

**Comment by Hoverbear** [comment]
It's such a bummer that it's hardcoded! Could we open an issue on https://github.com/bluejekyll/trust-dns/blob/c877d7611d7d2b4ff4094b4a2c017df3ff2cb4f0/crates/resolver/src/system_conf/unix.rs#L29-L31 ? @bluejekyll might appreciate it. :)

**Comment by a-rodin** [comment]
@Hoverbear The idea about opening an issue is good, but might it still  not work with an arbitrary location of `resolv.conf` file because it looks like NixOS builds are completely isolated from network, so I'm not sure would DNS resolution work at all or not. I hope a simpler fix in https://github.com/timberio/vector/pull/1874 can help to just disable accessing `/etc/resolv.conf` at all during the tests.
