### ISSUE TITLE
Add behavior test for merging nested values

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#1807]
Since nested values (`Value::Map`) is a thing now, there should be tests to ensure merging logic works properly for `Value`s with nested fields. Addressing nested fields is done, as before, with the `.` notation, and, in general, this should behave the same as it did before the real nesting was introduced.

Related to #1662.

**Comment by MOZGIII** [comment]
Can a test have multiple input messages?

**Comment by MOZGIII** [comment]
Seems like they don't.

To accurately test the behavior of the merge transform, we need to simulate the scenario when the transform takes in two (or more) events and produces a single event.

@Jeffail, since you implemented tests, can you help? How should I approach this?

**Comment by Jeffail** [comment]
Hey @MOZGIII, I can fairly easily expand the spec to support multiple inputs, which makes sense given we're introducing transforms that aggregate >1 events. Opened https://github.com/timberio/vector/issues/1819.
