### ISSUE TITLE
Don't exit on first configuration error when watching configuration files 

### ISSUE THREAD

**Issue by ktff** [timberio/vector#1816]
### Context
When starting process, if configuration has any error, the process will exit.

### Change
If we are watching configuration files for changes, process could remain running and not do anything until a valid configuration has been loaded.

### Implementation
Should be simple as a loop of waiting for `SIGHUP`, loading, and validating configuration.

### Motivation
In cases when configuration files are being watched, this would streamline fixing configuration errors. From having two cases:
 - Error in first loaded configuration requires starting Vector again.
 - Error after first successful configuration doesn't require starting Vector.

To one case:
 - All configuration errors can be fixed by simply changing the configuration files.

### Downside
"Vector is running" won't anymore mean "Vector is doing something".

**Comment by binarylogic** [comment]
Thanks. I'd like to get consensus from others on the team before we do this.

**Comment by a-rodin** [comment]
> "Vector is running" won't anymore mean "Vector is doing something".

If this behavior is enabled only explicitly, in addition to the usual config watching, and documented, then I think it should not be a source of confusion.

**Comment by ktff** [comment]
@a-rodin 

> If this behavior is enabled only explicitly

The `--watch-config=always (or, -ww)` flag you proposed in #2002 seems like a good choice.

**Comment by binarylogic** [comment]
@MOZGIII would you mind reviewing this and closing if it is no longer relevant?

**Comment by MOZGIII** [comment]
As part of the RFC 2221, we chose to not reload config at runtime. Thus I'm closing this.
