### ISSUE TITLE
Add new `TransformContext` type

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#1839]
We should add a new `TransformContext` type similar to `SinkContext` which would allow us to bundle both a task executor and our dns resolver so that transforms can use these.

The updated trait should look like:

```rust
#[typetag::serde(tag = "type")]
pub trait TransformConfig: core::fmt::Debug {
    fn build(&self, cx: TransformContext) -> crate::Result<Box<dyn transforms::Transform>>;

    fn input_type(&self) -> DataType;

    fn output_type(&self) -> DataType;

    fn transform_type(&self) -> &'static str;
}
```

**Comment by binarylogic** [comment]
Is this blocking any work?

**Comment by LucioFranco** [comment]
I opened this in conjunction with my review here https://github.com/timberio/vector/pull/1746#pullrequestreview-360439678

I don't think its directly blocking but we do have a case where we are not using our built in resolver and have some duplicated code.

**Comment by binarylogic** [comment]
How difficult is this? If it's a couple of hours or less I think it's worth doing now.

**Comment by LucioFranco** [comment]
@binarylogic this should be very easy, just mechanical and time consuming.

**Comment by binarylogic** [comment]
@ktff how do you feel about doing this in a separate PR for https://github.com/timberio/vector/pull/1746? Basically:

1. Create a new PR that addresses this
2. Merge it
3. Rebase https://github.com/timberio/vector/pull/1746.

**Comment by ktff** [comment]
@binarylogic Sounds good. It will be need for  #1072.
