### ISSUE TITLE
Add sematext_metrics sink (wrap Influx API?)

### ISSUE THREAD

**Issue by otisg** [timberio/vector#1845]
Note that the metrics ingestion API is the same as Influx API, which means that when you guys have the Influx sink (#562) done, `sematext_metrics` sink could reuse the implementation / wrap the new `influxdb_metrics` sink.

See https://github.com/timberio/vector/issues/1000#issuecomment-587677314 for context.

**Comment by otisg** [comment]
@binarylogic @LucioFranco now that #562 is done would you be able to add 'sematext_metrics' sink?  Should be just a simple wrapper around 'influxdb_metrics' sink.

**Comment by binarylogic** [comment]
Hi @otisg, sure, I just want to confirm. @LucioFranco is this possible for wrapping metrics sinks? I know the author of the `influxdb_metrics` sink put a considerable amount of effort into that PR.

**Comment by LucioFranco** [comment]
Yup, it should be possible to just wrap it.

**Comment by otisg** [comment]
@LucioFranco Is this something you could do please?

**Comment by otisg** [comment]
@binarylogic any way you could revisit this please?
