### ISSUE TITLE
s3 sink tower_limit errors 

### ISSUE THREAD

**Issue by mikhno-s** [timberio/vector#1850]
Hey!
I have a lot of errors and after each vector stops. (with RUST_BACKTRACE=full)

```
Feb 19 09:08:55.136  TRACE sink{name=s3_logs type=aws_s3}: tower_limit::rate::service: rate limit exceeded, disabling service
thread 'tokio-runtime-worker-4' panicked at 'service not ready; poll_ready must be called first', /opt/rust/registry/src/github.com-1ecc6299db9ec823/tower-limit-0.1.1/src/rate/service.rs:107:35
stack backtrace:
   0:           0xb80aca - <unknown>
   1:           0x6c5c5c - <unknown>
   2:           0xb80266 - <unknown>
   3:           0xb7feb1 - <unknown>
   4:           0xb7f4f1 - <unknown>
   5:          0x127c864 - <unknown>
   6:          0x13dba2c - <unknown>
   7:           0xd92d49 - <unknown>
   8:          0x11a91cb - <unknown>
   9:          0x140fd99 - <unknown>
  10:           0xdf759c - <unknown>
  11:           0xbd5f2e - <unknown>
  12:           0xbd165c - <unknown>
  13:           0xbd0bb7 - <unknown>
  14:           0xba89df - <unknown>
  15:           0xbabb8e - <unknown>
  16:           0xbcdbeb - <unknown>
  17:           0xbce50a - <unknown>
  18:           0xb94f7f - <unknown>
  19:           0xb97440 - <unknown>
Feb 19 09:08:55.550  ERROR vector::topology: Unhandled error
Feb 19 09:08:55.550  INFO vector: Shutting down.
```

What does this error mean and what can trigger rate limiter?

**Comment by Jeffail** [comment]
Hey @mikhno-s,

Sorry that this has impacted you! How regularly does this panic occur? And are you able to share any details about your configuration (and Vector version)?

In order to get more information it might be necessary to run a debug version of Vector, would you be willing to try that out? If so would you be comfortable building it yourself or would you like assistance?

Hopefully we can narrow this down quickly.

**Comment by LucioFranco** [comment]
@mikhno-s this was fixed here https://github.com/timberio/vector/pull/1569, so looks like you're on an older version that is affected.

**Comment by binarylogic** [comment]
And thanks for letting us know! We'll reopen if this didn't resolve your issue.
