### ISSUE TITLE
Fields set in `lua` transform are not available in templates

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1857]
This was posted in our chat:

> Hello, I am routing glog file to elasticsearch.
> ```
> [transforms.add_metadata] 
>  type = "lua"
>  inputs = ["src"]
>  source = """
> event['app'] = event['file']:match('/log/(.+)%.INFO')
> """
>
>[sinks.proj_sink]
>  type = "elasticsearch"
>  inputs = ["add_metadata"]
>  host = "http://1.2.3.4:5"
>  index = "proj-{{host}}-{{app}}"
> ```
>
> The above snippet does not work. The log shows nothing.
> However
> ```
>  index = "proj-{{host}}"
> ```
> works and msgs have correct app field. Why can't I use {{app}} in index?

**Comment by binarylogic** [comment]
I have a suspicion that the `app` field being set in the `lua` transform is not successful, and is being set to a `null` value. When you set a field to `null` in the `lua` transform it effectively removes the field.

**Comment by binarylogic** [comment]
@elbaro let us know if we're missing anything.

**Comment by donggu-prestolabs** [comment]
@binarylogic when I use `index = "proj-{{host}}"` I can see all records have non-null `app` field in Kibana.

I debug-printed from lua script
```
  source = """
event['app'] = event['file']:match('/log/(.+)%.INFO')
print('event app: ')
print(event['app'])
"""
```
and `docker logs vector` shows it has correct values:
```
Feb 20 04:07:29.564  WARN transform{name=parse_glog type=regex}: vector::transforms::regex_parser: Regex pattern failed to match. field="Log file created at: 2020/02/20 13:07:29" rate_limit_secs=30
Feb 20 04:07:29.564  WARN transform{name=parse_glog type=regex}: vector::transforms::regex_parser: "Regex pattern failed to match." is being rate limited. rate_limit_secs=5
event app: 
app_name
event app: 
app_name
event app: 
app_name
event app: 
app_name
event app: 
app_name
event app: 
app_name
event app: 
app_name
```

**Comment by elbaro** [comment]
@binarylogic

I think it silently drops when the {{app}} includes a slash.
Should elasticsearch sink emit an error msg for this?

**Comment by binarylogic** [comment]
I see, thanks for letting us know.

Yes, Vector should log an error when this happens. The issue is that the Elasticsearch `/_bulk` endpoint allows for partial failures (which happens with invalid index names). When this happens a 200 is returned and error detail is included in the response body. Parsing this body can cause performance issues because it can be very large, but we'll at least log an error message making this known. I've opened https://github.com/timberio/vector/issues/1865 to address this.

In the interim, these errors should also be available in the Elasticsearch logs themselves.

**Comment by binarylogic** [comment]
@elbaro I am closing this in favor of #1865. Please let us know if this doesn't resolve your issue (at least on the Vector side).
