### ISSUE TITLE
Automatically adjust backoff values RFC

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1858]
## Overview

A very common problem Vector users run into is internal service rate limiting:

```
Feb 18 22:11:25.128  TRACE sink{name=s3_logs type=aws_s3}: tower_limit::rate::service: rate limit exceeded, disabling service
```

To be clear, this is not S3 rate-limiting us, this is Vector's own internal rate limiting controlled via the [`request.rate_limit_num` option](https://vector.dev/docs/reference/sinks/aws_s3/#rate_limit_num). This problem is more pronounced in the case of self-hosted, variable size services like Elasticsearch.

Alternatively, users can run into the opposite problem, which is over-provisioning. This means overwhelming a downstream service to the point where it becomes unresponsive and starts queueing requests.

## Proposed Solution

It would be nice if Vector could adjust itself automatically based on feedback from the downstream service. For example, Vector could start with conservative rate-limits and continually try to push the boundaries until it receives feedback otherwise. "Feedback" in this context could be errors, timeouts, and high response times. This, of course, gets tricky since some users deploy hundreds of instances of Vector, but that is the point of this algorithm. In my opinion, Netflix [solved this well](https://github.com/Netflix/concurrency-limits).

## Prior Art

1. https://rocksdb.org/blog/2017/12/18/17-auto-tuned-rate-limiter.html
2. https://github.com/Netflix/concurrency-limits

## Light-weight solutions

In addition to implementing and algorithm we should:

1. Improve the error message so it's more obvious the user can adjust the `rate_limit_num` option.
2. Raise the level to `warn`
3. Include `rate_limit_num` in the "common" options of relevant sinks/sources.

**Comment by lukesteensen** [comment]
This sounds more like retry backoffs than rate limiting. We could just not set rate limits by default and rely on the backoff to accomplish this.

**Comment by binarylogic** [comment]
That's a good point. After doing some light research it seems like an algorithm that incorporates increasing the rate is closer to what I was thinking. I am not an expert in this area, clearly 😄, but something like AIMD or MIMD seems relevant. I thought [this paper](https://cs.nyu.edu/courses/fall17/CSCI-UA.0480-009/lectures/lec7.pdf) was interesting. Specifically:

> The name AIMD should make sense now.  It captures the fact that the window size increases additivity but decreases multiplicatively. Why pick this combination? You could imagine several other possibilities: Increase Additive Decrease (AIAD), Multiplicative Increase Multiplicative Decrease (MIMD), and MultiplicativeIncrease Additive Decrease (MIAD). The short answer is that you want to be ginger when increasing so that you don’t overwhelm the network, but you want to back off really quickly at the first sign of trouble. In other words, it is easier to drive the network into the overload and hence we should be careful about increasing. But, it’s not terrible if we are going to be underutilizing the network a little bit. Hence, we should back off quick

The idea that Vector can adapt to utilize throughput capacity is a very nice feature of a router.

**Comment by lukesteensen** [comment]
Yeah, we could potentially do something along though lines. We'd just want to be careful and think about interactions with existing mechanisms like backoff, and the potential for reacting inappropriately to non-load-related errors.

We were already discussing inlining our rate-limiting middleware to solve a logging oddity (#1391), and it shouldn't be terribly difficult to extend that with a feedback mechanism for adjusting the rate. We would need to think about how we'd expose that through configuration as well.

**Comment by binarylogic** [comment]
Another interesting prior art example from Netflix: https://github.com/Netflix/concurrency-limits

**Comment by LucioFranco** [comment]
Something also related that we just implemented in `hyper` is BDP https://github.com/hyperium/hyper/blob/master/src/proto/h2/ping.rs#L389

BDP is a way to adjust the size of the window for HTTP/TCP connections and is somewhat related to what we want to do here. Where you can think of the rate limit as a sliding window. https://en.wikipedia.org/wiki/Bandwidth-delay_product

**Comment by binarylogic** [comment]
I'm triple confirming that this is an important feature. I'm currently attempting to benchmark Vector and keep getting tripped up on rate limit errors. I've raised the `request.in_flight_limit` and `request.rate_limit_num` settings to arbitrarily large numbers but I have no idea if they align with the downstream capacity. I can only imagine how difficult this is in an environment where concurrency is variable (number of Vector instances) and capacity is changing.

**Comment by lukesteensen** [comment]
A nice side effect here is that we'll be able to replace `tower-limit`, which has a weird workaround for logging at `TRACE` even when our normal log level is set higher.

The approach from the Netflix project looks promising, we'll just want to be careful that we are measuring true round trip time and not any other internal waiting time.

**Comment by LucioFranco** [comment]
One thing I'd like to note, is we will be upgrading to newer versions of tower and tokio so this means any new implementation should focus on newer versions of tower.

**Comment by binarylogic** [comment]
Thanks. I'm also wondering if this might be best solved entirely external from Vector as an extension of our HTTP client.

**Comment by LucioFranco** [comment]
Our HTTP client uses tower as its solution for implementing abstract middleware on top of the wire connection. I don't think it would make sense to implement something like this within nyper at all.

**Comment by lukesteensen** [comment]
Yeah, there should not be in-built rate-limiting in the HTTP client. A tower layer is the right abstraction.

**Comment by binarylogic** [comment]
Closing via https://github.com/timberio/vector/pull/2329
