### ISSUE TITLE
Elasticsearch partial failures are not logged

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1865]
The `elasticsearch` sink uses the Elasticsearch `/_bulk` endpoint for flushing data. This is prone to partial failures, and Elasticsearch will respond with the error count. You can see a response example [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#docs-bulk-api-example). Notice the `errors` (boolean) as well as the. We should log a detailed error when this happens.

There is a caveat with this, notice that a summary of every single item is returned (in typical ES fashion, ref https://github.com/timberio/vector/issues/1857). Reading this response could consume quite a bit of memory. I've seen tricks where the client will only read the first X bytes of the response and then search for the presence of `/"errors": true/`. I would be in favor of doing this if there is not a better alternative.

## Requirements

- [ ] Log when Elasticsearch returns `"errors": true` in the response body. Because we can't get details information without parsing the entire response, we should start simple and just let the user know this happened.
- [ ] Avoid reading the entire response body into memory since this could be very large.

**Comment by bruceg** [comment]
I have written code that should accomplish this check, but am having difficulty figuring out how to force an error that would cause an error, and to check that the error happens. I welcome suggestions how to test this.

**Comment by binarylogic** [comment]
You should be able to recreate this error by changing a field value's type. Ex:

Document 1:

```json
{"string_field": "hello world"}
```

Document 2:

```json
{"string_field": 1}
```

Elasticsearch will reject the second document due to a type mismatch.
