### ISSUE TITLE
Add `log_schema.kubernetes_key` global option

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1867]
Similar to https://github.com/timberio/vector/issues/1823 we need to:

- [x] Add a `log_schema.kubernetes_key` option. This should
- [ ] Use this key in the `kubernetes` source
- [x] Use this key in the `kubernetes_metadata` transform
- [ ] Use this key when mapping in the `loki` and `datadog` sinks. Any others? Should we open these as separate issues?

**Comment by LucioFranco** [comment]
Looks like we can add the first two in this list today but the rest are blocked on the `kubernetes_pod_metadata` transform.

**Comment by MOZGIII** [comment]
I feel like this needs an RFC. We need a way to dynamically extend the schema and refer to the fields in it.

Practically, implementing this PR would be a simple task, yet, I'm a bit hesitant with this approach. As I understand, the main goal would be to automate the interoperation with `loki` and other sources that follow the same idea of having a semi-manually composed subset of fields that are considered interesting (`labels` in particular in `loki`). There are a couple of alternative approaches that seem to be a better fit for that particular task.

I'll elaborate more on this in a dedicated issue.

We can omit this issue from v1 feature set for now.

**Comment by binarylogic** [comment]
I agree. I think all of the field mapping in sinks is better served with metadata about fields instead of a strict a schema.

**Comment by MOZGIII** [comment]
Should we close this one?
