### ISSUE TITLE
The `split` transform `separate` option should support Regex

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1881]
Users should be able to supply regex patterns for the `split` transform `separate` option. For performance reasons, this should remain literal unless the value starts and ends with `/` and ends with `/`.

**Comment by lukesteensen** [comment]
> For performance reasons, this should remain literal unless the value starts and ends with `/` and ends with `/`.

I don't think this is necessary. The `regex` crate is very intelligent about doing fast string matching when the pattern is static.

**Comment by psinghal20** [comment]
@binarylogic @lukesteensen I would love to take up this issue if no one is working on it. 

> I don't think this is necessary. The regex crate is very intelligent about doing fast string matching when the pattern is static.

If there is no performance hit in the case of literals, we can just modify the `separator` field in the `split` transform to accept a regex, and use `re.split` to split the input text. Do I understand it right?

**Comment by bruceg** [comment]
That is close to right. We need to decide what to do about regex meta-characters—if we don't escape them, existing configurations that split on a pattern that contains one will break.

FTR I [just benchmarked this](https://github.com/timberio/vector/issues/2833#issuecomment-649096299) and regex is actually faster than `str::contains` for a single string. So, assuming `Regex::split` uses the same logic, it could potentially even be an optimization.

**Comment by psinghal20** [comment]
@bruceg If we don't want to introduce any breaking changes right now, maybe we can add an enum for the separator field, allowing for literal patterns as well as the regex, but we would lose the performance improvements you mentioned. What do you think?

**Comment by binarylogic** [comment]
Closing in favor of https://github.com/timberio/vector/issues/3745.
