### ISSUE TITLE
A minimal, Rust-native scripting transform

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1926]
## The Problem

@Hoverbear is working through a [number of schema improvements](https://github.com/timberio/vector/milestone/31), part of that work addresses fundamental transform operations such as the `add_fields`, `remove_fields`, and `rename_fields` transforms. While these simply "get the job done", there is concern on the team that these transforms are too primitive. The UX delivered by chaining together such simple transforms is clunky, unproductive, and hard to read. There are also under-the-hood complexity and performance implications. For example, events must now run through a series of topology components which have an inherent performance cost compared to simple functions. From a UX perspective the `lua` and (upcoming) `javascript` transform are much better options, but there is a performance hit. If performance was not a factor, I'd recommend that we ditch these transforms in favor of the `lua` or the `javascript` transform.

## Problem Shaping

If you take a step back, what we're really discussing are three things:

1. **Syntax** - Trying to retrofit these operations as Vector components in the TOML syntax is not ideal.
2. **Fundamental operation/transform boundary** (#1731) - Adding individual transforms for fundamental operations is noisy and clunky. It takes away from Vector's simplicity, making it harder to discover transforms and adopt Vector.
3. **Performance** - The solution should be similar, if not the same, performance-wise as chaining together the `add_fields`, `remove_fields`, and `rename_fields` transforms.

## Prior Solutions

We've gone back and forth on this discussion, coming at it from different angles. I'll address previous solutions and why I don't think they're correct:

* #750 (`shape` transform) - This solution was close, but the syntax proposed was still bad (TOML), violating problem 1 above.
* #1653 (`compose` transform) - This felt like a more generic/powerful transform to the `shape` transform, but it violates both problem 1 and 2 above.

## Proposed Solutions

I'll propose a variety of solutions to help shape how we're thinking about this problem. Some of them are obviously bad ideas 😄 .

1. Somehow bypass the full `lua` and `javascript` runtimes if we find that the operations are simple enough to execute natively in Rust.
    * Pro: We aren't creating a new language.
    * Con: It's not obvious to users that they are _not_ making a performance tradeoff. Users, by default, expect a performance hit when reaching for these languages.
    * Con: It seems prone to error.
    * Con: We are locked into whatever language we choose for simple operations.
2. Do the same as above but with a new language like `ruby`, `python`, etc.
    * Pros and cons are the same as above
3. Create our own _very_ simple syntax for mutating events (ex: a `mutate` transform)
    * Pro: Obvious to users that it's limited and designed for performance
    * Pro: It can evolve as a "catch-all" for future fundamental operations
    * Con: Creating our own syntax
    * Con: Learning curve for users.
4. Create an entire scripting language used to build topologies, replacing `vector.toml` (#1328)
    * Pro: High flexibility
    * Pro: Expressive and easier to read (control-flow statements like `if/else`, `switch`, etc are easier)
    * Pro: Unit testing is arguably easier and simpler.
    * Con: High risk. Lots of time and work. Very difficult to get right.
    * Con: Much steeper learning curve.

**Comment by Hoverbear** [comment]
Perhaps we could bundle a WASM runtime, and (running inside of that runtime) we also ship a super simple 'blessed' language compiler (Eg typescript), then  users could point vector at either a .wasm module, a typescript file, or just some typescript itself... then we can compile/load it at start time and use that.

So users can go ahead and have

```toml
[transforms.add_field]
type = "typescript"
action = """
  event["xyz"] = 123;
"""
```


Or

```toml
[transforms.rename]
type = "typescript"
source = "foo.wasm"
```

**Comment by lukesteensen** [comment]
Some interesting prior art on implementing a small interpreter in Rust: https://blog.cloudflare.com/building-fast-interpreters-in-rust/

**Comment by Jeffail** [comment]
From what I've seen there's a huge gap in this field for a widely adopted general purpose mapping syntax, this could be an opportunity for us to do something cool.

A project worth looking at is https://idml.io/, which is currently being used to do basically all schema to schema mapping at Meltwater. It has a very cool and powerful syntax, take a look at some of these expressions: https://idml.io/features/expressions.html#coalesce. It's heavily battle tested in production use cases, is pretty easy to read and write, and is very maintainable.

Adopting something like this gives users a lot of power without the performance implications (and opportunities for users to shoot themselves in the foot) of a full runtime.

We could start small and build an interpreter for a subset of the most basic features like simple assignments and arithmetic. If we like where that takes us maybe we can help out with the project, it's getting a lot of use internally but could do with some help in building a community around it.

**Comment by binarylogic** [comment]
Here's another use case I saw in a customer's config:

```
[transforms.company_api_timestamp]
type = "split"
inputs = ["company_api_json"]
field = "timestamp"
field_names = ["timestamp"]
separator = "."
```

These little operations would be much better solved with something like this.

**Comment by binarylogic** [comment]
Sorry to spam this issue. If we can expand our template syntax that might be sufficient for these operations. See #2063. This would make the `add_fields` transform much more powerful:

```toml
[transforms.modify]
  type = "add_fields"
  fields.user_id = "{{ user_id | default: "unknown" }}"
```

Additionally, we could still consider a simple syntax like the one proposed by @Jeffail .

**Comment by Hoverbear** [comment]
We could use `tera` for this! https://tera.netlify.com/ It's basically jninja or the Django language.

**Comment by binarylogic** [comment]
Closing in favor of https://github.com/timberio/vector/issues/2744
