### ISSUE TITLE
External cache resource

### ISSUE THREAD

**Issue by DpoBoceka** [timberio/vector#1957]
Hi. Imagine you’re in position to implement mutual collaboration with some external cache of a few Vector instances simultaneously. 
The required methods against such cache would be  SET, GET, EXISTS. After successful operation Vector should continue its transforms. In a nutshell, it is a simple correlation engine - you just need to catch a fact that certain events occurred on your flow somewhere under specific timeframe and order. 
But you don’t know which Vector is going to process one of those correlation participants, hence the external cache. 
Is it safe for me to surmise that it is, in fact, feasible with `lua`, if an appropriate function is found to connect to the cache of my choice?
How would you propose to resolve such use case, or is it completely out of Vector’s scope?

**Comment by Jeffail** [comment]
Hey @DpoBoceka, it's almost certainly possible with the lua transform but it's a stretch from how it's intended to be used, and therefore performance is not likely to be great. There are currently no plans to have coordination between distributed deployments of Vector, although that's not to say that it won't ever happen.

**Comment by binarylogic** [comment]
Thanks @DpoBoceka, closing based on @Jeffail's comment.
