### ISSUE TITLE
Add batch_quantity for relevant HTTP sinks

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#197]
In some cases, the max buffer size should implement a quantity limit in addition to it's byte size limit. This is helpful for sinks that impose quantity limits, like Kinesis:

> Each PutRecords request can support up to 500 records. Each record in the request can be as large as 1 MiB, up to a limit of 5 MiB for the entire request, including partition keys. Each shard can support writes up to 1,000 records per second, up to a maximum data write total of 1 MiB per second.

**Comment by bruceg** [comment]
I think this is closed by #2866 since all batch sinks now handle a `batch.max_events` configuration.
