### ISSUE TITLE
statsd source - support DD

### ISSUE THREAD

**Issue by afoninsky** [timberio/vector#1974]
I have an error trying to switch from DataDog agent to Vector.
```
vector-6f95d89b5c-m48c9 vector Mar 03 14:46:50.423 ERROR source{name=statsd type=statsd}: vector::sources::statsd: Statsd parse error: UnknownMetricType("d")
```
Looks like services support it. Example: https://github.com/prometheus/statsd_exporter
```
Note that timers will be accepted with the ms, h, and d statsd types. The first two are timers and histograms and the d type is for DataDog's "distribution" type. The distribution type is treated identically to timers and histograms.
```
It's a good idea to support DD specific types so Vector can replace DD agent. What do you think?

**Comment by binarylogic** [comment]
Very much agree! We'll build out support for this. We're planning to focus heavily on metrics this quarter.

**Comment by afoninsky** [comment]
https://github.com/timberio/vector/issues/2603 - same issue here

**Comment by binarylogic** [comment]
@afoninsky I'm closing this in favor of #2603 and https://github.com/timberio/vector/pull/2913. Vector should no longer error on this type but we still have work to do sending distributions to Datadog. We are working with Datadog to get clarity on the issues described in #3130.
