### ISSUE TITLE
Benchmark Vector with `mimalloc` memory allocator instead of default `jemalloc`

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#1985]
Currently Vector uses `jemalloc` as the memory allocator. It provides some performance improvements over Rust's default memory allocator. See https://github.com/timberio/vector/pull/310 for benchmarks.

It would be nice to benchmark Vector with [`mimalloc`](https://docs.rs/mimalloc/0.1.17/mimalloc/) to see whether it gives further performance improvements.

**Comment by Hoverbear** [comment]
We were recently marvelling about snalloc as well!

**Comment by binarylogic** [comment]
We performed extensive testing against jemalloc, mimalloc, and musl. The results of these tests is what prompted our switch to jemalloc + gnu as our new default. Here are the results for posterity:

![image](https://user-images.githubusercontent.com/1663286/89679671-9649e600-d8bf-11ea-9e21-fe9c3cccbf2e.png)
