### ISSUE TITLE
Support escaping in the field path notation

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#2005]
We should provide the ability to escape the `.`, `[`, and `]` characters in the field path notation:

```
parent.child[0]
```

**Comment by ktff** [comment]
Regarding #1888, interpreting everything after a, yet another, special character as an ordinary character would be sufficient/great. 

For example if such character is '#' than a path:
```
kubernetes.labels#app.kubernetes.io/name
``` 
would have only three parts/keys:

`kubernetes`, `labels`, and `app.kubernetes.io/name`.
