### ISSUE TITLE
Ability to call transform functions within a runtime

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#2015]
This has been discussed, and clarifies the intent behind https://github.com/timberio/vector/pull/2012. It is becoming clear that runtimes will likely replace the entire transform pipeline, at least for operations that cross the fundamental boundary. We can further encourage this by allowing users to call other "function" transforms from within runtimes.

Note, this should be limited to transforms that do not aggregate, only simple input/output transforms. For example, we should not allow users to call the `merge`, `dedupe`, or `transaction` transforms within a runtime since this would complicate the runtime APIs. I'm open to solutions for these, but I'm not sure they are worth it.

Finally, I do _not_ think we should address this in https://github.com/timberio/vector/pull/2000. We should defer this and follow up with this addition, assuming it is possible.

**Comment by Hoverbear** [comment]
This is interesting for #2006 as well since these would be hostcall candidates.

**Comment by binarylogic** [comment]
Removing this from the scripting project. It's not clear if this makes sense. I'm starting to think it does not since we are pushing users towards chaining transforms together instead of replacing the entire pipeline with a runtime.

**Comment by binarylogic** [comment]
Closing since this will be resolved in the new `remap` syntax. We'll add functions as it makes sense, and if possible share the code paths with any overlapping transforms. (Ex: JSON parsing).
