### ISSUE TITLE
Consider nested field syntax support with or without quotes

### ISSUE THREAD

**Issue by Hoverbear** [timberio/vector#2069]
In #2068 we found that users were using both quoted and unquoted syntax in their rename fields transforms (This is documented as a feature [here](https://vector.dev/docs/reference/transforms/rename_fields/). Since tables in toml require recursive flattening, this leads to some fun code!

Here's an example of table flattening code:

```rust
fn flatten(kv: (String, TomlValue), prequel: Option<String>) -> crate::Result<Vec<(String, TomlValue)>> {
    let (k, v) = kv;
    match v {
        TomlValue::String(s) => match prequel {
            Some(prequel) => Ok(vec![(format!("{}.{}", prequel, k).into(), s.into())]),
            None => Ok(vec![(k.into(), s.into())]),
        },
        TomlValue::Table(table) => {
            let results = table.into_iter().map(|sub_kv| {
                let key = match prequel {
                    Some(ref prequel) => format!("{}.{}", prequel, k),
                    None => k.clone(),
                };
                flatten(sub_kv, Some(key))
            }).collect::<crate::Result<Vec<_>>>()?;
            Ok(results.into_iter().flat_map(|v| v).collect::<Vec<_>>())
        }
        TomlValue::Integer(_)
        | TomlValue::Float(_)
        | TomlValue::Boolean(_)
        | TomlValue::Datetime(_)
        | TomlValue::Array(_) => Err(Box::new(FlattenError::CannotFlatten { key: k })),
    }
}
```

A discussion with @binarylogic lead us to wonder where we should focus on our support, or how to ensure this is consistently implemented. Do we support both? Are they equivalent?

**Comment by a-rodin** [comment]
I'm in favor of supporting both syntaxes, as it allows the users to avoid thinking too much about intricacies of TOML syntax.

**Comment by binarylogic** [comment]
Closing since the path syntax will be replaced with the new `remap` syntax, which supports better path notations. You can see examples [here](https://github.com/timberio/vector/blob/master/rfcs/2020-07-21-2744-remapping-syntax.md#guide-level-proposal).
