### ISSUE TITLE
A polite PR review reminder

### ISSUE THREAD

**Issue by Hoverbear** [timberio/vector#2073]
Create a GA to remind us if we're being lazy loafs and need to review a PR.

* 24, 48, 72 grace period
* Squelch able
* To slack?

**Comment by Hoverbear** [comment]
We could try: https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-scheduled-reminders-for-pull-requests#creating-a-scheduled-reminder-for-a-team

**Comment by Hoverbear** [comment]
@binarylogic enabled that to try it!

**Comment by Hoverbear** [comment]
Has anyone seen these happening?

**Comment by binarylogic** [comment]
This is done
