### ISSUE TITLE
Use `bors` for squash merging PRs

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#2074]
I'd like to suggest that we start using https://bors.tech for merging PRs instead of going through the regular github UI. There are a couple reasons I think this would be useful. The number 1 big benefit that bors brings is that at merge time instead of going through the UI and merging instantly, it does another round of tests against the master branch to ensure that newly merged code still "works" against the current master and not the master at the time the PR author pushed/merged. This will help us where doc generation has changed on master but all check marks show green for a PR. Another advantage is that bors has the ability to automatically squash PRs and use the PR title as the commit message. This is something that has come up as an issue before.

I've used bors in many projects before and have been very happy with it. The big downside is that it takes a bit more time to merge PRs but I think that cost is fine.

cc @binarylogic

**Comment by Hoverbear** [comment]
Looks like it's not supported? https://github.com/bors-ng/bors-ng/issues/194

**Comment by LucioFranco** [comment]
https://github.com/bors-ng/bors-ng/pull/718 Maybe? :)

**Comment by Hoverbear** [comment]
Oh wow! Great! I wonder if GA can do this? Might be something available already.

**Comment by binarylogic** [comment]
Closing this. We can reopen if we bump into the problems mentioned here, especially since the specific example cited dealt with the website, which no longer lives in this repo.

**Comment by JeanMertz** [comment]
Re-opening this, as I had the same idea, and the CI situation is considerably worse right now due to

1) randomly failing tests (which @jamtur01 is working on to fix),
2) more integration tests (such as Kubernetes) which take a long time to run, and
3) more contributors, causing more merge conflicts and thus more rebases + re-runs of CI.

Here's my comment about it on Discord, to which others reacted positively:

> Have we ever considered using something similar to Bors to manage our merge queue?
> 
> I feel like we could significantly improve our CI/PR flow if a) we reduced the amount of checks that run on each commit on each PR, and b) not have to wait for a PR to be 100% green after someone approved it before being able to merge it.
> 
> Ideally, I'd love it if we had:
> 
> 1) a subset of (reasonably) fast tests/lints/... running for each PR
> 2) have a Bors-like flow that allows us to add something to the merge queue and forget about it
> 3) have that merge queue end up in a bigger merge branch which then runs the full Vector test suite, including all the Kubernetes stuff, etc.
> 4) have that merge branch auto-merge by the bot once all is green
> 
> I know there are some considerations (probably keeping our semantic commits is one of them, and not running Kubernetes on the CI for regular PRs (for example) when you're working on Kubernetes-related work can also be problematic), but I feel like there must be a path forward that reduces the amount of minutes our CI runs for each PR and the amount of time you have to wait and regularly check back to see if you can finally merge a PR to master.

**Comment by jamtur01** [comment]
Implemented a test.
