### ISSUE TITLE
Better support key paths of nested fields

### ISSUE THREAD

**Issue by Hoverbear** [timberio/vector#2078]
In these issues we noted some current complexity around handling the presence of `.` in nested fields:

https://github.com/timberio/vector/pull/1888#issuecomment-598676895

https://github.com/timberio/vector/pull/2077#discussion_r393331274

This ticket tracks improving this issue. There should be a common function which folks can use to work with these keys. Perhaps we can take inspiration from how https://doc.rust-lang.org/std/path/index.html works.

**Comment by a-rodin** [comment]
I think this is a duplicate of https://github.com/timberio/vector/issues/2005.

**Comment by Hoverbear** [comment]
Agreed, so https://github.com/timberio/vector/pull/2081 fixes this :)
