### ISSUE TITLE
Support Text Encoding of Humio sink

### ISSUE THREAD

**Issue by Hoverbear** [timberio/vector#2084]
According to the humio engineering team the HEC protocol does support text encoding, and our current implementation does not. :(

https://github.com/timberio/vector/blob/c8a5e4f3631a9f483cfcfcb2f25c0d3de6480feb/src/sinks/humio_logs.rs#L34-L37

This issue calls to for adding a text encoding option to Humio.

**Comment by LucioFranco** [comment]
Our hec sinks supports text? https://github.com/timberio/vector/blob/master/src/sinks/splunk_hec.rs#L65

Maybe they mean't the splunk hec api doesn't support `text/plain`?

**Comment by krestenkrab** [comment]
In the "Examples" section of this link: https://docs.splunk.com/Documentation/SplunkCloud/latest/Data/FormateventsforHTTPEventCollector you can see that the `"event"` attribute can be either *just* a string, or a JSON object.  When sending data that is really just lines from a file (or some other source of raw logs), it would be great if it was an option to deliver the simple form, i.e. `"event" : " ... single log line ..."`.   That what I meant anyway.

**Comment by lukesteensen** [comment]
@krestenkrab Yep, that is what the merged `text` encoding should be doing right now. It doesn't change the whole request body to text, just how each event is rendered within the JSON body.
