### ISSUE TITLE
Make it possible to specify only some of the global schema keys

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#2110]
Currently if one of the [log schema](https://vector.dev/docs/reference/global-options/#log_schema) keys is specified, but others are omitted, then Vector produces a configuration error.

For example, the following config file

`vector.toml`
```toml
log_schema.host_key = "instance_id"

[sources.stdin]
  type = "stdin"

[sinks.console]
  type = "console"
  inputs = ["stdin"]
  encoding = "json"
```

results in the following output

```
$ vector --config vector.toml 
Mar 20 22:43:23.186  INFO vector: Log level "info" is enabled.
Mar 20 22:43:23.186  INFO vector: Loading configs. path=["vector.toml"]
Mar 20 22:43:23.188 ERROR vector: Configuration error: "vector.toml": missing field `message_key`
```

I think it should be possible to specify only some of the global schema keys and use default values for others.

**Comment by Hoverbear** [comment]
I'll fix this, sorry!
