### ISSUE TITLE
Rename gcp_stackdriver_logging to gcp_stackdriver_logs

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#2119]
I didn't realize the naming discrepancy, but for consistency we should suffix component names with `_logs` or `_metrics`.

**Comment by bruceg** [comment]
The name of the product in Google's literature is either just "Logging" or "Stackdriver Logging", which is where the sink name comes from.

**Comment by binarylogic** [comment]
Yeah, for our purposes I want to establish a convention of suffixing component names with `_logs` or `_metrics`, even if the provider uses "logging".
