### ISSUE TITLE
Dynamic connection load balancing for HTTP sinks

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#2120]
This is somewhat related to #288 but differs in that this is for our `HttpSink` based sinks. Currently, all of our sinks use `HTTP/1.1` which does not support multiplexing requests on a single connection. Using `HTTP/2.0` would solve this but I don't think many of our downstream services support this (as far as I know).

To overcome this limitation we should consider supporting some sort of dynamic pool of connections for our http sinks. This would allow us to send http requests on multiple connections to ensure maximum throughput. We should also be able to set up rate/concurrency limits per connection or per sink.

Adding this support should be possible https://docs.rs/tower-balance/0.3.0/tower_balance/pool/index.html which fits in well with hyper. No changes to the sinks should be required besides adding new request configuration.

**Comment by a-rodin** [comment]
Related to  #762, #1786, and #2032.

**Comment by LucioFranco** [comment]
Ah good catch @a-rodin I missed #2032, should we close that one in favor of this one?

**Comment by a-rodin** [comment]
@LucioFranco I agree to close #2032 in favor of this one because this one is more detailed.

**Comment by lukesteensen** [comment]
To be clear, this is not "load balancing". This is connection pooling and I'd be quite surprised if it's not already happening behind the scenes? If it isn't, we'd be unable to send concurrent http requests.

**Comment by LucioFranco** [comment]
@lukesteensen I would still consider this load balancing since you are balancing the load on the connections, the big difference with the pool here is that it will increase the amount of connections you are balancing across. Hyper has single connection pooling where it will attempt to reuse a connection. But h1 requests are still not concurrent.

**Comment by lukesteensen** [comment]
> I would still consider this load balancing since you are balancing the load on the connections

Yes, it is technically balancing load across two things :smiley:. My argument is that it's not load balancing in a way that's particularly meaningful to users.

> Hyper has single connection pooling where it will attempt to reuse a connection. But h1 requests are still not concurrent.

Are you saying that none of our current http sinks will send more than one http request at a time and our `in_flight_limit` is a lie?

**Comment by LucioFranco** [comment]
> My argument is that it's not load balancing in a way that's particularly meaningful to users.

I'll give you this one, its not a user facing load balancer :P

> Are you saying that none of our current http sinks will send more than one http request at a time and our in_flight_limit is a lie?

In this case in flight means how many requests we have buffered in hyper iirc. As far as I know I think hyper has an unbounded channel that it sends to the connection task that will attempt to write as fast as possible. If we had h2 we could take more advantage. There could be more digging done here but this is what I got away with my chat with sean today.

**Comment by LucioFranco** [comment]
After a chat with @lukesteensen it actually turns out that hyper does infact create multiple concurrent connections and this may not be the bottleneck. I think the real bottle neck comes from this issue #299 which should be fixed in #2111. So I am going to close this issue since it is not as relevant anymore.
