### ISSUE TITLE
bug(networking): TLS reorganization work broke TCP source

### ISSUE THREAD

**Issue by bruceg** [timberio/vector#2123]
The TLS reorganization work in #2101 ended up breaking the TCP source tests, and I missed it. Reverting 67a75445 (Use MaybeTlsListener in TcpSource) fixes the problem, but undoes some of why we wanted the TLS reorganization in the first place. I have an idea what's going on and I'd like a second opinion if I have thought it through properly, because the fix isn't straightforward.

The `MaybeTlsIncoming` type (introduced in b22e4d39a60b3e35e605d1f3997c32e14886853d) is intended to be a replacement for the `TcpListener` class, returning a stream of connected and negotiated `MaybeTlsStream`. It does this, but only for one stream at a time. If a second incoming connection comes while it's negotiating the first, it won't accept it, as it is in the wrong state.

Am I on the right track, or have I missed something in the type layers? If I'm right, this also implies the `splunk_hec` and `logplex` sources also have issues, as they were the first users.

I see two ways of handling this, neither particularly appealing:

1. When working as a TLS acceptor, maintain a set of accepted streams within `MaybeTlsIncoming` and handle their negotiation in `poll` before returning any. This keeps the code outside of `src/tls` clean but adds a lot of state management to this class.

2. Force all other code to do the TLS negotiation step by turning `MaybeTlsIncoming::poll` into a trivial wrapper for `incoming.poll` and then handle the negotiation in the returned struct, with non-TLS negotiation being a straight return. This requires extra steps in everything that uses this, but keeps the TLS lib saner.

As this is a regression on master, I am inclined to revert first and ask questions later, but if there is a simple fix I'd rather do that instead.

**Comment by LucioFranco** [comment]
@bruceg my initial implementation for `MaybeTlsIncoming` is actually flawed, we should push the handshake into `MaybeTlsStream`. We can reference this implementation https://github.com/seanmonstar/warp/blob/master/src/tls.rs#L182

So `MaybeTlsIncoming` should return a `MaybeTlsStream` that on first poll will (if enabled) attempt to complete the handshake then start streaming data.

**Comment by bruceg** [comment]
Do we want to be able to distinguish handshake errors from other I/O errors?

Should I do an immediate revert to let tests work for new PRs while I work on the full fix?

**Comment by LucioFranco** [comment]
@bruceg yeah, up to you how you want to do it, but reverting sounds fine to me.

As for the errors we probably want to sanfu them into a single error type that we will eventually erase via `Box<dyn Error>`.

**Comment by bruceg** [comment]
By distinguish, I am thinking of pushing the handshake into a new future that would then resolve into a `MaybeTlsStream`. This means all code that uses a `MaybeTlsIncoming` would require an extra step to get a stream, but they would be able to distinguish between the error happening during handshaking vs other stream errors, for better observability. Since it's more work, and we can adapt later, I'll just go with your original thought.

**Comment by LucioFranco** [comment]
@bruceg I think it makes sense to move the poll of the handshake into the `poll_read`/`poll_write` fn of the stream asyncread/write impl. like so https://github.com/seanmonstar/warp/blob/master/src/tls.rs#L211

This should simplify it and not require an extra future. This should also work well since we should be spawning a new task to poll the stream anyways so this won't block any other accepts and should be simple and just work.
