### ISSUE TITLE
New `aws_sqs` sink

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#2138]
From chat:
> can Vector output to AWS SQS?

There is a demand for supporting [AWS Simple Queue Service](https://aws.amazon.com/sqs/) as a sink. It is [supported by `rusoto`](https://rusoto.github.io/rusoto/rusoto_sqs/), so it seems to be possible to model it after other `aws_*` sinks.

**Comment by binarylogic** [comment]
Agree. Seems like we should have this is we're supporting GCP pubsub.

**Comment by fanatid** [comment]
Added in https://github.com/timberio/vector/pull/4675
