### ISSUE TITLE
Missing kubernetes labels on GH issues

### ISSUE THREAD

**Issue by Hoverbear** [timberio/vector#2151]
When attempting to label https://github.com/timberio/vector/pull/2134 I noticed we don't have labels such as `provider: kubernetes` as we do with others:

![image](https://user-images.githubusercontent.com/130903/77578439-cd31d900-6e95-11ea-92f3-c27d8038c83e.png)

Compared to:

![image](https://user-images.githubusercontent.com/130903/77578478-d91d9b00-6e95-11ea-8fc6-81b54f66a1a0.png)

Resolving this PR would add those tags.

**Comment by Hoverbear** [comment]
https://github.com/timberio/vector/pull/1888/ does part of this!

**Comment by LucioFranco** [comment]
@Hoverbear this is because @binarylogic originally wanted to not display kube docs, which is why we have a .bak file of it in the .meta folder. I think if we just enable that we should get labels?

**Comment by Hoverbear** [comment]
No problem. :)

**Comment by binarylogic** [comment]
These are now available
