### ISSUE TITLE
Excluding vector logs on Kubernets v1.13 and lower when `include_namespace` is not empty

### ISSUE THREAD

**Issue by ktff** [timberio/vector#2171]
A bug, discovered in #1970, which is causing a positive feedback loop of logs between `kubernetes` source and logs of vector process running it.

By default, we are excluding all logs from containers with a name with suffix `vector` from being collected. This default is turned off if we have `kubernetes` source configuration with any non empty `include_{namespace, name, uid}` options. 

This works as expected on v1.14 and higher but v1.13 and lower use different path scheme for the logs that don't include namespace in it. 

So, in cases when `kubernetes`
 - source is configured with:
    - non empty `include_namespace` option
    - empty `include_name` option
    - empty `include_uid` option 
 - run in Kubernetes cluster v.13 and lower

`vector` logs will be collected, and this bug will manifest. 

A quick fix would be to not turn off the default behavior for this exact scenario, but a more preferred solution is to find a more robust way of excluding `vector` logs from being collected.

**Comment by binarylogic** [comment]
Noting, it's likely that we won't support Kubernetes 1.13. Before working on this we should agree on our minimal Kubernetes version.

**Comment by MOZGIII** [comment]
This is addressed at part of the [k8s RFC](https://github.com/timberio/vector/pull/2222) ([rendered](https://github.com/timberio/vector/blob/k8s-rfc/rfcs/2020-04-04-2221-kubernetes-integration.md)).
