### ISSUE TITLE
Enable building TLS with in memory public/private keys

### ISSUE THREAD

**Issue by ktff** [timberio/vector#2172]
Currently `TlsSettings` are builded  with `TlsOptions` which accept paths to files with certificates. 

In the case of loading configuration on how to connect to Kubernetes cluster from `KUBECONFIG` file, we may load embeded ASCII public/private key from the file. 

This loading is done only for one test (`watch_pod`), so, before, it was solved by storing the public key in a tmp file and passed to `TlsOptions`. But this hack can't/shouldn't be done for private key, so currently `watch_pod` test is disabled for this reason.

**Comment by binarylogic** [comment]
@bruceg is this doable? What do you recommend as the best way to solve this?

**Comment by binarylogic** [comment]
@bruceg I'm assigning this to you since it appears to be blocking the Kubernetes integration. I just want to make sure this is the right way to solve/approach the problem before we proceed. I know there are a lot of ways to manage secrets, all of which are outside the scope of Vector.

**Comment by bruceg** [comment]
AFAICT the TLS settings handling can easily be modified to deal with non-file keys, since we already handle loading and parsing separately. The trick is how to get at the data if it isn't in a file. I could allow for an inline key in the config so the TLS settings just parses it directly, and then our tests can insert the key into the config structure.

I'm gathering this is a more general issue than just our tests though. Do I understand that correctly?

**Comment by ktff** [comment]
That would work.

Currently it's only one test, so I wouldn't consider it a priority. But it is a crucial feature in interacting with Kubernetes cluster from outside of it which would give us more design flexibility in future features like #1424 and #1293, and would also be a step in removing our dependecy on `kube`.

**Comment by bruceg** [comment]
For the test case, I could simply add additional optional fields `crt_text` and `key_text` that would contain the data inline. That should be pretty straightforward.

For the general case, though, what I'm thinking is to adding another creation function (something like `TlsSettings::from_options_with_certificate`) that would allow the Kubernetes source to pass in data that it has loaded from its configuration or secret store. Does this make sense?

**Comment by ktff** [comment]
The optional fields added in #2191 should be enough. 

And regarding `TlsSettings::from_options_with_certificate`, I'm not sure I understand what we would gain. Isn't it equivalent to the optional fields?

**Comment by bruceg** [comment]
No, with the addition of the optional text fields, the `_with_certificate` variants would not have much point since users of `TlsSettings` could just insert their TLS data into the `TlsOptions` before calling.

**Comment by binarylogic** [comment]
@MOZGIII do we still need this for the Kubernetes integration? If not, we can close.

**Comment by MOZGIII** [comment]
This problem remains even with our new k8s RFC. #2191 effectively provides the tools to solve it for the k8s case.

I'm linking this issue with #2191, so it's closed when #2191 lands.
