### ISSUE TITLE
Support file deletion after file has been read to the end

### ISSUE THREAD

**Issue by linshaoyong** [timberio/vector#2187]
Our data source comes from a directory, an external program keeps writing new files to this directory. Currently, we use flume(Spooling Directory Source) to meet the needs.

Now I want to replace some flume with Vector, because flume is more heavyweight and more resource-intensive. 

But Vector does not support file deletion, I don’t want to use an external program to delete because I don't know if Vector has read to the end of the file.

**Comment by binarylogic** [comment]
This is a reasonable request, and I've seen this option in other tools. @lukesteensen just assigning to you since you're working on the `file` source, but I assume this is pretty straightforward.

**Comment by linshaoyong** [comment]
[https://github.com/elastic/beats/issues/714](https://github.com/elastic/beats/issues/714)

> For everyone not using log rotation, it should be possible to create some scripts based on {your-language} that reads the registry file from filebeat and compares it to the existing files and the offset. If offset = file-size and did not modify for your predefined time, the script can remove it from disk.

This way is also acceptable.
