### ISSUE TITLE
Unknown variant papertrail

### ISSUE THREAD

**Issue by happysalada** [timberio/vector#2201]
when pasting the config for a papertrail sink, I get the following error

Configuration error: "/etc/vector/vector.toml": unknown variant `papertrail`, expected one of `aws_cloudwatch_logs`, `aws_cloudwatch_metrics`, `aws_kinesis_firehose`, `aws_kinesis_streams`, `aws_s3`, `blackhole`, `clickhouse`, `console`, `datadog_metrics`, `elasticsearch`, `file`, `gcp_cloud_storage`, `gcp_pubsub`, `gcp_stackdriver_logging`, `http`, `humio_logs`, `influxdb_metrics`, `kafka`, `logdna`, `loki`, `new_relic_logs`, `prometheus`, `sematext`, `socket`, `splunk_hec`, `statsd`, `vector` for key `sinks.out`

Is the docs not up to date, or will papertrail only be available in the next version?

I'm using timberio/vector:0.8.2-alpine

**Comment by Hoverbear** [comment]
Papertrail was merged in https://github.com/timberio/vector/pull/1835, which is so far unreleased. Please wait for 0.9.0 landing soon! I think @binarylogic is doing some QA before we cut it.

**Comment by binarylogic** [comment]
Closing since this has been released.
