### ISSUE TITLE
Test configuration reloading on Kubernetes

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#2224]
This might already be done, but it's part of our "Plan Of Attack" in https://github.com/timberio/vector/pull/2222. The purpose is to ensure that config reloading works properly:

- [ ] Reloading works as expected when a new _valid_ config is provided.
- [ ] Vector does not exit when a new _invalid_ config is provided.
- [ ] Vector logs a warning when a new _invalid_ config is provided, but it should not replace the config. It should continue with the old config until a valid config is provided.
- [ ] Vector eventually recovers when a new _valid_ config is provided.

It's likely all of these are satisfied but I want to add explicit tests for these. See #2002.

If any of these tests fail we should open issues for the work.

**Comment by MOZGIII** [comment]
Since we went with explicit config reloading at #2222, I'm closing this as no longer relevant.
