### ISSUE TITLE
Ability to manually trigger builds for a specific commit

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#2236]
It would be nice if we could manually trigger builds on a specific commit. This is useful for hotfixes and testing.

**Comment by Hoverbear** [comment]
Trigger builds of our CI? Or the release process?

**Comment by binarylogic** [comment]
This is likely a duplicate of https://github.com/timberio/vector/issues/2526, but I'm unsure which is the best direction. We should close the issue that does not represent the best direction.

**Comment by lukesteensen** [comment]
Yeah, it'd be great to be able to produce nightly-like artifacts from any given commit.

**Comment by Hoverbear** [comment]
How would you feel about producing nightly-level artifacts for every commit to the main branch?

**Comment by binarylogic** [comment]
Well, we want the ability to have a customer try out a fix in a branch before merging. Otherwise, I'm ok with it. It's free 😄 .

**Comment by Hoverbear** [comment]
I agree that's useful. :)

**Comment by Hoverbear** [comment]
Merging with #2526
