### ISSUE TITLE
Use GCP instance service account for sinks

### ISSUE THREAD

**Issue by gfrankliu** [timberio/vector#2243]
Most GCP related sinks (gcp_cloud_storage, gcp_pubsub, gcp_stackdriver_logs, etc) have credentials_path config where we can give the path to the service account private key json file. This means we have to download the SA private key which is insecure and hard for rotations.

Can we add support for retrieving that from the GCE instance metadata?
https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances

In case of GKE, we can also use the workload identity:
https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity

**Comment by binarylogic** [comment]
@bruceg has been working on this. Curious what you think @bruceg and how much work this would be?

**Comment by bruceg** [comment]
All authenticated GCP APIs require an access token to be passed along with each request. We already have a hook to fetch the access token on sink creation. If I'm reading right, for GCE instances it might be as simple as requesting this access token from the internal URL without credentials. If that's accurate, it'll probably take longer to test it than to implement it.

**Comment by gfrankliu** [comment]
Yes your understanding is correct. There are more code examples at https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances

We can certainly help on the testing if needed.

BTW GCS bucket has other ways for auth, eg: using signed URL. I will open a different one for that feature.

**Comment by gfrankliu** [comment]
@bruceg I opened https://github.com/timberio/vector/issues/2275 to capture feature request of using signed url to upload files to GCS.

**Comment by bruceg** [comment]
What makes sense for configuring this? If neither an `api_key` nor a `credentials_path` is configured, should it default to trying to retrieve an access token as an instance, or should there be an explicit flag to turn on this mode?

**Comment by gfrankliu** [comment]
Here is my suggestion:
1) if credentials_path is defined, use it.
2) next if $GOOGLE_APPLICATION_CREDENTIALS environment variable is defined, use it.
3) next if metadata service is available, use it
4) fail
Base on https://vector.dev/docs/reference/sinks/gcp_cloud_storage/#credentials_path we are already doing 1), 2). We can add the new feature as 3) so that if someone wants to explicitly use a service account, they can still do it via 1) or 2).

**Comment by lukesteensen** [comment]
Yes, I'd recommend something similar to what we do for AWS with Rusoto's [`ChainProvider`](https://docs.rs/rusoto_credential/0.41.1/rusoto_credential/struct.ChainProvider.html).
