### ISSUE TITLE
Support for Auto Keyvalue extraction via Transforms

### ISSUE THREAD

**Issue by raghu999** [timberio/vector#2246]
Hi first of all thanks for the amazing tool we are exploring Vector for different use cases and want to check if there is anyway we can do Key/Value extractions for logs which are not in json format. We used to use graylog and have this support natively [Graylog KV Extractor](https://docs.graylog.org/en/3.2/pages/extractors.html#automatically-extract-all-key-value-pairs) . With some digging I also found out that logstash supports this [Logstash KV Plugin](https://www.elastic.co/guide/en/logstash/current/plugins-filters-kv.html). Is this feature currently supported by vector if not can we get this added as a feature request. 

An example of our current logs: 

```
2020-04-07 16:48:12,752 [qtp1rer24-45666] INFO s=test c.c.a.f.AccessLoggingFilter  m="GET" http://example:9465/data/Account/49686441556/?maxResults=2147483647 status=200 duration=73 user-agent="ios" ip="76.x.x.x"
```
For the above in graylog we use a combination of grok extractor and K/V extractor to get timestamp and the fields extracted.

**Comment by lukesteensen** [comment]
Hi @raghu999! You can try the [logfmt transform](https://vector.dev/docs/reference/transforms/logfmt_parser/) for this. It does not require the entire message to be precisely formatted, and should be able to extract those key value pairs for you.

**Comment by raghu999** [comment]
Thanks @lukesteensen worked like a charm 

![Alt Text](https://media.giphy.com/media/CuMiNoTRz2bYc/giphy.gif)
