### ISSUE TITLE
Unable to fetch root ca certs on windows

### ISSUE THREAD

**Issue by thethomp** [timberio/vector#2256]
Hi all,

I'm trying to get some data written up to a Kinesis Data Stream. I've set my environment variables and the config verification works fine, but when I try to run it, I get the below error. I'm running this from a Windows 10 workstation.
```
Apr 07 17:20:20.288  INFO vector: Log level "debug" is enabled.
Apr 07 17:20:20.289  INFO vector: Loading configs. path=["config\\vector.toml"]
Apr 07 17:20:20.291  INFO vector: Vector is starting. version="0.8.2" git_version="v0.8.2" released="Fri, 06 Mar 2020 16:02:06 +0000" arch="x86_64"
Apr 07 17:20:20.301  INFO vector::topology: Running healthchecks.
Apr 07 17:20:20.328 ERROR vector::topology::builder: Healthcheck: Failed Reason: ListStreams failed: error trying to connect: the handshake failed: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl\statem\statem_clnt.c:1915:: unable to get local issuer certificate
Apr 07 17:20:20.330 ERROR vector::topology: Sinks unhealthy.
```
I couldn't find any reference to certs or anything in the documentation. Am I missing something?

This is my config, for what it's worth:
```
# Input data. Change me to a valid input source.
[sources.handshake]
  type = "file"
  include = ["file.log"]
  start_at_beginning = true

# Split transform to take CSV and turn it into JSON
[transforms.csv_splitter]
  type = "split"
  inputs = ["handshake"]
  separator = ","
  field_names = ["current_time_date", "duration_seconds_float", "ip_keyword", "id_keyword", "players_current_int", "players_max_int", "branch_keyword", "changelist_keyword", "map_keyword", "config_id_keyword", "request_id_keyword", "status_keyword", "persistent_keyword", "source_pkg_keyword", "updated_at_date"]

[sinks.data_stream]
  type = "aws_kinesis_streams"
  inputs = ["csv_splitter"]
  region = "us-west-2"
  stream_name = "test"
  encoding = "json"
```

If I can give any more info to help debug, please let me know. Thanks in advance!

**Comment by LucioFranco** [comment]
This sounds like we are unable to find the system certs. I have not done too much work on windows. @Hoverbear do you have any ideas? This might be just a problem of not having openssl installed? From what I can tell our probe crate is looking in well known places but doesn't seem to do anything special for windows vs linux.

**Comment by Hoverbear** [comment]
Hmmmm.... Perhaps it is! Let me try on a clean windows.

**Comment by LucioFranco** [comment]
We may want to provide some global way to set default certs for an entire vector pipeline.

**Comment by Hoverbear** [comment]
Confirmed I can reproduce this error.

**Comment by Hoverbear** [comment]
I confirmed this is not related to having OpenSSL installed.

I ran in a fresh windows:

```powershell
Set-ExecutionPolicy RemoteSigned -scope CurrentUser
iwr -useb get.scoop.sh | iex
scoop install vector
```

The issue occured. I then ran:

```powershell
scoop install openssl
```

The issue still occurred.

**Comment by genvidkyle** [comment]
I just ran into this issue as well. I tried installing openssl.

Using Windows Server 2019

**Comment by scv-m** [comment]
I've just ran into the same as @genvidkyle on Windows Server 2016 (1607)

`vector::sinks::util::retries: Retrying after error. error=Failed to make HTTP(S) request: error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl\statem\statem_clnt.c:1916:: unable to get local issuer certificate`
