### ISSUE TITLE
Update the `filter` transform to work with metrics

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#2266]
Now that components can support both logs and metrics we should re-enable metrics support in the `filter` transform. You can see where this was disabled in https://github.com/timberio/vector/pull/2088/commits/daca559fcefb307a44d4bd62ff2eef980da50e32

**Comment by binarylogic** [comment]
@a-rodin I could use some help implementing the metrics type. I'm not sure if it makes sense to leave this as `check_fields` or add a new `check_tags` condition. I'm indifferent.

**Comment by a-rodin** [comment]
@binarylogic I think `check_tags` actually sense, as with `check_fields` it is necessary to keep in mind the way metrics are serialized. On the other hand, it would be less general as it wouldn't make it possible to filter no metrics values.

**Comment by binarylogic** [comment]
That's true. There are a number of other changes I want to make to the API/UX for this, but `check_tags` or `check_metric` is fine with me.

**Comment by a-rodin** [comment]
> There are a number of other changes I want to make to the API/UX for this

Hmm, in that case it's possible to just leave `check_field` for checking tags for now (actually, I was not sure that it worked for metrics) and then introduce `check_metric` that would check not only tags, but also other metric fields such as name, kind, value, etc. At least, it would not be necessary to deprecate `check_tags` soon after introducing it.
