### ISSUE TITLE
ClickHouse sink cannot insert list fields into Array(T) columns

### ISSUE THREAD

**Issue by emilhf** [timberio/vector#2277]
Not sure if this is a feature request or a bug, but submitting it anyway. I will be taking some liberty with the format expected as such. (Your issue templates unfortunately do not seem to be working at the moment, by the way).

`Array(T)` is a common and useful column type in ClickHouse. For example, a column of this type might be used to store tags. Unfortunately, due to to how the ClickHouse sink seems to flatten  arrays (`tags: [...] => tags[0], ..., tags[n]`), it is not possible to insert into these columns.

### Vector Version

```
vector 0.8.2 (v0.8.2 x86_64-unknown-linux-musl 2020-03-06)
```

### Steps To Reproduce

Given a local ClickHouse instance, the following script reproduces the issue at hand.

```bash
#!/usr/bin/env bash
set -euo pipefail

clickhouse-client -q 'DROP TABLE IF EXISTS vector_logs;'
clickhouse-client -q "CREATE TABLE vector_logs (
  timestamp DateTime Codec(DoubleDelta, LZ4),
  host String,
  tags Array(String),
  message String
) Engine=MergeTree
PARTITION BY toYYYYMM(timestamp)
ORDER BY (host, timestamp);"

cat > vector.yml <<EOF
[sources.feed_me]
type = "stdin"

[transforms.with_metadata]
type = "add_fields"
inputs = ["feed_me"]
fields.tags = ["feed_me", "generic"]

[sinks.clickhole]
type = "clickhouse"
inputs = ["with_metadata"]
host = "http://localhost:8123"
table = "vector_logs"
encoding.timestamp_format = "unix"
EOF

echo "hello ClickHouse!" | vector -vv -c vector.yml
```

Afterwards, you might run the following to verify that nothing has been inserted:

```console
$ clickhouse-client -q "select count() from vector_logs"
0
```

### Debug output

```
Apr 08 22:09:01.242  INFO vector: Log level "trace" is enabled.
Apr 08 22:09:01.242  INFO vector: Loading configs. path=["vector.yml"]
Apr 08 22:09:01.242 TRACE vector: Parsing config. path="vector.yml"
Apr 08 22:09:01.246  INFO vector: Vector is starting. version="0.8.2" git_version="v0.8.2" released="Fri, 06 Mar 2020 15:52:10 +0000" arch="x86_64"
Apr 08 22:09:01.273  INFO vector::topology: Running healthchecks.
Apr 08 22:09:01.273  INFO vector::topology: Starting source "feed_me"
Apr 08 22:09:01.274  INFO vector::topology: Starting transform "with_metadata"
Apr 08 22:09:01.274  INFO vector::topology: Starting sink "clickhole"
Apr 08 22:09:01.275  INFO source{name=feed_me type=stdin}: vector::sources::stdin: Capturing STDIN
Apr 08 22:09:01.276  INFO source{name=feed_me type=stdin}: vector::sources::stdin: finished sending
Apr 08 22:09:01.280  INFO vector::topology::builder: Healthcheck: Passed.
Apr 08 22:09:02.279 DEBUG sink{name=clickhole type=clickhouse}: vector::sinks::util::http: sending request.
Apr 08 22:09:02.287 DEBUG sink{name=clickhole type=clickhouse}: vector::sinks::util::http: response. status=400 Bad Request version=HTTP/1.1
Apr 08 22:09:02.288  WARN sink{name=clickhole type=clickhouse}: vector::sinks::util::retries: request is not retryable; dropping the request. reason=response status: 400 Bad Request
Apr 08 22:09:02.288 TRACE sink{name=clickhole type=clickhouse}: vector::sinks::util: request succeeded. response=Response { status: 400, version: HTTP/1.1, headers: {"date": "Wed, 08 Apr 2020 20:09:02 GMT", "connection": "Keep-Alive", "content-type": "text/tab-separated-values; charset=UTF-8", "x-clickhouse-server-display-name": "localhost", "transfer-encoding": "chunked", "x-clickhouse-query-id": "b89c59fd-c02d-4f29-94ac-ec6c57cb0b49", "keep-alive": "timeout=3", "x-clickhouse-summary": "{\"read_rows\":\"0\",\"read_bytes\":\"0\",\"written_rows\":\"0\",\"written_bytes\":\"0\",\"total_rows_to_read\":\"0\"}"}, body: b"Code: 117, e.displayText() = DB::Exception: Unknown field found while parsing JSONEachRow format: tags[0] (version 20.1.8.41)\n" }
```

### Expected Behavior

It should be possible to insert list fields into the `tags` column. At least there should be an option to treat arrays this way.

### Additional Context

A manual insertion of the expected output works just fine:

```console
$ echo '{ 
    "host": "localhost", 
    "timestamp": 1586377016, 
    "message": "hello ClickHouse!", 
    "tags": ["feed_me", "generic"] 
}' | clickhouse-client -q "INSERT INTO vector_logs FORMAT JSONEachRow"
$ clickhouse-client -q "select * from vector_logs limit 1"
2020-04-08 22:16:56     localhost       hello ClickHouse!       ['feed_me','generic']
```

**Comment by binarylogic** [comment]
Thanks @emilhf, I agree, we need better mapping of types in the `clickhouse` sink. I'm curious what @a-rodin thinks since he has the most experience with Clickhouse on our team.

**Comment by emilhf** [comment]
Awesome, thanks for the swift reply. I would be happy to provide a few use cases and ideas if that would be useful going forward. Unfortunately, my Rust isn't particularly fluent at the moment, but that could of course change :)

**Comment by binarylogic** [comment]
That would be great. We're big fans of Clickhouse; we're planning to add more education around configuring it for the logging use case. We think it's excellent for storing log data. So, yes, please share any detail you have around use cases, that would be very helpful.

**Comment by a-rodin** [comment]
I confirm that it is an issue. One way to fix it is to change the serialization to encode arrays as `Array` and nested fields as `Nested`, however it is not clear what to do when there is more than one level of nesting.

**Comment by emilhf** [comment]
I think it would be hard for Vector to deal with arbitrarily nested data, at least in the general sense. One common pattern for dealing with arbitrarily complex, deeply nested JSON payloads is simply to ingest them as String and use `JSONExtract*` to materialize columns you need for querying purposes. This approach is [suggested by Altinity](https://www.altinity.com/presentations/2019/12/17/a-practical-introduction-to-handling-log-data-in-clickhouse). [Uber seems to be using a similar approach](https://github.com/ClickHouse/clickhouse-presentations/raw/master/meetup40/uber.pdf) as well, although I suspect they flatten the message payload as well. (Another interesting thing Uber does is normalizing fields by their type, e.g. `{ "session_id": "...", "counter": 2 } => { "session_id.String": "...", "counter.Number": 2 }`. Perhaps this could be achieved using runtime transforms in Vector?)

My end goal is actually somewhat of a hybrid to this approach, ingesting certain metadata fields directly into their appropriate type (hence `tags` as `Array(String)`) and then the parsed, normalized JSON payload as a String. I could then use the metadata to populate materialized views with more fine tuned schemas, indexing new fields via materialized columns as performance demands it. This patterns also allows to you to apply a search strategy similar to [Humio's pyramid](https://img2.storyblok.com/1199x627/smart/filters:quality:(100):format:(webp)/f/70749/1200x628/12f7989d79/index-free-funnel-dark-bg.png), using bloom filters on tags, source and so forth to skip large amounts of data.

**Comment by v-zhuravlev** [comment]
Need that badly to feed data into clickhouse.

**Comment by thomasdba** [comment]
any workaround for this ? thanks !

**Comment by mikezsin** [comment]
@a-rodin any updates?

**Comment by bazhenov** [comment]
I've faced the same problem. Suppose I sent following message to clickhouse sink

```
{"attrNames":["keyName"],"attrValues":["26__rel_52"],"dateTime":"2019-12-25 00:01:02"}
```

Related schema

```
CREATE TABLE metrics (
    dateTime DateTime,
    attrNames Array(LowCardinality(String)),
    attrValues Array(String)
)
ENGINE=MergeTree
ORDER BY (attrNames)
PARTITION BY toYYYYMMDD(dateTime);
```

Using `tcpdump` (and disabling compression) I can confirm clickhouse sink modifying JSON packet

```
# tcpdump -A -i lo 'port 8123' 
...
POST /?query=INSERT+INTO+%22default%22.%22metrics%22+FORMAT+JSONEachRow HTTP/1.1
content-type: application/x-ndjson
user-agent: Vector/0.11.1 (v0.11.1 x86_64-unknown-linux-gnu 2020-12-17)
accept-encoding: identity
host: localhost:8123
content-length: 1737

{"attrNames[0]":"keyName","attrValues[0]":"26__rel_52","dateTime":"2019-12-25 00:01:02"}
```

I see no reason why arrays should be flattened, Clickhouse can perfectly import them without any preprocessing.

```
$ echo '{"attrNames":["keyName"],"attrValues":["26__rel_52"],"dateTime":"2019-12-25 00:01:02"}' | \
  curl 'http://localhost:8123/?query=INSERT%20INTO%20metrics%20FORMAT%20JSONEachRow' --data-binary @-
```

Is there any reasons for that?

**Comment by bazhenov** [comment]
Btw, the workaround I found at the moment is to use http sink instead.

```
[sinks.http-output]
  type = "http"
  inputs = ["input"]
  compression = "none"
  uri = "http://localhost:8123/?query=INSERT%20INTO%20metrics%20FORMAT%20JSONEachRow"
  encoding.codec = "json"
```

This also allows you to use any clickhouse import format, not just `JSONEachRow` one.

**Comment by daniilguit** [comment]
@emilhf , @binarylogic: It looks like it was fixed recently, latest release (0.13.1) processes arrays correctly. I think this issue can be closed

**Comment by jszwedko** [comment]
Thanks @daniilguit ! There was a change in https://github.com/timberio/vector/pull/7081 to start passing `input_format_import_nested_json=1` to clickhouse which to allows it to accept the nested data.

@emilhf feel free to reopen this if you are still seeing this issue in 0.13.1.

**Comment by elderbig** [comment]
when I try store json into clickhouse by vector,I do this
vector version:
```
vector-x86_64-unknown-linux-musl/bin/vector --version
vector 0.25.1 (x86_64-unknown-linux-musl 9125a99 2022-11-07)
```
input string:
```json
"labels": [
  {
    "id": 3466055399,
    "node_id": "LA_kwDOGPcgVM7Ol87n",
    "url": "https://api.github.com/repos/WolseyBankWitness/rediffusion/labels/Automerge",
    "name": "Automerge",
    "color": "ededed",
    "default": false,
    "description": null
  }
]
```

clickhouse table:
```sql
CREATE TABLE events
(
    labels Array(LowCardinality(String))
)
ENGINE = MergeTree
ORDER BY (labels)
```

vector config:

```toml
[sources.stdin]
type = "stdin"

[transforms.parse]
type = "remap"
inputs = ["stdin"]
drop_on_error = false
source = '''
    .message = parse_json!(.message) 
    .event.labels = .message.labels
    . = .event
'''
[sinks.clickhouse]
type = "clickhouse"
inputs = ["parse"]
endpoint = "http://127.0.0.1:8123"
database = "default"
table = "events"
skip_unknown_fields = true
```
got error and data can not insert into clickhouse:
```
2022-11-24T03:36:28.773401Z ERROR sink{component_kind="sink" component_id=clickhouse component_type=clickhouse component_name=clickhouse}:request{request_id=0}: vector::sinks::util::sink: Response failed. response=Response { status: 400, version: HTTP/1.1, headers: {"date": "Thu, 24 Nov 2022 03:36:28 GMT", "connection": "Keep-Alive", "content-type": "text/plain; charset=UTF-8", "x-clickhouse-server-display-name": "localhost", "transfer-encoding": "chunked", "x-clickhouse-exception-code": "26", "keep-alive": "timeout=3", "x-clickhouse-summary": "{\"read_rows\":\"0\",\"read_bytes\":\"0\",\"written_rows\":\"0\",\"written_bytes\":\"0\",\"total_rows_to_read\":\"0\",\"result_rows\":\"0\",\"result_bytes\":\"0\"}"}, body: b"Code: 26. DB::ParsingException: Cannot parse JSON string: expected opening quote: (while reading the value of key labels): While executing ParallelParsingBlockInputFormat: (at row 9)\n. (CANNOT_PARSE_QUOTED_STRING) (version 22.9.1.1)\n" }
```
row 9 is the json stirng given in the head above.I seems meet the closed issue,Is something else I need to do? @jszwedko

**Comment by jszwedko** [comment]
Hi @bazhenov ,

Apologies for the delay! It looks like you are trying to insert an array of objects into a field defined in Clickhouse as an array of strings. I think you need to update the Clickhouse schema or encode the labels as a JSON string rather than an object.
