### ISSUE TITLE
Unify log message style

### ISSUE THREAD

**Issue by lukesteensen** [timberio/vector#2289]
We should make a pass through our logging statements and ensure that they all match a consistent style. They should not be capitalized, their wording should be concise, and they should use `tracing`'s k/v syntax instead of string formatting.

There is a bit of an open question about whether messages should end with a period. @LucioFranco thinks it looks better, but I'm somewhat skeptical. Please weigh in if you feel strongly, otherwise we can flip a coin.

**Comment by binarylogic** [comment]
I can handle this when I implement our events. The period issue is serious and I will think deeply about my punctuation choices.

**Comment by Hoverbear** [comment]
Microsoft tells us periods are good: https://docs.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions?redirectedfrom=MSDN#use-grammatically-correct-error-messages

**Comment by jamtur01** [comment]
c.f. #3850
