### ISSUE TITLE
Use cached paths in the `tokenizer` transform

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#2314]
The performance of the `tokenizer` transform can be improved by avoiding parsing the paths for each transformed event.

One way to do it is to introduce a new `OwnedPath` structure which would implement `Iterator<Item = PathComponent>`, which can then be used with [`LogEvent::insert_path`](https://github.com/timberio/vector/blob/bc48a21e95a9802a5cf57326b4be1c383c567e27/src/event/mod.rs#L128-L133).

**Comment by lukesteensen** [comment]
You can see an example implementation [here](https://github.com/timberio/vector/pull/2296/commits/1f8e0d58054808d4ce46e1780f3808d0d2e6d671) for `grok_parser`. We may want a nicer API, but the idea should be roughly the same.
