### ISSUE TITLE
Tutorial on https://vector.dev/guides/getting-started/your-first-pipeline/ failed

### ISSUE THREAD

**Issue by ahume** [timberio/vector#2316]
The tutorial on:

https://vector.dev/guides/getting-started/your-first-pipeline/

Here's what went wrong:

$ cat vector.toml
[sources.foo]
  type = "stdin"

[sinks.bar]
  inputs = ["foo"]
  type = "console"
  encoding.codec = "text"

$ echo 'Hello World!' | vector --config ./vector.toml
Apr 13 22:48:50.169  INFO vector: Log level "info" is enabled.
Apr 13 22:48:50.170  INFO vector: Loading configs. path=["vector.toml"]
Apr 13 22:48:50.172 ERROR vector: Configuration error: "vector.toml": unknown variant `codec`, expected `text` or `json` for key `sinks.bar`

**Comment by Hoverbear** [comment]
Hi! This is related to #2307 , 0.9.0 is due out imminently which will fix this issue! Sorry about that! We're working on fixing the root of this issue in #1291
