### ISSUE TITLE
Enable optimizations for benchmarks

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#2326]
Currently running `cargo bench` uses uses debug builds for benchmarking:

https://github.com/timberio/vector/blob/fb8ae10f193c1990259500941ddd90f01472063e/Cargo.toml#L12-L13

In order to ensure that we benchmark the same kind of generated code which is used in production builds, it is necessary to use release builds with LTO and `codegen-units=1` for the `bench` profile.

**Comment by lukesteensen** [comment]
The `debug` flag isn't the same as a `debug` build (see [docs](https://doc.rust-lang.org/cargo/reference/profiles.html#debug)). It just means that we include debug symbols in the binary, which is useful for profiling.

**Comment by LucioFranco** [comment]
I believe this just adds to binary bloat just for bench builds. Shouldn't impact performance like luke said.

**Comment by Hoverbear** [comment]
Closing, not relevant.
