### ISSUE TITLE
No native way to pass sub-second timestamp resolution from Lua

### ISSUE THREAD

**Issue by jschaf** [timberio/vector#2332]
The lua transform currently supports parsing a `os.date` table into a Vector timestamp. However, the Lua `os.date` table doesn't support sub-second resolution.

There's a couple ways to go about supporting sub-second resolution timestamps from Lua into Vector:

1. Do nothing and use a `coercer` transform to convert a Lua string into a timestamp. This currently works.

2. Support floats as the `sec` field in a Lua `os.date` table. This isn't a great idea because existing lua functions like `os.date` require `sec` to be an integer. Additionally, floats lose precision once you get into nanosecond range.

3. Add an optional field `nanosecond`. This is my preference. It plays nicely with existing Lua functions and doesn't lose precision.

**Comment by a-rodin** [comment]
Hi @jschaf, I prefer the third options as well, as it would keep using timestamps easy and still support nanoseconds.

One thought: as the seconds field is called `sec`, would it make sense to call the nanosecond field `nsec` or `nanosec`?

**Comment by binarylogic** [comment]
`nanosec` makes sense to me.
