### ISSUE TITLE
Design fast accessor methods for `LogEvent`

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#2334]
Currently `LogEvent` has `insert`/`get`/`...` methods which parse paths each time when used. For many components this can be optimized, so that parsing would happen just at the initialization of the component.

It was already done by @lukesteensen for `grok_parser` transform in https://github.com/timberio/vector/pull/2296 by introducing new [`LogEvent::insert_path`](https://github.com/timberio/vector/blob/e2eb9e7da20337e3522e9f4ad5ca9b049e8c26e2/src/event/mod.rs#L127-L132) method which takes `Vec<PathComponent>` as the key value.

One way to generalize it is to introduce new `OwnedPath` structure that would be a wrapper over `Vec<PathComponent>`. However, for methods like `get`, `get_mut`, `contains`, and `remove` it is desirable to have string slices as path components instead of owned strings.

Furthermore, for "simple" paths which don't contain escaping it is desirable to have a way to represent components of the parsed path as strings slices pointing to the source path, so that the parsing could be performed without string allocations at all.

This is probably requires an RFC, as the changes could affect multiple components.

**Comment by binarylogic** [comment]
So that https://github.com/timberio/vector/pull/2325#issuecomment-614078456 doesn't get lost:

> This is likely a good argument for going straight to ref-counted strings as the key type. We'd avoid copying on the insert path and avoid having to deal with a separate type on the get path.

**Comment by binarylogic** [comment]
Also, issue #1592 might be related.

**Comment by binarylogic** [comment]
@Hoverbear is this still relevant given the recent data model changes?

**Comment by Hoverbear** [comment]
I think the #2692 changes will hit this.
