### ISSUE TITLE
Update our release process to favor glibc builds

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#2337]
Given the results in #2313, we should update our release process to produce Vector versions compiled with glibc. Here's what that looks like:

### Strategy

We should _not_ rip out our MUSL builds, instead, we should continue to offer MUSL builds as an option. While offering both MUSL and Glibc builds can be confusing to users, we can eliminate that confusion by making the MUSL builds only discoverable by browsing packages.timber.io/vector. Pages like [https://vector.dev/releases/0.8.2/download/](https://vector.dev/releases/0.8.2/download/) do not need to display MUSL based download links, and we can mention that MUSL builds are available on pages like [https://vector.dev/docs/setup/installation/manual/from-archives/](https://vector.dev/docs/setup/installation/manual/from-archives/).

I like offering both because:

1. Some users require this depending on their environment.
2. Some users might prefer this.
3. Finally, to preserve backward compatibility with existing users.

#### Preface

- [ ] Add a new builder Docker image that dynamically links to `glibc` 2.19 and statically links to `libc++` or `libstdc++`. `libc` is needed for `leveldb`. Blocked by #2336. https://github.com/timberio/vector/pull/2328 represents the initial work.

#### Archives

- [ ] Update the `vector-x86_64-unknown-linux-gnu.tar.gz` archive to use the new `glibc` based build. Currently, this is just a redirect to `vector-x86_64-unknown-linux-musl.tar.gz`.
- [ ] Produce a new `vector-aarch64-unknown-linux-gnu.tar.gz` archive. (is this necessary)
- [ ] Produce a new `vector-armv7-unknown-linux-gnueabihf.tar.gz`. (is this necessary)
- [ ] Update the `vector-x86_64-apple-darwin.tar.gz` archive to use the new `glibc` based build.

#### Packages

- [ ] Update the Vector `.deb` packages to use the new `glibc` based build.
- [ ] Update the Vector `.rpm` packages to use the new `glibc` based build.

#### Docker

- [ ] Update the Vector Docker `*-debian` variant to use the new `glibc` based build.
- [X] The Vector Docker `*-alpine` variant should continue to use MUSL since this is required for Alpine.

#### Postface

- [ ] 🎉

**Comment by binarylogic** [comment]
@a-rodin could you verify that this is correct. There are some open questions around our `aarch64` and `armv7` builds. Feel free to edit the original issue to accurately reflect the work.

**Comment by a-rodin** [comment]
I took a bit more look at it and I feel like this actually might be not the lowest hanging fruit.

I feel like it might be worth to rather invest time into tuning the Tokio runtime, as it potentially can give much more than 18%. I came up to this conclusion by comparing performance of (single-threaded) `cat` utility with Vector running with the default config (piping stdin to console in text encoding).

**Comment by binarylogic** [comment]
Thanks @a-rodin, you're not wrong, but we need to do both. @lukesteensen is working on an RFC that will potentially address that. I'd still like to proceed with the above checklist unless you disagree.

**Comment by binarylogic** [comment]
@a-rodin I spent time today cleaning up CI so that it's in a good state for you. My hope is that you can focus on the work in this ticket and not cleaning up CI. You can see the changes in #2368, specifically the linked pull requests. The high-level changes include:

1. Move `/tests/Makefile` to `/Makefile`.
2. Point the `test.yml` and `nightly.yml` CI workflows to the new `/Makefile`.

https://github.com/timberio/vector/pull/2460 is the final change. Feel free to merge if you agree with this direction. I'd start by updating the `nightly.yml` workflow. Once that is done we can build out the release process, I've yet to migrate that from CircleCI.
