### ISSUE TITLE
GCP services don't use configured DNS resolvers

### ISSUE THREAD

**Issue by bruceg** [timberio/vector#2359]
In order to use GCP services, clients must first request a token from a separate API. This process happens through a `reqwest::Client` internal to the `goauth` library, and so does not use our custom resolver. This needs to be fixed to respect configured DNS servers.

**Comment by binarylogic** [comment]
This is blocked by the decision in #2635.

**Comment by binarylogic** [comment]
Closing since we've decided to remove DNS support. Please see https://vector.dev/highlights/2020-06-18-remove-custom-dns-resolution.
