### ISSUE TITLE
Guide on implemeting Protobuf support with WASM

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#2367]
Since our solution for #1472 is WASM, we should follow through with a guide demonstrating how Protobuf is implemented. The goal should be to make this as simple and easy as possible. I really like @a-rodin's idea [here](https://github.com/timberio/vector/pull/2341/files#r409806532).

**Comment by binarylogic** [comment]
Taking this out of the sprint since it's blocked by some of the data model work.

**Comment by Hoverbear** [comment]
#1377 #2846

**Comment by binarylogic** [comment]
@Hoverbear should we close this given that we want to start with a simple "hello world" guide for WASM? I also think Protobuf is better demonstrated when we build out support for custom codecs via WASM. What do you think?

**Comment by Hoverbear** [comment]
Agreed!
