### ISSUE TITLE
Cleanup test Makefile and align with Github Actions CI workflow

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#2368]
In https://github.com/timberio/vector/pull/1701 @a-rodin introduced a [Makefile](https://github.com/timberio/vector/blob/master/tests/Makefile) that rebuilds the CI dependency graph. The intent was to decouple the dependency graph from the `.circleci/config.yml` file so that we could effectively run the CI steps anywhere, including local machines.

This Makefile works by delegating back to the [root Makefile](https://github.com/timberio/vector/blob/master/Makefile) as well as the [root `docker-compose.yml`](https://github.com/timberio/vector/blob/master/docker-compose.yml) file. If you are confused, that's why this issue was opened 😄.

When we originally set out to do this we didn't have full context on the limitation that GH Actions imposes. While the idea of `cd tests && make` is appealing, the GH Actions runners simply do not have enough resources to do this. Setting aside CPU and memory, GH actions runners only allow 16gb of disk space. This is barely enough to run the tests now. As a result, we've split up the tests into many different GH action jobs.

If you're still with me, we need to clean this up. Here are the action items as I see it, feel free to adjust as necessary

- [ ]  Move all `tests/Makefile` targets to the root `Makefile` (skipping duplicates). Delete the `tests/Makefile`.
- [ ] Ensure that `.github/workflows/ci.yml` is calling these Make targets.
- [x] Should we update all of the `cargo test --no-default-features --features $FEATURES` calls in `.github/workflows/ci.yml` to use `make test`? We're using environment variables, so I don't see why `make test` can't support the same environment variables.

**Comment by Hoverbear** [comment]
To expand on this a bit:

* The root `Makefile` doesn't have much of a depgraph, and the `tests` done does, that's something we'd like to migrate.
* We should rearchitect `make test` to optionally accept a scope of test (eg `sinks::datadog`)
* We should rearchitect `make test` so it doesn't try to start a bunch of docker containers, and just starts what's needed to the things it will test.

This will end us in a position where we can have multiple runners running mutually exclusive tests on Vector in parallel on  the CI while not harming developer experience (hopefully!)

**Comment by Hoverbear** [comment]
Another note:

* We should make `check-component-features` take a selector or have sub-tasks like `check-sink-features`.
