### ISSUE TITLE
`splunk_hec` drops timestamp precision

### ISSUE THREAD

**Issue by lewisthompson** [timberio/vector#2376]
https://github.com/timberio/vector/blob/master/src/sinks/splunk_hec.rs#L122-L124:

```rust
        let timestamp = if let Some(Value::Timestamp(ts)) =
            event.remove(&event::log_schema().timestamp_key())
        {
            ts.timestamp()
        } else {
            chrono::Utc::now().timestamp()
        };
```

`timestamp()` returns a second-precision i64 whereas Splunk will accept nanosecond-precision Unix timestamp.  As a result of this call timestamp precision is reduced to second.

**Comment by binarylogic** [comment]
@LucioFranco it looks like you wrote this line. Do you have any context on why you chose second precision? And do you know if this is a problem across other sinks?

**Comment by binarylogic** [comment]
Thanks @lewisthompson, we'll prioritize this and get it fixed this week.
