### ISSUE TITLE
sinks(kafka): Topic field should be templatable.

### ISSUE THREAD

**Issue by Hoverbear** [timberio/vector#2385]
We discussed in https://github.com/timberio/vector/pull/1745#discussion_r412383212 that we would like to make the `topic` field of the `kafka` sink templatable.

**Comment by binarylogic** [comment]
@LucioFranco this should be simple given that this is a streaming sink, right?

**Comment by LucioFranco** [comment]
Yes, we would need to update the healthcheck https://github.com/timberio/vector/blob/master/src/sinks/kafka.rs#L217 since it relies on a topic but should be quite trivial to make the actual sink work with a template.

**Comment by LucioFranco** [comment]
For the healthcheck, if it requires an event we can just return `future::ok(())`.

**Comment by flyik** [comment]
Any idea when it will be ready?
