### ISSUE TITLE
macOS build does not use Security.framework for TLS CA lookup

### ISSUE THREAD

**Issue by lewisthompson** [timberio/vector#2395]
On macOS I have to either disable TLS verification or explicitly specify the CA certificate in my toml file, even if other binaries on the system trust the certificate.

It looks as though vector is not using Security.framework which is where macOS stores CA certificates, among other things.

This would be great to enhance in future to avoid any custom settings in the toml file.  Perhaps something like https://github.com/kornelski/rust-security-framework could be used?

**Comment by Hoverbear** [comment]
I think this might be related to what you're looking at with Windows right now @LucioFranco ?

**Comment by LucioFranco** [comment]
Yup! Related but not a duplicate #2256

**Comment by LucioFranco** [comment]
@lewisthompson https://github.com/timberio/vector/pull/2444 should provide a fix!
