### ISSUE TITLE
Dynamically adjusted batch sizes

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#2396]
For batching sinks that are forced into using discrete batch size types (Event based not byte based), we should attempt to roughly estimate the average size of the logs and adjust the batch size against the maximum accepted batch size in bytes. This could be achieved via estimated moving window average.

**Comment by binarylogic** [comment]
We need to solve this properly and not implement hacks like a "moving window average". What is the blocker to building a payload that does not exceed a certain byte size? Don't we accomplish this with other sinks?

Ideally, a user could set both a quantity and byte size limit. Whatever is hit first triggers a flush.

**Comment by binarylogic** [comment]
Closing this since we'll want to actually support byte size payloads and not estimates.
