### ISSUE TITLE
Lua transform doesn't modify event before sending them

### ISSUE THREAD

**Issue by happysalada** [timberio/vector#2398]
I am using the newly released 0.9.0 with lua transform version  2
I tried with the example from the doc, but I can't get lua to add fields to the emitted event.
Here is my vector.toml for reference

```
[sources.docker]
  type = "docker" # required

[transforms.drop_unused]
  type = "remove_fields" # required
  inputs = ["docker"] # required
  fields = [
    "container_created_at",
    "container_id",
    "container_name",
    "stream",
    "label.com.docker.stack.namespace",
    "label.com.docker.swarm.node.id",
    "label.com.docker.swarm.service.id",
    "label.com.docker.swarm.service.name",
    "label.com.docker.swarm.task",
    "label.com.docker.swarm.task.id",
    "label.com.docker.swarm.task.name",
    "label.org.label-schema.build-date",
    "label.org.label-schema.schema-version",
    "label.org.label-schema.vsc-ref",
    "label.org.label-schema.vsc-url",
    "label.org.opencontainers.image.description",
    "label.org.opencontainers.image.documentation",
    "label.org.opencontainers.image.title",
    "label.org.opencontainers.image.url",
    "label.org.opencontainers.image.vendor",
    "label.org.opencontainers.image.version"
  ] # required

 [transforms.level]
  # General
  type = "lua" # required
  inputs = ["drop_unused"] # required
  version = "2" # required

  # Hooks
  [transforms.level.hooks]
    process = """
    function (event, emit)
      event["test"] = "test"
      event.other = "other_test"
      -- Very important! Emit the processed event.
      emit(event)
    end
    """ 

[sinks.loki]
  # General
  type = "loki" # required
  inputs = ["level"] # required
  endpoint = "http://loki:3100" # required

  [sinks.loki.encoding]
    codec = "json"
    except_fields = ["source_type"]

  [sinks.loki.labels]
    level = "{{ level }}" # example
    image = "{{ image }}" # example

[sinks.file]
  # General
  type = "file" # required
  inputs = ["level"] # required
  path = "./logs/day-%d.log" # required
  healthcheck = true # optional, default

  [sinks.file.encoding]
    codec = "ndjson"
```

Let me know if I misunderstood anything.
(checking the logs, nothing appears in particular)

**Comment by binarylogic** [comment]
Hi @happysalada, we'll try to repreoduce tomorrow and update accordingly. If this is a bug we'll get a fix out ASAP. Thanks for letting us know.

**Comment by binarylogic** [comment]
Hi @happysalada, I see the problem. You need to set fields on the appropriate log type. Ex:

```lua
function (event, emit)
    event.log.test = "test"
    event.log.other = "other_test"
    -- Very important! Emit the processed event.
    emit(event)
end
```

Notice the `log` key. This is needed in case you want to modify metric tags as well:

```lua
function (event, emit)
    event.metric.tags.test = "test"
    event.metric.tags.other = "other_test"
    -- Very important! Emit the processed event.
    emit(event)
end
```

Let me know if that solves it.

**Comment by happysalada** [comment]
Wonderful, thank you for the fast answer!

Everything works now.
A couple of comments
- the lua transform adds a field "source_type", not that it's horrible, just a little unexpected. (just FYI, since it's actually really easy to remove)
- I was trying to do conditional parsing. If the logs are in a certain format, add those fields, if they are not, keep them as they are. The reason being that lots of containers have some conventions around logging  (like adding lvl= or level=) and some don't have those conventions. I thought it could be a good example for the docs, since it seems to me there is no way of doing conditional parsing without lua. (regex will fail in case there is no match)

Here is the file I ended up with

```
    process = """
    function (event, emit)
      message = event.log.message
      level = string.match(message, "le?ve?l=(%w+)")
      msg = string.match(message, "me?ss?a?ge?=(%w.+)")
      if level then
        event.log.level = level
        event.log.message = msg
        event.log.source_type = nil
      end
      -- Very important! Emit the processed event.
      emit(event)
    end
    """ 
```

(all this is just in case you are interested)

Thanks a lot for the help!

**Comment by binarylogic** [comment]
Thanks @happysalada.

> the lua transform adds a field "source_type", not that it's horrible, just a little unexpected. (just FYI, since it's actually really easy to remove)

That's coming from the `docker` source. But we should provide a way to disable it.

> I was trying to do conditional parsing. If the logs are in a certain format, add those fields, if they are not, keep them as they are.

That's a great feature idea. You could use the `swimlanes` transform to create lanes based on defined conditions, and then run the output lanes through custom `regex_parsers`, but that feels rather clunky.

Appreciate the feedback!
