### ISSUE TITLE
The remap `del` function should support patterns

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#2400]
After reviewing the config in https://github.com/timberio/vector/issues/2398, we should support patterns when removing fields.

This might already be done with the remap syntax's path syntax, but I wasn't sure. If so, please close this.

**Comment by Hoverbear** [comment]
How about regex?

**Comment by binarylogic** [comment]
This will likely conflict with #5605. If we favor #5605 then we should close this.

**Comment by JeanMertz** [comment]
Closing this, as we did end up going with #5605
