### ISSUE TITLE
Sinks: AWS Elasticsearch 403 Forbidden

### ISSUE THREAD

**Issue by panpan-wu** [timberio/vector#2403]
Response from AWS:

```
HTTP/1.1 403 Forbidden
Date: Wed, 22 Apr 2020 07:32:14 GMT
Content-Type: application/json
Content-Length: 75
Connection: keep-alive
x-amzn-RequestId: 62e2a8cf-846b-11ea-b204-1bd2d5c29e76
Access-Control-Allow-Origin: *

{"message":"Credential should be scoped to a valid region, not 'custom'. "}
```

Is there some ways to change the region to other value(eg: us-east-1)？

**Comment by bruceg** [comment]
Could you try the fix in #2412 and see if that fixes the issue for you?

**Comment by panpan-wu** [comment]
> Could you try the fix in #2412 and see if that fixes the issue for you?

I don't know how to build an docker image by myself. Could you give me some hints?

**Comment by binarylogic** [comment]
Hi @panpan-wu, I'm confident that change will resolve your issue. Building is [covered in our docs](https://vector.dev/docs/setup/installation/manual/from-source/). But you don't want to do that you can wait for this pull request to merge and it'll be part of our [nightly releases](https://vector.dev/releases/nightly/download/).

**Comment by binarylogic** [comment]
Also, it's likely we'll get this into `0.9.1` in the next day or so.

**Comment by panpan-wu** [comment]
> Also, it's likely we'll get this into `0.9.1` in the next day or so.

I use `timberio/vector:nightly-2020-04-25-alpine` to test. It reports 403 Forbidden Error:

```
Apr 26 02:23:10.584 ERROR vector::topology::builder: Healthcheck: Failed Reason: Unexpected status: 403 Forbidden
```
