### ISSUE TITLE
New `aws_cloudwatch_logs` source

### ISSUE THREAD

**Issue by rverma-jm** [timberio/vector#2405]
Aws by default push its internal logging to cloudwatch. We have multiple utilities which can tail cloudwatch logs eg. https://github.com/lucagrulla/cw/blob/master/cloudwatch/tail.go.

All these plugins uses https://docs.aws.amazon.com/sdk-for-go/api/service/cloudwatchlogs/#CloudWatchLogs.FilterLogEvents to create a filter and subscribe to it.

**Comment by rverma-jm** [comment]
Linking https://github.com/timberio/vector/issues/2695

**Comment by binarylogic** [comment]
Thanks @rverma-jm, sorry for the duplicate issue. I'm going to close this in favor of #2695.
