### ISSUE TITLE
Docker+Datadog very unreliable

### ISSUE THREAD

**Issue by mikehardenize** [timberio/vector#2406]
This happens when running the vector-0.9.0-1.x86_64 RPM on 10 separate Centos 7 boxes in AWS. I'm using a docker source with a datadog sink. My vector.toml contains:

```
[sources.monitor_source]
  type               = "docker"
  include_containers = ["monitor-"]

[transforms.monitor_transform]
  type            = "add_fields"
  inputs          = ["monitor_source"]
  fields.hostname = "my-hostname"
  fields.service  = "monitor"
  fields.ddsource = "vector"
  fields.ddtags   = "monitor,env:production,project:my-project,location:london"

[sinks.monitor_sink]
  type           = "datadog_logs"
  inputs         = ["monitor_transform"]
  api_key        = MY_DATADOG_API_KEY
  encoding.codec = "json"
      
  [sinks.monitor_sink.tls]
    enabled = true
    ca_path = "/etc/ssl/certs/ca-bundle.crt"
```

This works briefly after I start vector running. I can see logs going into datadog, but it just stops working after a couple of logs have got in. I tried switching to using the syslog source and using the docker syslog driver but this didn't help. I tried adding a disk buffer to the sink and that didn't help. I tried without tls and that didn't help.

I know both of these components are in beta atm, so I'm just wondering if this is expected behaviour at this time, or if I'm seeing something different to what everyone else is?

**Comment by binarylogic** [comment]
Hi, @mikehardenize thanks for reporting. That's certianly not the expected behavior. We'll prioritize and see what's going on.

**Comment by mikehardenize** [comment]
This might be bad timing on my part. I think datadog may be having issues. I've reconfigured my systems so that docker uses the syslog driver, and then I have rsyslogd just forwarding to datadog without vector being involved, and I'm still seeing the same issues. Only some of the logs are getting through. Unfortunately they don't have anything on their status page regarding problems.

**Comment by mikehardenize** [comment]
The problem continues. I'm using a "file" source instead to take docker out of the equation. I'm seeing a lot of stuff like this in my logs:

```
Apr 23 11:09:06 proxy10 vector[26418]: Apr 23 11:09:06.707 ERROR connection{host=intake.logs.datadoghq.com port=10516}: vector::internal_events::tcp: unable to flush connection. error=Broken pipe (os error 32)
```

FWIW, in the [datadog docs for rsyslog](https://docs.datadoghq.com/integrations/rsyslog/?tab=datadogussite) it says:

```
Datadog cuts inactive connections after a period of inactivity. Some Rsyslog versions are not able to reconnect properly when necessary. To mitigate this issue, use time markers so the connection never stops. To achieve this, add the following 2 lines in your Rsyslog configuration:

$ModLoad immark
$MarkMessagePeriod 20
```

Is the problem that datadog is disconnecting vector, and vector isn't handling reconnects well?

**Comment by LucioFranco** [comment]
@mikehardenize interesting, I'll see if I can reproduce this locally and get a fix out.

**Comment by lukesteensen** [comment]
#2209 might be of interest here.

**Comment by LucioFranco** [comment]
@mikehardenize I took a larger look today, so in general vector reconnects just fine, the error message here is not really an error actually lead us to find a bug with our shutdown detection! So in the case here the event that triggered the flush would get dropped but the rest of the events would continue to properly be sent to datadog.

#2429 fixes the issue I described above and should no longer produce error messages but a debug message when we get the proper signal to start a reconnect. Let me know if you have any more questions!

**Comment by mikehardenize** [comment]
Brilliant. I'll deploy this as soon as you do your next release and report back.
