### ISSUE TITLE
Update couldwatch sink to batch by bytes rather than events

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#2408]
Ref #2394.

We should update the cloudwatch logs sink to batch events by bytes. To achieve this we will need to write a custom `Batch` implementation that allows us to collect the size of each event post encoding. This won't represent the total size of the batch since events get wrapped with timestamps but should give us a very close estimate to what we might actually send down the wire.

**Comment by binarylogic** [comment]
Any wrapping should be predictable. We know the timestamp is 10 bytes, and that JSON cruft is X bytes (depends on Rusoto). We'll need to provide a buffer for things like headers, but 1kb should be plenty for all of this.
