### ISSUE TITLE
Log when Vector cannot list / glob directories due to permissions errors

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#2420]
From our chat:

> The globbing in the file source, can you use multiple asterisks in multiple locations. E.g is this valid? include = ["/opt/nomad/data/alloc/*/alloc/logs/monitor.std*.*"]
>
> To answer my own question: yes. The problem I was having was that Vector could not see these files because the "alloc" dir was owned root:root with mode 0711, which meant the vector user couldn't get a directory listing, therefore the globbing failed. I feel like this should have been logged by Vector, but it wasn't.

**Comment by binarylogic** [comment]
@ktff this might be slightly related to, or similar to, #5886.

**Comment by ktff** [comment]
One of the places where this error can pop up is indeed related to #5886, the other place is when globbing, and I think there is more. 

I'll also check if there are other io related errors that would be useful to the user.
