### ISSUE TITLE
Wrap all sources in lazy

### ISSUE THREAD

**Issue by michaelfairley** [timberio/vector#243]
We want our sources to bind to whatever they're reading from (socket, file, stdin) after they've been `spawn`ed, not when they're constructed. [Most](https://github.com/timberio/vector/blob/7f3430d200865fe2c9aad8004f2129a208763fc4/src/sources/file.rs#L68) [of](https://github.com/timberio/vector/blob/7f3430d200865fe2c9aad8004f2129a208763fc4/src/sources/syslog.rs#L60) [them](https://github.com/timberio/vector/blob/7f3430d200865fe2c9aad8004f2129a208763fc4/src/sources/syslog.rs#L86) [we](https://github.com/timberio/vector/blob/7f3430d200865fe2c9aad8004f2129a208763fc4/src/sources/syslog.rs#L106) [have](https://github.com/timberio/vector/blob/7f3430d200865fe2c9aad8004f2129a208763fc4/src/sources/tcp.rs#L40) wrapped in an explicit `lazy` to solve for this. We don't have this on the `stdin` source right now, meaning it can bind (and log that it's ready) before it's expected to be (as in #241).

Ideally there'd be a way for the topology builder to automatically wrap all sources `lazy`s (but our current interface for building sources doesn't really allow for that.) At the very least we should throw a `Lazy` onto [this type](https://github.com/timberio/vector/blob/7f3430d200865fe2c9aad8004f2129a208763fc4/src/sources.rs#L8) so that we'll at least guarantee that we're doing in the manual `lazy`ing for now.

**Comment by binarylogic** [comment]
@LucioFranco this is a pretty old issue, but I'm wondering if it's still relevant given your current work?

**Comment by LucioFranco** [comment]
No longer needed.
