### ISSUE TITLE
Socket sink should support keepalive options

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#2430]
The socket sink should support some form of keepalive options to allow the client to detect a disconnection easier.

Reference https://docs.rs/socket2/0.3.12/socket2/struct.Socket.html#method.keepalive

This is a pretty low priority feature but could be handy.

**Comment by pablosichert** [comment]
This has been partly implemented (keepalive `time` option) in https://github.com/timberio/vector/issues/4816 and will be further tracked in https://github.com/timberio/vector/issues/4957.
