### ISSUE TITLE
Datadog Sink should require TLS

### ISSUE THREAD

**Issue by mikehardenize** [timberio/vector#2436]
I followed the tutorial at https://vector.dev/guides/integrate/sinks/datadog_logs/ - Unbeknownst to me at the time, this lead to me exposing our datadog API key on the wire as plain text. It was a surprise to me when I dug into the configuration further and discovered that TLS was not the default.

I understand that you're not shipping the application with a CA bundle, so may feel like you can't make TLS the default. On the other hand, you could make TLS config required as part of the sink, and force the user to explicitly disable TLS through that config if a CA bundle is not available to them.

If you don't want to do the above, the tutorial could still be updated to include TLS config, so that people following it are aware that not using it will lead to their API key being exposed.

**Comment by binarylogic** [comment]
Hi @mikehardenize, very sorry about that. You are correct, there is no reason we shouldn't enable TLS by default. We'll prioritize this.

**Comment by LucioFranco** [comment]
#2256 and #2395 for me are a blocker here since a user who is on windows/mac won't get these sinks working out of the box but I agree we should be defaulting to tls on!
