### ISSUE TITLE
How to specify "not.contains" transform?

### ISSUE THREAD

**Issue by DmitryRusakovKodiak** [timberio/vector#2446]
Currently there is a "contains" transform: `condition."message.contains" = "foo"`
Is it possible to specify the opposite logic: emit only messages which don't contain a certain text, something like `condition."message.not.contains" = "foo"`?

**Comment by bruceg** [comment]
There is no way to negate a condition in that way, though I agree it would be a simple and very useful addition. I plan to work on this shortly.
