### ISSUE TITLE
DRY up Makefile and docker-compose.yml by removing CPU archs

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#2459]
This is low priority. While working on https://github.com/timberio/vector/pull/2456, I noticed that we might be able to DRY up our `Makefile` and `docker-compose.yml` files by removing the specific CPU archs. For example:

* `Dockerfile`
  * `scripts/ci-docker-images/builder-*/Dockerfile` -> `scripts/ci-docker-images/builder-musl/Dockerfile` (with `TARGET` var).
* `docker-compose.yml`
  * `build-*` -> `build-musl` (with `TARGET` var).
  * `package-*` -> `package-archive-musl` (with `TARGET` var).
  * `package-deb-*` -> `package-deb` (with `TARGET` var).
  * `package-rpm-*` -> `package-rpm` (with `TARGET` var).
* `Makefile`
  * `build-*` -> `build-musl` (with `TARGET` var).
  * `package-*` -> package-archive-musl` (with `TARGET` var).
  * `package-deb-*` -> `package-deb` (with `TARGET` env).
  * `package-rpm-*` -> `package-rpm` (with `TARGET` env).

It's very likely this is not possible because it all hinges on the `Dockerfile`s. For example, the [`builder-x86_64-unknown-linux-musl/Dockerfile`](https://github.com/timberio/vector/blob/master/scripts/ci-docker-images/builder-x86_64-unknown-linux-musl/Dockerfile) and the [`builder-aarch64-unknown-linux-musl/Dockerfile`](https://github.com/timberio/vector/blob/master/scripts/ci-docker-images/builder-aarch64-unknown-linux-musl/Dockerfile) look very similar, and I'm curious if we could easily, and safely, parameterize them. If so, that could cascade up through the `docker-compose.yml` and `Makefile`.

**Comment by a-rodin** [comment]
It is also possible to DRY up definitions of certain targets in the Makefile using [pattern rules](https://www.gnu.org/software/make/manual/html_node/Pattern-Examples.html#Pattern-Examples). For example,

```make
integration-test-aws:
    $(RUN) integration-test-aws

integration-test-gcp:
    $(RUN) integration-test-gcp
```

could be replaced by a single rule

```make
integration-test-%:
    $(RUN) $@
```

Similarly, it should be possible to add a pattern rule for building RPM packages for all architectures using something similar to this:

```make
package-rpm-%: package-archive-%
    $(RUN) $@
```

My only concern that using such patterns might make it harder to infer the list of all possible targets just by looking at the Makefile (it would be necessary to also look at the docker-compose file).

**Comment by binarylogic** [comment]
That's true. You are right, it doesn't make the targets easily discoverable. We've set precedence through environment variables, and if we could use those to switch between CPU archs that would be ideal. I only want to do this if it makes sense and is correct! I don't have the experience you have in this area, so only do it if it is correct and helpful.
