### ISSUE TITLE
Upgrade `trust-dns` to fix `RUSTSEC-2020-0014`

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#2464]
We should upgrade `trust-dns` to allow us to upgrade our version of rusqulite to avoid this vuln.

**Comment by binarylogic** [comment]
Noting, this is blocked by the decision on https://github.com/timberio/vector/issues/2635

**Comment by fanatid** [comment]
`trust-dns` removed in https://github.com/timberio/vector/pull/2884
Security advisories will be removed in https://github.com/timberio/vector/pull/3009
