### ISSUE TITLE
[Pulsar Sink] why the pulsar sink has a consumer healthcheck?

### ISSUE THREAD

**Issue by KannarFr** [timberio/vector#2475]
Hi,

On pulsar sink, why the producer is not considered as a valid healthcheck?

My question is about security issues, vector should not be able to consume as a sink IMO. More, it creates a not necessary connection, right?

WDYT?

**Comment by KannarFr** [comment]
I think the pulsar binary protocol have its healthcheck system. Will check it.

**Comment by KannarFr** [comment]
Ok http://pulsar.apache.org/docs/en/develop-binary-protocol/#keep-alive, 

```
PulsarDecoder#handlePing  PulsarDecoder#handlePong
```

Will open issue on pulsar-rs to use it and use it in vector.

Because currently the healthcheck consumer can be on different broker that the producer used.

**Comment by binarylogic** [comment]
Thanks @KannarFr, in the interim, you can disable the health check with `healthcheck = false`

**Comment by KannarFr** [comment]
The `healthcheck = false` has a strange behavior, by my side, on the pulsar sink the consumer healthcheck is created then stopped, right?

**Comment by KannarFr** [comment]
How can just not initiate the healthcheck? Can I?

**Comment by KannarFr** [comment]
@binarylogic^?

**Comment by binarylogic** [comment]
> The healthcheck = false has a strange behavior, by my side, on the pulsar sink the consumer healthcheck is created then stopped, right?

I'm not sure what you mean? Setting `healthcheck = false` causes a problem?

**Comment by KannarFr** [comment]
With `healthcheck = false` configured on the pulsar sink. I get the following error:
```
Apr 29 16:35:56 db6035d1-1258-4425-b22c-2df69ff7e1a3 vector[2136]: Apr 29 16:35:56.303 ERROR vector::topology: Configuration error: Sink "pulsar_output": consumer error: Connection error: CommandError { request_id: 0, error: AuthorizationError, message: "Client is not authorized to subscribe" }
```

The auth token has not the right to consume, but with healthcheck false it must not tries, right?

**Comment by KannarFr** [comment]
I think the consumer is created even if the healthcheck is not ran. Possible?

**Comment by KannarFr** [comment]
@binarylogic ^

**Comment by binarylogic** [comment]
@leshow you built this sink. Maybe you understand better what is happening here? Healthchecks should be optional, so I'm curious if it's doing more than it should?

**Comment by leshow** [comment]
A shot in the dark here because I don't really follow the above thread, I think I see where a problem could be, we should move this line: https://github.com/timberio/vector/blob/master/src/sinks/pulsar.rs#L171 into a `futures::lazy` or somethign similar so that it doesn't run `build` inside that method.

**Comment by binarylogic** [comment]
Thanks for chiming in. Would you mind doing that? Otherwise, we'll have someone do it next week-ish.

**Comment by leshow** [comment]
I could make a PR to make this change if you'd like?

**Comment by KannarFr** [comment]
Thanks to both of you.

**Comment by leshow** [comment]
does the kafka sink have the same problem? https://github.com/timberio/vector/blob/master/src/sinks/kafka.rs#L212

It calls `create` in it's healthcheck method also.
