### ISSUE TITLE
Sink Datadog Metrics doc setting not working for retry_attempts

### ISSUE THREAD

**Issue by szibis** [timberio/vector#2476]
```
  # Request
  request.in_flight_limit = 5 # optional, default, requests
  request.rate_limit_duration_secs = 1 # optional, default, seconds
  request.rate_limit_num = 5 # optional, default
  request.retry_attempts = -1 # optional, default
  request.retry_initial_backoff_secs = 1 # optional, default, seconds
  request.retry_max_duration_secs = 10 # optional, default, seconds
  request.timeout_secs = 60 # optional, default, seconds
```
but. -1 for request.retry_attempts is not correct value. 

```
Apr 28 13:26:45 ip-10-105-195-187 vector[7779]: Apr 28 13:26:45.245 ERROR vector: Configuration error: "/etc/vector/vector.toml": invalid value: integer `-1`, expected usize for key `sinks.datadg_metrics`
```

**Comment by binarylogic** [comment]
Hi @szibis thanks. I think that is meant to signal that it'll retry indefinitely. But I agree, the docs should be clearer. We'll fix.

**Comment by szibis** [comment]
Yes that was my point it is not about what this should be and this should support unlimited retries but also doc missing that. Also, this will support unlimited retries ??

**Comment by binarylogic** [comment]
@szibis we updated our docs to reflect the actual default which is `18446744073709552000`. Our intent is to infinitely retry. If you want infinite retries you can simply leave the option out of your config.

**Comment by binarylogic** [comment]
Thanks again for reporting @szibis, and apologies for the docs issue. I'm closing this since this is fixed in our docs.
