### ISSUE TITLE
Add `include_units` and `exclude_units` and deprecate `units` in `journald` source

### ISSUE THREAD

**Issue by KannarFr** [timberio/vector#2478]
Currently there is no way to exclude systemd units? Like * excepts specified units.

**Comment by binarylogic** [comment]
@KannarFr to clarify, you want pattern/prefix support when excluding Systemd units?

**Comment by KannarFr** [comment]
We can imagine multiple ways, as you prefer, I can suggest that:

A:
```
units = [] # all (as current version)
excluded-units = ["a.service"] # minus a.service
```

B:

```
units = ["-a.service"] # would be all minus a.service
```

But maybe you have another idea?

**Comment by binarylogic** [comment]
Yeah, we have a pattern of using `include_*` and `exclude_*`. I think the following would work:

```toml
include_units = [...]
exclude_units = [...]
```

We could do that without pattern support fairly easily.

**Comment by KannarFr** [comment]
Cool, so it will be either `units` or `include_units/exclude_units`?

**Comment by binarylogic** [comment]
@bruceg is this possible given that we interface with `journalctl`?

**Comment by bruceg** [comment]
We handle filtering units internally instead of passing any options to `journalctl` for that. So, we can set the policy to whatever we can describe by code.
