### ISSUE TITLE
Support Datadog Log's new HTTPs transport

### ISSUE THREAD

**Issue by szibis** [timberio/vector#2504]
In the latest Datadog Agent 6.19 and 7.19 new https transport is enforced by default for sending logs. Introduced in 6.14 and 7.14 and if any problems falling back to TCP transport.

This option is very nice because it allows standard HTTP compression on the transport layer which saves a lot of bandwidth on a network. 
Also, introduce some batching/rate limit conditions.

https://docs.datadoghq.com/agent/logs/log_transport/?tab=https

I think this. should be included in Vector and somehow similar to that one from Datadog metrics sink.

**Comment by binarylogic** [comment]
Thanks, @szibis

> if any problems falling back to TCP transport.

I'm curious, what issues would be present on HTTP but not on TCP? This will inform our implementation.

**Comment by szibis** [comment]
Not on Vector on DD docs they say that if any HTTP is not available they still use TCP but this may change in time.

For me in Vector switch to HTTP is compression and I think many that use high throughput on DD logs sending will be happy.

**Comment by binarylogic** [comment]
That makes sense. It's a tradeoff, of course. You're trading real-time delivery for compression, but real-time delivery doesn't matter if DataDog is not processing it as such (eg. they're batching in ingestion anyway). Either way, this can be reduced by lowering Vector's `batch.timeout` option.

**Comment by szibis** [comment]
This type of data is compressing like a charm. This is why compression even on the HTTP standard is a very throughput saving feature and makes more space to transfer more on the same network. With this DD make very similar to Metrics where we have batches and in the batch we can compress all.

**Comment by szibis** [comment]
This issue is going to be more critical than previously imagined as Datadog is not supporting TCP traffic on 10516 in PrivateLinks setups - https://docs.datadoghq.com/agent/guide/private-link/?tab=metrics#client-configuration. This is only allowed from public side endpoints and with TCP this is very cost consuming from transfer side - no compression and public endpoints ar in cloud traffic charged more.
All this makes Vector setup for Logs a very expensive option right now for Datadog Traffic.

**Comment by jamtur01** [comment]
@binarylogic I think this should go into the next sprint or assigned to someone soon'ish. We can pretty easily replace the `TcpSink` with a `HttpSink` I think.

**Comment by FungusHumungus** [comment]
@jamtur01 Do we want to support both Tcp and Http which an option to choose which one, or should I completely ditch the Tcp?

**Comment by jamtur01** [comment]
Unless I am missing something, everyone will be sending upstream to DD so I think we can ditch the TCP. I can't thin of a scenario where someone would be targeting some other service or destination.

**Comment by FungusHumungus** [comment]
This could potentially be a breaking change as the endpoint will be changing. If people have their data stored in the Eu, they will need a different endpoint to the Us and will need to change their configs accordingly.

Related #4070

**Comment by jamtur01** [comment]
Let's make region configurable on our end and document that. Would that solve the issue?

**Comment by FungusHumungus** [comment]
> Would that solve the issue?

Yes. Some people may need to update their configs to accomodate, and as long as they are aware it should be fine.
