### ISSUE TITLE
Consider enabling tls by default

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#2528]
Currently, in our `TlsConfig` the `enabled` option is set to `false` by default. Most of our sinks by default should be using tls. So I'd like to propose that we change the default behavior of `TlsConfig`.

**Comment by binarylogic** [comment]
Let's start by only enabling this for sinks where it is obvious, such as hosted sinks where data is being sent over the public internet.

**Comment by jamtur01** [comment]
Closing in favor of #2445
