### ISSUE TITLE
Sink Loki not working when multi-tenancy is enabled

### ISSUE THREAD

**Issue by xunleii** [timberio/vector#2535]
Currently, the field `tenant_id` in Loki sink doesn't work, due to a typo in the request `X-Scope-OrgID`, required for the multi-tenancy mode of Loki. (https://github.com/grafana/loki/blob/master/docs/operations/multi-tenancy.md)

_PS: because I forgot to read the `CONTRIBUTING` guide **before** making any changes (sorry for that), a fix is already available and ready for a PR (https://github.com/xunleii/vector/tree/fix-loki-multi-tenant)_

**Comment by binarylogic** [comment]
Thanks! We’ll get this merged. Appreciate the help.
