### ISSUE TITLE
Retention Sink Loki

### ISSUE THREAD

**Issue by romvarac** [timberio/vector#2538]
Hi team, 
In config sink loki, I don't see anything config about retention log in loki.
Thanks

**Comment by LucioFranco** [comment]
This sounds like a config you apply directly on the loki install rather than what vector sends? https://github.com/grafana/loki/blob/master/docs/operations/storage/retention.md

**Comment by binarylogic** [comment]
Hi @romvarac, let us know if the above comment does not resolve your issue.
