### ISSUE TITLE
Increase error level for parsing JSON from debug to info 

### ISSUE THREAD

**Issue by valerypetrov** [timberio/vector#2552]
Hi, sometimes hosts may send not valid JSON to vector. 
It would be convenient if the log level of the incorrect JSON were info, not the debug. 

```
impl Transform for JsonParser {
    fn transform(&mut self, mut event: Event) -> Option<Event> {
        let log = event.as_mut_log();
        let to_parse = log.get(&self.field).map(|s| s.as_bytes());

        let parsed = to_parse
            .and_then(|to_parse| {
                serde_json::from_slice::<Value>(to_parse.as_ref())
                    .map_err(|error| {
                        debug!(
                            message = "Event failed to parse as JSON",
                            field = self.field.as_ref(),
                            %error,
                            rate_limit_secs = 30
                        )
                    })
                    .ok()
            })
            .and_then(|value| {
                if let Value::Object(object) = value {
                    Some(object)
                } else {
                    None
                }
            });

```

```
May 06 09:30:38.229 DEBUG transform{name=json_parser_app type=json_parser}: vector::transforms::json_parser: 1 "Event failed to parse as JSON" events were rate limited. rate_limit_secs=5 
```

**Comment by Alexx-G** [comment]
Is there any significant memory/processing pressure in case there's a source that sends lots of logs in a non JSON format and all logs go through a json parser before sending them to a sink?
There are use cases when some libraries don't allow setting log format, so an app might log a mixture of JSON and plain text logs, making it impossible to filter by container or any other metadata and the only way to handle it is using json parser for the entire log stream. Even if we ignore previous use case, in K8S there are lots of services that don't log JSON, that would mean to use swimlanes/filter to split logs in JSON/non-json streams keeping (potentially) long lists of container names or other metadata to distinguish such services.
I guess my question is more about best-practice/usage. Are there any downsides/performance penalties (considering new log level) in using JSON parser as I described?

**Comment by lukesteensen** [comment]
@Alexx-G 

Good question. I don't imagine there would be a major performance penalty for situations like that. There may be some error paths that are slightly more expensive than the successful parsing paths, but you also would avoid the overhead of actually inserting all the parsed fields. So my semi-educated guess is that it wouldn't be a big deal, but I have not actually tested it :smile:
