### ISSUE TITLE
Systemd not reloaded after a package upgrade

### ISSUE THREAD

**Issue by gtie** [timberio/vector#2553]
After upgrading to vector 0.9.1 using `apt` on a Debian system, I noticed the following warning in systemd after restarting the `vector` service:
```
# systemctl status vector
Warning: The unit file, source configuration file or drop-ins of vector.service changed on disk. Run 'systemctl daemon-reload' to reload units.
● vector.service - Vector
   Loaded: loaded (/etc/systemd/system/vector.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/vector.service.d
           └─override.conf
   Active: active (running) since Wed 2020-05-06 09:36:47 UTC; 12min ago
```
A bit of poking around showed that no content changed in the stock `/etc/systemd/system/vector.service` file or in my overrides. The only difference was the _timestamp_ on `vector.service` file!

It is certainly easy to make that message go away, and run a manual daemon-reload, but it should not be necessary with a well-behaved .deb package. Running a daemon-reload should instead be done in a post-install script, and it is going to be even more important to do so when the service file does change in a future version.

**Comment by binarylogic** [comment]
Thanks @gtie, agree. I was not aware this was the behavior. We’ll prioritize get this fixed.
