### ISSUE TITLE
ld error: leveldb-sys + fPIC

### ISSUE THREAD

**Issue by fanatid** [timberio/vector#2600]
I'm not sure what's happen (maybe latest packages updates? Fedora31), but I start getting error:
```
= note: /usr/bin/ld: /home/kirill/projects/timberio-vector/target/debug/deps/libleveldb_sys-608f70936754b11b.rlib(snappy.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIC
```

I removed leveldb files from target directory (`find target/ | grep leveldb | xargs -L 1 rm -rf`) and run:
```
CXXFLAGS="-fPIC" cargo build
```
build was successful.

I checked build logs and difference only in flags for building snappy:
`
[leveldb-sys 2.0.5] /bin/sh ./libtool --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.     -g -O2 -MT snappy.lo -MD -MP -MF .deps/snappy.Tpo -c -o snappy.lo snappy.cc
`
vs
`
[leveldb-sys 2.0.5] /bin/sh ./libtool --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.     -fPIC -MT snappy.lo -MD -MP -MF .deps/snappy.Tpo -c -o snappy.lo snappy.cc
`

Any ideas on this?

**Comment by binarylogic** [comment]
Thanks for reporting @fanatid. Could you give us more information on your environment? OS, version, etc. Thanks.

**Comment by fanatid** [comment]
```
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 31 (Thirty One)
Release:	31
Codename:	ThirtyOne
$ gcc --version
gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
$ dnf list installed snappy*
Installed Packages
snappy.x86_64            1.1.7-9.fc31                 @fedora
snappy-devel.x86_64      1.1.7-9.fc31                 @fedora
```
Anything else?

**Comment by fanatid** [comment]
Error is disappeared with rust 1.46
