### ISSUE TITLE
Humio sinks documentation lists `host` as optional

### ISSUE THREAD

**Issue by jmountifield** [timberio/vector#2605]
The host option for the Humio sink is a required parameter:

https://vector.dev/docs/reference/sinks/humio_logs/#host

This also impacts the docker examples here when selecting "Humio Logs" as output option:

https://vector.dev/docs/setup/installation/operating-systems/macos/

**Comment by fanatid** [comment]
The only difference between docs and code for humio is that docs says that `host` is optional while in code default value is `https://cloud.humio.com`.
https://github.com/timberio/vector/blob/5904a3e2e6011b1bc616ef236528d3c320f04a3a/src/sinks/humio_logs.rs#L8
https://github.com/timberio/vector/blob/5904a3e2e6011b1bc616ef236528d3c320f04a3a/src/sinks/humio_logs.rs#L66

Is this looks correct?

**Comment by Hoverbear** [comment]
Yeah, sorry about this @jmountifield ! @fanatid has us covered. Thank you again Kirill!
