### ISSUE TITLE
Detect and error on header collisions

### ISSUE THREAD

**Issue by lukesteensen** [timberio/vector#2608]
See https://github.com/timberio/vector/issues/2599#issuecomment-628677546

The `http` sink has authentication options that result in headers being set, as well as the ability to set headers directly. We should identify when these two sets of headers collide and present an error to the user at startup.

**Comment by fanatid** [comment]
Would like submit PR for this.

**Comment by lukesteensen** [comment]
Sounds good! It's all yours @fanatid :smile:
