### ISSUE TITLE
Unify processing of all data types

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#2610]
Given that Vector collects all data types (logs, metrics, and traces in the future), we should take care to unify the processing and enriching of this data. This ensures that the data is correctly correlated, a highly sought after feature. There are a few areas we can improve upon this:

- [ ] Ensure all enrichment type transforms work on all data.
- [ ] Unify transforms that add, remove, and rename fields. This will likely be done with our new mapping language.

**Comment by szibis** [comment]
Also in the future, this should support Traces correlation and join through specific attributes in all components like tags and reserved by vector or user fields customized to be compatible with external vendor.

This is how Datadog, for example, uses this by specifying reserved attributes from host-level metrics through all the features like metrics, logs, traces - https://docs.datadoghq.com/logs/processing/attributes_naming_convention/ Some are hidden but in Vector can be easily created by adding/replacing any tag/field.  Have that in the scheme. through whole Vector pipe flow, built-in would be a nice addition to controlling that on the Vector level.
Now we. need to build static lists in add_fields and tags to maintain that for example internal Datadog ddtags field ```ddtags=region:us-east-1,env:dev,host:web``` which will decorate. in Datadog as usable tags the same ddsource and all from a link above.

**Comment by binarylogic** [comment]
Closing in favor of #3550
