### ISSUE TITLE
Elasticsearch Sink Issue

### ISSUE THREAD

**Issue by ragazzid** [timberio/vector#2634]
Hey there, I was following the doc (https://vector.dev/docs/reference/sinks/elasticsearch/) to get data from kafka and send it to es (hosted by amazon) but I'm getting the following errors:
Version
```
./bin/vector --version
vector 0.9.1 (v0.9.1 x86_64-unknown-linux-musl 2020-04-30)

```
Config
```
[sources.s_kafka]
  type = "kafka" # required
  bootstrap_servers = "mykafka:9600" # required
  group_id = "vector_test" # required
#   key_field = "message_key" # optional, no default
  topics = ["my_topic"] # required

[sinks.o_elastic]
  type = "elasticsearch" # required
  inputs = ["s_kafka"] # required
  auth.strategy = "aws"
  # aws.region = "us-east-1"
  compression = "none" # optional, default

  healthcheck = true # optional, default
  host = "https://aws_es_endpoint:443" # optional, no default
  index = "vector-%F" # optional, default
```
Errors
```
# When I set the aws.region
May 18 17:01:16.599 ERROR vector: Configuration error: "/tmp/vector/config.toml": unknown field `aws`, expected one of `host`, `index`, `doc_type`, `id_key`, `compression`, `encoding`, `batch`, `request`, `auth`, `headers`, `query`, `tls` for key `sinks.o_elastic`
# When I comment out aws.region
May 18 17:02:34.184  INFO vector::topology: Running healthchecks.
May 18 17:02:34.303 ERROR vector::topology::builder: Healthcheck: Failed Reason: Unexpected status: 403 Forbidden
May 18 17:02:34.303 ERROR vector::topology: Sinks unhealthy.
```
I'm pretty sure roles permission are correct because it works when I use logstash
Any idea?

**Comment by bruceg** [comment]
The `aws` option is something that was recently added, and is only available in the nightly version.

The health check invokes a request that requires read access. If the account accessing AWS ES only has write access, it will cause a 403 error that you observe. We could possibly ignore a 403 error. @lukesteensen you commented recently on this behavior, what do you think?

**Comment by lukesteensen** [comment]
Yes, this is a challenge we've had with making meaningful healthchecks. We try to read instead of writing dummy data (which seems undesirable), but that requires different permissions and isn't perfectly representative of normal operation.

In this case, I'd probably recommend just turning off the healthcheck. Hopefully this is something we can improve in the future, but it's a little tricky.

**Comment by ragazzid** [comment]
Oh ok, got it for the aws.region part, but regarding of the health-check, I was using Administrator Access (as a test) and even disabling the health check messages could not be delivered to the ES cluster.

**Comment by bruceg** [comment]
This is likely the same issue as #2403, and is fixed in the nightly releases.

**Comment by bruceg** [comment]
It appears this is resolved. Please reopen if that is not the case.
