### ISSUE TITLE
Upgrade warp based sources/sinks

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#2643]
This is a tracking issue for upgrading warp based sinks/sources. All of these components use warp and will require upgrading to the latest version `0.2`.

## Sinks to upgrade

- [ ] `prometheus` 

## Sources to upgrade

- [ ] `http`
- [ ] `splunk_hec`
- [ ] `logplex`

## Notes

These sinks should be pretty straight forward upgrade since I don't believe the `warp` api has changed that much. There is one in-flight PR that should resolve the only remaining issue to upgrade https://github.com/seanmonstar/warp/pull/581. Once that is merged I think this should be ready to be worked on.

**Comment by lukesteensen** [comment]
@fanatid is this done? I only see `warp v0.2.3` in our tree now :tada:

**Comment by fanatid** [comment]
Yes! Done in https://github.com/timberio/vector/pull/2837
