### ISSUE TITLE
Pulsar Sink limited encoding configuration

### ISSUE THREAD

**Issue by nickelozz** [timberio/vector#2648]
As found [here](https://vector.dev/docs/reference/sinks/pulsar/#encoding), the documentation says that the encoding configuration has multiple sub elements (e.g.: codec, only_fields). However, trying to set up ```encoding.codec = "json"``` generates the following error:

```bash
... ERROR vector: Configuration error: "/etc/vector/vector.toml": unknown variant `codec`, expected `text` or `json` for key `sinks.pulsar`
```

Additionally, adding any other options such as ```encoding.timestamp_format = "rfc3339"``` produces the following error:

```bash
... ERROR vector: Configuration error: "/etc/vector/vector.toml": invalid value: map, expected map with a single key for key `sinks.pulsar`
```

So the only way I was able to run the sink without any issues was when I set the value as ```encoding = "json"```.

This makes me wonder not only if there's a mistake in the docs but also if there's no way to setup the additional configuration options such as ```only_fields``` or ```timestamp_format```?

**Comment by leshow** [comment]
Looks to me like a mistake in the generated docs, maybe. The sink only supports `encoding = "json"` or `"text"` to the best of my knowledge. I got some help from on the doc generation front so that territory is pretty unknown to me.

**Comment by fanatid** [comment]
From code it's looks like `encoding` can be only `text` or `json`, so docs are incorrect.
https://github.com/timberio/vector/blob/6281932469d9bcef34edaf672b52edc804d49732/src/sinks/pulsar.rs#L29
https://github.com/timberio/vector/blob/6281932469d9bcef34edaf672b52edc804d49732/src/sinks/pulsar.rs#L41-L44

**Comment by lukesteensen** [comment]
It looks like pulsar did not get upgraded to the newer `EncodingConfig` wrapper that implements the new configuration options. We should do that upgrade and audit for other components that may also be out of sync.

**Comment by leshow** [comment]
I can take a look at updating this in the next few days if you like. I took a look at some of the existing sinks that use `EncodingConfig` and it looks to be a relatively small change.

**Comment by lukesteensen** [comment]
That'd be wonderful, thank you @leshow!
