### ISSUE TITLE
syslog: add host ip custom field

### ISSUE THREAD

**Issue by suvl** [timberio/vector#2655]
While using `syslog` as my source, I'm trying to keep both the hostname parsed from the syslog message and the host IP address (as a custom field or something else). I can't seem to find any docs about custom fields coming from properties of the source, are there any? Is there a way to do this or do I need to go with the `socket` source?

**Comment by Hoverbear** [comment]
Agreed! Let's add this! It sounds super useful.

@binarylogic Do you think we should make a global `host_ip` as right away, or keep it `syslog` local to start?

**Comment by lukesteensen** [comment]
I think the complexity here is how it interacts with the existing `host` field. Just adding another field seems like it would create its own set of problems and backwards-incompatibilities.

This is definitely a useful thing to support, it just clashes with some of the assumptions we've made around the log schema.

**Comment by Hoverbear** [comment]
Okay, so lets just put `host_ip_key` as a `syslog` option for now :)

**Comment by Hoverbear** [comment]
So, I'm reviewing the behavior a bit more... 

The current behavior of syslog is like so, where `host` contains the IP of the sending host. So it seems like this issue can be done by setting `host_key = "host_ip"`?

![Screenshot_20200521_095506](https://user-images.githubusercontent.com/130903/82584644-a1f00100-9b49-11ea-954f-0ecf983bf6bb.png)

This issue is that you'd like `host_ip` to contain what exactly? Or does the syslog message contain a `host` key already? Perhaps Vector is setting the host correctly but it's getting parsed and overwritten?

**Comment by suvl** [comment]
@Hoverbear I should have missed the docs where they talk about the possible values of `host_key` and what they mean to each source.

Even so, that'll overwrite the `host` field replacing the hostname parsed from the message with the client IP. I wanted to keep both those values as fields using maybe a custom field that'd read from an `host_ip` source property, but couldn't find any docs on how to do that.

**Comment by Hoverbear** [comment]
So you're trying to include both the syslog source host IP and some sent `host` field from the syslog? Or am I misunderstanding the goal?



![image](https://user-images.githubusercontent.com/130903/82586970-43c51d00-9b4d-11ea-896d-d72d52e46ff8.png)


```
data_dir = "/var/lib/vector/"
dns_servers = []

[sources.source0]
type = "syslog"
mode = "tcp"
encoding = "json"
address = "0.0.0.0:8080"
host_key = "host_ip"

[transforms.parser]
type = "json_parser"
inputs = ["source0"]

[sinks.sink0]
healthcheck = true
inputs = ["parser"]
type = "console"
encoding = "json"

[sinks.sink0.buffer]
type = "memory"
max_events = 500
when_full = "block"
```

**Comment by suvl** [comment]
@Hoverbear yeap that's it but remember that the host field from the docs:

> The hostname extracted from the Syslog line. If a hostname is not found, then Vector will use the upstream hostname.

So when I set `host_key = "host_ip"`  in my config I get these logs:

```
{"appname":"testtag","facility":"daemon","host_ip":"zd4500zno-4434A7990E3E","message":"4.1.038.n.prod-b Stopped G4client start.||10.216.222.51","procid":1,"severity":"info","source_type":"syslog","timestamp":"2020-05-21T17:36:10Z"}
```

Well the host_ip should be `10.0.0.132` (the IP of my client) and I should have a `host` field equal to `d4500zno-4434A7990E3E`.

The log line that produced the above parsing and that you can `nc` in this specific case is this:

```
<30>1 2020-05-21T17:36:10Z zd4500zno-4434A7990E3E systemd 1 - - 
4.1.038.n.prod-b Stopped G4client start.||10.216.222.51
```

**Comment by Hoverbear** [comment]
Okay awesome! Thanks so much for this clarity. I'll start on this now. :)

**Comment by Hoverbear** [comment]
I think this is kind of a UX bug in that it's very surprising.

Basically: `syslog` has a `hostname` field by convention, we have a `host_key` option, this `host_key` option tries to be clever and if it's set and a `hostname` is detected by `syslog` then it sets `host_key`'s value to that value and throws the `hostname` away. I'd like to make `host_key` has no impact on `hostname`, so you'd always have `hostname` from `syslog` and `host` would be that ip :)

**Comment by suvl** [comment]
@Hoverbear that sounds fine! How do you plan it'll behave in case of not finding the hostname in the syslog message? Will it just not add the `hostname` field?

**Comment by Hoverbear** [comment]
@suvl I think that'd be least surprising? :)

Is this matching the behavior you'd expect?

![image](https://user-images.githubusercontent.com/130903/82594624-39a91b80-9b59-11ea-98c4-9095fe3f45f3.png)

**Comment by suvl** [comment]
> @suvl I think that'd be least surprising? :)

@Hoverbear yeap that'd be what I would expect of it, but it kinda breaks what's on the docs so that'll have to be changed too 😄 

> Is this matching the behavior you'd expect?
> 
> ![image](https://user-images.githubusercontent.com/130903/82594624-39a91b80-9b59-11ea-98c4-9095fe3f45f3.png)

I assume that the `msg` field would have the atual message but it has not 'cause there's a newline on the bin file, so it matches exactly what I'm up to 😃 (the newline is my own copy&paste mistake on the example I've given above).

btw, thanks for all your help and consideration on this.
