### ISSUE TITLE
Vector Source Behind Loadbalancer Creates Large Amount of Logs

### ISSUE THREAD

**Issue by jasonmfehr** [timberio/vector#2664]
When running a source of type `vector` behind a loadbalancer that does healthchecking (for example AWS EC2 network load balancer), the vector logs have a huge volume of warnings written to them similar to:

```
May 21 21:14:33.126  WARN source{name=logs-vector type=vector}:connection{peer_addr=x.x.x.x}: vector::internal_events::tcp: connection error. error=TLS handshake failed: unexpected EOF
May 21 21:14:33.126  WARN source{name=logs-vector type=vector}:connection{peer_addr=x.x.x.x}: vector::sources::util::tcp: Error received while processing TCP source
```

@lukesteensen suggested on gitter to set the `LOG` environment variable to `vector::sources::util::tcp=error,vector::internal_events::tcp=error`.  This works with the side-effect of also hiding informative logs.

**Comment by jasonmfehr** [comment]
Here is a sample vector config:

```
[sources.logs-vector]
type = "vector"
address = "0.0.0.0:12345"

tls.enabled = true
tls.ca_path = "/etc/vector/root-ca.pem"
tls.crt_path = "/etc/vector/crt.pem"
tls.key_path = "/etc/vector/key.pem"
tls.verify_certificate = true
```

**Comment by jasonmfehr** [comment]
I assume the logs stem from the fact that the loadbalancer healthchecking is not presenting any cert.  Can requests without a cert be logged at a debug level or put into their own log module so the `LOG` env var can be used to ignore just those warnings?

**Comment by Hoverbear** [comment]
Hey @jasonmfehr , sorry Vector is so verbose here! We can definitely improve this.

I agree `WARN` is a bit severe, but I worry `DEBUG` will be missed by some users. How about `INFO`?

I will also rate limit the log, so it won't spam.

**Comment by jasonmfehr** [comment]
Sounds good.  Thanks!
