### ISSUE TITLE
Not all tests are running in CI

### ISSUE THREAD

**Issue by ktff** [timberio/vector#2673]
Tests for at least some of the `sources` aren't being run in CI. For example for `socket` source tests in `/src/sources/socket/mod.rs` aren't being run.

Noting, all those tests are being run locally and they are passing.

An additional CI check for `sources` feature could be added.

**Comment by Hoverbear** [comment]
This is probably resulting from 

https://github.com/timberio/vector/blob/f6e0eb2eb87fe874d56261d61522fdc2928d8966/.github/workflows/code.yml#L7-L31

Would we be game for running the full CI on each PR?

**Comment by ktff** [comment]
For the `source` tests the issue is that they aren't enabled through the feature sets in none of our CI testing. And from what I've searched through local `make` testing, they aren't running them either, for the same reason. They do show up on regular `cargo test` since the `default` feature set contains `sources` feature which is necessary to enable them.

**Comment by binarylogic** [comment]
Thanks for finding this @ktff. If possible could you fix this?
