### ISSUE TITLE
feature request: syslog does not allow for RFC6587 when set to "TCP"

### ISSUE THREAD

**Issue by suvl** [timberio/vector#2690]
We've got devices that will follow the [RFC6587](https://tools.ietf.org/html/rfc6587) specification. They send logs using Octet Counting as specified in 3.4.1. of that same RFC. It improves on syslog to allow for all characters to be sent, so you can send logs with `\n` characters if you need to, like sending lists of things or stack traces.

Logs sent by those devices look like this in raw text mode:
```
136 <14>1 2020-05-26T18:36:57.000000+01:00 zc4430kno-4234A71FAD01 kernel - - - [  128.604348] bcmgenet f0480000.ethernet eth0: Link is Down
259 <14>1 2020-05-26T18:36:57.000000+01:00 zc4430kno-4234A71FAD01 syslog 1952 - - 200526-17:36:57.976506 [mod=evo-platform, lvl=INFO] [tid=1992] SPlatformEthernetD  INFO SPlatformEtherne : platform_ethernet_driver_netlink_callback:network eth0 link is 'DOWN'
256 <14>1 2020-05-26T18:36:57.000000+01:00 zc4430kno-4234A71FAD01 syslog 1952 - - 200526-17:36:57.977317 [mod=evo-platform, lvl=INFO] [tid=1992] SPlatformEthernetD  INFO SProxy :  S_proxy_network_interface_event_handler : Update MAC to 44:34:a7:1f:ad:01
282 <14>1 2020-05-26T18:36:57.000000+01:00 zc4430kno-4234A71FAD01 syslog 1952 - - 200526-17:36:57.977466 [mod=evo-devconfig, lvl=INFO] [tid=1992] SPlatformEthernetD  INFO RemoteDeviceConfig : onChanged_callback: Something happened to config: clientDevice.DeviceId value: 4234a71fad01
127 <30>1 2020-05-26T18:36:57.000000+01:00 zc4430kno-4234A71FAD01 WPEFramework 1669 - - Interface: eth0 changed state new state: 2
365 <14>1 2020-05-26T18:36:57.000000+01:00 zc4430kno-4234A71FAD01 syslog 1952 - - 200526-17:36:57.977623 [mod=evo-platform, lvl=INFO] [tid=1992] SPlatformEthernetD  INFO SPlatformEtherne : platform_ethernet_driver_debug_print_interfaces: 
interface name='lo' 
link='UP' 
ipaddr='127.0.0.1' 
netmask='255.0.0.0' 
mac='00:00:00:00:00:00' 
gateway='' 
DNS='127.0.0.1'
```
can you see on the last log message as a multiline log might be useful?

right now these logs fail to be parsed by the sink, and are just processed as 
```
{"host":"89.152.250.225","message":"138 <30>1 2020-05-26T17:10:04.000000+01:00 zc4430kno-4234A71FAD01 WPEFramework 1616 - - 4.46.0.m.lab_development NCL ocdm_cb_thread();Looping","source_type":"socket","timestamp":"2020-05-26T16:10:04.778532001Z"}
```
as if they were from the `socket` sink. 

It'd be nice to also support this RFC as well as the other two already supported by the sink. It involves:
1. not using the `\n` delimiter as signal of a message ending, and
2. using the byte count given at the top to know how many bytes to load into a message before applying parsing.

As of the low level details, the byte count is sent on a separate TCP packet, 
![image](https://user-images.githubusercontent.com/6018083/82937203-aa9c6900-9f87-11ea-942d-1dc9eac2c003.png)

and then after an ACK the actual message is sent.
![image](https://user-images.githubusercontent.com/6018083/82937217-b1c37700-9f87-11ea-8973-433f36c97ec4.png)

and that can be useful too for pre-allocating some buffer needed for the entire message.

**Comment by lukesteensen** [comment]
Thanks for opening this @suvl! This is definitely something we plan to support.

**Comment by ktff** [comment]
Noting that from [RFC6587](https://tools.ietf.org/html/rfc6587) we also don't support `Non-Transparent-Framing` feature, but it doesn't seem to be something that we would like to support until the need for it arises.
