### ISSUE TITLE
Config to pass pipeline name in ES sink

### ISSUE THREAD

**Issue by raghu999** [timberio/vector#2691]
Hello Vector Team 

We are trying to parse some data using Ingest node and want to pass pipeline name to elasticsearch sink does vector support this config option?

[Filebeat Config Reference](https://www.elastic.co/guide/en/beats/filebeat/current/configuring-ingest-node.html#configuring-ingest-node)

**Comment by lukesteensen** [comment]
We don't currently but that would be a great addition, thank you for the suggestion! That should be a relatively straightforward change.

**Comment by raghu999** [comment]
The new version supports adding the pipeline name thanks for the quick turn around.
