### ISSUE TITLE
[releases] release pace + dev releases?

### ISSUE THREAD

**Issue by Diliz** [timberio/vector#2699]
Hello Timber PPLs!

First of all, thanks for your work, this issue will look as a complaint, but it's not the case at all, so sorry for that :/

I saw that vectore release pace is large, there's multiple weeks between patch versions, patch version which contains a lot of things actually.

It can be really risky to do that, since waiting too long to expose new features/fixes exposes to more bugs at the same time as well, instead of maintaining a bug flow by releasing more often.

For example: The v0.9.1 kafka source is not working with tls pass and path arguments, this was fixed now, but you'll have to wait maybe 4 weeks before having it working again, hopefully with no other bugs (I'm not saying it was not fixed correctly there, it could be any other fix or feature, and any bug that persists that was not seen when the fix was developped).

I dunno if this can help in anyway, but what we're doing were I work is using the commit messages to generate changelogs, when a pull request is merged in our master branch, it triggers 'dev' releases, with automatic changelogs generated with the commit messages (with a standard commit messages format).

Then when we want to trigger a "production" release, we do it manually (just clicking a button), you can write your release note there.

Applying the same kind of release management to vector would not change the production releases pace today, just the exposure of `in developpement` features, so your customers can try new features not every 3/4 weeks, making the bugs/ideas coming faster.

Thanks for reading 👍

**Comment by Hoverbear** [comment]
We do have nightly releases you can try listed on https://vector.dev/releases/0.9.1/download/ :)

Typically it's our goal not to release things that don't work! We're trying to get better about that. Sorry for this causing you troubles.

**Comment by Diliz** [comment]
Damn didn't saw there was, was looking for them on github, thanks for the response. Sorry for the pebkac there :)
