### ISSUE TITLE
Custom message timestamp on kafka source and sink

### ISSUE THREAD

**Issue by afoninsky** [timberio/vector#2700]
I want to push incoming events to Kafka using custom timestamp (not the current one). Later I want to consume them by custom service and make additional logic based on it.
Architecture looks like this:
`[external producer]->(data)->[vector kafka source]->[kafka queue]->[internal custom consumer]`

Unfortunately, I can't find the way how I can emit kafka message with timestamp extracted from (data) payload. Is it doable?
Thank you.

**Comment by shamil** [comment]
In `logstash` this is accomplished using [`decorate_events`](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-kafka.html#plugins-inputs-kafka-decorate_events). This is the only setting that blocks me from moving out of `logstash`. I need the timestamp from the message and not from the ingestion time
