### ISSUE TITLE
Regex Parser Documentation error

### ISSUE THREAD

**Issue by SyluxDX** [timberio/vector#2725]
The documentation for `regex_parser` says to configure the regex pattern in the field `patterns`, but if you do this you will get an error saying that `patterns` is an unknown field and to use the field `regex`

`regex_parser` configuration
```
[transforms.client_regex]
  type = "regex_parser"
  inputs = ["curl"]
  field = "hostname"
  overwrite_target = true
  patterns = "['^(?P<client_model>[\\d\\w]+)-(?P<client_mac>[\\d\\w]+)']"
```
runtime output:
```
$ docker run --rm -v $PWD/vector-test.toml:/etc/vector/vector.toml timberio/vector:0.9.1-alpine
Jun 02 17:25:19.658  INFO vector: Log level "info" is enabled.
Jun 02 17:25:19.658  INFO vector: Loading configs. path=["/etc/vector/vector.toml"]
Jun 02 17:25:19.660 ERROR vector: Configuration error: "/etc/vector/vector.toml": unknown field `patterns`, expected one of `regex`, `field`, `drop_field`, `drop_failed`, `target_field`, `overwrite_target`, `types` for key `transforms.client_regex`
```

**Comment by xluffy** [comment]
@SyluxDX Check here https://github.com/timberio/vector/pull/2716

**Comment by bruceg** [comment]
This is a change that has landed in the current nightly releases but is not yet present in the latest stable release. This is a known issue (#2649) that we would like to resolve. We apologize for this confusion.
