### ISSUE TITLE
[NIGHTLIES] glibc update 2.17+

### ISSUE THREAD

**Issue by Diliz** [timberio/vector#2743]
Hello Vector team!

First, thanks for your work.

Just to tell you that centos 7 does not officially support glibc version > 2.17 today.

You seem to support RHEL, centos is based on it, I don't know if you support RHEL 7, but if it's the case, and if it's like centos (which seems to be the case), vector seems not installable the official way on centos 7/RHEL 7 with the latest nightlies builds, since the requirements for the latest vector builds for glibc is >= 2.18.

Maybe it's not an issue, maybe it's working on RHEL 7.X, I opened this issue just in case, since it's not working on centos 7 with official packages.

Regards

**Comment by binarylogic** [comment]
Thanks @dillz, we tried to use a very old version to avoid these kinds of issues. Glibc `2.18` was released in `2013`. But based on our [Glibc performance tests](https://github.com/timberio/vector/issues/2313#issuecomment-614022976) I don't see why we couldn't drop down to `2.17`. I'd want to run similar tests on that version before we do so.

**Comment by binarylogic** [comment]
@Hoverbear I think this is worth doing if we can drop the glibc version easily. I'm hoping we can just based our builds on an older debian version. If this is not a simple change let's defer it.

**Comment by Hoverbear** [comment]
Yeah! Let's do it. :)

**Comment by Hoverbear** [comment]
@Diliz Can you use the musl nightlies for now? :)

**Comment by Hoverbear** [comment]
Hmmm, I think the easiest way to do this short term is to move our builder to centos7.

**Comment by Diliz** [comment]
I'll try this when I can for sure!

Thanks for the fix :)

**Comment by Hoverbear** [comment]
Patiently waiting to see if my fix works 
![image](https://user-images.githubusercontent.com/130903/84698851-5c82e180-af05-11ea-98a6-82906241b60c.png)

**Comment by Hoverbear** [comment]
This seems to work fine! PR coming shortly.

![image](https://user-images.githubusercontent.com/130903/84705578-77a71e80-af10-11ea-992e-7411e6713253.png)

**Comment by Hoverbear** [comment]
@Diliz Here's a build that should work, I tested with centos7, once you see #2824 merge you should be able to use the next nightly.

https://hoverbear.ams3.cdn.digitaloceanspaces.com/vector-x86_64.rpm
