### ISSUE TITLE
New `remap` transform RFC

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#2744]
I'd like to create an RFC for Vicscript (happy to reconsider the naming 😄 ). The problem is outlined in #1926 and @Jeffail has already implemented something similar in benthos with [bloblang](https://www.benthos.dev/docs/guides/bloblang/about/).

The main questions I have:

1. Is this necessary given the new WASM runtime? I think so since we are not "blessing" any specific WASM compiler.
2. What is the scope of this language? (parsing, control flow, transforming, etc)
3. Does the team agree there is room for something like that?

**Comment by MOZGIII** [comment]
> Is this necessary given the new WASM runtime? I think so since we are not "blessing" any specific WASM compiler.

If we have a minimal language that evaluates during the config parsing (as in the examples at #1926) - it makes sense to have a transform that would reuse this code, and allow users to call into it independently. It might not make sense though if the scope of that language isn't a good fit.

If this would be a new special language - similar to how we have `lua` or `javascript` for instance - in general, WASM mostly eliminates the need for it. It would be cool though if let users type their script code verbatim in the config and then compile it into WASM transparently.
