### ISSUE TITLE
Inputs for metric, file, packet and heartbeat 

### ISSUE THREAD

**Issue by somehowchris** [timberio/vector#2757]
I know this can be done differently with the HTTP one too but I just saw that there's a Prometheus input so why not have those as different inputs too?

**Comment by lukesteensen** [comment]
Could you expand a bit on what you're looking for here? We have a number of sources for ingesting metrics, log files, etc.

**Comment by binarylogic** [comment]
I think he's referring to the Elastic beats:

* https://www.elastic.co/beats/heartbeat
* https://www.elastic.co/beats/packetbeat
* https://www.elastic.co/beats/metricbeat

@somehowchris, thanks for opening this. We are actively working on supporting similar metrics collection.

**Comment by somehowchris** [comment]
@lukesteensen sry seemed to miss that one 😅

@binarylogic yes indeed and I have seen the issue opens to support it and sadly as described there we can not move the whole system at once to vector as this would result in a split brain like Operation and indeed vector is missing some stuff that the elastic stack has just because of its maturity. 

Sadly I need to have a strategy as in like where I'm going with logging and monitoring for the next year within 17 days 😐 

Is there effort to support the logstash output and if so is there a ETA?

Keep up the good work🥳

**Comment by yogevyuval** [comment]
@binarylogic  @lukesteensen 
Thanks for being so responsive and for the good work.

I wanted to follow up here and clarify - 
Are you woking on have a "logstash" input so the Vector could potentially replace Logstash entirely? 
Meaning will we be able send winlogbeats directly to Vector?

Would appreciate some more info on this - thanks! I could open a new issue if needed
