### ISSUE TITLE
Instrument `http::send`

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#2766]
I was adding events to the k8s PR, and noticed that we don't have `http::send` (and `http02::send`) instrumented.
Do we want to add some events there? Probably we do, timing information and status code counts can be very useful for observability.

**Comment by binarylogic** [comment]
@MOZGIII this seems useful, I'm curious how it would overlap with the component-level events. Could you expand on the exact events we should add?

**Comment by MOZGIII** [comment]
I think we should have:

- request sent counter
  - method
- response received counter
  - status code
- response error counter (for network-level errors during response )
  - io error kind
- time-to-full-headers histogram (time from right before we start sending the request till the time we read all response headers)
  - status code

These events won't be very meaningful without additional contextual labels, but we're about to address that too.

**Comment by jamtur01** [comment]
@MOZGIII Do you have some space this sprint to pick this work up?
