### ISSUE TITLE
Sink Batch redesign

### ISSUE THREAD

**Issue by bruceg** [timberio/vector#2768]
I've started to look into the sink batch design in order to figure out how to best resolve #2742, #2394, and #2408, and I think I have discovered what the design issues were that were referenced in our planning meeting.

1. All the current batch implementations can either count bytes or events, but not both. This is at least partly due to the underlying data type for many sinks being a simple `Vec<T>`. If `T` is a structured event, then the "length" is a number of events. If it is `u8` or equivalent, then the batch counts bytes. Now, things like `JsonArrayBuffer` actually track both, so moving everything to a design like that might not be a huge effort, particularly since that type is well used, but:

2. Batch buffering, as it stands now, adds things to the batch *and then* checks the size. There is no facility for tentatively adding to the batch or pushing back once the batch is full. As such, the only way to tell if a batch is ready to send is if it has reached *or exceeded* one of its limits, either time or "size" ([ref `should_send`](https://github.com/timberio/vector/blob/23ba0dc395c5af4b64babb0e27a308d8b246c85d/src/sinks/util/sink.rs#L189)). If the batch is counted in number of events, this is no problem because they are added one at a time. However for byte-sized batches, this means that a sink that reaches its batch size before timeout will routinely exceed that limit.

I don't see a good way of dealing with either of these without reworking the batch design. I welcome input into alternative directions to take this, particularly since I foresee any such rework as taking considerable effort.

**Comment by bruceg** [comment]
Hmm, I see point 1 isn't entirely true, as there are separate `size` and `num_items` methods in `trait Batch`. However, it is still true that the former is used to represent either bytes or events, and the latter is only used to track acknowledgements after the batch is sent.

**Comment by binarylogic** [comment]
> Batch buffering, as it stands now, adds things to the batch and then checks the size.
> ...
> However for byte-sized batches, this means that a sink that reaches its batch size before timeout will routinely exceed that limit.

I'm curious which encoding types require this post-checking behavior? I ask because I'm curious if the culprit is JSON. You cannot stream-encode a JSON array, but there are tricks to get around this. For example, we can hold an array of JSON encoded events and then concatenate them when we're ready to send. With this strategy, we can still predict the payload size.

> Hmm, I see point 1 isn't entirely true, as there are separate size and num_items methods in trait Batch

So it should be possible to limit by both byte size and quantity?

**Comment by bruceg** [comment]
> I'm curious which encoding types require this post-checking behavior?

This isn't based on the encoding type, it's baked into the `BatchSink` design. So, everything that uses `BatchSink` that tries to count bytes is affected. I agree that there are ways to get around this for JSON, and that would actually be my first target.

> So it should be possible to limit by both byte size and quantity?

You'd think so, but that can only work currently for batch buffers that encode the event within the buffer. AFAICT there are three basic buffer designs:

1. Buffer stores bytes directly. These limit total bytes but event count is irrelevant because it's not tracked.
2. Buffer stores raw events. These limit event counts, but don't know byte counts.
3. Buffer encodes events into a common format (like JSON). This one can count both, but due to 1 and 2 it can't really be enabled. This would be my target.

In any case, the issue about buffer size still stands, as events are pushed into the buffer *and then* length checked. We need something where sending can be triggered when the next event would go over the maximum length, preferably without double encoding.

**Comment by binarylogic** [comment]
> We need something where sending can be triggered when the next event would go over the maximum length, preferably without double encoding.

Agree. Although, the cost of encoding one extra event is very small, especially when we're talking about batching. This is a reasonable tradeoff if we have to make it.

**Comment by binarylogic** [comment]
Noting, we'll need an RFC for the new approach here. Some high-level requirements that we should address:

- [ ] The ability to limit by bytes and quantity if the encoding supports it.
- [ ] When limiting by either quantity or bytes, never exceed the specified limit.
- [ ] Surface these constraints as configuration errors to users if a batch is configured improperly. For example, `msgpack` cannot be limited by bytes since it cannot be stream-encoded. Therefore, an error should be raised if the user attempts to set `encoding.codec` to `msgpack` and `batch.max_size`. It's possible this is out of scope for the new implementation.
- [ ] Prioritize the changes necessary to resolve the `aws_cloudwatch_logs` sink.

**Comment by lukesteensen** [comment]
One option would be to write a custom `Batch` implementation for Cloudwatch that's aware of its encoding, ordering, etc, requirements. We could probably do that with a minimally invasive change to `BatchSink` (e.g. call an optional `Batch::is_full` method or something like that).

Once that's in place and working, we could generalize it and incrementally migrate other sinks to use it.

**Comment by bruceg** [comment]
@lukesteensen That's an attractive idea, and I'll have to think about it more, but two things jump out at me immediately:

1. The CloudWatch Logs sink uses `PartitionBuffer` over a `Vec`, which is pretty much the worse case for complexity. Even at the minimum level of incremental it won't be a small patch.

2. I still don't think this address the fundamental problem, which is that `Batch::is_full` is true when the *next* record to be added would overflow a limit. I could make it true when the batch size is larger than the maximum minus some anticipated size, but in my mind the only legitimate value for that anticipated size is 256kiB (the hard maximum record size), which is excessively limiting. The simplest way I see of adapting a batch buffer to that idea is to introduce an overflow element, but that's pretty ugly and not something we should standardize on.
