### ISSUE TITLE
Setup dependabot

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#2781]
Should help prevent manual updates like in https://github.com/timberio/vector/pull/2779.

**Comment by Hoverbear** [comment]
![image](https://user-images.githubusercontent.com/130903/84431126-a30fcd80-abdf-11ea-8466-37092e634c1a.png)
![image](https://user-images.githubusercontent.com/130903/84431138-a73beb00-abdf-11ea-9295-796c52355248.png)
