### ISSUE TITLE
Migrate release workflow to Github Actions

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#2797]
The final step in getting off of CircleCI is to migrate the release process to a Github Action workflow. The bulk of this is already handled in the `nightly` GH workflow. The release workflow will need the following additional steps:

- [x] [`release-github`](https://github.com/timberio/vector/blob/71f0d07ae0a39940c3c7c0ef90dc55c157343485/.circleci/config.yml#L619)
- [x] [`release-homebrew`](https://github.com/timberio/vector/blob/71f0d07ae0a39940c3c7c0ef90dc55c157343485/.circleci/config.yml#L632)

Both of this are backed by `make` targets, so migrating should be straight-forward. I would like to use this as an opportunity to cleanup the steps to work with our new dev environment.

**Comment by Hoverbear** [comment]
Done and testing with #2961
