### ISSUE TITLE
AWS IAM Instance Profile/Role auth for ElasticSearch breaks after 6 hours

### ISSUE THREAD

**Issue by tyrken** [timberio/vector#2815]
I was trying to use your in-built AWS authentication for the `elasticsearch` sink, i.e. `auth.strategy = "aws".

Unfortunately it breaks after 12 hours and with some extra debug info hacked in (small PR coming after some tidy up) I realised you are incorrectly caching the AWS authentication credentials for the assigned IAM Instance Profile the EC2 instance is running with.  Unlike IAM User credentials which are static, the creds from the EC2 metadata are temporary and expire every 6 hours or so.

Looking at the v0.9.2 code I'm using, you seem to be fetching credentials once and then keeping them as an Auth header to attach to all future HTTP requests which would match the observed issue.  Instead I suspect you should use `rusoto_credential::AutoRefreshingProvider`.

Note that all AWS authentication based on IAM Instance Profiles/Roles suffers from this problem, so it might be a wider problem than just elasticsearch.  I notice there are recent interesting changes in https://github.com/timberio/vector/pull/2735 which change some code related to this area, but I don't think are enough themselves (note I'm an absolute-beginner with Rust).

For now will try to work-around via https://github.com/abutaha/aws-es-proxy

**Comment by fanatid** [comment]
@tyrken should be fixed in new release, thank you that reported about bug!

**Comment by tyrken** [comment]
Thanks! Looking forward to the first 0.10 I can play with...
