### ISSUE TITLE
Make nightly CI jobs run for PRs in dry mode

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#2854]
If a PR breaks our nightly jobs we can't currently effectively spot that in time.
We should rework the nightly scripts in such a way that they can run almost to completion in a dry-run mode, and then enable them to run like that for PRs - so that we have a higher chance of noticing a problem before merging to `master`.
This should also help with uncovering nightly build stability issues if we have them currently - cause nightly builds will be run more frequently.

**Comment by binarylogic** [comment]
@Hoverbear before beginning work on this, I want to make sure it doesn't overlap with other "dry run" plans you had for releasing in general. This doesn't have to be limited to just nighly builds.

**Comment by binarylogic** [comment]
Closing in favor of #2526
