### ISSUE TITLE
Support IAM Roles for Service Accounts

### ISSUE THREAD

**Issue by lukesteensen** [timberio/vector#2881]
If you're looking to extend what sort of AWS auth you support, it might be useful to allow "IAM Roles for Service Accounts" which is an AWS EKS (Elastic Kubernetes Service) way of giving K8s daemonsets roles.   You have the necessary version of rusoto (0.44.0) but you might need to call different credential source, see https://github.com/rusoto/rusoto/issues/1497 & https://github.com/rusoto/rusoto/pull/1577.

Not necessary for my own use case (I'm running Vector as a Systemd unit on EKS hosts), but I believe K8s is a focus for the 0.10.0 release, using a daemonset by default...

_Originally posted by @tyrken in https://github.com/timberio/vector/pull/2859#issuecomment-646510586_

**Comment by binarylogic** [comment]
@MOZGIII I'm adding this to v2 for the k8s work, in addition to supporting EKS in general.

**Comment by MOZGIII** [comment]
It looks like this is fixed via #4049.
Please reopen if there are still issues with it.
