### ISSUE TITLE
Nix Based builds

### ISSUE THREAD

**Issue by Hoverbear** [timberio/vector#2900]
Our release process has some problems. We'd like to replace it with Nix.

Please refer to #2899 for implementation details.

**Comment by MOZGIII** [comment]
It was convenient for sec teams that we were building Vector off the `debian` / `alpine` images - as those are very popular, so less code to audit. But nix is even better in this sense, so we won't be losing much.

**Comment by Hoverbear** [comment]
Cancelled.
