### ISSUE TITLE
Tutorial on https://vector.dev/guides/getting-started/deploying/#start-the-vector-container failed

### ISSUE THREAD

**Issue by jbridge8133** [timberio/vector#2920]
The tutorial on:

https://vector.dev/guides/getting-started/deploying/#start-the-vector-container

Here's what went wrong:

Jun 30 18:18:23.860  INFO vector: Log level "info" is enabled.
Jun 30 18:18:23.860  INFO vector: Loading configs. path=["/etc/vector/vector.toml"]
Jun 30 18:18:23.864  INFO vector: Vector is starting. version="0.9.1" git_version="v0.9.2" released="Tue, 02 Jun 2020 21:45:49 +0000" arch="x86_64"
Jun 30 18:18:23.864 ERROR vector::topology: Configuration error: No sources defined in the config.

and here is my /etc/vector/vector.toml file:
[sources.in]
  type = "docker" # required
  include_containers = ["wizardly_hopper"] # optional

[sinks.out]
  # Encoding
  encoding.codec = "json" # required

  # General
  host = "https://http-inputs-rei.splunkcloud.com:443/services/collector" # required
  inputs = ["in"] # required
  token = "ECE*****C-6**3-4**2-A**3-A8********B7" # required
  type = "splunk_hec" # required

**Comment by jbridge8133** [comment]
This can be closed.  We figured out the problem.

**Comment by binarylogic** [comment]
Thanks for reporting @jbridge8133. If it is anything on our end we'd like to fix it. So please correct me if I'm wrong. I'll be closing this based on your comment.
