### ISSUE TITLE
Expose the ability to checksum the first line to the users

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#2926]
Now when #2904 is merged, a logical continuation would be to start the discussion on exposing this functionality to the users.

Relevant references:
- #2890
- #2904
- #2701

There are a few details that #2904 doesn't cover, but that we probably want to cover before we can move forward to expose this functionality to the users:
- support for compressed files
- skipping file headers (i.e. checksum second line instead of the first line)
- how do we teach users about the properties and use cases of this checksum mode and how it compares to the others

**Comment by binarylogic** [comment]
I do like this change for the reasons discussed, but I want to think carefully about the UX here. This is exactly the kind of decision I do not want to present to the user. Checkpointing within the file source is already confusing and this would make it even more so. I wish there was a way to combine this strategy with the current checksum strategy so it "just works" for small and large files.

**Comment by MOZGIII** [comment]
As far as I understand, the only use case when we are reading binary files is when we're processing compressed data. The only meaningful way I know that works for compressed log files if the compression algorithm permits streaming the uncompressed data as it arrives.

What if we just do the checksumming on a decompressed stream in case the fail is compressed? We can then use the line-aware snapshotting. I think the resulting solution would just work for any meaningful case - covering all the existing cases, but with less painful tradeoffs.

**Comment by binarylogic** [comment]
This is done. #5215 should have closed this.
