### ISSUE TITLE
Migrate RouterSink type to enum

### ISSUE THREAD

**Issue by lukesteensen** [timberio/vector#2934]
Blocked on #2687 

See [Architecture RFC](https://github.com/timberio/vector/blob/master/rfcs/2020-06-18-2625-architecture-revisit.md). Start with single variant wrapping existing sink type.

**Comment by fanatid** [comment]
Need update gcp and pulsar sinks when this will be available. Relevant PR's: https://github.com/timberio/vector/pull/2993 https://github.com/timberio/vector/pull/2977
