### ISSUE TITLE
Migrate StreamingSink to new sink variant instead of using compat

### ISSUE THREAD

**Issue by lukesteensen** [timberio/vector#2937]
Blocked on #2934 

See [Architecture RFC](https://github.com/timberio/vector/blob/master/rfcs/2020-06-18-2625-architecture-revisit.md).

**Comment by fanatid** [comment]
This is not fully done, need rid `StreamSinkOld`.

**Comment by fanatid** [comment]
Planning return to https://github.com/timberio/vector/pull/3893 on this week.

**Comment by fanatid** [comment]
Resolved by https://github.com/timberio/vector/pull/4597
