### ISSUE TITLE
Change compression option by default to `none`

### ISSUE THREAD

**Issue by fanatid** [timberio/vector#2954]
Compression in sinks should be disabled by default.

Currently `gzip` by default in 2 sinks:

- [ ] clickhouse
- [ ] aws s3

See https://github.com/timberio/vector/pull/2953#issuecomment-653902858

**Comment by fanatid** [comment]
Noticed new label `need: approval` when already made changes locally =(

**Comment by binarylogic** [comment]
Yeah, I'm curious what @bruceg and @lukesteensen think about this change before we proceed.

**Comment by binarylogic** [comment]
Closing. See https://github.com/timberio/vector/pull/2962#issuecomment-654935714 for context.
