### ISSUE TITLE
`BatchSink` does not properly drive the inner IO resources

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#299]
This issue stems from #272 and #287.

For some background, this issue was found in testing of a file to splunk topology. Requests using `gzip` kept timing out as they ended up taking 13 seconds each. Initially, this was thought to be a bug with hyper. But as it turns out the issue lies with the fact that our `BatchSink` and how it operates as a sink. 

To get an idea of how our sink pipeline works it looks something like this:

`Forward -> BatchSink -> BatchServiceSink -> Service -> Future`

`Forward` in this case is the outer most future that we pass to the tokio executor to be spawned. This is the future that drives the entire chain of a sink.

Internally within [`Forward`](https://github.com/rust-lang-nursery/futures-rs/blob/0.1/src/stream/forward.rs) it looks like this:

```rust
loop {
  try_ready!(self.inner.start_send(self.item.next()));
}
```

This relies on the assumption that once `start_send` returns `AsyncSink::NotReady(T)` it will flush the _entire_ sink via `poll_complete()?` until `poll_complete()` has returned `Async::Ready(())`, if `poll_complete()` returns `NotReady` it expects to be woken up when it is ready and can continue to `start_send`. In the sense of IO `poll_complete` should return `Ready` once all the IO is done, so it can properly drive the inner `IO`. 

In our case with batching, once we start the flushing, we still continue to `start_send` and return `AsyncSink::Ready`. Since, we have a never ending stream of records, the next time we yield back to the executor is on the finishing of the _next_ batch. In the case of `gzip` where it takes 13 seconds to fill a 2mb batch, the request that has been started will timeout because the IO never gets driven till the next batch.

One area of trouble in our current implementation is that we never hit this block https://github.com/timberio/vector/blob/master/src/sinks/util/batch.rs#L133. 

What does this mean? Well, we are not properly using sinks correctly is the base of this. What we really want is to decouple _batching_ from driving the underlying sink's IO.

The best solution that I can think of is to actually decouple the poll_completeling from the finishing of the batch. What this might entail is to setup another spawned task that would only take finished batches and submit them to the underlying sink, and _drive_ the IO. The outter sink that would use a channel to submit batches to this spawned task could then continue to collect records and fill the batch.

cc @lukesteensen @michaelfairley

**Comment by binarylogic** [comment]
@LucioFranco is this still relevant? Can we close if not?

**Comment by LucioFranco** [comment]
@binarylogic still relevent but not high priority fix.
