### ISSUE TITLE
Refactor Topology to be representable via a Future

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#300]
This change is to switch `vector`'s entire application to be one big future. This brings multiple benefits. One is that we no longer need to do any `tokio_trace::with_default()` within `main.rs`. Two, this will provide a full futures aware context allowing us to freely call `tokio::spawn` anywhere within the application. This will allow the prometheus sink to spawn its server, cloudwatch (maybe) to use a buffer, and would enable the solution proposed in #299 .

cc @michaelfairley @lukesteensen

**Comment by binarylogic** [comment]
Same here. Is this still relevant?

**Comment by LucioFranco** [comment]
We can close this, we've decided to go anther path but will likely revist all of this with new topology changes.
