### ISSUE TITLE
Add Helm chart(s) to deploy full observability stacks with Vector into Kubernetes

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#3008]
We can offer Helm chart (or charts) to deploy the full observability stack into k8s:

`vector` +

- `loki` + `grafana`
- `elasticsearch` + `grafana`
- `elasticsearch` + `kibana`

This would effectively be a turnkey self-hosted solution to use Vector at K8s.

### Motivation

Allow one-command installation of the observability stack.

### Technical details

Helm allows installing dependencies. We can create a `vector-stack` chart in addition to `vector` chart. This `vector-stack` will depend on `vector` chart and charts for `loki`, `grafana`, `elasticsearch` and etc.

All that this `vector-stack` has to do is to point parts of the stack to each other.
This is fairly trivial thing, should be easy to implement and maintain.

**Comment by afoninsky** [comment]
From my experience (and it's only my opinion), vector is a great component for building complex system. I'm not saying that it will be bad in predefined stacks "vector" + "<any-popular-stuff>", but having flexible helm chart is something I'd want to see. It can be used as a part of umbrella chart, core component for custom solution or even in discussed stacks.

For example, I maintain own private chart and combine it with tools I need for current task. Features I'm using in it:
- ability to inject sidecars together with Vector (to create "servicemesh" where vector acts as a transport)
- init containers support
- flexible config with the ability to use helm chart variables itself (example - to specify port in k8s service and reuse it in config)
- mounting of custom volumes (pvc, configmaps, etc...)
- tunable readiness/liveness for specific needs
- ingress
etc.

Yes, it's a tricky thing to build a universal chart. But I've seen some good examples in https://github.com/helm/charts and it's doable.

**Comment by MOZGIII** [comment]
Thanks for the input, @afoninsky! This is definitely a good idea. We’re currently reworking the k8s integration, and currently we’re focusing on a cluster-wide `DaemonSet` deployment model. We have a Helm chart for just Vector in progress - https://github.com/timberio/vector/pull/2871.
We will be improving it and adding more flexibility and configuration (Vector as deployment+service, Vector as sidecar) as we go.
I’m looking forward to know what you think about it!

**Comment by afoninsky** [comment]
Thank you for the information.

From my point of view, helm is not very suitable for reusing different deployment types (as it works with text templates without knowing context), so it looks more profitable to concentrate on DaemonSet first. Personally I see vector as a custom component in own solution so have no big ideas about separate chart (I think about it more like "envoy for istio" :).

About the rest, please deploy the resulting chart and we (community) will be happy to send pull-requests.

Great job though :)

**Comment by MOZGIII** [comment]
> vector as a custom component in own solution

@afoninsky you might then be interested in https://github.com/timberio/vector/issues/3018

> helm is not very suitable for reusing different deployment types

I agree. It's not yet clear if we'll be reusing the same chart, or split into multiple chars (i.e. `vector` for `DaemonSet` in agent deployment model + `vector-service` for `Deployment` & `Service` in a service deployment model).

**Comment by MOZGIII** [comment]
@afoninsky you might be interested in taking a look at our design for the next generation of our Helm Charts at #3227.

**Comment by spencergilbert** [comment]
Issue moved to [timberio/helm-charts #15](https://github.com/timberio/helm-charts/issues/15) via [**ZenHub**](https://www.zenhub.com/)
