### ISSUE TITLE
Allow `CloudwatchLogs` sink to impl `Clone`

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#301]
We need to find the best strategy around allowing the cloudwatch_logs sink to be cloneable so we can provide retries. There are two possible solutions here:

1) Back the service by a buffer that will enable later services to clone it as proposed in #274.

2) Move all stateful struct items to be inside an `Arc<Mutex<_>>`.

**Comment by binarylogic** [comment]
Same here. Is this still relevant?

**Comment by LucioFranco** [comment]
This has been solved.
