### ISSUE TITLE
Replace `merge` transform with upcoming `transaction` tranfsorm

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3012]
After some discussion, it appears that [the new `transactions` transform](https://github.com/timberio/vector/pull/2870) is a superset of the existing `merge` transform. Given that the `merge` transform is very limited, and line merging is being pushed up into the sources, I'd like to replace the `merge` transform with https://github.com/timberio/vector/pull/2870. I would be very surprised if any users are currently using the `merge` transform, but I don't know for sure.

cc @MOZGIII

**Comment by MOZGIII** [comment]
I checked the PR and didn’t find an example with the same behaviour as `merge` transform. I’m looking forward to replace `merge` transform with something more advanced, but if we want to replace it - we have to make sure the behavior tests with the same conditions pass (to ensure the same use case is still supported).

**Comment by binarylogic** [comment]
Closing this since we've decided to use the `reduce` name.
