### ISSUE TITLE
Generate command should have option to output to file

### ISSUE THREAD

**Issue by Hoverbear** [timberio/vector#3013]
Based on #3007 it seems there may be a use case for `vector generate --file foo.test` so a user can output a configuration to a particular file with verbose logging on, or in a situation where they don't have pipes available.

**Comment by binarylogic** [comment]
@Hoverbear we intend for this command to _not_ include log output, and I'm curious when pipes wouldn't be available? Looking to close this if possible.

**Comment by Hoverbear** [comment]
So you can consider that in some environments a full `bash` or `powershell` binary might not be available. This is rare of course, I think it would only be applicable in otherwise clean environments just running a kernel and vector.

I'd consider this a low priority but a great contribution for a community member.
