### ISSUE TITLE
New semantic tags

### ISSUE THREAD

**Issue by Hoverbear** [timberio/vector#3020]
As I prepared for #2961 I found myself wanting the following tags:

* feat(rfc)
* feat(kubernetes platform)
* enhancement(kafka platform)
* chore(ci)

**Comment by binarylogic** [comment]
@Hoverbear `kubernetes`, `ci`, and `rfc` have been added. Is Kafka a platform? I view it more as an integration.

**Comment by Hoverbear** [comment]
Ok! Agree!
