### ISSUE TITLE
Flaky `topology::reload_tests::topology_reuse_old_port`

### ISSUE THREAD

**Issue by ktff** [timberio/vector#3035]
Ref. #2978 

Main purpose is to test that when we reload with new config the resources, like port, of the old topology are released and are available to be used for the new topology. It tests this by reusing the same port.

Flaky on Windows.
https://github.com/timberio/vector/pull/3010/checks?check_run_id=857742471

Probably a race between us and the kernal.

**Comment by binarylogic** [comment]
@ktff if this passes reliably for linux and mac, could we enable for those platforms only? There is value in that.

**Comment by ktff** [comment]
Yes and true. I'm on it.

**Comment by ktff** [comment]
One more point of proof that Windows is still holding onto port after we close the connection. 
https://github.com/timberio/vector/pull/4030/checks?check_run_id=1141134663
The reconnect test creates a listener, drops it, and then immediately construct another one, which on windows errors with `"Only one usage of each socket address (protocol/network address/port) is normally permitted."`, but passes on Linux and Mac.
