### ISSUE TITLE
Subcommand to output config as DOT file

### ISSUE THREAD

**Issue by lukesteensen** [timberio/vector#3068]
As suggested [here](https://github.com/timberio/vector/issues/1699#issuecomment-657337795), we should support outputting your config/topology as a DOT file for visualization with graphviz. This should likely exist as a new subcommand.

**Comment by Hoverbear** [comment]
Prior art: https://www.terraform.io/docs/commands/graph.html

**Comment by guusvw** [comment]
+1 in general
@thalin when you're saying "by hand" are you really building the graph by hand? or have you any scripts which are generating the graph?
