### ISSUE TITLE
chore: Re-enable SASL in Kafka

### ISSUE THREAD

**Issue by Hoverbear** [timberio/vector#3080]
Undo #2930 .

We'd like to release this stable. This can be in 0.11.0 or #2961 (0.10.0).

If left for 0.11.0, this will be a tracking issue for a highlight.

**Comment by MOZGIII** [comment]
Afaik, there's a fix for this in rdkafka git, but there was some kind of troubles with using it. @fanatid knows more.

**Comment by Hoverbear** [comment]
Yeah! Some things have changed in our build process so I'm wondering if I can coax it into working.

**Comment by Hoverbear** [comment]
*Think* I got it.

**Comment by Hoverbear** [comment]
Score!
