### ISSUE TITLE
Consider using multipart uploads for the `aws_s3` sink

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3087]
Using [S3's multipart upload feature](https://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html) for the `aws_s3` sink would potentially allow Vector to reduce the time and size of data it holds while building the payload. This would be nice for files that are intended to be very large.

**Comment by jamtur01** [comment]
Closing in favor of #3829.
