### ISSUE TITLE
0.9.2 docker images missing 

### ISSUE THREAD

**Issue by perfectayush** [timberio/vector#3088]
Release images for `timberio/vector:0.9.2-alpine` are missing. 
Is it ok to have an expectation that every vector version image will be available via docker with convention `timberio/vector:<version>-alpine`?
I use these images for integration tests of vector configurations.

**Comment by Hoverbear** [comment]
I think when @lukesteensen cut this release he reported some issues... I'll investigate this.

**Comment by perfectayush** [comment]
I have switched to version `0.10.0` this is not an issue for me anymore.

**Comment by binarylogic** [comment]
Great! Thank you for reporting. I will close this.
