### ISSUE TITLE
RegexSets: incorrect capture group

### ISSUE THREAD

**Issue by splitice** [timberio/vector#3096]
Found a `regex_parser` bug with latest nightly.

```
  patterns = [
    '^blah \((?P<socket_code>[0-9]+): (?:[^\)]+)\) while (?P<timeout_while>.)',
    "^notblah (?P<close_while>.+)$",
  ]
```

If the first pattern matches `close_while` will be set to the value of `socket_code`.

**Comment by binarylogic** [comment]
Thanks for reporting @splitice , we’ll get on it this week.
