### ISSUE TITLE
Add max_length to UDP socket source

### ISSUE THREAD

**Issue by fanatid** [timberio/vector#3117]
UDP socket source should support `max_length` as docs say. Should be done after https://github.com/timberio/vector/pull/3095
Initially was done by @ktff in https://github.com/timberio/vector/pull/3100/. I think `max_length` and `host_key` can be moved to `SocketConfig`.

**Comment by fanatid** [comment]
@lukesteensen how you think, should we move `max_length` / `host_key` to `SocketConfig` https://github.com/timberio/vector/blob/be6839e3c7b9668b6472eb41097961f44eef6444/src/sources/socket/mod.rs#L20-L23, or left these field duplicated in `TcpConfig`, `UdpConfig`, `UnixConfig`?

**Comment by lukesteensen** [comment]
We can just duplicate for now. If that becomes annoying later then we can do the work to restructure.
