### ISSUE TITLE
Teach the Environment to package rpms

### ISSUE THREAD

**Issue by Hoverbear** [timberio/vector#3122]
Right now we use `cargo deb` and a packager docker image (https://github.com/timberio/vector/tree/master/scripts/ci-docker-images/packager-rpm)

This ticket requests that the environment be made capable of building the RPMs without a docker image.

(**Caveat:** This is easiest done when we teach our environment to be centos 7 as well.)

**Comment by jamtur01** [comment]
Everything is now packaged in the ci_image.
