### ISSUE TITLE
Teach Environment to be Centos when it wants

### ISSUE THREAD

**Issue by Hoverbear** [timberio/vector#3124]
Related to #3121 and #3122, this ticket teaches the environment to be centos when we want it to be by adding an `ARG` to the dockerfile called `BASE`, adding a `Makefile` environment called `ENVIRONMENT_BASE` which can be `ubuntu:20.04` (default) or `centos:7`.

**Comment by binarylogic** [comment]
@Hoverbear should we close this given the new recent CI/releasing changes with cross?

**Comment by Hoverbear** [comment]
Yes.
