### ISSUE TITLE
Flow the environment into the test suite

### ISSUE THREAD

**Issue by Hoverbear** [timberio/vector#3125]
To let us better leverage caching, build the environment **if it needs to be updated** before running any test suite jobs.

This requires merging the environment and test suite jobs.

Try to use the Github actions "Runs on container" feature if you can! Otherwise you may need to use an artifact.

This should result in a speedup of CI and should be aborted if not.

**Comment by binarylogic** [comment]
@Hoverbear @jamtur01 is this still relevant? If so, can it be deferred?

**Comment by Hoverbear** [comment]
Nah! We can use cross now
