### ISSUE TITLE
Add clippy rule: clone_on_ref_ptr

### ISSUE THREAD

**Issue by fanatid** [timberio/vector#3133]
[clone_on_ref_ptr](https://rust-lang.github.io/rust-clippy/master/#clone_on_ref_ptr) rule force use

```rust
Rc::clone(&x);
```

instead

```rust
x.clone();
```

for `Rc`, `Arc`, `rc::Weak`, `sync::Weak`.

I think it's a good rule for understanding what is variable type without keeping it in mind.

**Comment by lukesteensen** [comment]
Agreed! I think this would be helpful.
