### ISSUE TITLE
Prometheus source minor tech debt

### ISSUE THREAD

**Issue by bruceg** [timberio/vector#3160]
While reviewing #3090, I saw a few pieces of poor coding in the parser:

1. `enum ParserError` doesn't actually enumerate all the error cases. Instead, it uses a string embedded in the code to describe how something was malformed. Since there are a fixed set of ways something can be malformed, they should be enumerated explicitly in the error type.
2. Quoted values have leading and trailing spaces trimmed. Quoted values shouldn't be trimmed at all.
3. Values with a single leading or trailing double quote will have that stripped.

Seeing these, I'm sure there are other gotchas to be cleaned up. This could use a fuller review for additional issues.

**Comment by juchiast** [comment]
- Cannot parse tag values containing "," (for example "a,b").
