### ISSUE TITLE
[question]How to use Java write to vector [STDIN] source?

### ISSUE THREAD

**Issue by lorna1** [timberio/vector#3170]
How to use Java write to vector [STDIN] source?

**Comment by binarylogic** [comment]
Hi @lorna1, sorry for the delay. It really depends on how your application is started. Typically applications will write to STDOUT or to a file, which should allow you to hook up to the `stdin` or `file` sources for Vector. This is a pretty broad question, so I'm going to close. If you have any more specific please feel free to share.
