### ISSUE TITLE
Support configuration in JSON

### ISSUE THREAD

**Issue by sam701** [timberio/vector#3174]
Vector configuration file(s) can get very large and so difficult to look through and maintain. I would like to generate the vector configuration, e.g. by using some configuration languages like [dhall](https://dhall-lang.org/) or [jsonnet](https://jsonnet.org/). Most of the configuration languages can generate JSON but not (yet) TOML. It would be helpful if the `--config` flag supports files in JSON format, as well.

**Comment by binarylogic** [comment]
Thanks @sam701. We agree. We are considering other formats and will update as we obtain consensus.

Ref https://github.com/timberio/vector/issues/1327.

**Comment by avalenn** [comment]
@sam701  Some have already tried the jsonnet way with current TOML format https://github.com/xunleii/vector_jsonnet

**Comment by binarylogic** [comment]
@jamtur01 I'd like to prioritize this since it'll allow the use of many different configuration tools like jsonnet, cue, etc. From what I understand this should be pretty easy. Agree?

**Comment by jamtur01** [comment]
I think it should be easy but I'd like @lukesteensen to weigh in.

**Comment by lukesteensen** [comment]
> I presume we plan to keep TOML too?

That was my thought. We can keep the existing human-facing interface, docs examples, etc in TOML and simply add another flag that accepts config via JSON and position it to be used with config generation tools.
