### ISSUE TITLE
Define events for the `file` source

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3197]
As part of finishing https://github.com/timberio/vector-product/issues/14, we need to define internal events for the `file` source. This source was instrumented as part of our initial efforts, but I have a feeling we missed a few. So I'd like to add any missing events.

## Defining events

* If you have not already, please read [RFC 2064](https://github.com/timberio/vector/blob/master/rfcs/2020-03-17-2064-event-driven-observability.md).
  * ***Be sure to read the [Guide-level Proposal section](https://github.com/timberio/vector/blob/master/rfcs/2020-03-17-2064-event-driven-observability.md#guide-level-proposal) and the implementation details that affect performance.***
* You can also look at the [currently defined events](https://github.com/timberio/vector/tree/master/src/internal_events) for precedence.
* Events should be named properly: `<ComponentName><Noun><Verb>`. For example, the `syslog` source defines the [`SyslogEventReceived` struct](https://github.com/timberio/vector/blob/fb71f5ad76266d9a44164e6804723376353e4ff0/src/internal_events/syslog.rs#L9).

## Requirements

- [x] Audit and add events for all possible errors. ([example](https://github.com/timberio/vector/blob/fb71f5ad76266d9a44164e6804723376353e4ff0/src/internal_events/syslog.rs#L31))
- [ ] Audit and add events for all component-specific behavior. ([example](https://github.com/timberio/vector/blob/fb71f5ad76266d9a44164e6804723376353e4ff0/src/internal_events/tcp.rs#L9))
- [x] Ensure that logs in the hot path are rate limited via the `rate_limit_secs` parameter. ([example](https://github.com/timberio/vector/blob/fb71f5ad76266d9a44164e6804723376353e4ff0/src/internal_events/tcp.rs#L83)).
- [x] Ensure that all log messages start with a lowercase letter and end with a `.`. ([example](https://github.com/timberio/vector/blob/master/src/internal_events/tcp.rs#L83))

**Comment by ktff** [comment]
To cover `file` source with events, we need to add events to it's lib crate `file-source`. But for that we need to import `InternalEvent` and `emit!` which are in the main crate. As they are now, they can be extracted to their own lib crate and then imported into `file-source` and main crate. With that we can expand internal events for `file` source beyond just `FileEventReceived`.

 cc. @binarylogic @lukesteensen

**Comment by binarylogic** [comment]
Is there any way to adjust the code to accept events? Or provide an API that would allow us to trigger our own events? We have plans in the future to split off the underlying file source code, so I want to be careful with couplign.

**Comment by lukesteensen** [comment]
I think for the time being we can limit the instrumentation to the file source itself (i.e. around the API of the `file-source` crate). If we find that important things are missing, we can go back and add a configurable notification API.

**Comment by ktff** [comment]
> If we find that important things are missing

Without `file-source` crate, we only have `FileEventReceived`. Some of the events that could be added would be:
* `FileWatch`
* `FileDeleted`
* `FileCheckpointFailed`

> Is there any way to adjust the code to accept events?

Yes, but we would lose ordering with other logs, and it would be possible to lose them completely in case of a panic.

> Or provide an API that would allow us to trigger our own events?

It's doable. We could pass a function from main crate to the `file-source` crate that would accept `Any`, do checked type casting, and emitting, while struct would be defined in `file-source` crate, `InternalEvent` would be implemented in main crate. It wouldn't be as efficient, but considering frequency of the events, it won't be noticeable. 

This function API is a good compromise, and considering the event's that we would miss on, I'm for adding it now.

**Comment by binarylogic** [comment]
> This function API is a good compromise, and considering the event's that we would miss on, I'm for adding it now.

I am too. There are a couple of others that might be worthwhile:

* `FileCheckpointed`
* `FileChecksumFailed` (file is too small)
* `FileAdded` (instead of `FileWatch`?)
* `FileResumed` (instead of `FileAdded` when a checkpoint is resumed)

I'm curious if there is a precedence set for this type of API in the Rust eco-system?

**Comment by lukesteensen** [comment]
I think we should define an `EventReporter` trait in the file source crate with methods for each of these events we care about, then we can implement that trait in the main crate and pass our implementation down into the file source. That's the cleanest way I can think of to gather all these events in the way we want without perf issues or too much code reorganization.

**Comment by ktff** [comment]
> I'm curious if there is a precedence set for this type of API in the Rust eco-system?

I doubt that there isn't, but it certainly is not a good practice.

> define an EventReporter trait in the file source crate with methods for each of these events

It's a bit verbose, but it's definetely clearer and better. Let's go with this.
