### ISSUE TITLE
Define events for the `generator` source

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3198]
As part of finishing https://github.com/timberio/vector-product/issues/14, we need to define internal events for the `generator` source.

## Defining events

* If you have not already, please read [RFC 2064](https://github.com/timberio/vector/blob/master/rfcs/2020-03-17-2064-event-driven-observability.md).
  * ***Be sure to read the [Guide-level Proposal section](https://github.com/timberio/vector/blob/master/rfcs/2020-03-17-2064-event-driven-observability.md#guide-level-proposal) and the implementation details that affect performance.***
* You can also look at the [currently defined events](https://github.com/timberio/vector/tree/master/src/internal_events) for precedence.
* Events should be named properly: `<ComponentName><Noun><Verb>`. For example, the `syslog` source defines the [`SyslogEventReceived` struct](https://github.com/timberio/vector/blob/fb71f5ad76266d9a44164e6804723376353e4ff0/src/internal_events/syslog.rs#L9).

## Requirements

- [ ] Audit and add events for all possible errors. ([example](https://github.com/timberio/vector/blob/fb71f5ad76266d9a44164e6804723376353e4ff0/src/internal_events/syslog.rs#L31))
- [ ] Audit and add events for all component-specific behavior. ([example](https://github.com/timberio/vector/blob/fb71f5ad76266d9a44164e6804723376353e4ff0/src/internal_events/tcp.rs#L9))
- [ ] Ensure that logs in the hot path are rate limited via the `rate_limit_secs` parameter. ([example](https://github.com/timberio/vector/blob/fb71f5ad76266d9a44164e6804723376353e4ff0/src/internal_events/tcp.rs#L83)).
- [ ] Ensure that all log messages start with a lowercase letter and end with a `.`. ([example](https://github.com/timberio/vector/blob/master/src/internal_events/tcp.rs#L83))

**Comment by binarylogic** [comment]
@lukesteensen @bruceg, is this even worth doing? I opened it for completeness.

**Comment by bruceg** [comment]
The only thing to really report on is that events were generated or purely internal errors. Doesn't seem worth much, but I don't know.

**Comment by binarylogic** [comment]
Yep, closing for now.
