### ISSUE TITLE
Define events for the `journald` source

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3200]
As part of finishing https://github.com/timberio/vector-product/issues/14, we need to define internal events for the `journald` source.

## Defining events

* If you have not already, please read [RFC 2064](https://github.com/timberio/vector/blob/master/rfcs/2020-03-17-2064-event-driven-observability.md).
  * ***Be sure to read the [Guide-level Proposal section](https://github.com/timberio/vector/blob/master/rfcs/2020-03-17-2064-event-driven-observability.md#guide-level-proposal) and the implementation details that affect performance.***
* You can also look at the [currently defined events](https://github.com/timberio/vector/tree/master/src/internal_events) for precedence.
* Events should be named properly: `<ComponentName><Noun><Verb>`. For example, the `syslog` source defines the [`SyslogEventReceived` struct](https://github.com/timberio/vector/blob/fb71f5ad76266d9a44164e6804723376353e4ff0/src/internal_events/syslog.rs#L9).

## Requirements

- [x] Add a `JournaldEventReceived` event.
  - [x] Derive a `events_processed` metric via the `emit_metrics` method. ([example](https://github.com/timberio/vector/blob/master/src/internal_events/syslog.rs#L15))
  - [x] If possible, derive a `bytes_processed` metric via the `emit_metrics` method. ([example](https://github.com/timberio/vector/blob/fb71f5ad76266d9a44164e6804723376353e4ff0/src/internal_events/syslog.rs#L19))
- [x] Audit and add events for all possible errors. ([example](https://github.com/timberio/vector/blob/fb71f5ad76266d9a44164e6804723376353e4ff0/src/internal_events/syslog.rs#L31))
- [ ] Audit and add events for all component-specific behavior. ([example](https://github.com/timberio/vector/blob/fb71f5ad76266d9a44164e6804723376353e4ff0/src/internal_events/tcp.rs#L9))
- [ ] Ensure that logs in the hot path are rate limited via the `rate_limit_secs` parameter. ([example](https://github.com/timberio/vector/blob/fb71f5ad76266d9a44164e6804723376353e4ff0/src/internal_events/tcp.rs#L83)).
- [x] Ensure that all log messages start with a lowercase letter and end with a `.`. ([example](https://github.com/timberio/vector/blob/master/src/internal_events/tcp.rs#L83))

**Comment by bruceg** [comment]
The `journald` source internally filters events. Do we want to emit the `JournaldEventReceived` for all data received from journald/journalctl, or only for non-filtered events, or should there be one event for each case?

**Comment by binarylogic** [comment]
Post-filtering. The intent is to reflect the creation of a _Vector_ event.

**Comment by binarylogic** [comment]
@bruceg I'm reopening this. There are a few places where errors are happening but events are not being emitted:

1. https://github.com/timberio/vector/blob/e27d4ffc1e87aea67a54ce94024e744cc353f338/src/sources/journald.rs#L117
2. https://github.com/timberio/vector/blob/e27d4ffc1e87aea67a54ce94024e744cc353f338/src/sources/journald.rs#L161
3. https://github.com/timberio/vector/blob/e27d4ffc1e87aea67a54ce94024e744cc353f338/src/sources/journald.rs#L191

While we're at it. We should be improve these messages to include the file or directory path. That will help users debug errors like:

```
Configuration error: Source "in": Unable to open checkpoint file: Permission denied (os error 13)
```

A better message would be something like:

```
Configuration error: Source "in": Unable to open checkpoint file /var/lib/vector/in: Permission denied (os error 13)
```

This was discovered in #3558.

**Comment by bruceg** [comment]
Those three errors are configuration errors. That is, under normal usage they will not happen, and cannot be caused by contents of the data in the journal nor any other run time factor short of an administrator changing permissions or killing processes. I will gladly add events for those, but there are probably many other such configuration errors that do not result in internal events.

I do agree 100% on the error messages including the file or directory names. That would definitely add value.

**Comment by binarylogic** [comment]
Thanks.

> Those three errors are configuration errors.

Ah, my fault. No need to add events for those.

> I do agree 100% on the error messages including the file or directory names. That would definitely add value.

I'll open separate issues for that.
