### ISSUE TITLE
Define events for the `socket` source

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3204]
As part of finishing https://github.com/timberio/vector-product/issues/14, we need to define internal events for the `socket` source.

## Prior Work

This source was previously instrumented as part of our initial work. But I want to double-check that it is comprehensive.

## Defining events

* If you have not already, please read [RFC 2064](https://github.com/timberio/vector/blob/master/rfcs/2020-03-17-2064-event-driven-observability.md).
  * ***Be sure to read the [Guide-level Proposal section](https://github.com/timberio/vector/blob/master/rfcs/2020-03-17-2064-event-driven-observability.md#guide-level-proposal) and the implementation details that affect performance.***
* You can also look at the [currently defined events](https://github.com/timberio/vector/tree/master/src/internal_events) for precedence.
* Events should be named properly: `<ComponentName><Noun><Verb>`. For example, the `syslog` source defines the [`SyslogEventReceived` struct](https://github.com/timberio/vector/blob/fb71f5ad76266d9a44164e6804723376353e4ff0/src/internal_events/syslog.rs#L9).

## Requirements

- [x] Add a `SocketEventReceived` event.
  - [x] Derive a `events_processed` metric via the `emit_metrics` method. ([example](https://github.com/timberio/vector/blob/master/src/internal_events/syslog.rs#L15))
  - [x] If possible, derive a `bytes_processed` metric via the `emit_metrics` method. ([example](https://github.com/timberio/vector/blob/fb71f5ad76266d9a44164e6804723376353e4ff0/src/internal_events/syslog.rs#L19))
- [ ] Audit and add events for all possible errors. ([example](https://github.com/timberio/vector/blob/fb71f5ad76266d9a44164e6804723376353e4ff0/src/internal_events/syslog.rs#L31))
- [ ] Audit and add events for all component-specific behavior. ([example](https://github.com/timberio/vector/blob/fb71f5ad76266d9a44164e6804723376353e4ff0/src/internal_events/tcp.rs#L9))
- [ ] Ensure that logs in the hot path are rate limited via the `rate_limit_secs` parameter. ([example](https://github.com/timberio/vector/blob/fb71f5ad76266d9a44164e6804723376353e4ff0/src/internal_events/tcp.rs#L83)).
- [ ] Ensure that all log messages start with a capital letter and end with a `.`. ([example](https://github.com/timberio/vector/blob/master/src/internal_events/tcp.rs#L83))

**Comment by bruceg** [comment]
A couple of questions here.

1. The socket source defines separate events for the mode of the source, ie `TcpEventReceived` and `UdpEventReceived`. Should these be unified into one `SocketEventReceived` as suggested or left separate?

2. If we keep separate events, in the socket source, there is an event named `UnixSocketEventReceived`. This does not match the other events above, however, `UnixEventReceived` is awkwardly generic, and `UdsEventReceived` is a little obscure (UNIX domain socket). Should this be renamed or just leave it?

**Comment by binarylogic** [comment]
We should unify the events into a `SocketEventReceived` event and add a `mode` attribute that represents the socket mode (`tcp`, `udp`, `unix`).
