### ISSUE TITLE
Define events for the `vector` source

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3209]
As part of finishing https://github.com/timberio/vector-product/issues/14, we need to define internal events for the `vector` source.

## Special Note

To my knowledge, this source wraps the `socket` source. I'm curious how we should approach defining events in this case, since we do not emit duplicate events (ex: `*EventReceived` events).

## Defining events

* If you have not already, please read [RFC 2064](https://github.com/timberio/vector/blob/master/rfcs/2020-03-17-2064-event-driven-observability.md).
  * ***Be sure to read the [Guide-level Proposal section](https://github.com/timberio/vector/blob/master/rfcs/2020-03-17-2064-event-driven-observability.md#guide-level-proposal) and the implementation details that affect performance.***
* You can also look at the [currently defined events](https://github.com/timberio/vector/tree/master/src/internal_events) for precedence.
* Events should be named properly: `<ComponentName><Noun><Verb>`. For example, the `syslog` source defines the [`SyslogEventReceived` struct](https://github.com/timberio/vector/blob/fb71f5ad76266d9a44164e6804723376353e4ff0/src/internal_events/syslog.rs#L9).

## Requirements

- [x] Add a `VectorEventReceived` event.
  - [x] Derive a `events_processed` metric via the `emit_metrics` method. ([example](https://github.com/timberio/vector/blob/master/src/internal_events/syslog.rs#L15))
  - [x] If possible, derive a `bytes_processed` metric via the `emit_metrics` method. ([example](https://github.com/timberio/vector/blob/fb71f5ad76266d9a44164e6804723376353e4ff0/src/internal_events/syslog.rs#L19))
- [x] Audit and add events for all possible errors. ([example](https://github.com/timberio/vector/blob/fb71f5ad76266d9a44164e6804723376353e4ff0/src/internal_events/syslog.rs#L31))
- [x] Audit and add events for all component-specific behavior. ([example](https://github.com/timberio/vector/blob/fb71f5ad76266d9a44164e6804723376353e4ff0/src/internal_events/tcp.rs#L9))
- [x] Ensure that logs in the hot path are rate limited via the `rate_limit_secs` parameter. ([example](https://github.com/timberio/vector/blob/fb71f5ad76266d9a44164e6804723376353e4ff0/src/internal_events/tcp.rs#L83)).
- [ ] Ensure that all log messages start with a lowercase letter and end with a `.`. ([example](https://github.com/timberio/vector/blob/master/src/internal_events/tcp.rs#L83))

**Comment by ktff** [comment]
Was done in #1953

**Comment by ktff** [comment]
> this source wraps the `socket` source. I'm curious how we should approach defining events in this case

@binarylogic it was wrapping `socket` source, now the shared code is separated. For `vector` source, that is `tcp` code which only emits a generic `TcpConnectionError` that covers all errors that get propagated to it. And `vector` source emits it's own `VectorEventReceived`.
