### ISSUE TITLE
Profile use of `RegexSet` in Regex Parser

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#3224]
Bruce noted in https://github.com/timberio/vector/pull/3164#issuecomment-663722119 that, after using a `RegexSet` to find the matching regex in a list of regexes, we then execute the regex again to pull out the capture groups.

An alternative is to maintain a `Vec` of `Regex` and execute these to find the matching one, giving us the capture groups at the same time.

Presumably, matching with the `RegexSet` and matching the matching regex again would be faster if we have a large set of regexes, but there is a hunch that it might actually be slower for small numbers of regexes.

We should do some profiling and determine if we should be using a `RegexSet` at all or under what conditions it makes sense to use it.

**Comment by binarylogic** [comment]
Closing since this is no longer relevant given the new `remap` transform and the various parsing/error handling strategies there.
