### ISSUE TITLE
Allow user to specify default/fallback timezone for fallback situations

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3235]
For issues like https://github.com/timberio/vector/issues/3234, where we can't detect the user's system time zone, we should allow the user to configure a default. There are a few ways we can do this:

1. Detect the `TZ` environment variable. The value should be one of the [valid database time zones](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

2. A global configuration option. The same values for `TZ` should be supported here:

   ```toml
   timezone = "America/New_York"
   ```

3. A source level configuration option to allow it to vary by source.

**Comment by ethinx** [comment]
Hello vector team,

Is there a way to handle timezone now? I did some search and can't find much info about change timezone of received timestamp.

The problem we meet as follow:

source from kubernetes_log, and the timestamp of stdout log is in UTC format. We want to route to sinks.file. However, we format the filename with timestamp and it's UTC time.

I think it would be better if we could be able to transform the timestamp to local time, that we could locate the log file intuitively

**Comment by ethinx** [comment]
same issue to #1365 , hope we could have methods to handle timezone.

**Comment by ethinx** [comment]
Just figure out a workaround as follow:

```
data_dir = "/logdir/vector"

# Input data. Change me to a valid input source.
[sources.vector_socket]
  type = "vector"
  address = "0.0.0.0:9000"

[transforms.pod_stdout_time_unix]
  type = "remap" # required
  inputs = ["vector_socket"] # required
  source = '''
  .unix_time = to_int(format_timestamp(.timestamp, format="%s"))

  .utc8_time = .unix_time + 28800

  .year = format_timestamp(to_timestamp(.utc8_time), "%Y")
  .month = format_timestamp(to_timestamp(.utc8_time), "%m")
  .day = format_timestamp(to_timestamp(.utc8_time), "%d")
  .hour = format_timestamp(to_timestamp(.utc8_time), "%H")
  del(.utc8_time)
  del(.unix_time)
  '''

[sinks.debug]
  inputs = ["pod_stdout_time_unix"]
  type = "console"
  target = "stdout"
  encoding.codec = "json"

[sinks.k8s_console_log]
  type = "file"
  inputs = ["pod_stdout_time_unix"]
  compression = "none"
  path = "/logdir/vector/{{kubernetes.pod_namespace}}/{{kubernetes.pod_labels.app}}/log.{{year}}-{{month}}-{{day}}-{{hour}}"
```

**Comment by lucperkins** [comment]
@ethinx Two things that might interest you:

1. VRL supports variables
2. VRL has a `to_unix_timestamp` function

You could thus rewrite your script like this:

```ruby
unix_time = to_unix_timestamp(.timestamp)
utc8_time = unix_time + 28800
.log_file_ts = format_timestamp(to_timestamp(utc8_time), "%Y-%m-%d-%H")
```

That doesn't directly address the original timestamp issue, of course 😄 Just wanted you to know.

**Comment by ethinx** [comment]
@lucperkins thx, I found `to_unix_timestamp` in commits of recent few day but it seems release yet. I follow the up to date document methods.

**Comment by bruceg** [comment]
Note that the detection of the `$TZ` environment variable is done within the Unix standard C library functions for time conversion, and should already be supported. As evidence, note that we already test using it: https://github.com/timberio/vector/blob/121f93fe2cf6b9aaeae2f2904cc33c214dd9fa26/lib/shared/src/conversion.rs#L314

**Comment by max-arnold** [comment]
Thanks for the TZ hint, it fixed my `vector test` failure because of different timezones on my local machine and CI
