### ISSUE TITLE
Support tags in the `statsd` sink

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3270]
I would like to confirm this, but we have a user reporting that the `statsd` sink does not encode tags. For example, a single Statsd metric with tags looks like this:

```
performance.os.disk:1099511627776|g|#region:us-west-1,drive:/dev/nvme0,metric:blocks,size:4096
```

Given that we [support tags](https://vector.dev/docs/about/data-model/metric/#tags) in our metrics data model, we should be encoding them in the `statsd` sink.

## Prior art

The Statsd protocol is not very spec'd, so it might help to look at prior art:

* https://github.com/atlassian/gostatsd

**Comment by KrzysztofKowalczyk** [comment]
There are some flavours of StatsD:
- Etsy - https://github.com/etsy/statsd/blob/master/docs/metric_types.md 
- Datadog - https://docs.datadoghq.com/guides/dogstatsd/#datagram-format
- Telegraf - https://www.influxdata.com/blog/getting-started-with-sending-statsd-metrics-to-telegraf-influxdb
- Sysdig - https://sysdig.com/blog/monitoring-statsd-metrics

DataDog format is quite popular as it support tags and is supported by Splunk as input format:
https://docs.splunk.com/Documentation/Splunk/8.0.5/Metrics/GetMetricsInStatsd

Micrometer.io supports mentioned formats here:
https://github.com/micrometer-metrics/micrometer/tree/master/implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/internal

**Comment by FungusHumungus** [comment]
It looks like Vector is encoding tags fine. The code that encodes the tags is found [here](https://github.com/timberio/vector/blob/master/src/sinks/statsd.rs#L140). I can send the attached metric through Vector to a `statsd` sink and it will output the following:

```
performance.os.disk:1099511627776|g|#drive:/dev/nvme0,metric:blocks,region:us-west-1,size:4096
```

The metrics are reordered, but they are there.

Sending it to a statsd instance shows: 

```
gauges: {
    'statsd.timestamp_lag': 0,
    'performance.os.disk;drive=-dev-nvme0;metric=blocks;region=us-west-1;size=4096': 1099511627776
  },
```

As far as I can see this looks ok, unless you can think of anything else that's missing?
