### ISSUE TITLE
New `humio_metrics` sink

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3271]
Humio can ingest metrics data, as described in the following pages:

* https://docs.humio.com/integrations/data-shippers/beats/metricbeat/
* https://docs.humio.com/integrations/data-shippers/statsd/

Given that Statsd is a more open protocol, **we'd like to _wrap_ the `statsd` sink for the `humio_metrics` sink**. Notice how we [wrap the `splunk_hec` sink for the `humio_logs` sink](https://github.com/timberio/vector/blob/master/src/sinks/humio_logs.rs).

**Comment by FungusHumungus** [comment]
The StatsD interface to Humio only works with the self hosted version, which isn't particularly useful for general clients. So instead we are going to take the approach of converting the metrics into logs (ala #3552) and then send the logs to Humio as per the existing Humio Logs sink.
