### ISSUE TITLE
Improve malformed data errors

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3274]
I was assisting a user with the `prometheus` source and they ran into this error:

```
Jul 30 19:51:27.634 ERROR source{name=mystique type=prometheus}: vector::internal_events::prometheus: parsing error error=Malformed
```

While this is a good `ERROR` level log, we should take care to provide more info at the `DEBUG` level. Ideally, this would log the request details during the scrape. I'm open to other alternatives that would allow a user to inspect network activity better.

**Comment by bruceg** [comment]
Related: #3160 and #3173
