### ISSUE TITLE
Syslog Sink (v0.10.0) Drops Logs with Leading Integers when Proxied Behind Nginx with TCP & SSL

### ISSUE THREAD

**Issue by gteshome** [timberio/vector#3279]
(With apologies for the verbose title)

We recently upgraded from vector v0.9.2 to v0.10.0 and are experiencing an issue with character handling. Our setup is 

`remote syslog client -> Nginx as a TCP/TLS reverse proxy streaming to -> vector w/syslog source (TCP) to -> GCP cloud storage sink`

 With the upgrade to v.0.10.0 this breaks if the message going through Nginx starts with an integer. For example,

```asdlkkjsda,adfkjasdf,adskjasdfasd```

works fine but this fails:

```2020-07-13,15:20:17,asdlkkjsda,adfkjasdf,adskjasdfasd```

Adding any non-integer character in front of the leading integer will also work:

```>2020-07-13,15:20:17,asdlkkjsda,adfkjasdf,adskjasdfasd```

Vector prints this error:

```text
Jul 31 00:24:24 inst-vector-2 vector[2938]: Jul 31 00:24:24.002  WARN source{name=my_source_id type=syslog}:connect
ion{peer_addr=127.0.0.1}: vector::internal_events::tcp: 1 "connection error." events were rate limited. rate_limit_
secs=5
Jul 31 00:24:24 inst-vector-2 vector[2938]: Jul 31 00:24:24.002  WARN source{name=my_source_id type=syslog}:connect
ion{peer_addr=127.0.0.1}: vector::sources::util::tcp: Error received while processing TCP source
```

Nginx prints this error:

```text
2020/07/31 00:24:24 [error] 2455#0: *80 recv() failed (104: Connection reset by peer) while proxying and reading fr
om upstream, client: 10.128.0.30, server: 0.0.0.0:443, upstream: "127.0.0.1:514", bytes from/to client:421785/0, b
ytes from/to upstream:0/421785
```

This behavior does not exist when going directly to vector by bypassing Nginx or using Nginx as a reverse TCP proxy without SSL.

**Comment by gteshome** [comment]
I just ran another test where I setup the the syslog sink with TLS and completely removed nginx from the pipeline. The same behavior occurred where logs with a leading integer get dropped.

**Comment by binarylogic** [comment]
Thanks for reporting @gteshome, we'll see what's going on and attempt to reproduce.

**Comment by bruceg** [comment]
When you removed nginx from the pipeline, how were you feeding logs into vector? Was it just a direct raw connection (ie telnet, stunnel, gnutls-cli, etc) or something else?

**Comment by gteshome** [comment]
I used both gnutls-cli and openssl s_client, with the same results. I don't see any log entries in vector like when nginx is part of the path, though.

For the record, I'm running all this on CentOS Linux release 8.2.2004 on GCP.

**Comment by bruceg** [comment]
The syslog protocol requires having a number as the first word of each line. This number indicates the severity level of the log entry. There should be additional data on the lines as well, such as the timestamp, depending on _which_ syslog protocol is desired. If the logs are being fed through something that formats them for syslog transmission, it will handle this for you, but direct transmission requires reformatting the logs for syslog.

**Comment by gteshome** [comment]
@bruceg You are right that the messages we're sending through Vector are not correctly formatted Syslog. I am not able to test at the moment with proper Syslog messages but there is a behavior change in v0.10.0 because these same messages where being handled in v0.9.2.  Feel free to close this ticket if you want and I can re-open it when I am ready to test with actual Syslog messages.

**Comment by bruceg** [comment]
Between v0.9.2 and v0.10.0 we upgraded to a newer version of the syslog parsing crate [syslog_loose](https://crates.io/crates/syslog_loose), so that could be the cause of the parsing differences.
