### ISSUE TITLE
Feat: Key/Value (KV) parser

### ISSUE THREAD

**Issue by Nick011** [timberio/vector#3283]
# Description

As a current user of Logstash who would like to transition to vector for performance reasons, I would like to have a transform similar to Logstash's [KV parser](https://www.elastic.co/guide/en/logstash/current/plugins-filters-kv.html)

This request has been [made previously](https://github.com/timberio/vector/issues/2246). My use case does not work with `logfmt` because my data is not separated by whitespace and is not split on `=` characters. The Logstash KV parser allows the user to define; the separator, the key/value split character(s) and, trim character(s) for both the key and the value.

# Requirements

A new Key/Value Transform with the following options:

- [x] Can define a separator for splitting key/value pairs
- [x] Can define the character(s) for splitting the key and value
- [x] Can trim characters from the beginning and end of both the key and the value
- [x] Can define the field to parse
- [x] Can define if the field should be dropped after parsing
- [x] Can define the target field
- [x] Can define if the target field should be overridden
- [x] Can define data types for the values

# Additional Notes

Yes, this could be accomplished via lua scripting, or maybe even a regex. However, I believe this is a common enough use case that it warrants it's own native transform.

I have a branch and PR ready to do this.

**Comment by binarylogic** [comment]
Thank you for the detailed issue! I agree that we need this. I'm going to lump this with some upcoming parsing work.
