### ISSUE TITLE
Buggy elasticsearch test

### ISSUE THREAD

**Issue by bruceg** [timberio/vector#3303]
I'm leaving this in the hopes that somebody else might have a clue what's going on.

Setting `request.in_flight_limit = 1` in the elasticsearch sink causes the test `sinks::elasticsearch::integration_tests::insert_events_with_failure` to reliably fail. Any value greater than `1` works. On the surface, this isn't a test that should depend on the concurrency level.

Further, when it _works_, the result is 99 records returned by the query, while I would expect it to be just 1.

I have no idea what's going on at this point.

```patch
diff --git a/src/sinks/elasticsearch.rs b/src/sinks/elasticsearch.rs
index c456df128..9f329fbed 100644
--- a/src/sinks/elasticsearch.rs
+++ b/src/sinks/elasticsearch.rs
@@ -821,6 +821,10 @@ mod integration_tests {
                 max_events: Some(1),
                 ..Default::default()
             },
+            request: TowerRequestConfig {
+                in_flight_limit: Some(1),
+                ..Default::default()
+            },
             ..Default::default()
         }
     }

```

**Comment by bruceg** [comment]
Note that this is what is causing ES integration tests on #3094 to fail, as the new auto controller starts with the currency at 1 rather than the maximum.

**Comment by lukesteensen** [comment]
As far as I can tell, this seems to be odd behavior from ES itself. Here's what happens with the two concurrent requests:

```
Aug 03 17:59:51.720 DEBUG http: vector::sinks::util::http: sending request. uri=http://localhost:9200/_bulk?timeout=60s method=POST
Aug 03 17:59:51.721 DEBUG http: vector::sinks::util::http: sending request. uri=http://localhost:9200/_bulk?timeout=60s method=POST
Aug 03 17:59:51.901 DEBUG http: vector::sinks::util::http: response. status=200 version=HTTP/1.1
Aug 03 17:59:51.902  WARN request{request_id=0}: vector::sinks::elasticsearch: ElasticSearch error response err_type=illegal_argument_exception reason=mapper [message] of different type, current_type [long], merged_type [text] rate_limit_secs=30
Aug 03 17:59:51.902  WARN request{request_id=0}: vector::sinks::util::retries2: request is not retryable; dropping the request. reason=some messages failed
Aug 03 17:59:51.920 DEBUG http: vector::sinks::util::http: response. status=200 version=HTTP/1.1
test sinks::elasticsearch::integration_tests::insert_events_with_failure ... ok
```

And here's what happens when the requests are sent in series:

```
Aug 03 18:02:47.685 DEBUG http: vector::sinks::util::http: sending request. uri=http://localhost:9200/_bulk?timeout=60s method=POST
Aug 03 18:02:47.889 DEBUG http: vector::sinks::util::http: response. status=200 version=HTTP/1.1
Aug 03 18:02:47.890 DEBUG http: vector::sinks::util::http: sending request. uri=http://localhost:9200/_bulk?timeout=60s method=POST
Aug 03 18:02:47.898 DEBUG http: vector::sinks::util::http: response. status=200 version=HTTP/1.1
thread 'sinks::elasticsearch::integration_tests::insert_events_with_failure' panicked at 'assertion failed: `(left != right)`
  left: `2`,
 right: `2`', src/sinks/elasticsearch.rs:785:17
```

So when we send two concurrent requests, the **second one succeeds first, and then the first one fails** with what seems like the opposite of the intended mapping error (fails to parse the message as long instead of string). When we send one at a time, they both succeed.

It seems like the fix here is to come up with a more reliable way to cause an error in ES. The current solution of changing the type of the message key is not working as intended.
