### ISSUE TITLE
Ability to delete files after they've been ingested

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#3344]
For cases where Vector is being used to ingest a batch of files, it can be useful to delete the files after they've been ingested to serve as an indication that they have been processed.

This is similar to [Splunk's sinkhole](https://docs.splunk.com/Documentation/Splunk/8.0.5/Data/Monitorfilesanddirectorieswithinputs.conf) feature.

### Current Vector Version

```
v0.10.0
```

### Use-cases

I'd like to know when Vector has finished ingesting a file.

### References

https://docs.splunk.com/Documentation/Splunk/8.0.5/Data/Monitorfilesanddirectorieswithinputs.conf

**Comment by binarylogic** [comment]
Related #2187

**Comment by jszwedko** [comment]
Oops! I missed that. It seems like that satisfies this.
