### ISSUE TITLE
Support outputing gzipped files in file sink

### ISSUE THREAD

**Issue by perfectayush** [timberio/vector#3365]
### Current Vector Version

```
vector 0.10.0 (g0f0311a x86_64-unknown-linux-gnu 2020-07-22)
```

### Use-cases
`file` sink should support output of gzipped files. This is useful to reduce the disk utilization.

### Attempted Solutions
It can't be done via vector right now.

### Proposal
Extend the file sink to support `compression` key. And then extend the `open_file` interface in src/sinks/file/mod.rs to write a gzipped file. This should be fairly straight forward. I am trying to modify code but have couple of concerns:
1. Looks like gzipping files is not an stdlib feature in rust. Usually languages implement a gzipped file interface with similar semantics to a regular file. I have looked up online on how to achieve this and the top suggest is to use a buffered writer. Currently file sink is not using buffered writes.
2. I am not sure about the `async` semantics.

**Comment by ktff** [comment]
Done with #3373 and #3535
