### ISSUE TITLE
K8s: make vector installable via kubeapps.com

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#3384]
This is something we should get automatically from publishing a Helm Chart properly, but we should double-check if any extra work is needed.

Close this one after installation via kubeapps.com is verified.

**Comment by MOZGIII** [comment]
Noting that to integrate with kubeapps properly we should submit Vector Helm repo into the Kubeapps Hub - https://hub.kubeapps.com/submit-repository

**Comment by eeyun** [comment]
@MOZGIII I might be missing something here - do you mean with a local instance of kubeapps? Kubeapps is just a glorified directory of installation instructions that are native to the published package metadata. Our page on kubeapps includes:

![Screen Shot 2021-02-22 at 11.04.45 AM.png](https://images.zenhubusercontent.com/55ba46944f7a08fbb7f40032/aa3dc1aa-3884-40cf-83d4-fdca7a8c8c56)

**Comment by eeyun** [comment]
Closing this as there is no work to be completed from the initial issue description.
