### ISSUE TITLE
New `unix` source

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#339]
A simple `unix` source. This is already supported in our `syslog` source so I assume we can reuse a lot of that code.

**Comment by a-rodin** [comment]
If we proceed with adding this, would it make sense to merge it alongside `tcp` and `udp` sources into a single `socket` source? And the same applies to `tcp` sink.

**Comment by binarylogic** [comment]
Yep, good suggestion. I'll close and open a new issue representing that.
