### ISSUE TITLE
Help in stopping vector writing internal logs to /var/log/messages

### ISSUE THREAD

**Issue by raghu999** [timberio/vector#3414]
Hi Team,
 The internal vector logs are being written to the journald and `/var/log/messages` which is filling up our root disk is there a way to configure vector to write the logs to its own file and stop writing to `/var/log/messages`. I see `StandardOutput=null` and `StandardError=null` options available for systemd but that will stop vector to not log any internal logs which we dont want to happen. Please let us know if there is any other alternative. Thanks

**Comment by jszwedko** [comment]
Hi @raghu999 

Usually a syslog daemon (like rsyslog) is responsible for writing to `/var/log/messages`. You should be able to configure the daemon to route vector logs elsewhere. For rsyslog, this would look something like:

```
:app-name, isequal, "vector" /var/log/vector.log
&~
```

To route vector messages to `/var/log/vector.log`.

I'd recommend removing any `StardardOutput` and `StardardError` lines from your systemd unit file for vector. The distributed one defaults to sending via `syslog`, but I think it is better to rely on your configured systemd defaults.

**Comment by raghu999** [comment]
Issue resolved with new version.
