### ISSUE TITLE
Add more data to auto-concurrency trace messages

### ISSUE THREAD

**Issue by bruceg** [timberio/vector#3425]
The traces produced by the auto-concurrency layer only emit very basic data about what actually changed. They should be enhanced to include all the measurements used to reach the decision to make the change, such as measured RTT, past RTT, back pressure, etc.

**Comment by binarylogic** [comment]
@bruceg did https://github.com/timberio/vector/pull/3452 close this?

**Comment by bruceg** [comment]
Yes I think it did.
