### ISSUE TITLE
Runtime is shuting down too soon

### ISSUE THREAD

**Issue by ktff** [timberio/vector#3438]
### Vector Version
Master.

### Context
We are shutting down runtime before all work has been done. Detected in #3373 where full runtime shutdown has been initiated while sink future is still running. This manifest it self through underlying `File` futures returning cancelled error. 

### Vector Configuration File

Requires #3373 
```toml
[sources.in]
  type = "generator" # required
  lines = ["Line 1", "Line 2"] # required
  #batch_interval = 0.001 # optional, no default

[sinks.out]
    inputs = ["in"]
    type = "file"
    path = "vector-%Y-%m-%d.log.gz" # required
    compression = "gzip"

    # Encoding
    encoding.codec = "ndjson" # required
```

### Debug Output

```
Aug 13 15:36:52.745  INFO vector: Log level "debug" is enabled.
Aug 13 15:36:52.747  INFO vector: Loading configs. path=["../../generator_to_file.toml"]
Aug 13 15:36:52.761  INFO vector: Vector is starting. version="0.11.0" git_version="v0.9.0-498-g955e293" released="Thu, 13 Aug 2020 12:59:05 +0000" arch="x86_64"
Aug 13 15:36:52.761  INFO vector::topology: Running healthchecks.
Aug 13 15:36:52.762  INFO vector::topology: Starting source "in"
Aug 13 15:36:52.762  INFO vector::topology::builder: Healthcheck: Passed.
Aug 13 15:36:52.762  INFO vector::topology: Starting sink "out"
^CAug 13 15:37:00.724  INFO vector: Shutting down.
Aug 13 15:37:00.725  INFO vector::topology: Shutting down... Waiting on: out, in. 59 seconds left
Aug 13 15:37:00.725 DEBUG source{name=in type=generator}: vector::topology::builder: Finished
Aug 13 15:37:01.153 DEBUG sink{name=out type=file}: vector::topology::builder: Finished
Aug 13 15:37:01.153 DEBUG vector::sinks::file: Receiver exhausted, terminating the processing loop.
Aug 13 15:37:01.153 DEBUG vector::sinks::file: Flushing all the open files
Aug 13 15:37:01.154  INFO vector: Runtime shutdown
Aug 13 15:37:01.157 ERROR vector::sinks::file: Failed to flush file. path=b"vector-2020-08-13.log.gz" error=task was cancelled
```

Where 
```
Aug 13 15:37:01.154  INFO vector: Runtime shutdown
```
is an added log here 
https://github.com/timberio/vector/blob/bb942dda71e3f85cd14e0ec36e651d3b991b54b6/src/main.rs#L190-L191
too illustrate what's happening.

### Expected Behavior
Our topology shutdown should finish after our sinks finish.

### Actual Behavior
Our topology shutdown has finished before our sinks have which is causing too early runtime shutdown.

### Additional Context
This separation of sinks tasks is probably the cause 
https://github.com/timberio/vector/blob/bb942dda71e3f85cd14e0ec36e651d3b991b54b6/src/sinks/streaming_sink/compat.rs#L52-L57

### References
#3373

cc. @lukesteensen

**Comment by binarylogic** [comment]
Thanks @ktff, does a solution jump out to you? I'm curious how difficult this will be to fix and if you'd be up for investigating given that you recently worked on the shutdown behavior?

**Comment by ktff** [comment]
@binarylogic 

> does a solution jump out to you?

Somewhat, we need to synchronize on a future somewhere, that's for sure. If it's the spawned task mentioned above, it should be easy. And all clues point to that being the case. 

> you'd be up for investigating 

I'm up for it.
