### ISSUE TITLE
Add `decoding.delimiter` setting for `socket` source

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3453]
The `socket` source currently splits incoming data on the `\n` character. This can be surprising to some users. A quote from a Vector user:

>  I was fiddling with the “Socket” source earlier today, and I discovered that it appears to have a built-in bias/support for ASCII-oriented text.  Specifically, a UDP datagram that happens to have ASCII text separated by newlines and also not having a final newline … appears to be split into separate messages by the source before being sent downstream. 

## Requirements

- [ ] Document this behavior.
- [ ] Add a setting, that controls the delimiter (ex: `decoding.delimiter`, see #257 and #2166)

Possibly related #257, #2166.

**Comment by jszwedko** [comment]
Covered by https://github.com/timberio/vector/issues/7464
