### ISSUE TITLE
New `internal_logs` source

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3458]
Similar to the `internal_metrics` source, we should have an `internal_logs` source that makes it easy to run Vector's own logs through its internal pipeline.

- [ ] Should not generate additional logs as they flow through the pipeline. This would create recursion and ultimately a black hole 😁 .

**Comment by skupjoe** [comment]
+1

I would like to capture vector internal logs and send them to a different sink.

Specifically, I'd like to capture internal Vector errors like `Error grabbing logs` and `vector::internal_events::regex: regex pattern failed to match.` and send them to a different sink to watch and alert on these events.

**Comment by bruceg** [comment]
I expect the "not generate additional logs" requirement is effectively impossible. Consider if this source is connected to any batch sink. The logs that sink would generate would happen well after the sources logs hit it and be completely unrelated, which generates more logs, which get batched and sinked, repeat.

Not happy about being able to generate a black hole, not even a small one.

**Comment by binarylogic** [comment]
cc @lukesteensen since he avoided a blackhole with the `internal_metrics` source.
