### ISSUE TITLE
Docker source does not show events of containers anymore

### ISSUE THREAD

**Issue by amanjeev** [timberio/vector#3469]
I cannot see any events in when I have a Docker source in my config. The same container events show up when I use `journald` as the source.

### Vector Version

Built locally from `master`: `e4c60f4598987a6295fe7378655179c8cf0b0c94`

```
vector 0.11.0 (ge4c60f4 x86_64-unknown-linux-gnu 2020-08-15)
```

### Vector Configuration File

```toml
data_dir = "/home/aj/proj/rust/vector/data"

[sources.dock]
  type = "docker"

[sinks.out]
  inputs   = ["dock"]
  type     = "console"
  encoding = "json"
```

### Debug Output

```
> RUST_BACKTRACE=full sudo ./vector/target/debug/vector -vvv --config config/vector.toml
Aug 15 21:43:13.796  INFO vector: Log level "trace" is enabled.
Aug 15 21:43:13.798  INFO vector: Loading configs. path=["config/vector.toml"]
Aug 15 21:43:13.798 TRACE vector::config::loading: Parsing config. path="config/vector.toml"
Aug 15 21:43:13.810  INFO vector: Vector is starting. version="0.11.0" git_version="v0.9.0-526-ge4c60f4" released="Sat, 15 Aug 2020 17:12:21 +0000" arch="x86_64"
Aug 15 21:43:13.811  INFO vector::sources::docker: capturing logs from now on. now=2020-08-15T21:43:13.811529977+00:00
Aug 15 21:43:13.812  INFO vector::sources::docker: listening docker events.
Aug 15 21:43:13.812  INFO vector::topology: Running healthchecks.
Aug 15 21:43:13.812  INFO vector::topology: Starting source "dock"
Aug 15 21:43:13.813  INFO vector::topology: Starting sink "out"
Aug 15 21:43:13.812  INFO vector::topology::builder: Healthcheck: Passed.
Aug 15 21:43:13.813 TRACE sink{name=out type=console}: vector::sinks::util::sink: Acking events. acking_num=0
```
and then running a container like `flog` so it generates some logs for events

```
docker -l trace run -it --rm  --name flog mingrammer/flog
```

### Expected Behavior

The generated logs from `flog` container should have showed up in the Vector event output on `console`.

### Actual Behavior

It only shows events of starting and stopping of the container.

```
Aug 15 21:43:17.204 DEBUG source{name=dock type=docker}: vector::internal_events::docker: received one container event. container_id=b546f20f3a39dc075098018cc02bdc48e40b2d33a36b094fb4013b2d1d4eb8f7 action=start
Aug 15 21:43:17.209  INFO vector::internal_events::docker: started watching for logs of container. container_id=b546f20f3a39dc075098018cc02bdc48e40b2d33a36b094fb4013b2d1d4eb8f7
Aug 15 21:43:17.274 DEBUG source{name=dock type=docker}: vector::internal_events::docker: received one container event. container_id=b546f20f3a39dc075098018cc02bdc48e40b2d33a36b094fb4013b2d1d4eb8f7 action=die
Aug 15 21:43:17.501  INFO vector::internal_events::docker: stoped watching for logs of container. container_id=b546f20f3a39dc075098018cc02bdc48e40b2d33a36b094fb4013b2d1d4eb8f7
```

### Example Data

Following is the sample data that `flog` generated

```
92.141.174.168 - - [15/Aug/2020:21:43:17 +0000] "HEAD /target HTTP/1.0" 504 9070
122.96.117.35 - - [15/Aug/2020:21:43:17 +0000] "POST /seize HTTP/1.0" 403 8269
22.40.3.207 - sawayn4750 [15/Aug/2020:21:43:17 +0000] "PATCH /maximize/e-commerce HTTP/2.0" 201 11340
162.71.87.39 - - [15/Aug/2020:21:43:17 +0000] "PUT /architect/e-business HTTP/2.0" 500 23892
30.36.28.143 - reichel4265 [15/Aug/2020:21:43:17 +0000] "DELETE /e-enable/deploy/proactive HTTP/1.0" 200 24535
70.130.88.13 - kertzmann2066 [15/Aug/2020:21:43:17 +0000] "PUT /rich/real-time/deploy HTTP/1.1" 301 26805
160.152.66.81 - spencer1158 [15/Aug/2020:21:43:17 +0000] "DELETE /grow/relationships/functionalities/seize HTTP/1.1" 304 23459
88.39.226.110 - - [15/Aug/2020:21:43:17 +0000] "PATCH /scalable/action-items/aggregate/initiatives HTTP/1.0" 201 16601
117.90.138.39 - stokes8863 [15/Aug/2020:21:43:17 +0000] "DELETE /embrace/efficient/recontextualize/models HTTP/2.0" 204 13314
5.227.62.12 - larkin6681 [15/Aug/2020:21:43:17 +0000] "DELETE /wireless/leading-edge/channels HTTP/1.0" 406 25561
210.102.19.254 - - [15/Aug/2020:21:43:17 +0000] "POST /extend/models/engage HTTP/1.0" 504 18055
178.142.171.183 - - [15/Aug/2020:21:43:17 +0000] "HEAD /holistic/rich HTTP/1.0" 403 11673
```

### Additional Context

I was hoping to add `hostname` to the Docker source but could not see any events at all to be able to work on this. Please note that using `journald` as the source, the logs from `flog` show up fine but that is a different source altogether.

### References

https://github.com/timberio/vector/issues/3136

**Comment by binarylogic** [comment]
Thanks for the detailed report @amanjeev. A couple of questions:

1. Do you see the logs when you run the `docker logs ...` command for the flog container?
2. Which Docker logging driver do you have installed.

**Comment by amanjeev** [comment]
@binarylogic : Sorry for missing details and delays.

1. I see the logs when I run `docker logs ...`. So, 

Running 
```sudo docker -l trace run -it --rm  --name flog mingrammer/flog -l```

and then while it is running, in another terminal 

```docker logs <container-id>```

2. Logging driver: `json-file` is configured (I think)

because, I believe that running `flog` with `syslog` logging driver complains that `configured logging driver does not support reading`.

**Comment by binarylogic** [comment]
Strange. This appears to be a bug then. If you are seeing logs with `docker logs` you should see them with Vector as well. We'll investigate further.

> because, I believe that running flog with syslog logging driver complains that configured logging driver does not support reading.

Correct. I believe that's the limitation described [here](https://docs.docker.com/config/containers/logging/dual-logging/#overview), where `jsonfile` and `journald` must be enabled for `docker logs` to work.

**Comment by archoversight** [comment]
This seems to be related to: https://github.com/timberio/vector/issues/5903

Since its an issue due to running flog with a tty.

**Comment by jszwedko** [comment]
Ah indeed, the issue here is the use of `--t` (`--tty`). I think this issue can be merged with https://github.com/timberio/vector/issues/5903

**Comment by jamtur01** [comment]
Closing in favor of #5903.
