### ISSUE TITLE
Type coercion functions for the remap language

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3479]
See https://github.com/timberio/vector/issues/3119#issuecomment-674862424

**Comment by binarylogic** [comment]
@Jeffail regarding timestamps. I assume we'll want timestamp functions like `now()`, etc? Would it be worth adding that function as a reasonable default for timestamp coercion?

**Comment by JeanMertz** [comment]
I believe this can be closed, as it's superseded by (among others) #3753.
