### ISSUE TITLE
Deserializer for InFlightLimit without auto and none

### ISSUE THREAD

**Issue by fanatid** [timberio/vector#3487]
`InFlightLimit` option allows `auto` and number in vector config, but some sinks support only a fixed number of requests. As a result if the config will have `auto` variant vector will panic on sink building. For such cases, we can define additional deserializer which will invalidate config on parsing.

`InFlightLimit`: https://github.com/timberio/vector/blob/133d4b59cdbe2eb42a65a4b661918c103b820a80/src/sinks/util/service2.rs#L64-L69

Ref. https://github.com/timberio/vector/pull/3422#discussion_r469583796

**Comment by bruceg** [comment]
An alternate path would be another `TowerRequestConfig` struct, possibly using a generic, that had `in_flight_limit: Option<usize>` instead of `InFlightLimit`. This could be extracted into the same `TowerRequestSettings` and then used the same as we have now.
