### ISSUE TITLE
Permit lowercasing field values in templates

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#3496]
From gitter: https://gitter.im/timberio-vector/community?at=5f3cfc4578f4a801801390a3

Vector: 0.10.0

The user is running into an issue where they need to lowercase the value in one of the fields when using it in a template as the Elasticsearch index name.

ES error:

```
ElasticSearch error response err_type=invalid_index_name_exception reason=Invalid index name [application-CRON-2020-08-19.{lc_identifier}], must be lowercase
```

Potential approaches:
* I could see this also slotting into the `remap` transform, but would require the user to set an additional key that they would only use for the ES index (and that they probably wouldn't want to send in the payload to ES).
* [Liquid-style filter](https://shopify.github.io/liquid/) support in templates to allow for something like `index = "{{ some_field | lowercase }}"`

**Comment by binarylogic** [comment]
Yep, sounds like a perfect addition for remap.

**Comment by jamtur01** [comment]
Closing in favor of #3924.
