### ISSUE TITLE
bucket-owner-full-control permission missing in ACL for S3 bucket 

### ISSUE THREAD

**Issue by sagar-jatti** [timberio/vector#3506]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Vector issue tracker reserved for bug reports and feature requests. For general usage questions, please see https://chat.vector.dev.

PSA: Using Vector? Let us know! Add your company here: Cerner

https://github.com/timberio/vector/blob/master/.meta/companies.toml

### Current Vector Version
vector 0.10.0 (g0f0311a x86_64-unknown-linux-gnu 2020-07-22)

### Use-cases
We are trying to run Vector on EC2 instances in AWS and trying to send /var/log/messages & /var/log/audit logs to a centralized S3 bucket to process data, as of now we are having issues as listed below.

- Vector is working fine and it is sending files to S3 bucket but not able to add Canonical ID of from which AWS account these files are coming to S3 bucket.
- Even if we try to add the canonical ID in destination bucket manually it doesn't allow us to add because there is no Owner for each object stored in the bucket.
- As per the AWS documents it allows to list/delete objects on the S3 objects which don't have the owner canonical ID in it so because of this we are not able to read any files which is pushed from EC2 instance to S3 bucket

### Attempted Solutions

Case1: We tried to add **acl = "private"** in vector.toml file but it works fine but no canonical ID added to S3 objects.

Case2: We tried to add _grant_full_control = "79a59df900b949e55d96a1e698fbacedfd6e09d98eacf8f8d5218e7cd47ef2be"_ in Vector.toml file this approach it passes Health Checks but didn't push log files to S3 bucket.

### Proposal
Is there any possibility to modify the permissions of the files before pushing it to S3 bucket 

### References
As of now, i have been discussing this issue in the forum and I got a response with details as per the link https://github.com/timberio/vector/pull/3439. Since we are in need of this new feature at the earliest please let me know if there is any other alternative to it to solve the issue.

**Comment by binarylogic** [comment]
https://github.com/timberio/vector/issues/4104 seems related

**Comment by lucperkins** [comment]
Closed by #5304

**Comment by jszwedko** [comment]
Just noting this was technically closed in #3439 it's actually still missing from the docs though: https://github.com/timberio/vector/blob/e8fcf75466fcddf90bbe526052b24de97e470f20/docs/reference/components/sinks/aws_s3.cue#L84-L100

I'll open a PR.
