### ISSUE TITLE
Add `file` label to all `file` source metrics

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3517]
To enable the proper KPI breakdown for the `file` source we need to include a `file` label in each metric emitted from the file source, such as `events_received`, `bytes_received`, etc.

<img width="493" alt="Image 2020-08-21 at 12 39 24 PM" src="https://user-images.githubusercontent.com/1663286/90914188-729c9a80-e3ab-11ea-8741-e4dbced162fe.png">

**Comment by ktff** [comment]
It's best to add these labels directly when emitting metric. While this can be solved with both approaches, #2660 is more brittle and for every new event we add we would need to remember and check if it is covered by an appropriate span.

This is actually a good example for where to draw a line between these two approaches, for info known outside of component definitely #2660, but inside, a direct approach like this seems to me like a better option.

**Comment by binarylogic** [comment]
Sounds good to me. Thanks for the response.

**Comment by MOZGIII** [comment]
Given how `file` fields are mixed in the events in the single stream of events that we process it doesn’t seem like a good fit for a span. So yeah, adding them directly to the event is the only way, unless we somehow pass and bind a span to each particular event in a stream.

**Comment by ktff** [comment]
@binarylogic this is approved?

**Comment by binarylogic** [comment]
Yep, given that the UI is moving forward.
