### ISSUE TITLE
Tutorial on https://vector.dev/docs/setup/installation/operating-systems/ubuntu/ failed

### ISSUE THREAD

**Issue by tinoadams** [timberio/vector#3531]
The tutorial on:

https://vector.dev/docs/setup/installation/operating-systems/ubuntu/

Here's what went wrong:

`sudo dpkg -i vector-amd64.deb` installs a new systemd unit which executes `/usr/bin/vector` as user `vector`. By default that user has no read access to `journald` in order to read logs like in the installation example. It also cannot access `/var/log/syslog` and other logs for the same reason.

```
$ cat <<-VECTORCFG > /etc/vector/vector.toml
[sources.in]
  type = "journald" # required
...
```

```
$ cat /etc/systemd/system/vector.service
[Service]   
User=vector 
Group=vector
```

```
$ sudo journalctl -u vector
Aug 23 11:02:13 test-xenial-1 vector[9207]: No journal files were opened due to insufficient permissions.
```

**Comment by jamtur01** [comment]
@tinoadams Thanks! We'll take a look at updating the tutorial. Just to confirm so you can make progress - you need to add the `vector` user to the `systemd-journal` group:

```sh
usermod -aG systemd-journal vector
```

Let us know if you spot any other issues!

**Comment by jamtur01** [comment]
@binarylogic There's a couple of options here.

1. Add

```sh
usermod -aG systemd-journal vector
```

To the Debian/Ubuntu/RPM/other places package installation scripts, c.f. https://github.com/timberio/vector/blob/master/distribution/debian/scripts/preinst.

2. Add a step to the docs telling folks to do this to set permissions. Given the automated build - we'd probably have an `interface_permissions` or `interface_setup` or something set of templates?
