### ISSUE TITLE
Add gzip compression to `http` source

### ISSUE THREAD

**Issue by yuuhhe** [timberio/vector#3542]
Like the http sink's config
`compression = "gzip"`
When using http sink send a batch of events to http source, gzip can reduce the payload size.
Now http sink support the compression config, but http source not.

**Comment by jamtur01** [comment]
Closing as dup of #3542.

**Comment by binarylogic** [comment]
Think you meant #4218

**Comment by jamtur01** [comment]
No, no I was testing my internal referential integrity. Clearly need additional unit tests.
