### ISSUE TITLE
Collect metrics from services v1 RFC

### ISSUE THREAD

**Issue by jamtur01** [timberio/vector#3547]
We need an RFC for https://github.com/timberio/vector-product/issues/35. We need a simple MVP of service metric collection.

## Prior Art
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/apache
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/nginx
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/postgresql
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/redis
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/http
https://github.com/elastic/beats/tree/master/metricbeat

## Requirements

I recommend we adapt much of the basic constructs from #3191 including:

* Architecture of sources - one source versus many sources. Although I think that'll be moot and it'll be many sources.
* Frequency/granularity of this data and how to manage the configuration of this.

We then need to:

- [ ] Select two or three sources as test bed/templates. I recommend one from Nginx/Apache, one from a DB like PG/Redis, and one generic like a HTTP collector or one from a Cloud Provider like AWS' Cloudwatch.
- [ ] Address how we should collect data for each of these resources. Be specific with Rust libraries, OS-level commands, etc.

**Comment by jszwedko** [comment]
Noting that I did create an RFC for collecting metrics from Apache which seems like fits under this: #3092

**Comment by jamtur01** [comment]
Yes - I just found that. :) Literally 10 minutes ago.

**Comment by jamtur01** [comment]
I'm going to close this in favor of the point RFCS.
