### ISSUE TITLE
Support metrics with the new `remap` transform

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3550]
The [new `remap` transform](https://github.com/timberio/vector/pull/3341) currently only works with log data. It would be nice to bring the power of this syntax to our metrics data. Specifically the ability to:

1. Add, rename, and remove tags (deprecating the `add_tags`, `rename_tags`, and `remove_tags` transforms).
2. Parse and munge labels accordingly (remap functions).
3. Modify the metric timestamp?

This is intentionally a broad issue to represent metrics support for this transform. Before we begin work we should create an RFC that discusses how this works. There are limitations with metrics tags that are not present with log fields, such as nesting.

**Comment by FungusHumungus** [comment]
This has now been implemented, so can be closed!
