### ISSUE TITLE
Add `podLabels` template variable to DaemonSet template for Helm

### ISSUE THREAD

**Issue by nkinkade** [timberio/vector#3568]
### Current Vector Version
`0.11.0-nightly-2020-08-18` via Helm

### Use-cases
The [current Helm template for the Vector DaemonSet](https://github.com/timberio/vector/blob/master/distribution/helm/vector/templates/daemonset.yaml) does not appear to let a user installing Vector into a kubernetes cluster via Helm to modify pod labels. It does, however, already [allow a user to modify pod annotations](https://github.com/timberio/vector/blob/master/distribution/helm/vector/values.yaml#L36). For any number of reasons, users may like to label all nodes belonging to a given DaemonSet.

### Attempted Solutions
Our current workaround is to patch the DaemonSet created by Helm immediately after it is created. This works, but is clunky

### Proposal
Add a new `podLabels` section to the Vector Helm DaemonSet template, in the same way that [you already have for pod annotations](https://github.com/timberio/vector/blob/master/distribution/helm/vector/templates/daemonset.yaml#L16). This will allow users to add pod labels via a values.yaml file passed to Helm.

**Comment by nkinkade** [comment]
I'd be happy to work up a PR, if that would facilitate this feature, unless there is some reason that this feature has been intentionally left out. Otherwise, I suspect it would be a fairly minor change. Let me know what is easiest...

**Comment by MOZGIII** [comment]
It is something I missed while working on the feature initially, feel free to create a PR, I'd be happy to review :smile: No reason not to have this.

**Comment by nkinkade** [comment]
Excellent. I'll put together a (presumably small) PR tomorrow. Thank you.

**Comment by nkinkade** [comment]
@MOZGIII: PR submitted. It is very small.
