### ISSUE TITLE
Vectordev Daemonset POD goes into CrashLoopBackOff

### ISSUE THREAD

**Issue by abhi-paul** [timberio/vector#3579]
### Vector Version

```

docker timberio/vector:0.10.0-alpine

```

### Vector Configuration File

```toml

      [sources.foo]

        type = "stdin"

      [sinks.bar]

        inputs = ["foo"]

        type = "console"

        encoding.codec = "json"

```

### Debug Output

```

Aug 26 12:24:57.465  INFO vector: Log level "info" is enabled.

Aug 26 12:24:57.469  INFO vector: Loading configs. path=["/etc/vectordev.toml"]

Aug 26 12:24:57.471  INFO vector: Vector is starting. version="0.10.0" git_version="v0.9.0-377-g0f0311a" released="Wed, 22 Jul 2020 20:01:29 +0000" arch="x86_64"

Aug 26 12:24:57.472  INFO vector::topology: Running healthchecks.

Aug 26 12:24:57.472  INFO vector::sources::stdin: Capturing STDIN.

Aug 26 12:24:57.472  INFO vector::topology: Starting source "foo"

Aug 26 12:24:57.472  INFO vector::topology: Starting sink "bar"

Aug 26 12:24:57.477  INFO source{name=foo type=stdin}: vector::sources::stdin: finished sending

Aug 26 12:24:57.477  INFO vector::shutdown: All sources have finished.

Aug 26 12:24:57.477  INFO vector: Shutting down.

{"host":"sab12","message":"Hello, World from Vectordev eventlog!","source_type":"stdin","timestamp":"2020-08-26T12:24:57.477471868Z"}

```

I am running the vectordev container image inside pod with below command & args as part of Daemonset yaml file but after processing STDIN event container is going into "Back-off restarting failed container" and thereafter it goes into CrashLoopBack.

```

command: ["/bin/sh"]

args: ["-c", "echo 'Hello, World from Vectordev eventlog!' | vector --config /etc/vectordev.toml"]

```

### Expected Behavior

Pod should be in Running state...Don't why Vector is goes into Shutting down and then CrashLoopBackOff?

**Comment by MOZGIII** [comment]
The command you're using is `echo 'Hello, World from Vectordev eventlog!' | vector --config /etc/vectordev.toml`. What this does is starts vector, then sends `Hello, World from Vectordev eventlog!'` to vector's stdin and then it *closes stdin* (`vector::sources::stdin: finished sending` in the logs). When stdin closes, vector doesn't have any work left to do, and it shuts down. This, in turn, causes the Pod to be in the crashloop state, where it just attempts to start vector, but every time it shuts down. It doesn't technically crash, but Kubernetes can't tell the difference.

I'm not sure what was the intent, but if you just want to use Vector to collect logs from Kubernetes - please take a look at https://github.com/timberio/vector-k8s-examples. We'll release a new version with Kubernetes support soon, for now, please use nightly builds (see the example repo).

**Comment by MOZGIII** [comment]
I'm closing this issue, please reopen if you have any further questions or need help with this.
