### ISSUE TITLE
Configurable Kinesis partition keys

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#358]
Currently, Vector generates random partition keys in the `aws_kinesis` sink, but we need to provide the ability for the user to use an event field as the key. This is the same as the `kafka` sink's `key_field` option.

- [ ] Add new `partition_key_field` option that accepts a string for the event field to use.
- [ ] The `partition_key_field` field is optional, the default is to generate a random string (which is what currently happens)
- [ ] If the provided key name does not exist log a rate limited warning.

**Comment by lukesteensen** [comment]
Is this a place where it really makes sense to use interpolation? It seems quite different to me than something like ES indexes and I would expect to just provide a field name and have vector use the value in that field.

**Comment by binarylogic** [comment]
Agree, requirements have been updated to reflect that.
