### ISSUE TITLE
Make the `namespace` option on metrics sinks optional

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3609]
Following up on https://github.com/timberio/vector/pull/3519#issuecomment-682227377 and https://github.com/timberio/vector/issues/3609#issuecomment-682246671, we should make the `namespace` optional on all of the metrics sinks. There are cases where metrics are already prefixed, and therefore, an additional prefix is not needed.

## Requirements

- [ ] `aws_cloudwatch_metrics` sink
- [ ] `datadog_metrics` sink
- [ ] `influxdb_metrics` sink
- [ ] `prometheus` sink
- [ ] `statsd` sink

**Comment by jszwedko** [comment]
Just noting that the there are other metric sinks have this as a required field too:

* `aws_cloudwatch_metrics`
* `influxdb_metrics`
* `statsd`
* `datadog_metrics`

We may want to consider making it optional there as well.

**Comment by binarylogic** [comment]
Updated the description to account for those.
