### ISSUE TITLE
Add `internal_metrics` source `.meta` file

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3631]
We haven't documented this source since it was undergoing quite a bit of change and development. Given that we're settling on naming (#https://github.com/timberio/vector/issues/3629) and finalizing instrumentation, we should add the appropriate `.meta/sources/internal_metrics.toml` file.

**Comment by lucperkins** [comment]
This has been addressed in recent work, though under the CUE system rather than the `.meta` system.
