### ISSUE TITLE
Splunk integration test intermittently fails

### ISSUE THREAD

**Issue by leebenson** [timberio/vector#3651]
In #3644, noticed that Linux Splunk integration testing [occassionally fails](https://github.com/timberio/vector/pull/3644/checks?check_run_id=1052626702) with:

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: "https://localhost:8089/services/data/inputs/http?output_mode=json", source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) }', src/sinks/splunk_hec.rs:723:19

**Comment by jamtur01** [comment]
Having played with this a little recently I think this might be because the Splunk test container isn't ready when the tests are run.

**Comment by leebenson** [comment]
Might be worth sticking a `wait_for_tcp` call in this test. I'll file a quick PR.

**Comment by leebenson** [comment]
Actually, this is assigned to @ktff, so will hold fire.

**Comment by binarylogic** [comment]
@leebenson go for it if it's very simple. Just reassign yourself.

**Comment by ktff** [comment]
Resolved with #3692.
