### ISSUE TITLE
Generate IDs for each event?

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#366]
After adding https://github.com/timberio/vector/issues/365, it caused me to think about default IDs for each event. This is very useful when you want to relate events across disparate storages. My concerns are performance. You could also make the case that every event already has a composite ID with the `timestamp` and `message` fields. Options I'm thinking through:

1. Do this by default for every event.
2. Do this lazily, when needed (ex, when flushing), but the make the ID deterministic (a hash of the timestmap and message, for example)
3. Add a `generate_id` field to each source
4. Add an `add_id` transform

**Comment by ypid-geberit** [comment]
I find it more useful to use HMAC over the raw input event to generate a deterministic document ID as supported by https://github.com/logstash-plugins/logstash-filter-fingerprint. Refer to https://www.elastic.co/blog/logstash-lessons-handling-duplicates for details. One nice side-effect this has is that you can re-index your source events to for example fix your log parsing.

I also see this as superior to the `dedupe` transform (ref: https://github.com/timberio/vector/issues/1732), at least when you output to Elasticsearch.

**Comment by binarylogic** [comment]
Closing this in favor of https://github.com/timberio/vector/issues/3747.
