### ISSUE TITLE
Spam `ERROR` logs from Vector when kubernetes_logs sees standard container restarts

### ISSUE THREAD

**Issue by tyrken** [timberio/vector#3662]
### Current Vector Version
```
vector 0.11.0 (g75844bc x86_64-unknown-linux-gnu 2020-08-28)
```

### Use-cases
Viewing vector's own logs to see if the installation is working

### Attempted Solutions
Install vector slightly unusually (running in a systemd service on the host - but this isn't the cause of my issue), view its logs, get worried by lots of "noise" **ERRORs** in the logs like:
```
Sep 01 11:47:15.483 ERROR source{name=kubernetes_logs type=kubernetes_logs}:file_server: vector::internal_events::file: failed reading file for fingerprinting. path="/var/log/pods/platform_cluster-autoscaler-aws-cluster-autoscaler-78c69b78-jkpdl_cb3de7e0-67e1-416f-9c3e-e0ad2e640b67/aws-cluster-autoscaler/0.log" error=Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

### Proposal
K8s as part of it's standard behaviour (at least in v1.16+ using the common Docker container driver), creates symlinks in `/var/log/pods/NAMESPACE_PODNAME_HASH/CONTAINERNAME/`, called `0.log`, `1.log`, etc., directed to the actual log file owned by the docker daemon `/var/lib/docker/containers/HASH/HASH-json.log`.   It makes `0.log` for the first time it runs the container, and `1.log`, `2.log`, after any restarts - which can be a standard occurrence in the case of eventually consistent liveness/readiness checks.  Docker is then free to cleanup old containers to reclaim disk space, which will mean in time `0.log` becomes a dangling symlink - hence the error vector issues.  Logs were being correctly read from the `1.log` symlink as hoped in the given example.

I realise this is **very** nice-to-have, but it would be a better K8s UX if these expected situations did not yield ERROR level logs from Vector (drowning out other real ERRORs), if I accept the actual dangling symlink is an error for the low-level Vector file-logging component you make up the K8s feature from.

I would accept adding a new option "ignore_dangling_symlinks" that would get passed though from the kubernetes_logs code to vector's file scanning routines, but would prefer this default to true and not be a needed option at all.

**Comment by MOZGIII** [comment]
Interesting. So, for this to work, we'd need to recognize the case when `/var/log/pods/platform_cluster-autoscaler-aws-cluster-autoscaler-78c69b78-jkpdl_cb3de7e0-67e1-416f-9c3e-e0ad2e640b67/aws-cluster-autoscaler/0.log` exists, is a symlink, and it's target (let's assume `/var/lib/docker/containers/QWE/QWE-json.log`) is already gone. Correct?

It's not clear if we'd just want to mute the errors, or do something more advanced, like excluding these files from log collection via our globbing mechanism.

@tyrken how often do you see these errors? They should be reasonably rare in my understanding. Could you send us some log extracts from vector?

**Comment by tyrken** [comment]
Yes your summary/restatement is correct.  Thinking about it this is probably as we run `docker system prune -af --filter until=1h` in a cron to drop old containers & save disk space.  This might be less common around your respective users, but is necessary for "real" work rather than test clusters, where you want the worker-nodes to last days not just hours before they run out of disk space.  If it's working then Vector would have already shifted the logs off to central storage for any later inspection.

Example logs:

```
Sep 01 13:50:00 microservices-eks-nodes-i-0df6593cef579609b vector[17495]: Sep 01 13:50:00.000 ERROR source{name=kubernetes_logs type=kubernetes_logs}:file_server: vector::internal_events::file: failed reading file for fingerprinting. path="/var/log/pods/platform_cluster-autoscaler-aws-cluster-autoscaler-78c69b78-jkpdl_cb3de7e0-67e1-416f-9c3e-e0ad2e640b67/aws-cluster-autoscaler/0.log" error=Os { code: 2, kind: NotFound, message: "No such file or directory" }
Sep 01 13:50:00 microservices-eks-nodes-i-0df6593cef579609b vector[17495]: Sep 01 13:50:00.001 ERROR source{name=kubernetes_logs type=kubernetes_logs}:file_server: vector::internal_events::file: failed reading file for fingerprinting. path="/var/log/pods/kube-system_ebs-csi-controller-57cc4b7b9-9hgc8_d3774c4d-919b-4e6a-9892-7203a2eb833b/csi-attacher/0.log" error=Os { code: 2, kind: NotFound, message: "No such file or directory" }
Sep 01 13:50:10 microservices-eks-nodes-i-0df6593cef579609b vector[17495]: Sep 01 13:50:10.004 ERROR source{name=kubernetes_logs type=kubernetes_logs}:file_server: vector::internal_events::file: failed reading file for fingerprinting. path="/var/log/pods/kube-system_metrics-server-f78cb8cd8-t4nx2_1b131eec-5619-4d0e-b4d0-b320772a02fa/metrics-server/0.log" error=Os { code: 2, kind: NotFound, message: "No such file or directory" }
Sep 01 13:50:10 microservices-eks-nodes-i-0df6593cef579609b vector[17495]: Sep 01 13:50:10.005 ERROR source{name=kubernetes_logs type=kubernetes_logs}:file_server: vector::internal_events::file: failed reading file for fingerprinting. path="/var/log/pods/cert-manager_cert-manager-7d9ccdb774-9fdw4_583665d5-4b5d-4330-bf6e-5363b286066c/cert-manager/0.log" error=Os { code: 2, kind: NotFound, message: "No such file or directory" }
Sep 01 13:50:10 microservices-eks-nodes-i-0df6593cef579609b vector[17495]: Sep 01 13:50:10.006 ERROR source{name=kubernetes_logs type=kubernetes_logs}:file_server: vector::internal_events::file: failed reading file for fingerprinting. path="/var/log/pods/platform_cluster-autoscaler-aws-cluster-autoscaler-78c69b78-jkpdl_cb3de7e0-67e1-416f-9c3e-e0ad2e640b67/aws-cluster-autoscaler/0.log" error=Os { code: 2, kind: NotFound, message: "No such file or directory" }
Sep 01 13:50:10 microservices-eks-nodes-i-0df6593cef579609b vector[17495]: Sep 01 13:50:10.006 ERROR source{name=kubernetes_logs type=kubernetes_logs}:file_server: vector::internal_events::file: failed reading file for fingerprinting. path="/var/log/pods/kube-system_ebs-csi-controller-57cc4b7b9-9hgc8_d3774c4d-919b-4e6a-9892-7203a2eb833b/csi-attacher/0.log" error=Os { code: 2, kind: NotFound, message: "No such file or directory" }
Sep 01 13:50:20 microservices-eks-nodes-i-0df6593cef579609b vector[17495]: Sep 01 13:50:20.346 ERROR source{name=kubernetes_logs type=kubernetes_logs}:file_server: vector::internal_events::file: failed reading file for fingerprinting. path="/var/log/pods/kube-system_metrics-server-f78cb8cd8-t4nx2_1b131eec-5619-4d0e-b4d0-b320772a02fa/metrics-server/0.log" error=Os { code: 2, kind: NotFound, message: "No such file or directory" }
...
```

They repeat approx every 10 seconds, I'm guessing every time you scan for new files to watch, and currently make up over half of the log output of the vector service itself.  (The other bits are mostly warnings over JSON parse failures I'm debating to log in another ticket.)

**Comment by MOZGIII** [comment]
This is an issue with the `file` source, we might want to address it as part of the rewrite instead of doing this explicitly.

**Comment by spencergilbert** [comment]
Is there a timeline on the `file` rewrite that would/could address this?
