### ISSUE TITLE
TLS certificate chain not being sent

### ISSUE THREAD

**Issue by suvl** [timberio/vector#3664]
Hey! We are using the latest 0.10.0 and again we have some TLS troubles.

We have a Lets Encrypt certificate that has an intermediary certificate before the root. Both certificates are in the .crt file, and the .key file has ofc just one key, for the server certificate and not for the intermediate cert. The server (vector in this instance) is supposed to send the full chain, but it is not sending the intermediate certificate.

Running `openssl s_connect` we learn that the problem is exactly chain validation:

```
SSL handshake has read 2009 bytes and written 413 bytes
Verification error: unable to verify the first certificate
```

So I end up having to place some proxy in front of Vector to handle the TLS part of the connection.

## How To Reproduce

* Create a cert with an intermediate CA before the root CA.
* Configure vector to use that cert using `tls.crt_file` and `tls.key_file`
* Try to connect to vector securely using i.e. OpenSSL or even curl

**Comment by binarylogic** [comment]
Thanks for reporting @suvl, we'll have someone take a look.

**Comment by renegaderyu** [comment]
Seeing this as well except I thought I was doing certs wrong. Asked for help in the community here: https://gitter.im/timberio-vector/community?at=5f4e87d736e6f709fd1938e9 and I've linked that thread to this bug.

**Comment by Hoverbear** [comment]
I've managed to find a reproduction, @bruceg is making a fix!
