### ISSUE TITLE
Consider making namespace a first class field on `Metric`

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#3684]
Related #3609 

Opening this to pull out [my comment](https://github.com/timberio/vector/issues/3609#issuecomment-682246671) from #3609. Aside from making them optional, I think we may want to make the `namespace` of a metric a first-class field on `Metric` as:

* It's otherwise difficult to tell if a metric already has a namespace
* Some sinks require the namespace as a separate field (e.g. `aws_cloudwatch_metrics`)

**Comment by jszwedko** [comment]
RFC: https://github.com/timberio/vector/pull/3686

**Comment by jszwedko** [comment]
Closed by #3686

**Comment by jamtur01** [comment]
Closing in favor of #3896.
