### ISSUE TITLE
Fingerprint/Hashing transform

### ISSUE THREAD

**Issue by spencergilbert** [timberio/vector#3691]
### Current Vector Version

```
❯ vector --version
vector 0.10.0 (g0f0311a x86_64-unknown-linux-gnu 2020-07-22)
```

### Use-cases

I'm evaluating vector as a replacement for logstash/fluentd at my company and we currently use [the fingerprint plugin](https://www.elastic.co/guide/en/logstash/current/plugins-filters-fingerprint.html) that logstash provides (with fluentd offering similar [here](https://github.com/mtakemi/fluent-plugin-genhashvalue). This helps us avoid duplicated events in elasticsearch if we ever need to replay messages.

### Attempted Solutions

This could likely be written in lua or done with the wasm transform but it could be useful for users migrating to vector (also possibly suggested already here #1129)

### Proposal

Provide a built-in transform that allows users to hash with common hashing functions.

**Comment by fanatid** [comment]
Related with https://github.com/timberio/vector/issues/3615

**Comment by binarylogic** [comment]
Thanks @spencergilbert. I'm going to close this in favor of #3749 and #3748.
