### ISSUE TITLE
Update nightly and release jobs to release artifacts independently

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3694]
Following up on https://github.com/timberio/vector/issues/3515#issuecomment-686370310. It would be nice if we posted artifacts independently as they are made available. This way a single platform failure will not block the entire release.

**Comment by Hoverbear** [comment]
Agreed!

**Comment by jamtur01** [comment]
Closed - if build/tests do not pass then we shouldn't release partial releases/artifacts.
