### ISSUE TITLE
Possible unhandled/not received docker events

### ISSUE THREAD

**Issue by fanatid** [timberio/vector#3706]
First message in the discussion on discord: https://discord.com/channels/742820443487993987/746070591097798688/751381681969299466

I checked docker source code and do not see how it's possible. The container indeed will be restarted in the loop while we do not get the event `die`/`pause` from the docker daemon. But how's it's possible? Docker daemon sent some other event?

@ktff any ideas here?

**Comment by fanatid** [comment]
Superseded by #3709

**Comment by juchiast** [comment]
Looking at discord chat, this seems to be docker's problem and there's nothing we can do about it?

**Comment by fanatid** [comment]
Looks like yes, but even if this docker error we should handle error nicer (add delay / exclude container / etc).
