### ISSUE TITLE
minor docs fixup, `speicified` -> `specified`

### ISSUE THREAD

**Issue by aegershman** [timberio/vector#3717]
Hello! apologies in advance, I read over CONTRIBUTING and noticed a request a DCO + git commit signature, and at the moment I'm on my phone, so it's a bit of setup for what I'm wanting to do which is suggest a spelling correction in the doc: https://vector.dev/docs/reference/sources/file/#multiline specifically at https://github.com/timberio/vector/blob/master/.meta/_partials/fields/_multiline_options.toml.erb#L6

`speicified` -> `specified`

Apologies for not submitting a PR to fix it, I just wanted to put it out there but didn't have immediate means to ensure contributing was followed / also apologies for not following 'bug report' template, not a bug it's just a lil spelling thing. Thank you for your time 👍

**Comment by jamtur01** [comment]
Thanks @aegershman! PR'ed and much appreciated!
