### ISSUE TITLE
reload problem when changing tcp socket to udp

### ISSUE THREAD

**Issue by chezgi** [timberio/vector#3727]
1- configure tcp socket sink 
2- change socket type to udp
3- systemctl reload vector

vector logs this message: connection to tcp socket failed
it seems tcp connecion not closed when reloading configs.

**Comment by ktff** [comment]
@chezgi thanks for reporting this. There is an issue similar to this one, but I'll need some more information to confirm it. 

On what OS is this happening?
Can you provide debug log output of vector for at least the period from start of reload to message "connection to tcp socket failed"? It would help.

**Comment by chezgi** [comment]
os: yocto

this is for loki sink but the behavoir is same:
Sep 14 16:06:34.496  INFO vector::topology: Rebuilding sink "loki"
Sep 14 16:06:34.499  INFO vector::topology::builder: Healthcheck: Passed.
Sep 14 16:06:34.701  WARN sink{name=loki type=loki}:request{request_id=10}: vector::sinks::util::retries2: retrying after error: error trying to con>
Sep 14 16:06:34.701  WARN sink{name=loki type=loki}:request{request_id=15}: vector::sinks::util::retries2: retrying after error: error trying to con>
Sep 14 16:06:34.702  WARN sink{name=loki type=loki}:request{request_id=11}: vector::sinks::util::retries2: retrying after error: error trying to con>

**Comment by ktff** [comment]
@chezgi #4031 is the probable cause, but it doesn't quite explain what you are experiencing, so the plan is to fix #4031 and then to see how will that change the issue.

**Comment by ktff** [comment]
@chezgi fix for #4031 is in nightly, could you check if the issue is still present with the latest nightly version? Alternately we can wait for `v0.11` to come out. Other than that, I'm curios if the endpoint to which mentioned tcp socket sink connects has some limitation on how many connections it can handle at the same time.

**Comment by ktff** [comment]
@chezgi I think the main issue is fixed, if you still encounter the same issue with `v0.11` comment here and we'll get it reopened.
