### ISSUE TITLE
Allow multiplying strings/arrays in `remap` transform

### ISSUE THREAD

**Issue by JeanMertz** [timberio/vector#3728]
Extracted from https://github.com/timberio/vector/pull/3341#discussion_r474184279:

> Any consideration for `String * Integer` to produce a repeating string? Similarly, `Array * Integer` to extend an array?

**Comment by binarylogic** [comment]
@JeanMertz unless you've already started on this I think we should move this back to the backlog. It's low priority given the other remap work.
