### ISSUE TITLE
Support plain (non-float) integer division in `remap` transform

### ISSUE THREAD

**Issue by JeanMertz** [timberio/vector#3729]
Taken from https://github.com/timberio/vector/pull/3341#discussion_r474185413:

> If you are converting the result of integer division into a float, we should have a separate plain integer division operation. Python 3 went this way with `/` and `//`.

**Comment by bruceg** [comment]
Note that I was not necessarily recommending adding the `//` operator for this. We could also settle on having integer/integer division result in an integer, requiring an explicit conversion to float to trigger floating point division, which is the path most other languages have taken (at least those that distinguish between integers and floating point numbers).

**Comment by FungusHumungus** [comment]
@bruceg  Why do we want this? 

Is there anything that the `floor`, `ceil` and `round` functions that we currently have not cover?

**Comment by bruceg** [comment]
I've always found the behavior of integer division having a floating-point result to be surprising, but that comes from many years of programming in C and similar. I do understand the motivation for this behavior. There is one thing that these functions do not provide, and that is producing a result that is *not* a floating-point number. Due to range issues, all three should result in the same type as the input, but that doesn't turn a float into an integer. So, simple integer division then becomes `to_int(floor(X / Y))`.

**Comment by FungusHumungus** [comment]
Ah, yes that makes sense. We do have a `to_float` already. So do you think it will be sufficient to change the division routine to do this?

integer / integer => integer result
float / integer => float result
integer / float => float result
float / float => float result

I'm thinking adding an extra operator for integer division is an overcomplication.

**Comment by bruceg** [comment]
The question becomes, which is least surprising: `5 / 2 = 2` or `5 / 2 = 2.5`? From a programming perspective starting with integers should result in integers, but that is nonsense from a mathematical point of view. If we decide on a rule that operations on integers result exclusively in integers, then your suggestion is sufficient.

**Comment by binarylogic** [comment]
Definitely `5 / 2 = 2.5`, if you want my opinion.

**Comment by FungusHumungus** [comment]
Yes, looking around it does seem fairly arbitrary as to whether a field ends up as an Integer or a Float. For example, when parsing from Json, if the value is a whole number it will become an integer, if it isn't and can be represented as a float, then it becomes a float.

So if we did base the results on the input types, we could result in `5 / 2 = 2` and `5.2 / 2 = 2.6`. This could be surprising, especially for peoples who's data is only occasionally whole numbers..

**Comment by bruceg** [comment]
> So if we did base the results on the input types, we could result in `5 / 2 = 2` and `5.2 / 2 = 2.6`. This could be surprising, especially for peoples who's data is only occasionally whole numbers..

That strongly argues against the normal division resulting in anything other than a floating point number. Then the argument is over having a dedicated integer division operator over just requiring the use of `to_int`.

**Comment by FungusHumungus** [comment]
Or, do we need `to_int` at all? Could we just make `ceil`, `round` and `floor` return integers?

**Comment by binarylogic** [comment]
I'd be in favor of that.

**Comment by bruceg** [comment]
That could cause range issues. Consider if the input float is outside the range of an integer.

**Comment by FungusHumungus** [comment]
Yes, and of course, these functions also provide a `precision` parameter, allowing you to set the number of decimal places to round to. These things are never simple!!
