### ISSUE TITLE
New `parse_duration` remap function

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3733]
With log data, especially after parsing non-structured data, it's common for numbers to contain units in string format. Therefore, Vector's remap syntax could benefit from a `parse_duration` function.

## Example

For example, this common Elixir log contains time units (`5.4ms`):

```
17:42:51.469 [info] GET /17:42:51.469 [info] Sent 200 in 5.4ms
```

But the unit can change depending on the duration (`167µs`):

```
17:42:51.469 [info] GET /17:42:51.469 [info] Sent 200 in 167µs
```

In addition to the changing unit, you'll notice we went from floats to integers.

## Proposal

In the same vein that we have `to_int` and `to_float` functions, I propose that we add a `to_duration` function that handles parsing and normalizing. For example, when parsing this log:

```
17:42:51.469 [info] GET /17:42:51.469 [info] Sent 200 in 5.4ms
```

You'll likely end up with a `duration` (or whatever name they want) field:

```js
{
  // ...
  "duration": "5.4ms",
  // ...
}
```

And in order parse this into a normalized unit, I would recommend the user use the remap syntax to do the following:

```
.duration_seconds = parse_duration(.duration, "s")
del(duration)
```

This would result in:

```js
{
  // ...
  "duration_seconds": 0.0054,
  // ...
}
```

The `parse_duration` function handles all of the intricacies to normalize any value passed to it to seconds. This means:

* Handling unit suffixes.
* Converting units between each other.

## Requirements

- [ ] Recognize [valid time units](https://en.wikipedia.org/wiki/Orders_of_magnitude_(time)#Less_than_one_second) for our use case: `µs` (microsecond), `ns` (nanosecond), `ms` (millisecond), `s` (second), `m` (minute), `h` (hour), `d` (day).
- [ ] Be forgiving with parsing: `10ms` or `10 ms`.
- [ ] Convert and normalize units to the specified unit.

**Comment by JeanMertz** [comment]
@binarylogic what about [ISO8601 Duration](https://en.wikipedia.org/wiki/ISO_8601#Durations) notation?

Seems trivial to support, since the notation has to start with `P`, but we can add it in a later version if we think it's useful.

**Comment by binarylogic** [comment]
Ah yeah. Let's hold off until we identify a use case. I'm not sure where we'd see this in log data. The use case in the original issue seems much more common.
