### ISSUE TITLE
Support boolean variations for the remap `bool` function

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3734]
This might already be the case, but the Remap `bool` function should support the following inputs:

- [x] `"true"` => `true`
- [x] `"false"` => `false`
- [x] `"t"` => `true`
- [x] `"f"` => `false`
- [x] `"yes"` => `true`
- [x] `"no"` => `false`
- [x] `"y"` => `true`
- [x] `"n"` => `false`
- [x] `0` => `false`
- [x] `1` => `true`
- [x] `"0"` => `false`
- [ ] `"1"` => `true`
- [x] Case-insensitive for all of the above

**Comment by JeanMertz** [comment]
Most of this exists already:

https://github.com/timberio/vector/blob/374fca115f982d332c48143a919f59cbdf7d7771/src/types.rs#L172-L202

There are two exceptions:

* any non-0 integer is considered to be `true` (not just `1`, as defined in your list)
* `"1"` is not considered `true`

For the last one, given that `"0"` is explicitly supported, I feel like there must be a good reason why `"1"` was left out, but I can't think of one off the top of my head.

I can add that one if you want, or we can close this issue and leave as is.

**Comment by JeanMertz** [comment]
cc @binarylogic do you still want to add support for `"1"` as `true`? I'm not sure why it never got added, but again, since `"0"` _is_ added, I feel like it was a conscious decision.

**Comment by binarylogic** [comment]
It's fine to leave it out.
