### ISSUE TITLE
New `parse_json` remap function

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3738]
We need a remap function that makes it easy to parse JSON within a field's value. Combining this function with other instructions will allow users to assign the result to a field, merge it with an existing field, and more.

## Examples

For all examples we'll use this event:

```js
{
  // ...
  "message": "{\"key\": \"val\"}",
  "attributes": {
    "existing": "value"
  }
  // ...
}
```

### Assignment

It should be possible to parse the `message` key and assign it to another key:

```
.attributes = parse_json(.message)
```

This would result in:

```js
{
  // ...
  "message": "{\"key\": \"val\"}",
  "attributes": {
    "key": "val"
  },
  // ...
}
```

Notice that we replaced the `"attributes"` key entirely.

### Merging

It should be possible to parse the `message` key and combine it with the `merge` function (#3737):

```
merge(.attributes, parse_json(.message))
```

This would result in:

```js
{
  // ...
  "message": "{\"key\": \"val\"}",
  "attributes": {
    "existing": "value",
    "key": "val"
  },
  // ...
}
```

**Comment by JeanMertz** [comment]
closed in #3787.
