### ISSUE TITLE
Rename remap syntax coercion functions

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3741]
To help organize the remap function documentation and increase function discoverability, I'd like to rename the following functions:

- [x] `bool` -> `to_bool`
- [x] `float` -> `to_float`
- [x] `int` -> `to_int`
- [x] `string` -> `to_string`
- [x] `timestamp` -> `parse_timestamp`
- [ ] Add a new `to_timestamp` function, that takes two arguments, the second argument being the default. It should only accept integers as unix timestamps (seconds) and ISO8601 formatted strings. Other string formats can be parsed with the `parse_timestamp` function.

The rules for these names will be documented in #3740.

**Comment by JeanMertz** [comment]
I implemented the first 5 points in https://github.com/timberio/vector/pull/3767.

Regarding the _new_ `to_timestamp`, it feels a bit odd that the other `to_*` coercion functions take an optional second argument for when parsing fails, while `to_timestamp` does not.

Happy to do as documented here, but wanted to make sure you're aware of that difference. We can still have `to_timestamp`'s optional default value also be limited to Unix and RFC3339 formats, if that helps?

**Comment by binarylogic** [comment]
Hm, I wasn't aware they took an optional second argument. What is that for?

**Comment by JeanMertz** [comment]
It's the default value for when the field doesn't exist, or its type can't be coerced.

see: https://github.com/timberio/vector/blob/439a9cfdb48d976f19a0d2e5b84fc268752d93ba/.meta/transforms/remap.toml.erb#L118-L120

**Comment by binarylogic** [comment]
Good catch. I've updated it to take a second argument that is the default.

**Comment by binarylogic** [comment]
@JeanMertz, I'm assuming that second argument is optional, correct? If it is not provided we will error.

**Comment by JeanMertz** [comment]
Question about this part @binarylogic:

>     * It should only accept integers as unix timestamps (seconds) and ISO8601 formatted strings. Other string formats can be parsed with the `parse_timestamp` function.

What's the reason for this limitation? Is it to keep the documentation/usage of this function simple? Or maybe to reduce potential unexpected outcomes for users?

Reason I'm asking is that we already support [auto-parsing a string into a timestamp](https://github.com/timberio/vector/blob/f3c19bb137269355a78ef6eae7320b7decc0d6f3/src/types.rs#L218-L242).

We could re-use that same logic for `to_timestamp` and support all the formats described in the above link out of the box, or I could explicitly only accept UNIX and RFC3339.

**Comment by binarylogic** [comment]
> We could re-use that same logic for to_timestamp and support all the formats described in the above link out of the box

I like that. Feel free to reuse that logic.

It was mostly about the function signature. The `to_*` methods should perform automatic coercion or error unless a default was provided.
