### ISSUE TITLE
New `format_timestamp` remap function

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3742]
A `format_timestamp` function takes a timestamp as argument and formats it according to [Rust's strftime format](https://docs.rs/chrono/0.3.1/chrono/format/strftime/index.html).

Note, we explicitly opted not to use the `strftime` function name, since our remap syntax function naming rules use the `format_` prefix for formatting string (#3740).

## Example

```
.timestamp_string = format_timestamp(.timestamp, "%F")
```

Would result in:

```js
{
  "timestamp_string": "2020-08-03"
}
```

**Comment by JeanMertz** [comment]
Just to clarify @binarylogic, when you say:

> A `format_timestamp` function takes a timestamp

That means that you'll always have to first coerce any raw event fields to the `Timestamp` type, correct?

So this:

```rust
.timestamp_string = format_timestamp(.timestamp, "%F")
```

assumes that `.timestamp` was converted to a timestamp, using one of:

```rust
.timestamp = to_timestamp(.timestamp)
.timestamp = parse_timestamp(.timestamp, format = "...")
```

or, combined:

```rust
.timestamp_string = format_timestamp(to_timestamp(.timestamp), "%F")
```

**Comment by binarylogic** [comment]
> That means that you'll always have to first coerce any raw event fields to the Timestamp type, correct?

Correct.
