### ISSUE TITLE
New `strip_whitespace` remap function

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3746]
The `strip_whitespace` remap function strips leading and trailing whitespace

## Example

Given this event:

```js
{
  "message": "\t\tThis string has whitespace around it    "
}
```

And this remap instruction set:

```
.message = strip_whitespace(.message)
```

Would result in:

```js
{
  "message": "This string has whitespace around it"
}
```

## Requirements

- [ ] Strips leading _and_ trailing whitespace.
- [ ] Splits on all whitespace as defined by [Unicode whitespace character](https://en.wikipedia.org/wiki/Unicode_character_property#Whitespace).

**Comment by JeanMertz** [comment]
closed in #3787.
