### ISSUE TITLE
New `truncate` remap function

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3751]
The `truncate` function truncates a string to the provided length.

## Example

Given the following event:

```js
{
  "message": "Supercalifragilisticexpialidocious"
}
```

### Default

And the following remap instruction set:

```
.message = truncate(.message, 5)
```

Would result in:

```js
{
  "message": "Super"
}
```

### Ellipsis

And the following remap instruction set:

```
.message = truncate(.message, 5, true)
```

Would result in:

```js
{
  "message": "Super..."
}
```

Or, if the limit exceeds the length of the string, then no `...` is added:

```
.message = truncate(.message, 9999999, true)
```

Would result in:

```js
{
  "message": "Supercalifragilisticexpialidocious"
}
```

**Comment by JeanMertz** [comment]
closed in #3787.
