### ISSUE TITLE
New `flatten` remap function

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3752]
The `flatten` remap function flattens an array into a single-depth array.

### Arrays

Given the following event:

```js
{
  "array": [1 [2, [3, 4, 5]], 6]
}
```

And the following remap instruction set:

```
.array = flatten(.array)
```

Would produce:

```js
{
  "array": [1 2, 3, 4, 5, 6]
}
```

### Objects

Given the following event:

```js
{
  "object": {
    "parent": {
      "child1": 1,
      "child2", 2,
    },
    "key": "val"
  }
}
```

And the following remap instruction set:

```
.object = flatten(.object)
```

Would produce:

```js
{
  "object": {
    "parent.child1": 1
    "parent.child2": 2,
    "key": "val"
  }
}
```

**Comment by FungusHumungus** [comment]
I could do with some clarification around flattening objects that are a mixture of objects and arrays.

There is some prior art around flattening objects [here](https://github.com/timberio/vector/blob/master/src/event/util/log/all_fields.rs) where an object containing an array:

```
{ "field": [1,[2,3]] }
```
would get flattened to
```
{
  "field[0]": 1,
  "field[1][0]": 2,
  "field[1][1]": 3
}
```

The array on it's own in the remap function for this issue would just get flattened to `[1,2,3]`. So there is a difference in how they get flattened depending on if the base object is an array or an object. It feels slightly incongruous, but I can't think of a better way around it. Do you have any thoughts?

I'm a little unclear how an array containing objects should be flattened.

```
[
 {a: {b: 1}}, 
 [ 
   {a: {b: 2}}, 
   {a: {b: 3}}
 ]
]
```

This could just flatten the array and leave the objects untouched:
```
[
 {a: {b: 1}},  
 {a: {b: 2}}, 
 {a: {b: 3}}
]
```

Or, it could flatten the fields in the objects as well:
```
[
 {"a.b": 1},  
 {"a.b": 2}, 
 {"a.b": 3}
]
```

I think the first one is the least surprising, and avoids further surprises with arrays containing objects containing arrays, but that could depend on the use case.

**Comment by jszwedko** [comment]
Kind of related to that question, I could see it being useful to also do something like lodash's [`flatten`](https://lodash.com/docs/4.17.15#flattenDepth) where you pass the depth to recurse as an argument (we could default to 1).

Thus:

```
[
 {a: {b: 1}}, 
 [ 
   {a: {b: 2}}, 
   {a: {b: 3}}
 ]
]
```

With `flatten(.object, 1)` would give you:

```
[
 {a: {b: 1}},  
 {a: {b: 2}}, 
 {a: {b: 3}}
]
```

With `flatten(.object, 2)` would give you: 

```
[
 {"a.b": 1},  
 {"a.b": 2}, 
 {"a.b": 3}
]
```

I agree that flatten objects at all might be a bit surprising. Usually when I think of `flatten` I think only of nested arrays.
