### ISSUE TITLE
New `tokenize` remap function

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3760]
This aims to replace the [`tokenizer` transform](https://vector.dev/docs/reference/transforms/tokenizer/).

## Examples

Given the following event:

```
{
  "message": "217.250.207.207 - - [07/Sep/2020:16:38:00 -0400] \"DELETE /deliverables/next-generation/user-centric HTTP/1.1\" 205 11881"
}
```

And the following remap instruction set:

```
.message = tokenize(.message)
```

The result would be:

```js
{
  "message": ["217.250.207.207", null, null, "07/Sep/2020:16:38:00 -0400", "DELETE /deliverables/next-generation/user-centric HTTP/1.1", "205", "11881"]
}
```

This should largely mimic what's going on in the [`tokenizer` transform](https://vector.dev/docs/reference/transforms/tokenizer/).

## Requirements

Just to verify, the tokenize should:

- [x] Split on all whitespace as defined by the [unicode whitespace definition](https://en.wikipedia.org/wiki/Whitespace_character).
- [x] Ignore blank values, such as `""` and `"-"`
- [x] Respect quotes
- [x] Should not perform any coercion since that can be performed in a followup step.

**Comment by JeanMertz** [comment]
>     * Ignore blank values, such as `""` and `"-"`

Just to be sure, this is actually not the behaviour of the existing `tokenizer` transform.

I did implement this in [the remap implementation](https://github.com/timberio/vector/pull/4093/files#diff-818ec910a8af440038e27fc679c4d693R27-R30), but I wanted to make sure this difference is noted.
