### ISSUE TITLE
New IP address functions for the remap syntax

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3761]
Working with IP addresses is a common use case when dealing with log data. We should think about functions that help users extract (#1978) parts of an IP address and [process](https://vector.dev/docs/reference/transforms/swimlanes/#field_nameip_cidr_contains). You can see how these needs are already represented in Vector's current features with the aforementioned links.

I'm leaving this issue open so that we can agree on a set of functions that would allow users to:

- [ ] Extract parts of IPv4 and IPv6 addresses.
- [ ] Check if addresses are within larger subsets of addresses ([ex](https://vector.dev/docs/reference/transforms/swimlanes/#field_nameip_cidr_contains)).

**Comment by binarylogic** [comment]
@JeanMertz, I'm assigning this to you to outline the requirements first. Basically, propose one or more functions that would address this use case.

**Comment by JeanMertz** [comment]
Here's my suggestion w.r.t. implementing these functions. I'm cc'ing some people to review this proposal; @binarylogic, @bruceg, @jszwedko.

I'm basing this proposal mostly on Rust's stdlib [`IpAddr` type](https://doc.rust-lang.org/std/net/enum.IpAddr.html) and [the `ipnet` crate `IpNet` type](https://docs.rs/ipnet/2.3.0/ipnet/enum.IpNet.html).

### Goals

I would suggest the following goals:

1. allow interop with other remap functions and arithmetic
2. start with a limited set of IP-specific functions, expanding as we go

### Functions

Given this, here's the set of functions I would propose:

* `parse_ip` — convert from `string` to `[number]`
* `format_ip` — represent `[number]` or `string` as either v4 or v6 `string`

* `ip_hostmask` — get the IP hostmask as `[number]`
* `ip_netmask` — get the IP netmask as `[number]`
* `ip_contains` — test if a network address or IP address contains either another network address or an IP address

_We can optionally merge `ip_hostmask` and `ip_netmask` (and similar ones) into a single function, such as `ip_component(.foo, component = "netmask")`, but this would be restricted to only exposing components that can be represented as `[number]`, such as `netmask`, `hostmask`, `broadcast`, `network` and `supernet`._

Combined, these functions should get us to a useful set of applications, such as:

```rust
.ip_parts = parse_ip("127.0.0.1")
.ip_v6_netmask = format_ip(ip_netmask("127.0.0.1"), variant = "v6")
.ip_hostmask_parts = ip_hostmask(.ip_parts)
```

Converting the string-based IP to an array of numbers helps the user apply arithmetic to the different parts of the IP and improves performance when chaining multiple IP manipulations.

Having said that, all functions _except `parse_ip`_ accept both `[number]` and `String` as their input values. This allows for extra convenience (not having to convert to `[number]` first), at the cost of some extra CPU cycles to parse the string to the relevant numbers.

When passing in `[number]` it either has to contain 4 or 5 8-bit integers (with, or without routing prefix) for Ipv4 addresses, or 16 (or 17) for Ipv6 addresses.

### Examples

Here's some quick examples of the suggested functions:

**`parse_ip`**

Take a string-based IP (optionally using the CIDR notation), and convert it to an array of numbers representing the octets + routing prefix. This allows the user to then use other remap functions, or arithmetic to manipulate those individual integers.

The routing prefix defaults to `32` for IPv4 and `128` for IPv6, if none is provided.

```rust
parse_ip(value = String) -> [number]
```

Examples:

```rust
parse_ip(value = "101.45.76.219") // [101, 45, 76, 219, 32]
parse_ip(value = "::FFFF:101.45.76.219") // [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 101, 45, 76, 219, 128]
parse_ip(value = "::101.45.76.219") // [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 101, 45, 76, 219, 128]
parse_ip(value = "101.45.76.219/16") // [101, 45, 76, 219, 16]
```

Any non-valid IP format results in an error.

**`format_ip`**

Convert a list of octets to the string-representation of the IP. This allows the user to convert back to the string representation of the IP after manipulation of the individual octets.

```rust
format_ip(value = ([number] | String), variant = ("v4" | "v6" | "v6_compatible"), cidr = bool) -> String
```

_note: we could opt to not support `v6_compatible` as it [has been deprecated](https://tools.ietf.org/html/rfc4291#section-2.5.5.1)._

Examples:

```rust
format_ip(value = [101, 45, 76, 219, 32], variant = "v4") // "101.45.76.219"
format_ip(value = [101, 45, 76, 219], variant = "v6") // "::FFFF:101.45.76.219"
format_ip(value = [101, 45, 76, 219], variant = "v6_compatible") // "::101.45.76.219"
format_ip(value = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], variant = "v4") // "127.0.0.1"
format_ip(value = [101, 45, 76, 219, 16], variant = "v4", cidr = true) // "101.45.76.219/16"
format_ip(value = "101.45.76.219", variant = "v6", cidr = true) // "::FFFF:101.45.76.219/32"
```

**`ip_hostmask`**

Get the host mask of a network address.

```rust
ip_hostmask(value = ([number] | String)) -> [number]
```

Examples:

```rust
ip_hostmask(value = [101, 45, 76, 219, 20]) // [0, 0, 15, 255, 32]
ip_hostmask(value = [101, 45, 76, 219, 32]) // [0, 0, 0, 0, 32]
ip_hostmask(value = "101.45.76.219/20") // [0, 0, 15, 255, 32]
```

**`ip_netmask`**

Get the network mask of a network address.

```rust
ip_hostmask(value = ([number] | String)) -> [number]
```

Examples:

```rust
ip_netmask(value = [101, 45, 76, 219, 20]) // [255.255.240.0, 32]
ip_netmask(value = [101, 45, 76, 219, 32]) // [255.255.255.255, 32]
ip_netmask(value = "101.45.76.219/20") // [255.255.240.0, 32]
```

**`ip_contains`**

Test if a network address contains another network address.

Given that we either receive the prefix length or default it to the max value, this function can be used to both check if an IP falls within a subnet, or if one subnet falls within another subnet (or if two IPs are equal, although you might as well use `==` for that).

```rust
ip_contains(value = ([number] | String), other = ([number] | String)) -> bool
```

Examples:

```rust
ip_contains(value = [101, 45, 76, 219, 20], other = [101, 45, 76, 219, 32]) // true
ip_contains(value = "101.45.76.219/20", other = [101, 45, 76, 219, 32]) // true
```

**Comment by jszwedko** [comment]
Agreed, nice write-up!

A few thoughts / questions, but I think this is a great start.

`format_ip`

Are all ipv6 addresses representable as ipv4? I see your example of converting to 127.0.0.1, but I'm curious if all addresses would be convertable and, if not, what the output would be if it couldn't be formatted.

Is `variant` optional? It'd be nice to format it as whatever the internal representation indicates it was parsed from. For example, I'd expect `format_ip(value = parse_ip(value = "101.45.76.219"))` to give me back "101.45.76.219.

Similarly to `variant` it might be nice to have `cidr` default to whatever the value encodes. For example, `format_ip(value = parse_ip(value = "101.45.76.219/16"))` would give me back `101.45.76.219/16`. I could still pass `cidr = false` to get it back without the `/16`.

**Comment by jszwedko** [comment]
> @jszwedko
> 
> > Are all ipv6 addresses representable as ipv4?
> 
> No, I should have written that down more explicitly.
> 
> Right now if the function fails, the entire mapping (the collection of all functions and assignments for a given event) fails. On a per-event level, the end-user can configure Vector to either drop the event, or keep it in its original state.
> 
> It might be worth exploring options to ignore individual failing functions, for example in this case we could have an `ignore_error` flag for `format_ip`, which would (depending on what we want) either return `null` or the original IP if the IP cannot be formatted to the desired variant.

:+1: 
 
> > Is `variant` optional?
> 
> It's required, but your suggestion seems doable +1

:+1: I think it'd help when people aren't aware of the incoming format (if it is being parsed from a log, from example).
 
> > it might be nice to have `cidr` default to whatever the value encodes
> 
> This one is a bit trickier (but not undoable), since right now the design describes always adding the maximum value (`32` or `128`) if no routing prefix is provided. This means we lose the format of the original provided value. There are ways to fix that, however, so might be worth considering +1.

Yeah, this one I see as more of a nice-to-have, but it seems like we could support it just via a flag indicating whether it had an original `/32` or `/128` or not when parsing.

**Comment by jszwedko** [comment]
Aaah, yeah, I see. I neglected these are just ending up as `event::Value`s. Sounds good.

**Comment by bruceg** [comment]
> I'm basing this proposal mostly on Rust's stdlib [`IpAddr` type](https://doc.rust-lang.org/std/net/enum.IpAddr.html) and [the `ipnet` crate `IpNet` type](https://docs.rs/ipnet/2.3.0/ipnet/enum.IpNet.html).

I am a little concerned about conflating bare IP addresses with IP-with-netmask addresses. This leads to a bit of confusion below.

>     * `ip_hostmask` — get the IP hostmask as `[number]`
> 
>     * `ip_netmask` — get the IP netmask as `[number]`

If you're going for minimal, I'd expect these two to be far less useful than the other three.

> _We can optionally merge `ip_hostmask` and `ip_netmask` (and similar ones) into a single function, such as `ip_component(.foo, component = "netmask")`, but this would be restricted to only exposing components that can be represented as `[number]`, such as `netmask`, `hostmask`, `broadcast`, `network` and `supernet`._

I don't see this as particularly useful.

> ```rust
> .ip_parts = parse_ip("127.0.0.1")
> .ip_v6_netmask = format_ip(ip_netmask("127.0.0.1"), variant = "v6")
> ```

I have doubts about this. IPv4 and IPv6 are different addresses. You can "embed" an IPv4 address in IPv6, which would turn this into `::ffff:127.0.0.1` but that's not just a formatting convention, that's technically a different address (and also different from `::127.0.0.1` as referenced elsewhere). So I'm not sure the `variant` here is a good idea. Perhaps an explicit IP-to-IPv6 conversion function would be in order.

> Converting the string-based IP to an array of numbers helps the user apply arithmetic to the different parts of the IP and improves performance when chaining multiple IP manipulations.

What expectations do we have on having the user actually apply arithmetic to the parts of the IP? This seems unusual. Converting to a non-allocating fixed-size type (ie `Ipv4Addr` etc) would be even more performant, but would then require the use of more helper functions to access the data "inside".

> Having said that, all functions _except `parse_ip`_ accept both `[number]` and `String` as their input values. This allows for extra convenience (not having to convert to `[number]` first), at the cost of some extra CPU cycles to parse the string to the relevant numbers.

This seems reasonable for convenience.

> When passing in `[number]` it either has to contain 4 or 5 8-bit integers (with, or without routing prefix) for Ipv4 addresses, or 16 (or 17) for Ipv6 addresses.

What about using 32-bit numbers? That would let the IPv4 be representable as a single number, or two with the netmask, and makes any math on the whole address simple. I don't know if that would complicate things for IPv6 addresses.

(I think you also meant "without and with routing prefix", not the other way around)

> **`parse_ip`**
> 
> The routing prefix defaults to `32` for IPv4 and `128` for IPv6, if none is provided.

Which way is it? Does it default the routing prefix and return an address with it included, or does it return different data (as above) based on if a routing prefix was present?

> ```rust
> format_ip(value = ([number] | String), variant = ("v4" | "v6" | "v6_compatible"), cidr = bool) -> String
> ```

Does the `cidr` flag here make it include the routing prefix / network mask, or does it change the string reprentation of said mask? If it's the former, then the flag is probably misnamed.

**Comment by JeanMertz** [comment]
Thanks for the thorough review @bruceg. Left some thoughts below, and I think you're right w.r.t. the `variant` flag, so I suggested an alternative.

I also think we're veering close to "this should have been a mini-RFC", but I want to hold off on that if we can for now. Ideally, we can agree on a limited set of first functions, and then go from there, potentially using a mini-RFC down the line if we think some of the more obscure/complex functions require some more thinking.

---

> I am a little concerned about conflating bare IP addresses with IP-with-netmask addresses. This leads to a bit of confusion below.

I agree it's not ideal, but the concepts still map correctly (perhaps excluding the `variant` flag for `parse_ip`, as you alluded to), so I concluded that the functionality provided by the current proposal covers all bases without being overly complex or introducing too many IP-specific functions. I should say that I'm not an expert on terminology and exact usage, so I based this proposal off the IP address RFC and  the Rust docs I linked to.

> If you're going for minimal, I'd expect these two to be far less useful than the other three.

I agree with `ip_hostmask`, however `ip_netmask` was part of the request as listed in the original issue.

> Perhaps an explicit IP-to-IPv6 conversion function would be in order.

Yeah, maybe you're right. I wouldn't call the current `format_ip` function "wrong", but it isn't technically accurate to call it a variant.

I guess we can either find a more appropriate name for the parameter, or introduce more explicit functions, such as:

* add the `ip_to_ipv6` and `ip_from_ipv6` functions (of which the last one can fail)
* remove `variant` from `format_ip`, which would determine if it's a v4 or v6 address based on the number of octets (optionally after parsing the string)
* drop the `v6_compatible` variant until there's an explicit need for it

> Converting to a non-allocating fixed-size type (ie `Ipv4Addr` etc) would be even more performant

As I mentioned to @jszwedko, with the current implementation of the remap language, there is no way for us to do anything other than converting one `event::Value` to another. I've written about a possible way forward in #4091. I want to keep the language simple and easy to understand, and so would like to avoid introducing values that can't be assigned to a field (i.e. it has to be representable as an `event::Value`). My latest proposal to tackle this is to convert complex values to `Value::Map` (see https://github.com/timberio/vector/issues/4091#issuecomment-702066049), but I want to avoid blocking this PR on that being available.

> What about using 32-bit numbers

That's an interesting idea. I hadn't really considered it.

One issue with this could be that JSON only supports *signed* integers, which would mean on a 32-bit machine you can't represent the entire range of IPv4 addresses, requiring us to split it between multiple integers (which would be needed for Ipv6 representations regardless). Once we need to split it across multiple integers, I feel like representing it as octets is easier to work with. Another issue is that we currently don't support bitwise operations in the remap language (although we could add support, if we believe it's useful to have).

> Which way is it? Does it default the routing prefix and return an address with it included, or does it return different data (as above) based on if a routing prefix was present?

I don't quite follow your question. I believe the provided examples answer your question, don't they?

```rust
parse_ip(value = "101.45.76.219") // [101, 45, 76, 219, 32]
parse_ip(value = "::FFFF:101.45.76.219") // [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 101, 45, 76, 219, 128]
parse_ip(value = "::101.45.76.219") // [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 101, 45, 76, 219, 128]
parse_ip(value = "101.45.76.219/16") // [101, 45, 76, 219, 16]
```

**Comment by bruceg** [comment]
> > What about using 32-bit numbers
> 
> That's an interesting idea. I hadn't really considered it.
> 
> One issue with this could be that JSON only supports _signed_ integers, which would mean on a 32-bit machine you can't represent the entire range of IPv4 addresses,

This wouldn't need to necessarily be representable in JSON — it would be just stored in our internal `Value` type, which uses an explicit `i64` for integers, so this is fine.

> I don't quite follow your question. I believe the provided examples answer your question, don't they?

The examples all show 5 or 17-number arrays. However, above was written that addresses could be a 4, 5, 16, or 17 number array, depending on the presence of a routing mask:

> When passing in `[number]` it either has to contain 4 or 5 8-bit integers (with, or without routing prefix) for Ipv4 addresses, or 16 (or 17) for Ipv6 addresses.

**Comment by JeanMertz** [comment]
> This wouldn't need to necessarily be representable in JSON

That's not actually true. If you do `.foo = parse_ip()`, leave that field as is, and then produce a log line as JSON, you would end up with the value being present in the final JSON output.

> The examples all show 5 or 17-number arrays. However, above was written that addresses could be a 4, 5, 16, or 17 number array, depending on the presence of a routing mask:

I must be missing a key piece of your question (might just be a language-barrier thing) as I'm still unsure what's unclear about what I wrote.

Perhaps this will clear things up: all functions that return `[number]`, return 5 or 17 numbers in the array, so they always include the routing prefix. If the user did not provide a routing prefix, it will default to `32` or `128` and will be included in the array returned by the functions.

Then, when the user wants to convert those numbers back to a string using `format_ip`, they have to manually define whether they want the routing prefix to be included (using the CIDR notation) or not, using the `cidr` flag.

**Comment by binarylogic** [comment]
@JeanMertz are you clear on how to proceed here or do we need to do more with the spec?

**Comment by JeanMertz** [comment]
Yeah, I think, given the feedback, that I'm going to move forward with a less expansive proposal, that prevents the use of arithmetic, but should get us the minimal required features:

* `ip_to_ipv6(value = string) -> string`
* `ipv6_to_ip(value = string) -> string`
* `ip_cidr_contains(value = string, cidr = string) -> bool`

We can iterate on this once the first batch of functions are in, and since we won't ship this as a stable transform just yet, we can make backward breaking changes in the coming weeks if we decide to change the API to work with IPs.
