### ISSUE TITLE
ES error reporting should be better

### ISSUE THREAD

**Issue by lukesteensen** [timberio/vector#3789]
As reported on [discord](https://discordapp.com/channels/742820443487993987/746070591097798688/753329583423619163), we don't do a great job surfacing certain errors in the ES sink.

We emit a [warning log](https://github.com/timberio/vector/blob/50a9c3af6779b887f9e72a313f7caee4c0d3c41c/src/sinks/elasticsearch.rs#L333-L338) directly when some messages in a request fail, and we also emit a more generic [error log](https://github.com/timberio/vector/blob/50a9c3af6779b887f9e72a313f7caee4c0d3c41c/src/sinks/util/retries.rs#L111) of the same error. The more specific warning log is rate limited while the error log is not, which can be confusing.

The simplest improvement here would be to consolidate these two log messages into one that provides both the high-level context (we are not retrying the request) and the details (ES error type and reason). In general, we should look for places like this where we're logging twice and try to ensure that it's clear where that logging should happen and that it has all the relevant information.

**Comment by spencergilbert** [comment]
```
[2020-09-11T01:41:58,886][WARN ][logstash.outputs.elasticsearch][main][c10c4ad48dfff1ddbb0262e94c037fa66077b42b3b88903e10b9c358addc61e9] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>"5f5ad5e56b4bbba1548f4ac3b8d2e6f139141d21", :_index=>"logstash-index", :routing=>nil, :_type=>"_doc"}, #<LogStash::Event:0x51300d7b>], :response=>{"index"=>{"_index"=>"logstash-index", "_type"=>"_doc", "_id"=>"5f5ad5e56b4bbba1548f4ac3b8d2e6f139141d21", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse field [json.point.status] of type [long] in document with id '5f5ad5e56b4bbba1548f4ac3b8d2e6f139141d21'. Preview of field's value: 'xxxxxx'", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"For input string: \"xxxxxx\""}}}}}
```
This is a common WARN log we get from logstash today, sanitized somewhat. The amount of information that can be surfaced to the user obviously depends on what details vector gets back from the indexing request. I can't say I'm familiar with what that looks like, nor have I encountered many other errors between vector and ES - but I'll keep an eye on this as I continue to do testing.

**Comment by spencergilbert** [comment]
An example of where the logs could be more user friendly:

```
Sep 15 21:21:28.893  WARN sink{name=elasticsearch type=elasticsearch}:request{request_id=91}: vector::sinks::elasticsearch: ElasticSearch error response err_type=mapper_parsing_exception reason=Could not dynamically add mapping for field [log.level]. Existing mapping for [log] must be of type object but found [text]. rate_limit_secs=30
```

I'm having a hard time figuring out what exactly this log contains/where it's coming from. A dead letter queue has also been mentioned and could solve this specific problem for me as well though

**Comment by juchiast** [comment]
@spencergilbert PR #3861 only combine `warn!` and `error!` into one, so it won't help with the mentioned issue.

What do you think about a Vector source where all dropped request will go to? This have the same functionality as a dead letter queue and could help you.

**Comment by spencergilbert** [comment]
> What do you think about a Vector source where all dropped request will go to? This have the same functionality as a dead letter queue and could help you.

@juchiast I think a dead letter queue `source` would be a great add, definitely would help resolve the issue I'm trying to solve and be more widely useful other Vector users. :+1:
