### ISSUE TITLE
Ensure that log events are flattened before sending to Honeycomb

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3792]
https://github.com/timberio/vector/issues/3779#issuecomment-689879847 pointed out that Honeycomb cannot take nested log data. I want to double-check that we are flattening events before sending them off in the `honeycomp` sink. If not, we should flatten the events to ensure they are not rejected.

Note, #3752 is covering this same functionality in the remap syntax.

**Comment by FungusHumungus** [comment]
Yup, from what I can see the Honeycomb is flattening the data just fine.

I can send this through Vector:

```json
{"grandparent": {"parent": {"child": "icecream"}, "parent2": "hello"}}
```

And it appears in Honeycomb as follows:

![image](https://user-images.githubusercontent.com/192679/93387774-a8755780-f861-11ea-8bd1-6b3e28cd2cce.png)

Dumping the JSON being sent by the sink indicates this:

```
Object({"data": Object({"grandparent.parent.child": String("icecream"), "grandparent.parent2": String("hello"), "host": String("127.0.0.1"), "source_type": String("socket")}), "timestamp": String("2020-09-16T20:26:41.596641795Z")})
```


Similary with arrays:

```json
{"field": [1,[2,3,[4]]]}
```

![image](https://user-images.githubusercontent.com/192679/93388060-0bff8500-f862-11ea-9760-aa23e57a0af2.png)

**Comment by binarylogic** [comment]
Perfect!
