### ISSUE TITLE
Support custom path for Prometheus metrics

### ISSUE THREAD

**Issue by langecode** [timberio/vector#3800]
### Current Vector Version
```
0.10.0
```

### Use-cases

Currently the Prometheus source assumes Prometheus metrics to always be exposed on the given endpoint under a path `metrics`. While this is a good default it might not be the case - for instance to scrape the `federate` endpoint exposed by Prometheus itself it is necessary to be able to configure the URL.

### Attempted Solutions

One workaround would be to put a reverse proxy (e.g., nginx) in between Vector and the endpoint being scraped - however this is unnecessary complexity if the URL is fully configurable.

### Proposal

Add an extra configuration parameter to the Prometheus source allowing for configuring the path.

**Comment by jamtur01** [comment]
+1 - additional option is the right route. Thanks - I so rarely think about the path so this is a good catch.

**Comment by jamtur01** [comment]
Linked to #3801
