### ISSUE TITLE
add_fields transform: Don't error if fields not overwritten when overwrite = false

### ISSUE THREAD

**Issue by Hoverbear** [timberio/vector#3803]
https://github.com/timberio/vector/blob/439a9cfdb48d976f19a0d2e5b84fc268752d93ba/src/internal_events/add_fields.rs#L71

This should be a `trace` call.

**Comment by spencergilbert** [comment]
I'm getting the following logs when using an add_field _with overwrite = true_
```
Sep 11 16:50:22.444 ERROR transform{name=add_fields type=add_fields}: vector::internal_events::add_fields: Field overwritten. self.field=host rate_limit_secs=30
Sep 11 16:50:22.444 ERROR transform{name=add_fields type=add_fields}: vector::internal_events::add_fields: "Field overwritten." is being rate limited. rate_limit_secs=5
Sep 11 16:50:52.447 ERROR transform{name=add_fields type=add_fields}: vector::internal_events::add_fields: 845 "Field overwritten." events were rate limited. rate_limit_secs=5
```

This seems, related but not exactly the same - should I open another issue for the "successful overwrite ERROR log"

**Comment by Hoverbear** [comment]
I think this can be joined

**Comment by spencergilbert** [comment]
Awesome - this _looks_ like a pretty innocuous change @Hoverbear, if there aren't any gotcha's I'm missing I'd be happy to look art replacing `error!` with `trace!`

**Comment by Hoverbear** [comment]
@spencergilbert  So `add_fields` has an `overwrite` flag we need to be mindful of.

https://github.com/timberio/vector/blob/ecbc91e86e3947d9b99e21d44a3a888e2908b303/src/transforms/add_fields.rs#L24

Which we need for the context in:

https://github.com/timberio/vector/blob/850a8bc9e1999e3cfc352d69deea10b1bcdd6489/src/internal_events/add_fields.rs#L53-L73

I think the best way to do that is to add a new field to them called `overwrite` (a bool), and then we can switch on that.

**Comment by Hoverbear** [comment]
@spencergilbert Was this something you wanted to tackle or shall I fix it up? :)

**Comment by spencergilbert** [comment]
@Hoverbear I think I can take my very beginner swing at this tonight/over the weekend

**Comment by Hoverbear** [comment]
@spencergilbert Gosh thank you. ☺️

**Comment by spencergilbert** [comment]
Failed to document... @Hoverbear and I discussed proper level and thought DEBUG might be a preferred level compared to TRACE
