### ISSUE TITLE
Add configurable ports for k8s pods

### ISSUE THREAD

**Issue by spencergilbert** [timberio/vector#3808]
### Current Vector Version

```
vector 0.11.0 (g50a9c3a x86_64-unknown-linux-musl 2020-09-10)
```

Chart version: vector-0.11.0-nightly-2020-09-10

### Use-cases

When utilizing the `prometheus` sink (my current use case of exposing `internal_metrics`) you'd need to expose a port to allow for the scraping of metrics. 

### Attempted Solutions

Hand editing of the helm templates

### Proposal

Allow users to pass a port in with the `values.yaml` file (either just the port number or entire spec) to expose the metrics endpoint

### References

N/A

_Note: I'll likely have a PR for this soon as I'll need to implement it for my current use_

**Comment by MOZGIII** [comment]
Hey @spencergilbert, thx for creating this issue! This is definitely something we'd want to add.

FYI, specifying ports in containers is not really necessary. From the https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#container-v1-core:

> List of ports to expose from the container. Exposing a port here gives the system additional information about the network connections a container uses, but is **primarily informational. Not specifying a port here DOES NOT prevent that port from being exposed. Any port which is listening on the default "0.0.0.0" address inside a container will be accessible from the network.** Cannot be updated.

**Comment by MOZGIII** [comment]
Related: https://github.com/timberio/vector/issues/3799

**Comment by spencergilbert** [comment]
What? TIL - didn't know that about the ports. I was planning on setting up a ServiceMonitor as well which could knock out #3799

**Comment by MOZGIII** [comment]
I've submitted https://github.com/timberio/vector/pull/4835. I'd be very interested in the feedback from people subscribed to this issue. Does the change proposed in this PR fit your needs? Please tell me if this is sufficient.
