### ISSUE TITLE
Support for multiple multiline transform not only file source

### ISSUE THREAD

**Issue by szibis** [timberio/vector#3817]
### Use-case

The real feature to use multiline in microservices platforms is to use many multiline on many types of logs from many applications. Sometimes our in many cases it is hard to know which language this app is and we should have the ability to match many multiline types on the same log to find the best option at scale.

Right now only file source support multiline as far I can see.

### Attempted Solutions

Current configuration support only one multiline per one file source.

### Proposal

Maybe the multiline feature should be moved from the file source into the transform part as a universal multiline parsing feature and this could be executed many times in the pipeline and used with multiple sources.

And if we have many for example events from the Syslog source we can use a similar feature - always there is a problem with a guarantee of sequence but this could be extended by more adding more options to recognize merge in specified time window.

This could work similarly to log2metrics when we aggregate based on the time window of events.

Right now I can't imagine a proper solution or definition for this in space of file source

**Comment by binarylogic** [comment]
@szibis thanks for this! I'm closing thins in favor of #4258 since we believe this will solve the problem.
