### ISSUE TITLE
Consistent encoding

### ISSUE THREAD

**Issue by lukesteensen** [timberio/vector#383]
How records are encoded by a sink shouldn't vary for a given configuration unless users explicitly opt in to that behavior (i.e. configure an encoder with dynamic behavior).

To accomplish this, we should move the explicit/implicit field tracking from transform implementations up into their type signatures. This will require extending the type system to propagate this information, and probably also adjusting our config implementations to be able to incorporate type system information when determining defaults, etc.

**Comment by binarylogic** [comment]
I believe this is no longer relevant. Please reopen if I am wrong.
