### ISSUE TITLE
Fully remove `docker-compose.yml`

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3835]
If I understand correctly, we are working to simplify our environment by shifting logic into the Makefile and away from `scripts/*` and `docker-compose.yml`. We still have a Makefile command called `RUN` that executes a specified `docker-compose.yml` job. We should remove this in favor of using `CONTAINER_TOOL` directly in the Makefile.

**Comment by jamtur01** [comment]
Yes, that's my plan. The build jobs are quite complex though and I need to do a bit of refactoring to achieve it.
