### ISSUE TITLE
Ternary operators for the remap syntax

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3837]
I am proposing that we support ternary operators for the remap syntax. This will help with inline assignment as well as the upcoming support for template strings (#3836).

## Example

```
.level = .status >= 500 ? "error" : "info"
```

or this, which might already be done:

```
.level = if (.status >= 500) { "error" } else { "info" }
```

If the second example is done, let's close this.

**Comment by JeanMertz** [comment]
Remap is now an expression-based language. The if-statement returns the last expression of whatever arm matches (if/else if/else).

I'll close this as the second example now works:

```
.level = if .status >= 500 { "error" } else { "info" }
```
