### ISSUE TITLE
Ensure all remap function optional arguments are named

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3851]
This is a follow up take to https://github.com/timberio/vector/issues/3838#issuecomment-691525665. We need to make sure all remap functions implement this named argument style. Here are the ones I'm aware of, but I may be missing some:

- [ ] `to_*(arg, default=val)`

**Comment by JeanMertz** [comment]
@binarylogic I already created a draft PR yesterday at https://github.com/timberio/vector/pull/3927.

To avoid confusion (and duplicate work), I've unassigned @FungusHumungus and re-assigned myself again.
