### ISSUE TITLE
Internal Vector community support guidelines

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3879]
As Vector's community grows, we should outline internal community guidelines to clarify behavior. Community is very important to Vector and these guidelines should maximize its effect. Specifically, it should help:

1. Align expectations both internally and externally.
2. Direct users to the best channel to get quality support.
3. Assuage any anxiety about what's expected internally, promoting fairness and transparency.

This should cover things like:

1. Response expectations.
2. Displacing current sprint work -- Community work should always be represented through issues.
3. After hours -- No one is required to interact with the community after hours.
4. Canned/example responses for common scenarios. (can't get it to immediately, can't solve the problem, etc).
5. Directing users to open Github issues as much as possible.

I'm sure there are other best practices I'm leaving out, as well as prior art for this.

**Comment by jamtur01** [comment]
Internal docs:

https://www.notion.so/timber/Vector-Support-Guidelines-d22dde3113974850bb1fb9d8f4a14f98

Some external updates in #4832.
