### ISSUE TITLE
Ensure CI is consistently green

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3880]
Flaky tests and other CI checks routinely fail. This adds friction to the PR workflow. We should:

- [ ] Inventory all flaky test issues and ensure they are accurate.
- [ ] Remove flaky tests and open issues for fixing them later.

**Comment by JeanMertz** [comment]
We still have a policy of creating issues for unknown flaky tests, and linking them to https://github.com/timberio/vector/issues/2978. There have been a few added in recent days.
