### ISSUE TITLE
new `sha2` remap function

### ISSUE THREAD

**Issue by JeanMertz** [timberio/vector#3883]
The `sha2` remap function hashes the provided argument with the [SHA2](https://en.wikipedia.org/wiki/SHA-2) algorithm.

It takes an optional second argument to specify the [algorithm variant](https://en.wikipedia.org/wiki/SHA-2#Comparison_of_SHA_functions) used to perform the hashing, defaulting to the `SHA-512` variant.

This will become a _named argument_ `variant` once #3851 lands.

The function returns an error for unknown variants.

## Examples

For all examples assume the following event:

```js
{
  "message": "Hello world",
  "remote_addr": "54.23.22.123"
}
```

### Path

```
.fingerprint = sha2(.message)
```

### String literal, with custom algorithm variant

```
.fingerprint = sha2("my string", "SHA-384")
```

### Operators

```
.fingerprint = sha2(.message + .remote_addr)
```

**Comment by binarylogic** [comment]
@JeanMertz would someone pass this variant?

```
.fingerprint = sha2("my string", "SHA-384")
```
