### ISSUE TITLE
make `blackhole` sink's `print_amount` field optional

### ISSUE THREAD

**Issue by JeanMertz** [timberio/vector#3886]
While testing out a local Vector configuration in https://github.com/timberio/vector/issues/230#issuecomment-692727213, I ran into https://github.com/timberio/vector/issues/3885.

That got me thinking, I wonder if we should consider making `print_amount` an optional field. Its purpose is orthogonal to what the actual sink is supposed to do, and given that this sink seems like a good fit for quickly testing something, the less configuration it requires, the better.

**Comment by lukesteensen** [comment]
I would really like to get rid of this option entirely. I don't find it useful at all. I think we could have the sink periodically emit how many messages it has received (though even that could be done better with a reduce transform?) or some other form of feedback, but I'm not sure what would be most useful.

**Comment by JeanMertz** [comment]
I actually agree with you @lukesteensen. One reason I've seen people wanting this is so that their tooling doesn't consider Vector to be stuck if it no longer produces output.

I would say for that we have a much better solution now, the `internal_metrics` source.

Given that, I think we should just purge this field, _and_ the output this sink generates, entirely.
