### ISSUE TITLE
Coercer transform triggers errors with dotted keys 

### ISSUE THREAD

**Issue by awangc** [timberio/vector#3891]
### Vector Version

```
vector 0.10.0 (g0f0311a x86_64-unknown-linux-gnu 2020-07-22)
```

### Vector Configuration File

```toml
[sources.http]
  type = "http"
  address = "0.0.0.0:8081"
  encoding = "json"

[transforms.coerce]
  type = "coercer"
  inputs = ["http"]
  types.parent.child = "int"    # example from https://vector.dev/docs/reference/transforms/coercer/

[sinks.out]
  type = "console"
  inputs = ["coerce"]
  target = "stdout"
  encoding.codec = "json"
```

### Debug Output

```
$ RUST_BACKTRACE=full vector -vvv -c ./vector.toml
Sep 15 18:54:20.365  INFO vector: Log level "trace" is enabled.
Sep 15 18:54:20.370  INFO vector: Loading configs. path=["vector.toml"]
Sep 15 18:54:20.370 TRACE vector: Parsing config. path="vector.toml"
Sep 15 18:54:20.379 ERROR vector: Configuration error: "vector.toml": invalid type: map, expected a string for key `transforms.coerce`
```

### Expected Behavior

Vector should have started
### Actual Behavior

Vector stopped with an ERROR

```
Sep 15 18:54:20.379 ERROR vector: Configuration error: "vector.toml": invalid type: map, expected a string for key `transforms.coerce`
```

**Comment by jamtur01** [comment]
Perhaps overlap/related to #3889?

**Comment by lukesteensen** [comment]
This works if you change `types.parent.child` to `types."parent.child"`.

It's a little confusing, but the quotes let us differentiate between the structure of the config, where the key is a single field, and the structure of the key itself, which can have multiple components.

**Comment by lukesteensen** [comment]
I'm trying to see where in the docs pipeline we're failing to add those quotes but not having much success. /cc @binarylogic

**Comment by binarylogic** [comment]
Yeah, I couldn't find anything. Again, I think the new remap transform outlined in [the RFC](https://github.com/timberio/vector/blob/master/rfcs/2020-07-21-2744-remap-syntax.md) will make this much more straight-forward.

Thanks for reporting @awangc, I'm closing given the above comments.
