### ISSUE TITLE
Make `namespace` a first class field on metrics

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#3896]
Implementation issue for https://github.com/timberio/vector/pull/3686

Also see https://github.com/timberio/vector/pull/4437#issue-499451433

**Comment by ktff** [comment]
Plan of action:

- [ ] Introduce `namespace` to `struct Metric` and  proto `Metric`.

- [ ] Update sinks to combine namespace to name. 

- [ ] Update transforms to expose namespace and to not merge namespaces with names. Possible breaking change.  

- [ ] Update sources to not merge namespaces with names. Breaking change.

**Comment by ktff** [comment]
Regarding metric sinks I propose that we:
* Add required `default_namespace` option, mentioned in the rfc, to those sinks that need namespace to be defined.
* Remove optional `namespace` option from all sinks.

Having both options in the sinks seems a bit too much when required `default_namespace` option for, `prometheus`, `aws_cloudwatch_metrics`, and `sematext_metrics` sinks, is all that is needed. The rest is covered with `add_tags`/`remove_tags` transforms.

Both points are a breaking change.  

### Alternative
Have both options. This would still be a breaking change.

cc. @jszwedko @binarylogic

**Comment by jamtur01** [comment]
I am +1 the proposal. The alternatives seem confusing to the end user.

**Comment by jszwedko** [comment]
Agreed, I like `default_namespace`.
