### ISSUE TITLE
Process logs - Parse common formats

### ISSUE THREAD

**Issue by vector-vic** [timberio/vector#3904]
This project is concerned with improvin the Vector log parsing experience, something that still has room for improvement.

# User Needs

As a user, I need the...

1. ABILITY to parse a variety of well known formats,  so that I can quickly parse logs across my entire organization.

2. ABILITY to delegate parsing for known formats, so that I parse my logs reliably and receive upstream improvements without having to manage it myself.

3. ABILITY to auto-detect known formats, so that I Vector can automatically adjust to format changes without my intervention.

**Comment by vector-vic** [comment]
Link to feature: https://timber.productboard.com/feature-board/planning/features/5154378

**Comment by binarylogic** [comment]
Closing in favor of #3913
