### ISSUE TITLE
Resolve concurrency issues

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#391]
When I bump the router instance to a `c5.4xlarge` (16 vCPUs) we see a large performance decrease to 15mib/s that gets worse with more concurrency. This is compared to a `c5.large` (2 vCPUs) where we were pushing 100mib/s.

Here are some stats with different `-t` configurations:

* `-t 1` = `70.0 MiB/s`
* `-t 2` = `90.8 MiB/s`
* `-t 4` = `127.9 MiB/s`
* `-t 8` = `61.6 MiB/s`
* `-t 16` = `13.1 MiB/s`

The detailed profiling data is here: https://gist.github.com/binarylogic/d912d0fafe9ea423aff4710809735516

This is on a `c5.4xlarge` with 10 producers sending data over TCP as fast as possible (edited)

**Comment by MOZGIII** [comment]
I assume it's not currently possible to pass `-t` via test harness?

**Comment by binarylogic** [comment]
No, but we should create a `concurrency_performance` test that simply runs vector with that variable set.

You could also make this part of the [test case configuration](https://github.com/timberio/vector-test-harness/blob/master/cases/tcp_to_tcp_performance/configurations/default/ansible.yml). Although, this test should be running Vector without a thread limit specified. My hope is that we can remove the limitation [here](https://github.com/timberio/vector/blob/0d9c2c98b8dfcb24ee08c0d0e536238208fe44dd/src/main.rs#L270).

**Comment by MOZGIII** [comment]
Yeah, that's something I'd have to implement at the test harness myself, i.e. it's not yet supported in any way? I'm specifically referring to passing cli args and/or env vars to `vector`.

**Comment by MOZGIII** [comment]
What if I just create a `configuration` that runs tests with a bigger VM, like at `c5.2xlarge` (8 cores) instead of `c5.large` (2 cores)?
