### ISSUE TITLE
Sink data - Auto-concurrency

### ISSUE THREAD

**Issue by vector-vic** [timberio/vector#3912]
This epic deals with optimally transmitting data to downstream services. This means taking full advantage of available bandwidth while taking care not to overwhelm the service.

# User Needs

As a user, I need the...

1. ABILITY to automatically adjust throughput, so that I don't overwhelm downstream services when I scale up the number of Vector instances.

2. ABILITY to automatically adjust throughput, so that I don't overwhelm downstream services when data volume increases substantially.

3. ABILITY to protect against large volume spikes, so that I don't overwhelm downstream services when data volume increase substantially.

4. ABILITY to automatically adjust throughput, so that I don't artificillay limit throughput for downstream services.

**Comment by vector-vic** [comment]
Link to feature: https://timber.productboard.com/feature-board/planning/features/5156255

**Comment by binarylogic** [comment]
Nice work on this feature @bruceg!
