### ISSUE TITLE
Sink data - Auto-concurrency tuning

### ISSUE THREAD

**Issue by vector-vic** [timberio/vector#3959]
#3192 introduced an AIMD based autoconcurrency layer to our outgoing HTTP requests. This performed well under our test scenarios, but we think there is still room for improvment. This epic represents those efforts.

# User needs

I as a user, I need the...

1. Ability to adjust auto concurrency algorithm variables, so that I can optimize my outgoing data throughput.

2. Ability to change auto concurrency algorithm (gradient), so that I can optimize my outgoing data throughput.

**Comment by vector-vic** [comment]
Link to feature: https://timber.productboard.com/feature-board/planning/features/5309192

**Comment by binarylogic** [comment]
Nice work on closing this @bruceg
