### ISSUE TITLE
Debt - Transition off of Tokio 0.1

### ISSUE THREAD

**Issue by vector-vic** [timberio/vector#3961]
This is the big one. We need to keep up with the ecosystem here to avoid becoming blocked on upgrading important dependencies.

# Goal

Our goal should be to set ourselves up for easy, incremental change.  Currently, we have some futures 0.3 code that we map back to futures 0.1  via the compat layer. Success here means flipping that around. We'll  still have plenty of futures 0.1 code, but it should be compat-mapped  into futures 0.3, which is then the default for all new code.

Actually moving totally to futures 0.3 will be a long, incremental  journey. This piece of work should lay the foundation and plot a rough  course.

# Plan of Attack

1. Investigate and clear potential blockers ([#1695](https://github.com/timberio/vector/issues/1695), [#1696](https://github.com/timberio/vector/issues/1696))

2. Make the minimal change onto tokio-compat as described in [#1142](https://github.com/timberio/vector/issues/1142)

3. Test heavily

4. Triage existing futures 0.1 code

Other related issues: [#1639](https://github.com/timberio/vector/issues/1639), [#716](https://github.com/timberio/vector/issues/716), [#990](https://github.com/timberio/vector/issues/990)

**Comment by vector-vic** [comment]
Link to feature: https://timber.productboard.com/feature-board/planning/features/5156388

**Comment by binarylogic** [comment]
Nice work @kirillt! Really awesome to see this completed.
