### ISSUE TITLE
Debt - Improve release process

### ISSUE THREAD

**Issue by vector-vic** [timberio/vector#3964]
This epic deals with updating and simplifying our dev and CI environments.

# Motivation

Our development and CI environments have grown to a level of complexity that makes it very difficult to maintain. Not only does this make it difficult to contribute to the project, but it makes it difficult to release versions of Vector.

<p></p>

More detail is covered in <https://github.com/timberio/vector/issues/2645>

**Comment by vector-vic** [comment]
Link to feature: https://timber.productboard.com/feature-board/planning/features/5156475

**Comment by binarylogic** [comment]
Nice work @Hoverbear @jamtur01 on finishing this.
