### ISSUE TITLE
Automatic concurrency has bad behavior with explicit backpressure

### ISSUE THREAD

**Issue by bruceg** [timberio/vector#3998]
In the presence of explicit backpressure (HTTP 429 and 503 responses), the behavior of the automatic concurrency limiter has wildly variable behavior, leading to very sub-optimal performance. For example, here are several sequential runs of producing HTTP 429 responses above a request rate of 10 requests per second. The optimal request rate would thus be hovering around 10, but that's not even close to what happens:
![plot-rate](https://user-images.githubusercontent.com/477552/93491762-50713c00-f8c7-11ea-8bbc-8250442ee683.png)
![plot-rate](https://user-images.githubusercontent.com/477552/93491944-80204400-f8c7-11ea-93fd-aa7c2a2d84e9.png)
![plot-rate](https://user-images.githubusercontent.com/477552/93491124-911c8580-f8c6-11ea-9da8-2a2b390379bf.png)
![plot-rate](https://user-images.githubusercontent.com/477552/93492098-acd45b80-f8c7-11ea-8d6a-b64b280d8499.png)
![plot-rate](https://user-images.githubusercontent.com/477552/93492269-db523680-f8c7-11ea-83ef-02bf26f5182f.png)
![plot-rate](https://user-images.githubusercontent.com/477552/93492764-67645e00-f8c8-11ea-9229-a469b0aa4af4.png)

**Comment by jszwedko** [comment]
@bruceg I like the request rate line you added. Was this using gnuplot? Do you have code you used for that?

**Comment by bruceg** [comment]
Yes, that was simply using the following:
`plot infile_rate using 1:2 with linespoints, infile_rate using 1:2 with lines smooth sbezier`
(bezier and sbezier should be equivalent for this data)

**Comment by bruceg** [comment]
Update from #4082 to split up the concerns:
This is currently also spiking up to the maximum rate limit as well:
![429_limit](https://user-images.githubusercontent.com/477552/94278684-5b9c1b80-ff08-11ea-9ba8-bfc388cbb6a0.png)
![503_limit](https://user-images.githubusercontent.com/477552/94278699-5f2fa280-ff08-11ea-9770-4dcdbf7bef75.png)

**Comment by bruceg** [comment]
I think this may be an artifact of the test environment. As configured in the HTTP 429 and 503 tests, the OK responses take ~202ms, while the backpressure messages take just ~2ms. While the concurrency never goes up for these backpressure requests, the fact that they return so fast means the retry mechanism, which is outside the concurrency mechanism, will keep hammering away until the server is ready. At a 2ms RTT, that amounts to 500 requests/sec when the concurrency is at the minimum of one.

Since this mechanism has no way of limiting the *rate* of requests, only how many are made at once, this doesn't seem to be something that can be fixed at this level. Additionally, the discrepancy between normal response time and backpressure response time is likely to be at least somewhat smaller in real life, this may not even be a large problem in real deployments.

As such, I suggest we close this until we have more experience with the behavior in real deployments.

**Comment by jszwedko** [comment]
> Additionally, the discrepancy between normal response time and backpressure response time is likely to be at least somewhat smaller in real life, this may not even be a large problem in real deployments.

I'm not sure if I necessarily agree with this statement. Gating API limits, in my experience, is usually done very early and sometimes even before the request makes it to the service that will process it (for example if an API gateway-type service is used). I don't think it'd be uncommon for successful responses to take much longer than ones that are rejected due to API limits.

> While the concurrency never goes up for these backpressure requests, the fact that they return so fast means the retry mechanism, which is outside the concurrency mechanism, will keep hammering away until the server is ready. 

I think the retry mechanism should probably use its own back-off, independent of the auto concurrency control, to avoid this situation (specifically with 429 responses). I've commonly seen an exponential back-off with some jitter. It could even take into consideration `Retry-After` headers.

In essence, I agree that the auto concurrency layer is behaving properly, but that we should open an issue for back-off in the retry logic. I'll do that.
