### ISSUE TITLE
Improve failed template rendering log message

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3999]
When rendering a template string fails, users get an error, but it is not very helpful. For example, in the `add_fields` transform a user could do:

```toml
fields.new_field = "{{ hostgroup }}:{{ hostname }}:{{ env }}"
```

And if one of the fields is missing they'll get:

```
vector::transforms::add_fields: Failed to render templated value at key `new_field`, dropping.
```

We should note which field is missing in the above message.

This should also be covered in #3924.

**Comment by ktff** [comment]
Already done in #6242
