### ISSUE TITLE
Not all the integration tests are running

### ISSUE THREAD

**Issue by bruceg** [timberio/vector#4007]
As evidenced by the build failures in #4006 and the lack of corresponding failures in CI, not all of the integration tests are running. In particular, the `test-integration-gcp` test is not running the pubsub and cloud_storage tests, which are gated by the `gcp-pubsub-integration-tests` and `gcp-cloud-storage-integration-tests` flags, respectively. Also, the `humio-integration-tests` suite is not being exercised, as it fails to build on master.

**Comment by jamtur01** [comment]
Yes - the humio job is missing at least. :( I'll add it back.
