### ISSUE TITLE
Ability to specify quantiles in relevant sinks

### ISSUE THREAD

**Issue by szibis** [timberio/vector#4016]
As log2metrrics support count, sum, gauge, set, and histogram we need to have there or on the separate transformation distribution support which will calculate percentiles from defined fields with a defined list of percentiles from logs to generate metrics on them which we can then send in proper format for example into Datadog sink.

**Comment by ktff** [comment]
@szibis do you need some specific percentiles, or are the ones defined in DataDog's distribution metric enough?

#3726 added support for DataDog's distribution metric in `log_to_metric`, although it's not yet documented. Such metric will in the `datadog metric` sink, and some others, compute the percentiles and send them accordingly. Tracking issue for this is #2603

**Comment by szibis** [comment]
> @szibis do you need some specific percentiles, or are the ones defined in DataDog's distribution metric enough?
> 
> #3726 added support for DataDog's distribution metric in `log_to_metric`, although it's not yet documented. Such metric will in the `datadog metric` sink, and some others, compute the percentiles and send them accordingly. Tracking issue for this is #2603

That's great. 
For me, the best option is to have the ability to override the default values and put own list of percentiles to calculate.

**Comment by binarylogic** [comment]
@ktff @szibis would percentiles be specified within the `log_to_metric` transform or within each sink?

**Comment by ktff** [comment]
To correct myself
> Such metric will in the `datadog metric` sink, and some others, compute the percentiles and send them accordingly.

`datadog metric` sink will not do such thing, it will send the raw data points to DataDog as its `distribution` metric.  #3130
@szibis does this change something for you?

With that in mind, I think specifying percentiles should be done at the sinks since which percentiles to choose depends more on where are they being sent then from where they came from.

**Comment by ktff** [comment]
Sinks to enhance with option to specify percentiles:

- [ ] `prometheus`

- [ ] `influxdb_metrics`
