### ISSUE TITLE
Allow running "vector validate" over Helm-managed vector config

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#4040]
We have a `vector validate` command that's very useful during the development of the config file.

On the other hand, we have a Helm chart, that can manage the config such that users only have to fill in the relevant parts of the config. The resulting config is generated from templated and either passed directly into the Kubernetes API, or exposed as a `ConfigMap` YAML file. This makes it very difficult to apply `vector validate` during the development phase of the config.

Investigate ways to allow running the `vector validate` when using the Helm chart, to allow checking the config validity before deployment. For when people run it locally, or use at CI.

Related: #3828.

**Comment by MOZGIII** [comment]
Currently, the most promising way of doing this is https://helm.sh/docs/topics/charts_hooks/, to be used similar to https://helm.sh/docs/topics/chart_tests/.

**Comment by spencergilbert** [comment]
Issue moved to [timberio/helm-charts #14](https://github.com/timberio/helm-charts/issues/14) via [**ZenHub**](https://www.zenhub.com/)
