### ISSUE TITLE
Switch metadata from TOML+ERB

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#4041]
The Vector `.meta` directory has evolved over time in a way that is no longer easy for humans to maintain. Given that we're about to embark on a number of changes for upcoming website efforts, we need to rethink how we're managing this data given the new requirements.

## Requirements

1. This data should be easy for a human to manage.
2. This data should be version controlled, like code, so that we can couple it with code changes.
3. It should be easy to convert to JSON.
4. It should be easy to validate.
5. Bonus points if we can easily generate a Typescript interface.

## Proposal

I'm proposing that we migrate the TOML data to [jsonnet](https://jsonnet.org/). It solves all of the requirements above, and provides much better facilities to manage this data. Such as variables, conditions, arithmetic, functions, and imports. Alternatively, we could consider [cue](https://cuelang.org/).

**Comment by MOZGIII** [comment]
`jsonnet` has some issues with readability (it inherits some from JSON, and adds it's own atop of it).

Also, I really like how you get autocompletion at VS Code for JSONs and YAMLs if the schema is properly defined and the editor knows how to pick it up.

TOML data model is a bit different from the JSON and YAML, and I find that people are much more used to JSON and YAML, and most of the time expect to be able to use TOML the same way.

JSON doesn't allow comments, and it's a probem for a use case like ours, so if we like raw JSON we might want to go with at least CSON instead.


All that said, I'm not opposed to `jsonnet`, but it's not perfect. We might want to actually try a couple of things and see what works best.

It would make a lot of sense if some parts could be implemented in, for instance, YAML (the ones that contain the most user-written data), and some - structural ones, that bring everything together - in `jsonnet`.
