### ISSUE TITLE
New Sources: DataDog Agent Logs and Metrics

### ISSUE THREAD

**Issue by khionu** [timberio/vector#4052]
### Current Vector version

```
vector 0.10.0 (g0f0311a x86_64-unknown-linux-gnu 2020-07-22)
```

### Use-cases

DataDog is a major observability platform. People who are using DataDog and want to start using Vector will need to be able to transition. Being able to continue using [the DataDog Agent](https://docs.datadoghq.com/agent/) as a point of data collection will ease the burden of transition.

### Proposal

Vector already has two DataDog Sinks for Logs and Metrics respectively. It should be little effort to establish an endpoint for the DataDog Agent to send to. Users can then immediately pipe the DataDog Agent Sources to the respective DataDog Sinks.

### References

- https://docs.datadoghq.com/agent/
- https://github.com/DataDog/datadog-agent
- https://github.com/DataDog/agent-payload

**Comment by khionu** [comment]
Edit: there would need to be two sources, as there are two sinks. Fixed the issue to address that.

**Comment by zsherman** [comment]
@prognant can we close this?

**Comment by prognant** [comment]
Unfortunately no, we have a source for datadog logs, but not -yet- for metrics.

**Comment by binarylogic** [comment]
Closing in favor of #3994
