### ISSUE TITLE
Ability to specify histogram buckets in relevant sinks

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#4060]
This is a follow up to https://github.com/timberio/vector/issues/4016#issuecomment-696649084. We should support the ability to specify `buckets` in all relevant metrics sinks. Currently, we only do this in the `prometheus` sink, but I'm curious if we need to support others?

**Comment by ktff** [comment]
There is no other sinks that aggregate to buckets beside the current two prometheus sinks. 

While `influxdb_metrics` is aggregating distribution, it aggregates to quantiles which seems to be modeled by how [telegraf does it](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/statsd#measurements). This could be revisited in light of addition of `StatisticKind` which lets users to chose between histogram and quantiles. @binarylogic
