### ISSUE TITLE
Support specifying the environment in the LogDNA sink config

### ISSUE THREAD

**Issue by romatthe** [timberio/vector#4076]
As you can see in the [LogDNA API reference](https://docs.logdna.com/reference), it allows you to include an `env` field that can be used to specify the environment (staging, acceptance, production, etc.) from which an event originated.

Currently, the Vector configuration for the LogDNA sink does not seem to support this, and setting an `env` field to an event manually only includes it in the `meta` object.

Ideally, an `env` field that is set manually should be properly included in the LogDNA request body, and there should probably also be a `default_env` config option for events which do not include such a field, very similar to the current `default_app` option.

Considering that this is a pretty small change I can submit a quick PR for this if so desired.

**Comment by jamtur01** [comment]
Hi @romatthe we'd welcome a PR! Thanks.

**Comment by romatthe** [comment]
Thanks, PR submitted, should be enough hopefully.
