### ISSUE TITLE
Add metric labels for resources

### ISSUE THREAD

**Issue by ktff** [timberio/vector#4096]
### Use-cases
We have resources, like file handles and tcp connections, for which we would like to expose their state/state changes through metrics. That would enable for admin UI to have components mentioned in #3516 and #3518.

### Attempted Solutions
Directly exposing open time of a resource as a metric can introduce:
* complexities of needing to introduce additional timers to components to emit the metric in reliable fashion. This wasn't the case for `file` source in  #3583 since the PR was able to reuse internal timed loop, but this isn't the case for other components. 
* an issue of correlating multiple metrics to a single resource. 
* an issue of unreliable closing metrics which are needed to determine if the resource should still be listed as open. For example our `tcp` sink can close a connection in three ways, all having different behavior. One emits `tcp_connections_disconnected` metric, other `tcp_connection_shutdown`, and the third doesn't emit anything.

### Proposal
For resources like file handles, tcp connections, etc. we can emit opening metrics and closing metrics with labels :
* `state` - represents current state of the resource, `open` or `close`.
* `id` - a unique identifier of the resource. It can be file path, ip:port , uuid, etc.

These labels should be uniformly applied over all opening and closing metrics, and it should be ensured that all code paths are covered by such metrics.

This would enable for external systems, like admin UI, to track the lifetime of the resources.

Attack plan can be added after ironing this proposal out.

### Extensions
On top of this change we can extend `internal_metrics` source with options to track states of resources and emit 
* `gauge` with current open time
* ~~`timing`~~ `histogram` for how long was the resource opened

### References
This unifies conversation from multiple threads, and is a replacement for #3516 and #3518 issues, and would close PR #3583 without merging it.

@binarylogic @lukesteensen @MOZGIII @jszwedko

**Comment by MOZGIII** [comment]
Note that new metrics release removes the `timing` macro in favor of `histogram`, as it was just syntax sugar.

**Comment by binarylogic** [comment]
@ktff I've opened #4506 and #4505. I didn't realize how complicated this would be, therefore, let's start simple with a single `open_files` and `open_connections` gauges.

Closing in favor of those issues.
