### ISSUE TITLE
Collect Windows performance metrics

### ISSUE THREAD

**Issue by otisg** [timberio/vector#4099]
Vector runs on Windows, but it doesn't collect any Windows metrics.  It would be great if it collected core Windows metrics.

**Comment by jamtur01** [comment]
@otisg We're about release a host_metrics source for Unix and we've got plans to expand that to OSX and Windows.

**Comment by bruceg** [comment]
To be clear, the host metrics source will be cross-platform at release, with support for all three. See also #3587

**Comment by jamtur01** [comment]
Or you know what @bruceg said. :)

**Comment by jamtur01** [comment]
Closing in favor of #3587.

**Comment by otisg** [comment]
@jamtur01 and @bruceg thanks for the info!  Would you happen to have a rough ETA for OSX & Windows metrics support?

**Comment by jamtur01** [comment]
@otisg When this gets merged: https://github.com/timberio/vector/pull/4157. 👍 :)
