### ISSUE TITLE
Move topology warning to the warn level or update it's message

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#414]
```
ERROR vector::topology: Configuration warning: Transform "apache_common_parser" has no outputs
```

This should be logged on the `warn` level given its language or we should classify this as an error.

**Comment by cetanu** [comment]
What does this message mean, by the way?

As far as I can tell, there is no way to configure a transform with an output?

**Comment by lukesteensen** [comment]
Right, this would just mean that the transform is not listed in any other transform or sink's `inputs` array.
