### ISSUE TITLE
Create a guide for ingesting AWS CloudWatch Logs via AWS Kinesis Firehose

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#4153]
After #3566 is done, we should create a user guide and related assets (maybe Cloudformation template?) for forwarding CloudWatch Logs to Vector via the AWS Firehose.

**Comment by jamtur01** [comment]
@jszwedko Is this done?

**Comment by jszwedko** [comment]
I have a draft up at https://www.notion.so/timber/Ingesting-AWS-CloudWatch-Logs-with-Vector-and-AWS-Kinesis-Firehose-bfc6ffcd66224c47af69c60555411366 . I'd like to do another pass on it and then get one or two reviews.

**Comment by jamtur01** [comment]
@jszwedko Ping me when you're ready for reviews on the PR and I'll take a look.
