### ISSUE TITLE
Tutorial on deploying failed

### ISSUE THREAD

**Issue by jpds** [timberio/vector#4168]
The tutorial on:

https://vector.dev/guides/getting-started/deploying

Here's what went wrong:

1. Install vector with `.deb` package
1. Configure vector to send to "File"
1. `/var/log/vector` does not exist
1. Configuration files with:

```
Sep 27 22:03:04 debian systemd[1]: Started Vector.
Sep 27 22:03:04 debian vector[3084]: Sep 27 22:03:04.607  INFO vector: Log level "info" is enabled.
Sep 27 22:03:04 debian vector[3084]: Sep 27 22:03:04.610  INFO vector: Loading configs. path=["/etc/vector/vector.toml"]
Sep 27 22:03:04 debian vector[3084]: Sep 27 22:03:04.614  INFO vector: Vector is starting. version="0.10.0" git_version="v0.9.0-377-g0f0311a" released="Wed, 22 Jul 2020 19:45:24 +0000" arch="x86_64"
Sep 27 22:03:04 debian vector[3084]: Sep 27 22:03:04.621  INFO vector::topology: Running healthchecks.
Sep 27 22:03:04 debian vector[3084]: Sep 27 22:03:04.622  INFO vector::topology: Starting source "in"
Sep 27 22:03:04 debian vector[3084]: Sep 27 22:03:04.622  INFO vector::topology::builder: Healthcheck: Passed.
Sep 27 22:03:04 debian vector[3084]: Sep 27 22:03:04.622  INFO vector::topology: Starting sink "out"
Sep 27 22:03:04 debian vector[3084]: Sep 27 22:03:04.622  INFO source{name=in type=journald}: vector::sources::journald: Starting journald server.
Sep 27 22:03:04 debian vector[3084]: No journal files were opened due to insufficient permissions.
```

**Comment by jpds** [comment]
I found on https://vector.dev/docs/reference/sources/journald/ that the `vector` user needs to be part of a group.

Also, the configuration needs to be adjusted to have a `path` of `/var/log/vector/vector-%Y-%m-%d.log`.

**Comment by jamtur01** [comment]
Thanks! The group issue is fixed in our nightly builds https://cloudsmith.io/~timber/repos/vector-nightly/packages/. I'll take a look at the other issues.

**Comment by jamtur01** [comment]
@jpds Can you explain further about the /var/log/vector issue? Can you share the error output you're getting? I've installed the 0.11 nightly and don't have any issues. Thanks!

**Comment by jpds** [comment]
@jamtur01 The error I get is:

```
Sep 29 13:55:56.524 ERROR vector::sinks::file: Unable to open the file. path=b"vector-2020-09-29.log" error=Permission denied (os error 13)
```

**Comment by jpds** [comment]
I oddly get the same error if I install the nightly after installing the 0.10 release .deb.

**Comment by jamtur01** [comment]
The latest nightly won't have fixed the /var/log/ permissions issue. Only the journald issue.

**Comment by jpds** [comment]
Debian 10.6, running:

```
sudo dpkg -i vector-amd64.deb
sudo vim /etc/vector/vector.toml
# copy and paste "File" example from deploying
sudo systemctl restart vector
sudo systemctl status vector
```

**Comment by jamtur01** [comment]
Can you show me what's in `/etc/vector/vector.toml`? 

Is it:

```toml
[sources.my_source_id]
  # General
  type = "file" # required
  ignore_older = 86400 # optional, no default, seconds
  include = ["/var/log/nginx/*.log"] # required
  start_at_beginning = false # optional, default

  # Priority
  oldest_first = false # optional, default
```

**Comment by jpds** [comment]
@jamtur01 It is not, it is literally what's in the documentation for deploying:

![Screenshot_2020-10-02_11-48-24](https://user-images.githubusercontent.com/29158971/94916042-d71c4080-04a5-11eb-8651-a9f7ec00eaae.png)
