### ISSUE TITLE
log_to_metric configuration documentation does not show an inputs field

### ISSUE THREAD

**Issue by vamega** [timberio/vector#4177]
### Vector Version

N/A

### Vector Configuration File

N/A

### Debug Output

N/A

### Expected Behavior

The configuration shown at: https://vector.dev/docs/reference/transforms/log_to_metric/ should contain an `inputs` field.

### Actual Behavior

The `inputs` field is missing from the configuration.

### Example Data

N/A

### Additional Context

I was trying to understand if all transforms and sinks use the field inputs to represent a list of nodes/components that they are connected to.

I wasn't sure how to submit a PR to fix this. Looking at the repository I would guess that this is handled in the `meta/*.erb` files, but I couldn't identify how to fix it from there. The `ansi_stripper` documentation doesn't have a explict `inputs` field in it's erb file, yet I can see the `inputs` in the documentation.

### References

N/A. Maybe related to more general conversations I've seen about schemas for the configuration.

**Comment by jamtur01** [comment]
This is fixed in master but not in our released docs yet.

For interest - it's added via this partial:

```ruby
<%= render("_partials/fields/_component_options.toml", type: "transform", name: "log_to_metric") %>
```
