### ISSUE TITLE
New `either` remap function

### ISSUE THREAD

**Issue by JeanMertz** [timberio/vector#4180]
The `either` function resolves to the first argument, unless that one points to a non-existing path (potentially `null` would also fail to resolve, if we want), in which case it resolves to the second argument.

This can be used to provide **default** values to any other function or assignment.

## Example

```rust
// these are equal:
.foo = to_bool(either(.bar, false))
.foo = to_bool(either(value = .bar, or = false))

// this is how it's currently done:
.foo = to_bool(.bar, false)
.foo = to_bool(.bar, default = false)

// optionally skip null values:
.foo = to_bool(either(.bar, false, accept_null = false))
```

Basically, `either` allows you to always define a `default`, without us having to support such an optional argument for each individual function.

Technically, this could also be done with an if/else statement:

```rust
.foo = to_bool(if .bar { .bar } else { false })
```

But:

1. `either` is more concise, for those that want it
2. I don't think `if .bar` works yet? We'd probably need a `exists(.bar)` function
3. We don't have ternary operators yet (#3837)

cc @binarylogic

**Comment by lukesteensen** [comment]
This sounds like the coalesce operator (`.foo | .bar`) from the original RFC.

**Comment by JeanMertz** [comment]
Ah yes! Thanks @lukesteensen.

So, then the question becomes, do we want to remove all the extra plumbing to support `default` parameters for a few of the functions that we currently have?

It seems somewhat pointless to keep that around, but maybe there's a use-case I haven't considered yet?

**Comment by JeanMertz** [comment]
Ah, never mind. The difference is that a `to_int(.foo, default = 1)` also triggers if `.foo` can't be coerced into an int, which isn't the case for `(.foo | 1)`.
