### ISSUE TITLE
Forwarding metrics and an Any type

### ISSUE THREAD

**Issue by lukesteensen** [timberio/vector#421]
The `vector` source and sink should support forwarding/accepting both logs and metrics, but this would currently be problematic because no other component can accept both and we have no way to filter them.

To fix this, we should:
1. Introduce an `Any` type and assign it to the vector source and sink
2. Build transforms that take `Any` and filter to either `Log` or `Metric` events

**Comment by lukesteensen** [comment]
This is partially addressed by #631, which adds an `Any` type.

**Comment by binarylogic** [comment]
@lukesteensen what exactly is left on this?

**Comment by lukesteensen** [comment]
Before we close this out we need some way to deal with sources that produce `Any`-typed output. Currently, there's no way for them to be sent to transforms or sinks that only accept `Log` or `Metric`.

The simple solution would be to add `Any -> Log` and `Any -> Metric` transforms that just filter out the other type. A fancier solution would be for that to happen automatically when you plug an `Any` source into a `Log` or `Metric` transform/sink.

**Comment by a-rodin** [comment]
> A fancier solution would be for that to happen automatically when you plug an `Any` source into a `Log` or `Metric` transform/sink.

I think we also need to output runtime warnings if a transform produces say metrics, but is attached to a components which accepts only logs in that.

**Comment by lukesteensen** [comment]
> I think we also need to output runtime warnings if a transform produces say metrics, but is attached to a components which accepts only logs in that.

We have this part now! Our [typechecking](https://github.com/timberio/vector/blob/b8f144527bda15e98e4e91d42d8ab6306169af85/src/topology/config/validation.rs#L89) pass will catch things like this, it's just very standalone right now. Once we start doing fancier expansions, etc, it would be helpful to  integrate more directly.
