### ISSUE TITLE
RFC for allowing metrics to be forwarded to the elasticsearch sink

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#422]
Elastic has a whole use case on metrics, so there is no reason we can't dump metrics into ES:

https://www.elastic.co/solutions/metrics

Blocked by https://github.com/timberio/vector/issues/421

**Comment by loony-bean** [comment]
There are several ways we could achieve this.
1. Create a dedicated sink in Vector. This might give very precise control over batching and formatting, but will require some fair amount of configuration.
2. Transform metrics into logs (#1199) and reuse the existing sink. This is pretty straightforward, but gives much less control over document format.
3. Do nothing? There is an ES tool/agent called Metricbeat, which could ingest data from [Prometheus](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-prometheus-collector.html), [Statsd](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-statsd-server.html), and some other metric sinks. It comes with preconfigured indexes and dashboards. Not sure how useful is it in practice, thought, but it could provides some guidelines for formatting metrics.

**Comment by loony-bean** [comment]
(2) approach will also work towards creating universal logs & metric SQL sinks, in the spirit of [this idea](https://github.com/timberio/vector/issues/939#issuecomment-536225642).

**Comment by binarylogic** [comment]
Yes, 2 is also related to https://github.com/timberio/vector/issues/1199, which could give the user more control over the conversion.

Let's get weigh-in on this before proceeding. It's possible we might not do this for Elasticsearch until we get more demand.

**Comment by binarylogic** [comment]
@ktff I think this may already be done, but please see https://github.com/timberio/vector/pull/5806 for additional context. Also, we should audit metrics beat to make sure we are conforming to the proper naming and value schemes that Elasticsearch expects for metrics. If need be, we can do a small RFC.
