### ISSUE TITLE
multiple config files load order

### ISSUE THREAD

**Issue by afoninsky** [timberio/vector#4248]
### Vector Version
image: timberio/vector:nightly-2020-09-24-alpine
args: --config /etc/vector/*.toml --log-format

### Actual Behavior
TLDR: seems like config load order is matter

Currently, I'm playing with http health checks introduced in the latest nightly releases. 

I have file `vector.toml` with the following config:
```
[api]
    enabled = true
    bind = "0.0.0.0:8686"
```
And `victora.yaml` with own custom sink.
Internal http rest api does not init:
```
{"timestamp":"Sep 28 14:24:28.022","level":"INFO","target":"vector","message":"Loading configs.","path":"[\"/etc/vector/vector.toml\", \"/etc/vector/victoria.toml\"]"}
{"timestamp":"Sep 28 14:24:28.046","level":"INFO","target":"vector::topology","message":"Running healthchecks."}
```
When I rename `victoria.yaml` to `test.yaml` - everything is OK:
```
"timestamp":"Sep 28 13:31:36.173","level":"INFO","target":"vector","message":"Loading configs.","path":"[ \"/etc/vector/test.toml\", \"/etc/vector/vector.toml\"]"}
{"timestamp":"Sep 28 13:31:36.177","level":"INFO","target":"vector::sources::util::http","message":"Building HTTP server","addr":"0.0.0.0:9090"}
```

### Expected Behavior
Configuration should be idempotent and don't rely on file naming.

**Comment by binarylogic** [comment]
Thanks @afoninsky, the order of the configs shouldn't matter since we are basically just concatenating them before evaluating. We'll take a look and get this fixed.

**Comment by ktff** [comment]
@afoninsky  #4342 fixes the ordering for `api`. Did you perhaps noticed anything else?

**Comment by afoninsky** [comment]
Not yet, will report if notice something. Great job, thank you 👍
