### ISSUE TITLE
Remap inspired `reduce` transform to solve multiline merging

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#4258]
This issue proposes an idea for a new `reduce` transform that borrows from the new `remap` transform. The intent is to solve event merging, as well as other reduce-like problems, through robust reduce functionality. Even with the current options, many Vector users are still blocked on this functionality and I think we need to explore a more robust solution to this problem so that we can solve it and move on.

### `multiline` options

Currently, Vector offers `multiline` options in select sources. By setting these options users can achieve basic log merging directly in the source. While this works for some use cases, it falls short in a few areas (covered below).

### `merge` transform

The merge transform was introduced as a way to merge Docker logs initially. The intent was to decouple the merging strategy from the source so that users could use it as an escape hatch for sources that didn't have this functionality built-in. Over time we would inline this transform within sources where we could automatically merge data based on known factors. For example, Docker splits logs in such a way that we can automatically detect it and merge the logs without any configuration from the users.

### `reduce` transform

Finally, the `reduce` transform was introduced to enable the [Stripe canonical log lines pattern](https://stripe.com/blog/canonical-log-lines). And while the target use case was different, it's really just a sophisticated way to merge events.

### 1. Confusing

As you can see from the current state above, we have 3 different ways to merge events. This is confusing. And even if we direct users to a specific solution, like the source-level `multiline` options, the UX that provides is also confusing.

For example, the `file` source multiline options are still confusing to me, and I should understand them given my involement in the project. This is shared by a number of users I've helped as well.

### 2. Inability to specify per-stream merge conditions

Even though we offer `multiline` options within sources, users can only supply one set of settings. This is not sufficient in cases where data is coming from multiple disparate streams. For example, if a user configures the `file` source to ingest logs from many different files they'll likely want to configure different `multiline` settings for each file. The only way to achieve that currently is by defining multiple `file` sources.

### 3. Inflexbile

Because we must implement the `multiline` functionality within each relevant source, it's possible that sources will lack this functionality. This means we are more likely to block users on this functionality until a user supplies feedback. And once that occurs we'll need to allocate development time to implement this.

### 1. Drop the `merge` transform

I'd like to drop the `merge` transform in favor of a more robust approach to source-level multiline merging. I don't think we'll ever want to keep this around.

### 2. Add `stream_id` event metadata

To my knowledge, there are 2 reasons we prefer to inline `multiline` options within sources:

1. We have the context to operate within each stream. This is a requirement for multiline merging and it means users do not have to configure anything to achieve this.
2. It's faster and simpler. In some cases, we can skip the whole event creation process and simply merge strings/bytes.

I'm unsure how much of a problem 2 actually is. And while 1 is true for the simple case, it doesn't allow different merging options per stream (problem 2 above). I think we can retain the source-level simplicity by adding event metadata the identifies which stream the event came from (ex: `stream_id`_. The new `reduce` transform could segment events automatically based on this metadata. Event metadata, as whole, is being considered in #3910.

### 3. Remap inspired reduce transform

Finally, we should consider a more robust `reduce` transform. I can't help but wonder if there is a light-weight and flexible syntax we could support for robust merging, borrowing from the remap syntax. From a UX perspective, something like the following would be nice. I'll use the [examples in our docs](https://vector.dev/docs/reference/sources/file/#multi-line-messages).

#### 1. Ruby Exceptions

```
First line
foobar.rb:6:in `/': divided by 0 (ZeroDivisionError)
  from foobar.rb:6:in `bar'
  from foobar.rb:2:in `foo'
  from foobar.rb:9:in `<main>'
Last line
```

Merged with:

```toml
[transforms.reduce]
type = "reduce"
group_by = ["stream_id"] # default (see point 2 above)
timeout_secs = 10 # ensures pipelines don't stall
reduce = """
while next_event in nextEvent() {
  if startsWith?(next_event.message, /\w/) {
    .message += ("\n" + next_event.message)
    del(next_event)
  } else {
    break
  }
}
"""
```

#### 2. Line Continuations

```
First line\
second line\
third line
```

Merged with:

```toml
[transforms.reduce]
type = "reduce"
group_by = ["stream_id"] # default (see point 2 above)
timeout_secs = 10 # ensures pipelines don't stall
reduce = """
if match?(.message, /\\$/) {
  .message = replace(.message, /\\$/)

  while next_event in nextEvent() {
    .message += ("\n" + replace(next_event.message, /\\$/)
    del(next_event)
    if !match?(next_event.message, /\\$/) {
      break
    }
  }
}
"""
```

#### 3. Shortcut functions

And we could simplify the above with purpose-driven functions:

```toml
[transforms.reduce]
type = "reduce"
group_by = ["stream_id"] # default (see point 2 above)
timeout_secs = 10 # ensures pipelines don't stall
reduce = """
join_with_indentation(.message)
"""
```

```toml
[transforms.reduce]
type = "reduce"
group_by = ["stream_id"] # default (see point 2 above)
timeout_secs = 10 # ensures pipelines don't stall
reduce = """
join_with_line_continuation(.message, '\')
"""
```

#### Summary

All of the above is definitely up for discussion. I'm less concerned about the actual syntax and naming, and more concerned with the direction. If we agree this approach is better we can start an RFC to nail down the details.

But the reasons I like this approach:

1. It's similar to the new `remap` syntax, and we can share the learning curve there.
2. We can borrow functions from the `remap` syntax.
3. Shifting this to a transform means we can decouple this functionality providing for more flexibility and the ability to compose higher-level components. Something we are solving in #3791.
4. It solves problem 2 above by allowing users to conditionally target streams if

**Comment by MOZGIII** [comment]
I agree that `merge` transform can go - in the presence of the more advanced `reduce` transform there's no need for a `merge` transform that is a subset of that functionality.

Regarding the addition of the `stream_id` event metadata - I have thought about a similar solution too, so I like this. I thought about the implementation and figured there may be some complications with the naive approach like adding a single field. I actually was going to submit a proposal for specifically this - a way to distinguish the streams - after I figure out a solution. But `stream_id` works as a start!

I'd like to note here, that unlike `merge` and `reduce` transforms that emit either one or zero events per one event, the `multiline` merging logic may also emit two events in certain scenarios - see https://github.com/timberio/vector/pull/3262.

I like the proposed idea to take care of `multiline` implementation as part of the `reduce` transform via the built-in shortcut functions a lot! However, afaik `reduce` can only emit one or zero events atm, and that doesn't allow some modes of operation (`continue_through` and `halt_before`).

**Comment by JeanMertz** [comment]
I definitely like the goal of this proposal.

**technical and cognitive complexity**

I am a bit worried about the technical and cognitive complexity this change introduces into the language<sup>*</sup> though. I would propose this transform implicitly iterates over events, instead of introducing the concept of loops to the language.

Consider your examples, using an implicit loop (and `$` to reference the root event):

```js
if !starts_with(.message, /\w/) {
	break
}

$.message = $.message + "\n" + .message

// Or, if we add compound-assignment operator support:
// $.message += "\n" + .message

// Or, if we add a `join` function which by-default joins with "\n":
// $.message = join($.message, .message)
```

```js
if !ends_with(.message, "\\") {
	break
}

$.message = $.message + "\n" + trim_end(.message, "\\")
```

(I know you said you don’t care about the syntax right now, but this is less about syntax and more about overall design for both the transform and the language)

<sub>* _we really should come up with an official name for the language, as I've referred to it as "remap language" before, but that no longer applies after this transform is introduced_</sub> 

**shortcut functions**

I’m not sure this is a good idea to add right now, especially not in a first iteration of this transform.

The reason being that we’re working towards supporting macros (#3791), and I feel like this has some tie-in with that proposal.

**complexity**

Adding support for custom reduce logic will complicate the usage of this transform. We definitely need good documentation and examples (and hopefully a way forward with macro’s to cover the most common use-cases with simple declarative rules).

As an aside, I also wonder if we should introduce some kind of “expert” flag (or whatever) to transforms that require more complex logic and can relatively easily result in unexpected outcomes if used incorrectly.

**performance**

We should definitely benchmark the performance of a transform like this, but given our existing benchmarking results for the `remap` transform, I think we should be OK here.

**more examples**

I do think it makes sense to have a larger list of (real-world) examples, so that we can be sure that whatever set-up we come up with, fits all the required use-cases.

**stream_id event metadata**

I’ll defer commenting on this, as it seems to be part of a larger discussion that is somewhat orthogonal to this transform proposal (until we deprecate existing `multiline` options, at which point identifying a stream of events becomes a requirement).

**Comment by FungusHumungus** [comment]
A use case I would really like to support with this is s-expressions. Here's an example:

```
("2020-10-04 01:40:40" :BACKTRACE 
 :ROOT-CONTEXT
 "Date/time: 2020-10-04-01:40An unhandled error condition has been signalled: Unknown scheme: NIL

(FFFFFC7FCAC19338) : 0 (PRINT-CALL-HISTORY :CONTEXT NIL :PROCESS NIL :ORIGIN NIL :DETAILED-P NIL :COUNT 1152921504606846975 :START-FRAME-NUMBER 0 :STREAM #<STRING-OUTPUT-STREAM  #x302019FCEFDD> :PRINT-LEVEL 2 :PRINT-LENGTH 5 :SHOW-INTERNAL-FRAMES NIL :FORMAT :TRADITIONAL) 853
(FFFFFC7FCAC194A0) : 1 (PRINT-BACKTRACE-TO-STREAM #<STRING-OUTPUT-STREAM  #x302019FCEFDD>) 85
...")
```

An event can cover multiple lines until it encounters a closing parenthesis. Fields are white space separated, and within '"' anything can happen, until we get to a closing ". '"' can be escaped by a '`\"'`within a string.

I think if we could get this to work here, it would stretch the transform enough such that any other multiline requirement would work.

I can think of two ways we could go about this.

## parsing grammars

This is a parsing problem which we could possibly solve in a way similar to pest, by allowing the user to specify a grammar that the event could fit into. It wouldn't need to be as comprehensive as pest, but we would need to think carefully about which primitives we could strip it down to.

A very simple example

```
"(" ~ parse_timestamp(.timestamp) ~ .type ~ .context ~ parse_string(.message, "\"", "\\") ~ ")"
```

The `parse_string` function would tell the parser to expect a string enclosed by `"` and with a `\` escape character.

The grammar would automatically handle multiple incoming messages to a single outgoing message, as per however the grammar is defined.

## iteratively

Or we could provide a language that the user could use to iteratively parse the events. The function could be called once per incoming message, but not produce a message until it calls a given function `pushMessage()`.

In addition to what we have with remap currently, the language would need to support: 

- local variables, to maintain the current state of the pointer - in a string, just after an escape etc.. The variables would need to persist over incoming events (per group_id). Perhaps they could be reinitialized every time an event is pushed out?
- the ability to loop over each character in the incoming message.

A (potentially very buggy, but simplified) example:

```
var inString = false
var currentString = ""

for i in .event {
  if i == "\"" {
    if inString {
      inString = false
      .message = currentString
    } else {
      inString = true
    }
  }
  if inString {
     currentString = currentString + i
  }

  if i == ")" {
    pushMessage()
  }
}

```

I think iteratively would probably allow more flexibility, and is inline more with how remap currently works, but could result in less intuitive config files.


---

I think both of these ways are potentially configuration nightmares and do increase complexity substantially. But, I imagine it is quite likely that there are only a limited number of specific scenarios that would generally be in use with very few exceptions. Perhaps we could have a library of specific `reduce` functions stored in external files that people could include, so a typical config would just be: 

```
[transforms.reduce]
type = "reduce"
group_by = ["stream_id"]
timeout_secs = 10
include = "./lib/sexp.remap"
```

**Comment by JeanMertz** [comment]
That's an interesting use-case @FungusHumungus.

I am terribly worried that we're going to make this transform (or even the language itself) way too complex to cover some of these edge-cases.

I would _really_ like to try and solve this without having to introduce loops into the language, and do looping out of the language itself, inside the transform we're going to introduce here.

I'm not sure if we'll be able to handle all cases doing so, but I definitely think we can hit 80% with that as a start.

**Comment by binarylogic** [comment]
> I am a bit worried about the technical and cognitive complexity this change introduces into the language* though. I would propose this transform implicitly iterates over events, instead of introducing the concept of loops to the language.

I'm a fan.

> Consider your examples, using an implicit loop (and $ to reference the root event):

So `$` represents the previous event at first and then continues to represent that event until `break` is seen?

> we really should come up with an official name for the language, as I've referred to it as "remap language" before, but that no longer applies after this transform is introduced

The official name is ✨  Timber Remap Language ✨ . Or TRL for short.

---

@FungusHumungus I tend to lean towards @JeanMertz for now -- as a first step. Coming back to the key principles of the language:

1. Simple - Users should be able to look at any remap syntax and get it immediately.
2. Safe - Very hard to shoot yourself in the foot.
3. Fast - Not only fast in execution but also prevent users from writing things that are slow.

That said, offering a `loop` transform (or whatever we want to call it) enhances the same principles:

1. Simplicity - Jean's examples are much easier to understand at first glance.
2. Safety - We can timeout a loop after a configured time. We can make this a required argument.
2. Performance - We can offer observability around this transform, helping users to get insight into this step and optimize it over time.

Let me know if you agree or disagree.

**Comment by FungusHumungus** [comment]
Yes, I totally agree, providing a comprehensive parsing solution can potentially trash all 3 of those principles! 

I am all up for keeping things simple - especially as anything we do we will need to continue to support, so we need to be very careful and choose our solutions wisely.

Perhaps the parsing grammar is a better solution for this use case but not here as it isn't really a part of  :sparkles: TRL :sparkles:

**Comment by MOZGIII** [comment]
I wanted to look into the one key difficulty with implementing multiline support - the need to occasionally emit two events for a single incoming event. I.e., rather than `transform(&mut self, event: Event) -> Option<Event>` we'd need to `transform(&mut self, event: Event) -> Vec<Event>`.
See https://github.com/timberio/vector/issues/4258 for more info on why this is.

Thankfully, it's already solved by `Transform::transform_stream`, so we can go ahead with implementing this!

**Comment by lukesteensen** [comment]
I chatted with @binarylogic about this today and we had a few takeaways:

1. It seems that the shortest path to unblocking most users is to make some tweaks to the existing `reduce` transform to better support the multi-line merging use case. We should do that first.
2. A relatively simple UX improvement would be to use `remap` to express conditionals rather than the existing TOML-based condition system. This is an expansion of remap's scope from `fn(&mut event)` to `fn(&event) -> bool`, but seemingly a worthwhile and not-too-confusing one. It can also serve as an experiment to help inform future ideas about expanding scope.
3. Down the road a bit, we could consider reimagining the `reduce` transform to be focused around `remap`. This could take a few different forms. One would be to use an `Event` as the intermediate state instead of the per-field state we use now, and using `remap` to express how that event should be mutated with each incoming event. Another would be to introduce a `remap` merge strategy to the existing list, working directly with values instead of a whole event.

**Comment by binarylogic** [comment]
Closed in https://github.com/timberio/vector/pull/4743

**Comment by ArtemTraierLotus** [comment]
how do we define stream_id to begin with, where can I find docs for that ? Is that smthing we attach in each log msg on client side ?

**Comment by jszwedko** [comment]
Hi @ArtemTraierLotus !

> how do we define stream_id to begin with, where can I find docs for that ? Is that smthing we attach in each log msg on client side ? cc: @binarylogic sry for pinging on closed thread

`stream_id` is just an example, you can group by any field that exists on the log event. You can see an example grouping by three fields here: https://vector.dev/docs/reference/configuration/transforms/reduce/#examples-merge-ruby-exceptions.

**Comment by ArtemTraierLotus** [comment]
thanks for reply @jszwedko , is understanding correct that the field we group by should be unique for each multiline log msg we have ?

**Comment by jszwedko** [comment]
> thanks for reply @jszwedko , is understanding correct that the field we group by should be unique for each multiline log msg we have ?

It should be unique for each "ordered stream" of messages. For example, `file` would be a good grouping for messages coming from the `file` source; `topic` and `partition` for the `kafka` source.
