### ISSUE TITLE
Align CI jobs with the files changes

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#4295]
It would be nice if CI jobs only ran when necessary. For example, `make check-clippy`, which takes 10m to run, does not need to run for PRs that only contain documentation changes (https://github.com/timberio/vector/pull/4274). This is more pronounced in the `bors` workflow, which runs the full test suite, taking an hour +.

Feel free to close if we don't think it's worth the maintenance.

**Comment by jamtur01** [comment]
This is now done.
