### ISSUE TITLE
Verify async-graphql interface handling for 'empty' topology types via Apollo Server

### ISSUE THREAD

**Issue by leebenson** [timberio/vector#4384]
I submitted [an issue](https://github.com/async-graphql/async-graphql/issues/301) to async-graphql re: returning empty objects on interface types with no matching fields. I don't recall seeing empty results in previous interface implementations with other libs (Apollo, gqlgen), but it's also possible that I just didn't notice it.

In any case, I'd like to whip together a quick Apollo demo to see how they handle it. If the GraphQL spec allows for empty results where no interface fields match, we'll likely want to check for that eventuality in the UI and parse those out.

**Comment by leebenson** [comment]
Async-graphql is doing the right thing here. [Test ref.](https://github.com/async-graphql/async-graphql/issues/301#issuecomment-708631546).

**Comment by sghall** [comment]
Drive-by. 🚗   Hmmm...that is surprising.  Good to know. 👍

**Comment by leebenson** [comment]
Yeah @sghall - was gonna tag you on this, to see if it’s something you’d seen before.

I guess we should filter out `{}` in the client, when querying only implementor-specific fields on an interface type.
