### ISSUE TITLE
Update unit tests to use the new remap `assert` function

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#4398]
This issue represents work to drop the "conditions" used in our unit tests in favor of the remap language. Specifically, the `assert` function (#4395).

**Comment by FungusHumungus** [comment]
Not sure I fully understand this. When you say unit tests, do you mean the behaviour tests?

**Comment by binarylogic** [comment]
I think @JeanMertz already handled this via the `type = "remap"` option for all conditions.
