### ISSUE TITLE
The remap language does not support quotes for look ups

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#4401]
See https://github.com/timberio/vector/pull/4277#issuecomment-703876896

Things like this do not work:

```
fields."@timestamp" = "foo"
.foo = .bar."baz.buz".bev

# Use slash escapes within quotes
.bar = .buz."fub\"\\fob".fab
```

This is noted in the RF:

https://github.com/timberio/vector/blob/master/rfcs/2020-07-21-2744-remap-syntax.md#guide-level-proposal

**Comment by Hoverbear** [comment]
Lookups and remaps both support quotes, here's some tests:

https://github.com/timberio/vector/blob/d82e221948549139a4a8ae68252e86f5830c4111/tests/data/fixtures/lookup/quoted_multiple#L1
https://github.com/timberio/vector/blob/d82e221948549139a4a8ae68252e86f5830c4111/tests/data/fixtures/lookup/sufficiently_complex#L1
https://github.com/timberio/vector/blob/d82e221948549139a4a8ae68252e86f5830c4111/tests/data/fixtures/lookup/nested_quoted#L1

The issue linked (#4277) is already covered by https://github.com/timberio/vector/issues/4273.
