### ISSUE TITLE
Enhancement: Assume role when using EKS Web Identity

### ISSUE THREAD

**Issue by grantisdale** [timberio/vector#4405]
### Current Vector Version

```
vector 0.11.0 (gda89b0b x86_64-unknown-linux-musl 2020-10-06)
```

### Use-cases

Using the `AWS CloudWatch Logs` Sink to send logs cross account we need to make use of the `assume_role` configuration available to the sink, but this is not currently compatible with Vector's EKS Web Identity implementation.

In our case we want to do this so that we can aggregate logs from all our clusters, in a number of different AWS accounts, into a _logging_ account for our security team to access.

### Attempted Investigation

When I exec into the vector pod the AWS role env var is set to the correct role:
`AWS_ROLE_ARN=arn:aws:iam::<id>:role/vector-logs`

But the logs of that same vector pod when trying to put to an AWS CloudWatch sink:
`arn:aws:sts::<id>:assumed-role/dev-1...is not authorized to perform...`

It's not authorised to perform sts assume role because it's the wrong role trying to do the assuming. The vector workload should be running as the `vector-logs` role not the `dev-1` role. When using the `assume_role` parameter of the AWS CloudWatch sink in the config, Vector seems to no longer make use of the environment variable as expected.

@tustvold has responded on discord to say that the current implementation doesn't support assuming a role and it expects the injected role to be the one that it should run as.

**Comment by MOZGIII** [comment]
Closed via #4406.
