### ISSUE TITLE
Add support to "catch" errors in remap language

### ISSUE THREAD

**Issue by JeanMertz** [timberio/vector#4409]
Currently, any function in the remap language is allowed to fail. This can happen for example if you use one of the `parse_*` functions, such as `parse_json`, but you pass in a value that can't be parsed. 

You can configure the `remap` transform to either drop an event for which the script fails, or keep the original one, but this applies to the entire script you used to remap the event, meaning in a 100 line script, if one function fails, the entire script fails.

This might be too coarse of a control, as some people might want to act on a single failing function and define what should happen in the error case.

There are multiple ways we can solve this, this issue is simply to make sure we track this situation and come up with a long-term solution.

**Comment by JeanMertz** [comment]
Comment by @jszwedko, we could take a look at how Lua does error handling:

https://www.lua.org/pil/8.4.html

**Comment by binarylogic** [comment]
Closing since we have decided not to take error handling in this direction, we can reopen if that changes.
