### ISSUE TITLE
Remove the `sources.journald.remap_priority` in favor of VRL

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#4414]
The `journald` source `remap_priority` option does the following:

> If the record from journald contains a PRIORITY field, it will be remapped into the equivalent syslog priority level name using the standard (abbreviated) all-capitals names such as EMERG or ERR.

This should be deprecated and handled by the new Remap Language.

**Comment by ktff** [comment]
@jamtur01 It seams #4415 needs to be done before this, but I don't see it being worked on.

**Comment by jamtur01** [comment]
Hmmm I thought that was being worked on - hold one and I'll work out what's happening.

**Comment by binarylogic** [comment]
@ktff, @lucperkins already did the work in that issue via https://github.com/timberio/vector/pull/5505 and https://github.com/timberio/vector/pull/5503, but didn't link it. I've closed it.
