### ISSUE TITLE
New `syslog_level_keyword_to_priority` Remap function

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#4417]
See #4414 and https://en.wikipedia.org/wiki/Syslog#Severity_level.

## Examples

Given this event:

```json
{
  "level": "err"
}
```

And this Remap source:

```
.priority = syslog_level_keyword_to_priority(.level)
```

The result would be:

```json
{
  "level": "err",
  "priority": 3
}
```

Special requirements:

- [ ] Also check for "error" since "err" is not commonly used.

**Comment by JeanMertz** [comment]
We have `to_syslog_level` and `to_syslog_severity`, which seem to tackle this use-case. Closing this, but please don't hesitate to re-open if there's still a need for this.
