### ISSUE TITLE
Exposing a single, shared API for all transforms that evaluate user code

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#4423]
We have `lua`, `WASM`, and now `remap` transforms. Also, `javascript` was on the way at some point?

It seems like a very straightforward idea to build a single API (set of helper functions) and expose all of them in every supported language/runtime.

- this approach is more structured, easier to maintain, and we only have to work on the groundwork of exposing the API to each runtime once
- when we want to add new function we just add it to the API, and it is automatically available to the consuming languages
- dry - less code, less bugs, more work done with less effort, usual stuff
- easier for users - they know they can easily switch languages, and the same functionality is universally available
- simpler mental model - with helper-function specific issues, we can provide support to users without knowing the specific details of the language user are working with
- allows us to consolidate our work - instead of addressing M*N problems with M issues at N languages, we can just focus on solving M problems universally
- this unlocks interesting things potentially, like interop of macros across different languages - but this is an extra step
- will help us see the bigger picture - the API requirements will help drive the needs of the language integrations from the architectural perspective, we won't have to go through the issues we had with `lua` transform - like no ability to share the state across events, or emit events arbitrarily - for each new of the language-oriented transforms

Refs:
- https://en.wikipedia.org/wiki/Web_IDL
- https://wasi.dev/
- https://en.wikipedia.org/wiki/Linux_kernel_interfaces#Linux_API
- https://man7.org/linux/man-pages/man7/bpf-helpers.7.html
- https://github.com/eqrion/cbindgen
- https://github.com/rustwasm/wasm-webidl-bindings

**Comment by binarylogic** [comment]
That's an interesting idea. To clarify, the shared functions would be defined in Rust and exposed through each runtime? Do you envision that being a lot of maintenance overhead?

**Comment by MOZGIII** [comment]
> the shared functions would be defined in Rust and exposed through each runtime?

Yes, that's the idea!



> Do you envision that being a lot of maintenance overhead?

On the contrary, I expect the maintenance time to be extremely low compared to what we currently have spread among all the transforms.

The maintenance time on the machinery to expose the API to each respective language is very likely to be done only once, and then will just work. We will likely make it so that the efforts to alter the exposed API are automated - after all we'll be defining the functions in Rust, and all the language binding already have some way to interop with rust. All we have to do is to properly design the API and land it in such a way that it can actually be utilized in every binding we have. Given the nature of the functions we want to expose - this should technically be kind of trivial.

**Comment by MOZGIII** [comment]
To be clear, this is more related to implementing complicated functions - like multiline merging for instance. Trivial things, like type conversion, (as in `u16` to `f32`, etc) are usually already handled natively by the respective languages.

**Comment by binarylogic** [comment]
Also related is #5823

**Comment by JeanMertz** [comment]
I think we should close this off. I don't think there's anything actionable at the moment here. Please don't hesitate to re-open if you think differently @binarylogic.
