### ISSUE TITLE
Add `cue fmt` to CI

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#4424]
This ensures that formatting is consistent across all `.cue` files.

**Comment by jamtur01** [comment]
Doesn't `cue fmt` actually format the files? I can't find a test mode for it?

**Comment by JeanMertz** [comment]
> I can't find a test mode for it?

We probably want a shell script that formats the files, stores them in a temp dir, and then compares those files to the original files, to see if anything changed (and thus someone forgot to format the files).

**Comment by MOZGIII** [comment]
We could also ask cue maintainers to take action on https://github.com/cuelang/cue/pull/247

**Comment by jszwedko** [comment]
We had some precedent for this in another project. It looked like:

```
          cue fmt docs/**/*.cue
          status="$(git status --porcelain)"
          [[ -z "$status" ]] || {
            echo >&2 "uncommitted go:generate changes"
            echo >&2 "$status"
            git diff
            exit 1
          }
```
