### ISSUE TITLE
New `compact` remap function

### ISSUE THREAD

**Issue by JeanMertz** [timberio/vector#4430]
Allow compacting events by removing "empty" data, where the definition of empty is configurable.

## Example

Given this event:

```json
{
 	"a": "a",
	"b": "",
	"c": null,
	"d": {},
	"e": [],
	"f": {
		"g": null
	}
}
```

And this remap function:

```rust
. = compact(., recursive = true, string = true, null = true, map = true, array = true)
```

Would result in:

```json
{
  "a": "a"
}
```

The defaults are:

* `recursive`: `true`
* `null`: `true`
* `string`: `false`
* `map`: `false`
* `array`: `false`

**Comment by JeanMertz** [comment]
cc @binarylogic @FungusHumungus

**Comment by binarylogic** [comment]
Like it.
