### ISSUE TITLE
Allow specifying image registry via `global` variable in the Helm chart

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#4443]
I've started with this already but decided it might not in-line with the work at hand, and decided to postpone it a bit, and also give us a chance to discuss the approach first.

So, some users, typically with big deployments, or strict enterprise ops policies will use their own custom repos to mirror all the deployed containers. This is done for various reasons, like bandwidth optimization, security concerns, etc.

To support such use cases better, we need to implement the ability to customize the container image repository at our Helm charts family.

The plan is to introduce the following variables:

- `global.vector.imageRegistry` (unset by default)
- `global.vector.imagePullSecrets` (unset by default)
- `image.registry` (set to `docker.io` by default)
- `image.pullPolicy`  (set to `IfNotPresent` by default)

Due to how chart values are defined, while a bit counter-intuitive, *`global` values take priority over local values if defined*.

Refs:
- https://github.com/helm/helm/issues/7754
- https://github.com/helm/charts/blob/54761c116c0df515056bb62ed2e11ae37c3abf72/stable/postgresql/values.yaml#L5-L29
- https://github.com/bitnami/charts/blob/e91188c1dc8e409fd944962268ced92273f40e10/bitnami/postgresql/templates/_helpers.tpl#L57-L78

**Comment by spencergilbert** [comment]
Configuration for a global image registry/repository is already implemented, local registry/repository is implemented, and local pullPolicy is implemented as well.

We can just add a global option for pullSecrets configuration - that's currently able to be set at the local level.
