### ISSUE TITLE
Handle file rotation

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#445]
I have a simple file rotation test that is failing:

1. [Config file](https://github.com/timberio/vector-test-harness/blob/master/cases/file_rotate_create_correctness/ansible/config_files/vector.toml)
2. [Rotation scheme](https://github.com/timberio/vector-test-harness/blob/master/cases/file_rotate_create_correctness/ansible/run.yml#L38-L43)

You can see that the test expects to receive a total of 3 lines, which includes lines in both the rotated and new file, yet we only receive 2. Meaning new data placed in the newly rotated file is not recognized.

**Comment by lukesteensen** [comment]
@binarylogic Have you rerun this test recently? Following file rotation is something I expect to be working.

One potential issue with your test is the small amount of data you're writing. By default we use the checksum fingerprinting strategy and we need at least `fingerprint_bytes` of data (i.e. 256 bytes by default).

**Comment by binarylogic** [comment]
Yep, good catch. I ran this test before we introduced the fingerprinting, but I've been meaning to re-run it. So I am not confident this is still an issue. I'll add this to my next sprint and address it then.

**Comment by binarylogic** [comment]
I've re-tested this against Vector `0.5.0` and all works as expected. I'm closing as a result.
