### ISSUE TITLE
Ensure Kubernetes `kustomization.yaml` file is accurate

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#4450]
As part of writing the Kubernetes docs I noticed that these two `kustimzation.yaml` files do not match:

1. https://github.com/timberio/vector/blob/master/kustomization.yaml
2. https://github.com/timberio/vector-k8s-examples/blob/master/kubectl/kustomization.yaml

I wanted to verify that the one in the `vector` repo is correct. If not, we should update it.

**Comment by MOZGIII** [comment]
Both are good, they have different purposes, and one depends on the other:

https://github.com/timberio/vector/blob/6b424e320d42e38b46ae1415a4c5f6e67c999d63/kustomization.yaml#L6-L7

**Comment by MOZGIII** [comment]
Oh, I misread.

https://github.com/timberio/vector-k8s-examples/blob/master/kubectl/kustomization.yaml - this one is actually an example of what users would have in their config management repo. More of like a sample way to deploy vector based on our kustomization base.
https://github.com/timberio/vector/blob/master/kustomization.yaml - this is our internal thing that drives skaffold to allow in-kubernetes development. So it's for us.

There's also a third one - https://github.com/timberio/vector/blob/master/distribution/kubernetes/kustomization.yaml - this is our kustomization base - everything else reuses it in one way or another.
