### ISSUE TITLE
Documentation to reconfigure Vector in Kubernetes

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#4461]
As part of finishing the Kubernetes docs I need the recommended steps for reconfiguring Vector on Kubernetes using both `kubectl` and `helm`?

**Comment by MOZGIII** [comment]
With `kubectl` you just update your local manifests and `kubectl apply` the changes. If needed, ``kubectl rollout restart vector`.

With `helm`, use `helm upgrade vector timber/vector --version $VERSION` (`vector` is the release name, `timber/vector` is the chart name, and `$VERSION` is the version you have currently installed - you can get it via `helm list`) with either the updated values passed via `--values`, or via `--set`, optionally combining with `--reuse-values`.

**Comment by MOZGIII** [comment]
This was implemented.
