### ISSUE TITLE
Documentation to update Vector on Kubernetes

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#4462]
When Vector releases a new version what is the recommended way to update Vector to the latest versio on Kubernetes?

**Comment by MOZGIII** [comment]
1. Read the release notes, check if there are any backward-incompatible changes.
1.1. If there are - decide whether to proceed with an update or to do a reinstall instead.
1.2. No backward-incompatible changes, or none that affect you - proceed with an update.

2. `helm repo update timber` (where `timber` is the name of our repo)

3. `helm upgrade vector --reuse-values` (where `vector` is your release name)

    Optionally use `--atomic` and/or pass new values via `--values` or `--set`.

If using `kubectl`, after step 1 just update your local config from our examples for the latest version, change the image tag to the latest version (literal numeric value of the latest version, never use `latest` tag!) reapply the config `kubectl apply`.

Any custom steps for these instructions should be provided with the release notes for each release.

Step 1 - read the release notes - is a must!

**Comment by MOZGIII** [comment]
This was implemented and available in `master`.
