### ISSUE TITLE
grok parser: Allow for nested data to be produced when parsing

### ISSUE THREAD

**Issue by itkovian** [timberio/vector#4465]
### Current Vector Version

```
vector 0.11.0 (ga6248f5 x86_64-unknown-linux-gnu 2020-10-08)
```

### Use-cases

We need to process syslog messages from a wide variety of hosts. Eventually, processed messages end up in Elasticsearch (currently through logstash) A number of these contain information we'd like to have queryable in ES, preferably nicely split into different fields, for example:

~~~~json
  "_source": {
    "message": "lmod::  username=myuser, cluster=mycluster, jobid=12345, userload=yes, module=tensorflow/intel-2019a, fn=/apps/CO7/skylake-ib/modules/all/Tensorflowintel-2019a.lua",
    "type": "lmod",
    "@timestamp": "2020-10-08T20:42:37.767Z",
    "program": "lmod",
    "syslog_version": 1,
    "host": "loghost",
    "@source_host": "node1234",
    "lmod": {
      "userload": true,
      "filename": "/apps/CO7/skylake-ib/modules/all/Tensorflow/intel-2019a.lua",
      "module": {
        "version": "intel-2019a",
        "name": "Tensorflow"
      },
      "info": {
        "cluster": "mycluster",
        "jobid": 12345,
        "username": "myuser"
      }
    },
    "syslog_abspri": 13,
    "@version": "1"
  },
~~~~

In the above example, there is an extra nesting level at the `lmod` entry, meaning that fields under it will not clash with other fields nested under other top-level identifiers, for example, syslog messages about ssh, sudo, ceph, ... Idem for e.g., `jobid` which is numerical here, but might be a string when a similar piece of information is coming from another kind of syslog message.

Plain grok patterns used in e.g., logstash and vector do not allow this kind of nesting, essentially placing all matched fields in a flat object.

### Attempted Solutions

Currently, grok allows a single pattern. If further processing of one of the resulting fields is desired, a next transform can be used, but then no nested structure is created. 

For example,

~~~~toml
[sources.foo]
  type = "stdin"

[transforms.int_day]
  inputs = ["foo"]
  type = "grok_parser"
  field = "message"
  drop_field = true

  pattern = "%{NONNEGINT:id} %{GREEDYDATA:int_message}"

[transforms.day]
  inputs = ["int_day"]
  type = "grok_parser"
  field = "int_message"

  drop_field = true
  pattern = "^%{DAY:day}$"

[sinks.stdout]
  type = "console"
  inputs = ["day"]
  encoding.codec = "json"
~~~~

For example,
~~~~json
1 Monday
{"day":"Monday","host":"logstash20.banette.os","id":"1","source_type":"stdin","timestamp":"2020-10-08T21:45:34.861510557Z"}
~~~~

So the resulting structure remains flat, rather than given someone like

~~~~json
{"int_message":{"day":"Monday","id":1},"host":"logstash20.banette.os","source_type":"stdin","timestamp":"2020-10-08T21:45:34.861510557Z"}
~~~~

### Proposal

I'm not sure if something like this can be achieved through use of TOML features for nesting, or if it would be preferable to have an extra configuration option to actually nest the inner match in the outer new field.

**Comment by binarylogic** [comment]
@FungusHumungus does this seem doable for the new `parse_grok` Remap function?

**Comment by FungusHumungus** [comment]
Yes! This sounds like exactly the sort of thing Remap was made for.

Something like the following should do the trick (once #5279 is merged):

```
[transforms.remap]
  type = "remap"
  inputs = ["stdin"]
  source = """
         $$intday = parse_grok(.message, "%{NONNEGINT:id} %{GREEDYDATA:int_message}")
         $$day = parse_grok($$intday.int_message, "^%{DAY:day}$")

         .int_message = { 
                      "day": $$day.day,
                      "id": $$intday.id
         }
         del(.message)
    """
```

Once that PR is merged, I'll test this works properly.

**Comment by JeanMertz** [comment]
I would note that #5279 isn't required, you could do:

```rust
.int_message.day = $day.day
.int_message.id = $intday.id
```

Which gets you the same result as

```rust
.int_message = { 
	"day": $day.day,
	"id": $intday.id
}
```

**Comment by JeanMertz** [comment]
Closing this, since this can be achieved using the Remap transform.

**Comment by ypid-geberit** [comment]
> Plain grok patterns used in e.g., logstash and vector do not allow this kind of nesting

Logstash supports creating nested fields from within grok patterns. I opened #8382 as a fresh start of this issue.

**Comment by itkovian** [comment]
Thanks!
