### ISSUE TITLE
Deprecate custom config maps in favor of allowing users to customize them in Helm charts

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#4494]
https://github.com/timberio/vector/blob/878145e4837633589cf192525732c7326a2482b2/distribution/helm/vector/templates/daemonset.yaml#L115-L122

These need to go, and be replaced with dynamically customizable Helm values. The same config should be achievable with the end result through configuration, but the defaults should not include any "custom configs" like in the snippet above.

**Comment by tyrken** [comment]
I'd be a little careful of this (assuming I'm understanding this issue correctly).

A second parallel set of full config options in the helm chart that needs updating whenever a new option is added to the main program can get tiring to keep updated.  Golang templating driven by Helm values can act differently (e.g. defaulting) compared to the rust language reading the TOML, so upgrades can be difficult or require a lot of README documented breaking changes that trip people up.

I'm hoping this is just a helm-package-contained way of creating the same config map, where the chart-user authors TOML reading the main app documentation still.  Not having to go through a helm-specific mapping layer.

**Comment by MOZGIII** [comment]
This issue is not even about YAML vs TOML - it's more about removing those two hard-coded `ConfigMap` volumes from the Helm chart `DaemonSet`. The recommended YAML file will remain the same, but the Helm Chart will loose those two hardcoded volumes. This will change the defaults, but this way of configuration it is not normally expected either way with Hem charts. Users will still be able to use `existingConfigMap`, or add custom volumes as they see fit.

We have plans to support JSON and YAML configs natively in Vector, but those are tracked in other issues.
