### ISSUE TITLE
Unify `host`, `hostname`, and `source_ip` keys in the `syslog` source

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#4496]
These keys appear to be duplicative, we clean them up. In general we should favor the data we're extracting from the syslog line.

- [ ] Honor the `host_key` option.

**Comment by binarylogic** [comment]
@FungusHumungus curious what you think about this?

**Comment by FungusHumungus** [comment]
`source_ip` is the ip address (or pathname for unix sockets) of the host the syslog message was received from.
`hostname` is the host field that has been parsed out of the syslog message.
`host_key` is `hostname` if it exists. If it doesn't exist, it takes the `source_ip`.

HAProxy syslog messages don't seem to include the hostname, and that is a fairly significant application, so unfortunately it does happen.

I imagine we could remove `hostname` without losing any value in the events. 

I think `source_ip` would quite possibly be useful still. With some complex syslog forwarding going on the `source_ip` could be a different machine to the `hostname`, which someone may find useful.

**Comment by binarylogic** [comment]
Sounds good, I'll close then.
