### ISSUE TITLE
Add connection open and close events in the `socket` source and sink

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#4505]
See https://github.com/timberio/vector/issues/3518#issuecomment-689780361

Given the complexities of using high cardinality values in labels, we're going to start simple with a generic `open_connections` gauge that represents the total number of connections currently open.

- [x] Increment the `open_connections` gauge when a connection is established.
- [x] Decrement the `open_connections` gauge when a connection is closed.

**Comment by binarylogic** [comment]
@ktff it's possible this is better handled at a lower level, so that any component opening and closing connections would have this metric, but I'm unsure how our code is organized.

**Comment by ktff** [comment]
An pretty generic `open_connections` gauge was added. It covers both `tcp` and `unix` connections for:
* `statsd` sink
* `socket` sink
* `vector` sink
* `papertrail` sink
* `syslog` source
* `vector` source
* `socket` source

It could be labeled with mode, either `tcp` or `unix`. This can be added if needed.

**Comment by binarylogic** [comment]
Nice work, thanks.
