### ISSUE TITLE
The `pulsar` sink `encoding.codec` should default to `json`

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#4511]
Currently, the `pulsar` sink's `encoding.codec` option defaults to `"text"`. Text should very rarely, if ever, be the default. We should default to `"json"` unless I misunderstanding something.

**Comment by jszwedko** [comment]
I don't know anything about pulsar, but their docs make it look like that we should pass key/values as `metadata.properties`:

> A sequence of key/value pairs (using the KeyValue message). These are application-defined keys and values with no special meaning to Pulsar.

https://pulsar.apache.org/docs/en/develop-binary-protocol/#message-metadata

If that is the case, I could see `text` making sense as the default to just send `message` as the `message` in the pulsar payload.

**Comment by binarylogic** [comment]
If that's the case we shouldn't even offer an `encoding.codec` option.

**Comment by jszwedko** [comment]
With my superficial understanding of pulsar, I tend to agree. Maybe @leshow has thoughts? It'd be nice to hear from pulsar users.

**Comment by lukesteensen** [comment]
I believe the intent is to simply pass data through as-is by default. For example, if a user wanted to use Vector as a Kafka-Pulsar bridge, it would work transparently with no additional configuration. (`text` continues to be a bad name, `raw` is much more indicative of this use case)

Obviously this makes less sense in configurations where users are enriching events. We did discuss a long time ago trying to have these defaults differ based on the rest of the pipeline (e.g. simple pass through defaults to `text`/`raw`, anything adding fields makes the default switch to `json`).

**Comment by leshow** [comment]
I talked to some people using the pulsar plugin and as I understand it they are using it as a raw pass-through (so `text` or `raw` if you want to rename).

**Comment by binarylogic** [comment]
Closing as a result. Thanks @leshow.
