### ISSUE TITLE
Document Kubernetes authentication requirements

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#4633]
We need to very clearly document any requirements needed for Kubernetes access. Such as enabling RBAC or anything else.

@MOZGIII could you respond to this issue with the requirements? I'll get them documented.

For context I had this:

```
Kubernetes [RBAC][urls.kubernetes_rbac] must be enabled for this component to
work. This can be achieved by passing the appropriate flags when starting
the [Kubernetes API server][urls.kubernetes_api_server]:

```bash
kube-apiserver --authorization-mode=RBAC ...
```

For specific permissions, please see the ["Permissions"
section][<%= component_short_link(component) %>#permissions].
```

**Comment by MOZGIII** [comment]
Sure, here goes:

---

Vector requires access to the Kubernetes API, specifically, the `kubernetes_logs` uses the `/api/v1/pods` endpoint to "watch" the pods from all namespaces.

Modern Kubernetes clusters run with RBAC (role-based access control) scheme. RBAC-enabled clusters require some configuration to grant Vector authorization to access to the Kubernetes API endpoints. As RBAC is currently the standard way of controlling access to the Kubernetes API, we ship the necessary configuration out of the box: see `ClusterRole`, `ClusterRoleBinding` and a `ServiceAccount` in our `kubectl` YAML config, and the `rbac` configuration at the Helm chart.

If your cluster doesn't use any access control scheme and doesn't restrict access to the Kubernetes API, you don't need to do any extra configuration - Vector will just work.
Clusters using legacy ABAC scheme are not officially supported (although Vector might work if you configure access properly) - we encourage switching to RBAC.
If you use custom access control scheme - make sure Vector `Pod`/`ServiceAccount` is granted access to the `/api/v1/pods` resource.

**Comment by MOZGIII** [comment]
This is now available in `master`.
