### ISSUE TITLE
Installation script for Raspbian doesn't work

### ISSUE THREAD

**Issue by technetx** [timberio/vector#4669]
### Link to script

```
https://vector.dev/docs/setup/installation/operating-systems/raspbian/
```

### Expected Behavior

Script should download and install correct .deb file.

### Actual Behavior

Error: >>> unsupported arch: armv7-unknown-linux-gnueabihf

### Additional Context

Device: Raspberry PI 4
OS: RaspberryOS(old Raspbian)
Linux raspberrypi 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux

**Comment by Hoverbear** [comment]
I'd love to support armv7 again targeted specifically at this model? It'll likely be the same strategy as with `aarch64`.

**Comment by jamtur01** [comment]
This should now be working.
