### ISSUE TITLE
vector support CLI command

### ISSUE THREAD

**Issue by jamtur01** [timberio/vector#4670]
We want a CLI command that outputs useful information for solving Vector issues and shedding light on bugs.

The command:

```
vector support
```

Should output to `STDOUT` with the option to redirect content to a file.

```
vector support > support.txt
```

The command should output:

1. Vector version and build information from `vector -V`.
2. Vector config from `/etc/vector/vector.toml`.
3. Snapshot of internal metrics and host metrics.
4. Output of `uname -a`.
5. Contents of `/etc/hosts`, `/etc/resolv.conf`, `/etc/nsswitch.conf`.
6. Output of `dmesg`.
7. Vector logs?

**Comment by jszwedko** [comment]
:+1: I'm definitely a fan of this as a way to facilitate supporting users. Do you imagine that it would interact with a running vector? Or it would run vector, as usual, but also output this file?

We should probably try to sanitize as much info as we can (e.g. `dmesg`, `/etc/hosts`, etc., could have sensitive data). We could push that onto users, but I think the experience would be better if we anonymized as much as we could.

**Comment by binarylogic** [comment]
Closing in favor of #4660
