### ISSUE TITLE
Add way to avoid overwriting fields to `json_parser` transform

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#4673]
Requested in discord: https://discordapp.com/channels/742820443487993987/746070591097798688/768262550974234645

The user would like to parse the JSON in a given field (presumably `message`) without overwriting the `timestamp` key.

It's probably worth adding this functionality to the pending `parse_json` remap function as well if users do something like `. = parse_json(.message)`.

**Comment by binarylogic** [comment]
Thanks @jszwedko, we'll cover this with remap. Small nit, could you add the appropriate labels when opening issues? Otherwise, they are more likely to fall through the cracks.

**Comment by JeanMertz** [comment]
Do we still think there's something to be done here?

Currently, this would be the way to go:

```coffee
ts = .timestamp
. |= parse_json(.message)
.timestamp = ts
```

**Comment by jszwedko** [comment]
Ah, yes, I think this issue predates VRL support for parsing JSON. Users can also do:

```
. = merge(object!(parse_json!(.message)), .)
```

To preserve existing fields.

**Comment by jszwedko** [comment]
:D yes, pipelining functions like that would be great.
