### ISSUE TITLE
new source: AWS ECS/Fargate metrics

### ISSUE THREAD

**Issue by drunkirishcoder** [timberio/vector#4683]
When running containers in AWS ECS, you can collect the container metrics via the [task metadata endpoint](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint-v4.html) set as an environment variable. The return is in [JSON](https://docs.docker.com/engine/api/v1.30/#operation/ContainerExport). Vector should have a AWS ECS metrics source that can scrape this endpoint.

**Comment by binarylogic** [comment]
This would be a very welcome addition. I believe you mentioned you had code for this? We'd welcome a PR and assist with getting it integrated.

**Comment by jamtur01** [comment]
Does this need to be a specific source? Could you use the `http` source for this and use a transform for the data?

**Comment by drunkirishcoder** [comment]
@binarylogic yeah I have some rough code. I can open a PR and get some feedback on the whether the approach is good or there's a better way to implement it.

@jamtur01 not as the http source for logs. I don't think that's a fit. but it does behave very similarly to the prometheus metrics source. I remember there are some conversations around separating out the codec parsing from the polling so it's easier to implement similar sources. I'm not sure if that refactoring was ever worked on.

**Comment by jamtur01** [comment]
Yes, I should have been clearer, we had some back and forth on the `http` source for metrics [here](https://github.com/timberio/vector/pull/3984) and I was wondering if we should revisit some abstraction.

**Comment by drunkirishcoder** [comment]
that's acting as a http server for "pushing" metrics into Vector right? This needs the pull model, related to #3532 I would say.

**Comment by jamtur01** [comment]
@drunkirishcoder Argh. Yes - sorry - brain is on melt today clearly. :)

**Comment by drunkirishcoder** [comment]
yeah that makes sense. I copied a big chunk of code from the prometheus source, and that's code should be shared. looking forward to that cleanup.

**Comment by binarylogic** [comment]
Closing since #4698 appears to have closed this.
