### ISSUE TITLE
'postinst' script in Debian package emitted error about usermod command failure

### ISSUE THREAD

**Issue by j-bai** [timberio/vector#4692]
While installing debian package (i.e. 'vector-amd64.deb') on Debian Buster as 'root' user with command 'dpkg -i vector-amd64.deb', following error was emitted at the end:

> usermod: -a flag is only allowed with the -G flag

### Vector Version

```
vector 0.11.0 (486a875 x86_64-unknown-linux-gnu 2020-10-21)
```

### Additional Context
The 'usermod' command involved is in debian package script 'distribution/debian/scripts/postinst', and was last modified by pull request [enhancement: Add vector user to adm in debian packaging #4544](https://github.com/timberio/vector/pull/4544). Basically, the command line was changed from
> usermod -aG systemd-journal vector

to

>usermod --append --gid adm vector
>usermod --append --gid systemd-journal vector

And obviously the command line parameter '--gid' is misused here, at least incorrect on Debian.

**Comment by jszwedko** [comment]
Ah, yes, that should be `--groups`. Thanks for reporting @j-bai
