### ISSUE TITLE
Remap binary operator does not short-circuit

### ISSUE THREAD

**Issue by JeanMertz** [timberio/vector#4706]
The current implementation of the binary operator does not [short-circuit](https://en.wikipedia.org/wiki/Short-circuit_evaluation):

```rust
.foo = false            // false
false && (.foo = true)  // false
.foo                    // true

.bar = true             // true
true || (.bar = false)  // true
.bar                    // false
```

If `false && ...` were to short-circuit, the `...` part wouldn't evaluate. The same applies to `true || ...`.

It's not a given that this is what we want, but I wanted to raise this point to discuss what the most logical solution for Remap is.

https://github.com/timberio/vector/blob/c4c8cb69971e3a57b36018507f719ddc9e96bc94/src/mapping/query/arithmetic.rs#L76-L93

**Comment by binarylogic** [comment]
@JeanMertz if you have time for this sprint let's consider this after you've resolved the blocking 0.12 Remap issues.
