### ISSUE TITLE
Uplift Test Harness

### ISSUE THREAD

**Issue by jamtur01** [timberio/vector#4715]
We want to:

1. Better integrate the test harness into our CI lifecycle.
2. Better equip it to end-to-end testing more capable than our existing integration tests to capture bugs that "real world" users might experience.
3. Add a performance element to the harness to help us identify regressions that users might experience in the wild.

**Comment by jszwedko** [comment]
I broke this down into:

https://github.com/timberio/vector-test-harness/issues/60
https://github.com/timberio/vector/issues/5396
https://github.com/timberio/vector-test-harness/issues/61
