### ISSUE TITLE
Support Elasticsearch AWS authentication

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#474]
AWS [hosts Elasticsearch as a service](https://aws.amazon.com/elasticsearch-service/), and in order to write data to a hosted AWS Elasticsearch cluster you must authenticate. [This guide](https://aws.amazon.com/blogs/security/how-to-control-access-to-your-amazon-elasticsearch-service-domain/) details how you can authenticate against an AWS Elasticsearch cluster. You'll notice it follows the same authentication procedure of any other AWS service. The problem is that the `elasticsearch` sink does not use [rusoto](https://www.rusoto.org/) like our other `aws_*` sinks. Rusoto, automatically handles authentication in the following priority: 

1. Environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`
2. credential_process command in the AWS config file, usually located at `~/.aws/config`.
3. AWS credentials file, usually located at `~/.aws/credentials`.
4. IAM instance profile. Will only work if running on an EC2 instance with an instance profile/role.

Option 4 should currently work, as it requires no changes to the request itself. 1 - 3 effectively obtain credentials by which the request is signed (as far as I understand it). In other words, this change should support methods 1 - 3, just like our other `aws_*` sinks. To handle this, I propose that the user explicitly opt-in (I'm open to better/automatic ways of detecting this):

```toml
[sinks.<sink-id>]
  type = "elasticsearch"
  provider = "aws"
```

In the above configuration, the user explicitly specifies that ES cluster is provided by AWS, and therefore, it should use Rusoto to make the request to the Elasticsearch cluster.

I'm curious if Rusoto allows us to reuse the same code they use internally for other services, enabling us to make authenticated requests to AWS Elasticsearch clusters with little work. If not, I would recommend opening a pull request on that repo so that we can reuse it. I would not recommend implementing this authentication strategy ourselves.

**Comment by binarylogic** [comment]
@bruceg I've assigned this to you since it's important towards our roadmap priorities, but it's not more important than journald or the TLS changes you're working on. Also, this change might require a discussion, if any of this is unclear we're happy to hop onto a quick chat and firm up the requirements.

**Comment by LucioFranco** [comment]
This can be done using rusoto. All of the request signing and credential fetching can be done by [`rusoto_core`](https://docs.rs/rusoto_core/0.37.0/rusoto_core/).

First thing will be to fetch credentials this should be done via [DefaultCredentialsProvider](https://docs.rs/rusoto_core/0.37.0/rusoto_core/struct.DefaultCredentialsProvider.html) which will allow you to fetch the credentials via a future.

Once, you have the credentials you can create a [`SignedRequest`](https://docs.rs/rusoto_core/0.37.0/rusoto_core/signature/struct.SignedRequest.html). Once you've done that you can then call [`sign_with_plus`](https://github.com/rusoto/rusoto/blob/master/rusoto/core/src/client.rs#L178). The next step should be to convert the `SignedRequest` into a `http::Request`. You can see an example of this in the [rusoto hyper client](https://github.com/rusoto/rusoto/blob/master/rusoto/core/src/request.rs#L416).

Doing it this way should produce a `http::Request` that can be returned to our `HttpService` and used with the rest of the es sink.
