### ISSUE TITLE
Capture and save `/benches` data for historical analysis

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#4759]
Once #4758 is complete we should capture the results of our benchmarks and store them somewhere for analysis.

## Requirements

- [ ] Ideally, the benchmarking data would be decoupled from the means of analysis. For example, storing the raw data in an open format on S3 and then using something like Athena to analyze it in-place. If Athena is not sufficient we could load the data into a database.
- [ ] An easy for members of the team to compare historical versions.
- [ ] Report % change since last Vector release in the PR comment mentioned in #4758.

**Comment by jszwedko** [comment]
Quick update on this:

I've been attempting to load the raw criterion measurements into Athena with partitions like:

```
s3://test-artifacts.vector.dev/benches/benches_version=1/environment_version=1/group=files/function=files_without_partitions/value=null/branch=upload-benchmarks-s3/machine=x86_64/operating_system=linux/libc=gnu/threads=8/year=2020/month=12/day=08/rev_count=3501/sha=8a37ff4fe02e11eb7bd6ce9e9ec2010d81cf7965/timestamp=1607456261/raw.csv
```

This should allow us to compare an individual benchmark across time as well as the same benchmark against multiple configurations (like musl vs glibc).

I've been struggling a bit getting Athena to play nice though. When it fails reloading table partitions, the error is pretty opaque:

```
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask
```

AWS support helped me resolve this once (a partition key was missing a value: like `group=/`). I've opened another support ticket to see about this latest incarnation.

**Comment by jszwedko** [comment]
I'm going to mark this as done since we are publishing to S3 now. I'll wait to see how we move forward before we spend more time here.
