### ISSUE TITLE
Partition `aws_cloudwatch_logs` requests

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#476]
Similar to other sinks (`aws_s3`, `elasticsearch`) we need to partition data coming out of the `aws_cloudwatch_logs` sink by `log_group` and `log_stream`. This is slightly different in that the partition key is 2 separate values and does not include the date.

To take a step back, CloudWatch logs is organized by 2 hierarchical concepts: `log_group`s and `log_stream`s. An AWS account can have many `log_group`s (up to 500), and a `log_group` can have many `log_stream`s (infinite).

In the traditional sense, as defined by the CW Agent, a `log_group` [represents a file path by default](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-Configuration-File-Details.html#CloudWatch-Agent-Configuration-File-Logssection) and a log stream [represents an instance_id by default](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-Configuration-File-Details.html#CloudWatch-Agent-Configuration-File-Logssection). For example:

* `log_group` = `/aws/elasticbeanstalk/TimberNodejsAgentCustomConfig-env/var/log/eb-activity.log`
* `log_stream` = `i-01813f03ce9d78642`
* [Demo](http://bens.files.timber.io/fa6caed473e1)

Setting aside the fact that CloudWatch makes this incredibly hard to search, user should be able to set these 2 values to anything they want, and we should probably default to the above since that is the expected behavior.

### Requirements

- [ ] Both the `log_group` and `log_stream` config values should allow variable interpolation, allowing values from the event to be subbed in, which effectively dynamically partitions the data.
- [ ] If an event does not have a specified field, a rate-limited (https://github.com/timberio/vector/issues/418) `warn` level log should be logged and a blank value should be used in it's place.
- [ ] If a `log_group` or a `log_stream` does not exist we should automatically create it since this is what the CW agent does. I'd recommend being reactive. In other words, attempting to write to the log stream and looking for a specific "log stream does not exist" error to trigger a create.
- [ ] Default `log_group` to `{event.file}`
- [ ] Default `log_stream` to `{event.host}`

**Comment by binarylogic** [comment]
I am reopening this because the requirements were not met.

**Comment by LucioFranco** [comment]
Closing in favor of #683
