### ISSUE TITLE
add UnixDatagram to Socket Source

### ISSUE THREAD

**Issue by ivmaks** [timberio/vector#4787]
Nginx uses UnixDatagram when writing to Unix Socker.

https://nginx.org/en/docs/syslog.html

**Comment by alippai** [comment]
@bruceg while the docs says I can use "unix_datagram" only "tcp", "udp" and "unix" is allowed in vector 0.15.0 (according to validate / startup messages). Is this WIP?

**Comment by jszwedko** [comment]
Hi @alippai . It looks like there is a documentation issue on the website, but `unix_datagram` and `unix_stream` are supported on the `socket` source as `mode`. They are not yet supported on the `socket` sink though. Are you trying to use them there?

**Comment by alippai** [comment]
@jszwedko oh, I checked the `syslog` source type (as NGINX is syslog protocol)

**Comment by jszwedko** [comment]
@alippai aha, we probably need a separate issue to add support there then.

**Comment by jszwedko** [comment]
Opened https://github.com/timberio/vector/issues/8509
