### ISSUE TITLE
Ensure that all components report the same basic metrics

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#4841]
As part of the work on `vector top` it seems like we should ensure that all components report the basic metrics we expect to show:

* Number of errors
* Number of events processed (or emitted in the case of sources)
* Bytes processed (or emitted in the case of sources); note that all components should probably have the same concept of "bytes processed" to ensure that the numbers match up

It would be nice to do this in a way that we check that the component has these metrics at build time to avoid neglecting to include them as we add additional components.

We should also consider how to report these particular metrics in a typed way. Right now, the vector API is just relying on string matching to find the metrics; which seems error prone.

**Comment by binarylogic** [comment]
@lucperkins is working on the docs and I think that work will help surface inconsistencies.

**Comment by jszwedko** [comment]
Reopening, I'd really like to see this happen as a compile-time check to ensure that we have the expected metrics for each component.

**Comment by jamtur01** [comment]
Closed in #5304

**Comment by jszwedko** [comment]
@jamtur01 did you link to the correct PR? https://github.com/timberio/vector/pull/5304 doesn't seem to cover this.

I do, however, think it is covered by the new issues I opened: #6008 and #6007. This already happened for transforms in https://github.com/timberio/vector/pull/5492

**Comment by jamtur01** [comment]
@jszwedko Yes - you are right - this was supposed to be on the IAM ticket. Will fix.
