### ISSUE TITLE
Support using capture groups in `replace`

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#4865]
Spun off from https://github.com/timberio/vector/pull/4861#pullrequestreview-523413392

When using a regex to replace text it can be useful to use the capture groups from the regex. Maybe something like:

```
remap("foo_bar_baz", /foo_(.*)_baz/, "\1") // bar
remap("foo_bar_baz", /foo_(?P<a>.*)_baz/, "$a") // bar
```

We could potentially use `$1` instead of `\1` (or allow them both). `\0` or `$0` should match the whole text matched by the pattern.

**Comment by JeanMertz** [comment]
Closing this, as capture groups are now supported:

```coffee
$ replace("foo_bar_baz", r'foo_(.*)_baz', "$1")
"bar"

$ replace("foo_bar_baz", r'foo_(?P<a>.*)_baz', "$a")
"bar"
```
