### ISSUE TITLE
syslog sink

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#4867]
It'd be useful to support a `syslog` sink for vector to interoperate with more downstream providers, which often provide a syslog input (like Splunk, Graylog, Rsyslog, etc.).

I'd suggest supporting both RFC 5424 and RFC 3164.

I'd also suggest allowing embedding of fields as structured fields for RFC 5424.

**Comment by mcarbonneaux** [comment]
this while be interesting for exemple to tranform RFC 3164 to RFC 5424... 
and for exemple add structured field information to RFC 5424....

**Comment by jszwedko** [comment]
This is the same as #6863 so I'll close this for that one.
