### ISSUE TITLE
Provide Cue configuration for the Vector CLI

### ISSUE THREAD

**Issue by lucperkins** [timberio/vector#4877]
The Vector CLI is currently fairly simple but it will almost certainly grow in complexity over time, and we'll need to generate reference documentation for it. To that end, we should provide typesafe Cue configs that can be used by the website to generate a CLI reference. These configs may have additional uses, though that is TBD.

**Comment by jamtur01** [comment]
Oh nice! +1.

**Comment by jszwedko** [comment]
Maybe we can use the same config to drive https://github.com/timberio/vector/issues/1658 (or use the output of _that_ to drive the cue docs).

**Comment by lucperkins** [comment]
@jszwedko I was hoping that Clap had a built-in ability to generate JSON, like [Cobra](https://github.com/spf13/cobra) does, but alas, no dice. I'm certainly open to a generated approach in the future.
