### ISSUE TITLE
expose librdkafka stats for kafka source/sink as part of `internal_metrics` source

### ISSUE THREAD

**Issue by awangc** [timberio/vector#4889]
### Current Vector Version

```
0.10
```

### Use-cases

librdkafka has internal metrics which are being logged by vector when `librdkafka_options."statistics.interval.ms"` is non zero. It will be very useful if these can be exported as prometheus metrics under the `internal_metrics` source.

### References

- https://github.com/edenhill/librdkafka/blob/master/STATISTICS.md
- https://github.com/fede1024/rust-rdkafka/blob/master/src/client.rs#L79-L85

**Comment by binarylogic** [comment]
Thanks @awangc, agree. We'll prioritize accordingly.

For posterity, I'd like to audit other available metrics and include them as necessary.

**Comment by skupjoe** [comment]
+1
We're using Vector for heavy Kafka consumption/parsing/producing and very eager to be able to monitor this!

**Comment by binarylogic** [comment]
To update, the work for this is mostly complete but is currently blocked by #6412. We are working to resolve that now.
