### ISSUE TITLE
Extract a list of fields used in Remap language so it can be unified with the template string support

### ISSUE THREAD

**Issue by FungusHumungus** [timberio/vector#4904]
It would be useful to unify the Remap language with our existing template strings support. Ref #3836 

The current template string allows a component to extract a list of fields used by the template string. For example, the Loki sink will use this list to remove any fields used in generating the label fields from the main message. It is not as straightforward to support this with Remap as there is some ambiguity as to whether a field is actually used or not.

An RFC is needed to plan the best way to tackle this.

Note, in my [comment](https://github.com/timberio/vector/issues/3836#issuecomment-721129824) I also said it would be difficult to determine if the syntax was the old style templates or Remap. I have gone back on this now, I think I just didn't fully understand how the templates worked. That should actually be fairly easy to determine by looking ot which non alphanumeric characters are used in the field specification. The template only allows a very limited range here, whereas Remap allows much more. So this is no longer a concern.

**Comment by binarylogic** [comment]
Closing, please see https://github.com/timberio/vector/pull/4905#issuecomment-753670799.
