### ISSUE TITLE
Update problematic `api` tests to run in different processes

### ISSUE THREAD

**Issue by leebenson** [timberio/vector#4925]
API tests are currently failing in #4886 due to shared global state. This isn't simple to isolate currently, due to the global nature of tracing and metrics.

A workaround could be using [rusty-fork](https://crates.io/crates/rusty-fork), but known disadvantages are:

- It doesn't currently [support async tests](https://github.com/AltSysrq/rusty-fork/issues/9).
- Wrapping tests in a `rusty_fork_test!` macro disables code analysis in IDEs, making it harder to write/maintain tests.

Need to investigate whether there's an option to combine with `#[tokio::test]` and/or create a thin wrapping function which executes the test in a separate runtime, so tests themselves can be written as regular functions.

**Comment by jszwedko** [comment]
I have no idea how much effort this would be, but my initial thought would be to get rid of the global state and have metrics be associated with `Topology`.

**Comment by leebenson** [comment]
👍 I think that's a better approach; this is the kick-the-can-down-the-road option. I don't know exactly how much ground this would shift, but in the API for example, there'd be a fair amount of reworking to not invoke `capture_metrics()` directly.
