### ISSUE TITLE
Use random sampling when no message field is specified

### ISSUE THREAD

**Issue by lucperkins** [timberio/vector#4940]
At the moment, the [`sampler`](https://vector.dev/docs/reference/transforms/sampler) has a `key_field` option that is used to determine whether any given event is sampled. The default for that option is `message`. One drawback of this approach is that if the `message` field is missing, then *no events* are sampled, which produces behavior that would be unexpected to less-experienced Vector users. A more intuitive behavior for the transform might be to perform true random sampling if no key is specified.

This branch of the decision tree would be modified:

* **Previous**:  no `key_field` specified + no `message` field in event --> sample based on `message` field anyway --> no sampler output
* **Proposed**: no `key_field` specified --> random sampling

**Comment by ktff** [comment]
#4918 fixes this behavior.
