### ISSUE TITLE
The `sampler` transform should take a configurable window that the `rate` is applied within

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#498]
If I understand correctly, the `rate` option is applied on a per second basis. This window needs to be configurable via a `window` option that takes an `int` representing the window size in seconds.

**Comment by karlseguin** [comment]
Then the documentation probably shouldn't define `rate` as:

> The maximum number of events allowed per second.

**Comment by lukesteensen** [comment]
Yep, that's a documentation bug. Sorry about that! I'll push a fix shortly.
