### ISSUE TITLE
Consider erroring for unconfigured outputs

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#4994]
### Current Vector Version

```
vector 0.11.0 (g0bebc74 x86_64-unknown-linux-gnu 2020-11-11)
```

### Use-cases

With the following config:

```toml
[sources.in]
  type = "stdin"

[sources.in2]
  type = "generator" # required
  lines = ["Line 1", "Line 2"] # required

[sinks.my_sink]
  type = "console"
  inputs = ["in"]
  encoding.codec = "json"
```

It would be nice to have a warning or error that `in2` is not connected to any sinks. For large topologies, this type of unconnected sink error is likely to be more common.

**EDIT** There is a warning :sweat: . I just missed it.

Current logs:

```
Nov 11 19:54:27.163  INFO vector::app: Log level is enabled. level="trace"
Nov 11 19:54:27.164  INFO vector::app: Loading configs. path=["/tmp/tmp.toml"]
Nov 11 19:54:27.177  WARN vector::config::compiler: Source "in2" has no consumers
Nov 11 19:54:27.179  INFO vector::sources::stdin: Capturing STDIN.
Nov 11 19:54:27.179  INFO vector::topology: Running healthchecks.
Nov 11 19:54:27.179  INFO vector::topology: Starting source. name="in2"
Nov 11 19:54:27.179  INFO vector::topology::builder: Healthcheck: Passed.
Nov 11 19:54:27.179  INFO vector::topology: Starting source. name="in"
Nov 11 19:54:27.180  INFO vector::topology: Starting sink. name="my_sink"
Nov 11 19:54:27.180 TRACE source{component_kind="source" component_name=in2 component_type=generator}: vector::internal_events::generator: Received one event.
Nov 11 19:54:27.180  INFO vector: Vector has started. version="0.11.0" git_version="v0.9.0-1303-g0bebc74" released="Wed, 11 Nov 2020 15:07:20 +0000" arch="x86_64"
Nov 11 19:54:27.182 TRACE vector: Beep.
Nov 11 19:54:27.194 TRACE source{component_kind="source" component_name=in2 component_type=generator}: vector::internal_events::generator: Received one event.
Nov 11 19:54:27.195 TRACE source{component_kind="source" component_name=in2 component_type=generator}: vector::internal_events::generator: Received one event.
Nov 11 19:54:27.195 TRACE source{component_kind="source" component_name=in2 component_type=generator}: vector::internal_events::generator: Received one event
....
```

`vector validate` does output a warning:

```
Nov 11 19:56:05.348  WARN vector::config::compiler: Source "in2" has no consumers
√ Loaded ["/tmp/tmp.toml"]
√ Component configuration
√ Health check `my_sink`
--------------------------
                 Validated
```

**Comment by ktff** [comment]
The warning is present in the run logs,
``` 
Nov 11 19:54:27.164  INFO vector::app: Loading configs. path=["/tmp/tmp.toml"]
Nov 11 19:54:27.177  WARN vector::config::compiler: Source "in2" has no consumers
Nov 11 19:54:27.179  INFO vector::sources::stdin: Capturing STDIN.
```
but I guess it's easy to miss it. 

I think we should make this a hard error. It would make the configuration a bit stricter, but it would help users to address two scenarios:
- The unconnected component should have been connected but there is a mistake in the configuration, like misspell or using old config files in combination with new ones.
- The unconnected component is really not used anymore so it's a performance/maintenance burden.

**Comment by jszwedko** [comment]
Yeah, it definitely is. I don't know how I missed that.

I'll repurpose this issue to be about deciding whether to make it a hard error.

**Comment by ktff** [comment]
I also missed it in the first read, that just shows how easy it is.

**Comment by ktff** [comment]
On second thought, this sounds like it's use case of `deny_warnings` in `validate` command. If users want stricter compilation for the reasons mentioned [here](https://github.com/timberio/vector/issues/4994#issuecomment-725664423) then they can use `validate` command with `deny_warnings`.

**Comment by jszwedko** [comment]
True, I agree. I'll close this for now. We can revisit the default if more users run into it.
