### ISSUE TITLE
Check for conflicting port usage as part of config validation

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5013]
I was reading https://github.com/timberio/vector/issues/4031#issuecomment-699700788 and it wasn't clear if we already do this, but it makes sense to check for resource conflicts as part of configuration validation. For example, if an `http` source and `socket` source are configured to listen on the same port we should exit with a configuration error.

cc @lukesteensen @ktff

**Comment by ktff** [comment]
With #4031 and #4827(#4996) we will check for conflicting resource usages, like port, during config validation for all components, so I'll close this.
