### ISSUE TITLE
Default configuration loading to a directory and pattern

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5035]
Currently, our various installation methods look for an exact `vector.toml` file. For example, the `.deb` and `.rpm` packages are hardcoded to look for `/etc/vector/vector.toml`. Users like to split their Vector files up, usually by pipeline, and we should allow them to do so. Instead, Vector should look for `toml` (`json` and `yaml` when we support it) in the `/etc/vector` directory:

```
vector --config /etc/vector/*.toml
```

**Comment by jamtur01** [comment]
I am a so-so on this idea. People can change this default once Vector is installed but a *.{toml|json|etc} by default seems a little broad.

**Comment by binarylogic** [comment]
What else would be in that directory though? I don't see any risk to enabling this other than making setup and maintenance easier.

**Comment by jamtur01** [comment]
Could be anything. Variant or old config files for example. I think the capability to do this exists but the need to change the default? Less convinced.
