### ISSUE TITLE
Represent Kubernetes `values.yaml` schema as cue data

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5036]
As part of documenting Kubernetes, we need to expose the various fields allowed in the `values.yml`. This should be encoded in our cue data in the same way that our components document their `configuration`.

**Comment by MOZGIII** [comment]
Helm supports `values.schema.json` now: https://helm.sh/docs/topics/charts/
I think we should focus on that instead first, and then use the JSON Schama in .cue files to extract the data. It should be possible to do.

**Comment by binarylogic** [comment]
See https://github.com/timberio/vector/issues/5253#issuecomment-841477489

**Comment by spencergilbert** [comment]
Issue moved to [timberio/helm-charts #13](https://github.com/timberio/helm-charts/issues/13) via [**ZenHub**](https://www.zenhub.com/)
