### ISSUE TITLE
Preserve types when encoding events across sinks

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#504]
Now that we support types in our events we need to ensure those types are preserved when encoding. Currently, we only support `json` encoding across the various sinks, and we need test and make sure types are supported when encoding.

**Comment by binarylogic** [comment]
@LucioFranco I assigned this to you, but wanted to confirm that this was the behavior across all sinks. If so, do you confidently feel we can close this?

**Comment by LucioFranco** [comment]
Yes, this is complete. To clarify, we've added more typed serialization https://github.com/timberio/vector/blob/master/src/event/mod.rs#L168 thus any sink that uses serde to encode the event values will use this type preservation.
