### ISSUE TITLE
Prepare a guide for sidecar deployment at Kubernetes

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#5040]
This needs to:
1. Explain what is sidecar deployment, and use cases for it.
2. Show how to deploy Vector as a sidecar.
3. Request users to express their interest in the sidecar deployment model to us.

This does not require Kubernetes metadata annotations.

**Comment by binarylogic** [comment]
Closing, see https://github.com/timberio/vector/issues/5254#issuecomment-762379096
