### ISSUE TITLE
Flaky `timely_shutdown_docker`

### ISSUE THREAD

**Issue by ktff** [timberio/vector#5046]
The test is failing because started vector instance exited with non 0 exit code. It isn't config since then it wouldn't be flaky. Also one clue is the lack of shutdown logs. That mostly points to either crash, or more probably we never actually started which narrows the problem space.

Another possibility is that `docker` is misbehaving on CI, but in that case we should make source resistant to it.

https://github.com/timberio/vector/runs/1403149743

**Comment by jszwedko** [comment]
I looked a bit at this last week but couldn't reproduce locally. I tried running the test in a loop until it failed, but I never got a failure.

**Comment by bruceg** [comment]
I have found no test runs with this failure before https://github.com/timberio/vector/commit/45b744c2bb89ea7824be318ab680d784883aa5b1 However, as noted, it is not consistent so the actual trigger may be a few commits earlier. It is not obvious why that commit should have anything to do with a docker shutdown test.

**Comment by bruceg** [comment]
Could it be connected with https://github.com/timberio/vector/commit/6d90a084e978ffb638fb3d3cbc105f7e0c71f479? In particular, this commit adds the `"-v"` option to vector if it's not being run "quiet". Further, the command is being run with a pipe on stdout. That pipe is *never read*, which introduces the possibility of vector blocking when the pipe fills up. Adding the verbose option could (occasionally) be pushing the output up to the pipe buffer size.

Does this make sense?
