### ISSUE TITLE
Add rustfmt.toml to project root

### ISSUE THREAD

**Issue by spacejam** [timberio/vector#507]
A lot of people run automatic code formatters, which basically will result in a huge amount of change in random PRs unless there is a default rustfmt configuration provided in the root that will keep them tamed. This also is nice because people who contribute don't need to disable their formatter when they work with this project.

**Comment by hdost** [comment]
https://github.com/timberio/vector/blob/master/CONTRIBUTING.md#code-style According to this there's not a custom format that is being used. I have created a basic PR.
