### ISSUE TITLE
Avoid Result types as function arguments

### ISSUE THREAD

**Issue by spacejam** [timberio/vector#508]
I've noticed [places where Result types were passed in as arguments](https://github.com/timberio/vector/blob/59fa8eff995645dd71481a06c30a019ea54598b7/src/topology/mod.rs#L33), and later on handled. Generally, this will make debugging more difficult, as it causes a bunch of random log messages etc... being introduced between when the actual error happened and when it's made visible to the user. Generally you don't see Results as arguments for most functions, as they are usually meant to bubble up through the control hierarchy of a program. In cases where nothing can be done about an error but it indicates the program was misconfigured, it's probably best to just panic immediately to give users an "easy" backtrace to look at.

**Comment by binarylogic** [comment]
@kirillt this is resolved, correct?

**Comment by kirillt** [comment]
@binarylogic right, resolved.
