### ISSUE TITLE
Default the API to use a unix socket

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5083]
We'd like the API to be on by default. In order to respect security concerns, the API should communicate through a Unix socket by default but can be configured for different addresses.

**Comment by jszwedko** [comment]
I think `docker`s handling of this could be good inspiration:

https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-socket-option

Specifically, I like that they allow binding to multiple interfaces.

**Comment by leebenson** [comment]
Some initial considerations that strike me (some of these may have simple/known answers):

- What's the default socket location? `/var/run`? Is this likely to change per OS?
- What are the default permissions, especially in instances where Vector is built from source and may not have a user/group associated?
- AF_UNIX is supported on Windows 10, since ~2018. Do we need to support older versions?
- If the socket location is likely to change (say, between *nix / Windows), should `vector top` default to the location per the OS it's running on?
- What might need changing in our Warp config to support Unix sockets? (https://github.com/seanmonstar/warp/issues/101 suggests it's possible, but the API needs further research.)
- Does this affect the WebSocket query/subscription clients? Both default to `http(s)://` / `ws(s)://` right now. Does anything need changing to accommodate local sockets?
- Does binding to multiple interfaces introduce any considerations / complications?
- Does the `url::Url` type accommodate local socket paths, or would we need to do something else?
- Do any special considerations need to be given for accepting multiple clients over a single local socket?

**Comment by jszwedko** [comment]
Good questions, some initial thoughts:

> Some initial considerations that strike me (some of these may have simple/known answers):
> 
>     * What's the default socket location? `/var/run`? Is this likely to change per OS?

I'd say `/var/run/vector.sock` would be reasonable. I think Windows would be the only outlier.

>     * What are the default permissions, especially in instances where Vector is built from source and may not have a user/group associated?

I think it could be created using whatever user/group the process is running as. This would be `vector` for package installations.

>     * AF_UNIX is supported on Windows 10, since ~2018. Do we need to support older versions?

It looks like docker uses named pipes for Windows: https://github.com/moby/moby/blob/8e610b2b55bfd1bfa9436ab110d311f5e8a74dcb/client/client_windows.go#L4

We could opt to do the same. I'm less familiar with the Windows ecosystem.

>     * If the socket location is likely to change (say, between *nix / Windows), should `vector top` default to the location per the OS it's running on?

Yeah, I think it is reasonable to default based on the build platform of the binary. For Windows this might be the named pipe, for everything else it'd be `/var/run/vector.sock`.

**Comment by leebenson** [comment]
I guess another obvious point I overlooked is: If we're using a local socket by default, neither the playground nor the GraphQL API are accessible via a browser.

`vector top` would work, but everything else is locked down.

Are we okay with that? Is this reason enough just to stick with `127.0.0.1`?

**Comment by binarylogic** [comment]
cc @Hoverbear. I am ok with that. Wouldn't the GraphQL playground and API be accessible to a local browser still?

**Comment by leebenson** [comment]
It would if the browser can navigate/serve from a local socket address (can it? never tried it) I know curl can do it with `--socket`, but it's unusual and probably unexpected in any case.

`http://127.0.0.1/playground` is a bit more aligned with the norm, IMO.

**Comment by jamtur01** [comment]
+1 to 127.0.0.1.

**Comment by jszwedko** [comment]
:thinking: I feel like the more common case for vector will be running on a remote server where there wouldn't be a browser. If they access the API, they'll likely need to jump through some hoops anyway (like exposing the API to an external interface) so I don't think it is unreasonable to have them enable the API bound to a particular port for HTTP traffic at that point.

**Comment by leebenson** [comment]
After further discussion, I don't think a socket is a viable approach. It limits the use-case to just `vector top` running on the same system, and doesn't offer a satisfying answer for enabling the wider API/playground/web UI with at least augmenting with a network proxy.

Even though a socket is perhaps slightly more secure than a port equivalent, [early user feedback](https://github.com/timberio/vector/pull/5114#issuecomment-731018408) suggests it may still be surprising to some, reducing the distinction further.

I personally think our best approach at this stage is to leave the API off by default, but perhaps reword the message the user will see if they attempt `vector top` to make it really clear what they need to do to enable it. Maybe even link to the API docs (when they're done.)

**Comment by quentinmit** [comment]
Is there a separate issue somewhere for *optional* Unix socket support? I don't want to open a TCP port (with no authentication) when I could use a Unix socket with limited permissions.

I don't understand the analysis of the "early user feedback" that was linked; the linked comment is asking for zero ports by default, but when there is an open socket, it is also preferring a Unix socket - "us more senior/old-timers would be fairly surprised at a logging agent opening an unexpected port, even on a UNIX socket."

**Comment by jszwedko** [comment]
> Is there a separate issue somewhere for _optional_ Unix socket support? I don't want to open a TCP port (with no authentication) when I could use a Unix socket with limited permissions.
> 
> I don't understand the analysis of the "early user feedback" that was linked; the linked comment is asking for zero ports by default, but when there is an open socket, it is also preferring a Unix socket - "us more senior/old-timers would be fairly surprised at a logging agent opening an unexpected port, even on a UNIX socket."

Thanks the bump on this. I agree it should be an option to have the API server bind to a unix socket. Would you want to open a new feature request?
