### ISSUE TITLE
Incorrect Log Level Message

### ISSUE THREAD

**Issue by specterz** [timberio/vector#5084]
### Vector Version

```
vector 0.11.0 (gb8f83d7 x86_64-unknown-linux-musl 2020-11-16) running on Docker
```

### Vector Configuration File

```bash
docker run \
  --network host \
  -v /etc/vector/vector.toml:/etc/vector/vector.toml:ro \
  --env LOG=debug \
  --restart always \
  timberio/vector:nightly-alpine
```

### Expected Behavior

Docker logs should indicate correct log level. e.g. debug 

### Actual Behavior

Docker logs indicate debug level as "info"

### Example Data

```
Nov 17 18:18:27.375  INFO vector::app: Log level is enabled. level=**"info"**
```

### Additional Context

https://discord.com/channels/742820443487993987/746070591097798688/778324625439588433

**Comment by juchiast** [comment]
This does not need docker to be reproducible.
