### ISSUE TITLE
Consider feature gating dependencies that pull in many others

### ISSUE THREAD

**Issue by spacejam** [timberio/vector#509]
Vector has a surprising number of dependencies that it requires to build, which can lead to editors becoming unresponsive if they do much automatic analysis. The [cargo tree](https://github.com/sfackler/cargo-tree) command reveals that some of the big offenders are rusoto, hyper, tokio-trace and tower, where 4 different versions of the same things are being pulled in. In some cases it may lower contribution and deployment friction to feature gate some of the functionality provided through these different large redundant libraries.

**Comment by binarylogic** [comment]
This is done.
