### ISSUE TITLE
Allow for templating in the `elasticsearch.index` field

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5099]
We should allow for our templating language in the `elasticsearch` `index` field. This allows users to dynamically route events to different indices based on event data.

**Comment by spencergilbert** [comment]
I'm fairly sure this is supported today!

**Comment by binarylogic** [comment]
Nice! Thanks.

**Comment by jszwedko** [comment]
Just confirming support:

https://github.com/timberio/vector/blob/c357da46928b23db5016d6b5da17b44c49fb73e3/src/sinks/elasticsearch.rs#L152
