### ISSUE TITLE
Drop futures01

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#5103]
Tracking issue for dropping futures01 usage.

I thought there was an issue for this already, but I couldn't find it. I know some work is happening towards it already (like #4888).

**Comment by fanatid** [comment]
Noticed that we have dependencies which use futures01:

- [ ] `tokio01-test`
- [ ] `tokio-retry` (#5113)
- [ ] `task-compat` (#5113)

**Comment by ktff** [comment]
@pablosichert there shouldn't be anything left that's blocking this.
