### ISSUE TITLE
GCP Stackdriver Logs Sink Not Passing Instance Id 

### ISSUE THREAD

**Issue by scott-johnson-recursion** [timberio/vector#5105]
### Vector Version

```
vector 0.10.0 (g0f0311a x86_64-unknown-linux-gnu 2020-07-22)
```

### Vector Configuration File

```
[sinks.out]
  inputs = ["in"] # required
  log_id = "vector-logs" # required
  project_id = "my-project-id" # required
  type = "gcp_stackdriver_logs" # required
  resource.type = "gce_instance"
  resource.projectId = "my-project-id"
  resource.instanceId = "12341234123412341234"
  resource.zone = "us-east1-b"
  credentials_path = "/etc/google/auth/example.json"
```

### Expected Behavior

Instance ID should be a part of the instance_id label within the stackdriver log. 

### Actual Behavior

The other labels (project_id and zone) are both present in stackdriver but the instance_id label is blank. 

``` 
resource: {
  labels: {
   instance_id: ""    
   project_id: "my-project-id"    
   zone: "us-east1-b"    
  }
  type: "gce_instance"   
 }
```
### Example Data

Stackdriver API post is successful: 
```
 DEBUG http: vector::sinks::util::http: sending request. uri=https://logging.googleapis.com/v2/entries:write method=POST
Nov 18 22:16:29.730 DEBUG http: vector::sinks::util::http: response. status=200 version=HTTP/1.1
Nov 18 22:16:29.731 TRACE sink{name=out type=gcp_stackdriver_logs}:request{request_id=23}: vector::sinks::util::sink: Response successful. response=Response { status: 200, version: HTTP/1.1, headers: {"content-type": "application/json; charset=UTF-8", "vary": "X-Origin", "vary": "Referer", "vary": "Origin,Accept-Encoding", "date": "Wed, 18 Nov 2020 22:16:29 GMT", "server": "ESF", "cache-control": "private", "x-xss-protection": "0", "x-frame-options": "SAMEORIGIN", "x-content-type-options": "nosniff", "accept-ranges": "none", "transfer-encoding": "chunked"}, body: b"{}\n"
```

**Comment by bruceg** [comment]
This is because the GCP stackdriver logs sink does not actually support the instance ID field, and only accepts this config option because I missed the flag to deny unknown fields. We will add support for this field.

**Comment by bruceg** [comment]
Hmm, I think I misread this issue. The labels (such as `projectId`, `zone` and `instanceId` in your config) are passed on as-is to the request. No special handling is done that would cause a change to only the one label. Is it possible this label is being altered by Google?

**Comment by bruceg** [comment]
Ok, I have tested the config and found the issue, and it is a typo in the posted config file. It should read:
```
…
resource.type = "gce_instance"
resource.instance_id = "12341234123412341234"
resource.zone = "us-east1-b"
…
```
The `resource.project_id` field does not appear to be necessary, as stackdriver is copying it into the labels from the top-level `project_id`.

**Comment by scott-johnson-recursion** [comment]
Thank you! That fixed it. You might update the documentation [here](https://vector.dev/docs/reference/sinks/gcp_stackdriver_logs/#resource) to have an example with the instance_id since it showed this under the label example and I assumed camel case would also be used for the instance id. ```resource.projectId = "vector-123456"
resource.zone = "Twilight"```
