### ISSUE TITLE
Add `path` event key to `http` source

### ISSUE THREAD

**Issue by samgiles** [timberio/vector#5112]
I'd like to be able to use the path used when sending to the `http` source to change the `key_prefix` in the s3 sink.

### Current Vector Version

```
vector 0.10.0 (g0f0311a x86_64-apple-darwin 2020-07-22)
```

### Use-cases

We have a custom built tool that batches logs to S3 and depending on the path we use a different key prefix in S3, I want to use vector as a drop in replacement.  To do that I need to be able to use the path from the http request and include it as part of the event.

```
[sources.in]
  type = "http"
  address = "0.0.0.0:80" 
  encoding = "json"

[sinks.out]
  type = "aws_s3"
  inputs = ["in"]
  ...
  key_prefix = "{{ path }}/%Y/%m/%d/"
```

**Comment by samgiles** [comment]
I can probably contribute this change unless there's some changes imminent to this here: https://github.com/timberio/vector/issues/2414

If not it looks like I'll need to add something to the `SimpleHttpSource` here: https://github.com/timberio/vector/blob/c357da46928b23db5016d6b5da17b44c49fb73e3/src/sources/http.rs#L71?

**Comment by jszwedko** [comment]
@samgiles Thanks for reporting! I agree that that'd be useful. I don't believe there are any imminent plans to change how that metadata is added. I think the place you identified is the best place to do it.

**Comment by binarylogic** [comment]
@samgiles that would be fine for now. We do have a schemas project on the roadmap, but it's unclear exactly how that will work out. Your proposal should be fine for now.

**Comment by jszwedko** [comment]
I think we should add this same support to the `logplex` and `prometheus_remote_write` sources for consistency.

Additionally, as noted in https://github.com/timberio/vector/pull/5191, I think we should just call it `path`, but have a `path_key` configuration key (similar to the `host_key` configuration we have on some sources) to let the users choose a different field to put that metadata into.
