### ISSUE TITLE
Allow for HTTP in the `vector` source and sinks

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5124]
A user requested the ability to use the HTTP protocol with the `vector` source and sinks. They prefer this protocol since it:

1. Implements application-level acknowledgment.
2. Is easy to load balance.
3. Takes advantage of the adaptive concurrency feature.
4. Compression.
5. Fits into existing HTTP based workflows and configuration.
6. All of the other benefits that HTTP brings.

The obvious downside is batching, but that can be reduced.

cc @lukesteensen for approval

**Comment by lukesteensen** [comment]
Yes, I think we should deprecate the old proto-over-tcp implementation in favor of HTTP with something like CBOR for serialization.

> The obvious downside is batching, but that can be reduced.

Batching is a good thing :slightly_smiling_face: but we can also implement streaming bodies to keep the latency as low as possible.

**Comment by eeyun** [comment]
Closing this issue as written. We've decided in the RFC process to instead implement vector to vector comms in GRPC. Opening a new issue to track this work.
