### ISSUE TITLE
Prepare a real-world like Kubernetes cluster deployment dev env

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#5125]
We already have a bare-bones demo, but I feel like we need a more complicated deployment example that will contain a whole modern observability stack, including all the third-party things we integrate with (Prometheus operator, grafana, etc).

I already have a reasonable setup at hand that I use to test vector with, so I'll just adapt it, and port over to be able to share it.

This will be very useful to iterate on our grafana dashboards.

**Comment by jamtur01** [comment]
Can you add it to https://github.com/timberio/vector-demo please.

**Comment by MOZGIII** [comment]
I'm planning to use a different layout (Helm vs kubectl based). How about we chat about it tomorrow?

**Comment by MOZGIII** [comment]
I decided this image can grow out of proportion as defined, so I'm changing the scope of it is to just setup the initial EKS cluster version, suitable for grafana dashboard development. This limited scope is completed, so I'm closing this.
The rest of the tasks related to that dev env are at the https://github.com/timberio/vector-k8s-dev-env/issues
