### ISSUE TITLE
Allow setting UDP socket recv buffer sizes

### ISSUE THREAD

**Issue by lukesteensen** [timberio/vector#5127]
For traditional syslog setups using UDP, setting the size of the recv buffer on the socket is an important tool for tuning throughput. On the relevant platforms, Vector should allow configuring this value and set it via [`setsockopt`](https://docs.rs/nix/0.19.0/nix/sys/socket/fn.setsockopt.html) before binding to the socket.

**Comment by pablosichert** [comment]
Interestingly, Tokio has [`TcpSocket::set_recv_buffer_size`](https://docs.rs/tokio/1.0.2/tokio/net/struct.TcpSocket.html#method.set_recv_buffer_size), but doesn't have any `set_recv_buffer_size` method on [`UdpSocket`](https://docs.rs/tokio/1.0.2/tokio/net/struct.UdpSocket.html).

We can still set it by getting the `RawFd` and using [`libc::setsockopt`](https://docs.rs/libc/0.2.82/libc/fn.setsockopt.html).  This requires `unsafe`, but should work both on
- unix: https://linux.die.net/man/2/setsockopt
- windows: https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-setsockopt

Alternatively, we could contribute `set_recv_buffer_size` for UDP sockets to `mio`/`tokio`.

**Comment by pablosichert** [comment]
Filed a PR to `mio`: https://github.com/tokio-rs/mio/pull/1441.

**Comment by pablosichert** [comment]
Do we want to add this option to
- every source/sink that uses a TCP/UDP socket
- syslog source via TCP/UDP
- any of the above, but only for UDP sockets

The implementation effort would be roughly the same, just asking if we need that level of granularity in the other modules.

**Comment by jamtur01** [comment]
I vote 1. every source/sink that uses a TCP/UDP socket but @binarylogic and @lukesteensen probably have thoughts here.

**Comment by pablosichert** [comment]
I'd suggest adding a `socket` option to all sources/sinks that use a TCP/UDP socket, and group `the send_buffer_bytes`, `receive_buffer_bytes`, and (for TCP sockets) the existing `keepalive` option beneath that.

What do you think?

**Comment by binarylogic** [comment]
@pablosichert we don't have a `socket` option on components that build ontop of the `socket` source:

https://master.vector.dev/docs/reference/sources/syslog/

Notice that `mode`, `address,` etc are at the root level for that source. Why not add those as root level options?

**Comment by pablosichert** [comment]
Was afraid that on the top level they seem either to specific or may clash. But since the options you mentioned are even more general, that seems fine.

**Comment by lukesteensen** [comment]
We should be able to have a shared `SocketOptions` struct or similar that we can embed in the relevant configs and choose whether or not to `#[serde(flatten)]` to the root level. I agree that they should be fine at the root level, but it shouldn't be a big deal to change our minds later.
