### ISSUE TITLE
Include topic in events from Kafka source

### ISSUE THREAD

**Issue by spencergilbert** [timberio/vector#5143]
### Current Vector Version

```
vector 0.11.0 (g9806442 x86_64-unknown-linux-musl 2020-11-17)
```

### Use-cases

We'd like to reference the Kafka topic an event originated from downstream, other log aggregators support similar metadata - [Logstash Kafka metadata](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-kafka.html#_metadata_fields) 

### Attempted Solutions

The only way it seems possible today is to create a sink per topic and based on the originating sink add a field for the topic. This is manageable for a small number of topics but can't scale.

### Proposal

Vector should know the topic it's retrieving messages from in the request, so it should be possible to extract that and include it in the event schema.

### References

[Logstash](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-kafka.html#_metadata_fields)
[Kafka source fields](https://vector.dev/docs/reference/sources/kafka/#fields)

**Comment by jamtur01** [comment]
Also worth noting is #1150.
