### ISSUE TITLE
Check for conflicting buffer usage when reloading config

### ISSUE THREAD

**Issue by bill-bateman** [timberio/vector#5147]
### Expected Behavior
Should be able to edit config of a sink that uses the disk buffer.

### Actual Behavior
Vector crashes out - can't build new config, and can't rebuild old config.

Ran into an issue related to #4031. Basically if you are using disk buffer on any sink, and then change the sink, the reload will fail. What happens is the new (changed) sink tries to open the data_dir again, but the old sink hasn't ended yet, so still has data_dir open. So the reload fails. Then Vector tries to rebuild the old configuration, but again cannot open the data_dir, so it fails to recover and stops the program.

This happens on any change to the sink -- e.g. in the below config, if I change the encoding from text to json, the above will happen and it will crash.

### Vector Configuration File

```
data_dir = "tmp_data/"

[sources.in]
  type = "stdin"

# Output data
[sinks.out]
  inputs   = ["in"]
  type     = "console"
  encoding = "text"
  buffer.type = "disk"
  buffer.max_size = 1400000
  buffer.when_full = "drop_newest"
```

### Output
```
Nov 20 09:12:10.975  INFO vector::app: Log level is enabled. level="info"
Nov 20 09:12:10.976  INFO vector::app: Loading configs. path=["config/vector.toml"]
Nov 20 09:12:10.991  INFO vector::sources::stdin: Capturing STDIN.
Nov 20 09:12:16.041  INFO vector::topology: Running healthchecks.
Nov 20 09:12:16.042  INFO vector::topology: Starting source. name="in"
Nov 20 09:12:16.042  INFO vector::topology::builder: Healthcheck: Passed.
Nov 20 09:12:16.042  INFO vector::topology: Starting sink. name="out"
Nov 20 09:12:16.043  INFO vector: Vector has started. version="0.11.0" git_version="v0.9.0-1391-ge769bcc" released="Fri, 20 Nov 2020 16:45:10 +0000" arch="x86_64"
Nov 20 09:12:31.642 ERROR vector::topology: Configuration error. error=Sink "out": Unable to open data_dir "tmp_data"
Nov 20 09:12:31.642  INFO vector::topology: Rebuilding old configuration.
Nov 20 09:12:31.642 ERROR vector::topology: Configuration error. error=Sink "out": Unable to open data_dir "tmp_data"
Nov 20 09:12:31.643 ERROR vector::topology: Failed in rebuilding the old configuration.
Nov 20 09:12:31.643 ERROR vector: Reload was not successful.
Nov 20 09:12:31.643 ERROR vector: Vector has failed to recover from a failed reload.
Nov 20 09:12:31.643  INFO vector: Vector has stopped.
Nov 20 09:12:31.644  INFO source{component_kind="source" component_name=in component_type=stdin}: vector::sources::stdin: Finished sending.
Nov 20 09:12:31.644  INFO vector::topology: Shutting down... Waiting on running components. remaining_components="in, out" time_remaining="59 seconds left"
```

### Related To
#4031, #4735 - basically the same issue, just with the data_dir being the resource in conflict instead of the port.
 
Fix could be to add data_dir as a `Resource` somehow. If I force the reload to wait for the sink, then the reload works correctly. But the buffer is in the `SinkOuter`, and resources are currently only in the inner `SinkConfig`. So not sure how that should look.

**Comment by ktff** [comment]
I see three ways of fixing this:
* As @bill-bateman mentioned, we can use `Resource` to handle buffer conflict. 
   * Introduces dependencies that in theory we can avoid.
* Reuse buffers. That is, instead of detaching sinks with the buffer, detach sink from the buffer and then reuse the buffer in the replacement sink. 
    * Will require some changes in how we handle topology.
    * Can speed up closing of sinks on reload.
* Create new buffer with different name. For example, we can attach index to name which increments on conflict.
    *  Solves the problem directly.

Using different names on conflict seems as best option, although there will be some complexity in handling the files. Alternatively, we can go with reusing the buffers to gain it's nice side effects.  

@lukesteensen what do you think?

**Comment by j-bai** [comment]
IMHO, although Vector has never guaranteed of no buffer data loss upon conf reloading, but making best efforts to avoid it whenever possible should make the conf reloading much more usable and preferable.
If the above presumption stands, the 3rd approach in @ktff's suggested fix list wouldn't be the best solution, as it'd result in existing data in the old disk buffer being dropped unnecessarily.

**Comment by ktff** [comment]
> as it'd result in existing data in the old disk buffer to be dropped unnecessarily.

It wouldn't be dropped, the old sink will continue to run until it has exhausted the buffer. And to cover situations where vector was forcibly shutdown, some extra management of files will be needed to pickup/join multiple file buffers. That's the mentioned
> complexity in handling the files

**Comment by j-bai** [comment]
@ktff Yes, it wouldn't be dropped if the old sink could continue to deliver buffered data to its destination, but that assumption might not always hold true. Users reload configurations for reasons, and one of them could be that the old data destination (e.g. "uri" configured for http sink) has become unreachable and therefore a new one has been set up and configured with the new sink.

**Comment by lukesteensen** [comment]
> Reuse buffers. That is, instead of detaching sinks with the buffer, detach sink from the buffer and then reuse the buffer in the replacement sink.

If it's not too complex of a change, I think this is likely our best option. Disk buffers can potentially hold a large amount of data and therefore take a long time to drain, so it'd be nice to remove that consideration from the reload process. This also helps to avoid weird ordering issues that could occur when two versions of the same sink are running at the same time, one processing data from an old buffer and one from a new one.

**Comment by ktff** [comment]
> has become unreachable and therefore a new one has been set up and configured with the new sink.

currently, events in memory buffers would be lost in such scenario, plus points mentioned by @lukesteensen, reusing buffers would fix a lot of issues in one go so let's go with that.
