### ISSUE TITLE
Add support for  `directory` option to journald source

### ISSUE THREAD

**Issue by bruceg** [timberio/vector#5225]
When running inside a container, one use case is to mount the journald log files from the host into the container to so that they can be read by vector. In this case, the machine ID discovered from `/etc/machine-id` will not match the desired logs in `/var/log/journal`. It is not possible to specify an alternate machine ID on the journalctl command line. This can be worked around by mounting the host's `/etc/machine-id` file into the container, but that has other possible complications.

The enhancement is to add support for a `directory` option to the `journald` source to allow for specifying an alternate location for the logs. When given this option, `journalctl` reads from all machine IDs located under that path. This will additionally allow for use cases of reading from a different journal than journald would normally write to, etc.

**Comment by zadunn** [comment]
@bruceg  - do you happen to know what the "other possible complications" are here?  Is this an acceptable work around until directory support is added into Vector?

**Comment by bruceg** [comment]
The complications I was thinking about is if anything within the container logs messages via journald/systemd. By having the same `machine-id` and journal directory, at best those logs would cause permissions issues due to the journal not being writable, or be emitted to the host logs stream, which could be undesirable, but it could also lead to corruption of the journal as multiple writers try to modify it simultaneously.

I think cloning the `machine-id` is acceptable if the above is respected and nothing in the container will be writing to the journal.

**Comment by Mitsuwa** [comment]
Mounting `/etc/machine-id` fixed my problem as well.  TY ❤️ 

Supporting `-D /var/log/journal` would be a very nice option

**Comment by watawuwu** [comment]
I too need this feature and am considering implementing it.

Maybe it is easy to implement this feature.
I think that just need to add a new option with a name like `--journal-files-dir` and pass it to the `--directory` argument of the jouranlctl command.

```
journalctl [OPTIONS...] [MATCHES...]

Options:
...
  -D --directory=PATH        Show journal files from directory
```

However, Journal Source depends on the journalctl binary, which makes it difficult to write unit tests.
I'd like to avoid having only the journald source tests depend on binaries, any ideas?

**Comment by jszwedko** [comment]
Hi @watawuwu . I think that seems reasonable. For the tests, I think you could think about just testing the configuration mapping in isolation: that is, if the user specifies an alternate directory that it ends up calling `journalctl` with that directory; mocking out the actual call.

**Comment by YanaDevOps** [comment]
Thanks a lot, @bruceg, your solution solved my problem! ❤️
