### ISSUE TITLE
Tutorial on null failed

### ISSUE THREAD

**Issue by jgmachen** [timberio/vector#5249]
The tutorial on:

null

Here's what went wrong:

[vagrant@ldserver ~]$ ~/.vector/bin/vector  --config vector.toml
Nov 26 23:03:38.822  INFO vector: Log level "info" is enabled.
Nov 26 23:03:38.823  INFO vector: Loading configs. path=["vector.toml"]
Nov 26 23:03:38.824  INFO vector: Vector is starting. version="0.10.0" git_version="v0.9.0-377-g0f0311a" released="Wed, 22 Jul 2020 19:45:24 +0000" arch="x86_64"
Nov 26 23:03:38.838 ERROR vector::topology: Configuration error: Source "in": data_dir "/var/lib/vector/" does not exist

**Comment by binarylogic** [comment]
@jgmachen, thanks for reporting. Please create the `/var/lib/vector` directory:

```
mkdir -p /var/lib/vector
```

Or set the `data_dir` to another directory that does exist:

```toml
data_dir = "/my/dir"
```

**Comment by jgmachen** [comment]
thank you
