### ISSUE TITLE
Include native extensions for the `lua` transformer

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#526]
From https://github.com/timberio/vector/issues/61#issuecomment-491391352, see https://github.com/timberio/vector/pull/337 for an explanation.

**Comment by a-rodin** [comment]
I believe this wouldn't work with the statically linked Vector binaries because `dlopen` wouldn't work. The issue is the same as in #1433/#1473.

**Comment by lukesteensen** [comment]
Given that we're planning to add wasm support, I don't think this is actually worth the effort anymore.
