### ISSUE TITLE
Test common lua scripts

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#527]
From https://github.com/timberio/vector/issues/61#issuecomment-491391352

>  Get some fancier parsing scripts working and make sure they're reasonably performant. (The depends on native extension work above).

https://github.com/mozilla-services/lua_sandbox_extensions/blob/780f5ec6e9fdd8ef972a0f4f89d4727d7a7305b6/lpeg/modules/lpeg/common_log_format.lua

**Comment by Hoverbear** [comment]
I think this is all done Alex?

**Comment by a-rodin** [comment]
Some behavior tests are added [tests/behavior/transforms/lua_v2.toml](https://github.com/timberio/vector/blob/febbdfb39546c15a430b808226a03ad5a5bc41ec/tests/behavior/transforms/lua_v2.toml), so I think it is done.
