### ISSUE TITLE
After lua transformed , all int type values changed to float 

### ISSUE THREAD

**Issue by thomasdba** [timberio/vector#5310]
### Vector Version
0.10.0

```
...
```

### Vector Configuration File

```toml
...
[transforms.lua]
  inputs = ["file"]
  type = "lua"
  version = "2"
  hooks.process = """
    function (event, emit)
      local cjson = require('cjson.safe')
      local str = event.log.message
      local msg = cjson.decode(str)
      if msg then
        msg['env_vars'] = cjson.encode(msg['env_vars'])
        msg['request']['headers'] = cjson.encode(msg['request']['headers'])
        msg['response']['headers'] = cjson.encode(msg['response']['headers'])
        msg['response']['body'] = cjson.encode(msg['response']['body'])
        msg['route']['paths'] = cjson.encode(msg['route']['paths'])
        msg['route']['protocols'] = cjson.encode(msg['route']['protocols'])
        msg['service']['tags'] = cjson.encode(msg['service']['tags'])
        for key, value in pairs(msg) do
          event.log[key] = value
        end
      end
      event.log.message = nil
      emit(event)
    end
  """
```

### Actual Behavior
After using lua to transform , all int values were converted to float . for example status:200 is transformed to status: 200.0

**Comment by binarylogic** [comment]
Thanks for reporting @thomasdba, we'll expedite a fix.

**Comment by ktff** [comment]
@thomasdba this is an issue of missing support for Lua 5.3 integers in `openresty` and `mpx` repositories. You can see it mentioned here https://github.com/openresty/lua-cjson/pull/3 and here https://github.com/mpx/lua-cjson/issues/33, so I'll close this.

**Comment by jszwedko** [comment]
@ktff thanks for investigating this. Could we add it to the docs for the `lua` transform?

**Comment by ktff** [comment]
@jszwedko I'm not sure that we need to. This is a missing feature in `cjson` which the user needs to install separately from Vector and then explicitly load it to `lua` transform so I think it's the users responsibility to check for this.

**Comment by jszwedko** [comment]
@ktff aha, gotcha 👍  I missed that this was specific to cjson. I thought we were generally converting ints to floats in the Lua transform. Agreed, that we don't need to document it then.
