### ISSUE TITLE
nginx_metrics source page leads to mongodb_metrics docs

### ISSUE THREAD

**Issue by spencergilbert** [timberio/vector#5324]
### Expected Behavior

https://vector.dev/docs/reference/sources/nginx_metrics/ should lead to the documentation for the NGINX metrics source

### Actual Behavior

It's a duplicate of the mongodb_metrics docs page. The cue file for nginx looks correct (on master)

**Comment by jamtur01** [comment]
Thanks @spencergilbert! We'll get this fixed up.

**Comment by binarylogic** [comment]
Thanks! Fix is deploying now.

**Comment by spencergilbert** [comment]
So fast!
