### ISSUE TITLE
Failed to run on vector-0.11.0-1.x86_64.rpm

### ISSUE THREAD

**Issue by ivmaks** [timberio/vector#5327]
```
md5sum /usr/bin/vector ; cat /etc/centos-release ; ldd /usr/bin/vector
782b0740d50fb8c28de92299e9416a3f  /usr/bin/vector
CentOS Linux release 7.8.2003 (Core)
/usr/bin/vector: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/bin/vector)
/usr/bin/vector: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/bin/vector)
/usr/bin/vector: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /usr/bin/vector)

```

**Comment by jamtur01** [comment]
@ivmaks I am afraid this isn't a bug. Vector supports glic 2.18 or later. I know Centos 7 does not provide this (albeit 2.17 was released in 2012). We use `cross` to build Vector currently and we're considering options to build for earlier versions but that support isn't available upstream currently (c.f. https://github.com/rust-embedded/cross/issues/455). We'll take another look at the state of this.

**Comment by Hoverbear** [comment]
Our `gnu` arch builds no longer support Glibc prior to 2.18. (More info here: https://vector.dev/highlights/2020-07-09-add-musl-and-glibc-support-to-install-sh/) Could I invite you to try the musl builds? We are tracking https://github.com/rust-embedded/cross/issues/455 and have been investigating possible fixes.

**Comment by ivmaks** [comment]
binary from timberio/vector:0.11.X-distroless-static
works great on centos 7, maybe it should be packaged to rpm?

```cat /etc/centos-release;md5sum ./vector ;ldd ./vector
CentOS Linux release 7.5.1804 (Core) 
ac7a4bed2800cdb1c7521d43d3b20656  ./vector
	statically linked
```

**Comment by Hoverbear** [comment]
@ivmaks Heck, I forgot about those. Maybe huh? :)

**Comment by jamtur01** [comment]
@ivmaks We'll be providing a musl RPM shortly. I'll update this ticket with the details when it's got a home.

**Comment by jszwedko** [comment]
@jamtur01 noting that we may need to update the script referred to by https://vector.dev/docs/setup/installation/operating-systems/centos/ too.

**Comment by jamtur01** [comment]
Docs and website updates will be in #5364

**Comment by jamtur01** [comment]
The nightly musl RPM is here:

https://packages.timber.io/vector/nightly/latest/vector-0.12.0-1-musl.x86_64.rpm
