### ISSUE TITLE
Missing text on kubernetes installation page

### ISSUE THREAD

**Issue by spencergilbert** [timberio/vector#5340]
https://discord.com/channels/742820443487993987/753400475545501836/783732699327889408

### Expected Behavior

Kubernetes install page shows instructions on how to install, operate, and uninstall vector on kubernetes.

### Actual Behavior

Until I cleared cookies and site data the instructions didn't display, after it seems to be working fine.

**Comment by jamtur01** [comment]
Looks like it's working now. I'll re-open if it reappears.
