### ISSUE TITLE
Allow sending metrics via the Kafka sink & source

### ISSUE THREAD

**Issue by lukesteensen** [timberio/vector#5341]
As noted on [HN](https://news.ycombinator.com/item?id=25280311), we don't currently allow you to send metrics directly via the Kafka sink. There's no technical reason to disallow this, especially now that the text and JSON encoding formats of metrics are better defined and already being used in other sinks.

**Comment by binarylogic** [comment]
@lukesteensen how are you thinking about decoding this data on the other end via the `kafka` source? We would want those to be decoded into metrics, right?

**Comment by lukesteensen** [comment]
@binarylogic I don't know yet. That's why I didn't include the Kafka source when I added the issue :slightly_smiling_face: 

Most setups I can think of that send metrics to Kafka would be relatively custom, so it seems reasonable to just serialize to JSON and assume the consumers can deal with that. With the source, we're the ones who need to deal with it and I'm not sure if there's a good default format for us to assume. I'd be hesitant to position our internal-ish JSON as some kind of standard.
