### ISSUE TITLE
Remap parse_json example in the docs is wrong

### ISSUE THREAD

**Issue by FungusHumungus** [timberio/vector#5345]
The `parse_json` example for the remap transform is currently:

```
  message = del(.message)
  . = parse_json(message)
```

This is incorrect. `del` does not return the value of the field being deleted. Plus, if it was a variable it would need to be `$message` rather than just `message`.

Probably needs to be just:

```
  . = parse_json(.message)
```

It should be noted that this example doesn't seem to work at present, but will once #5277 is merged.

**Comment by JeanMertz** [comment]
> `del` does not return the value of the field being deleted

We actually discussed changing `del` (and others) to no longer take a variable number of arguments, but instead focus on having some way to iterate over a set of values and call `del` multiple times.

So we could leave the docs as is, and update `del` to take one argument.

We don't have iterating yet, but that will follow soon.

**Comment by FungusHumungus** [comment]
Ah ok. `message` still needs changing though - either a path - `.message` or a variable - `$message`.

**Comment by lucperkins** [comment]
I'm not sure in which PR this was fixed but we're in the clear here 👍🏼
