### ISSUE TITLE
Document timestamp formats

### ISSUE THREAD

**Issue by JeanMertz** [timberio/vector#5354]
When parsing timestamps, we support multiple timestamp formats out of the box:

https://github.com/timberio/vector/blob/e9371ac1de252bb667a8c6d833dbd0ecfdb882b3/src/types.rs#L204-L228

However, we also support providing a custom format:

https://github.com/timberio/vector/blob/e9371ac1de252bb667a8c6d833dbd0ecfdb882b3/src/types.rs#L297

Users are unaware of this, as it's (apparently?) not documented anywhere.

We do have some _examples_ showing custom formats (https://vector.dev/docs/reference/transforms/grok_parser/), but it isn't immediately clear how this should be used and what constitutes a valid format.

Also, if you search for `timestamp` in the search box, there isn't anything useful that pops up.

**Comment by 065191** [comment]
example: [24/Nov/2020:22:03:10 +0300] 
timestamp|%d/%b/%Y:%H:%M:%S %:z
or
example: [24/11/2020:22:03:10 +0300] 
timestamp|%d/%m/%Y:%H:%M:%S %:z
%d - day        | 24
%b - month   | Nov
%Y -year        | 2020

%d - day        | 24
%m - month  | 11
%Y -year        | 2020

the timestamp function will convert **YOUR**values ​​from the column according to the format of **YOUR** time:

How I used:
input: 
5.5.5.5 - - [24/Nov/2020:22:22:22 +0300] "GET /d/settings HTTP/2.0" 200 81 "" "testtest" "" 649 "" RUS mail.ru 5.5.5.5 p:111 107 0.002 0.002 - "276111111111111111" "" "" "" "-"

[transforms.parser_nginx_access]
  type     = "grok_parser"
  inputs   = ["in_nginx_access"]
  pattern  = '%{IPORHOST:client_ip} - %{DATA:username} \[(?<time>%{MONTHDAY}/%{MONTH}/%{YEAR}:%{HOUR}:%{MINUTE}:%{SECOND} %{INT})\] \"%{WORD:method} %{DATA:request} HTTP/%{NUMBER:http_version}\" %{INT:status} %{NUMBER:body_sent} \"%{DATA:referrer}\" \"%{DATA:user_agent}\" \"%{DATA:http_x_forwarded_for}\" %{NUMBER:bytes_sent} \"%{DATA:cookie_cud}\" %{DATA:geoip_country} %{DATA:hostname} %{IPORHOST:server_ip} p:%{INT:server_port} %{NUMBER:request_length} (%{NUMBER:upstream_response_time}|-) (%{NUMBER:request_time}|-) %{DATA:cache_status} \"%{DATA:request_id}\" \"%{DATA:http_request_id}\" \"%{DATA:cookie_dev}\" ?(\s*)?(\"%{DATA:cookie_tabIndex}\")?(\s*)?(\"%{DATA:PRTN}\")?'
  types.time = "timestamp|%d/%b/%Y:%H:%M:%S %:z"

**Comment by jszwedko** [comment]
We support chrono's time specifiers: https://docs.rs/chrono/0.4.19/chrono/format/strftime/index.html . I'd advocate for documenting it all on our docs though rather than linking to theirs

**Comment by 065191** [comment]
Sorry - IDK :)
