### ISSUE TITLE
Investigate the "Vector for Kubernetes cluster operators" use case

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#5362]
We've made Vector work for people that use Kubernetes, now it's time to address the needs of people who *run* Kubernetes clusters - the operators (the people in this context, not the operators as in automated control loops :smiley: ).

The goal of this task if to write up a mini-RFC that outlines what's needed to be done. Based on this mini-RFC we'll organize a roadmap.

This has been partially explored at the [Kuberntres RFC](https://github.com/timberio/vector/blob/master/rfcs/2020-04-04-2221-kubernetes-integration.md#gather-data-from-the-host-os), and we've already got a number of related issues:
- https://github.com/timberio/vector/issues/5256
- https://github.com/timberio/vector/issues/5255
- https://github.com/timberio/vector/issues/2199
- https://github.com/timberio/vector/issues/3680

We need a more complete view on the matter though, and this is what this task aims to address.

**Comment by MOZGIII** [comment]
One of the possible integration/deployment variants for cluster operators is via [AWS EKS addons](https://aws.amazon.com/ru/blogs/containers/introducing-amazon-eks-add-ons/). It's on a different level from the Helm charts, and quite possibly we could integrate more broadly there. We probably want to chat with someone from AWS about it.

**Comment by binarylogic** [comment]
@MOZGIII would you mind sharing where you landed on this? I'm curious if this is something you think we should proceed with?
