### ISSUE TITLE
New `parse_aws_cloudwatch_log` Remap function

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5367]
To replace the [`aws_cloudwatch_logs_subscription_parser` transform](https://vector.dev/docs/reference/transforms/aws_cloudwatch_logs_subscription_parser/).

**Comment by jszwedko** [comment]
I might call this `parse_aws_cloudwatch_log_subscription_message` as the format is specific to CloudWatch Logs subscriptions.

**Comment by binarylogic** [comment]
@jszwedko would it make sense to consolidate parsing of all formats into a single `parse_aws_subscription_message` function?

**Comment by jszwedko** [comment]
@binarylogic 

> @jszwedko would it make sense to consolidate parsing of all formats into a single `parse_aws_subscription_message` function?

Which other formats did you have in mind? I know the term subscription is also used in the context of SQS, but those messages could be any random payload. Are there other services?
