### ISSUE TITLE
Run test-harness on nightly artifacts in CI

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#5396]
After nightly artifacts are built, run the test-harness using them. We could output the comparison of that day vs. the previous day.

We have a `test-harness` CI workflow which this could be modeled after: https://github.com/timberio/vector/blob/master/.github/workflows/test-harness.yml

Any correctness test failures should alert discord.

**Comment by jszwedko** [comment]
Bumping to the backlog based on a conversation with Ben.

**Comment by binarylogic** [comment]
For context, we want to finish the microbenchmarks before moving onto this, due to their short iteration cycle and integration as a PR check.

**Comment by blt** [comment]
This strikes me as a duplicate of #7891, except that the soak tests themselves will not have a focus on correctness being that they're performance concerned.

**Comment by jszwedko** [comment]
Yeah, I think we can close this in-lieu of the soak test work.
