### ISSUE TITLE
Support timers in the `log_to_metric` transform

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#540]
**The requirements for this issue have changed, see https://github.com/timberio/vector/issues/540#issuecomment-511595605**

---

Currently we only support counters and gauges in the `log_to_metric` transform. We've held off on supporting histograms due to their more complex nature. We need to support histograms for obvious reasons, specifically because one of the most common use cases is capturing histograms on timings (response times for example).

## Use Case

Give a `duration_ms` field that is a `float`:

```json
{
  "message": "Sent 200 in 54.2ms",
  "duration_ms": 54.2,
  "status": 200,
  "host": "123.123.22.32"
}
```

We want to create a histogram representing the timings:

```
[transforms.log_to_metric]
  type = "log_to_metric"
  
  [[transforms.log_to_metric.metrics]]
    type = "histogram"
    field = "duration_ms"
    name = "duration_ms" # default
    labels.status = "#{event.status}" 
    labels.host = "#{event.host}"
```

## Histogram Types & Support

The intricacies of the various histogram types is admittedly a little beyond me. I do not have deep experience with metrics data models and I think the engineer assigned to this issue should propose a histogram data model structure before proceeding. A few things to note:

1. I'm hesitant to adopt the Prometheus histogram data model that requires a user to specify static buckets up front. I've yet to meet a developer that enjoyed this process as it was next to impossible to determine the correct buckets. Granted, I do not understand all of the reasoning behind this decision, but my hope is that we can do better.
2. I think [Stripe's Veneur approach to histograms](https://github.com/stripe/veneur#approximate-histograms) is interesting and possible something we could use as inspiration.
3. If we choose to adopt a more flexible histogram data model, it might make sense to perform the conversion in the `prometheus` sink. Perhaps we can defer addressing that until we decide on our own histogram data model.

**Comment by lukesteensen** [comment]
After discussing this a bit, I think we know how to move forward here. The transform won't aggregate histograms itself, but simply emit Timer events that can be aggregated into histograms (or anything else that suites the context) in sinks.

That simplifies this quite a bit and lets us defer answering most of the above question until we implement support in specific sinks, where the answers should be more clear.
