### ISSUE TITLE
Add support for detecting glibc version to installer script

### ISSUE THREAD

**Issue by jamtur01** [timberio/vector#5415]
For versions with glibc older than 2.18 use musl, alternatively use gnu.

https://dev.to/0xbf/how-to-get-glibc-version-c-lang-26he

**Comment by binarylogic** [comment]
Noting, we're already doing this:

https://github.com/timberio/vector/blob/24528d4d3b1ebe8566e43b48b6d3aef64bf308bd/distribution/install.sh#L274

We just need to adjust it so that it recommends MUSL when the version falls below 2.18.
