### ISSUE TITLE
Update Elasticsearch version used in integration testing

### ISSUE THREAD

**Issue by spencergilbert** [timberio/vector#5417]
Alternatively look into a way to test across a variety of ES versions.

#5126 allows Vector to use Elasticsearch as a sink when the target is a "data stream", a feature introduced in ES7.9. Currently, integration tests are run against 6.6.2. Depending on Vector's compatibility guarantees with ES versions, updating ES would be valuable, or alternatively introducing a way to integration test against a number of different versions would be valuable.

**Comment by jszwedko** [comment]
I think this is closed by #7903
