### ISSUE TITLE
Event time filter

### ISSUE THREAD

**Issue by jerryleooo** [timberio/vector#5422]
### Current Vector Version

```
0.12.0
```

### Use-cases

When handling logs/metrics, we may only be interested in the new ones. Hope we can have a component that ignores old events.

### Attempted Solutions

Enhance filter transform or have a new transform that ignores old events.

**Comment by binarylogic** [comment]
Thanks @jerryleooo I agree. This might have some overlap with #443.

**Comment by jerryleooo** [comment]
Cool @binarylogic , then I close this and watching #443
