### ISSUE TITLE
Explain the `rawConfig` of the Helm's `values.yaml` in the docs

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#5433]
Until #4932 is landed people have to use the `rawConfig` key in Helm `values.yaml` in our charts to pass extra parameters to the Vector components (source/transforms/sinks).

This is not documented clearly enough at the installation docs, we should make it clearer and provide some examples.

**Comment by binarylogic** [comment]
@MOZGIII this is moot given the recent YAML support, right?

**Comment by MOZGIII** [comment]
Yes, closing.
