### ISSUE TITLE
Feature Request: Read_from_Head like Fluent Bit Tail

### ISSUE THREAD

**Issue by runminlook** [timberio/vector#5437]
### Current Vector Version

```
vector 0.11.0 (v0.11.0 x86_64-unknown-linux-musl 2020-12-02)

```

### Use-cases

For new discovered files on start (without a database offset/position), read the content from the head of the file, not tail.
https://docs.fluentbit.io/manual/pipeline/inputs/tail

**Comment by lukesteensen** [comment]
This is actually the current default behavior, but we're working to make it more explicit via a `read_from` option that works as you describe. You can follow along at #6178.
