### ISSUE TITLE
VRL - support for comments

### ISSUE THREAD

**Issue by spencergilbert** [timberio/vector#5443]
### Current Vector Version

```
vector 0.12.0 (gb1d0189 x86_64-unknown-linux-musl 2020-12-08)
```

### Use-cases

Describing the functionality of remap configuration _next to_ the actions themselves, documentation of what the transformation is/should be doing

### Attempted Solutions

Right now I've been doing this as `toml` comments above/below the remap _source_ key, which works but as the remap becomes longer or more complex it's more difficult to understand.

### Proposal

Inclusion of comments for TRL using something like `//`, `#`, etc

**Comment by JeanMertz** [comment]
For reference, our grammar parser (`Pest`) has [built-in support for this](https://docs.rs/pest_derive/2.1.0/pest_derive/#whitespace-and-comment). Enabling this _should_ be as simple as adding the following rule to our grammar:

```peg
COMMENT  = _{ "#" ~ ANY* ~ NEWLINE }
```

I _think_ we have to use `#` since `//` is being proposed to use for integer division (see https://github.com/timberio/vector/pull/5353).

In the future, we could expand this to also allow inline comments using `/* ... */`.

**Comment by binarylogic** [comment]
This might sound crazy, but what if we didn't allow comments? A goal of the language is to be self-documenting, and if comments are required we failed to accomplish that goal. If there is a circumstance where comments are required, I'm willing to bet we could clean up the syntax to avoid them. Like replacing complex code with a descriptive function and so on.

**Comment by FungusHumungus** [comment]
One place where comments are still useful is whilst developing the script. It is really handy to comment out lines of code when trying alternative calls or trying to track down bugs. 

Not essential, but it does speed up development/debugging time.

**Comment by JeanMertz** [comment]
> This might sound crazy, but what if we didn't allow comments?

Yep. Crazy. 😛

I don't have a strong opinion on this, other than I'd note that comments aren't necessarily (or preferably) related to the logic as written in the program, but instead provide context to the reader that _can't_ be expressed through code.

For example, if a script did something like:

```rust
if starts_with(.message, "[boop]") {
	.timestamp = now()
}
```

As a reader, I'd have no idea why we're doing this, and there's no way to express this intent in the code.

However, with a comment, things become more clear:

```rust
// Our "boop" service lacks the capability to add timestamps to log messages,
// so we have to add them here, to make sure they are picked up by out log
// processor.
if starts_with(.message, "[boop]") {
	.timestamp = now()
}
```

We can defer implementing code comments for now, but I suspect we'll want to add support for this eventually.

**Comment by lucperkins** [comment]
As someone who has spent years working against the "good code is self-documenting" mantra, I have to chime in with a +1 and some not-yet-expressed reasons:

1. If we don't support this in the language I suspect that users will end up commenting in their config files anyway. Might as well let them comment in a more targeted way.
2. The other runtime transforms allow for comments.
3. As comments would be ignored at compile time, there's no per-invocation cost, so it's hard for me to see a downside.

**Comment by binarylogic** [comment]
Sounds good, let's support them. My biggest reason for deferring this is to force us to simplify the language early on as we encounter the need for comments, instead of using it as a bandaid for the real problem.
