### ISSUE TITLE
remap-lang: allow querying into result of functions

### ISSUE THREAD

**Issue by JeanMertz** [timberio/vector#5453]
We currently support querying the root object using paths (e.g. `.foo.bar`) and also variables (`$foo.bar` since #5094).

We've had at least one report thus far requesting to query the result of functions:

```rust
.url = "https://vector.dev"
.scheme = parse_url(.url).scheme // parse_url returns a `Value::Map`
.scheme // "https"
```

I'm not necessarily advocating we support this (it might be a slippery slope from here to supporting methods, although I don't think that's necessarily the case), but it's worth tracking this, given that more people might be looking for a similar feature.

**Comment by JeanMertz** [comment]
I forgot to cc @binarylogic and @FungusHumungus for input. I'm also curious what @bruceg and @jszwedko think about this.

**Comment by jszwedko** [comment]
:+1: this seems fairly natural to me.

**Comment by binarylogic** [comment]
I'm happy with this.

**Comment by binarylogic** [comment]
@JeanMertz this is not required for 0.12, but if you have time this would be nice to have.

**Comment by nnz1024** [comment]
> We've had at least one report thus far requesting to query the result of functions

Please add me to the list :smiley: 

Now I'm experimenting with Remap and Nginx logs parsing, and sometimes it requires strange constructions like
```
  upstream_addr_array_last = slice(split(.tmp.upstream_addr, ", "), -1)
  .upstream_addr = upstream_addr_array_last[0]
```
Here I need to use slice() because []-syntax does not allow to index elements from the end of the array, and also need to use intermediate variable because it is impossible to use `slice()[0]`, which is slightly disappointing.

**Comment by JeanMertz** [comment]
Thanks for the experience report @nnz1024 👍 

> because []-syntax does not allow to index elements from the end of the array

I agree, this can be annoying, and we should fix that. We are tracking this feature in https://github.com/timberio/vector/issues/5546.

> and also need to use intermediate variable because it is impossible to use `slice()[0]`, which is slightly disappointing.

Agreed, another paper cut we should (and will!) address.



> Nginx logs parsing

Are you using the default nginx log format, or a specialized one?

Looking at the docs, it appears the default log format is defined as:

```
log_format combined '$remote_addr - $remote_user [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    '"$http_referer" "$http_user_agent"';
```

We should add a specialized `parse_nginx_log` function to make this as easy as possible. I've filed a tracking issue at https://github.com/timberio/vector/issues/6103.

**Comment by nnz1024** [comment]
@JeanMertz No, I'm using JSON format, which is much easier to parse
```
log_format nginx_json escape=json '{ "@nginx_timestamp": "$time_iso8601", '
                         '"upstream_response_time": "$upstream_response_time", '
                         '"request_time": $request_time, '
                         '"body_bytes_sent": $body_bytes_sent, '
                         '"request_length": $request_length, '
                         '"status": $status, '
                         '"server_port": $server_port, '
                         '"remote_addr": "$remote_addr", '
                         '"remote_user": "$remote_user", '
                         '"request_uri": "$request_uri", '
                         '"uri": "$uri", '
                         '"request_method": "$request_method", '
                         '"http_referrer": "$http_referer", '
                         '"vhost": "$host", '
                         '"server_name": "$server_name", '
                         '"upstream_addr": "$upstream_addr", '
                         '"server_protocol": "$server_protocol", '
                         '"scheme": "$scheme", '
                         '"http_user_agent": "$http_user_agent" }';
```

In this case, the main problem is parsing `$upstream_response_time` and `$upstream_addr`. These fields can contain more than one value, according to [documentation](https://nginx.org/en/docs/http/ngx_http_upstream_module.html)
> keeps the IP address and port, or the path to the UNIX-domain socket of the upstream server. If several servers were contacted during request processing, their addresses are separated by commas, e.g. “192.168.1.1:80, 192.168.1.2:80, unix:/tmp/sock”. If an internal redirect from one server group to another happens, initiated by “X-Accel-Redirect” or error_page, then the server addresses from different groups are separated by colons, e.g. “192.168.1.1:80, 192.168.1.2:80, unix:/tmp/sock : 192.168.10.1:80, 192.168.10.2:80”. If a server cannot be selected, the variable keeps the name of the server group.

In my case, I can afford not to care about internal redirect, though.

When you will implement Nginx logs parsing, I think it worth considering to implement `$upstream_*` parser, which can be used with non-standard Nginx log formats, like in my case.

> Looking at the docs, it appears the default log format is defined as:

You right, [combined](https://nginx.org/en/docs/http/ngx_http_log_module.html#log_format) is the default format for Nginx HTTP logs. However, when Nginx is used as a reverse proxy, this format is quite insufficient, particularly in regard of upstream information, so it is often overridden by something custom.
Moreover, when one log destination is used for several virtual hosts (`server` blocks in Nginx terminology), the next problem shows up — `combined` format does not contain anything about virtual host selection.

So, IMHO, parser for Nginx `combined` will be nice-to-have addition, but definitely is not the number one priority. Parsers for upstream info and for error log format (cannot be redefined) would be much more handy.

**Comment by JeanMertz** [comment]
Thanks for the details @nnz1024, I added your comment in https://github.com/timberio/vector/issues/6103 to keep all nginx parsing related discussion in one place.

Given your example, I'd say something like this should work for now (using the latest nightly release):

```ruby
# parse Nginx message as JSON, or abort if it isn't valid JSON
. = parse_json!(.message)

# enforce that the new "upstream_addr" field is a string, or abort program if it isn't
.upstream_addr = to_string!(.upstream_addr)

# get the last address if the string contains multiple
if contains(.upstream_addr, ", ") {
	last = slice(split(.upstream_addr, ", "), -1)
	.upstream_addr = last[0]
}
```

**Comment by nnz1024** [comment]
@JeanMertz Thanks, using new fallible functions is a good idea.
