### ISSUE TITLE
Glibc problems on older Ubuntu and apt repo problems

### ISSUE THREAD

**Issue by szibis** [timberio/vector#5454]
**Glibc problems for 0.11 and earlier on older Ubuntu**
On system:
```
ldd --version
ldd (Ubuntu EGLIBC 2.19-0ubuntu6.14) 2.19
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```
But the version is not older than 2.18 here but may be connected with https://github.com/timberio/vector/issues/5415 and https://github.com/timberio/vector/issues/5412 and https://github.com/timberio/vector/issues/5327

As on Vector 0.11 and earlier versions, there is a problem with:
```
vector: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by vector)
vector: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by vector)
```
I get the package directly from the public repo:
```
 https://repositories.timber.io/public/vector/deb/ubuntu/pool/any-version/main/v/ve/vector-0.11.0-amd64.deb
```

When I download latest musl generic binary for 0.12 all is working
```
https://packages.timber.io/vector/nightly/latest/vector-0.12.0-x86_64-unknown-linux-musl.tar.gz
```
and vector working
```
./vector --version
vector 0.12.0 (ged31012 x86_64-unknown-linux-musl 2020-12-09)
```

**Package repo add problem**

As there are some problems described above.

Is there any chance as a repository from a vector is detected trusty there 
```
Executing the setup script for the 'timber/vector' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... OS detected as: distro=ubuntu  version=14.04  codename=14.04.5 LTS, Trusty Tahr
   OK: Checking for apt dependency 'apt-transport-https' ...
   OK: Checking for apt dependency 'ca-certificates' ...
   OK: Checking for apt dependency 'gnupg' ...
   OK: Importing 'timber/vector' repository GPG key into apt ...
   OK: Checking if upstream install config is OK ...
   OK: Installing 'timber/vector' repository via apt ...
   OK: Updating apt repository metadata cache ...
 ^^^^: ... The repository has been installed successfully - You're ready to rock!
```
But 
```
E: Problem parsing dependency Depends
E: Error occurred while processing vector (NewVersion2)
E: Problem with MergeList /var/lib/apt/lists/repositories.timber.io_public_vector_deb_ubuntu_dists_trusty_main_binary-amd64_Packages
E: The package lists or status file could not be parsed or opened.
```
With content
```
 cat /var/lib/apt/lists/repositories.timber.io_public_vector_deb_ubuntu_dists_trusty_main_binary-amd64_Packages
Package: vector
Version: 0.11.0
Architecture: amd64
Homepage: https://vector.dev
Priority: optional
Standards-Version: 3.9.4
Maintainer: Vector Contributors <vector@timber.io>
Installed-Size: 116812
Depends:
Description: A lightweight and ultra-fast tool for building observability pipelines
 .
Filename: pool/any-version/main/v/ve/vector-0.11.0-amd64.deb
Size: 24934116
MD5Sum: ca7d9a487c135cee71faececec7840d0
SHA1: e5c5f187e757ab250d83f2f80e1b1f61e416b093
SHA256: 1e0d90037eb12a3a206d6c19cc91020afb17fb192e2bdf14bb5060289b3c126b
```

**Comment by szibis** [comment]
In the end, is there an option to release 0.11.1 musl for deb packages from the repository ??

**Comment by binarylogic** [comment]
@szibis we'll investigate this today and have an answer to you shortly. For context, we switched our release process to use [cross](https://github.com/rust-embedded/cross), which is heavily adopted across the Rust community and improved the reliability and security of our releases. In that process, it appears the glibc version was raised slightly. But we'll get this worked out.

**Comment by jamtur01** [comment]
See #5458 for musl-debs that'll be generated for nightly. I'll add 0.11 specific deb shortly.

**Comment by jamtur01** [comment]
Okay - we know have 0.11 RPMs and Debs.

https://packages.timber.io/vector/0.11.0/vector-0.11.0-1.musl.x86_64.rpm
https://packages.timber.io/vector/0.11.0/vector-0.11.0-musl-amd64.deb

**Comment by jamtur01** [comment]
@szibis Can you please test and let me know how you go? Thanks!

**Comment by szibis** [comment]
@jamtur01 it is working. I tested this - https://packages.timber.io/vector/0.11.0/vector-0.11.0-musl-amd64.deb

**Comment by jamtur01** [comment]
Excellent. We'll hopefully have glibc-packages that support earlier versions shortly too.
