### ISSUE TITLE
Support TLS configuration for Humio sinks

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#5465]
The underlying `splunk_hec` sink supports the `tls` configuration options, but the Humio sinks do not expose it. We should expose the `tls` options on `humio_logs` and `humio_metrics` as well for use with custom Humio installations.

**Comment by langecode** [comment]
Just for the record. The concrete problem was being able to add a CA to trust. One workaround for this is is to extend the Vector container adding the CA (or add the CA to the host if not running in Docker). Docker file for this could be:

```
FROM timberio/vector:0.11.0-alpine

RUN mkdir -p /usr/local/share/ca-certificates
COPY ./my-ca.crt /usr/local/share/ca-certificates
RUN update-ca-certificates
```
