### ISSUE TITLE
Debian package install requires systemd to be running

### ISSUE THREAD

**Issue by nwmcsween** [timberio/vector#5478]
### Vector Version
Latest from https://packages.timber.io/vector/latest/vector-amd64.deb as of date of this bug

### Vector Configuration File
N/A

### Debug Output
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
dpkg: error processing package vector (--install):
 installed vector package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 vector

### Expected Behavior
dpkg -i vector.deb should install without systemd running

### Actual Behavior
dpkg -i vector.deb requires systemd running to install

**Comment by jamtur01** [comment]
@nwmcsween What Debian version/flavor is this? Can you tell me the circumstances of your install - i.e. how and when you're doing it? Thanks!

**Comment by jamtur01** [comment]
Hi @nwmcsween Just following - if you get a chance could you provide some more information! Thanks.

**Comment by nwmcsween** [comment]
Sorry for the late reply, I ended up reformatting my work laptop due to some issues. The system was Debian buster, install was within a container e.g. a Dockerfile with the end result being copied to a storage system to netboot servers for immutable infra.
