### ISSUE TITLE
remap: parser doesn't allow creating a string with a \ in it by escaping it as \\

### ISSUE THREAD

**Issue by spencergilbert** [timberio/vector#5482]
Creating from: https://discord.com/channels/742820443487993987/746070591097798688/786718829626654730

### Vector Version

```
vector 0.12.0 (g605ea3c x86_64-unknown-linux-gnu 2020-12-04)
```

### Vector Configuration File

```toml
...
```

### Expected Behavior

```
173.205.206.38 - vector [10/Dec/2020:17:21:57 +0000] "POST /_bulk?timeout=60s HTTP/1.1" 200 23953 "-" "Vector/0.12.0 (ged31012 x86_64-unknown-linux-gnu 2020-12-09)" 25520 0.145 [logging-quickstart-es-http-https] [] 10.42.2.98:9200 23953 0.148 200 ae6d0658c04ed7280fd19237a3d90747
```
When trying to write a grok pattern for the above message, I used a function like: `parse_grok(.message, "%{IPORHOST:remote_addr} - %{USER:remote_user} \[%{HTTPDATE:time_local}\] %{GREEDYDATA:greedy}")`

This should work per existing grok documentation and examples.

### Actual Behavior

Vector errors with: `invalid escape character in string: `[` at line 162 column 33.`

### Example Data

```
.ook = "nork \\ noog"
```
@FungusHumungus noted that the simple example above doesn't parse

**Comment by spencergilbert** [comment]
```
 .noog = parse_grok(.message, "\\\\[%{HTTPDATE:time_local}\\\\]")
```
@FungusHumungus solved the problem, always needs more `\` because toml also escapes

**Comment by FungusHumungus** [comment]
It should be noted that there are a number of places where Remap and Toml clash.

This is one place, since Toml needs `\` and Remap needs `\` escaping, we end up having to have `\\\\` to have a single `\` in the string.

Another place is the `$` in variables. Toml needs them escaped, so variables have to use `$$` - eg. `$$foo = "hello"`.

I'm not sure what the solution is here, but at the very least these gotchas need to be documented.

**Comment by binarylogic** [comment]
I'm also curious if TOML's string literals help here?

```toml
re = '''\d{2} apps is t[wo]o many'''
lines = '''
The first newline is
trimmed in raw strings.
All other whitespace
is preserved.
'''
```

**Comment by binarylogic** [comment]
Website has been updated:

https://vector.dev/docs/reference/transforms/remap/
