### ISSUE TITLE
When releasing artifacts to dynamic s3 folders we should cleanup previous files

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5485]
After investigating an issue with broken download links, I noticed that [this path](https://packages.timber.io/vector/latest/) had a bunch of old artifacts. This was due to the artifact name change (including the version now). As part of uploading artifacts to a dynamic folder, we should first clear the folder to remove any old artifacts.

- [ ] https://packages.timber.io/vector/0.X/
- [ ] https://packages.timber.io/vector/0.9.X/
  - [ ] ...any path with an X in it
- [ ] https://packages.timber.io/vector/latest/
- [ ] https://packages.timber.io/vector/nightly/latest/

It might be easier to clear the folder regardless of the path, but I hate introducing the ability for CI to delete files.

**Comment by jamtur01** [comment]
@binarylogic What's the point of the .X directories?

**Comment by binarylogic** [comment]
To opt into a major or minor version. So `0.11.X` allows users to seamlessly upgrade patch releases.

**Comment by jamtur01** [comment]
Do we know if anyone uses them?

**Comment by jamtur01** [comment]
Okay - I did this to fix this:

https://github.com/timberio/vector/pull/5672/files#diff-43ad4584a2629705fa6a417fbe227b9182cab58cf23f8290060a99f5b2393f44R92

Let me know if that works.
