### ISSUE TITLE
The Remap `parse_timestamp` function `format` argument should be optional

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5496]
I think this is already implemented in the `to_timestamp` function. To make timestamp parsing easier, we should do what we currently do in our legacy types conversion code:

https://github.com/timberio/vector/blob/2ab17c8ac514211d5579d16821b5e47c050c745b/src/types.rs#L205-L228

That is, automatically detect and parse common formats.

**Comment by JeanMertz** [comment]
If we do this, there isn't much that separates `to_timestamp` from `parse_timestamp` any more. Should we consolidate the two?

**Comment by binarylogic** [comment]
Yes, I think so, although to_timestamp handles integers.

**Comment by JeanMertz** [comment]
If we'd go with #5507, I'd personally leave this as is, but provide:

* `to_timestamp(.foo, default = "2020/10/21")` (together with `to_string`, etc)
* `timestamp::parse(.foo, format = "%s")` (for this one I'd make the format optional, and remove the `default` parameter)

**Comment by binarylogic** [comment]
Actually, I'm going to close this. I think the current behavior is correct:

* `to_timestamp` is automatic, intended for simple conversions.
* `parse_timestamp` is specific to a custom format.
