### ISSUE TITLE
New `to_level` Remap function

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5500]
Given a [Syslog severity](https://en.wikipedia.org/wiki/Syslog#Severity_level), the `to_level` function would produce the level name:

```js
to_level(3)
=> "error"
```

**Comment by JeanMertz** [comment]
See #5507 for a discussion on scoping this into a separate (syntactic) module.

**Comment by lucperkins** [comment]
Added as `to_syslog_level` in #5503
