### ISSUE TITLE
New `to_severity` Remap function

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5501]
Given a [Syslog level](https://en.wikipedia.org/wiki/Syslog#Severity_level), the `to_severity` function would produce the severity value:

```js
to_severity("error")
=> 3
```

**Comment by JeanMertz** [comment]
See https://github.com/timberio/vector/issues/5507 for a discussion on scoping this into a separate (syntactic) module.

**Comment by lucperkins** [comment]
Added as `to_syslog_severity` in #5505
