### ISSUE TITLE
remap-lang: allow negative indexing into arrays

### ISSUE THREAD

**Issue by JeanMertz** [timberio/vector#5546]
given this:

```json
{ "foo": ["bar", "baz"] }
```

This works:

```rust
.foo[0] // "bar"
.foo[1] // "baz"
```

This does not:

```rust
.foo[-1] // "baz"
.foo[-2] // "bar"
```

There is no technical reason we can't implement this, but the language grammar does not support negative index numbers at the moment.

This was either a deliberate choice to reduce language complexity, or just something we haven't got to yet (I don't know the answer).

Regardless, people seem to run into this limitation (see https://discord.com/channels/742820443487993987/746070591097798688/787115063500472331), so it's worth considering supporting negative indexing in path queries.

**Comment by asymmetric** [comment]
Is this documented? I couldn't find any mention of negative indexes in the docs.
