### ISSUE TITLE
New `loki` sink

### ISSUE THREAD

**Issue by shane-axiom** [timberio/vector#557]
https://github.com/grafana/loki/blob/master/docs/api.md

**Comment by binarylogic** [comment]
❤️ loki. We'll definitely look into this and update as we make progress.

**Comment by tlvenn** [comment]
that would indeed be awesome !

**Comment by tlvenn** [comment]
Prior art for Fluentd in Ruby: https://github.com/banzaicloud/fluent-plugin-kubernetes-loki
