### ISSUE TITLE
Benchmark Remap functions for performance baselines

### ISSUE THREAD

**Issue by JeanMertz** [timberio/vector#5573]
We should do a "performance pass" over all of our TRL functions.

I've created this issue to keep track of any performance-related comments during development, so that we can tackle them whenever we plan to work on this.

**Comment by JeanMertz** [comment]
@bruceg:

> This `map` has a fixed number of elements, and the tree form is not actually used other than to iterate over. I think this could be done as an array (`[(&str, Value)]`) and avoid the extra tree allocation work for nothing.

[here](https://github.com/timberio/vector/pull/5522#discussion_r542502932)

**Comment by jszwedko** [comment]
We closed https://github.com/timberio/vector/issues/2833 in-lieu of this one so we should make sure to cover comparing `ends_with` vs. `regex` parsing to see if we should do anything fancy in vector to try to identify simple regexes to convert.

**Comment by jszwedko** [comment]
I'm content to work on this after my vacation, but @JeanMertz has also been adding these as I think it is easily something someone else could pick up.

Example of existing function benchmarks:

https://github.com/timberio/vector/blob/4cb7409f3e45597df12ace3389cb415eba60432f/benches/remap.rs#L36-L43
