### ISSUE TITLE
Vector 0.11 cannot bind to both TCP and UDP on same port. 

### ISSUE THREAD

**Issue by aske1204** [timberio/vector#5575]
### Vector Version
```
vector 0.10.0 (g0f0311a x86_64-unknown-linux-gnu 2020-07-22)
```

### Vector Configuration File

```
[sources.syslog_tcp_511]
  type = "syslog" # required
  address = "0.0.0.0:511" # required, required when mode = "tcp" or mode = "udp"
  mode = "tcp" # required

[sources.syslog_udp_511]
  type = "syslog" # required
  address = "0.0.0.0:511" # required, required when mode = "tcp" or mode = "udp"
  mode = "udp" # required
```

### Debug Output

```
 vector[1466290]: Dec 17 12:08:55.176 ERROR vector::cli: Configuration error. error=Resource `0.0.0.0:511` is claimed by multiple components: {"syslog_tcp_511", "syslog_udp_511"}
```

### Expected Behavior
Vector running 

### Actual Behavior

Vector can't start because of the above error

**Comment by aske1204** [comment]
![image](https://user-images.githubusercontent.com/11734072/102499717-ced2ab00-407b-11eb-9af9-849dfd64439b.png)

**Comment by ktff** [comment]
@juchiast look at the `struct Resource` that's where the bug originates. Addresses are a resource of which only one component can use. In this case we are too strict since we aren't taking in consideration that `udp` address are different from `tcp` address.
