### ISSUE TITLE
New `blank` option to the `compact` Remap function

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5577]
A new `blank` argument/option for the `compact` Remap function that implements the logic in https://github.com/timberio/vector/issues/5576.

**Comment by JeanMertz** [comment]
Once we have a way to traverse fields, you could compose existing functions instead of having this be an option on `compact`.

Something like (ignore the traverse method syntax):

```rust
. = compact(traverse(., is_blank(.) && . = null))
```

(this assumes `traverse` returns the object it walked)

Or, with the pipe operator (#5431):

```rust
. = . |> traverse(is_blank(.) && . = null) |> compact
```
