### ISSUE TITLE
New `aws_kinesis_firehose` sink

### ISSUE THREAD

**Issue by mustafaakin** [timberio/vector#559]
We batch the logs with Firehose and it works great as you can already send its output to S3, it works mostly better then putting it directly to S3 and safer since Firehose is append-only.

**Comment by binarylogic** [comment]
Thanks @mustafaakin! This is actually why we were so specific with the [`aws_kinesis_stream` sink](https://docs.vector.dev/usage/configuration/sinks/aws_kinesis_streams) name 😄 . This should largely reuse much of the code. We'll update this issue as we make progress.
