### ISSUE TITLE
Emit `outputted_events_total` for transforms

### ISSUE THREAD

**Issue by ktff** [timberio/vector#5595]
We are emitting `processed_events_total` which reflects how many events went into the transform. We can add a complementary metric `outputted_events_total` that would reflect how many events came out of the transform. 

Follow up to https://github.com/timberio/vector/pull/5492#discussion_r541337736

**Comment by binarylogic** [comment]
@ktff the name is past tense, which suggests it already processed the events. If anything `processed_events_total` should represent what you're proposing here, with a new metric named something like `received_events_total` representing the reception of events.

**Comment by ktff** [comment]
@binarylogic 
> the name is past tense, 

Yep, the name `processed_events_total` was not changed with #5492 since it in essence wasn't changed, while changing the name will require changes to api and it's consumer since they would need to handle both `processed_events_total` from sources and sinks and `received_events_total` from transforms. But it is an option so I'll add it to the issue  #5596.

> If anything `processed_events_total` should represent what you're proposing here

It doesn't, since some transforms can drop events and create more events so there is no correlation between processed events and outputted events.

But the description of this issue could be clearer so I'll update it.

**Comment by ktff** [comment]
Closing in favor of #6367
