### ISSUE TITLE
`processed_events_total` for transforms is emmited before the event is processed

### ISSUE THREAD

**Issue by ktff** [timberio/vector#5596]
With #5492 the emission of `processed_events_total` metric was moved and unified to topology level where it is emitted when passing the event to the transform, and not actually when the event is processed. so the naming is not quite correct, although close, which can cause ordering issues and confusion. 

Before #5492, half of the transforms emitted before and half after the event was processed. 

Some ways of solving this are:
* Find a way to emit `processed_events_total` after it was processed. 
    * The main problem with this is `Transform::Task` type of transforms into which such emitting code can't be added to the right place so some changes to the architecture would be needed.
* Rename `processed_events_total` to `received_events_total` which would reflect it's current behavior. 
    * Will require changing api and it's consumers to handle both metrics.
* Go the middle route and only emit `processed_events_total` on topology level for `Transform::Function`, and return emitting of  `processed_events_total` back inside `Transform::Task`. 
    * It would more taxing for developers to follow this rule.
    * Athough this could reintroduce double counting issues, I don't expect for this kind of transforms to be reused.

cc. @MOZGIII

**Comment by MOZGIII** [comment]
> Find a way to emit `processed_events_total` after it was processed.
> * The main problem with this is `Transform::Task` type of transforms into which such emitting code can't be added to the right place so some changes to the architecture would be needed.

I'd suggest adding bith before and after - for some of the transforms these values will be different, and the difference is actually very meaningful the users - for instance, it enable trivial bookkeeping of the where and how much events are dropped/merged/split in a universal fashion.

**Comment by ktff** [comment]
@MOZGIII yep the #5595 addresses the `after`, and this the `before`.
