### ISSUE TITLE
Allow the Prometheus remote write sink to set a custom `X-Scope-OrgID` header

### ISSUE THREAD

**Issue by FungusHumungus** [timberio/vector#5598]
From [Discord](https://discord.com/channels/742820443487993987/746070604192415834/789456135445938176) it would be useful if the Prometheus Remote Write Sink could set a custom `X-ORG-ID` HTTP header.

The value of this header needs to come from the Metric tags, so we would need this field to be templateable. The Batching would also need to take this into consideration.

Some documentation is [here](https://cortexmetrics.io/docs/guides/auth/).

**Comment by mrmassis** [comment]
Greate!!!!
On correction (my mistake), the field is X-Scope-OrgID.

**Comment by mrmassis** [comment]
It is necessary to enable full multi-tenant feature in cortex. I couldnt find other solution to this problem.

**Comment by mrmassis** [comment]
The better field to get the namespace is: `kubernetes_namespace`, if it dont exist is possible set a default field value?

**Comment by mrmassis** [comment]
Some like it:
```
[sinks.my_sink_id]
  type = "prometheus_remote_write" # required
  inputs = ["my-source-or-transform-id"] # required
  tenant_id = kubernenetes_namespace # optional
  tenant_id_default = "service"  # optional
  endpoint = "https://localhost:8087/" # required
  healthcheck = true # optional, default
  ```

**Comment by mrmassis** [comment]
@bruceg some news?

**Comment by jamtur01** [comment]
@mrmassis Hi - it's the weekend here. :) The issue is in our next sprint and we'll take a look then. Keep an eye on the ticket for updates!

**Comment by mrmassis** [comment]
Great! sorry for inconvenience :(

**Comment by mrmassis** [comment]
Hi,
any update about this issue?
Tkz

**Comment by bruceg** [comment]
Yes, actually, I just finished the implementation on Friday and am writing up tests to ensure it's behavior is correct. I expect to have a pull request up today.

**Comment by mrmassis** [comment]
Great,
Tkz for your work.
Ler me know when tou finish the tests.
Regards

Em seg, 11 de jan de 2021 12:27, Bruce Guenter <notifications@github.com>
escreveu:

**Comment by mrmassis** [comment]
Sorry by typos

Em seg, 11 de jan de 2021 22:48, Marcio R M Assis <
marcio.miranda.assis@gmail.com> escreveu:

**Comment by bruceg** [comment]
Note that this requires #5985 to finish support for templating on metric tags.

**Comment by mrmassis** [comment]
@bruceg this feature is already to tests? Could I used in my enviroment??

**Comment by bruceg** [comment]
It is ready to test if you are able to build vector from source. Otherwise it will be in the next nightly build.

**Comment by mrmassis** [comment]
Ok, I will wait. Tkz

**Comment by mrmassis** [comment]
The modification is already in master @bruceg .
Sorry, but I don't know how the nightly works.

**Comment by jamtur01** [comment]
@mrmassis Download a nightly build from here: https://vector.dev/releases/0.11.1/download/.

**Comment by mrmassis** [comment]
@bruceg,
could you give a example of config file. With source, extract the tenant_id and the sink?
Tkz

**Comment by mrmassis** [comment]
@jamtur01 could you give me a exemplo how I use this new feature

**Comment by bruceg** [comment]
To use this, put something like this in the config:
```toml
[sinks.some_name]
type = "prometheus_remote_write"
inputs = ["my_metrics_source"]
endpoint = "http://hostname:port/api/etc"
tenant_id = "my_org_id"
```

**Comment by mrmassis** [comment]
@bruceg could I get the my_org_id from the metric message? Like kubernetes namespaces?

**Comment by bruceg** [comment]
@mrmassis unfortunately that is not yet implemented. See #5985. This currently only supports expansion from environment variables (which is standard throughout the config file).

**Comment by mrmassis** [comment]
@bruceg os possible i get Thais valeu in previous stage and put It in a variable?
There are some way to setting variable in obter stage?

**Comment by mrmassis** [comment]
The main Idea is dinamicy.

**Comment by mrmassis** [comment]
Hi @bruceg 
when this sink modification will be sent to main stream?
Some agenda?
Tkz

**Comment by bruceg** [comment]
It is in the current nightly images, and will be in the next official release. We are cleaning up a few bugs in preparation for releasing. No firm timeline has been set.

**Comment by mrmassis** [comment]
tkz for ansewer!
