### ISSUE TITLE
Add gzip|snappy|lz4 compression support to Kafka sink

### ISSUE THREAD

**Issue by erikbos** [timberio/vector#560]
It would be nice to have gzip, snappy or lz4 compression in the kafka sink

**Comment by erikbos** [comment]
Another way to save on broker capacity might be through generic payload compression, I opened https://github.com/timberio/vector/issues/734 for that.

**Comment by lukesteensen** [comment]
Thanks for opening this and sorry for the lack of response @erikbos!

I agree this is definitely something we should have. The way we're using the underlying kafka library means this should just be a matter of adding the relevant option to the kafka sink config and passing it along. 

I've also had success using broker-side compression with kafka (i.e. setting the `compression.type` topic config value). If you can afford the extra cpu cycles, you can get compression that's a bit more space efficient than doing it producer-side.

**Comment by erikbos** [comment]
For my situation passing the relevant parameters to the Kafka library would probably not do the trick: That would enable compression on Kafka protocol level, which most non-native Kafka implementations (like Azure Event Hubs) do not appear to support.

So I'm looking for a feature that would compress the payload, as being transported by Kafka. Probably the the whole payload in one go. That would likely also mean assembling it before it goes into the Kafka lib, but that might be hard to do in case you feed the Kafka lib one event at a time..

**Comment by lukesteensen** [comment]
Interesting. I don't have much experience with non-native Kafka implementations like Azure Event Hubs. It appears that compressing individual message bodies is the only supported form of compression there: https://github.com/Azure/azure-event-hubs-for-kafka#compression--message-format-version-issue

Any compression of more than a single message would become a protocol-level change, which seems unsupported. A more extreme option would be batching multiple vector events into a single Kafka message and compressing that, but that's not something I would encourage.

**Comment by erikbos** [comment]
I think it's ok to batch multiple events into a single Kafka message. We actually currently do up to 80 events of 5k in a single message usingfilebeat, and send it to AzureEventHubs (For cost and efficiency sake, as Azure charges per Kafka message)

See option bulk_max_size: https://www.elastic.co/guide/en/beats/filebeat/master/kafka-output.html#_literal_bulk_max_size_literal_3

**Comment by fanatid** [comment]
Can be closed after https://github.com/timberio/vector/pull/1969 ?

**Comment by erikbos** [comment]
Thanks for the heads up, will have a look at #1969
