### ISSUE TITLE
New `influxdb` sink

### ISSUE THREAD

**Issue by steverweber** [timberio/vector#562]
influxdb is a neat endpoint for metric data

the format is somewhat simple.
https://docs.influxdata.com/influxdb/v1.7/write_protocols/line_protocol_tutorial/

**Comment by evaryont** [comment]
In terms of performance, I'd be interested to see support of [InfluxDB's UDP protocol](https://docs.influxdata.com/influxdb/v1.7/supported_protocols/udp/).

**Comment by jonbayer** [comment]
fwiw, I personally have use for a parser for this line format; should it be possible to parse this via the existing system?

**Comment by megastef** [comment]
To use the influx line protocol to ship metrics to SaaS like Influx & Sematext Cloud, we would like to see support for HTTPS. 
I think UDP is great in local networks, however, UDP is not the best choice for SaaS Services like Influx Cloud or Sematext Cloud. 

Curl example: 
```
curl -i -XPOST 'http://localhost:8086/write?db=mydb' --data-binary 'cpu_load_short,host=server01,region=us-west value=0.64 1434055562000000000'
```

**Comment by otisg** [comment]
We've had people ask about shipping metrics to Sematext with Vector and as Sematext exposes Influx Line Protocol API for metrics ingestion, we'd love to see Vector add support for it.

@binarylogic do you have a rough ETA for this?

**Comment by loony-bean** [comment]
Thanks for input @jonbayer!
Does it mean you need a `source` (in Vector terms) that will consume line protocol data?

**Comment by loony-bean** [comment]
Thanks @megastef! Do you happen know if Sematext is 100% compatible with Influx API, or there are some differences which might be important here? I'm going to spec this out, and I'd like to understand if the user experience (auth, limits, status codes, metric batches, compression) is the same.

**Comment by otisg** [comment]
I believe the Sematext API doesn't cover 100% of the Influx Line Protocol (e.g. no reads), but it covers everything one typically needs for ingestion.

**Comment by bednar** [comment]
Hi all,

We would like to prepare a support for InfluxDB 2.0. Is there a documentation how to write new sink? Or we can just follow [datadog metrics](https://github.com/timberio/vector/pull/967) implementation?

Regards

**Comment by lukesteensen** [comment]
Hi @bednar! We don't have specific documentation for writing sinks yet, but following along with the datadog metrics sink should get you started.

If you have any questions at all, please feel free to open issues or hop in our [gitter channel](https://gitter.im/timberio-vector/community)!

**Comment by MOZGIII** [comment]
There are some helpful hints [here](https://github.com/timberio/vector/blob/master/CONTRIBUTING.md#development).

**Comment by bednar** [comment]
You can check progress of `influxdb sink` here: https://github.com/bonitoo-io/vector/blob/influxdb_metrics/src/sinks/influxdb_metrics.rs

**Comment by binarylogic** [comment]
Nice! Let us know when you're ready for a review. And we're happy to answer any development questions in our [chat](https://chat.vector.dev).
