### ISSUE TITLE
New `Rust` transform

### ISSUE THREAD

**Issue by andrewbanchich** [timberio/vector#564]
I'd love to be able to write Rust code for custom filtering instead of just Lua. Is that possible?

**Comment by LucioFranco** [comment]
@andrewbanchich Currently the only way is to actually write the rust within the project aka fork. I think down the line WASM is feasible but we have not crossed that road yet, but that would be the best method to getting rust transforms that are external.

**Comment by andrewbanchich** [comment]
Okay, thanks!

**Comment by andrewbanchich** [comment]
@LucioFranco Would [Gluon](https://github.com/gluon-lang/gluon) be a possibility instead?

**Comment by LucioFranco** [comment]
@andrewbanchich Yeah, it looks like it should be pretty easy to embed gluon though not sure how many people would actually use it over rust directly.

**Comment by andrewbanchich** [comment]
The reason I'm personally interested is that I'm pretty comfortable with Rust but I don't know Lua and Gluon's syntax looks pretty similar to Rust's.

Maybe others also feel the barrier to entry would be less for them with Gluon due to a familiar syntax / language?

**Comment by lukesteensen** [comment]
@andrewbanchich That makes sense. It would be interesting to have something like gluon or [rhai](https://github.com/jonathandturner/rhai) available for people who are more familiar with rust-like languages. We would just want to make sure that there's significant enough demand to justify the cost of implementation, docs, maintenance, etc, which I don't think we've seen yet.

**Comment by andrewbanchich** [comment]
Agreed! Feel free to close this if you'd like.
