### ISSUE TITLE
Support AWS WebIdentityProvider everywhere

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#5648]
This was done for CloudWatch, but not for Elasticsearch for instance. We need to make sure ut's enabled everywhere.

**Comment by binarylogic** [comment]
@MOZGIII any idea who enabled that (git blame)? I'm unsure which area of the code this lives.

**Comment by jamtur01** [comment]
@binarylgoic In a2cc2440307cd3fe34ba99d80445260286dace56 that closes #4049.

**Comment by MOZGIII** [comment]
Yep! This should be as easy as just going through the codebase and updating to our custom chain.
There's also this: https://github.com/timberio/vector/pull/4406

I didn't look too deep into it yet, to the taks might not well posed really, but it looks like it was broken.

**Comment by tustvold** [comment]
@MOZGIII AFAIK everything should be using the custom credentials provider, which has support for this. I've commented on https://github.com/timberio/vector-k8s-dev-env/pull/10 with what I suspect is the issue

**Comment by MOZGIII** [comment]
I've prepared https://github.com/timberio/vector-k8s-dev-env/pull/11 to check this in practice.

@tustvold I was under this impression as well, however I've got some troubles with validating it. Since that I've changed the approach from using the node-based auth to service-level auth, and will check it once again. I might've just created an incorrect IAM roles/policies relationship before, but the error I got from AWS suggester otherwise.

Anyhow, the service-level auth is more straightforward, and I have high certainty in this config this time, so we'll know if it `elasticsearch` sink works as expected in a bit.

**Comment by MOZGIII** [comment]
I think I managed to confirm it via https://github.com/timberio/vector-k8s-dev-env/pull/11#issuecomment-749386558.

**Comment by MOZGIII** [comment]
False alarm, but we should improve our error handling. More info at https://github.com/timberio/vector-k8s-dev-env/pull/11#issuecomment-749401779.

**Comment by ktff** [comment]
WebIdentityProvider is enabled everywhere relevant. There are just few small things to address.
