### ISSUE TITLE
RFC for distributing the TRL CLI tool

### ISSUE THREAD

**Issue by lucperkins** [timberio/vector#5664]
@JeanMertz has provided us with a lovely CLI tool for the Timber Remap Language but the only way to use it currently is via `cargo run` in the Vector repository. We should explore distributing the `trl` tool via the same channels that we distribute Vector. An RFC would clarify:

* Which changes to our build/release definitions and processes would be necessary to accommodate a second executable
* Whether `trl` should be bundled with the `vector` executable in some distributions
* What kind of versioning scheme to use for it

**Comment by jamtur01** [comment]
@lucperkins Is this still needed?

**Comment by binarylogic** [comment]
The RFC was closed, so let’s close this
