### ISSUE TITLE
remap-lang: serialize timestamp value in RFC3339

### ISSUE THREAD

**Issue by fanatid** [timberio/vector#5677]
Initial discussion: https://github.com/timberio/vector/pull/5653#discussion_r546857915

**Comment by binarylogic** [comment]
cc @JeanMertz and @FungusHumungus for input/approval.

**Comment by JeanMertz** [comment]
I agree. This was an oversight on my part, as I expected `DateTime<UTC>`'s Display impl to actually result in an RFC3339 formatted string.
