### ISSUE TITLE
TRL reference invalid example

### ISSUE THREAD

**Issue by spencergilbert** [timberio/vector#5678]
https://master.vector.dev/docs/reference/remap/#example

```rust
. = parse_json(.message)
.bytes = to_int(.bytes)
.duration = parse_duration(.duration, "s")
.status = to_int(.status)
.timestamp = parse_timestamp(.timestamp)
```

`parse_timestamp` requires an input, as well as the format - so it should be `parse_timestamp(.timestamp, "%+")` I think.

**Comment by lucperkins** [comment]
We're doing a big overhaul of the Remap docs and this was addressed (inadvertently heh) in #5494
