### ISSUE TITLE
Clarify benchmark units

### ISSUE THREAD

**Issue by nh2** [timberio/vector#568]
Hi, I had originally asked this question [here](https://news.ycombinator.com/item?id=20340702) but perhaps was too late to get a response:

> For clarification, does "mib/s" mean "Mbit/s" (since lowercase b usually stands for bits, and uppercase B usually for Bytes)? This makes an 8x difference.
>
> If yes, how comes log processing runs at only so low throughput in general?
>
> That is not to talk down your achievements (as per your benchmark page, you do better than similar projects in terms of throughput), but I'm genuinely curious why modern machines that have 40 Gbit/s memory bandwidth are capped at (in your case) 76.7Mbit/s. What's the bottleneck?

Independently, would you mind improving the units in the README and https://vector.dev, switching either to either `Mbit/s`,`Mibit/s`, `MB/s`, `MiB/s`, depending on which is the right one, to remove any doubt?

Thanks!

**Comment by binarylogic** [comment]
Hey @nh2, I'm amazed that I did not know this. I just updated everything to use `MiB`, thanks for pointing that out!

**Comment by nh2** [comment]
@binarylogic Great, thanks! That makes the numbers look much better :grin:
