### ISSUE TITLE
Disallow a `scrape_interval` value of <= 0.5 seconds

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5680]
We should disallow a `scrape_interval` value of <= 0.5 for all metrics sources. I chose this value since it seems like the lowest value that would not produce high CPU usage. I'd be happy to allow a lower value if we could demonstrate that it does not significantly increase CPU usage.

**Comment by jszwedko** [comment]
I believe we use integers everywhere for scrape intervals, so 1 is likely to be the lowest value we'd like to allow.

**Comment by MOZGIII** [comment]
I think we'll also want to investigate why it's not using the default properly. The default is 2 seconds, but the effective value if the setting is omitted is 0.

**Comment by MOZGIII** [comment]
Confirmed the 0-value interval bug btw. Fix is ready - https://github.com/timberio/vector/pull/5682.
