### ISSUE TITLE
Enhance documentation about building from source

### ISSUE THREAD

**Issue by romibuzi** [timberio/vector#569]
Hi there, 

First of all thank you for releasing vector ! 

I wanted to build it from source and according to the [doc](https://docs.vector.dev/setup/installation/manual/from-source) you can use `make build` to build the project but there is no such target in the Makefile. 
The closest one is `make build-archive` but it requires $TARGET and $VERSION env vars. Should we update the docs to document that or should we add a `build` target to reflect the doc ?

Thanks in advance

**Comment by LucioFranco** [comment]
Hi! Thank you for mentioning this! I just opened #570 that should address this.
