### ISSUE TITLE
New `externally_tag_types` Remap function

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5727]
I'm open to better names for this, and I'm curious if there is a specific term for this, but this function will externally tag all values with its value type. This is particularly useful for storages that require consistent types (like Elasticsearch). This function would ensure that type conflicts never exist. This strategy reminds me of DynamoDB since this is how it avoids typ conflicts.

## Example

For example, given this log event:

```json
{
  "message": "Hello world",
  "request": {
    "duration_ms": 67.9
  }
}
```

And the following Remap expression:

```js
. = externally_tag_types(.)
```

The log event would be transformed into:

```json
{
  "message": {
    "string": "Hello world"
  },
  "request": {
    "duration_ms": {
      "float": 67.9
    }
  }
}
```

**Comment by JeanMertz** [comment]
Just to clarify, with the given example, we only want to externally tag scalar types, correct?

**Comment by pablosichert** [comment]
What does the `external` refer to, specifically? If it the term is not critically to distinguish the functionality, I'd propose to call it `tag_types`.

**Comment by binarylogic** [comment]
> Just to clarify, with the given example, we only want to externally tag scalar types, correct?

The only special type we have are timestamps, and I would argue that we should tag them as `timestamp`.

> What does the external refer to, specifically? If it the term is not critically to distinguish the functionality, I'd propose to call it tag_types.

It borrows from [serde terminology](https://serde.rs/enum-representations.html#externally-tagged).

**Comment by pablosichert** [comment]
Proposal for how the tags would look like:

- Bytes: `bytes`
- Integer: `integer`
- Float: `float`
- Boolean: `boolean`
- Map: no external tag
- Array: `array`
- Timestamp: `timestamp`
- Regex: `regex`
- Null: `null`

Did you have the same specifically for `Map` and `Bytes` in mind?

**Comment by binarylogic** [comment]
Sure, a few comments on that:

* I don't think we need a `bytes` tag since the intent is to preserve types when encoding data into structured documents (ex: JSON). I don't think we can preserve that type.
* `regex` is not a supported type in our data model.
* `null` should be stripped from the document.

**Comment by pablosichert** [comment]
I took the types from the remap [Value](https://github.com/timberio/vector/blob/e6ec1d54cf87328b1b0e40000293a267c98e3bf9/lib/remap-lang/src/value.rs#L20-L30). Is there another data model that I am not aware of?

Currently the `Bytes` type serves as a container for both binary data and strings, but think it would be helpful to explicitly add a `String` type that guarantuees its content to be valid UTF-8. Do you have any insight here @JeanMertz and @FungusHumungus?

> `null` should be stripped from the document.

Im some cases the distinction between `null` and _absent_ can be important, so I'd rather add an argument e.g. `preserve_null` that defaults to `false`.

**Comment by pablosichert** [comment]
On a second thought: I think the `Array` type doesn't need an external tag either.

**Comment by pablosichert** [comment]
Another thing to put up to debate: Should the function rather be called `tag_types_externally`?

That way we could add
- `tag_types_internally`
- `tag_types_adjacently`

similar to the naming scheme of

- `encode_base64`
- `encode_json`

**Comment by binarylogic** [comment]
Yeah I like that name.

**Comment by FungusHumungus** [comment]
> Is there another data model that I am not aware of?

The main `Value` type used by Vector is here: https://github.com/timberio/vector/blob/master/src/event/value.rs#L12-L21.

Remap takes that and adds Regular Expressions since there are some functions that accept regexes as params. When converting Remap `Value` to Vector `Value` a regex would be converted to Bytes, but there is some code in there that ensures that if you attempt this it will not compile.

I think, theoretically at least, it is possible to send binary data through Vector, at least with a subset of the available components. I wouldn't imagine it is used that often, but I do have a vague recollection of someone in the support channel who was doing this. Vector won't do any UTF8 validation unless it has to when required. I presume this function would need perform the validation here in order to tag it as a String and guarantee that it actually is a String..
