### ISSUE TITLE
New `coerce` Remap function

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5728]
This is a replacement issue for #1542 since the coercion tactics described there are being deprecated. I'm also not sure if we should do this given that this could be bad for performance. Finally, if this was paired with #5727 it would ensure type conflicts never happen, which is another downside to automatic coercion.

## Examples

Given this event:

```json
{
  "duration": "23.44",
  "message": "Hello world",
  "status": "200",
  "timestamp": "26/Dec/2020:11:34:57 -0500"
}
```

And this Remap expression:

```
. = coerce(.)
```

The log event would be transformed to:

```json
{
  "duration": 23.44,
  "message": "Hello world",
  "status": 200,
  "timestamp": "2020-12-26T11:34:57 -0500"
}
```

Timestamps will be tricky, but we have/had precedence for this in the deprecated `types` options used in previous transforms:

https://github.com/timberio/vector/blob/eb7e3db3b030c6fd9d9e040d8fa98eab1d6adc09/lib/shared/src/conversion.rs#L185-L223

**Comment by lucperkins** [comment]
I don't think that a "magical" coercer like this should be favored over coercing individual fields, which hews much more closely to one of the core tenets of VRL, which is to provide Just Enough Syntax to meet user needs. Without a clear and present use case, I'm a gentle -1 on this.

**Comment by jszwedko** [comment]
I'm also wondering about consistency of coercion. As a user, I probably want all events to be coerced the same way, but remap only has knowledge of the current event so it might, for example, decide to coerce a field that is a string in some events to an integer in others if the field just happens to only contain numbers.

I wonder if better support for schemas would also solve this need?

**Comment by binarylogic** [comment]
Sure. I'm not a fan of magic either, but I still think this has utility for the operator that wants to improve the quality of their data, but doesn't want to enforce a schema.

> one of the core tenets of VRL, which is to provide Just Enough Syntax to meet user needs

Is that a core tenet? :) This should require less code to accomplish the use case I described above, but I can see how this would violate the safety and performance tenets.

**Comment by binarylogic** [comment]
I think we need this function to coerce values after decoding formats that don't preserve types, like key/value, logfmt, and URI encoding.

For example:

```
path=/checkout status=500
```

When parsed, that will produce string values:

```json
{
	"path": "/checkout",
	"status": "500"
}
```

And given that an operator won't know every key, they will want to coerce them to restore the types values into:

```json
{
	"path": "/checkout",
	"status": 500
}
```

**Comment by JeanMertz** [comment]
Should the individual parse functions instead do this (potentially with an optional parameter)? They have (in most use-cases) more information on what to coerce and what not to.

**Comment by binarylogic** [comment]
That's a good point, we can certainly start with that before considering this function.

**Comment by jszwedko** [comment]
My concern is that they might have events like:

```
{
	"path": "123",
	"status": "500"
}
{
	"path": "foobar",
	"status": "500"
}
```

Where path would be converted to a number in the first case and a string in the second. Maybe this is fine, but I feel like mixing schemas across log messages might result in undesired effects. In this case, the user knows that the `path` should be treated as a string and could enforce that.

**Comment by JeanMertz** [comment]
I agree with @jszwedko, I can't say I'm very enthusiastic about this function. I can see the use-case to "quickly get going", but I worry that it's somewhat counter to the eventual goal of making sure people are consciously dealing with their events and the different ways in which they might not be shaped the way they expect them to be.

**Comment by JeanMertz** [comment]
I'm closing this as I don't think this is the direction we want to go, and we haven't had any feedback on a need for a function like this.

We can revisit this later if need be.
