### ISSUE TITLE
The Remap `to_int` function should accept timestamps

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5730]
Passing a timestamp to `to_int` should return the Unix representation of the time as an integer.

**Comment by jszwedko** [comment]
Some may also want this to be a millisecond or nanosecond timestamp in its integer representation. I might eschew permitting `to_int` to be used with timestamps in-lieu of `to_int(format_timestamp(...))` to encourage users to control what sort of timestamp they end up with. I'd also be ok with a `to_unix_timestamp()` function.
