### ISSUE TITLE
Audit and reduce dependencies

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5738]
This is a follow-up issue for https://github.com/timberio/vector/pull/5723#pullrequestreview-559173615. We also have duplicate dependencies as mentioned in https://github.com/timberio/vector/issues/5733. Given this, it's worth an audit to explicitly reduce our dependencies. Before we begin work, we should produce a requirements list with the dependencies we want to remove and the course of action. This can be a simple checkbox list.

- [x] Replace `portpicker` with our own implementation.
- [x] Replace `derive_is_enum_variant` with our own implementation.
- [ ] Drop `is_enum_variant` in favor of defining methods manually.
- [ ] ...add more here

**Comment by fanatid** [comment]
Possible duplicated dependencies removed with `cargo update --aggressive`. Every week new PR with an update (this update also includes dependencies that are not updated by cargo aggressive update).
