### ISSUE TITLE
Emit warning log when the `check_fields`, `is_log`, or `is_metric` condition type is used

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5742]
This issue is broken out of #4791. We are breaking that issue down into smaller issues.

When a user uses the `check_fields`, `is_log`, or `is_metric` condition anywhere in Vector we should emit a log at startup warning the user that the `check_fields` condition is deprecated, redirecting them to use the `remap` condition.

**Comment by JeanMertz** [comment]
Since we don't have a way of checking if an event is a log or metric in remap, I guess we'll want to only warn when people use `check_fields`, not the other two?

**Comment by FungusHumungus** [comment]
I wonder if we should add a way of determining if it is a log or a metric event to remap?

One thing about `check_fields` is that for metric events `check_fields` will look directly in the metric tags.

This means that you can for example create a filter transform with a condition of `"host.equals" = "bart"`. For log events this checks the field "host", for metric events, this will check the "host" tag. To achieve the equivalent in remap you need to do

```
  (if exists(.tags) { .tags.host } else { .host }) == "bart"
```

The `exists(.tags)` is the only way it can really determine if it is a metric event. It is probably workable, but perhaps not ideal. Coalescing the path also doesn't work in this scenario.
