### ISSUE TITLE
Create OpenCensus exporters

### ISSUE THREAD

**Issue by derekperkins** [timberio/vector#576]
Writing OpenCensus exporters for vector would make it much easier to implement vector and provide visibility.
https://opencensus.io/exporters/

It may be best to wait until their merger with OpenTracing to become OpenTelemetry is completed. https://www.cncf.io/blog/2019/05/21/a-brief-history-of-opentelemetry-so-far/

**Comment by binarylogic** [comment]
Closing in favor of https://github.com/timberio/vector/issues/1444
