### ISSUE TITLE
Investigate how to reduce Vector's binary size

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5765]
Vector's binary size has grown over time, and before it gets too large for resource-constrained environments we should investigate how to reduce it. I'm curious if there are easy wins here. The value of reducing the size is not worth copious amounts of time to achieve it.

**Comment by binarylogic** [comment]
@fanatid as a first step we'd like you to investigate _only_, and add what you think the steps would be to reduce the binary size. Once we agree on the steps that are worth it, we can create tickets and assign those to you. This issue represents investigative work only.

**Comment by jszwedko** [comment]
Just noting there was some discussion around this in discord that could be useful: https://discord.com/channels/742820443487993987/746070604192415834/786270584471814164 . Primarily: https://github.com/johnthagen/min-sized-rust

**Comment by fanatid** [comment]
Remark for myself: https://github.com/dtolnay/cargo-llvm-lines can be probably useful too.
