### ISSUE TITLE
New Remap function for `to_syslog_facility`

### ISSUE THREAD

**Issue by jbradleynh** [timberio/vector#5769]
Similar to request to map syslog severity levels to human readable keywords from  #5500 it would be helpful to have a means to remap [syslog facility codes](https://en.wikipedia.org/wiki/Syslog#Facility) to their keyword as well.

### Use-cases

When parsing events message from the journald source, the raw facility values could be enriched with a simple remap transform to down stream labeling

### Proposal

create a remap-function `to_syslog_facility` which could produce the facility name:

```rust
to_syslog_facility(10)
=> "authpriv"
```

### References

- #4304 related to need for cleanup of journald sources

**Comment by JeanMertz** [comment]
Resolved in #5770
