### ISSUE TITLE
Error when the Remap `del` function attempts to delete a path that doesn't exist

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5779]
This is a replacement issue for #5566 to more clearly represent the conclusion there:

> So given this, I’m almost inclined to say: when deleting a path, you have to handle the error case for when a path does not exist.

This is blocked on #5479 since we should resolve our error handling primitives first.

**Comment by JeanMertz** [comment]
We opted not to do this, instead documenting the existence of the `exists` function to make a distinction between existing `null` fields or non-existing fields. See the discussions in #5633.
