### ISSUE TITLE
Accept multiple patterns in the `parse_regex` Remap function

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5781]
This is a replacement issue for #5726. The ability to attempt parsing a log with multiple patterns is a _very_ common pattern that we need to support. Given that this is specific to parsing functions that accept custom patterns, it makes more sense to just accept multiple patterns in priority order. This, in my opinion, makes more sense than requiring the user to jump through error handling hoops.

## Example

```js
. = parse_regex(.message, [
	/^(?P<timestamp>[^\\]]+) \\[(?P<level>\\w+)\\] (?P<pid>[0-9]+)#(?P<tid>[0-9]+): \\*(?P<cid>[0-9]+) (?P<message>.*)$/,
	/client: (?P<client>[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3})/,
	/server: (?P<server>[^,]+)/
])
```

**Comment by JeanMertz** [comment]
I would personally prefer if we generalize this pattern by allowing one to "execute multiple expressions until one succeeds and return the value of that expression".


For example, we could add a `try` block that executes each expression, until one succeeds:

```rust
. = try {
	parse_regex(.message, /^(?P<timestamp>[^\\]]+) \\[(?P<level>\\w+)\\] (?P<pid>[0-9]+)#(?P<tid>[0-9]+): \\*(?P<cid>[0-9]+) (?P<message>.*)$/)
	parse_regex(.message, /client: (?P<client>[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3})/)
	parse_regex(.message, /server: (?P<server>[^,]+)/)
}
```

If all expressions fail, the last failed expression error is returned.

If you want to make sure this expressions is infallible, you can add an `else` block:

```rust
. = try {
	// ...
} else {
	.message
}
```

**Comment by JeanMertz** [comment]
I added support for the error coalescing operator in #5830. I definitely prefer it over other solutions because it is a more generic solution that can be applied to all expression types while still being succinct enough to remain readable, but am happy to discuss this if you feel differently.

**Comment by binarylogic** [comment]
@JeanMertz this is fine. I'm happy to start with this:

```
. = parse_regex(.message, /^(?P<timestamp>[^\\]]+) \\[(?P<level>\\w+)\\] (?P<pid>[0-9]+)#(?P<tid>[0-9]+): \\*(?P<cid>[0-9]+) (?P<message>.*)$/) \
  ? parse_regex(.message, /client: (?P<client>[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3})/) \
  ? parse_regex(.message, /server: (?P<server>[^,]+)/) \
  ? .message
```

How would a user fail the script instead of defaulting to `.message` though?

Closing as a result.
