### ISSUE TITLE
Accept multiple patterns in the `parse_grok` Remap function

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5782]
This is a replacement issue for #5726. Same as #5781 but for the `parse_grok` Remap function.

**Comment by JeanMertz** [comment]
I left a comment in https://github.com/timberio/vector/issues/5781#issuecomment-753896751 to generalize this pattern.

**Comment by binarylogic** [comment]
Closing as a result of https://github.com/timberio/vector/issues/5781#issuecomment-753944242
