### ISSUE TITLE
Magic `*_keys` and `*_values` Remap functions

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5785]
Yes, I said "magic" 🐰 . #5377, #5784, and #5783 introduce functions that walk and mutate the entire event. They are simple solutions that avoid hard-to-follow traversal/walk constructs in Remap, like the ones being discussed in #4518. These functions are much easier to implement, read, and understand. To avoid the repetitive nature of defining functions that end with `_keys` and `_values` it would be nice to get these functions automatically. I'm on the fence with this but wanted to record an explicit decision here before we move forward with the blocked issues.

## Requirements

- [ ] Automatically define `*_keys` and `*_values` for functions that operate on single values (accept a single value as their first parameter).

**Comment by binarylogic** [comment]
@JeanMertz I'd like to get your approval/opinion on this before starting on #5377, #5784, and #5783. I'm not opposed to just creating these functions to start and then cleaning them up later.

**Comment by JeanMertz** [comment]
Closing this as we are going to work on iteration this quarter, which should solve this need as well.
