### ISSUE TITLE
New `get_env_var` Remap function

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5801]
Retrieves an environment variable's value.

## Example

```js
.hostname = get_env_var("HOSTNAME")
```

## Requirements

- [ ] Should error if the env var does not exist.

**Comment by jszwedko** [comment]
> Should error if the env var does not exist.

I think it is a common pattern when environment variables are used as flags to allow an unset variable to be the same as the variable set to `0`, `false`, or `""`. We may want to facilitate that by returning `""` when the variable is not set.

**Comment by JeanMertz** [comment]
> We may want to facilitate that by returning `""` when the variable is not set.

You could always write `get_env_var("HOSTNAME") ?? ""` yourself, instead of us assuming you want it to resolve to an empty string.

**Comment by jszwedko** [comment]
Agreed, my comment predated the error coalescing discussion. I think `get_env_var("HOSTNAME") ?? ""` is reasonable for this case.
