### ISSUE TITLE
Ability to specify file extension for `aws_s3` sink

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#582]
Hi!

I'm planning to use Vector as a way to continuously write content of a Kafka topic to S3 (using [kafkacat](https://github.com/edenhill/kafkacat) and `stdin` source).

I would like the output objects to have extension `.jsonl.gz`, but it seems to be not possible to change the extension from default `.log.gz`.

Thanks for the amazing piece of software, by the way!

**Comment by binarylogic** [comment]
Thanks @a-rodin, this makes sense. And appreciate the feedback, keep it coming! 😄
