### ISSUE TITLE
Diagram not found 

### ISSUE THREAD

**Issue by juchiast** [timberio/vector#5832]
https://vector.dev/docs/reference/sinks/loki/

On "Buffers & batches":
> This component buffers & batches data as shown in the diagram above

But there is no diagram.

**Comment by jszwedko** [comment]
This diagram appears to be here now:

<img width="788" alt="Screen Shot 2021-09-08 at 12 53 47 PM" src="https://user-images.githubusercontent.com/316880/132576267-cd87a803-97f1-4db8-9359-79ba728caca4.png">
