### ISSUE TITLE
kubernetes_logs source doesn't detect new pods

### ISSUE THREAD

**Issue by Alexx-G** [timberio/vector#5846]
There was an existing Nginx deployment **before** I deployed the vector-agent helm chart. Everything was working fine until I've decided to do a rolling restart of the Nginx deployment, what caused the pod to be scheduled to a different node (due to pod anti-affinity rules).
However after several hours I've noticed that sink (S3 bucket) doesn't receive any logs from the new Nginx pod, when I checked vector-agent logs from the corresponding Node, I didn't see any log messages that is started watching Nginx logs.

### Vector Version

```
timberio/vector:0.11.1-debian
```
**Kubernetes environment:** `1.17 (AWS EKS)`

### Vector Configuration File

```yaml
# Schema part of the generated `vector` config.
logSchema:
  hostKey: "host"
  messageKey: "message"
  sourceTypeKey: "source_type"
  timestampKey: "timestamp"

kubernetesLogsSource:
  enabled: true
  sourceId: kubernetes_logs
  rawConfig: |
    extra_field_selector = "metadata.namespace=ingress-nginx"

internalMetricsSource:
  enabled: true
  sourceId: internal_metrics
  rawConfig: null

# The "built-in" host metrics source emitting the metrics gathered from the node
# that Vector is executing on.
hostMetricsSource:
  # Disable to omit the host metrics source from being added.
  enabled: true
  # The name to use for the "built-in" host metrics source.
  sourceId: host_metrics
  # Raw TOML config to embed at the host metrics source.
  rawConfig: null

# The "built-in" prometheus sink exposing metrics in the Prometheus scraping
# format.
# When using this "built-in" sink, we automatically configure container ports,
# and ensure things are ready for discovery and scraping via Prometheus'
# `kubernetes_sd_configs` jobs.
prometheusSink:
  # Disable to omit the prometheus sink from being added.
  enabled: true
  # The name to use for the "built-in" prometheus sink.
  sinkId: prometheus_sink
  # Inputs of the built-in prometheus sink.
  # If you have built-in internal metrics source enabled, we'll add it as a
  # input here under the hood, so you don't have to pass it here.
  # Unless `excludeInternalMetrics` is set to `true`, in which case you're
  # responsible of wiring up the internal metrics.
  inputs: []
  # Set this to `true` to opt-out from automatically adding the built-in
  # internal metrics source to the inputs.
  excludeInternalMetrics: false
  # The address to listen at.
  listenAddress: "0.0.0.0"
  # The port to listen at.
  listenPort: "9090"
  # Raw TOML config to embed at the vector source.
  rawConfig: null
  # Add Prometheus annotations to Pod to opt-in for Prometheus scraping.
  # To be used in clusters that rely on Pod annotations in the form of
  # `prometheus.io/scrape` to discover scrape targets.
  addPodAnnotations: false
  # Use prometheus-operator `PodMonitor` to opt-in for Prometheus scraping.
  # To be used in clusters that rely on prometheus-operator to gether metrics.
  # You might want to set `podMonitorSelectorNilUsesHelmValues=false` if you're
  # using prometheus-operator Helm chart to allow `PodMonitor` resources
  # dicovery in all namespaces.
  podMonitor:
    # Whether to add the `PodMonitor` resource or not.
    # `prometheus-operator` CRDs are necessary, otherwise you'll get an error.
    enabled: false
    # Additional relabelings to include in the `PodMonitor`.
    extraRelabelings: []


transforms:
  app_logs:
    type: "swimlanes"
    inputs: ["kubernetes_logs"]
    rawConfig: |
      lanes.nginx."kubernetes.container_name.eq" = "nginx-ingress-controller"

# Sinks to add to the generated `vector` config.
sinks:
  nginx_s3:
    type: "aws_s3"
    inputs: ["app_logs.nginx"]
    rawConfig: |
      bucket = "..."
      region = "us-west-2"
      encoding.codec = "text"
      key_prefix = "date=%F/"

```

### Expected Behavior

Kubernetes source must pick up newly created pod and forward logs.

### Actual Behavior

Vector agent deployed on the node with the new pod, didn't detect it and no logs have been forwarded to the sink.

### Example Data

Logs from the vector agent deployed to the node where a new Nginx pod has been added by the deployment. Notice that there are no logs after Dec 30.

```
Dec 30 14:43:15.278  INFO vector::app: Log level is enabled. level="vector=info,codec=info,file_source=info,tower_limit=trace,rdkafka=info"
Dec 30 14:43:15.278  INFO vector::app: Loading configs. path=[("/etc/vector/managed.toml", None)]
Dec 30 14:43:15.280  INFO vector::sources::kubernetes_logs: Obtained Kubernetes Node name to collect logs for (self). self_node_name="ip-10-43-2-174.us-west-2.compute.internal"
Dec 30 14:43:15.295  INFO vector::topology: Running healthchecks.
Dec 30 14:43:15.295  INFO vector::topology: Starting source. name="kubernetes_logs"
Dec 30 14:43:15.295  INFO vector::topology: Starting transform. name="app_logs.nginx"
Dec 30 14:43:15.295  INFO vector::topology: Starting sink. name="nginx_s3"
Dec 30 14:43:15.295  INFO vector: Vector has started. version="0.11.1" git_version="v0.11.1" released="Thu, 17 Dec 2020 17:09:17 +0000" arch="x86_64"
Dec 30 14:43:15.295  INFO vector::app: API is disabled, enable by setting `api.enabled` to `true` and use commands like `vector top`.
Dec 30 14:43:15.296  INFO source{component_kind="source" component_name=kubernetes_logs component_type=kubernetes_logs}:file_server: file_source::checkpointer: Loaded checkpoint data.
Dec 30 14:43:15.331  INFO vector::topology::builder: Healthcheck: Passed.
Dec 30 14:44:16.779  INFO source{component_kind="source" component_name=kubernetes_logs component_type=kubernetes_logs}:file_server: vector::internal_events::file::source: Resuming to watch file. path="/var/log/pods/ingress-nginx_echoserver-6b856cc8dc-kcpcr_4997bd83-bc8f-46be-9fe0-6a138306e0fc/echoserver/0.log" file_position=558687
```

**Comment by Alexx-G** [comment]
Update - restarting vector-agent daemonset fixes the issue (meaning vector-agent forwards logs now), however still the expectation is that new pods are detected "on the fly".

**Comment by binarylogic** [comment]
Thanks @Alexx-G, we'll investigate and fix.

**Comment by tustvold** [comment]
I'm still digging into this but at least for me the stuck nodes have very strange looking metrics from the kubernetes reflector loop, in particular they have a similar order of magnitude for `vector_k8s_watch_requests_invoked_total` and  `vector_k8s_stream_chunks_processed_total` and the rate of the former indicates it is capping out at 1 request per second. 

This suggests to me something off with [this piece of code](https://github.com/timberio/vector/blob/master/src/kubernetes/reflector.rs#L75). `pause_between_requests` is set to 1 second which fits with the 1 rps I'm seeing. On restart the new files are found and the rate returns to 1 per ~5 minutes which fits with the watch expiry of [290 seconds](https://github.com/timberio/vector/blob/master/src/kubernetes/reflector.rs#L145).

I'll keep looking but thought I'd share what I've found so far

**Comment by tustvold** [comment]
I think I have found the culprit, the desync detection makes the perfectly reasonable assumption that the HTTP status code matches the status code in the response. This is true sometimes with kubernetes, but for some reason does not appear to be the case here

Relevant code

```
        let status = response.status();
        if status != StatusCode::OK {
            let source = invocation::Error::BadStatus { status };
            let err = if status == StatusCode::GONE {
                watcher::invocation::Error::desync(source)
            } else {
                watcher::invocation::Error::other(source)
            };
            return Err(err);
        }
```
Example response

```
HTTP/1.1 200 OK
Audit-Id: cae51432-66ad-4d7b-89ff-bcd4352842b0
Content-Type: application/json
Date: Wed, 06 Jan 2021 11:45:41 GMT
Transfer-Encoding: chunked

{
    "object": {
        "apiVersion": "v1",
        "code": 410,
        "kind": "Status",
        "message": "too old resource version: 12122 (359817167)",
        "metadata": {},
        "reason": "Gone",
        "status": "Failure"
    },
    "type": "ERROR"
}
```

**Comment by eeyun** [comment]
This is a fantastic find, thanks for your effort!

**Comment by binarylogic** [comment]
@tustvold thanks for your work on this! I couldn't find your contact information, but I have no shame 😆. I would love to talk to you about joining the Vector team and working on Vector full time (if that interests you). At the very least, it would be great to meet you. Feel free to email me if interested: ben@timber.io - I won't bother you again about this!

**Comment by uthng** [comment]
I constated the same issue when I delete a pod and a new one is created but its logs are not sent to ES by the vector agent. In the log of vector agent in the same node of the pod, I got:

`Jan 06 23:40:02.952  INFO source{component_kind="source" component_name=kubernetes_logs component_type=kubernetes_logs}:file_server: vector::internal_events::file::source: Stopped watching file. path="/var/log/pods/istio-system_istio-ingressgateway-5fd454f8ff-bz59q_56cf8280-bbf0-4685-aede-b7fc27054e79/istio-proxy/0.log"`

and nothing else after.

**Comment by MOZGIII** [comment]
I guess the problem is here:
https://github.com/timberio/vector/blob/15d3db09bc94f154a7dffefdb31e6c640a9a51a1/src/kubernetes/api_watcher.rs#L79

I'm checking the response status code (which is 200) instead of the error code in the body (which is 410). It's an overlook from my part.

**Comment by uthng** [comment]
Hello,

I would like to know if you're planning the correction of this bug in the next release or soon? I would like to use Vector on production because it is really amazing and better than others stuffs, but it will be quite difficult to do without the correction.

Thanks.

**Comment by MOZGIII** [comment]
We're working on the fix - see https://github.com/timberio/vector/pull/6053. It should land soon (I suppose this week). It'll be available in the nightly builds as soon as we merge it!

**Comment by eeyun** [comment]
https://github.com/timberio/vector/pull/6053#issuecomment-769919389
