### ISSUE TITLE
Kubernetes Reflector Silently Drops Errors

### ISSUE THREAD

**Issue by tustvold** [timberio/vector#5877]
Whilst investigating #5846 I realised that watch stream errors are silently dropped as `Reflector::process_stream_item` silently ignores any watch event without a resource version. This would have made it significantly easier to diagnose the incorrect desync detection in #5846 as the logs would have been filled with too old resource version errors

**Comment by eeyun** [comment]
https://github.com/timberio/vector/pull/6053#issuecomment-769919389
