### ISSUE TITLE
Don't log errors in the `file` source when the directories are included

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5886]
Currently, when a user uses the `file` source, Vector will continually log errors for directories found:

```
file_source::file_server: Error reading file for fingerprinting err=Is a directory (os error 21) file="..."
```

- [ ] Move these to `debug`.
- [ ] Only log them once for each directory (if possible). We should discuss this so it doesn't slowly increase memory for the bookkeeping.

cc @lukesteensen

**Comment by ktff** [comment]
We shouldn't even log this for directories, but just filter them out before fingerprinting, since they are of no interest to `file` source.
