### ISSUE TITLE
Remap boolean operators don't short circuit

### ISSUE THREAD

**Issue by FungusHumungus** [timberio/vector#5889]
Given the following repl session:

```
$ .
{ "foo": 2 }

$ false && del(.foo)
false

$ .
{  }
```

I would expect `.foo` to not be deleted since the `&&` should stop evaluation of the right hand side if the left hand side is `false`. However, currently both sides are evaluated regardless.

The same applies to `||`.

**Comment by binarylogic** [comment]
Closing in favor of https://github.com/timberio/vector/issues/4706

**Comment by FungusHumungus** [comment]
Oh, sorry, didn't see that.

**Comment by JeanMertz** [comment]
Ah! Sorry, @FungusHumungus. I asked Stephen to file an issue, not realizing I had already done so quite a while ago 🙈
