### ISSUE TITLE
Source file failed to read new found files from the beginning

### ISSUE THREAD

**Issue by voyagertanyao** [timberio/vector#5902]
**Vector 0.10.0** 
**centOS 7**
/etc/vector/vector.toml just like this:

[sources.user_tag_source]
> type = "file"
> file_key="file"
> fingerprinting.strategy="device_and_inode"
> glob_minimum_cooldown=5000
> ignore_older=3600
>  include=["/data/vector/es/**/*.txt"]
>  oldest_first=true
> remove_after=604800

It works very well when Vector startup with no file in ["/data/vector/es/**/*.txt"] directory，following adding some files，Vector can correctly read data from the beginning;
But when we manually delete some files in the directory ["/data/vector/es/**/*.txt"]，after this， we add other new files into the directory，then incomprehensenible  things happen :

**If the file size of new added file equals the file size of deleted one before, Vector just read data from the end of that new file**

For example:
If we currently have files in directory ["/data/vector/es/**/*.txt"] like this:
>     1.txt   (size 10 Byte)
>     2.txt   (size 20 Byte)
And we delete the file 1.txt
Then we manually add another file named 3.txt with the same content in 1.txt，（no copy 1.txt，but generate same content），
**Vector just set file checkpoint to 10，which is the end of 3.txt**
WHY？The fingerprinting I set is "device_and_inode"

**Comment by lukesteensen** [comment]
> Then we manually add another file named 3.txt with the same content in 1.txt

The reason is that, by default, Vector identifies files based on their content. The relevant docs are [here](https://vector.dev/docs/reference/sources/file/#fingerprint-1).

We also support an alternative strategy of using the device and inode numbers to identify files, which has some edge cases but seems to better match what you expect here. You can use that by setting `fingerprint.strategy = "device_and_inode"` in the [file source config](https://vector.dev/docs/reference/sources/file/#strategy).

Sorry about the confusion, and please do feel free to reopen if this does not resolve your problem!

**Comment by itayvolo** [comment]
Same here, tried what you suggested with the strategy but still nothing:

```
2024-09-24T13:12:38.087078Z ERROR source{component_kind="source" component_id=file component_type=file}:file_server: vector::internal_events::file::source: Failed reading file for fingerprinting. file=/var/log/containers/pod_name_namespace_container_name-474fbffdc73c84950353261544411a2309f96c96957a6aa7e69cfcdd45591858.log error=No such file or directory (os error 2) error_code="reading_fingerprint" error_type="reader_failed" stage="receiving" internal_log_rate_limit=true

2024-09-24T13:12:38.087123Z ERROR source{component_kind="source" component_id=file component_type=file}:file_server: vector::internal_events::file::source: Internal log [Failed reading file for fingerprinting.] is being suppressed to avoid flooding.
```

Here's my config:
```
      file:
        type: file
        data_dir: /var/local/lib/vector/
        fingerprint:
          strategy: device_and_inode
        include:
          - /var/log/containers/${VECTOR_POD_NAME}_${VECTOR_POD_NAMESPACE}*.log
        ignore_older_secs: 3600
```
The errors say that the file doesn't exist, but as you can see in the log it does recognize the file by its full name when I only configured wildcard in the config.. 

Any idea how to solve it?
