### ISSUE TITLE
Remap should allow raw string literals

### ISSUE THREAD

**Issue by FungusHumungus** [timberio/vector#5905]
When defining a grok pattern, quite often these patterns will include `"` and `\` that need to be escaped.

For example the following pattern

```
%{IPORHOST:client_ip} - %{USER:ident} \[%{TIMESTAMP_ISO8601:timestamp}\] %{IPORHOST:domain} "(%{WORD:method} %{NOTSPACE:request_uri}(?: HTTP/%{NUMBER:http_version})?)" %{NUMBER:response} %{NUMBER:bytes_sent} %{NUMBER:response_time_ms} %{QS:http_referer} %{QS:agent}
```

Actually needs to be 

```rust
parse_grok(.messgae, "%{IPORHOST:client_ip} - %{USER:ident} \\[%{TIMESTAMP_ISO8601:timestamp}\\] %{IPORHOST:domain} \"(%{WORD:method} %{NOTSPACE:request_uri}(?: HTTP/%{NUMBER:http_version})?)\" %{NUMBER:response} %{NUMBER:bytes_sent} %{NUMBER:response_time_ms} %{QS:http_referer} %{QS:agent}")
```

Requiring these escapes is confusing and error prone. We should allow Remap to support a way of creating strings that don't require escapes.

Something similar to Rust raw strings would work. Surrounding strings with `r#"..."#` - any number of `#` characters can be used if the actual string needs to contain a `"#`. So this is a also a valid string:

`r##"We can surround strings with r#".."# and it will work"##`

The above pattern would be:

```rust
parse_grok(.messgae, r#"%{IPORHOST:client_ip} - %{USER:ident} \[%{TIMESTAMP_ISO8601:timestamp}\] %{IPORHOST:domain} "(%{WORD:method} %{NOTSPACE:request_uri}(?: HTTP/%{NUMBER:http_version})?)" %{NUMBER:response} %{NUMBER:bytes_sent} %{NUMBER:response_time_ms} %{QS:http_referer} %{QS:agent}"#
```

**Comment by JeanMertz** [comment]
I can see the appeal for this. We could also use single quotes to achieve the same. If you want to use single quotes inside the string, you can escape those:

```js
parse_grok(.message, 'can use " and \ and \' etc')
```

Perhaps we can think of another solution to this? I do like the simplicity of only having one way to use string literals 🤔
