### ISSUE TITLE
Fix Remap `fallible_unless` type definition method

### ISSUE THREAD

**Issue by JeanMertz** [timberio/vector#5915]
The `fallible_unless` method we have for type definitions isn't working as expected.

For example; `5 / "foo"` results in a type definition for an _infallible_ expression, while this obviously will fail at runtime.

I pushed a branch in which I started to debug this, backed out of it for now, but will circle back to it soon.

https://github.com/timberio/vector/commit/a2d7a317b301de7b3f5353e7682c5eb3c17a9a26

cc @FungusHumungus

**Comment by binarylogic** [comment]
@JeanMertz is this still relevant given the latest changes?

**Comment by JeanMertz** [comment]
Solved in recent refactor.
