### ISSUE TITLE
Prometheus Sink Not Updating

### ISSUE THREAD

**Issue by tustvold** [timberio/vector#5916]
### Vector Version

```
Current master 19a90e8f1cba1642cfc9b97e8598c6a9ef310372
```

### Bug Report

The prometheus_sink is not updating with new metrics, new metric _samples_ (set of name and labels) appear but the values never update again.

**Comment by jszwedko** [comment]
@jamtur01 @binarylogic just noting that @tustvold mentioned this was working on 0.11.1 so we should fix this before 0.12.

**Comment by juchiast** [comment]
I think @bruceg and @tustvold is already working on it.
