### ISSUE TITLE
Doc bug: gcp_stackdriver_logs sink docs doesn't say that "resource" is necessary

### ISSUE THREAD

**Issue by mwoodson** [timberio/vector#5929]
I believe this is a simple doc bug.  Famous last words.

I am playing with the gcp_stackdriver_logs sink.  In doing so, I followed the docs here:

https://vector.dev/docs/reference/sinks/gcp_stackdriver_logs/

After configuring it without the "resource" type, I got the error:

`Jan 07 21:04:44.811 ERROR vector::cli: Configuration error. error=missing field `resource` for key `sinks.gcp_cloud_operations` at line 38 column 1
`

After adding the resource type, I was able to start it.  

The docs mention that "resource" is optional.  This doesn't appear to be the case.

### Vector Version

```
version="0.12.0" git_version="v0.11.0-265-g5b5222c"
```

### Vector Configuration File

```toml

```

**Comment by binarylogic** [comment]
Thanks for reporting. This is fixed.
