### ISSUE TITLE
increase test coverage and fix issues with `inner_type_def`

### ISSUE THREAD

**Issue by JeanMertz** [timberio/vector#5939]
The `inner_type_def` work was added pretty quickly to solve a particular issue we were having at the time. While we have tests that cover this, I'm pretty sure we're still lacking some, and I can see one case where we have an inconsistency (which might result in a bug, but I'm not sure yet).

This example:

```rust
.foo = parse_json(.bar)
```

Would result in a type def that includes any valid JSON types (scalars, map or array), but it keeps `inner_type_def` at `None`. Technically, I guess we should set it to "any", since if it's a map or array, we don't know what types are included within those collections.

I'm not convinced this is an issue right now, but I do think this is an area we should look at and potentially improve.

**Comment by binarylogic** [comment]
@JeanMertz is this still relevant given the latest changes?

**Comment by JeanMertz** [comment]
This one was solved in the recent refactor.
