### ISSUE TITLE
Transforms document that `processed_bytes_total` is part of its telemetry when it is not

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5962]
For example, the `remap` transform [documents](https://vector.dev/docs/reference/transforms/remap/#processed_bytes_total) that it expose the `processed_bytes_total` telemetry metric when it does not.

**Comment by lucperkins** [comment]
@bruceg Could you verify that this is the case?

**Comment by lucperkins** [comment]
Closed by #6010
