### ISSUE TITLE
Problems with the `assert` Remap function

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5963]
These are some minor things I noticed while cleaning up Remap docs:

1. I would expect `assert` to return `true` on success.
2. Should the function be renamed to `assert!` given that it raises an error?
3. Should we allow error handling? That seems silly given the purpose of the function.

**Comment by JeanMertz** [comment]
> I would expect `assert` to return `true` on success.

I've fixed this in https://github.com/timberio/vector/pull/6353.

> Should the function be renamed to `assert!` given that it raises an error?

A function cannot have `!` at the end, that's something the compiler enforces based on its fallibility. Some functions (like this one, and `parse_jon`) are _always_ fallible, so there's no way to use them without handling the error, but you can still handle the `assert` error using `ok, err =` and `assert!(...) ?? null`.

> Should we allow error handling? That seems silly given the purpose of the function.

There's no way _not_ to allow error handling. Functions have no control over how VRL calls them and handles them. This would have to be a built-in (something we haven't done so far, so this requires some more design consideration) to be able to special-case this function.

**Comment by JeanMertz** [comment]
I'm closing this for now as the biggest issue has been resolved, and the others are not supported by the language right now. If we do want to support any of those changes, it's best to create a dedicated issue describing the language change we want to make.
