### ISSUE TITLE
Question: multiple instances of Vector with the same data_dir

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#597]
What would happen if multiple instances of Vector with the same configuration file are using the same data directory with `disk` buffer?

Would there be a conflict or duplicated output, or would it be just fine?

**Comment by binarylogic** [comment]
Great question, I'd _highly_ recommend that each running instance of Vector have an exclusive `data_dir`. Perhaps you could set it to `/var/lib/vector1` and so on.

---

Technically though, this would work fine as long as your `sink_id`s are unique across instances. For example:

```
[sinks.my_s3_sink]
  type = "aws_s3"
  # ...
```

This creates a namespaced buffer using `my_s3_sink` as id. If 2 running instances of Vector have the same sink IDs then there would be a conflict. If not, it would work fine.

I'm curious if you have any clever workarounds? Or, if you were expecting any specific behavior?

**Comment by a-rodin** [comment]
> Or, if you were expecting any specific behavior?
I'm thinking about the following use case.

Let's say that I have a service that sends data to Vector. I want to deploy it for example to [AWS ECS](https://aws.amazon.com/ecs/) backed by EC2, having both my service and Vector inside a single [task definition](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definitions.html). It is desirable to have them in the same task definition because Vector's configuration lives in the service's repository and because this way it is not needed to do service discovery from the service.

But if [scheduling strategy](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/scheduling_tasks.html) for the service is set to `REPLICA`, it is possible to end up in a situation when there are multiple tasks consisting of service+Vector pairs running on the same underlying EC2 instance, for example during rolling deployments.

In this situation using disk buffer with pre-defined mount point for `data_dir` on underlying EC2 instance would mean that it is possible to have multiple Vector instances with identical configuration (and thus the same `sink_id`).

There are multiple solutions to avoid this problem, but each of them has its own trade-offs:
* Don't use disk buffer, in this case downtimes on the sink side would cause out-of-memory or dropping of the events;
* Use separate volume for each task (automatically set up by ECS), but in this case the disk buffer would not provide persistence between restarts of service+Vector pair;
* Use `DAEMON` scheduling strategy instead of `REPLICA`, but in this case it would not be possible to do rolling deployments while keeping the desired number of running instances of the service without having additional spare instances;
* Have a separate cluster of Vector instances and send events to them from the agent Vector. But this adds additional complexity, such as the need to do service discovery, load balancing, and also separate monitoring and scaling for this cluster.

So this question was mostly to check out whether it is a good idea or not to use the configuration that I've described above with `REPLICA` scheduling strategy and disk buffer, but without a separate Vector cluster.

**Comment by LucioFranco** [comment]
@a-rodin I have not used ECS that much but I know in systems like k8 and nomad you can get a task specific id, I wonder if that could be used to namespace the instance of vector within the task?

**Comment by a-rodin** [comment]
@LucioFranco Do you mean to namespace it so that each instance of Vector uses its own data directory?

**Comment by lukesteensen** [comment]
Environment variables are interpolated into the config when it's loaded, so you could get unique data directories with an identical config file if you have access to an env var that varies across the instances.

**Comment by a-rodin** [comment]
So from this I see that the best way to deploy Vector on ECS is to run only one instance at time per data directory and machine. Then, if there are sources that require Vector to be constantly up, there should be multiple machines with Vector, and Vector service should run behind a load balancer. This setup would allow to have both persistent state between restarts/deployments of Vector and zero downtime during deployment.
