### ISSUE TITLE
Add support for templating with metric events

### ISSUE THREAD

**Issue by bruceg** [timberio/vector#5985]
Vector's template support currently assumes that the input event is a log. However, the full implementation of #5598 requires support for metrics as well. I've added this as a separate issue as it is somewhat out of scope for that issue.

**Comment by binarylogic** [comment]
Thanks. To keep things simple and ensure we're aligned, we only need to support metrics tags:

```
{{tag}}
```

**Comment by bruceg** [comment]
The original requester of #5598 has indicated that he also needs support for using the metric namespace in the template. See https://discord.com/channels/742820443487993987/746070604192415834/803314554959560714

**Comment by mrmassis** [comment]
Tkz @bruceg

**Comment by mrmassis** [comment]
This feature is so important.
