### ISSUE TITLE
Don't use ANSI terminal color sequences when the output is not a terminal

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#599]
Sometimes the logs of Vector itself are piped to a logs collection system. In this case it is desirable to not have ANSI escape sequences, but only plain text, to avoid seeing logs lines like this:

```
[32m INFO[0m vector: Log level "info" is enabled.
```

It would be nice to detect whether Vector runs in a TTY and/or use a special flag to enable or disable colored output.

**Comment by LucioFranco** [comment]
@a-rodin very good idea, this is totally possible right now we use a `tracing-fmt` subscriber that has this option. We should probably provide a `--no-color` option.

**Comment by a-rodin** [comment]
@LucioFranco I've checked out `tracing-fmt`, it looks like ANSI sequences can be enabled/disabled only on the level of Cargo package features, but not at runtime: https://github.com/tokio-rs/tracing/blob/master/tracing-fmt/src/default.rs#L275-L299.

**Comment by LucioFranco** [comment]
Once this PR is merged we can use the builder flag and finish this issue. https://github.com/tokio-rs/tracing/pull/175
