### ISSUE TITLE
New `parse_<type>` Remap functions

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#6000]
Like the `to_int`, `to_string`, etc. functions, we need `parse_int`, `parse_string`, etc functions that work exclusively with strings. The difference between the 2 is:

```
to_int(false) => 0
parse_int(false) => error
```

We should have:

- [ ] `parse_int`
- [ ] `parse_float`
- [ ] `parse_boolean`

This should not block 0.12.

**Comment by jszwedko** [comment]
I'm a little confused about `to_int` not throwing an error given the example in https://github.com/timberio/vector/issues/5960#issuecomment-758787757 of:

```
. = { "status": "not a status" }
.status = to_int(.status) ?? 200
```

Would `to_int` not need to error there?

**Comment by binarylogic** [comment]
It would error, but `??` would catch the error and set it to `200`.

**Comment by jszwedko** [comment]
Ah, gotcha, I was just confused by the example in the PR description of `to_int(false) => 0`, but I can see a use for mapping false => 0 and true => 1.

**Comment by JeanMertz** [comment]
The issue description mentions `parse_string`, but I don't think there's any use for that function, correct?

**Comment by binarylogic** [comment]
Correct, `parse_string` is pointless 😁 . I left it out of the requirements.

**Comment by JeanMertz** [comment]
We added functions that perform a similar role:

```coffee
$ int!(false)
function call error for "int" at (0:11): expected "integer", got "boolean"
```

Closing this as the intended use-case is resolved.

**Comment by jszwedko** [comment]
I think the type assertions are a bit different than the intent of this issue. I believe the intent is to have `parse_int` and friends that parse strings into the target type. We have `to_int`, `to_float`, etc. which do do this though.

`parse_int` was added recently in #8078 which allows string parsing of an `int` in various formats.

I could see us still adding `parse_float`, and `parse_bool`, but we can leave it until someone asks for it.
