### ISSUE TITLE
Update `thread_local` dependency?

### ISSUE THREAD

**Issue by fanatid** [timberio/vector#6005]
With new version of [thread_local](https://crates.io/crates/thread_local) (`1.1.0`) structs which use `CachedThreadLocal` increase their own size from 48 bytes to 544. I'm not sure how this will change `vector` memory consumption so I not updated `thread_local` in https://github.com/timberio/vector/pull/5999#discussion_r555936500. We need to figure this out before update it (I guess everything will look ok but better check).

**Comment by jszwedko** [comment]
`CachedThreadLocal` was deprecated and replaced with a simple wrapper over `ThreadLocal`. This decreases `Regex`'s size back down to 16 bytes.
