### ISSUE TITLE
Parent fields should be marked as `map` types during nested assignment in Remap

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#6006]
From our chat:

One thing that doesn't yet work I believe is this:

```
.foo.bar = "baz"
.foo.bar // string
.foo // any
```

That is to say, in this last example, `.foo.bar` would be tracked as being a `string`, but `.foo` should be known as a `map`, but currently isn't. Would be nice to fix that case.

**Comment by binarylogic** [comment]
@JeanMertz @FungusHumungus is this still relevant given the latest changes?

**Comment by JeanMertz** [comment]
This works since the recent refactor.
