### ISSUE TITLE
The Remap `encode_base64` should pad by default

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#6012]
The `encode_base64` Remap function should default to padding, which is [inline with the Rust default](https://docs.rs/base64/0.13.0/base64/constant.STANDARD.html). Is there any particular reason we deviated?

**Comment by lucperkins** [comment]
@binarylogic There wasn't any particular reasoning behind that choice in hindsight. I'll switch it up.


hence the decision: https://docs.rs/base64/0.13.0/base64/fn.encode.html.

**Comment by lucperkins** [comment]
@binarylogic Padding is currently enabled by default:

* [Docs](https://github.com/timberio/vector/blob/master/docs/reference/remap/encode_base64.cue#L16)
* [Code](https://github.com/timberio/vector/blob/master/lib/remap-functions/src/encode_base64.rs#L44-L58)
* [Test](https://github.com/timberio/vector/blob/master/lib/remap-functions/src/encode_base64.rs#L129-L137)

**Comment by binarylogic** [comment]
Ah, sounds good. I must have misread the default.
