### ISSUE TITLE
The `parse_syslog` Remap function should error on parsing failures

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#6015]
In the `parse_syslog` Remap function docs it says:

> If parsing fails, Vector will include the entire Syslog line in the message field.

This deviates from other functions in that it can never fail. It should return an error if the string cannot be parsed.

**Comment by FungusHumungus** [comment]
This requires some changes to `syslog_loose` since it is there that it returns the whole message if it can't parse.

**Comment by binarylogic** [comment]
Sounds good. Thankfully we know the syslog_loose author 😄 . Perhaps that could be configurable?
