### ISSUE TITLE
CI failures due to missing Rust toolchain

### ISSUE THREAD

**Issue by lucperkins** [timberio/vector#6018]
[This](https://github.com/timberio/vector/pull/6010/checks?check_run_id=1692121297) CI run alerted me to a recently introduced issue. It looks the `scripts/environment/prepare.sh` script wrongly assumes the presence of rustup in the CI environment. A fix for this will be necessary to get the `master` build back to green.

**Comment by jszwedko** [comment]
Taking a look at this now.

**Comment by jszwedko** [comment]
This turned out to be an issue with stale userdata for the runners where it was still installing the Github Actions runner as root instead of ubuntu. I've replaced the runners.

Thanks for reporting @lucperkins !
