### ISSUE TITLE
Deprecate rawConfig from the Helm charts

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#6042]
We've been using the `rawConfig` in the Helm charts at 0.11 release, and at 0.12 we'll have an alternative of passing the values inline (https://github.com/timberio/vector/pull/5673).
We need to deprecate the `rawConfig` settings a couple of releases down the line - around 0.14 or 0.15.

**Comment by jamtur01** [comment]
Can we add a warning of some kind now?

**Comment by MOZGIII** [comment]
Yes, we'll be updating the docs for this one, and we'll have to add a note that the `rawConfig` is deprecated. I'll crate a separate issue for this.

**Comment by jszwedko** [comment]
@spencergilbert this is done as of #7671  , yes?

**Comment by spencergilbert** [comment]
I figured it would be done when the feature was actually removed?

**Comment by jszwedko** [comment]
I think this ticket just covers deprecation. We can remove it at some point in the future. Ideally we'd keep it around until 1.0 unless there is a substantial maintenance burden.

**Comment by spencergilbert** [comment]
There's sort of... I think. Might be a call to make when I actually make the planned cutover. Can close for now.
