### ISSUE TITLE
Rework buffering of metrics in sinks

### ISSUE THREAD

**Issue by bruceg** [timberio/vector#6045]
While discussing #5916 and #5917, we also discussed the possibilities of an individual metric (as identified by name and namespace) changing type. We reached the conclusion that this was both a rare and nonsensical situation.

This has implications for metrics buffering, both for the batch buffer and for `prometheus_exporter` which buffers internally. First, including the metric type in key comparisons (ie `MetricEntry`) is incorrect behavior, since it is not reasonable to have different metrics with the same name. Secondly, if a metric ever does change type (say, a backwards-incompatible software upgrade to a metric source), the only sensible thing to do is to discard all buffered data for that metric and start over.

We should review the batch buffer and all our metric sinks to ensure they match the above two behavior requirements.

**Comment by binarylogic** [comment]
Just notinh, @tustvold has agreed to take a stab at this, so I've unassigned @bruceg. @brucge and @tustvold it would be prudent to agree on an approach here to ensure your contribution gets merged. Thank you for your help!

**Comment by binarylogic** [comment]
@tustvold, @bruceg is taking #6050, and it appears that will simplify the work here. We will prioritize that work. Let us know if you'd like to wait for that to complete.

**Comment by tustvold** [comment]
I agree this ticket should wait for #6050 as that will determine the path forward on this one.

**Comment by tustvold** [comment]
I see the linked issue has been closed, I'll look to pick this one up, time permitting, in the next couple of days

**Comment by bruceg** [comment]
@tustvold Note that I have almost completed my work on #5589 which does a simplification of the metrics batch buffer. It does not specifically address this issue, so this work is still needed on it, but work on that component will have conflicts. You can see my work so far on this branch https://github.com/timberio/vector/tree/metrics-batch-buffer-fixes

I look forward to seeing what you come up with here.

**Comment by tustvold** [comment]
I'm afraid my availability has not been what I'd hoped it would be. I'll try to find some time to look into this, but I can't promise that it will be this week. If this is blocking something, I'd be perfectly happy for someone else to pick it up, but otherwise I can take a look as and when I have a chance.

I suspect as @bruceg says, the outcome of #6251 will have significant bearing on the implementation of this, and so it may be worth holding off until that work has been merged regardless.
