### ISSUE TITLE
`ipv6_to_ipv4` remap function returns an ipv6 address when given an ipv4 address.

### ISSUE THREAD

**Issue by FungusHumungus** [timberio/vector#6046]
As per this repl session, if you give this function an ipv4 address, it will convert it to ipv6:

```
$ ipv6_to_ipv4("127.0.0.1")
"::ffff:127.0.0.1"
```

It should just pass it through:

```
$ ipv6_to_ipv4("127.0.0.1")
"127.0.0.1"
```

**Comment by jamtur01** [comment]
@FungusHumungus I don't think this is a 0.12 blocker but happy to be corrected.

**Comment by FungusHumungus** [comment]
> @FungusHumungus I don't think this is a 0.12 blocker but happy to be corrected.

I will be merging this in a minute..
