### ISSUE TITLE
Add `redact` function to VRL

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#6049]
**EDIT** I've updated this issue to be for readding the `redact` function to VRL. See below for thoughts on function signature.

There was some discussion in https://github.com/timberio/vector/pull/5297, the PR adding `redact` to remap, about what the signature should be. We ended up merging it to keep things moving, but with a note to reconsider before it was released with 0.12.0 (https://github.com/timberio/vector/pull/5297#issuecomment-738635362).

So far, the suggestions are:

```
redact(.input, filters = ["pattern"], patterns = ["hello"]) # 1 (current)
redact(.input, filters = [/hello/]) # 2
redact(.input, filters = [ { type = "pattern", patterns = [ "\b{3}", "\b{6}" ] } , "credit_card" ]) # 3
```

My feeling about the current signature is that it makes `patterns` a special case where there is another argument, `patterns`, that is only used if `filters` contains `patterns`. If we end up adding patterns in the future that also have parameters, this function signature will get a bit confusing.

The second option, makes `filters` take either an enum like `credit_card` or a regular expression. In this approach, there would be no `pattern` filter, just regexes specified directly in `filters`.

The third option, I think, is most flexible in that it allows for future filters that have parameters to be added. I realize we want to try to avoid adding any additional filters that have parameters, but I also get the feeling we'll run into cases in the future where this is the case and this approach future proofs for this.

My preference is to combine both options 2 and 3, allowing both types of specifying patterns. This has the advantage of letting users use the concise format when desired, but still allows for passing maps as filters in the future should we have additional filters that would benefit from configuration.

We could opt to punt this conversation until after 0.12.0, but if we can quickly come to consensus, I think it'd be nice to make this change before we release to avoid needing to deprecate behavior later.

cc/ @FungusHumungus @JeanMertz @binarylogic

**Comment by JeanMertz** [comment]
See also: https://github.com/datanymizer/datanymizer

**Comment by jszwedko** [comment]
@binarylogic Just FYI I updated this issue to represent adding `redact` to VRL given we didn't release it in 0.12 and I couldn't find another issue for it.

**Comment by jszwedko** [comment]
I was able to spend a chunk of time on this today.

I think it'll take me another couple of days to get it into a PR'able state so I figured I'd outline my intended path here for any early comments before I commit more time to this approach.

I pursed my suggested approach above, that is: allow for filters to be specified in one of three ways:

1. A simple regex: `redact(.input, filters: [r"hello"])`. This would replace any matches in the text.
2. A named pattern: `redact(.input, filters: ["credit_card"])`. This would replace any matches using a credit card filter.
3. An object with a type key and any arguments: `redact(.input, filters: [ { type =  "pattern", patterns = [ r"\b{3}", r"\b{6}" ] } ])`. This would allow specification of filters that require additional arguments.

Additionally, I am implementing it in a way that will automatically recurse through objects or arrays that are passed. That is, you could call it with simply `.` like: `redact(., ["credit_card"])` and it will recurse through all of the values, replacing with the filter.

For now, I've opted to just implement one redactor, but this function could be expanded to allow additional redactors. I think this would something like `redact(.input, filters: [ { type =  "pattern", patterns = [ r"\b{3}", r"\b{6}" ], redactor = "SOME_REDACTOR" } ], redactor: "FULL"))` where, if `redactor` is given with the `filter`, it is used, otherwise the `redactor` given at the top-level is used. This allows some flexibility in redacting different filters differently, for example showing the last 4 for the credit card filter.

I think, in the future, we will probably add a simple "redact all the things" function that just "does the right thing" and runs a suite of redaction filters, but I think this `redact` function will still be useful for users that want more control.

Open questions:

* Do we want to allow dynamic values for the `filters` argument here? We could evaluate them at compile time if we only allow users to use literals there and not variables or paths. I'm leaning towards this, at least for now, to avoid runtime errors.

**Comment by StephenWakely** [comment]
I think `redact` is a pretty important function that could have severe consequences if something goes wrong, so I would lean towards as much safety as possible. 

I agree that only allowing literals would be a a good idea - not only for the compile time checks, but also if we allow the redact function to depend on incoming data there is a much wider scope for things to go wrong and that error not being discovered for several months until the user is hacked and leaks their entire credit card database.

**Comment by pablosichert** [comment]
From the three options I agree that the third one definitely has the best ergonomics and flexibility.

Some questions:
- Could you elaborate what use the attribute `type = "pattern"` serves in your example `redact(.input, filters: [ { type = "pattern", patterns = [ r"\b{3}", r"\b{6}" ] } ])`? Wouldn't `redact(.input, filters: [ { patterns = [ r"\b{3}", r"\b{6}" ] } ])` be sufficient, or do you want to require the `type` attribute to unambiguously discriminate between all future filters? If we would be able to infer the filter from the options that would improve usability a lot, in my opinion.
- You mentioned that some of the predefined filters might be customized in the future. Could you sketch out how a customized version of `redact(.input, filters: ["credit_card"])` would look like?

I like the proposed iteration and fallback redactor a lot 👍

**Comment by jszwedko** [comment]
Thanks for for the thoughts!

> do you want to require the type attribute to unambiguously discriminate between all future filters

Yeah, I saw thinking the `type` field would discriminate. In this particular example, `patterns` is unambiguous, but I could see adding additional filters where their options might share the same config name.

> You mentioned that some of the predefined filters might be customized in the future. Could you sketch out how a customized version of redact(.input, filters: ["credit_card"]) would look like?

I think it'd look like `filters: [ { "type": "credit_card", "some_option": "some_value" } ]`. That example probably isn't great as I don't think the `credit_card` filter will have any additional options in practice. It could be used to specify a custom redactor though: filters: [ { "type": "credit_card", "redactor": "LAST_FOUR" } ]` to mask all but the last 4 characters.
