### ISSUE TITLE
Split metric data into key + value

### ISSUE THREAD

**Issue by bruceg** [timberio/vector#6050]
The data model for `struct Metric` combines data that is used as a key or metadata with data used as the value of the metric into a single flat structure. When these metrics are aggregated into buffers, this requires the introduction of a wrapper to effect comparisons and hashing, as well as requiring complex and inefficient update cycles when combining metrics.

We should investigate dividing the metric type into metadata and value, and refactor the metric type accordingly to allow for splitting it for use in maps or sets. The biggest question in my mind is which fields belong in which part? I think `name`, `namespace`, and `tags` are metadata, and `timestamp`, `kind`, and `value` are the value bits, but would like confirmation. Technically, the type of the metric should be unique on the `name` and `namespace` alone (ref #6045), but aggregation requires including the `tags` with the key.

**Comment by tustvold** [comment]
This is indeed a tricky one, and one I perhaps didn't appreciate the complexity of when I brought it up.

I believe the below to be correct, the list is notably incomplete but I think should be a representative sample. The distinction between requires and expects is the former fails on write whereas the latter would require an impractical level of effort to query correctly

* Prometheus - requires a single type per `name` and `namespace` per scrape
* Datadog - expects name and namespace to have a single type
* Cloudwatch - expects name and namespace to have a single type
* InfluxDB v1.* - expects name and namespace to have a single type per field, limited _support_ [for multiple types](https://docs.influxdata.com/influxdb/v1.8/troubleshooting/frequently-asked-questions/#how-does-influxdb-handle-field-type-discrepancies-across-shards)
* InfluxDB v2.* - requires name and namespace to have a unique type per field

InfluxDB theoretically would allow mixing types for a given name and namespace provided they were encoded to different fields, but this would be a rather unusual schema design. It is also conceivable that a metric sink could be added, such as S3, that could support multiple types provided they were encoded to distinct partitions (i.e. subsets of the `tags`). In both cases, however, I feel that whilst technically possible they aren't a particularly compelling nor common use-cases.

I therefore think vector would be justified in considering `name`, `namespace` (and possibly `tags`) as the key identifying a unique type of data as suggested by this ticket. In places where new data is of a different type/shape I think it would be valid for it to log a warning event and drop the old value.

As for whether `tags` should be included in this key the distinction is less clear cut to me. If the division is into two it's definitely more key than value. However, there are definitely cases where it is desirable to key just by `name` and `namespace`, for example in the prometheus exporter, or any component that seeks to enforce consistent typing across a `name` and `namespace`.

Might it make sense therefore to define something like this, and therefore avoid picking one or the other:

```
struct MetricName {
    namespace: String,
    name: String,
}

struct MetricSeries {
    name: MetricName,
    tags: BTreeMap<String, String>
}

struct MetricData {
    timestamp: Option<DateTime<Utc>>
    kind: MetricKind,
    value: MetricValue,
}

struct Metric {
    series: MetricSeries,
    data: MetricData,
}
```

Provided the sort order for `MetricSeries` gives the tags the lowest precedence it should be possible to efficiently convert a sorted collection keyed by `MetricSeries` to one grouped by `MetricName`. Similarly the nesting of `MetricName` within `MetricSeries` would allow efficient by reference lookups in a collection keyed by `MetricName` when given a `MetricSeries`.

**Comment by bruceg** [comment]
Thanks, @tustvold, that's a very helpful break down!
