### ISSUE TITLE
Allow use of _ to throwaway values in remap

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#6054]
I believe this is already planned, but I didn't see an issue for it, so opening here :slightly_smiling_face: 

It'd be useful to be able to use `_` to ignore return values you don't care about in remap. The most common example is ignoring errors that you don't need to handle.

For example:
```
json, _ = parse_json(.message)
```

If we don't care about handling errors from `parse_json`. This is the same as:

```
json = parse_json(.message) ?? null
```

We could go further and allow the Rust idiom of throwing away values simply starting with an `_` like:

```
json, _err = parse_json(.message)
```

To allow naming the values we are tossing.

**Comment by JeanMertz** [comment]
> We could go further and allow the Rust idiom of throwing away values simply starting with an `_` like:
> 
> ```
> json, _err = parse_json(.message)
> ```
> 
> To allow naming the values we are tossing.

In Rust, there's actually a difference between `_` and `_err`, in that the former _immediately drops the value assigned to the variable_, whereas in the latter case the value isn't dropped until `_err` goes out of scope.

> throwing away values simply starting with an `_`

To clarify, are you suggesting actually having some kind of special behaviour for these variables, or just allowing variables to begin with `_` as an idiomatic way to represent "values I don't care about"?

Either way, we should start with `_` as planned, we can create a follow-up PR to allow `_err`.

**Comment by jszwedko** [comment]
Thanks for the thoughts @JeanMertz ! I agree, let's just start with `_`.
