### ISSUE TITLE
add support for error codes in VRL

### ISSUE THREAD

**Issue by JeanMertz** [timberio/vector#6070]
Once #6023 is merged, we'll have improved diagnostic messages, such as:

```
error: unneeded error assignment
  ┌─ :2:1
  │
2 │ foo, err = 5;
  │ ^^^^^^^^   - because this expression cannot fail
  │ │          
  │ this error assignment is unneeded
  │
  = hint: assign to "foo", without assigning to "err"
  = see language documentation at: https://vector.dev
```

The library we use for this ([codespan](https://github.com/brendanzab/codespan)) also supports assigning error codes to each diagnostic message.

We should leverage this to link to specific documentation sections on our website that inform users with a more elaborate explanation why they got the error, and how they can resolve it (including a representative example).

Additionally, we should update our function trait such that function errors also return the error code, such that all errors generated by functions can be documented as well.

**Comment by binarylogic** [comment]
@JeanMertz this is done, right?
