### ISSUE TITLE
Consider treating every set of labels as a separate metric for vector_internal_metrics_cardinality_total

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#6074]
`vector_internal_metrics_cardinality_total` currently reflects the count of metrics by name only; however, in sinks like AWS CloudWatch Metrics and InfluxDB store each unique set of labels for a metric as a separate time series.

I propose updating `vector_internal_metrics_cardinality_total` to count each set of labels as a separate metric.

For example:

```
vector_processed_events_total{component_kind="source",component_name="in",component_type="stdin"} 1 1610727343146
vector_processed_events_total{component_kind="sink",component_name="out",component_type="http"} 6993 1610727345146
```

Would count as two metrics instead of one.

Issue was broken off of https://github.com/timberio/vector/issues/5746

**Comment by MOZGIII** [comment]
I don't think it's correct - the idea behind the *implementation* of the `vector_internal_metrics_cardinality_total` is that we estimate the size of data in the registry. It counts keys, but each key is both the metric name and it's labels set - meaning that the example above should already be counted as two metrics.

Of course, if the implementation behaves differently from the idea I described above - it's a bug, and we should fix it.

**Comment by jszwedko** [comment]
@MOZGIII interesting, maybe this should be a bug then. Right now, it seems to only count the metric names, ignoring the labels.

**Comment by MOZGIII** [comment]
Indeed.

Let's take a look at the implementation, maybe we'll figure this out.

We do the counter bumping in a non-standard way, here:
https://github.com/timberio/vector/blob/b7e1234ab24aa33c155f093ed7a8e0f3a08c934b/src/metrics.rs#L69-L77

The recorder is the using this function in the registration callback:
https://github.com/timberio/vector/blob/b7e1234ab24aa33c155f093ed7a8e0f3a08c934b/src/metrics.rs#L79-L134


The registration callback is called when a new metrics value has to be initialized (`FnMut() -> MetricValue`, where `MetricValue` is a holder for the underlying atomics/histograms - a counter/gauge/etc). So, effectively, if there is a metric value - the cardinality counter should've been bumped.

I don't get how it can be 2 when it's initialized with 1 (to account for self).

Maybe I'm passing it by value somewhere where I should pass it by ref?

**Comment by jszwedko** [comment]
Sorry, it is counting itself too; I truncated the example in my description. I'll try to get a full example.

**Comment by jszwedko** [comment]
Actually.... you seem to be right! I think I was again seeing an issue because of the stale prometheus output. I see that the value is actually incremented for each label set when I added some trace statements. I'll close this out.
