### ISSUE TITLE
Improve postgresql_metrics sink: tests, reconnect, wildcard in filters

### ISSUE THREAD

**Issue by fanatid** [timberio/vector#6086]
Copied from initial PR: https://github.com/timberio/vector/pull/5391#issuecomment-761196457

- [x] add more asserts to tests: https://github.com/timberio/vector/pull/5391#discussion_r558581861 -- Implemented in https://github.com/timberio/vector/pull/6110
- [ ] refactor client reconnect (remove `expect`): https://github.com/timberio/vector/pull/5391#discussion_r558510249 -- Implemented in https://github.com/timberio/vector/pull/6415
- [x] support wildcard in filters: https://github.com/timberio/vector/pull/5391#discussion_r558499855 - Implemented in https://github.com/timberio/vector/pull/6118
- [x] edit CODEOWNERS -- Implemented in https://github.com/timberio/vector/pull/6110
- [x] check version on connect, error if not supported (use `SHOW server_version` / `SHOW server_version_num`) -- Implemented in https://github.com/timberio/vector/pull/6110
- [x] Do not connect on `SourceConfig::build` https://github.com/timberio/vector/pull/6110#issuecomment-762313502 -- Implemented in https://github.com/timberio/vector/pull/6246

**Comment by juchiast** [comment]
Btw, I think it is more correct to use `tokio::select!` for shutdown, instead of just `take_until`.
https://github.com/timberio/vector/blob/4dfbdea470693aa419febc1397c492fc688964b6/src/sources/postgresql_metrics.rs#L154-L169

If something causes `source.collect()` to hang, vector won't shutdown on time.

**Comment by fanatid** [comment]
I checked [take_until](https://docs.rs/futures-util/0.3.12/src/futures_util/stream/stream/take_until.rs.html#126-147) code and do not see any problem :thinking: can you explain why `tokio::select!` is more correct?

**Comment by juchiast** [comment]
Hi, here's what I see: if the code is awaiting in `join_all(...).await` and `shutdown` signal is called, it won't shutdown immediately, instead it has to wait till the next `interval.next().await` to shutdown.

**Comment by juchiast** [comment]
With tokio::select wrapping the whole wihle block, it should shutdown immediately.

**Comment by fanatid** [comment]
`interval.next().await` will return result immideatelly when `shutdown` signal is called because this signal will resolve this future.
`shutdown` signal poll in `take_until`: https://docs.rs/futures-util/0.3.12/src/futures_util/stream/stream/take_until.rs.html#129-130

**Comment by juchiast** [comment]
Yes, but if the code is not awaiting at `interval.next().await`, but somewhere else inside the loop, I don't think take_until would have an effect?

**Comment by fanatid** [comment]
Yes, that's correct, `take_until` will not have any effect for anything in `while` loop. But I think this is correct and we should wait metrics collecting before shutdown?

**Comment by juchiast** [comment]
> But I think this is correct and we should wait metrics collecting before shutdown?

This might be true, I'm not sure about this.

**Comment by jszwedko** [comment]
It's worth noting that we use this interval pattern in a few places:

```
src/sources/host_metrics.rs
149:        while interval.next().await.is_some() {

src/sources/generator.rs
124:                interval.next().await;

src/sources/nginx_metrics/mod.rs
109:            while interval.next().await.is_some() {

src/sources/internal_metrics.rs
64:    while interval.next().await.is_some() {

src/sources/postgresql_metrics.rs
156:            while interval.next().await.is_some() {

src/sources/aws_ecs_metrics/mod.rs
132:    while interval.next().await.is_some() {

src/sources/mongodb_metrics/mod.rs
137:            while interval.next().await.is_some() {
```

So we should update them all if we prefer `tokio::select`.

I think @juchiast's point is valid that, if it is blocking inside of the loop, it won't shutdown until the action inside has finished; however, I think this might also be acceptable behavior: letting it finish the last scrape before shutting down; limited by the shutdown grace period. I also think it'd be fine to abort the current scrape though :smile:
