### ISSUE TITLE
Installation instructions for Debian don't work on Debian 10 "buster"

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#614]
Debian 10 "buster" is released: https://www.debian.org/News/2019/20190706

However, the installation instructions for Vector don't work on it as there are no packages for it in the repository.

**Comment by binarylogic** [comment]
Weird, we'll test and see what's going on.

**Comment by binarylogic** [comment]
@a-rodin we should be set, it'll be available on the next release which should be this week. Thanks for letting us know.
