### ISSUE TITLE
Update helm docs `extra_field_selector` to reference correct type and usage

### ISSUE THREAD

**Issue by eeyun** [timberio/vector#6140]
As seen in #6130 our documentation around the extra_field_selector is unclear. 

Currently the documenation shows this field as supporting an array which is incorrect. This field is a kubernetes-formatted filter predicate string. 

When we update the examples we should include a multiform example like

`metadata.namespace!=other,metadata.name=mypod,metadata`

**Comment by MOZGIII** [comment]
The `extra_label_selector` might share the same issues, would be good to take a check it as well if we're at it.
