### ISSUE TITLE
Extract Adaptive Concurrency module into a separated crate

### ISSUE THREAD

**Issue by calavera** [timberio/vector#6151]
Hi 👋 

I found your [Adaptive Concurrency](https://github.com/timberio/vector/tree/master/src/sinks/util/adaptive_concurrency) module super interesting, and I was wondering if it could be extracted into a separated crate. I'd like to use it with a Tower based client that I help maintaining, but it's not trivial to use it as it currently is.

Sorry if I mislabeled this issue, I didn't know where to put it. Feel free to close this issue if you're not very interested in doing that refactor, I can always find another way around it.

**Comment by binarylogic** [comment]
Hey @calavera, no problem. @bruceg built the feature so I'll let him chime in on the amount of work required for this.
