### ISSUE TITLE
`prometheus_scrape` does not tag metrics with timestamp

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#6156]
### Vector Version

```
vector 0.12.0 (g50d375d x86_64-unknown-linux-gnu 2021-01-19)
```

### Vector Configuration File

```toml
[sources.cadvisor]
type = "prometheus_scrape"
endpoints = ["http://localhost:9100/metrics"]
scrapte_interval_secs = 5

[sinks.stdout]
type = "console"
inputs = ["cadvisor"]
encoding.codec = "json"
```

### Debug Output

https://gist.github.com/jszwedko/13fe219eeffc1f395b02744b3eec8a2c

### Expected Behavior

Vector should tag metrics with their timestamp: the timestamp included in the prometheus metrics endpoint, if it exists, otherwise the scrape time.

### Actual Behavior

The metrics have no timestamp.

For example:

```
{"name":"node_cooling_device_max_state","tags":{"name":"1","type":"Processor"},"kind":"absolute","gauge":{"value":0.0}}
```

### Example Data

I used the Prometheus node_exporter for testing.

**Comment by vpedosyuk** [comment]
Hi, does `prometheus_remote_write` sink still works correctly for `prometheus_scrape`source  -> `prometheus_remote_write` sink flow? As far as I understand the Prometheus remote write protocol needs a timestamp for each sample.

**Comment by zephyrinzephyr** [comment]
Have the same issue.

**Comment by jszwedko** [comment]
@vpedosyuk 

> Hi, does `prometheus_remote_write` sink still work correctly for `prometheus_scrape`source -> `prometheus_remote_write` sink flow? As far as I understand the Prometheus remote write protocol needs a timestamp for each sample.

It should work. It is just that the timestamp won't be the timestamp of the original metric but, rather, the timestamp when the sink processes the message.

**Comment by vpedosyuk** [comment]
@jszwedko
Unfortunately, it doesn't seem to be working. I installed Prometheus Node Exporter and VictoriaMetrics with default settings on Ubuntu 18.04. Then I installed Vector 0.12.1 and run it with the following config:
```toml
[sources.exporter]
  # General
  type = "prometheus_scrape"
  endpoints = ["http://localhost:9100/metrics"]
  scrape_interval_secs = 15

[sinks.victoriametrics]
  type = "prometheus_remote_write"
  inputs = ["exporter"]
  endpoint = "http://localhost:8428/api/v1/write"
  healthcheck.enabled = true
```

And here's VictoriaMetrics logs:
```
Mar 26 17:00:41 vagrant victoriametrics.victoriametrics[7110]: 2021-03-26T17:00:41.510Z        info        /root/parts/build/build/app/vmselect/promql/rollup_result_cache.go:169        rollupResult cache has been cleared
Mar 26 17:00:51 vagrant victoriametrics.victoriametrics[7110]: 2021-03-26T17:00:51.455Z        error        /root/parts/build/build/lib/storage/storage.go:1346        warn occurred during rows addition: cannot insert row with too small timestamp 0 outside the retention; minimum allowed timestamp is 1614099651000; probably you need updating -retentionPeriod command-line flag; metricName: node_netstat_Icmp_InSrcQuenchs{}
Mar 26 17:00:51 vagrant victoriametrics.victoriametrics[7110]: 2021-03-26T17:00:51.512Z        info        /root/parts/build/build/app/vmselect/promql/rollup_result_cache.go:169        rollupResult cache has been cleared
Mar 26 17:01:06 vagrant victoriametrics.victoriametrics[7110]: 2021-03-26T17:01:06.460Z        error        /root/parts/build/build/lib/storage/storage.go:1346        warn occurred during rows addition: cannot insert row with too small timestamp 0 outside the retention; minimum allowed timestamp is 1614099666000; probably you need updating -retentionPeriod command-line flag; metricName: node_memory_VmallocChunk{}
... (similar events) ...
```
it reports a zero timestamp so no data get ingested into the VictoriaMetrics TSDB

**Comment by jszwedko** [comment]
Ah @vpedosyuk , I think you hit https://github.com/timberio/vector/issues/6814 . The fixes for that are in master now. We hope to release them early next week. You can try the latest nightly build now if you want to see if it resolves your issue.

**Comment by jszwedko** [comment]
@bruceg this was fixed by https://github.com/timberio/vector/pull/6827, no?

**Comment by bruceg** [comment]
@jszwedko I believe so, yes.

**Comment by jszwedko** [comment]
👍 I'll close this out then.
