### ISSUE TITLE
Verify lua script compilation as part of config validation

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#616]
This would be a nice a touch for the `lua` transform, to ensure the lua script passed is syntactically valid. We can't verify execution because we won't know the structure of the event, but we can verify syntax.

There's a chance we already do this. If that's the case, please close.

**Comment by a-rodin** [comment]
I'm thinking about slightly changing the execution model, so that the script source would be used to create a transformer function at start and then execute it for each transform. This should both improve the performance and do the parsing at the step when the transform is initialized.

**Comment by a-rodin** [comment]
I'm thinking about slightly changing the execution model, so that the script source would be used to create a transformer function at start and then execute it for each transform. This should both improve the performance and do the parsing at the step when the transform is initialized.
