### ISSUE TITLE
Make sure we are actually using jemalloc as the global allocator for benches

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#6163]
We think we are currently running the benches with the default allocator. We should bench with jemalloc given that is the most common allocator we distribute vector with.

**Comment by MOZGIII** [comment]
Validated this. So, the rule about `global_allocator` is that it can be set 0 times, or no more than once per compile target (i.e. binary) and all of its dependencies.

I propose that we move the `global_allocator` from `vector` crate to `vector-global-alloc` subcrate, to enable its use in standalone benches. We can then also easily add more allocators, and switch between them via feature-flags - sharing the implementation with both vector itself (along with everything that depends on `vector` - tests, benches) and standalone benches.

**Comment by MOZGIII** [comment]
The benches have to use `jemalloc` feature, which might be missing currently.

After discussing with @jszwedko we decided to proceed with the proposed refactor - I'll conduct it as part of this task, as it's small and fairly isolated.
