### ISSUE TITLE
Disallow root assignment in Remap

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#6171]
After working on the Remap documentation, I'm realizing that the default behavior of overriding objects during assignment is going to be troublesome.

## Problem

For example, this will be a common mistake:

```js
. = parse_apache_log!(.message)
```

On the surface, this does not appear problematic, but in practice, it is. This will override the context set by sources, such as the `host` and `timestamp` keys.

And I realize the user can do this:

```js
. = merge(., parse_apache_log!(.message))
```

But that is not obvious.

## Proposals

Given that I cannot think of a use case where a user would want to wipe out their entire event (including the `timestamp` key), I propose that we raise an compile-time error on root object assignment:

```js
. = parse_apache_log!(.message) # raises compile-time error
```

Instead, the user can do any of the following:

```js
. = merge(., parse_apache_log!(.message))
. += parse_apache_log!(.message) # += is being proposed coming soon
.apache = parse_apache_log!(.message)
```

**Comment by jszwedko** [comment]
:+1: I agree that doing `. = some_parse_function()` will be a common foot gun, but users may actually want that functionality in some cases. It might be useful to describe how we could still support that as well for when they do want to drop any context and _just_ have the parsed metadata.

**Comment by jszwedko** [comment]
Noting example from @spencergilbert where it would be nice to be able to overwrite: `. = compact!(.)`.

I wonder if we could just make it a warning?

**Comment by lukesteensen** [comment]
> This will override the context set by sources, such as the `host` and `timestamp` keys.

It's worth considering what this problem would look like once we've moved those keys into metadata. Maybe this is just another reason to do that?

**Comment by JeanMertz** [comment]
> It's worth considering what this problem would look like once we've moved those keys into metadata. Maybe this is just another reason to do that?

I agree with @lukesteensen comment here. I don't think "just" disallowing root assignment is the solution here, as there are edge-cases where this is actually desired. In fact, I'd argue that there's a not insignificant likelihood that if you are doing `. = parse_json(.message)`, your parsed JSON object will contain a timestamp field already, and it might even contain a host field that is more correct than the one Vector added (e.g. if Vector runs in a separate container/host).

I see four ways forward (other than the one proposed in by this issue):

1. As Luke proposed, delegate host/timestamp keys to the metadata level.
2. As Jesse proposed, add a warning but don't disallow this.
3. Update the `remap` transform to add a "do not remove these fields" option, which would allow you to _change_ those fields, but not remove them (technically, Vector would add the original values back, if it notices the fields have been removed).
4. Keep as is.

**Comment by JeanMertz** [comment]
I'm going to close this, as this won't be in 0.12, and I don't think we should add it in a later version either. Also, @FungusHumungus is working on support for `. |= { "foo": "bar" }`, which will merge the rhs object into the existing one.
