### ISSUE TITLE
Rename Remap map to object

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#6174]
We should switch the "map" Remap terminology to "object" since it aligns better with JSON terminology.

@JeanMertz @FungusHumungus is there internal renaming that needs to happen here? Or is this entirely docs focused?

**Comment by lucperkins** [comment]
If we decide that this is the way to go, I would definitely argue for changing the underlying names (`Value::Object`, `Kind::Object`, etc.), as map types are all over the codebase and any discrepancy between how we publicly present this type and what it looks like to engineers is going to get unwieldy.

One potential snag here is that we do frequently make references to "event objects" in the VRL docs. We'd need to be more careful about our usage if we go down this path (no pun intended).

**Comment by FungusHumungus** [comment]
Agree with @lucperkins, there's a lot of code that refers to the type as Map, which technically doesn't need changing, but it would be very confusing if we didn't. 

There's probably some places in the parser, particularly with error reporting that would need changing as these messages would be displayed to the user.

My main concern would be that the Log Event throughout Vector refers to the type as Map. There's no reason why Remap could call them `Object` and Vector could use `Map`, but it's an extra cognitive overhead I'd rather avoid - so I'd suggest we would want to change it through out Vector. There may be some repercussions there that I am not currently familiar with..

**Comment by binarylogic** [comment]
Sounds good. For the record, I am indifferent. @JeanMertz and I talked about this earlier today. If it's a lot of work I do not think it's worth it.

**Comment by FungusHumungus** [comment]
It's quite possible an IDE like CLion could automate a lot of the renaming.
