### ISSUE TITLE
Helm: vector-aggregator - NodePort (LoadBalancer, etc.)

### ISSUE THREAD

**Issue by dzirg44** [timberio/vector#6175]
### Current Vector Version

```
nightly-2021-01-20-debian image
```

### Use-cases
I am thinking about using different service types in this chart, but it seems that we cannot easily add this feature, because in 
https://github.com/timberio/vector/blob/9fa2ca2f0b11453e004edeca97a917500abbf159/distribution/helm/vector-aggregator/templates/_helpers.tpl#L14
we have `to yaml`
and of course it cannot check our structure.

### Attempted Solutions
maybe something like
```yaml
service:
  # Additional ports to expose.
  type: "ClusterIP"
```

### Proposal
i created a possible way to resolve it.
https://github.com/dzirg44/vector/blob/service-type/distribution/helm/vector-aggregator/templates/_helpers.tpl
or we can just use `toYaml` without checking ports in helpers.

### References

an example of using it is
https://github.com/kubernetes/ingress-nginx/blob/master/charts/ingress-nginx/templates/controller-service.yaml

**Comment by dzirg44** [comment]
I added a temporary  solution for headless service, it doesn't look good, but I cannot make up something better.

**Comment by MOZGIII** [comment]
Related: https://github.com/timberio/vector/pull/6020

**Comment by langecode** [comment]
@dzirg44 yes, this was exactly what we solved with the changes fed back through PR #6020 which @MOZGIII mention. Turns out that if your try to pin your node port using the `nodePort` property the headless services (of type `ClusterIP` fails) so it gets a bit more complicated.

**Comment by dzirg44** [comment]
Thank you !
In this case i think we can close this issue.

**Comment by langecode** [comment]
Hmm, maybe your proposal is more clean modelling the properties than just doing the `toYaml` as it is not that easy to remove the `nodePort` property on the yaml level - that get a bit ugly.

**Comment by MOZGIII** [comment]
Thanks for this proposal! I've finally got some time to review, and we definitely want to do it like this! Great job!
