### ISSUE TITLE
Investigate the impact of the compatibility wrapper for metrics going to/from Lua v2

### ISSUE THREAD

**Issue by bruceg** [timberio/vector#6191]
In #6034, the data for distributions, histograms, and summaries was changed from a pair of (equal length) vectors into a single vector of data pairs. The Lua script interface (v2) already exposed this data, both going to scripts and coming back in, as pairs of arrays. To maintain compatibility, the above change splits the vector when sending metrics to scripts, and rejoins pairs of arrays coming from scripts. This raises two questions:

1. While rewriting the vector data in Rust has a performance cost, it is likely that handling data as a single array of very small arrays (tables) also has a cost in Lua compared to a pair of larger tables. Which combination provides the highest performance for Lua scripts? Is this difference significant?
2. Which shape of this data is more suitable for Lua idioms? Are there any advantages to keeping it the same as it is now, or would changing it (to match the internal representation) improve usability?

Blocks #6186

**Comment by binarylogic** [comment]
> Which shape of this data is more suitable for Lua idioms? Are there any advantages to keeping it the same as it is now, or would changing it (to match the internal representation) improve usability?

This is the most important question. I do not think the Lua data model has to match Vector’s internal representation exactly. We should do exactly as you described, agree on a data model that makes the most sense for Lua and treat that like a public contract. We should not be breaking the `lua` transform every time  we make a data model change. At the same time, we need to balance performance implications. My assumption is that the performance is no different since we have to convert our data to a Lua structure regardless of the approach we take.

**Comment by bruceg** [comment]
As I am not well versed in Lua idioms, I cannot answer the second question well. I have, however, run a simple benchmark on the second question and the results are dramatic. Changing the representation into a single array of small tables introduces significant overhead for non-trivial sized distributions (the data shape of the other two aggregates are effectively equivalent, so timing should be the same). At one element, the time is effectively the same before and after, however by 10 elements I showed a 56% time increase (36% throughput reduction), and at 100 elements it's 188% more time (65% throughput reduction). This was run on my home system, which will have had some minor noise between runs, but I can't imagine it looking any less terrible on a more controlled system.

I think that, unless there is very compelling coding idiom related reasons to prefer the revised schema, this points strongly to us keeping the existing public data format for Lua.

**Comment by binarylogic** [comment]
Agree, a performance drop of that magnitude is prohibitive. If it is correct we should stick with the current structure since it does not suffer from performance.
