### ISSUE TITLE
Add additional language runtime comparison benches

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#6198]
Broken off from https://github.com/timberio/vector/pull/6063#issuecomment-761834980

> @jszwedko it would be nice to see comparisons for:
>
>    Baseline (ex: adding fields)
>    Parsing JSON
>    Parsing Syslog
>    Redaction (something simple like credit cards or emails)
>    Combined (parsing, reshaping, redacting)
>
> That would be a strong showing for comparison across all runtimes. Is this doable?

Should be picked up after #6063 is merged.

**Comment by jszwedko** [comment]
@lucperkins I assigned this one to you since you expressed interest in https://github.com/timberio/vector/pull/6063#issuecomment-762424546 but feel free to ping me or @MOZGIII if you need any assistance with them.

**Comment by lucperkins** [comment]
With #6387 merged I think we're in a pretty good place with this. I'll close this.
