### ISSUE TITLE
Kinesis healthcheck failing on streams that exist

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#622]
The kinesis healthcheck use [`ListStreams`](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_ListStreams.html) api action to detect if the stream exists. The healthcheck will set the `ExclusiveStartStreamName` to the name of the stream _exactly_. Sometimes AWS only accepts the exact string minus the last character but won't accept the full stream name. This is odd since localstack does not reproduce this behavior.

**Comment by thethomp** [comment]
Is there any update on this? I'm also receiving this error from the Mac version of vector (version 0.8.2)
`Apr 08 11:23:15.884 ERROR vector::topology::builder: Healthcheck: Failed Reason: Stream returned does not contain any streams that match miket-test`

I only have 1 stream and it is very clearly called miket-test.

Is there a known workaround? Maybe I can disable the health check or something? As far as I can tell this sink is unusable while this is broken.

Thanks!

**Comment by thethomp** [comment]
> Is there any update on this? I'm also receiving this error from the Mac version of vector (version 0.8.2)
> `Apr 08 11:23:15.884 ERROR vector::topology::builder: Healthcheck: Failed Reason: Stream returned does not contain any streams that match miket-test`
> 
> I only have 1 stream and it is very clearly called miket-test.
> 
> Is there a known workaround? Maybe I can disable the health check or something? As far as I can tell this sink is unusable while this is broken.
> 
> Thanks!

My mistake - the agent was continuing to work after the error line I have quoted here, so this is not a blocking issue. 

The log line was so long after the error it wasn't displaying on my screen correctly (different issue related to batch size), so I assumed the agent was failing. I was able to suppress the error message by adding the `healthcheck = false` in my config (though, again, it will work even if you don't have this).
