### ISSUE TITLE
Component links are broken on master.vector.dev

### ISSUE THREAD

**Issue by juchiast** [timberio/vector#6235]
Hi,
Links in this page do not work: https://master.vector.dev/components/

For example, link to Docker source is: https://master.vector.dev/docs/reference/sources/docker_logs/
But it should be https://master.vector.dev/docs/reference/configuration/sources/docker_logs/ 

I was automatically redirected when I open it in a new tab or refreshing the page, but there was no redirecting when opening on the same tab.

**Comment by binarylogic** [comment]
Thanks!
