### ISSUE TITLE
Root objects are not considered valid paths in Remap

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#6266]
You cannot pass the root object to functions that support working with objects:

```
Configuration error. error=Transform "compact": remap error: parser error:  --> 1:16
  |
1 |   . = compact(.)␊
  |                ^---
  |
  = expected path_segment
```

**Comment by JeanMertz** [comment]
Curious. This seems to be a regression...

I added a test in the new parser, and this is working as expected, so should be solved as soon as that PR lands.
