### ISSUE TITLE
Rate limited logging audit

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#628]
Now that #494 is merged, we can implement rate limited logs throughout Vector. This is _very_ helpful for logging in the hot path and providing valuable insight for users. @LucioFranco performed extensive benchmarking on this and it appears to have a negligible impact on performance. As such, the recommendations here are based on that information.

**tracing**:

- [x] Update to new released versions of tracing https://github.com/timberio/vector/issues/929

**docs**

- [ ] ~~Write docs on how to trouble shoot sinks, sources, and transforms using tracing.~~ (#970)

**sources**

- [x] `file` source - line exceeds `max_line_bytes` - once every 30 seconds
- [x] `stdin` source - line exceeds `max_line_bytes` - once every 30 seconds
- [x] `syslog` source - parsing failed - https://github.com/timberio/vector/pull/885#issuecomment-532385824 - once every 10 seconds
- [x] `tcp` source - line exceeds `max_line_bytes` - once every 30 seconds

**transforms**

- [x] `grok_parser` transform - parsing missed - once every 30 seconds
- [x] `json_parser` transform - parsing failed - once every 30 seconds
- [x] `log_to_metric` transform - `increment_by_value` parsing failed - once every 30 seconds
- [x] `lua` transform - any script / compile error - once every 30 seconds
- [x] `regex_parser` transform - parsing missed - once every 30 seconds
- [x] `regex_parser` transform - field coercion failed - once every 30 seconds
- [x] `tokenizer` transform - field coercion failed - once every 30 seconds

**sinks**

- [x] `aws_cloudwatch_logs` sink - event interpolation (partition keys) missing event field - once every 30 seconds
- [x] `aws_cloudwatch_logs` sink - event interpolation (partition keys) bad type (can't coerce to string) - once every 30 seconds
- [x] `aws_kinesis` sink - event interpolation (partition keys) missing event field - once every 30 seconds
- [x] `aws_s3` sink - event interpolation (partition keys) missing event field - once every 30 seconds
- [x] `elasticsearch` sink - event interpolation (partition keys) missing event field - once every 30 seconds
- [x] `http` sink - event interpolation (partition keys) missing event field - once every 30 seconds

**buffers**

This section is a little tricky, because I want to continually notify users if there is continuous back pressure.

- [x] Log when a buffer becomes full - once every 10 seconds.
- [x] Log when an event is dropped (shed) - once every 10 seconds.

**Comment by binarylogic** [comment]
@lukesteensen I just need you to review the details of this issue, specifically the 30 second rates I've chosen. Once you've made the changes necessary please:

1. Unassign yourself
2. Remove the `meta: needs review` label

**Comment by lukesteensen** [comment]
These all seem good to me. Anywhere we could potentially be logging some kind of error on every incoming event in a tight loop is somewhere we should probably be limiting.

I had initially imagined the period would be something like 5 seconds, but I've come around to 30. If it's going to be that long though, I think we may want to add a "limiting the output of log message X for the next 30 seconds" message that the rate-limiting implementation outputs _before_ dropping messages. The existing implementation of outputing a summary _after_ the period assumed a smaller period during which a user could wonder where their logs went.

**Comment by binarylogic** [comment]
@LucioFranco what's the status on this? The ones that are checked are in master, right? I don't see any PRs referencing this issue.

**Comment by LucioFranco** [comment]
@binarylogic changes are being worked on locally. Most of the work is done but there is a blocking issue right now upgrading `tracing` that I am working on. These new changes in upgrading `tracing` will really improve the logging UX so I think it's very worth it.

I am hoping to get a draft PR up soon with the rate limit changes then will update it with the new tracing version.

**Comment by LucioFranco** [comment]
I've opened a related issue around adding docs https://github.com/timberio/vector/issues/970

**Comment by binarylogic** [comment]
I'm reopening this since items were checked that were not actually completed. For example, the `grok_parser` is not rate limiting it's messages:

https://github.com/timberio/vector/blob/58d6e976cf81f2175e7fd6cc6d4c85c9e2bc88eb/src/transforms/grok_parser.rs#L106

I'd prefer not to check all of these myself, that was the purpose of creating the checklist in the first place.
