### ISSUE TITLE
Improving the type definitions of Remap Arrays 

### ISSUE THREAD

**Issue by FungusHumungus** [timberio/vector#6297]
When #6182 lands Remap will be able to track the type definitions of maps, so the following code will typecheck:

```coffeescript
.x = parse_regex!(.foo, /(?P<thing>a.b)/)
sha3(.x.thing) # <- We know here that .x.thing is a string
```

At present we aren't able to carry this type checking over into Arrays, so for example, this code will not typecheck:

```coffeescript
.x = parse_regex_all!(.foo /(?P<thing>a.b)/)
sha3(.x[3].thing) <- .x[3] may not exist, so is fallible.
```

There are scenarios where this type checking can be carried over into Arrays.

## 1. If an index is set directly:

```coffeescript
.x[3] = { "thing": "bar" }

sha3(.x[3].thing) <- We know .x[3].thing is a string
```

## 2. If the length of an array is checked

```coffeescript
.x = parse_regex_all!(.foo /(?P<thing>a.b)/)
if length(.x) > 3 {
  sha3(.x[3].thing) <- We now know that .x[3] exists, and that .thing is a string.
}
```

## 3. Within a for loop

As per #5875, within a for loop, we know every row in that array will exists, so the inner type definitions can be carried over.

```coffeescript
.x = parse_regex_all!(.foo /(?P<thing>a.b)/)
for row in .x {
  sha3(row.thing) <- We row exists, so row.thing is a string.
}
```

----

**1.** is certainly doable. However, it is questionable how useful that would be. I can't imagine Remap being used like this that often. 

**2.** I feel could be part of a greater exercise. For example, there is a usecase far carrying type checking information `if` blocks as a result of functions such as `is_string`, `is_null`. The logic could get quite complex, but we could probably implement some unification rules that could handle this. 

**3.** is probably the most common use case that will get the most use if we do decide to integrate for loops.

There is nothing preventing us from implementing all 3!

**Comment by binarylogic** [comment]
@FungusHumungus, good call, but why can't we type check this?

```
.x = parse_regex_all!(.foo /(?P<thing>a.b)/)
sha3(.x[3].thing) <- .x[3] may not exist, so is fallible.
```

Wouldn't that function raise and abort if the parsing fails? And wouldn't we know what was returned from the `parse_regex_all!` call?

**Comment by FungusHumungus** [comment]
> Wouldn't that function raise and abort if the parsing fails?

The compiler wouldn't allow this as you are not handling the error. You need to use `sha3!` (note trailing `!`) to indicate you are happy for it to abort.

**Comment by binarylogic** [comment]
Right, I was talking specifically about this line:

```
.x = parse_regex_all!(.foo /(?P<thing>a.b)/)
```

We know that `x[0]` and `x[1]` will always be strings, right? But anything beyond that is optional.

**Comment by FungusHumungus** [comment]
> We know that `x[0]` and `x[1]` will always be strings, right?

Oh, I see. No, `parse_regex_all` returns an empty array if it doesn't match anything. I see that is inconsistent with the docs.

We could change that function to error and set the type information for the 0th index of the array, but anything beyond that will be unknown - so I'm not sure if we gain too much by doing that. We really need a more generic solution.

**Comment by JeanMertz** [comment]
I believe this can be closed, as we added array type definition checking in #6353
