### ISSUE TITLE
Other platform has higher version number

### ISSUE THREAD

**Issue by stappersg** [timberio/vector#6302]
### Vector Version

`0.11.0` and `0.11.1`

### Vector Configuration File

Not applicable

### Debug Output

```
$ curl --silent https://repositories.timber.io/public/vector/deb/ubuntu/dists/bionic/main/binary-amd64/Packages \
 | grep -e ^Package -e ^Version -e ^Filename
Package: vector
Version: 0.11.0
Filename: pool/any-version/main/v/ve/vector-0.11.0-amd64.deb
Package: vector
Version: 0.11.1
Filename: pool/any-version/main/v/ve/vector-0.11.1-musl-amd64.deb
```

### Expected Behavior

A `glibc` server gets `glibc` executables installed.

### Actual Behavior

A `glibc` server got `musl` executable installed.

### Example Data

Not applicable

### Additional Context

It is inherent to `apt` to install the package with the highest version number got from `Packages`.

### References

I think this is somehow related to #5833 where also switch happened from a working `...musl.x86_64.rpm`  to a somewhat broken `...musl.x86_64.rpm` version.

**Comment by jamtur01** [comment]
This was a packaging error in 0.11.1 and I thought had been fixed. I've replaced the package with what should be the right package.

**Comment by jamtur01** [comment]
Please re-open if the issue continues.
