### ISSUE TITLE
The Metric update interfaces may fail silently

### ISSUE THREAD

**Issue by bruceg** [timberio/vector#6329]
Ref: https://github.com/timberio/vector/pull/6251#discussion_r568797744

Several methods in `Metric`, `MetricData`, and `MetricValue` (specifically `add`, `subtract`, and `update`) conditionally update `self` if certain conditions hold. No indication is given to the caller that the update actually happens though, which could lead to data corruption.

Most of the callers to these functions ensure that the conditions are met before calling, effectively doubling the conditional evaluation.

These methods should be modified to return a status indicator that they completed the update (either `bool` or `Result<(), ???>`), and then sweep all the callers to ensure they handle this properly.

**Comment by jszwedko** [comment]
Copying comment over from https://github.com/timberio/vector/pull/6738#pullrequestreview-610778033

> I'm ok with this going in as-is, but I do see that the fields on MetricData are pub so I'm slightly concerned that there might be other code paths that might modify value directly instead of calling update(). Do you think it'd be feasible to mark them as not-pub that way any modifications would come through MetricData which could enforce the rules around the timestamp?

Solving this issue seems like a good time to also isolate mutations to ensure that only `MetricData` makes them.

**Comment by bruceg** [comment]
I did some preliminary work on this, but it looks like much of this would be simplified by #6045. So I am going to defer on this until that is is completed.
