### ISSUE TITLE
Sinks: elasticsearch self signed TSL certificates

### ISSUE THREAD

**Issue by dzirg44** [timberio/vector#6334]
### Current Vector Version

```
version="0.11.1" git_version="v0.11.1" released="Thu, 17 Dec 2020 17:09:17 +0000" arch="x86_64"
```

### Use-cases
Some people use self signed certificates in Elasticsearch clusters (like me) and don't wan't to generate it for vector(keeping it a little bit unsafe in private networks is fine ). Also, opendistro(elasticsearch fork) uses self-signed certificates by default.

### Attempted Solutions
Don't have options to do it.
I tried to solve it with 
```json
      "tls" : {
        "verify_hostname" : false
      },
but unsuccessfully 
```

### Proposal
maybe something like
```
insecure: true
```

**Comment by jszwedko** [comment]
Thanks for the report @dzirg44 ! I'd actually opened https://github.com/timberio/vector/issues/6132 to add this feature so I'll close this in-lieu of that one, but it's helpful to know others would find it useful.
