### ISSUE TITLE
It should be possible to specify a key with which to rate limit Internal logs.

### ISSUE THREAD

**Issue by FungusHumungus** [timberio/vector#6342]
Currently rate limiting is keyed on the Call Site (the line and module in the Rust source code) of where the log message (`trace!`, `debug!`, `info!`, `warn!` or `error!`) call was made.

The result is that, for example in a Remap script, if the script makes two different log calls those are being called from the same source code location. So the rate limiting kicks in and the second log message is not be displayed. This blocks #6324 from being useful. It also impacts #6242 since only one template rendering errors will be reported with the rest being rate limited. It would likely be useful to report all these.

It would be really useful to specify an alternate key with some non-static data that could be used by the rate limiter to determine which messages are unique. Something like:

```coffeescript
warn!(message = %msg, internal_log_rate_secs = 30, internal_log_rate_key = remap_source_line)
```

This does not seem to be a straighforward change to make.

Looking at the code where the rate limiting is being applied ([here](https://github.com/timberio/vector/blob/master/lib/tracing-limit/src/lib.rs#L106-L156)) the function does not have access to the log message data, only it's metadata (effectively the callsite and the fields in the message). So as it stands it can't simply look up an alternative key in the log message to use as an index.

Some insight from @jszwedko on how we may approach this:

>  I think it will need some substantial refactoring to allow for different limit buckets for the same callsite. You are right that the event doesn't seem to be available in #enabled. It seems like most of the logic would need to be moved into on_event, which does have access. I almost wonder if this rate limited logging would be better modeled as a tracing Subscriber rather than a tracing Layer
>
> Like create something that just wraps the FmtSubscriber we currently have wired up with the layer in front
However the callsite is accessible via the Event in Layer#on_event so I think most of the logic could be moved there where it lazily inserts into the events store

**Comment by juchiast** [comment]
#6242 also requires rate-limit to be keyed by component's name.

**Comment by jszwedko** [comment]
I mentioned this to @MOZGIII and he had an idea to wrap the macro calls with spans that inject different labels. I believe these should be available in `#enabled` and could be used to further scope the rate limit.

**Comment by FungusHumungus** [comment]
> I mentioned this to @MOZGIII and he had an idea to wrap where we call the macros (`warn!`, etc.) with spans that inject different labels

The spans have to be `'static`, which I think, unfortunately means this idea wouldn't work. I can't think of a way in Remap that we could make the lifetimes of each call > `'static.`

**Comment by jszwedko** [comment]
Noting I had some discussion in the tracing discord channel: https://discord.com/channels/500028886025895936/627649734592561152/813481896977235998

The consensus there was to model it as a `Subscriber` given it doesn't seem possible to achieve what we want as a `Layer`, currently.

**Comment by juchiast** [comment]
Just an idea, can we add some metadata to the event, e.g. `rate_limited = true`, and use this to filter the event on the subscriber? This way we don't have to move everything to subscriber.

**Comment by jszwedko** [comment]
@juchiast 👍 that would work for identifying callsites that are rate limited in `Layer#enabled`. We could probably just reuse the existing `internal_log_rate_secs`; however, we still need access to the event field values to do the rate limiting. It seems like that logic will have to vile in a `Subscriber`. I definitely welcome other ideas though.

**Comment by juchiast** [comment]
@jszwedko I meant the logic could be in `on_event` of Layer, but now I see that it only receives an _immutable_ reference to event. So that probably won't work.

**Comment by jszwedko** [comment]
@juchiast ah gotcha. Yeah, the fact that `on_event` just receives a reference seems to be limiting us from using a `Layer` to implement this.
