### ISSUE TITLE
Sinks: elasticsearch extended index configuration

### ISSUE THREAD

**Issue by dzirg44** [timberio/vector#6343]
### Current Vector Version

```bash
version="0.11.1" git_version="v0.11.1" released="Thu, 17 Dec 2020 17:09:17 +0000" arch="x86_64"
```

### Use-cases
as you know, modern ES (or their forks) solutions provide **Index Management**
Elasticsearch https://www.elastic.co/guide/en/elasticsearch/reference/current/index-lifecycle-management.html
or 
AWS https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/ism.html
that's why I propose to implement such functionality in Vector.

### Attempted Solutions
Manual index creating \\ updating

### Proposal
maybe something like this
```json
{
  "sinks" : {
    "my_sink_id" : {
      "compression" : "none",
      "endpoint" : "http://10.24.32.122:9000",
      "healthcheck" : {
        "enabled" : true
      },
      "index" : {
        "name": "example",
        "settings": [],
        "aliases": []
      },
      "inputs" : [
        "my-source-or-transform-id"
      ],
      "pipeline" : "pipeline-name",
      "type" : "elasticsearch"
    }
  }
}
```

**Comment by jszwedko** [comment]
Closing this in-lieu of https://github.com/timberio/vector/issues/7745. Please feel free to add any additional thoughts there.
