### ISSUE TITLE
Create benchmark framework for transforms

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#6346]
This benchmark framework will make it easier to add additional benchmarks without boilerplate and standardize the way we benchmark them.

Probably put these utilities in separate crate in `lib/`.

To validate:

* Implement for 3 transforms

**Comment by jszwedko** [comment]
Closing this given @blt has already started the work in https://github.com/timberio/vector/issues/7777

**Comment by blt** [comment]
@jszwedko and I just so happened to do that work for three transforms. Fun.
