### ISSUE TITLE
Support more formats for timestamp literals

### ISSUE THREAD

**Issue by JeanMertz** [timberio/vector#6360]
see: https://github.com/timberio/vector/pull/6353#discussion_r570788666

Currently, only RFC3339 timestamps are allowed as timestamp literals in VRL, but we should add the same logic we have in Vector, which "guesses" the timestamp format based on a number of pre-defined formats.

**Comment by JeanMertz** [comment]
I'm closing this, until there's a concrete need for it.

**Comment by jszwedko** [comment]
👍 I think `to_timestamp()` does this.
