### ISSUE TITLE
Instructions for installing the apt package repo is not helpful for sysadmins

### ISSUE THREAD

**Issue by abeluck** [timberio/vector#6366]
This is in reference to this docs page:

https://vector.dev/docs/setup/installation/package-managers/apt/

### Current Vector Version

n/a

### Use-cases

I am an ops engineer configuring systems to be installed with vector. I have a well established procedure for depending on new apt repositories that involves automation (ansible) and approval+verification. I cannot simply `curl | bash` scripts on every box I want to install vector.

### Attempted Solutions
I had to download the script file and figure out WTF was going on to end up with a simple string:

```
deb https://repositories.timber.io/public/vector/deb/debian buster main
deb-src https://repositories.timber.io/public/vector/deb/debian buster main
```

### Proposal

I understand you are trying to reduce friction for the "let me just try this thing dangint!" use case. And that's 100% cool. But for real production installations we aren't going to exec your script as part of our provisioning pipeline. Please just include the information we need in the documentation (underneath the simple script, and by all means and in a smaller less prominent font), and trust that we know what we're doing.

```
Install our repository manually:

    deb https://repositories.timber.io/public/vector/deb/debian <codename> main
    deb-src https://repositories.timber.io/public/vector/deb/debian <codename> main

We support debian versions: buster, FOO, and BAR

Our PGP signing key is at  https://repositories.timber.io/public/vector/gpg.3543DB2D0A2BC4B8.key
```

**Comment by jamtur01** [comment]
You don't need to download the script - you can find complete instructions here: https://cloudsmith.io/~timber/repos/vector/setup/#formats-deb. I'll see if we can add a link somewhere.

**Comment by abeluck** [comment]
That's brilliant! Would definitely love to see that linked from the main docs.
