### ISSUE TITLE
more localized error reporting

### ISSUE THREAD

**Issue by JeanMertz** [timberio/vector#6372]
Given this program:

```rust
[1 == 1, 0 == 1, "true" == true, 5 / .foo == 0]
```

You get this error:

```
error: unhandled error
  ┌─ :2:1
  │
2 │ [1 == 1, 0 == 1, "true" == true, 5 / .foo == 0]
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  │ │
  │ expression can result in runtime error
  │ handle the error case to ensure runtime success
  │
  = see error handling documentation at: https://vector.dev/docs/reference/vrl/
  = see language documentation at: https://vector.dev/docs/reference/vrl/
```

The problem is that a division operation is always fallible, so you have to handle any potential error `5 / .foo` might produce.

We already produce localized error messages for other expressions, e.g.:

```
error: non-boolean predicate
  ┌─ :2:4
  │
2 │ if "nope" {
  │    ^^^^^^
  │    │
  │    this predicate must resolve to a boolean
  │    instead it resolves to "string"
  │
  = hint: coerce the value using one of the coercion functions
  = see language documentation at: https://vector.dev/docs/reference/vrl/
```

We should apply the same strategy to all our expression types, such that we no longer have to show the above generic "this root expression can fail" diagnostic.

For starters, we should do so for logical/arithmetic operations.

**Comment by binarylogic** [comment]
@JeanMertz is this still relevant given the latest changes?

**Comment by JeanMertz** [comment]
It is, although a few of them have been resolved. I'll circle back to this in a bit to see which ones are still pending.

**Comment by JeanMertz** [comment]
cc #7204

**Comment by JeanMertz** [comment]
Closing this, as we're tracking this in the above-mentioned issue.
