### ISSUE TITLE
Loki Dynamic label syntax does not work

### ISSUE THREAD

**Issue by shawel** [timberio/vector#6381]
I tried the following from documentation

```
labels.* = "vector"
labels.* = "{{ event_field }}"
```

I get the following message 
`Configuration error. error=unexpected character found: *`

Is it possible?

**Comment by juchiast** [comment]
Hi @shawel, the `*` is meant as a wildcard to fill up, you would actually do things such as
```
labels.host = "{{ hostname }}"
```

**Comment by shawel** [comment]
I see thanks @juchiast  I probably read it wrong then.   Is there a way do dynamically assign the label keys. Because I don't know the name of the keys before hand.

**Comment by juchiast** [comment]
Unfortunately, it is not possible to set dynamic label keys at the moment. How many possible label keys do you have? It might be possible to use the swimlanes transform to route logs based on their labels to different loki sinks.

**Comment by shawel** [comment]
Ok thanks @juchiast. I was hoping it would work. Swimlane is interesting but still it is static.  For our use case labels are arbitrate and data driven.
