### ISSUE TITLE
WASM parse_json benchmark doesn't match the other parse_json implementations

### ISSUE THREAD

**Issue by bruceg** [timberio/vector#6397]
The `benchmark_parse_json` function is intended to run the same operation in multiple scripting. https://github.com/timberio/vector/blob/9c0bdd3adca4fe9243cca75053c66d10ed2fe9eb/benches/languages.rs#L78

The source code for the WASM transform is missing a step: https://github.com/timberio/vector/blob/9c0bdd3adca4fe9243cca75053c66d10ed2fe9eb/tests/data/wasm/parse_json/src/lib.rs#L26

The JSON decoding it is doing in that function is the base decode needed by all WASM transforms to get at the event data. A second JSON decode is necessary, after accessing the `message` field of the source (log) event.

**Comment by lucperkins** [comment]
Yeah, that's my bad. I pretty much have very little idea what I'm doing with Wasm. Should be easy enough to address.
