### ISSUE TITLE
Update `kafka` sink `key_field` to just `key`

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#640]
Similar to #358, this issue aims to use event interpolation for a new `key` option. Currently, the `kafka` sink includes  `key_field` option which is no longer necessary if we support event field interpolation in a `key` field.

- [ ] Add new `key` option that accepts a string supporting event interpolation (`{{field}}`)
- [ ] I'm unsure if Kafka requires a key when writing events. If it does, then the default should be a random string, otherwise this field should be required.

**Comment by binarylogic** [comment]
@lukesteensen I need you to review this issue. Please adjust and then remove the `meta: needs review` label. I would like @LucioFranco to do this issue since he is doing other related issues with event interpolation.

**Comment by lukesteensen** [comment]
I actually don't think it makes sense to use interpolation here, for much the same reason as #358. Simply specifying which field to use as the key seems much more expected.

**Comment by binarylogic** [comment]
Cool, I think I agree with you now. Happy to close this and see if customers ask for it.
