### ISSUE TITLE
Update metrics crate and investigate performance degradation

### ISSUE THREAD

**Issue by fanatid** [timberio/vector#6412]
Our benchmarks show that upgrading the `metrics` crate to `v0.13.1` causes a significant performance regression (>20%). We need to investigate and resolve the performance problem before we can upgrade.

PR with an attempted update: https://github.com/timberio/vector/pull/6217#issuecomment-766435360

**Comment by pablosichert** [comment]
For https://github.com/timberio/vector/pull/5874 we need to upgrade to `metrics 0.14.x` to be able to use `layers::AbsoluteLayer` from `metrics-util 0.6.1`. That's a good opportunity to look if the version bump fixed some of the regressions.

**Comment by jszwedko** [comment]
Closing this since we did go through with the upgrade in https://github.com/timberio/vector/pull/7031
