### ISSUE TITLE
Enable top-level arrays in json_parser when target_field is set

### ISSUE THREAD

**Issue by lukesteensen** [timberio/vector#6417]
Right now the `json_parser` transform only adds data to the event if the parsed JSON is an object (i.e. not an array or a scalar). This makes sense because it defaults to adding the fields of the object to the top level of the event, so without fields it's not obvious where on the event to put things (since it can't itself be an array).

When the user has configured `target_field`, however, that issue goes away. It's quite easy to insert an array/number/whatever at a specific field on an event, and it seems like we should do that.

_Edit:_

After more discussion on [discord](https://discord.com/channels/742820443487993987/746070591097798688/809125965514276905), the idea came up that top-level arrays could simply be parsed into multiple output events. There may be some odd edge cases, we'd need to clone the original event, etc, but it's worth considering.

**Comment by valerypetrov** [comment]
I think that some people are looking forward to switching from logstash to vector. And it will be convenient to make homogeneous behavior in JSON processing. Per logstash JSON parser:
`This codec may be used to decode (via inputs) and encode (via outputs) full JSON messages. If the data being sent is a JSON array at its root multiple events will be created (one per element).`

https://www.elastic.co/guide/en/logstash/current/plugins-codecs-json.html

So it means that the following message:
`[{"message":"ololo","log_format":"json", "component_type":"lol", "id":"5758436633ba46d7a57db483c4049835", "log_type":"main"},{"message":"lalala","log_format":"json", "component_type":"pas", "id":"fsdfsdtgy65756457db483c4049835", "log_type":"main"}]`
It Will parsed and divided into 2 different events:
`
{"message":"ololo","log_format":"json", "component_type":"lol", "id":"5758436633ba46d7a57db483c4049835", "log_type":"main"}

{"message":"lalala","log_format":"json", "component_type":"pas", "id":"fsdfsdtgy65756457db483c4049835", "log_type":"main"}
`

**Comment by zsherman** [comment]
Closing in favor of remap usage in #6988
