### ISSUE TITLE
Use incremental histograms internally

### ISSUE THREAD

**Issue by bruceg** [timberio/vector#6456]
Some internal metrics output data as histograms. These histograms are represented as absolute metrics internally. This means that each time they are added to, the memory requirements for the data grow. For some metrics, such as network response times which are measured in nanoseconds, there is not even a good way of reducing the number of samples, as each new response time will likely be different than all previous ones.

We should investigate and implement the use of incremental metrics for internal histograms, as they will only accumulate the minimum values required for the new values unless the target sink requires absolute histograms.

Ref #6423

**Comment by binarylogic** [comment]
I'm curious how we could prevent this going forward? It seems like introducing absolute histograms would be an easy foot-gun.

**Comment by bruceg** [comment]
This likely requires a change to the `metrics` crate. All we are doing with those values is calling `histogram!`, so it would mean a change to that macro.

**Comment by pablosichert** [comment]
I think this was supposed to be closed automatically with https://github.com/timberio/vector/pull/7014.

Please reopen if that doesn't apply @blt.
