### ISSUE TITLE
New `explode` transform

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#6459]
This is a simple transform that'll explode an event into multiple events. Currently, this is only achieved through the `lua` transform which is non-ideal given Lua's performance implications. It is worth discussing alternative solutions to this function, but I like the single-purpose nature of a new transform.

**Comment by jszwedko** [comment]
I think this is related to #6330

**Comment by zsherman** [comment]
@jszwedko is this still relevant or does https://github.com/timberio/vector/issues/6330 cover the use case?

**Comment by jszwedko** [comment]
@zsherman Ah, yes, this is covered by https://github.com/timberio/vector/issues/6330 . I'll close this.
