### ISSUE TITLE
loki sink healthchecks fail for Grafana Cloud hosted Loki

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#6463]
Reported by user in discord: https://discord.com/channels/742820443487993987/746070604192415834/811356602220150844

It looks like Grafana Cloud doesn't expose the `/health` endpoint that`vector` expects:

```
ERROR vector::topology::builder: msg="Healthcheck: Failed Reason." error=A non-successful status returned: 404 Not Found component_kind="sink" component_type="loki" component_name="loki"
```

For example, see:

```
$ curl -I https://logs-prod-us-central1.grafana.net/ready
HTTP/2 404 
content-type: text/plain; charset=utf-8
x-content-type-options: nosniff
date: Tue, 16 Feb 2021 22:46:18 GMT
content-length: 19
via: 1.1 google
alt-svc: clear
```

It does return OK for top-level queries though:

```
$ curl -I https://logs-prod-us-central1.grafana.net/     
HTTP/2 200 
date: Tue, 16 Feb 2021 22:46:43 GMT
content-length: 2
content-type: text/plain; charset=utf-8
via: 1.1 google
alt-svc: clear
```

### Vector Version

```
vector 0.11.1 (v0.11.1 x86_64-unknown-linux-musl 2020-12-17)

```

Ref: Loki API https://grafana.com/docs/loki/latest/api/#get-ready

**Comment by med93600** [comment]
Same issue with Vector version 
vector 0.12.1 (v0.12.1 x86_64-unknown-linux-gnu 2021-03-12)

**Comment by jszwedko** [comment]
Moving out of the milestone, but we do have this work scheduled for this upcoming quarter.
