### ISSUE TITLE
kubernetes_logs container_id - logs cannot integrate with all context in Datadog without this

### ISSUE THREAD

**Issue by szibis** [timberio/vector#6466]
As Datadog relies on container_id in context merging we need to have that in Kubenretes_logs by default added to every logline to be properly parsed by Datadog and context appears in places where such logs come from this particular container.

![image](https://user-images.githubusercontent.com/329831/108179529-01ddfd00-7106-11eb-9bc0-94c56f03b7a2.png)

As the documentation says we got container_image and container_name but lack container_id. 
This is a crucial thing in any Datadog out-of-the-box integration.

https://vector.dev/docs/reference/sources/kubernetes_logs/
```
{
  "file" : "/var/log/pods/pod-namespace_pod-name_pod-uid/container/1.log",
  "kubernetes.container_image" : "busybox:1.30",
  "kubernetes.container_name" : "coredns",
  "kubernetes.pod_ip" : "192.168.1.1",
  "kubernetes.pod_ips" : "192.168.1.1",
  "kubernetes.pod_name" : "coredns-qwertyuiop-qwert",
  "kubernetes.pod_namespace" : "kube-system",
  "kubernetes.pod_node_name" : "minikube",
  "kubernetes.pod_uid" : "ba46d8c9-9541-4f6b-bbf9-d23b36f2f136",
  "message" : "53.126.150.246 - - [01/Oct/2020:11:25:58 -0400] \"GET /disintermediate HTTP/2.0\" 401 20308",
  "mylabel" : "myvalue",
  "source_type" : "kubernetes_logs",
  "stream" : "stdout",
  "timestamp" : "2020-10-10T17:07:36+00:00"
}
```

**Comment by szibis** [comment]
It is available in k8s API in container status - next to container_name and container_image id.

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#container-v1-core

If you don't have time for that now I can try to prepare #PR for that.

**Comment by zsherman** [comment]
thanks @szibis we'll take a look asap!
