### ISSUE TITLE
Revive VRL function changes

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#6476]
It appears that #6353 dropped changes like #6052. We should audit and revive any changes like this that were dropped.

**Comment by pablosichert** [comment]
Relevant PRs to be reviewed:

- [x] https://github.com/timberio/vector/pull/6293
- [x] https://github.com/timberio/vector/pull/6296
- [x] https://github.com/timberio/vector/pull/6335
- [ ] https://github.com/timberio/vector/pull/6310
- [ ] https://github.com/timberio/vector/pull/6313
- [ ] https://github.com/timberio/vector/pull/6314
- [ ] https://github.com/timberio/vector/pull/6325
- [ ] https://github.com/timberio/vector/pull/6422
- [ ] https://github.com/timberio/vector/pull/6446
- [ ] https://github.com/timberio/vector/pull/6462
- [ ] https://github.com/timberio/vector/pull/6468
- [ ] https://github.com/timberio/vector/pull/6471

**Comment by pablosichert** [comment]
I reviewed all of the PRs that have been merged between the opening of https://github.com/timberio/vector/pull/6353 and now.

Really weird that #6052 has been dropped, since that landed on Jan 19, but the first commit on https://github.com/timberio/vector/pull/6353 was on Feb 4.

**Comment by jszwedko** [comment]
It looks like the parent commit of the first commit on #6535 is https://github.com/timberio/vector/commit/7e5f6baa19cc616eab8b69e5be43c4c70990e1ff which is actually January 19th so that branch was likely branched from a stale `master`.

**Comment by jszwedko** [comment]
That might also mean you should expand the search window for possibly affected PRs?

**Comment by pablosichert** [comment]
Very good point @jszwedko! Will do.

**Comment by pablosichert** [comment]
Interesting, I remember exactly encountering and [fixing](https://github.com/timberio/vector/pull/6353/commits/be332938ac0c9636652b368fb4065c87b2b33450#diff-0423a4a9c41ec2e2ee51358842a7cfb78a73602d141c95f3c24d3a5635961927L135) it in passing: https://github.com/timberio/vector/pull/6229.

Which affirms your point 😄

**Comment by pablosichert** [comment]
Let's hope I caught all. For the huge pull request I did many probes of single changes.
