### ISSUE TITLE
Tutorial on null failed

### ISSUE THREAD

**Issue by marcobazzani** [timberio/vector#6500]
The tutorial on:

vector --config ./vector.toml

Here's what went wrong:

```

Feb 19 22:09:15.362  INFO vector::app: Log level is enabled. level="vector=info,codec=info,file_source=info,tower_limit=trace,rdkafka=info"
Feb 19 22:09:15.362  INFO vector::app: Loading configs. path=[("vector.toml", None)]
Feb 19 22:09:15.364 ERROR vector::cli: Configuration error. error=No sources defined in the config.
Feb 19 22:09:15.364 ERROR vector::cli: Configuration error. error=Input "my-source-or-transform-id" for sink "out" doesn't exist.
```

**Comment by jszwedko** [comment]
Hi @marcobazzani, thanks for reporting! Can you provide a link to the failing tutorial? It seems like you meant to in the issue, but it is empty.

**Comment by jszwedko** [comment]
Hi @marcobazzani . I'll close this since I'm not sure which tutorial you were trying, but definitely reopen if you are able to provide a link.
