### ISSUE TITLE
Delivering AWS Firehose events to vector

### ISSUE THREAD

**Issue by papovyr** [timberio/vector#6501]
Hi vector team,

I was trying to receive events from AWS kinesis firehose and deliver them to loki.
But i failed to receive logs from AWS Firehose

First idea was to configure kinesis firehose HTTP destination and point to vector which will have `sources.aws_kinesis_firehose` input. See config below

```
[sources.aws_kinesis_firehose]
type = "aws_kinesis_firehose"
address = "0.0.0.0:443"
region = "us-east-1"
tls.crt_file = "/etc/letsencrypt/live/node1.mydomain.info/fullchain.pem"
tls.key_file = "/etc/letsencrypt/live/node1.mydomain.info/privkey.pem"
tls.enabled = true

[sinks.out]
type = "console"
inputs = [ "aws_kinesis_firehose" ]
encoding.codec = "json"
```
I can confirm that SSL certificate is valid (as I saw some ssl error during configuration until i did it right).

In AWS Firehose Console I see following error to deliver logs 
```
Delivery to the endpoint was unsuccessful. See Troubleshooting HTTP Endpoints in the Firehose documentation for more information. Response received with status code. 400: {"requestId":"93a8fff3-fd4a-4af8-869e-d7cdf02a4324","timestamp":1613772495321,"errorMessage":"Could not parse records from incoming request 93a8fff3-fd4a-4af8-869e-d7cdf02a4324: invalid gzip header"}
```

In vector I see following logs
```
Feb 19 22:23:36.513 ERROR vector::internal_events::aws_kinesis_firehose: Error occurred while handling request. error="Could not parse records from incoming request 26d1b24d-124f-4eaf-a3c5-bd85682902a4: invalid gzip header" rate_limit_secs=10
Feb 19 22:23:47.320  INFO vector::internal_events::aws_kinesis_firehose: 1 "Handling AWS Kinesis Firehose request." events were rate limited. rate_limit_secs=5
Feb 19 22:23:47.321 ERROR vector::internal_events::aws_kinesis_firehose: 1 "Error occurred while handling request." events were rate limited. rate_limit_secs=5
Feb 19 22:24:02.459  INFO vector::internal_events::aws_kinesis_firehose: Handling AWS Kinesis Firehose request. request_id=94d203b2-c12c-4b08-8596-8d470ffac74b source_arn=arn:aws:firehose:us-east-1:4966114683XX:deliverystream/zzz rate_limit_secs=10
```
In AWS firehose console I tried to enable/disable GZIP but it didn't work 
I'm not sure why this is not working

As this failed 
Next idea was to configure Kinesis firehose splunk destination and use vector `sources.splunk_hec` to receive them
```
[sources.splunk_hec]
type = "splunk_hec"
  address = "0.0.0.0:443"
  token = "CF179AE4-3C99-45F5-A7CC-3284AA91CF67"
  tls.crt_file = "/etc/letsencrypt/live/node1.mydomain.info/fullchain.pem" # optional, no default
  tls.enabled = true # optional, default
  tls.key_file = "/etc/letsencrypt/live/node1.mydomain.info/privkey.pem" # optional, no default

[sinks.out]
type = "console"
inputs = [ "splunk_hec" ]
encoding.codec = "json"
``` 
In AWS Firehose console I see following logs 
```
The connection to Splunk timed out. This might be a transient error and the request will be retried. Kinesis Firehose backs up the data to Amazon S3 if all retries fail.
```
No logs in vector.

When i use curl it works 
```
curl -k "https://node1.mydomain.info/services/collector/event" \
    -H "Authorization: Splunk CF179AE4-3C99-45F5-A7CC-3284AA91CF67" \
    -d '{"event": "Hello, world!"}'
```

Problem might be that `sources.splunk_hec` does not supporting acknowledgment.

Any ideas on this ?
Am I Doing something wrong ?

**Comment by jszwedko** [comment]
Hi @papovyr !

Thanks for the report! For the gzip issue, are the events coming from Kinesis streams? If so, this might be the same issue as #5918 where vector's assumption that the data is coming across as a base64 gzip'd payload is invalid.

As for Splunk, it does look like Firehose might expect indexer acks to be enabled (https://docs.splunk.com/Documentation/AddOns/released/Firehose/RequestFirehose) though that error seems to indicate that Firehose wasn't even able to connect. I opened https://github.com/timberio/vector/issues/6534 to track adding support for indexer acknowledgements to the `splunk_hec` source.

**Comment by papovyr** [comment]
HI @jszwedko 
In other words this 
```
[sources.aws_kinesis_firehose]
type = "aws_kinesis_firehose"
```
is not usable yet ?

I will be happy to do any tweaks to deliver logs from firehose to vector.

I have Firehose and vector, and i generate test events in AWS console for Firehose.

Is there any way to deliver Firehose Logs to vector, What tweaks do i need to do ? Or its not usable yet ?

**Comment by jszwedko** [comment]
@papovyr It is useable, for example, to ingest logs from CloudWatch Logs via Firehose, but, if you are using Kinesis data streams then https://github.com/timberio/vector/issues/5918 will need to be addressed first. What is the source f the data going into Firehose?

**Comment by papovyr** [comment]
@jszwedko If I use lambda to transform data will it work ?
Still not clear how data needs to look like so vector will accept it ? 
Or it depends on datasource input type. I think that doesn't mater how events got to Firehose it should deliver them to HTTP destination (To vector). I guess its just data format ?

**Comment by jszwedko** [comment]
@papovyr Hmm, yeah, you could try using a lambda to transform the data. Vector expects the payloads to be base64 encoded, gzip'd, data. That is, the `data` portion of of each record in the Firehose HTTP request: https://docs.aws.amazon.com/firehose/latest/dev/httpdeliveryrequestresponse.html#requestformat

**Comment by papovyr** [comment]
@jamessewell thanks for response 

Data is already BASE64 Encoded when using Firehose with HTTP destination (As events i use generate simple data in AWS Firehose console). When I point to destination where my python code runs to print request_data I see following.

```
  "request_data": "b'{\"requestId\":\"1f495001-3bca-4ee3-963c-60464f6258d5\",\"timestamp\":1613699620804,\"records\":[{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiTkZMWCIsInNlY3RvciI6IlRFQ0hOT0xPR1kiLCJjaGFuZ2UiOi0wLjg5LCJwcmljZSI6OTEuNDN9\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiUVdFIiwic2VjdG9yIjoiVEVDSE5PTE9HWSIsImNoYW5nZSI6LTQuNDMsInByaWNlIjoyMjkuNDZ9\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiSU9QIiwic2VjdG9yIjoiVEVDSE5PTE9HWSIsImNoYW5nZSI6MS44OSwicHJpY2UiOjEzMS4zNn0=\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiUVhaIiwic2VjdG9yIjoiRklOQU5DSUFMIiwiY2hhbmdlIjotMC41OSwicHJpY2UiOjI1My41Mn0=\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiV1NCIiwic2VjdG9yIjoiRklOQU5DSUFMIiwiY2hhbmdlIjotMC4zMSwicHJpY2UiOjExNC4xNX0=\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiVEJWIiwic2VjdG9yIjoiSEVBTFRIQ0FSRSIsImNoYW5nZSI6Ni45OSwicHJpY2UiOjIwNS4zMn0=\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiV0ZDIiwic2VjdG9yIjoiRklOQU5DSUFMIiwiY2hhbmdlIjotMC4xMywicHJpY2UiOjQ1LjgzfQ==\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiQVNEIiwic2VjdG9yIjoiRklOQU5DSUFMIiwiY2hhbmdlIjotMC4yNiwicHJpY2UiOjYzLjcyfQ==\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiUkZWIiwic2VjdG9yIjoiRklOQU5DSUFMIiwiY2hhbmdlIjowLjgyLCJwcmljZSI6NTAuODV9\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiUExNIiwic2VjdG9yIjoiRklOQU5DSUFMIiwiY2hhbmdlIjowLjE4LCJwcmljZSI6MjAuMTh9\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiTkZTIiwic2VjdG9yIjoiRU5FUkdZIiwiY2hhbmdlIjotNC4yMywicHJpY2UiOjEyNC4xN30=\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiTkZTIiwic2VjdG9yIjoiRU5FUkdZIiwiY2hhbmdlIjotMC42NSwicHJpY2UiOjEyMy41Mn0=\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiTUpOIiwic2VjdG9yIjoiUkVUQUlMIiwiY2hhbmdlIjotOC43NSwicHJpY2UiOjE2Ni45NH0=\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiUExNIiwic2VjdG9yIjoiRklOQU5DSUFMIiwiY2hhbmdlIjotMC4wMSwicHJpY2UiOjIwfQ==\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiU0FDIiwic2VjdG9yIjoiRU5FUkdZIiwiY2hhbmdlIjoxLjkzLCJwcmljZSI6NTUuNzl9\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiV1NCIiwic2VjdG9yIjoiUkVUQUlMIiwiY2hhbmdlIjotMC4xMiwicHJpY2UiOjguMDR9\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiREZUIiwic2VjdG9yIjoiUkVUQUlMIiwiY2hhbmdlIjowLjczLCJwcmljZSI6ODguMTd9\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiTkZTIiwic2VjdG9yIjoiRU5FUkdZIiwiY2hhbmdlIjo4LjEsInByaWNlIjoxMjguNH0=\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiV0FTIiwic2VjdG9yIjoiUkVUQUlMIiwiY2hhbmdlIjowLjA2LCJwcmljZSI6MTEuMX0=\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiREVHIiwic2VjdG9yIjoiRU5FUkdZIiwiY2hhbmdlIjowLjQ1LCJwcmljZSI6Ni4wOX0=\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiTkZMWCIsInNlY3RvciI6IlRFQ0hOT0xPR1kiLCJjaGFuZ2UiOi0wLjE2LCJwcmljZSI6OTEuMjd9\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiSU9QIiwic2VjdG9yIjoiVEVDSE5PTE9HWSIsImNoYW5nZSI6MC4wMiwicHJpY2UiOjEzMS4zOH0=\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiQ1ZCIiwic2VjdG9yIjoiVEVDSE5PTE9HWSIsImNoYW5nZSI6LTEuMDcsInByaWNlIjo1Mi4zMX0=\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiQUFQTCIsInNlY3RvciI6IlRFQ0hOT0xPR1kiLCJjaGFuZ2UiOjAuNzMsInByaWNlIjo5OS44N30=\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiV1NCIiwic2VjdG9yIjoiRklOQU5DSUFMIiwiY2hhbmdlIjotMy4wMSwicHJpY2UiOjExMS4xNH0=\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiSktMIiwic2VjdG9yIjoiVEVDSE5PTE9HWSIsImNoYW5nZSI6MC4yNCwicHJpY2UiOjE0LjMxfQ==\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiSEpWIiwic2VjdG9yIjoiRU5FUkdZIiwiY2hhbmdlIjotMTcuNCwicHJpY2UiOjIwMi40OH0=\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiSEpWIiwic2VjdG9yIjoiRU5FUkdZIiwiY2hhbmdlIjoxMS4yNiwicHJpY2UiOjIxMy43NH0=\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiVEdIIiwic2VjdG9yIjoiRklOQU5DSUFMIiwiY2hhbmdlIjoxLjI2LCJwcmljZSI6NjAuNn0=\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiU0xXIiwic2VjdG9yIjoiRU5FUkdZIiwiY2hhbmdlIjoxLjk0LCJwcmljZSI6MTAxLjQ2fQ==\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiU0xXIiwic2VjdG9yIjoiRU5FUkdZIiwiY2hhbmdlIjoxLjE5LCJwcmljZSI6MTAyLjY1fQ==\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiVUhOIiwic2VjdG9yIjoiRklOQU5DSUFMIiwiY2hhbmdlIjo3LjQ4LCJwcmljZSI6NTk5fQ==\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiREVHIiwic2VjdG9yIjoiRU5FUkdZIiwiY2hhbmdlIjotMC40MywicHJpY2UiOjUuNjZ9\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiREZUIiwic2VjdG9yIjoiUkVUQUlMIiwiY2hhbmdlIjo0LjIyLCJwcmljZSI6OTIuMzl9\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiV01UIiwic2VjdG9yIjoiUkVUQUlMIiwiY2hhbmdlIjozLjg4LCJwcmljZSI6ODUuOTl9\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiUVhaIiwic2VjdG9yIjoiUkVUQUlMIiwiY2hhbmdlIjowLjE1LCJwcmljZSI6NTcuODR9\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiV01UIiwic2VjdG9yIjoiUkVUQUlMIiwiY2hhbmdlIjowLjE1LCJwcmljZSI6ODYuMTR9\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiV0FTIiwic2VjdG9yIjoiUkVUQUlMIiwiY2hhbmdlIjowLjI3LCJwcmljZSI6MTEuMzd9\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiS0lOIiwic2VjdG9yIjoiRU5FUkdZIiwiY2hhbmdlIjowLjEsInByaWNlIjo0LjIyfQ==\"},{\"data\":\"eyJ0aWNrZXJfc3ltYm9sIjoiS0lOIiwic2VjdG9yIjoiRU5FUkdZIiwiY2hhbmdlIjowLjIsInByaWNlIjo0LjQyfQ==\"}]}'",
```

Is this not a right format ?

**Comment by jszwedko** [comment]
Hi @papovyr,

Thanks for the example events. So, in this case, the events are base64 encoded, but vector additionally assumes that the content will have been gzip. That is, it first base64 decodes the paypload and then attempts to gunzip it.

You could inject a lambda in the middle that would gzip the payloads. Ideally we will fix this with #5918 though so that no transformation is needed on your part.

**Comment by papovyr** [comment]
I will assume that if i enable Gzip for Firehose HTTP destination it will work, However it's not.

Will wait for #5918 and will check vector again 

Thank you

**Comment by jszwedko** [comment]
> I will assume that if i enable Gzip for Firehose HTTP destination it will work, However it's not.
> 
> Will wait for #5918 and will check vector again
> 
> Thank you

👍 correct, enabling gzip at that level gzips the entire HTTP body (which vector also supports), but vector incorrectly assumes that each event payload is additionally gzip'd.

Thanks for providing all of the details. I'll close this issue in-lieu of https://github.com/timberio/vector/issues/5918
