### ISSUE TITLE
Improve integration benchmarking framework

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#6510]
The [Vector test harness](https://github.com/timberio/vector-test-harness) was created alongside Vector to benchmark Vector against alternatives, and while it has served us well, there is still quite a bit to improve.

## Goals

Bring the test harness up to a reliable state so that we can start to depend on it for nightly integration benchmarks.

**Comment by blt** [comment]
This ticket's concerns are superseded by our soak testing work. Many of the tickets in this epic were either duplicates of work accomplished in the soaking epic or are no longer relevant.
