### ISSUE TITLE
Splunk HEC source should accept either URL params or HTTP header

### ISSUE THREAD

**Issue by toddboom** [timberio/vector#6524]
### Current Vector Version

```
vector 0.12.0 (g420c911 x86_64-unknown-linux-gnu 2021-02-21)
```

### Use-cases

When sending logs from certain services that expect to write to a Splunk HEC endpoint, it is not always easy/possible to sent HTTP headers. In this case, it should be possible to use the `channel` URL param as described in the Splunk docs here:
https://docs.splunk.com/Documentation/Splunk/8.1.2/Data/FormateventsforHTTPEventCollector

### Attempted Solutions

N/A

### Proposal

The `splunk_hec` source plugin should accept either the `channel` URL param or the `X-Splunk-Request-Channel` HTTP header.

### References

Conversation on Discord with @jszwedko:
https://discord.com/channels/742820443487993987/746070604192415834/813042115885006879

**Comment by rikonor** [comment]
Can confirm I have `nightly-2021-04-13-debian` deployed and the issue appears to be resolved.

**Comment by jszwedko** [comment]
Awesome, thanks for confirming @rikonor and for the implementation. I'll close out this issue.
