### ISSUE TITLE
internal_metrics source doesn't emit expected metrics

### ISSUE THREAD

**Issue by zack-johnson5455** [timberio/vector#6530]
### Vector Version

```
0.12.0-nightly-2021-02-22
```

### Vector Configuration File

For privacy reasons I'm just going to list the Vector components that we use:

Installation 1:

Sources:
- Kubernetes Logs
- Journald

Transforms:
- add_fields

Sinks: 
- s3

Installation 2:
Sources:
- Kubernetes Logs
- File
- Journald

Transforms:
- add_fields
- regex_parser
- concat
- aws_ec2 metadata

Sinks:
- s3

### Debug Output

I use port-forwarding to expose the Vector pod's metrics endpoint (:9090/metrics) to localhost. The metrics that seem to be being collected are as follows:

Installation 1:
https://gist.github.com/zack-johnson5455/80ab6549d59ad9c1ffa57a149569b123

Instllation 2:
https://gist.github.com/zack-johnson5455/727a97e8e2e34fa701a7420ca270de60

### Expected Behavior

Installation 1: 
I expected to see metrics reported for:
-  [k8s_event_annotation_failures_total](https://vector.dev/docs/reference/sources/kubernetes_logs/#k8s_event_annotation_failures_total)

Installation 2:
I expected to see metrics reported for:
- [file_watch_errors_total](https://vector.dev/docs/reference/sources/file/#file_watch_errors_total)
- [metadata_refresh_failed_total](https://vector.dev/docs/reference/transforms/aws_ec2_metadata/#metadata_refresh_failed_total)
- [processing_errors_total](https://vector.dev/docs/reference/transforms/regex_parser/#processing_errors_total)
- [checkpoint_write_errors](https://vector.dev/docs/reference/sources/file/#checkpoint_write_errors_total)

### Actual Behavior
None of these metrics are exposed on the :9090/metrics endpoint

### Additional Context

Vector is running in Kubernetes and is installed via helm chart. We use AWS ec2 nodes and disable the hostMetrics source.

**Comment by jszwedko** [comment]
Hi @zack-johnson5455 . Those error metrics will only be published if there are actual errors that cause the corresponding events to be triggered. We have an enhancement ticket, https://github.com/timberio/vector/issues/6532, that will have us start publishing those, even if the associated event isn't triggered, where possible. I'll close this in-lieu of that issue.
