### ISSUE TITLE
Documentation for 'file' source is not clear

### ISSUE THREAD

**Issue by alpi-ua** [timberio/vector#6558]
Hello team.
Some clarification is needed for the file source.
This text in documentation is quite confusing:

1.  Ignore_older
**ignore_older** Ignore files with a data modification date that _does not_ exceed this age.
What is age here? In what units? It means that files more than "ignore_older N" will be ignored ? Or opposite? 

2. Remove_after
**remove_after** N = what units are using there ?

Appreciate your help

**Comment by jszwedko** [comment]
Hi @alpi-ua ,

Agreed, the documentation could be improved here. To answer your questions:

1. `ignore_older` should be the number of seconds to ignore files that have a modification time older than `now() - ignore_older` at vector startup. For example, an `ignore_older` of `300` would ignore files that haven't been written to within the last 5 minutes from when vector starts up. This option was identified as confusing in https://github.com/timberio/vector/blob/master/rfcs/2020-10-15-3480-file-source-rework.md and should hopefully be updated with something more clear.
2. `remove_after` is in seconds

**Comment by jszwedko** [comment]
Let me know if that clarifies things! I can update the docs if so.

**Comment by alpi-ua** [comment]
Thank you, with your explanation it becomes more clear.
Update would be helpful.

**Comment by jszwedko** [comment]
@alpi-ua thanks for confirming! I opened #6568 to update the docs and also rename the config values to be suffixed to be more clear.
