### ISSUE TITLE
Validate example configs

### ISSUE THREAD

**Issue by loony-bean** [timberio/vector#658]
Since Vector binary supports handy `--dry-run` command now, it could be used to validate example config files, possibly somewhere in CI pipeline.

```
$ cargo run -- --dry-run --config config/examples/complete/wrapped_json.toml

<snip>

Jul 18 10:32:20.515  INFO vector: Dry run enabled, exiting after config validation.
Jul 18 10:32:20.516 ERROR vector::topology: Configuration error: Input "apache_parser" for sink "out" doesn't exist.
```

**Comment by Jeffail** [comment]
I think this is basically ready to go but there's a few small QOL improvements outlined in https://github.com/timberio/vector/issues/98#issuecomment-542660074 that I think would ought to add before adding this to our CI.

**Comment by Jeffail** [comment]
This adds a target for executing dry run tests on example configs: https://github.com/timberio/vector/commit/a56d8bf3a7cd25be0017ba7c76c0223b5f209d34

SPOILER ALERT: There are issues with the example configs.

**Comment by binarylogic** [comment]
Ha. I'd like to point out that these example configs in the `config/examples/sinks`, `config/examples/transforms` and `config/examples/sources` are generated based on the project's [`.meta`](https://github.com/timberio/vector/tree/master/.meta) data. They were initially there to serve as quick references, as opposed to the `config/vector.spec.toml` which is more verbose.

Interestingly, the code that generated and maintained these is no longer present (need to fix that).

**Comment by Jeffail** [comment]
@binarylogic I've got a branch where I have the examples fixed, should I delete the component specific configs entirely? If I do then I might move everything in `./config/examples/complete` out into `./config/examples`.
