### ISSUE TITLE
Periodically trigger disk buffer compaction

### ISSUE THREAD

**Issue by lukesteensen** [timberio/vector#6597]
#5821 addressed a number of issues related to us doing too many compactions in leveldb, leading to inefficiency, large log files, and poor performance. In fixing those issues, however, our behavior has changed somewhat for less busy use cases.

We will now not trigger compaction at all (or at least very rarely) before we approach the maximum size of the disk buffer. This means we will use a significant amount of disk space even when the sink is caught up to the current input events, which is surprising to users. It would be less surprising if we still periodically compacted to keep disk usage low in the normal case.

To address this, we should add some kind of simple interval checking that ensures we trigger a compaction iff there has not been one for some time period (e.g. 1 minute). We should be careful not to reintroduce any of the old problems by compacting very often, and simply provide a backstop for cases where we shouldn't need to use much disk.

**Comment by ktff** [comment]
@lukesteensen just want to check, what's the reason for using leveldb in the first place? Is it related to future plans or?

**Comment by binarylogic** [comment]
@ktff it was a decision we made very early on for the disk buffer MVP. It is not something we plan to keep around, but it is not worth changing at this time.

**Comment by lukesteensen** [comment]
Yes, it was a choice early on to take advantage of an existing tool for persistence. Without it we would have needed to deal with crash-safe persistence across platforms ourselves, as well as performance and other concerns we figured would be "good enough" with leveldb. In the future it's likely to be replaced with something that is simpler internally and better matches our use case, but that will be a decent amount of work.
