### ISSUE TITLE
Bug: Vector test harness repository is not available

### ISSUE THREAD

**Issue by rw** [timberio/vector#6605]
Bug: Vector test harness repository is not available

I'd like to read the source code of the benchmarks this project uses, so I can figure out how I can best use Vector.

The repository is linked multiple times from this project's README, e.g. https://github.com/timberio/vector-test-harness/tree/master/cases/tcp_to_tcp_performance

Thanks!

**Comment by binarylogic** [comment]
Hi @rw, thanks for reporting. That was accidental. The repository is public now.
