### ISSUE TITLE
Tutorial on https://vector.dev/docs/setup/installation/operating-systems/centos/ failed

### ISSUE THREAD

**Issue by moogspike** [timberio/vector#6611]
The tutorial on:

https://vector.dev/docs/setup/installation/operating-systems/centos/

Here's what went wrong:

vector: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by vector)
vector: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by vector)
vector: /usr/lib64/libc.so.6: version `GLIBC_2.18' not found (required by vector)

**Comment by jszwedko** [comment]
Hi @moogspike . What version of CentOS are you running?

**Comment by moogspike** [comment]
Hi, 

Thanks for the ping. 

Centos 7 - downloaded the vector-nightly-x86_64-unknown-linux-musl.tar build and all working now. 


Cheers
Spike
--
Andrew Hepburn
+44 7785 500 132
spike@moogsoft.com

**Comment by jszwedko** [comment]
Thanks for the update @moogspike ! The nightly glibc rpm's should work for you too. The glibc version constraint was relaxed to 2.15 such that CentOS 7 should be supported now.

This should be fixed with the next release so that you will be able to install the stable version.

**Comment by moogspike** [comment]
Cracking !!! Very much enjoying Vector and it’s capacities. Thanks for being so responsive. 


Cheers
Spike
--
Andrew Hepburn
+44 7785 500 132
spike@moogsoft.com

**Comment by SirEdvin** [comment]
Hm ... when we can expect new release? Currently I can't install vector 0.11 to my centos servers, and I am not sure, that nightly build is suitable for production.

**Comment by jszwedko** [comment]
Hi @SirEdvin . We are targeting today 🤞

**Comment by jszwedko** [comment]
Hi @SirEdvin . we released 0.12.1 which should be usable on CentOS 7. I'll close this out, but please let me know if you still see any issues. I tested out using the `centos:7` docker image.
