### ISSUE TITLE
VRL 100 error thrown for non-function expression

### ISSUE THREAD

**Issue by lucperkins** [timberio/vector#6644]
This expression throws a 100 error:

```
$ 10 - "foo"
error[E100]: unhandled error
  ┌─ :1:1
  │
1 │ 10 - "foo"
  │ ^^^^^^^^^^
  │ │
  │ expression can result in runtime error
  │ handle the error case to ensure runtime success
  │
  = see documentation about error handling at https://errors.vrl.dev/#handling
  = learn more about error code 100 at https://errors.vrl.dev/100
  = see language documentation at https://vrl.dev
```

In this case, it doesn't make sense to handle an error on a mathematical operation. The VRL compiler needs to not treat expressions of this sort as function cals.

**Comment by lucperkins** [comment]
Actually, I take it back. I can see why this is necessary and how it can be handled via capture. Closing.

**Comment by jszwedko** [comment]
🤔 in this particular case, I think it'd be nice to throw a complier error since it can definitely tell that that expression will fail.
