### ISSUE TITLE
Automatically publish musl based packages

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#6645]
This was previously done for 0.11.0 specifically, see https://github.com/timberio/vector/issues/5364, but I don't see them for the nightlies or 0.11.1 so it seems like this is not wired up in CI.

We should publish musl based debs and rpms for older distributions like Centos 7 that lack glibc 2.18. These should additionally be available via the cloudsmitch package repositories.

**Comment by jszwedko** [comment]
I dug into this a bit more and think it may not be worth it to also publish musl packages given the only combination I could find that seems like it'd be unsupported is centos7/aarch64.

I did a quick survey of the oldest supported versions of some common distros to see their glibc support:

```
ubuntu:14.04        2.19
centos:7            2.17
debian:9            2.24
fedora:27           2.31
opensuse/leap:15.0  2.26
```

I'd rather wait for someone to ask for aarch64/centos7 support before we add that to the release process. I also opened https://github.com/rust-embedded/cross/issues/528 to see if it'd be possible to have `cross` itself relax the requirement.

@blt brought up the idea that embedded environments will probably prefer musl, but we do publish tarballs for those. Again, we can wait and see if there is user desire for this.

**Comment by blt** [comment]
@jszwedko happy to.

**Comment by blt** [comment]
@jszwedko I agree with your analysis. Addressing this upstream strikes me as ideal and, second, aarch64/centos7 probably has very, very few users globally, so I can't imagine we're inconveniencing any users. So long as we keep the option open to build for this target I'm happy to drop it, absent any demand for it.

**Comment by jszwedko** [comment]
Thanks for taking a look and confirming!
