### ISSUE TITLE
CLI subcommand for new 'tap' API

### ISSUE THREAD

**Issue by leebenson** [timberio/vector#6658]
#6610 introduces a new Vector 'tap' API that allows observability into component log events.

The first client will be a `vector tap` CLI subcommand.

Features:

- Connect to a local/remote GraphQL API endpoint (`--url`)
- Provide one or more components to observe, by name/glob (`--name`)
- Capture events over a time window (`--interval`)
- Sample events, up to a provided max (`--limit`)
- Displays log event lines as JSON/YAML (`--json`  / `--yaml`)

Later work will include filtering (#6390) and using VRL to limit/transform data.

**Comment by binarylogic** [comment]
Closed via https://github.com/timberio/vector/pull/6871
