### ISSUE TITLE
`vector vrl` doesn't exist in the 0.12.0 x86_64 Linux binaries

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#6707]
Reported by user in discord: https://discord.com/channels/742820443487993987/746070591097798688/819356395660902403

```
❯ vector --version
vector 0.12.0 (v0.12.0 x86_64-unknown-linux-gnu 2021-03-10)
❯ vector vrl
error: The subcommand 'vrl' wasn't recognized

USAGE:
    vector help <subcommands>...

For more information try --help
```

I verified the same.

It is released with the OSX binaries and is built in when I run `cargo bulid` on Linux x86_64 so there might be something different with how the release process is building it.

We should check the other released architectures and OSs (windows and aarch64).

**Comment by lucperkins** [comment]
Ah okay, I see the issue
