### ISSUE TITLE
Smarter sampling for tap

### ISSUE THREAD

**Issue by leebenson** [timberio/vector#6713]
Vector tap introduced in #6610 allows sampling of log events over a provided `interval` in the API.

To provide fair/even sampling, events are currently copied into a vec and then post-sampled. This results in _all_ events over an interval for observed component(s) being duplicated in memory.

For lower volumes, this is unlikely to be a bottleneck. At scale, this could result in a significant number of allocations and memory pressure.

Ideally, events should be sampled as they arrive, up to the max provided `limit`. The complexity is how to ensure even distribution over `interval` in situations where volume is unpredictable.

**Comment by jszwedko** [comment]
An idea for this is just to fill a vec to the limit and then randomly evict entries as more events come in. I think this would result in a randomly distributed sample over the interval.

**Comment by leebenson** [comment]
Nice idea @jszwedko. [rand::distributions::Uniform](https://docs.rs/rand/0.8.3/rand/distributions/struct.Uniform.html) might be useful here.

**Comment by leebenson** [comment]
Also https://docs.rs/reservoir/0.2.0/reservoir/ per https://en.wikipedia.org/wiki/Reservoir_sampling

**Comment by jszwedko** [comment]
Nice! That seems exactly it.

**Comment by leebenson** [comment]
Noting that the "Algorithm R" reservoir sampling approach was implemented in #6610. Closing.
