### ISSUE TITLE
Ability to drop events in the `remap` transform

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#6720]
I'm recording feedback from a user. In order to fully switch from the `lua` transform to `remap`, they need the ability to conditionally drop events. This is achieved by _not_ calling the `emit` function in the `lua` transform. They want to do this when the event is severely malformed.

In the future, this should be paired with our deadletter queue feature.

cc @JeanMertz

**Comment by JeanMertz** [comment]
We do already support dropping events _if the program errors at runtime_.

I think there are two things we would need to do to fully support this:

1. Document `drop_on_err` (it exists, but hasn't been documented, it seems)
2. Either direct users to write `assert!(false)` in their program to abort the program, or add a new `abort` built-in statement to stop execution.

I'll open up a PR for (1), and I feel like instructing people to use `assert!(false)` for now is sufficient, but am also happy to add `abort` as a statement specifically for this use-case.

**Comment by binarylogic** [comment]
Yeah, I think there needs to be a non-error/silent way of dropping events that users can opt into.

**Comment by JeanMertz** [comment]
Right. I would say if you explicitly call `abort`, it should stop the program, but not log an error. You can always use `log` to manually log an error if you have a need to do so.

I'll follow up with a PR to add an `abort` statement.

**Comment by JeanMertz** [comment]
Working on this in https://github.com/timberio/vector/pull/6723, will wrap that work up tomorrow.

**Comment by binarylogic** [comment]
cc @karlseguin, let us know if this solves your problem.

**Comment by karlseguin** [comment]
I think so. This will let us replace the last of our lua transforms, thanks. Having just 1 transform language will help with maintainability.
