### ISSUE TITLE
Add flag to `parse_regex` to suppress numeric capture groups

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#6721]
Requested by user in discord: https://discord.com/channels/742820443487993987/746070591097798688/819582119230963723

The user's config looks like:

```
. |= parse_regex!("first group and second group.", r'(?P<number>.*?) group')
```

Currently it gives them:

```json
{
  "number": "first",
  "0": "first group",
  "1": "first"
}
```

In this case, it'd be useful to have only the `number` capture group merged into `.`.

I know I was the one that originally advocated for numeric capture groups, but I could see defaulting them to off 😄

**Comment by jszwedko** [comment]
Just noting another couple of users requested this today:

https://discord.com/channels/742820443487993987/746070604192415834/821573607590854726
https://discord.com/channels/742820443487993987/746070591097798688/821500635534196807

This seems like the expectation so far so I could see treating this as a bug which we could fix in a patch release.

**Comment by binarylogic** [comment]
@FungusHumungus is on it, and I've added it to the 0.12.2 milestone.

**Comment by brianpham** [comment]
This would be useful for me too. I am currently parsing the kafka topic which looks like (env_server_logs) or (env_client_logs) and using that to add new fields. The following below seems to work for me as a workaround. 

```
  .topic_name, err = parse_regex(.topic, r'((?P<env>[a-z_-]+)_(?P<log_type>[a-z]+)_logs)')
  .@metadata.env_name = .topic_name.env
  .@metadata.log_type = .topic_name.log_type
```
