### ISSUE TITLE
Link from `JSON` documentation to `remap` tranform doc broken

### ISSUE THREAD

**Issue by tinoadams** [timberio/vector#6752]
Broken link in documentation

On page https://vector.dev/docs/reference/configuration/transforms/json_parser/

`This transform has been deprecated in favor of the remap transform, which enables you to`

Link to `remap` current is https://vector.dev/docs/reference/transforms/remap/
but should be https://vector.dev/docs/reference/configuration/transforms/remap/

**Comment by jszwedko** [comment]
@binarylogic you probably already noticed this, but there seems to be a general issue where clicking links on the site does not interact with the redirects that we have defined where as refreshing the same URL does.

**Comment by jszwedko** [comment]
Noticed by another user in discord: https://discord.com/channels/742820443487993987/746070591097798688/821530172364423179
