### ISSUE TITLE
Allow wildcard to appear anywhere in the input name

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#6786]
https://github.com/timberio/vector/pull/6170 added wildcard support for `inputs`, for example:

```
inputs = ["foo*"]
```

But only at the end of strings.

A user in discord, https://discord.com/channels/742820443487993987/746070591097798688/821455853009240084, requested allowing the wildcard at the end of strings as well.

I would propose allowing full glob syntax including `?`s.

This also has implications for `vector tap` where I think it'd be nice to have the same patterns supported for component names in both places. cc/ @leebenson

**Comment by leebenson** [comment]
I'm +1 on full glob.

It's what I'd expect as a user, and we're already leaning on the `glob` lib for the file source and config expansion, so it doesn't cost us much to offer it.

**Comment by jszwedko** [comment]
Requested by discord user again: https://discord.com/channels/742820443487993987/746070591097798688/846783250612355073
