### ISSUE TITLE
kubernetes_logs source stop glob after [unexpected EOF during chunk size line] occurred

### ISSUE THREAD

**Issue by CasparChou** [timberio/vector#6795]
### Vector Version

```
v0.11.1-debian
```

### Vector Configuration File

https://gist.github.com/CasparChou/70234ddf69d18291f27f04df106f0c5d#file-vector-agent-config

### Debug Output

debug logs still collecting

### Expected Behavior

if error can't be handled, exit process
if process can handle the exception and resume collecting/sink, will be better
after restart pod, file checkpoint forward to current time and seems losing logs

### Actual Behavior

kubernetes_logs source stuck and stop collecting logs, and increased `vector_k8s_watch_requests_failed_total`
but process still alive, it's hard to know logs is stop collecting

```
Mar 16 22:46:59.121 ERROR source{component_kind="source" component_name=kubernetes_logs component_type=kubernetes_logs}: vector::internal_events::kubernetes::instrumenting_watcher: Watch invocation failed. error=Reading { source: hyper::Error(Body, Custom { kind: UnexpectedEof, error: "unexpected EOF during chunk size line" }) } rate_limit_secs=5
Mar 16 22:46:59.121 ERROR source{component_kind="source" component_name=kubernetes_logs component_type=kubernetes_logs}: vector::sources::kubernetes_logs: Reflector process exited with an error. error=streaming error
```

### Additional Context

losing logs when agent is not working, and not recovering logs when agent is back (by terminated pod)
![image](https://user-images.githubusercontent.com/10682620/111433256-06172d80-8739-11eb-9543-e9375ec096d0.png)

Error occurred on all agent in same time (first graph), and all of agents' source/sink plugin stop process any event (second graph)
![image](https://user-images.githubusercontent.com/10682620/111436966-88095580-873d-11eb-9adb-a076bfb7ad79.png)

**Comment by jszwedko** [comment]
A few more examples from discord:

https://discord.com/channels/742820443487993987/746070591097798688/814662393408782367
https://discord.com/channels/742820443487993987/753400475545501836/821662662919716864
https://discord.com/channels/742820443487993987/753400475545501836/820684877519257650

**Comment by CasparChou** [comment]
anthor situation is `{ code: 104, kind: ConnectionReset, message: "Connection reset by peer" }`
we also got same error in some pods

0.12.1 
(copied from discord message sent by hjarvard)
```
Mar 14 15:42:38.468 ERROR source{component_kind="source" component_name=kubernetes_logs component_type=kubernetes_logs}: vector::internal_events::kubernetes::instrumenting_watcher: Watch invocation failed. error=Other { source: K8sStream { source: Reading { source: hyper::Error(Body, Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) } } } internal_log_rate_secs=5
Mar 14 15:42:38.468 ERROR source{component_kind="source" component_name=kubernetes_logs component_type=kubernetes_logs}: vector::sources::kubernetes_logs: Reflector process exited with an error. error=streaming error
Mar 14 15:42:38.469  INFO source{component_kind="source" component_name=kubernetes_logs component_type=kubernetes_logs}: vector::sources::kubernetes_logs: Event processing loop completed gracefully.
Mar 14 15:42:38.469  INFO source{component_kind="source" component_name=kubernetes_logs component_type=kubernetes_logs}: vector::sources::kubernetes_logs: File server completed gracefully.
Mar 14 15:42:38.469  INFO source{component_kind="source" component_name=kubernetes_logs component_type=kubernetes_logs}: vector::sources::kubernetes_logs: Done.
```

**Comment by CasparChou** [comment]
workaround on agent

```
        containers:
          - name: vector
            securityContext:
              {}
+           livenessProbe:
+             exec:
+               command:
+               - bash
+               - -c
+               - |
+                 (($(tail -n 10 $(ls /var/log/containers/`hostname`*) | grep 'Reflector process exited with an error.' -c) < 1))
+             failureThreshold: 5
+             initialDelaySeconds: 120
+             periodSeconds: 6
+             successThreshold: 1
+             timeoutSeconds: 5
```

**Comment by jszwedko** [comment]
Another discord example:

https://discord.com/channels/742820443487993987/746070591097798688/826477956611833856

**Comment by jszwedko** [comment]
This issue was not actually resolved, but has been reopened as https://github.com/timberio/vector/issues/7401. Closing this in-lieu of that one, but figured I'd leave a note here.
