### ISSUE TITLE
New `vector_metrics` source

### ISSUE THREAD

**Issue by lukesteensen** [timberio/vector#68]
Following #64, it would be neat if we could create an "internal" metrics source and use it to instrument the rest of the application.

This would give us good feedback on our metrics implementation and make our own observability story better. It would replace the existing prometheus counters and give us the flexibility to use any metrics sink we want.

Taken to the extreme, we could have the source be our existing logger and use transforms, aggregates, etc to derive all the metrics we want. We don't need to go that far at first, but it could be something interesting to work towards.

**Comment by binarylogic** [comment]
I'm adding some high-level considerations to include in this spec:

1. Metrics have a cost to our users depending on the downstream service:
    1. We should provide options to white-list and black-list metrics.
    2. Depending on our naming structure, it'd also be nice if we could do this for entire categories of metrics.
    3. Given that there is a cost, does it make sense for users to explicitly opt-into metrics by default? This way upgrading doesn't introduce an influx of new metrics and surprise costs.
2. This one is obvious but worth mentioning. I'd like to outline all of the metrics we plan to emit for v1 of this source as well as their labels. Let's keep this to a minimum for v1. This way we can obtain consensus on a naming pattern and try it out before we add more metrics. It's likely we'll make changes during this process.

@danpalmer has graciously offered to beta this feature when we're ready 😄
