### ISSUE TITLE
kubectl instructions still refer to 0.11.1

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#6804]
https://vector.dev/docs/setup/installation/platforms/kubernetes/ (click kubectl in the dropdown that defaults to helm)

<img width="776" alt="Screen Shot 2021-03-17 at 4 24 14 PM" src="https://user-images.githubusercontent.com/316880/111533505-3d87d900-873d-11eb-9a20-7ef9e583d36c.png">

I think ideally we'd wire this up in a way where it automatically updates to the latest version.

**Comment by binarylogic** [comment]
Yes, this page should be templated, I'm surprised that it is not.

**Comment by binarylogic** [comment]
I take that back, we need to make this value dynamic:

https://github.com/timberio/vector/blob/d41a79de4f03f56ad3ac5de794024bb10d676e44/docs/reference/installation/_interfaces/kubectl.cue#L22

**Comment by jszwedko** [comment]
@spencergilbert fixed this in #7828 . It would be nice if that value was dynamic though. For now, I just added it to the release documentation. I think this may also go away with the new site (or be managed differently).
