### ISSUE TITLE
Add documentation on how to run Vector as non-root

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#6820]
From https://github.com/timberio/vector/issues/6555#issuecomment-802630143

> I don' think CAP_DAC_READ_SEARCH should be included by default, but I do think reading files owned by different users is probably a common issue people are reading on, and good documentation could help people avoid running vector as root.

In general, Vector should not be deployed under the `root` user unless absolutely necessary. We should make this as easy as possible, and this will likely require some documentation.

**Comment by jszwedko** [comment]
We currently release service definitions that run `vector` as the `vector` user.

The commenter is correct, though, that users using the `file` source will often be collecting files not owned by the `vector` user. A typical approach I've taken for this is adding the user to the `adm` or equivalent group (which we actually already do for the deb packages) which is usually able to read `/var/log` and friends. I agree that we should document this though. I consider `CAP_DAC_READ_SEARCH` as a sort of last resort right underneath running as root, but we can mention it too.
