### ISSUE TITLE
Identify any additional noise reducing improvements for criterion benches

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#6828]
We've spent some time optimizing the benchmark workers to reduce noise, but it is still higher than desired. We should take a quick look and see if there are any other opportunities to reduce including:

* Disabling any CPU power management features
* Disabling any CPU turbo features

Timebox this to a half day.

**Comment by jszwedko** [comment]
I've exceeded the timebox of a couple hours for this one.

I did verify that we are locking cstates to a max of 1 already via grub:

```
GRUB_CMDLINE_LINUX_DEFAULT="console=tty1 console=ttyS0 nvme_core.io_timeout=4294967295 isolcpus=0 intel_idle.max_cstate=1 intel_pstate=disable"
```

I could not figure out what CPU frequency module was being used here to see about locking the pstate too though. I assumed it would be `intel_pstate` since that seems to be the one used on modern systems but the expected `/sys/devices/system/cpu/intel_pstate/` was not there.

`powercpu` says:

```
ubuntu@ip-10-0-101-81:~$ sudo cpupower frequency-info
analyzing CPU 0:
  no or unknown cpufreq driver is active on this CPU
  CPUs which run at the same hardware frequency: Not Available
  CPUs which need to have their frequency coordinated by software: Not Available
  maximum transition latency:  Cannot determine or is not supported.
Not Available
  available cpufreq governors: Not Available
  Unable to determine current policy
  current CPU frequency: Unable to call hardware
  current CPU frequency:  Unable to call to kernel
  boost state support:
    Supported: yes
    Active: yes
```

The boost state support reported there is interesting.

I tried installing the `acpi-cpufreq` to see if I could get that working. `modprobe` happily takes it, but doesn't actually enable it (`lsmod` doesn't return it). I tried adding it to the boot modules too but to no avail.

Reported frequencies do seem to bubble around the max of 3400 MhZ:

```
ubuntu@ip-10-0-101-81:~$ grep -E '^model name|^cpu MHz' /proc/cpuinfo
model name	: Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
cpu MHz		: 3404.103
model name	: Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
cpu MHz		: 3398.098
model name	: Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
cpu MHz		: 3404.132
model name	: Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
cpu MHz		: 3400.723
```

Even when there is nothing much running:

```
 22:32:54 up 10 min,  1 user,  load average: 0.00, 0.00, 0.00
```

@blt I dunno if you have any other ideas to try off the top of your head?

**Comment by blt** [comment]
Hmm, and as I recall our EC2 instances don't have burstable CPUs, so we're good there too. @jszwedko this strikes me as very thorough.
