### ISSUE TITLE
log_to_metric field data into label

### ISSUE THREAD

**Issue by jamessewell** [timberio/vector#684]
It would be cool if I could use the field name in the metric label (or maybe the metric name, but I can't actually think of a sane example for this).

So take a log file with a field of `error` (ERROR/WARN/INFO/DEBUG) and then end up with a metric which used a label to show that:

    `status_total{type="ERROR|WARN|INFO|DEBUG"}`

Another example would be breaking a REST API hits counter down with a label for the response code.

I don't think you can do this at the moment?

**Comment by binarylogic** [comment]
Hey @jamessewell thanks for the feedback. This is definitely something we have planned. We're still working on building out the core data model for metrics (specifically histograms) and wanted to get a couple of different metrics sources and sinks built out before we implemented labels. Although, it's looking like we'll prioritize that (see https://github.com/timberio/vector/pull/675#issuecomment-514212709) and should have labels support in the next couple of weeks.
