### ISSUE TITLE
function "statvfs" call failed: Too many levels of symbolic links

### ISSUE THREAD

**Issue by zzswang** [timberio/vector#6842]
### Vector Version

```
version="0.12.1" git_version="v0.12.1" released="Fri, 12 Mar 2021 21:27:28 +0000" arch="x86_64"
```

### Vector Configuration File

install vector-agent by helm with default config in k8s.

[the helm values.yaml](https://github.com/timberio/vector/blob/master/distribution/helm/vector-agent/values.yaml)

### Debug Output

main error

```
vector::sources::host_metrics: Failed to load partition usage data. mount_point="/host/proc/sys/fs/binfmt_misc"
error=FFI function "statvfs" call failed: Too many levels of symbolic links (os error 40) internal_log_rate_secs=60
```

while enter this pod:

```
# kubectl exec -it vector-agent-5b45m -- bash                                                                                                  
root@vector-agent-5b45m:/# ls /host/proc/sys/fs/binfmt_misc
ls: cannot open directory '/host/proc/sys/fs/binfmt_misc': Too many levels of symbolic links
```

details:

https://gist.github.com/zzswang/d9956a3934cea1703b4c35b3603f0b30

### Additional Context

k8s was setup on PVE's kvm, not sure if it is related to this error.

**Comment by binarylogic** [comment]
I'm curious what you think @bruceg. Is this something we should handle?

**Comment by bruceg** [comment]
AFAICT we are "handling" it — this error message would not have prevented other host metrics from being reported. The question is if we should silence this particular case. This seems like a system configuration (not user configuration) issue where portions of `/proc` have looping symbolic links. I would tend to think we should keep the error (which is rate limited to once a minute), unless this is a common configuration issue.

**Comment by jszwedko** [comment]
Another user ran into this in discord: https://discord.com/channels/742820443487993987/753400475545501836/826918778549043301

**Comment by jszwedko** [comment]
Noting a similar issue in dd-agent: https://github.com/DataDog/datadog-agent/issues/3600 . There the recommended solution was to blacklist that specific mount point `/host/proc/sys/fs/binfmt_misc`.

The go so far as to include that in their default config, commented out:

https://github.com/DataDog/integrations-core/blob/8b23ba90963e88f8973c0740bb9043d4a1c0dd47/disk/datadog_checks/disk/data/conf.yaml.default#L22-L29

We may want to adjust our documentation to convey the same.

The issue seems to occur when `systemd-binfmt` is not running.

**Comment by bruceg** [comment]
Given that evidence, it does seem we should at least work around this common situation by ignoring certain errors like this. The `host_metrics` source doesn't directly reference files like this, but a suitable wrapper could be written. I'll take a look.

**Comment by bruceg** [comment]
We discussed ignoring this particular error for all mount points in #6970, but concluded that it causes a bigger problem (undiagnosable errors) than it solves, particularly given that this can be worked around by adding one of the following line to the Vector config:
```toml
filesystem.devices.excludes = ["binfmt_misc"]
filesystem.filesystems.excludes = ["binfmt_misc"]
filesystem.mountpoints.excludes = ["*/proc/sys/fs/binfmt_misc"]
```

Does the above work for you @zzswang?

**Comment by zzswang** [comment]
@bruceg, sorry for the late reply.

Yes, this work around fixed the problem. Thanks very much.

And I found the changes in [values.yaml](https://github.com/timberio/vector/blob/master/distribution/helm/vector-agent/values.yaml#L188) is not work.

**Comment by jszwedko** [comment]
Thanks for the reply @zzswang . I'll reopen this issue to make sure we update the helm chart.
