### ISSUE TITLE
support multiline expression in the `()` block

### ISSUE THREAD

**Issue by VVvKamper** [timberio/vector#6848]
### Current Vector Version

```
vector 0.12.1 (v0.12.1 x86_64-apple-darwin 2021-03-12)
```

### Use-cases

I'm trying to write in vrl something like 

```
if (starts_with(image, "k8s.gcr.io/kube-apiserver") ||
    starts_with(image, "k8s.gcr.io/kube-scheduler")) {"k8s-plain"}
else {"unknown"}
```

but get an error that this is invalid syntax. I tested it with the `vector vrl` command.

### Attempted Solutions

I also tried to escape new lines with the `\` but still got the error

```
error[E203]: syntax error
  ┌─ :1:53
  │
1 │ if (starts_with(image, "k8s.gcr.io/kube-apiserver") \
  │                                                     ^
  │                                                     │
  │                                                     unexpected syntax token: "Escape"
  │                                                     expected one of: "\n", "!=", "%", "&&", "(", ")", "*", "+", ",", "-", ".", "/", ";", "<", "<=", "==", ">", ">=", "??", "[", "]", "identifier", "path field", "string literal", "{", "|", "|", "||", "}"
  │
  = see language documentation at https://vrl.dev
```

### Proposal

I think it'll be good to support multiline expressions in the if predicate.

### References

#4946

**Comment by jszwedko** [comment]
FWIW, it does appear to work in the transform, just not in the REPL. I did need to reformat it a bit though:

```
[sources.in]
type = "stdin"

[transforms.remap]
type = "remap"
inputs = ["in"]
source = """
foo = if (starts_with(.image, "k8s.gcr.io/kube-apiserver") ||
    starts_with(.image, "k8s.gcr.io/kube-scheduler")) {
        "k8s-plain"
} else {"unknown"}
"""

[sinks.out]
type = "console"
inputs = ["remap"]
encoding.codec = "json"
```

I needed to put the `else` on the same line as the `}`.

**Comment by JeanMertz** [comment]
> FWIW, it does appear to work in the transform, just not in the REPL.

The REPL has a custom implementation to support multi-line input:

https://github.com/timberio/vector/blob/b2008a948a93e8c89296a7d3f8199e8c8ac81c92/lib/vrl/cli/src/repl.rs#L229-L250

I presume this is why it fails in the REPL? That logic also seems to be outdated with the latest language changes, so it's worth an update.

> I needed to put the `else` on the same line as the `}`.

That's worth fixing on its own.
