### ISSUE TITLE
VRL REPL hangs for `parse_grok` input

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#6875]
Reported by user in discord: https://discord.com/channels/742820443487993987/746070591097798688/824146032543399967

The following input in the VRL console hangs. I think it is waiting for more input:

```
parse_grok!("1.2.3.4 - - [23/Mar/2021:06:46:35 +0000]", "%{IPORHOST:remote_ip} %{USER:ident} %{USER:user_name} \[%{HTTPDATE:timestamp}\]")
```

Possibly related to https://github.com/timberio/vector/issues/6788

**Comment by JeanMertz** [comment]
Doesn't seem related to #6788, but I'll look into it.

**Comment by JeanMertz** [comment]
Actually, I suspect this must be related to the escaping, since escaping `]` using `\]` isn't valid. It still shouldn't hang though.

The correct way to write this is to use `\\]` or use `r'\]'`.

**Comment by jszwedko** [comment]
Indeed, confirming that:

```
parse_grok!("1.2.3.4 - - [23/Mar/2021:06:46:35 +0000]", "%{IPORHOST:remote_ip} %{USER:ident} %{USER:user_name} \\[%{HTTPDATE:timestamp}\\]")
```

Works.

```
parse_grok!("1.2.3.4 - - [23/Mar/2021:06:46:35 +0000]", "%{IPORHOST:remote_ip} %{USER:ident} %{USER:user_name} \[%{HTTPDATE:timestamp}\]")
```

Still hangs forever and uses 100% of a CPU.
