### ISSUE TITLE
Check VRL function results in tests against `type_def`

### ISSUE THREAD

**Issue by vladimir-dd** [timberio/vector#6881]
In VRL functions we define `type_def`, for example:
```
fn type_def() -> BTreeMap<&'static str, TypeDef> {
    map! {
        "message": Kind::Bytes,
        "timestamp": Kind::Timestamp | Kind::Null
    }
}
```
but we don't really check property types in tests, so no matter if `timestamp` is defined as `Kind::Timestamp` or `Kind::Integer` the tests will pass for any `timestamp` value. We should check property types in our tests.

**Comment by JeanMertz** [comment]
I believe this is resolved with the new `test_function` macro. If not, then I might be misunderstanding the request here. Please let me know if that's the case @vladimir-dd.
