### ISSUE TITLE
Insert unknown fields in Clickhouse

### ISSUE THREAD

**Issue by mr-karan** [timberio/vector#6891]
### Current Vector Version

```
vector 0.12.1 (v0.12.1 x86_64-unknown-linux-gnu 2021-03-12)
```

### Use-cases

While inserting a JSON, Clickhouse gives an error in case the field is not present in the schema. There's an option([`input_format_skip_unknown_fields`](https://clickhouse.tech/docs/en/faq/integration/json-import/#useful-settings)) to ignore this error (it simply discards the field silently and doesn't error out). This could be a useful setting for Vector users.

Currently, this is the error which comes, if Vector sends a field which is not present in the table schema of Clickhouse:

```
Mar 26 09:19:24.590 ERROR sink{component_kind="sink" component_name=clickhouse component_type=clickhouse}:request{request_id=0}: vector::sinks::util::sink: Response wasn't successful. response=Response { status: 400, version: HTTP/1.1, headers: {"date": "Fri, 26 Mar 2021 03:49:24 GMT", "connection": "Keep-Alive", "content-type": "text/tab-separated-values; charset=UTF-8", "x-clickhouse-server-display-name": "6cb9bf192222", "transfer-encoding": "chunked", "x-clickhouse-query-id": "fac6bad3-27bf-42a9-9835-e79d0759b4d8", "x-clickhouse-format": "TabSeparated", "x-clickhouse-timezone": "UTC", "x-clickhouse-exception-code": "117", "keep-alive": "timeout=3", "x-clickhouse-summary": "{\"read_rows\":\"0\",\"read_bytes\":\"0\",\"written_rows\":\"0\",\"written_bytes\":\"0\",\"total_rows_to_read\":\"0\"}"}, body: b"Code: 117, e.displayText() = DB::Exception: Unknown field found while parsing JSONEachRow format: msg.line: (at row 1)\n (version 21.3.3.14 (official build))\n" }
```

### Proposal

Support https://clickhouse.tech/docs/en/faq/integration/json-import/#useful-settings client side settings in Vector's config for Clickhouse sink. I'm not exactly sure, but I believe the change has to be done somewhere here: https://github.com/timberio/vector/blob/6e37d6180dd675aab0bbb996a7a30731ad4049cf/src/sinks/clickhouse.rs#L167

**Comment by pachico** [comment]
It states that it works when the insert format is JSON.
Does this apply to how this sink works?

**Comment by mr-karan** [comment]
It does, I believe. The sink sends the logs as `JSONEachRow` format, which is what their example in the docs show too:

> $ echo '{"foo":"bar"}'  | clickhouse-client --query="INSERT INTO test FORMAT JSONEachRow"

**Comment by mr-karan** [comment]
Bumped into this again. I'm using a `route` transform and added a top level metadata field for K8s namespace, which is not a part of the CH table schema. Not having that setting configurable, makes it impossible to have extra metadata and have to delete any such fields before the sink is reached.

**Comment by Shogobg** [comment]
I can confirm this. A few weeks ago, I was evaluating Clickhouse with Vector and at that time I had to include `only_fields` on my output, because i didn't want to re-create the whole schema of my event in Clickhouse.

**Comment by spencergilbert** [comment]
This should be configurable now with the new `skip_unknown_fields` config option in the sink. Should be available on the next nightly.

**Comment by mr-karan** [comment]
Tried this today with `nightly • 2021-06-23`:

`skip_unknown_fields = true`

Works well. Thanks for this! :+1:
