### ISSUE TITLE
New `apache_pulsar` sink

### ISSUE THREAD

**Issue by KannarFr** [timberio/vector#690]
Apache Pulsar is an open-source distributed pub-sub messaging system originally created at Yahoo and now part of the Apache Software Foundation.

It will be very cool to have a Sink to push Vector output to pulsar.

refs:
* apache pulsar: https://pulsar.apache.org;
* pulsar rust client crate: https://crates.io/crates/r2d2_pulsar;
* pulsar rust client sources: https://github.com/wyyerd/pulsar-rs.

**Comment by binarylogic** [comment]
Nice! Thanks for requesting.

**Comment by ckdarby** [comment]
Also interested in this :+1:

**Comment by leshow** [comment]
I was poking around on this, reading through the `pulsar` crate. It looks like most `pulsar` methods require a `TaskExecutor`. I was looking for where this is available for sinks and the closest thing I could find was `SinkContext`, but it doesn't provide access to any `TaskExecutor`. Is that correct? The trait could be expanded perhaps by adding a method that provides a `TaskExecutor`?

**Comment by KannarFr** [comment]
@binarylogic Hi, can you answer to @leshow? (I allow myself to poke you to ensure you saw the message). Thanks a lot for your answer.

**Comment by LucioFranco** [comment]
@leshow taking a look, it seems that their implementation will need to be changed to support generic executors. I do not want to expose the tokio 0.1 `TaskExecutor` since we are going to be slowly upgrading so this means we will still need a generic executor. 

The proper solution here would be to write a wrapper executor.

```rust
pub trait Executor: futures::future::Executor + Clone + Send + Sync + 'static {}
impl<T: futures::future::Executor + Clone + Send + Sync + 'static> Executor for T {}

#[derive(Clone)]
struct TaskExecutor(Box<dyn Executor>);

impl futures::future::Executor for TaskExecutor {...}
```

This is basically how it should be done and it should be drop in and would allow anything that implements that Executor trait via the blanket impl. I think once this is done, then we can pass our own executor into that library and it should work.

**Comment by KannarFr** [comment]
@stearnsc @geal, fyi.

**Comment by stearnsc** [comment]
@leshow we're currently in the progress of upgrading pulsar to futures 0.3, so I'm holding off on releasing any breaking changes until then, but if you need this now, I think making the executor changes @LucioFranco suggested would be pretty straightforward, and I'd be happy to help you with them on a fork.

**Comment by LucioFranco** [comment]
@stearnsc I spent 20min looking at this, I opened a draft PR https://github.com/wyyerd/pulsar-rs/pull/56 that should work towards this, the only thing missing is threading through the correct traits and types. I don't have more time to continue working on this today (and for some reason rust-analyzer isn't working)  but happy to help review any changes you might want to make to this. If this is implemented we could then use this internally within vector.

**Comment by leshow** [comment]
I don't mind spending time on this as long as I can get some feedback! Happy to upgrade it when the next version of the pulsar create comes out also.

**Comment by LucioFranco** [comment]
@leshow cool! Feel free to continue my PR and ping me for feedback. If you're interested in writing up the sink also feel free to ping me on gitter and we can chat about how to do that :)

**Comment by KannarFr** [comment]
@leshow Hi, what is the current status?

**Comment by leshow** [comment]
I'm going to put up what I've got so far to try to get some feedback on the design sometime today. Stay tuned!
