### ISSUE TITLE
Add Kubernetes namespace to Kubernetes metadata

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#6905]
This was required by a user and I could not find an issue that covers this. We should ensure that the `kubernetes_logs` source includes namespace as part of the metadata.

**Comment by jszwedko** [comment]
@binarylogic is this different from the `pod_namespace`? We do include that already: https://vector.dev/docs/reference/configuration/sources/kubernetes_logs/#kubernetespod_namespace

**Comment by binarylogic** [comment]
I think it is slightly different. @lukesteensen was on the call as well so maybe he can clarify here.

**Comment by lukesteensen** [comment]
My understanding was that they want to use the k8s namespace to determine the `index` in the Splunk HEC sink, which looks like it should possible as of #5418 but might not be documented? They also mentioned `source` and `source_type` as fields they want to be able to iterpolate.

**Comment by jszwedko** [comment]
Aha, gotcha. All three of those are actually already templatable, but it does look like that is not documented. I'll open a PR to document.

Should we close this issue then?

**Comment by jszwedko** [comment]
Documentation PR: https://github.com/timberio/vector/pull/6906

**Comment by lukesteensen** [comment]
Yeah I think we're good then!
