### ISSUE TITLE
Allow hashing arbitrary fields in VRL to fingerprint

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#6919]
Logstash provides a fingerprint filter that is useful to generate the unique document `_id` for Elasticsearch documents: https://www.elastic.co/guide/en/logstash/current/plugins-filters-fingerprint.html

Currently we support hashing strings in VRL (`sha1`, `md5`, `sha2`, etc.) which could be used for the same purposes but is not quite as user friendly for the specific purpose of ES ids which often involves hashing some subset of the fields of an event.

I think there are two options:

* Expand our hashing functions to also take a list of fields and hash them. For example: `sha1([.foo, .bar])`
* Add a special purpose `fingerprint` function that implements similar functionality to logstash

This also requires https://github.com/timberio/vector/issues/4479 to be usable.

**Comment by binarylogic** [comment]
Also related #4478.

**Comment by jszwedko** [comment]
Aha, I missed that one somehow. I think they represent the same issue so I'll close this one.
