### ISSUE TITLE
Expose `max_line_bytes` for `kubernetes_logs`

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#6966]
Requested by user.

The `kubernetes_logs` hardcodes `max_line_bytes` at 32 KiB. We should expose this as configuration on the `kubernetes_log` source:

https://github.com/timberio/vector/blob/a7d3f047dbfc2ca2df1fa56ae187d504e8113c8a/src/sources/kubernetes_logs/mod.rs#L259

I'm also noting that the comment there indicates that the chosen `max_line_bytes` was expected to cover all valid k8s log lines but it seems like it is not. This default may need to be revised. For reference, the user is using GKE.

**Comment by jszwedko** [comment]
Got some more info, their offending log was `39223` bytes long, the `39067` bytes of which was the log event itself.

**Comment by MOZGIII** [comment]
I suggest increasing the default. The 32KB value was chosen as a rough double of the 16k - which is supposed to be the limit of the logline length before the cut. Seems like the limit is in the characters at the UTF-8 coding though, so doubling is not enough.
I suggest using `6 * 16 * 1024` as the new default.
