### ISSUE TITLE
`kubernetes_logs` hardcoded max_line_bytes is too low

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#6967]
Related to https://github.com/timberio/vector/issues/6966

A user reported they had a log line that was 39223 bytes long 39067 bytes of which was the log event itself, which seems to indicate that the assumption mentioned in https://github.com/timberio/vector/blob/a7d3f047dbfc2ca2df1fa56ae187d504e8113c8a/src/sources/kubernetes_logs/mod.rs#L254-L258

Is not valid.

**Comment by jszwedko** [comment]
Closing this since we don't have a reproducible case at present. If anyone else runs into this, please share!

**Comment by portante** [comment]
Looking at the CRI-O code, really [`conmon`](https://github.com/containers/conmon/blob/main/src/ctr_logging.c), it does not appear to limit the length of a log line.  The `read(2)` buffer used when reading from the pipe is 8KB, so each partial record in the file could be 8KB in size (which would be 8KB + 46 bytes + 1 added trailing new line per record in the container log file).

See also https://github.com/containers/conmon/issues/262.

**Comment by jszwedko** [comment]
Aha, interesting, thank you @portante

By 

> The `read(2)` buffer used when reading from the pipe is 8KB, so each partial record in the file could be 8KB in size (which would be 8KB + 46 bytes + 1 added trailing new line per record in the container log file)

Do you mean that the partial lines are written to the file in 8 KB chunks with a boolean flag that the event continues (as docker does)? Or something else?

**Comment by portante** [comment]
> Do you mean that the partial lines are written to the file in 8 KB chunks with a boolean flag that the event continues (as docker does)? Or something else?

A log record in a CRI-O log file looks like:

```
1997-03-25T13:20:42.999999999+01:00 stdout P ... 8192 bytes ...\n
         ^         ^         ^         ^   ^ ^
12345678901234567890123456789012345678901234567890 ...
         1         2         3         4   4 4
```

At byte 44 you'll see a capital `P`, indicating it is a "partial" log line, which means the newline (`\n`) at the end of the line is not part of the log record.  Byte 46 is where the actual bytes of the log payload begin.

So that including the newline, you have 8,192 + 45 + 1 = 8,238 bytes per line in the file.

**Comment by jszwedko** [comment]
Aha, gotcha, thanks for clarifying! It seems like the default max line length we have of 16 K should cover this case then.

**Comment by portante** [comment]
Only if the original log line emitted was 16 KB or less.  Otherwise, parts of the long log line will be separate ... which is understandable.

**Comment by anas-aso** [comment]
I faced this issue also. Even with a 64K.
