### ISSUE TITLE
Tutorial on Loki failed

### ISSUE THREAD

**Issue by japaniel** [timberio/vector#6979]
The tutorial on:

https://vector.dev/guides/integrate/sinks/loki/#next-steps
Here's what went wrong:

There is no information about Loki itself. I do see some text at the bottom what looks to be some templating artifact: `[urls.vector_website]:`  but doesn't seem like it would indicate more information about Loki if it did render to a link.

**Comment by jszwedko** [comment]
Closing since this section doesn't exist anymore.
