### ISSUE TITLE
Supplementary config files are replaced during each deb package update

### ISSUE THREAD

**Issue by nnz1024** [timberio/vector#6987]
When Vector is installed from deb package, on each package update supplementary configuration files `/etc/systemd/system/vector.service` and `/etc/default/vector` are replaced by stock versions without any notice. Tested on Debian Buster and Ubuntu 18.04.

### Vector Version

```
vector 0.12.2 (v0.12.2 x86_64-unknown-linux-gnu 2021-03-30)
```

### Expected Behavior

```
test:~# cat /etc/default/vector 
# /etc/default/vector
# This file can theoretically contain a bunch of environment variables
# for Vector.  See https://vector.dev/docs/setup/configuration/#environment-variables
# for details.
TEEST=tost
test:~# apt update              
...
test:~# apt install vector
...
The following packages will be upgraded:
  vector
1 upgraded, 0 newly installed, 0 to remove and 87 not upgraded.
...
test:~# cat /etc/default/vector 
# /etc/default/vector
# This file can theoretically contain a bunch of environment variables
# for Vector.  See https://vector.dev/docs/setup/configuration/#environment-variables
# for details.
TEEST=tost
```

I expect that configuration files must not be changed during package update without explicit approve by user, and any local changes will persist (`TEEST` env var, for example).

### Actual Behavior

```
test:~# cat /etc/default/vector 
# /etc/default/vector
# This file can theoretically contain a bunch of environment variables
# for Vector.  See https://vector.dev/docs/setup/configuration/#environment-variables
# for details.
TEEST=tost
test:~# apt update              
...
test:~# apt install vector
...
The following packages will be upgraded:
  vector
1 upgraded, 0 newly installed, 0 to remove and 87 not upgraded.
Need to get 16.1 MB of archives.
After this operation, 50.5 MB disk space will be freed.
Get:1 https://repositories.timber.io/public/vector/deb/ubuntu bionic/main amd64 vector amd64 0.12.2 [16.1 MB]
Fetched 16.1 MB in 2s (8,730 kB/s) 
(Reading database ... 151414 files and directories currently installed.)
Preparing to unpack .../vector_0.12.2_amd64.deb ...
Unpacking vector (0.12.2) over (0.11.1) ...
Setting up vector (0.12.2) ...

Configuration file '/etc/vector/vector.toml'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** vector.toml (Y/I/N/O/D/Z) [default=N] ? N
test:~# cat /etc/default/vector 
# /etc/default/vector
# This file can theoretically contain a bunch of environment variables
# for Vector.  See https://vector.dev/docs/setup/configuration/#environment-variables
# for details.
```

Main config `/etc/vector/vector.toml` is properly marked as a configuration file, and package manager asks for overriding it during update. However, files `/etc/systemd/system/vector.service` and `/etc/default/vector` was silently overridden (note the missing line `TEEST=tost` after package update), which is an incorrect behavior IMHO.

### Additional Context

Vector is installed/updated from public Timbe.io repository
```
test:~# cat /etc/apt/sources.list.d/repositories_timber_io_public_vector_deb_ubuntu.list
deb https://repositories.timber.io/public/vector/deb/ubuntu bionic main
test:~# apt-cache policy vector
vector:
  Installed: 0.12.2
  Candidate: 0.12.2
  Version table:
 *** 0.12.2 500
        500 https://repositories.timber.io/public/vector/deb/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     0.12.1 500
        500 https://repositories.timber.io/public/vector/deb/ubuntu bionic/main amd64 Packages
     0.12.0 500
        500 https://repositories.timber.io/public/vector/deb/ubuntu bionic/main amd64 Packages
     0.11.1 500
        500 https://repositories.timber.io/public/vector/deb/ubuntu bionic/main amd64 Packages
     0.11.0 500
        500 https://repositories.timber.io/public/vector/deb/ubuntu bionic/main amd64 Packages
```

### Proposed solution

This problem must be easy to fix, by adding `/etc/systemd/system/vector.service` and `/etc/default/vector` to list [`package.metadata.deb.conf-files`](https://github.com/timberio/vector/blob/414f33f9aad407bab9b0664b8c1d65864b8c118a/Cargo.toml#L30) in Cargo.toml

**Comment by jszwedko** [comment]
Thanks for reporting this @nnz1024 ! I opened #7007 so that it will prompt before overwriting `/etc/default/vector`.

For the systemd config, I actually moved that to `/lib/systemd/system` as part of #7007 as this seems to be a more appropriate place for packages to install their systemd unit files. `/etc/systemd/system` appears to be for system admins to write their own system specific systemd configuration. This file will continue to be overwritten if modified, but can be overridden by creating supplementary unit config files (`systemd edit vector`) that will be merged with the package config.

Let me know if this addresses your issue!

**Comment by nnz1024** [comment]
Thanks @jszwedko! Just tested nightly deb package.
Looks like moving systemd config file introduced some side effect — removing `/etc/systemd/system/vector.service` during upgrade.

For example, we have Vector 0.12.2 installed from repo, and update it to [nightly](https://packages.timber.io/vector/nightly/2021-04-06/vector-nightly-amd64.deb) with `dpkg -i`:
```
test:~# cat /etc/systemd/system/vector.service
# Some nice custom config file
[Unit]
Description=Vector
Documentation=https://vector.dev
After=network-online.target
Requires=network-online.target
Before=haproxy.service

[Service]
User=vector
Group=vector
ExecStartPre=/usr/bin/vector validate
ExecStart=/usr/bin/vector
ExecReload=/usr/bin/vector validate
ExecReload=/bin/kill -HUP $MAINPID
EnvironmentFile=-/etc/default/vector

Restart=always
RestartSec=2
TimeoutStopSec=5
StartLimitInterval=0

CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
LockPersonality=true
NoNewPrivileges=true
PrivateDevices=true
PrivateTmp=true
ProtectControlGroups=true
ProtectHome=true
ProtectKernelModules=true
ProtectKernelTunables=true
ProtectSystem=full
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX
RestrictNamespaces=true
RestrictRealtime=true

[Install]
WantedBy=multi-user.target

test:~# dpkg -i vector-nightly-amd64.deb 
(Reading database ... 151414 files and directories currently installed.)
Preparing to unpack vector-nightly-amd64.deb ...
Unpacking vector (0.13.0) over (0.12.2) ...
Setting up vector (0.13.0) ...
test:~# cat /etc/systemd/system/vector.service 
cat: /etc/systemd/system/vector.service: No such file or directory
```

I think moving this file to `/lib` is pretty right step. However, it looks like dpkg says "hmm, /etc/systemd/system/vector.service file was present in old version of package and not present in current, let's remove it".

I'm not big in Cargo's deb packaging features, but there must be some way to prevent this.

**Comment by jszwedko** [comment]
@nnz1024 thanks for taking a look!

We could try to maintain the existing file so dpkg won't delete it, but I'm unsure if this is even possible given that the version of the vector deb that installed that file did not mark it as a conf file. I'll make sure we call it out in the next release though so people are aware of the change.
