### ISSUE TITLE
Allow the root object (`.`) in Remap to be an array

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#6988]
A few users have noted the ability to "explode" an event into many events. This could be solved with #6330, but isn't the best solution for events where the user doesn't know how many items are in the array. Therefore, we should allow users to set `.` to an array, and if `.` results in an array at the end of execution we should emit each as individual events.

**Comment by jszwedko** [comment]
I didn't realize this was already assigned, I was planning on working on this today. Hopefully that's ok @FungusHumungus 😄

**Comment by FungusHumungus** [comment]
> I didn't realize this was already assigned, I was planning on working on this today. Hopefully that's ok @FungusHumungus 😄 

Yup, fine by me!

**Comment by jszwedko** [comment]
Closing this in-lieu of https://github.com/timberio/vector/issues/6330 which I think is a more agnostic issue for emitting multiple events since we aren't 100% sure how we'll do it yet.
