### ISSUE TITLE
Update `x86_64-unknown-linux-musl` image with released versions of the compilers

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#700]
Currently, to support LTO across `clang` and `rustc` we depend on a couple unreleased versions of `rustc` and of `libressl`.

- [x] Update the image to use stable `rustc 1.38` ([reference](https://github.com/timberio/vector/pull/689/files#diff-83d6ef9eeb865202079fa6cad3096777R3))
- [x] Update to a `libressl` version `>2.9.2` ([reference](https://github.com/timberio/vector/pull/689/files#r308750034))

Reference PR with comments

**Comment by a-rodin** [comment]
This was done in #945 (stable Rust) and #927 (replaced LibreSSL by OpenSSL).

**Comment by LucioFranco** [comment]
@a-rodin thanks for doing this!
