### ISSUE TITLE
Makefile target 'test-integration-nginx' doesn't work

### ISSUE THREAD

**Issue by j-bai** [timberio/vector#7016]
### Vector Version

```
vector 0.13.0 (gd889d5f x86_64-unknown-linux-gnu 2021-04-02)
```

### Vector Configuration File

```toml
...
```

### Expected Behavior

Run command `make test-integration-nginx`, and all 4 tests under `sources::nginx_metrics` should be executed:

> running 4 tests
> test sources::nginx_metrics::parser::tests::nginx_stub_status_try_from ... ok
> test sources::nginx_metrics::tests::generate_config ... ok
> test sources::nginx_metrics::integration_tests::test_stub_status_auth ... ok
> test sources::nginx_metrics::integration_tests::test_stub_status ... ok
> 
> test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 255 filtered out; finished in 0.08s

### Actual Behavior

Run command `make test-integration-nginx`, and no tests were executed:

>running 0 tests
> 
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 1211 filtered out; finished in 0.00s

### Additional Context
Currently, makefile target `test-integration-nginx` will run following command to execute tests:
>	${MAYBE_ENVIRONMENT_EXEC} cargo test --no-fail-fast --no-default-features --features nginx-integration-tests --lib ::nginx:: -- --nocapture

Obviously, the test name matching pattern `::nginx::` is wrong. It should be `::nginx_metrics::` instead.

**Comment by jszwedko** [comment]
Indeed it is, thanks @j-bai

**Comment by j-bai** [comment]
Thanks for the quick fix, @jszwedko 👍
