### ISSUE TITLE
VRL Contains function wrong case_sensitive default value

### ISSUE THREAD

**Issue by SyluxDX** [timberio/vector#7044]
On the [Contains Documentation](https://vector.dev/docs/reference/vrl/functions/#contains) states that the default value for the case_sensitive argument is `True` but when testing the actual default value is `False`

### Vector Version
```
0.12.2
```

### Expected Behavior

```
$ contains("The Needle In The Haystack", "Needle")
true

$ contains("The Needle In The Haystack", "needle")
false
```

### Actual Behavior

```
$ contains("The Needle In The Haystack", "Needle")
true

$ contains("The Needle In The Haystack", "needle")
true
```

### Example using event

```
$ .message
"4.46.4.m.prod-b [15467.608359] ### Error at magnum/portinginterface/hdm/src/common/bhdm_hdcp.c:375"

$ contains!(.message, "error")
true

$ contains!(.message, "Error")
true

$ contains!(.message, "error", false)
true

$ contains!(.message, "error", true)
false
```

**Comment by SyluxDX** [comment]
After searching through the code for the function contains, the default value for case_sensitive is indeed `false`:
#### vector/lib/vrl/stdlib/src/contains.rs:
```
impl Expression for ContainsFn {
    fn resolve(&self, ctx: &mut Context) -> Resolved {
        let case_sensitive = match &self.case_sensitive {
            Some(expr) => expr.resolve(ctx)?.try_boolean()?,
            None => false,
        };
...
```

**Comment by spencergilbert** [comment]
@jszwedko is this just updating the documentation, or changing the default setting?

**Comment by jszwedko** [comment]
I think it's a bug and the documentation is correct. Or, at least, that would have been my expectation: that it would default to case-sensitive matching. This appears to be incorrectly defaulted for `ends_with` and `starts_with` as well.

**Comment by jszwedko** [comment]
Bump @binarylogic does this seem like the desired behavior to you?
