### ISSUE TITLE
Support enriching metrics with the `aws_ec2_metadata` transform

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#7082]
Requested by user in discord: https://discord.com/channels/742820443487993987/759154784309215252/830797070868414505

Currently this transform only supports log events.

**Comment by binarylogic** [comment]
Closing in favor of #1582. @jszwedko do you know which tags they'd want? Most of the tags here are high cardinality.

**Comment by jszwedko** [comment]
@binarylogic aha 👍 I missed that one. They were specifically interested in `instance-id`. This can be highish cardinality but it is fairly common, in my experience, to want to tag metrics from an instance with its id.
