### ISSUE TITLE
Retry all errors in `kubernetes_logs` source

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#7149]
Broken off from https://github.com/timberio/vector/pull/6816.

https://github.com/timberio/vector/pull/6816 added retrying of `hyper` level errors which includes things like connectivity issues, but we still have cases where we kill the reflector if we see an error. I'm not 100% sure what other conditions would cause unknown errors, but, when this happens, the `kubernetes_logs` component stops functioning, but Vector continues to run. This results in it silently failing to pick up logs.

We should either:

* Retry all errors that occur in the `Reflector`
* Restart the `Reflector` if a fatal error occurs
* Have Vector exit (least favorite option)

**Comment by eplightning** [comment]
Had this happen today when upgrading Kubernetes control plane:
```
May 06 12:06:58.709  INFO vector: Vector has started. version="0.13.0" git_version="v0.13.0" released="Wed, 21 Apr 2021 17:18:41 +0000" arch="x86_64"

...

May 06 16:11:14.509 ERROR source{component_kind="source" component_name=source-kubernetes component_type=kubernetes_logs}: vector::internal_events::kubernetes::instrumenting_watcher: Watch invocation failed. error=Other { source: K8sStream { source: Reading { source: hyper::Error(Body, Custom { kind: UnexpectedEof, error: "unexpected EOF during chunk size line" }) } } } internal_log_rate_secs=5
4
May 06 16:11:14.509 ERROR source{component_kind="source" component_name=source-kubernetes component_type=kubernetes_logs}: vector::sources::kubernetes_logs: Reflector process exited with an error. error=streaming error
3
May 06 16:11:14.509  INFO source{component_kind="source" component_name=source-kubernetes component_type=kubernetes_logs}: vector::sources::kubernetes_logs: Event processing loop completed gracefully.
2
May 06 16:11:14.509  INFO source{component_kind="source" component_name=source-kubernetes component_type=kubernetes_logs}: vector::sources::kubernetes_logs: File server completed gracefully.
1
May 06 16:11:14.509  INFO source{component_kind="source" component_name=source-kubernetes component_type=kubernetes_logs}: vector::sources::kubernetes_logs: Done.
```

It stopped processing K8s logs after that, requiring a manual restart. I guess it's related to this issue.

**Comment by jszwedko** [comment]
@eplightning thanks for noting. https://github.com/timberio/vector/pull/6816 was actually supposed to resolve that specific error so it seems like might still be missing something.

**Comment by jszwedko** [comment]
Copying my comment over here since I think it fits better: https://github.com/timberio/vector/pull/7484#issuecomment-844140480

> Errors that will still stop the kubernetes_logs source are:
> 
> 1. Errors that occur when building the TLS and Https connector.  In other words errors that occur (here)[https://github.com/timberio/vector/blob/master/src/http.rs#L55-L56]. I suspect these are pretty low level errors that indicate something has gone severely wrong.
> 2. Any HTTP response returned from the API server other than OK (200) or GONE (410). From what I can gather, the only call we make to the api is [`watch_pod_for_all_namespaces`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#list-all-namespaces-pod-v1-core). Looking at the docs, the implication is that the only return from this call is a 200, so it seems to me like any other return would imply a non recoverable error.

I think we can follow up on this, but, if these are really non-recoverable, we should make sure that vector exits. Right now, the behavior seems to be that vector continues to run, but the `kubernetes_logs` component stops which can be a difficult condition to detect for users.

**Comment by StephenWakely** [comment]
I'm going to close this issue in favour of #7527. Any discussion can continue there.
