### ISSUE TITLE
Determine if some of our tests can be "downgraded" from end-to-end to limited integration and/or unit tests

### ISSUE THREAD

**Issue by JeanMertz** [timberio/vector#7171]

**Comment by StephenWakely** [comment]
`simple_raw_config` can be removed now that raw_config has been deprecated.

https://github.com/timberio/vector/blob/master/lib/k8s-e2e-tests/tests/vector-agent.rs#L144

**Comment by spencergilbert** [comment]
> `simple_raw_config` can be removed now that raw_config has been deprecated.
> 
> https://github.com/timberio/vector/blob/master/lib/k8s-e2e-tests/tests/vector-agent.rs#L144

I figure I'd take it out when I _fully_ removed it with 0.15/whenever we remove it
