### ISSUE TITLE
`make check-events` fails on macOS

### ISSUE THREAD

**Issue by leebenson** [timberio/vector#7187]
Awk syntax error:

```
➜  vector git:(leebenson/provider) make check-events
./scripts/check-events.sh
awk: syntax error at source line 7
 context is
	  match($0, >>>  /(trace|debug|info|warn|error)!\(\s*(message\s*=\s*)?"([^({)][^("]+)"/, <<< 
awk: bailing out at source line 7
make: *** [check-events] Error 2
```

**Comment by jszwedko** [comment]
@leebenson could you post the output of `awk --version`? You may want to `brew install coreutils`.

**Comment by leebenson** [comment]
awk version 20200816

`coreutils` already installed; no joy, unfortunately.

**Comment by jszwedko** [comment]
@leebenson ah, apologies, I thought that was included in `coreutils` but it is a separate package: `brew install gawk`. That version does seem like the one bundled with OSX.

**Comment by leebenson** [comment]
That did the trick, thanks @jszwedko.
