### ISSUE TITLE
Allow HTTP headers to be templated for HTTP-based sinks

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#7189]
A user would like to template the value of an HTTP header in the `http` sink, however these are only allowed to be static strings.

Example:
```
request.headers.foo = "{{ bar }}"
```

This will require additional event partitioning.

**Comment by jalaziz** [comment]
I believe this is related to #201

**Comment by jszwedko** [comment]
Ah, yes it is, thank you @jalaziz . I'll close this in-lieu of #201
