### ISSUE TITLE
[VRL] `parse_timestamp()` function seems to be ignoring spaces in format

### ISSUE THREAD

**Issue by hhromic** [timberio/vector#7215]
### Vector Version

```
vector 0.13.0 (v0.13.0 x86_64-unknown-linux-gnu 2021-04-21)
```

### Expected Behavior

I expected the `parse_timestamp()` function to consider spaces in the `format` strictly. Examples:
```
$ parse_timestamp!("12/25/20 12:00:00", format: "%D %T")
t'2020-12-25T12:00:00Z'

$ parse_timestamp!("12/25/20-12:00:00", format: "%D - %T")
function call error for "parse_timestamp" at (0:56): Invalid timestamp "12/25/20-12:00:00": input contains invalid characters
```

### Actual Behavior

It seems that the `parse_timestamp()` function actually ignores whitespace around format specifiers when matching:
```
$ parse_timestamp!("12/25/2012:00:00", format: "%D %T")
t'2020-12-25T12:00:00Z'

$ parse_timestamp!("12/25/20 12:00:00", format: "%D    %T")
t'2020-12-25T12:00:00Z'

$ parse_timestamp!("  12/25/2012:00:00", format: "%D %T  ")
t'2020-12-25T12:00:00Z'
```

While the above seems convenient, it leads to incorrect results due to the ambiguity of the non-strict parsing:
```
$ parse_timestamp!("12/25/2 12:00:00", format: "%D %T")
t'2002-12-25T12:00:00Z'

$ parse_timestamp!("12/25/212:00:00", format: "%D %T")
t'2021-12-25T02:00:00Z'
```

**Comment by jszwedko** [comment]
Interesting I was not aware of this lack of whitespace sensitivity. However, `strptime`, which is somewhat the standard for time parsing, specifies this behavior:

> All other characters in the format string must have a matching character in the input string, except for whitespace, which matches zero or more whitespace characters in the input string.  There should be whitespace or other alphanumeric characters between any two field descriptors.

https://man7.org/linux/man-pages/man3/strptime.3.html

I imagine [`chrono`](https://docs.rs/chrono/0.4.19/chrono/format/strftime/index.html), the time parsing library we use, chose to maintain this behavior.

**Comment by hhromic** [comment]
@jszwedko interesting indeed. I wasn't aware of that in standard `strptime()` either. I did a quick test using Python's own `strptime()` and to my surprise it behaves similarly, with the exception that it doesn't like zero whitespace:
```python
strptime("2021/12/25    12:30:45", "%Y/%m/%d %H:%M:%S")
# time.struct_time(tm_year=2021, tm_mon=12, tm_mday=25, tm_hour=12, tm_min=30, tm_sec=45, tm_wday=5, tm_yday=359, tm_isdst=-1)
strptime("2021/12/25    12:30:45", "%Y/%m/%d  %H:%M:%S")
# time.struct_time(tm_year=2021, tm_mon=12, tm_mday=25, tm_hour=12, tm_min=30, tm_sec=45, tm_wday=5, tm_yday=359, tm_isdst=-1)
strptime("2021/12/25 12:30:45", "%Y/%m/%d  %H:%M:%S")
# time.struct_time(tm_year=2021, tm_mon=12, tm_mday=25, tm_hour=12, tm_min=30, tm_sec=45, tm_wday=5, tm_yday=359, tm_isdst=-1)
strptime("2021/12/2512:30:45", "%Y/%m/%d %H:%M:%S")
# ValueError: time data '2021/12/2512:30:45' does not match format '%Y/%m/%d %H:%M:%S'
```

But nevertheless, if Vector is delegating the time-parsing to a third-party library which has this behaviour, then I think is not really the fault of Vector in this case. Therefore I will close this issue 👍

I guess the lesson learned here is to be careful with the whitespace then in `strptime()`-like formats.

**Comment by jszwedko** [comment]
Even more interesting! Thanks for bringing it up @hhromic

If anything, I think this would manifest as an attempted upstream change to `chrono` to allow two modes of parsing (strict or lenient).
