### ISSUE TITLE
horizontal scrolling in documentation

### ISSUE THREAD

**Issue by karlseguin** [timberio/vector#7231]
https://vector.dev/docs/reference/vrl/functions/ has horizontal scrolling (at least in both Firefox and Chrome). It really messes up trying to search through the document.

It's `.remap-entity.remap-entity--custom-header > h3`  which has a `position:absolute; right: -999em`

**Comment by jszwedko** [comment]
Oh wow, yeah it does. I never noticed that.

**Comment by jszwedko** [comment]
I fixed this in the website repo. It should go out with the next release.
