### ISSUE TITLE
unflatten MapValue::Null is serialized to string instead `null`

### ISSUE THREAD

**Issue by MarkusH** [timberio/vector#724]
As part of #678 the `MapValue::Null` was added. The implementation of the `serde::Serialize` trait creates a `"null"` string:
https://github.com/timberio/vector/blob/e267f72beda5092984b0f6b4c92fb785037419b9/src/event/unflatten.rs#L186-L198

However, as far as my understanding goes, `"null"` and `null` are different. As such, I think `MapValue::Null` should map to `serializer.serialize_none()`.

**Comment by lukesteensen** [comment]
Thanks for catching this!
