### ISSUE TITLE
Create listings for directories on packages.timber.io

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#729]
Accessing URLs like https://packages.timber.io/vector/ or http://packages.timber.io/vector/0.3.0/ returns default 404 page generated by S3.

For example, [kernel.org](https://cdn.kernel.org/pub/linux/kernel/v5.x/) or [rust-lang.org](https://static.rust-lang.org/dist/2019-08-08/) show directory listings for downloads.

I think using S3 it might be achieved by generating static `index.html` files with listings for each folder and setting them to be corresponding [index documents](https://docs.aws.amazon.com/AmazonS3/latest/dev/IndexDocumentSupport.html).

**Comment by binarylogic** [comment]
Thanks. I'm working on our release process this week and will try to add this.

**Comment by binarylogic** [comment]
This is resolved: https://packages.timber.io/vector
