### ISSUE TITLE
More native/secure way to add the Vector repo on Debian

### ISSUE THREAD

**Issue by ypid** [timberio/vector#7291]
### Use-cases

The [suggested way to install Vector on Debian](https://vector.dev/docs/setup/installation/operating-systems/debian/) involves running a custom Bash script which is not verified by a cryptographic signature (other than HTTPS) as Apt would do. Also the key distribution is not ideal. Users have to trust that the webserver that serves the key or script is not compromised at the time of adding the repo.

### Attempted Solutions

[Extrepo](https://salsa.debian.org/extrepo-team/extrepo) exists to address this problem. It has the advantage of being in Debian (and Ubuntu) so there is a trust chain for the user that can be publicly reviewed.

I prepared the required metadata here: https://salsa.debian.org/ypid/extrepo-data/-/blob/add/vector/repos/debian/vector.yaml In the future, Extrepo could handle other distros like Ubuntu as well.

If that is fine for you, I would like to contribute it to https://salsa.debian.org/extrepo-team/extrepo-data

Edit: Done that after I got positive feedback in https://github.com/timberio/vector/issues/7291#issuecomment-830654492 as https://salsa.debian.org/extrepo-team/extrepo-data/-/merge_requests/80

### Proposal

If you think Extrepo is useful or at some later point, when more distros are supported, the Vector docs could be updated. But that does not need to happen now. This issue could be closed after discussion and later be reconsidered.

### References

* https://grep.be/blog/en/computer/debian/Announcing_extrepo/

**Comment by binarylogic** [comment]
Thanks @ypid, I definitely agree. We'll get this scheduled.

**Comment by ypid** [comment]
https://salsa.debian.org/extrepo-team/extrepo-data/-/merge_requests/80 has been merged. Only a small docs change is now left. I have not used the template system you are using to generate the docs so I am out for now. If you want to, you could add an alternative section like Jellyfin is considering it, ref: https://github.com/jellyfin/jellyfin-docs/pull/531

**Comment by jszwedko** [comment]
Awesome, thanks @ypid ! We'll get this added to the docs.
