### ISSUE TITLE
syslog source: support time format with milliseconds

### ISSUE THREAD

**Issue by kvitali** [timberio/vector#7315]
### Current Vector Version
0.10

### Use-cases

We use syslog source

### Proposal

Support timeformat param in syslog source that will contain millisecond precision format

**Comment by jszwedko** [comment]
Hi @kvitali !

Can you confirm what format the syslog messages are in? RFC3164 or RFC5432? Or could you provide an example message?

I tested that milliseconds are picked up by RFC5432 messages using the following config:

```toml
[sources.in]
type = "syslog"
address = "0.0.0.0:9514"
mode = "udp"

[sinks.out]
type = "console"
inputs = ["in"]
encoding.codec = "json"
```

And then sending a message via:

```
echo '<13>1 2021-05-04T14:00:49.882+00:00 a-8cktst39ij0a CORP\jesse - - [timeQuality tzKnown="1" isSynced="1" syncAccuracy="5910"] hello' | nc -u 127.0.0.1 9514```

In vector's output I saw:

```
{"appname":"CORP\\jesse","facility":"user","host":"a-8cktst39ij0a","hostname":"a-8cktst39ij0a","message":"hello","severity":"notice","source_ip":"127.0.0.1","source_type":"syslog","timeQuality":{"isSynced":"1","syncAccuracy":"5910","tzKnown":"1"},"timestamp":"2021-05-04T14:00:49.882Z","version":1}
```

(including the milliseconds)

I did note that `RFC3164` messages do not pick up milliseconds:

```
echo '<13>May  4 14:03:14.123 a-8cktst39ij0a CORP\jesse: hello' | nc -u 127.0.0.1 9514
```

Output:

```
{"facility":"user","host":"127.0.0.1","message":".123 a-8cktst39ij0a CORP\\jesse: hello","severity":"notice","source_ip":"127.0.0.1","source_type":"syslog","timestamp":"2021-05-04T14:03:14Z"}
```

However, I also noted that RFC3164 specifies that timestamps only have seconds: https://tools.ietf.org/html/rfc3164#section-4.1.2

**Comment by kvitali** [comment]
Hi,

I tried to reproduce your step and got exactly same results.
Apparently our syslog sends the timestamp without the milliseconds:

`<14>May  4 15:13:20 ip-172-16-16-197 health-checker/0ad2c0ac2e07[1295 time="2021-05-04T15:13:20Z" level=info msg="TCP connection to port 443 successful"
`

I will try to switch to RFC5432 format.

**Comment by kvitali** [comment]
I switched syslog forwarding format to rfc5424 format and now I see the milliseconds in vector.
Thank you @jszwedko
