### ISSUE TITLE
Vector's logs are noisy when using load balancer SYN/SYN-ACK healthchecks

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#7318]
User reported that they saw noisy logs when setting up a load balancer with Vector that used syn/syn-ack healchecks due to the TCP connection terminating early:

```
May 03 18:07:48.492  WARN source{component_kind="source" component_name=vector_to_vector component_type=vector}:connection{peer_addr=10.0.213.137}: vector::internal_events::tcp: Connection error. error=TLS handshake failed: the handshake failed: unexpected EOF internal_log_rate_secs=10
May 03 18:07:48.797  WARN source{component_kind="source" component_name=vector_to_vector component_type=vector}:connection{peer_addr=10.0.213.137}: vector::internal_events::tcp: Internal log [Connection error.] is being rate limited.
```

I'm not sure what the ideal behavior is here. We should take a look at how other agents handle this.

**Comment by jszwedko** [comment]
Note this can be reproduced via `nc -vz localhost 4000`

**Comment by ktff** [comment]
We can for this exact situation downgrade the log to `debug` and if the rate of the error is greater than some limit after the `internal_log_rate_secs` expires we then also log it as a warning. @jszwedko what do you think? From what I found it seems logstash has something similar.

**Comment by jszwedko** [comment]
@ktff interesting, do you have a link to how logstash is handling it? That seems sensible though I'd also be ok with just downgrading it to debug if adding the additional warning is substantial work.

**Comment by ktff** [comment]
@jszwedko  https://github.com/logstash-plugins/logstash-input-tcp/issues/132 seemed like the same issue, but after running logstash with ssl config and `nc -vz localhost 4000` it didn't log anything of the kind on any level. 

fluentd reports the same warning as we do.
```
2021-06-04 15:40:32 +0200 [warn]: #0 unexpected error before accepting TLS connection by OpenSSL host="127.0.0.1" port=43216 error_class=OpenSSL::SSL::SSLError error="SSL_accept SYSCALL returned=5 errno=0 state=before SSL initialization"
```

With that said, just downgrading it to debug seems like ok compromise.

**Comment by jszwedko** [comment]
👍 agreed, I think downgrading to debug seems like a decent compromise here.
