### ISSUE TITLE
Ability to compress individual messages in sinks

### ISSUE THREAD

**Issue by erikbos** [timberio/vector#734]
Introduce transform capability to compress payload before it goes to the sink.

**Comment by binarylogic** [comment]
Hi @erikbos, thanks for the issue 👍 . Just to clarify, we try to provide an `encoding` and `compression` option for any sinks that supports them. We're working on expanding support. Are there specific sinks you need this for?

Part of the reason we can't make compression a transform is that individual events flow into a buffer before reaching the sink. In addition, some sinks require access to event attributes as part of partitioning (ex: partitioning events into time based partitions on s3).

**Comment by lukesteensen** [comment]
Yeah, I'm not sure how useful this would be given that it' could only compress individual events one at a time. Unless there's a use case I'm missing, I'd much prefer that we keep compression as a sink-level concern.

**Comment by binarylogic** [comment]
Closing in favor of https://github.com/timberio/vector/issues/1411
