### ISSUE TITLE
Unit tests broken

### ISSUE THREAD

**Issue by splitice** [timberio/vector#7355]
### Vector Version

vector 0.13.1 (v0.13.1 x86_64-unknown-linux-gnu 2021-04-29)

### Vector Configuration File
https://vector.dev/docs/reference/configuration/tests/

### Additional Context

I recently got back into vector after taking a break to let the project mature. After doing some basic upgrades to the configuration format to reflect the non-backwards compatible changes I noticed all my unit tests were failing.

I then went and checked over the unit test formats and noted even the example provided is broken currently.

After filling out required fields from the provided example you get:
```invalid type: map, expected a sequence for key `tests.outputs.conditions` at line 14 column 21.```

**Comment by jszwedko** [comment]
We plan to take a fresh look at the unit test docs in the next couple of months to update to use `remap` among other things. We'll plan to address this as part of that work.

**Comment by splitice** [comment]
@jszwedko in the mean time have you got a working example for unit tests?

Both my original style and the current documentation style return errors.

**Comment by jszwedko** [comment]
@splitice 👍 you can see some examples that we run in CI in https://github.com/timberio/vector/tree/master/tests/behavior

I think your existing unit tests should work if you add `type = "check_fields"`. The new default is `"remap"`.

**Comment by jszwedko** [comment]
Superseded by https://github.com/timberio/vector/issues/7832
