### ISSUE TITLE
New `aws_ec2_metadata` transform

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#736]
We need a way to enrich events with [EC2 instance metadata](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html). You'll notice this API has a lot of data, and to start we should keep things simple.

## Prior art

- <https://github.com/takus/fluent-plugin-ec2-metadata>
- <https://www.elastic.co/guide/en/beats/metricbeat/current/add-cloud-metadata.html>

## Configuration

There are a number of ways we could go with this. I propose the following simple options:

```
[transforms.my_transform_id]
  type = "aws_ec2_metadata"
  fields = ["instance-id", "local-hostname", "local-ipv4", "public-hostname", "public-ipv4"] # default
  namespace = "aws.ec2" # optional, no default
```

### `fields`

This is a white list of fields to add. The example represents the default list, but the user can override it. To start, I think we should keep things simple and only support the following fields:

- `ami-id`
- `availability-zone` via `placement/availability-zone`
- `instance-id`
- `local-hostname`
- `local-ipv4`
- `public-hostname`
- `public-ipv4`
- `region`
- `role-name` via `/iam/security-credentials/role-name
- `subnet-id` via `network/interfaces/macs/mac/subnet-id`
- `vpc-id` via `network/interfaces/macs/mac/vpc-id`

### `namespace`

The `namespace` field prefixes the added metadata fields with the value provided. The default is no namespace, but if a `namespace` is provided it should be delimited with a `.`. Ex:

- Not provided => no namespace

- `aws` => `aws.*`
- `aws.ec2` => `aws.ec2.*`
- `aws_ec2.` => `aws.ed2..*`

## Output

A shown above, the `fields` option represents a white list of fields to add. The fields are added to the root of the event like so:

```
{
  // ...
  "instance-id": "...",
  "local-hostname": "...",
  "local-ipv4": "...",
  "public-hostname": "..."
  // ...
}
```

And if the user provides a `namespace` value, then the metadata fields would be added under that namespace:

```
{
  // ...
  "aws.ec2.instance-id": "...",
  "aws.ec2.local-hostname": "...",
  "aws.ec2.local-ipv4": "...",
  "aws.ec2.public-hostname": "..."
  // ...
}
```

You'll notice that the `.` character is allowed. This represents nesting as described in our [log data model doc](https://docs.vector.dev/about/data-model/log#nested-keys).

### Renaming fields

The user should pair this with another transform designed to rename fields.

## Open questions

1. Are there any special permissions required to access this data? Ex: does the `vector` process need to be in a certain group with read access to this data? Are IAM policies required?

2. Adding instance tags would be very powerful, but this would require a `describe_instance` call against the AWS API. I do not think we should include this in the scope of the first version unless someone is aware of a light weight strategy for this.

3. How could this transform be applied to both logs and metrics? I assume the fields here could be added as `labels` (or `tags`) on metrics. This might require a larger discussion around field management in general. (related https://github.com/timberio/vector/issues/524)

**Comment by binarylogic** [comment]
Link to feature: https://timber.productboard.com/feature-board/planning/features/2645274

**Comment by kapilt** [comment]
fwiw an additional corollary endpoint for ecs containers is https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint-v3.html

re questions
1. none at the moment (8/2019)
2. agreed, having every instance describe themselves to get tags periodically is a ddos recipe in a busy/large environment
3. another useful metric label/tag would be the instance role name if present
`/iam/security-credentials/role-name`

**Comment by binarylogic** [comment]
Thanks @kapilt, that's helpful. I was not aware of the ecs endpoint.

**Comment by lukesteensen** [comment]
> 3. How could this transform be applied to both logs and metrics?

At least until we've done a deeper investigation of the possiblity of a more unified fields/tags model, we should build this primarily as an independent module and expose it through separate log and metrics transform wrappers.

**Comment by LucioFranco** [comment]
@binarylogic I don't think `/iam/security-credentials/role-name` is correct, from reading this doc https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html it seems that this expects you to provide a role name and if it is present it will return the security credentials, I don't think this is what you were expecting when you wrote up this issue, could you verify?

**Comment by jszwedko** [comment]
Just a note that AWS recently added a more secure way of interacting with the metadata service that might be useful to support (and/or provide support for both modes):

https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/

**Comment by LucioFranco** [comment]
@jszwedko yup the plan is to support that, mostly just seems like we need to track a token and refresh it on an interval. Otherwise, the actual metadata api should remain the same.

**Comment by LucioFranco** [comment]
Looking deeper, there are two endpoints `subnet-id` and `vpc-id` which are connected to the network interface. There can exist multiple of these on a system because of this how do we want to add them? Do we want to just choose the first one?

**Comment by lukesteensen** [comment]
> There can exist multiple of these on a system because of this how do we want to add them?

If there can be multiple I don't think it's correct to just pick whichever happens to show up first. Seems like we'd want to nest them under the name of the interface, right?

**Comment by LucioFranco** [comment]
So `public-ipv4` uses the first default mac address that comes from `latest/meta-data/mac`. So I guess they kinda already make that assumption? The rest are there if you want to fetch them I assume.
