### ISSUE TITLE
`datadog_logs` defaults are a bit conservative

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#7370]
A [user in discord](https://discord.com/channels/742820443487993987/746070591097798688/839914746521845770) reported very slow throughput of their `file` to `datadog_logs` pipeline; on the order of ~10 KiB/second.

After looking I discovered that our configuration for requests and batches on the `datadog_logs` source are a little conservative. It seems to default to:

* Batches of 1MB
* 5 concurrent requests
* 5 requests / second

Even with these, I would have expected a higher throughput than ~10 KiB / second though; unless the requests to Datadog are very slow (on the order of multiple seconds)

Also, these settings are not documented on https://vector.dev/docs/reference/configuration/sinks/datadog_logs/

I suggested they increase throughput by setting:

```
batch.max_bytes = 5242880 # max datadog allows https://docs.datadoghq.com/api/latest/logs/#send-logs
request.concurrency = "adaptive"
request.rate_limit_num = 1000
```

Which seemed to cause an improvement.

**Comment by jszwedko** [comment]
I tested with the following config:

```
data_dir = "/tmp/vector"

[sources.syslog_log]
  type               = "file"
  include            = ["/tmp/in.log"]

[sinks.myfile]
  type = "file"
  inputs = ["syslog_log"]
  compression = "none"
  path = "/tmp/out.log"
  encoding.codec = "ndjson" # required

[transforms.syslog_transform]
  type            = "add_fields"
  inputs          = ["syslog_log"]
  fields.hostname = "syslog-iad-2"
  fields.service  = "syslog"
  fields.ddsource = "vector-syslog"
  fields.ddtags   = "syslog,env:production,location:iad2"
#[sources.ldap_log]
  #type               = "file"
  #include            = ["/var/log/remote/ldap.json"]
  ##ignore_older       =  604800 # 1 week
#[transforms.ldap_transform]
  #type            = "add_fields"
  #inputs          = ["ldap_log"]
  #fields.hostname = "syslog-iad-2"
  #fields.service  = "ldap"
  #fields.ddsource = "vector-ldap"
  #fields.ddtags   = "ldap,env:production,location:iad2"
[sinks.datadog]
  type                = "datadog_logs"
  inputs              = ["syslog_transform"]
  api_key             = "db09e13af33f0c3f657c347f0185232a"
  compression         = "gzip"
  encoding.codec      = "json"
  healthcheck.enabled = true

[api]
  enabled = true

[sources.internal_metrics]
type = "internal_metrics"

[sinks.metrics]
type = "prometheus_exporter"
inputs = ["internal_metrics"]
address = "0.0.0.0:8567"
```

With this I saw roughly 500 KB/s being processed to Datadog.

If I added:

```
        batch.max_bytes = 5242880
        request.concurrency =  "adaptive"
        request.rate_limit_num = 1000
```

I was able to get 2 MB/s.

If I hardcoded the concurrency to 100 like:

```
        batch.max_bytes = 5242880
        request.concurrency =  100
        request.rate_limit_num = 1000
```

I was able to get 10 MB/s. This could indicate that the adaptive algorithm isn't finding the maximum.

`ioping` output:

```
--- /dev/xvdf1 (block device 200.0 GiB) ioping statistics ---
999 requests completed in 454.8 ms, 3.90 MiB read, 2.20 k iops, 8.58 MiB/s
generated 1 k requests in 474.5 ms, 3.91 MiB, 2.11 k iops, 8.23 MiB/s
min/avg/max/mdev = 254.1 us / 455.2 us / 3.16 ms / 168.9 us
```

I was able to get ~15 MB/s just going file-to-file though, which exceeds what ioping things I should be able to get.

**Comment by jszwedko** [comment]
I think this issue should represent:

* Updating the `request` default to use adaptive concurrency
* Updating the `batch.max_bytes` to 5 MB
* Documenting the existence of the `request` parameters in cue for the `datadog_logs` source

**Comment by bruceg** [comment]
Note that the default batch size appears to be limited to 20 events, which seems pretty tiny, no matter what the byte maximum is. https://github.com/timberio/vector/blob/7e90a2469f931ca601601221b9e6f35fe9350fa4/src/sinks/datadog/logs.rs#L100

**Comment by jszwedko** [comment]
I tested with the following config:

```
data_dir = "/tmp/vector"

[sources.syslog_log]
  type               = "file"
  include            = ["/tmp/in.log"]

[sinks.myfile]
  type = "file"
  inputs = ["syslog_log"]
  compression = "none"
  path = "/tmp/out.log"
  encoding.codec = "ndjson" # required

[transforms.syslog_transform]
  type            = "add_fields"
  inputs          = ["syslog_log"]
  fields.hostname = "syslog-iad-2"
  fields.service  = "syslog"
  fields.ddsource = "vector-syslog"
  fields.ddtags   = "syslog,env:production,location:iad2"
#[sources.ldap_log]
  #type               = "file"
  #include            = ["/var/log/remote/ldap.json"]
  ##ignore_older       =  604800 # 1 week
#[transforms.ldap_transform]
  #type            = "add_fields"
  #inputs          = ["ldap_log"]
  #fields.hostname = "syslog-iad-2"
  #fields.service  = "ldap"
  #fields.ddsource = "vector-ldap"
  #fields.ddtags   = "ldap,env:production,location:iad2"
[sinks.datadog]
  type                = "datadog_logs"
  inputs              = ["syslog_transform"]
  api_key             = ""
  compression         = "gzip"
  encoding.codec      = "json"
  healthcheck.enabled = true

[api]
  enabled = true

[sources.internal_metrics]
type = "internal_metrics"

[sinks.metrics]
type = "prometheus_exporter"
inputs = ["internal_metrics"]
address = "0.0.0.0:8567"
```

With this I saw roughly 500 KB/s being processed to Datadog.

If I added:

```
        batch.max_bytes = 5242880
        request.concurrency =  "adaptive"
        request.rate_limit_num = 1000
```

I was able to get 2 MB/s.

If I hardcoded the concurrency to 100 like:

```
        batch.max_bytes = 5242880
        request.concurrency =  100
        request.rate_limit_num = 1000
```

I was able to get 10 MB/s. This could indicate that the adaptive algorithm isn't finding the maximum.

`ioping` output:

```
--- /dev/xvdf1 (block device 200.0 GiB) ioping statistics ---
999 requests completed in 454.8 ms, 3.90 MiB read, 2.20 k iops, 8.58 MiB/s
generated 1 k requests in 474.5 ms, 3.91 MiB, 2.11 k iops, 8.23 MiB/s
min/avg/max/mdev = 254.1 us / 455.2 us / 3.16 ms / 168.9 us
```

I was able to get ~15 MB/s just going file-to-file though, which exceeds what ioping things I should be able to get.

**Comment by jszwedko** [comment]
> Note that the default batch size appears to be limited to 20 events, which seems pretty tiny, no matter what the byte maximum is.
> 
> https://github.com/timberio/vector/blob/7e90a2469f931ca601601221b9e6f35fe9350fa4/src/sinks/datadog/logs.rs#L100

Good catch, I'm wondering if we should even have a default for that one. Really it's the byte size that matters.

**Comment by spencergilbert** [comment]
I suspect this could be superseded by #8263. @jszwedko what do you think?

**Comment by jszwedko** [comment]
Yeah, I think that's fair. We can let these changes fall out of #8263
