### ISSUE TITLE
Support setting bulk action per event with Elasticsearch sink

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#7389]
Requested by user in discord: https://discord.com/channels/742820443487993987/746070591097798688/841132654044381214

They'd like to issue `delete` actions, but also be able to set that action per document so that some documents might be inserted while others are deleted. This field should be templatable.

**Comment by simonxxz** [comment]
More specifically, enable multiple actions for es sink. According to @jszwedko , right now vector "only allows setting one bulk action" for one es sink.

**Comment by spencergilbert** [comment]
Technically Vector currently supports `index` and `create` bulk actions, https://vector.dev/docs/reference/configuration/sinks/elasticsearch/#bulk_action

I'm curious about the use case for deleting documents as part of a logging pipeline

**Comment by simonxxz** [comment]
> Technically Vector currently supports `index` and `create` bulk actions, https://vector.dev/docs/reference/configuration/sinks/elasticsearch/#bulk_action
> 
> I'm curious about the use case for deleting documents as part of a logging pipeline

Basically I want to achieve both updating and deleting documents in es, and the action will be determined by the data in the log event itself--If it's 'update', put it in es; If it's 'delete', delete it.

**Comment by jszwedko** [comment]
Closed by #7805
