### ISSUE TITLE
Links on the homepage frontpage graphic are broken

### ISSUE THREAD

**Issue by apollo13** [timberio/vector#7392]
The links on the "explosion" image (first image) on https://vector.dev/ all seem to be broken. Ie clicking on "aggregate" yields https://vector.dev/docs/reference/transforms/log_to_metric instead of https://vector.dev/docs/reference/configuration/transforms/log_to_metric/

**Comment by apollo13** [comment]
@jszwedko I assume most of this went out but the "sample" in the middle and "prometheus" sink still 404.

**Comment by jszwedko** [comment]
Ah yes, thank you @apollo13 . I had fixed the links for the SVG further down the page (https://vector.dev/#integrations) but not the ones in the top one. I'll reopen this.

**Comment by jszwedko** [comment]
This is fixed in the new site.
