### ISSUE TITLE
Divvy up `vector-core` into crates

### ISSUE THREAD

**Issue by blt** [timberio/vector#7407]
As a part of #7400 we've discussed that `vector-core` should be split up into crates with `buffers` being an isolated crate.

**Comment by blt** [comment]
Ah, this has proved to be an interesting challenge. Today our buffers type is implicitly tied up with `Event`, so a split of core into separate workspace members leaves a dependency on `Event` from a sub-package. Not... ideal. Also, we today use the protobuf version of `Event` to serialize, so we can't just easily convert buffers to be generic on some type `T` because there's no way for us to express that the type must be ser/de in protobuf. We also, further, can't convert the existing disk buffer to ser/de `Event` because that will break any existing user's disk buffers, a no-no. 

The ultimate goal of this work is to get in a better position to do something about our use of leveldb -- #7380 and #7246 for example. We can probably awkwardly force a division into the core package to get a split but not in a way that meaningfully moves us toward this goal. As of #7400 we still have the top-level package actually creating buffer instances through `BufferConfig`, so making an abstract interface for "buffers" that is not generic and not in a sub-package strikes me as moving closer to our end aim. Once core can actually create a buffer we'll be able to benchmark buffers in core, which is not possible today. 

Considering the upgrade path for end users we're a little pinned down with regard to the disk buffer as-is. @lukesteensen have we ever broken compatibility in the disk buffer and, if so, what's the process been like there for the users?

**Comment by blt** [comment]
Alright, on further reflection I have got #7438 queued up to move the constructor down into core but actually separating buffer from `Event` is challenging to the point where our time would be better spent reworking buffer as a concept. The main sticking point is the protobuf serialization for disk buffer. If we had an implementation that only relied on `Serialize` and `Deserialize` making buffer generic would be a matter of typing. 

I am inclined to close this out and/or scoot it into a "rework buffers" epic. Unless we can address either the heavy startup time imposed by #7410 or find some other mechanism to tame the disk buffer memory burden we might be on the doorstep for tackling a buffer rework. @ktff did an excellent bit of work tracking known issues with our current approach in #7425. 

/cc @binarylogic

**Comment by lukesteensen** [comment]
> have we ever broken compatibility in the disk buffer and, if so, what's the process been like there for the users?

We have not, so there's no real precedent. I think we'd need to keep the leveldb code around for at least one release and do some kind of simple detection (look for `.ldb` files?) to rewrite any existing data into a new format at startup. 

> If we had an implementation that only relied on `Serialize` and `Deserialize` making buffer generic would be a matter of typing.

Could we define our own `{To,From}Bytes` trait (or similar) in a buffers crate and simply delegate the implementation to `Event`'s existing protobuf codepath? Or maybe reuse prost's [`Message`](https://docs.rs/prost/0.7.0/prost/trait.Message.html)?

**Comment by blt** [comment]
> > have we ever broken compatibility in the disk buffer and, if so, what's the process been like there for the users?
> 
> We have not, so there's no real precedent. I think we'd need to keep the leveldb code around for at least one release and do some kind of simple detection (look for `.ldb` files?) to rewrite any existing data into a new format at startup.

Heard. Detecting an existing leveldb and draining it seems relatively straightforward, so we've got that going for us. 

> > If we had an implementation that only relied on `Serialize` and `Deserialize` making buffer generic would be a matter of typing.
> 
> Could we define our own `{To,From}Bytes` trait (or similar) in a buffers crate and simply delegate the implementation to `Event`'s existing protobuf codepath? Or maybe reuse prost's [`Message`](https://docs.rs/prost/0.7.0/prost/trait.Message.html)?

My preference would be to define a `{To,From}Bytes`. The less the buffer knows about the thing being serialized the better from the point of view of testing. This comment actually gave me an idea for how to move forward, so tomorrow I'll see about making a `{To,From}Bytes`.
