### ISSUE TITLE
Compute disk buffer `initial_size` with Jean's method 

### ISSUE THREAD

**Issue by blt** [timberio/vector#7408]
@blt Actually, looking at the crate, there does appear to be a [`LevelDBIterator`](https://docs.rs/leveldb/0.8.6/leveldb/database/iterator/trait.LevelDBIterator.html) trait, which has a [`from`](https://docs.rs/leveldb/0.8.6/src/leveldb/database/iterator.rs.html#388-391) (and `to`) method which seems to imply we can iterate over an arbitrary range of keys.

It seems to me we could create a DB handle, iterate X times, get the key of the last item, and set that as the starting key for the next DB handle iterator. Reading the [offiial docs](https://github.com/google/leveldb/blob/master/doc/index.md#comparators) it appears key ordering happens lexicographically, which implies we can have stable ordering across DB handles at startup when the cache isn't actually in use, correct?

_Originally posted by @JeanMertz in https://github.com/timberio/vector/issues/7398#issuecomment-838913110_

**Comment by ktff** [comment]
This should solve the OOM issue reported in https://github.com/timberio/vector/issues/6741#issuecomment-799557456.

cc. @mikhno-s

**Comment by blt** [comment]
We gave this method a shot in #7410 but the startup cost imposed by the technique is simply too high to be useful.
