### ISSUE TITLE
Investigate and speed up the k8s end to end tests

### ISSUE THREAD

**Issue by StephenWakely** [timberio/vector#7540]
Currently the k8s end to end tests are slow and could potentially be sped up pretty significantly. 

I'm not 100% sure exactly where the issues are, investigation is needed. 

It looks like there is quite a delay between Vector starting up and fetching the logs.  Potentially this is just the speed with which kubernetes deployments work, or the speed it takes for Vector to pick up the logs to scan. If that is the case it may be worth looking into running multiple tests against a single deployment.

Plus it looks like the tests are scanning more logs than it needs to in order to pass the tests, these log lines can be produced quite slowly. I think the first thing to try is to see if each test can limit the logs it inspects to only those produced by the pod it has created. However, these are really only issues that would occur when running on a cluster and not a fresh minikube instance so I don't think it explains fully what the issues are.

**Comment by StephenWakely** [comment]
Noting that each test has this in the Vector logs:

```
Got line: "May 24 09:22:33.058  INFO source{component_kind=\"source\" component_name=kubernetes_logs component_type=kubernetes_logs}:file_server: file_source::checkpointer: Loaded checkpoint data.\n"
Got line: "May 24 09:23:34.548  INFO source{component_kind=\"source\" component_name=kubernetes_logs component_type=kubernetes_logs}:file_server: vector::internal_events::file::source: Resuming to watch file. path=/var/log/pods/local-path-storage_local-path-provisioner-547f784dff-5b79w_5dfc8d26-ba9d-4982-ad21-f456e5469dc3/local-path-provisioner/0.log file_position=1518\n"
```

Why does Vector need to wait for a minute at this point?

**Comment by spencergilbert** [comment]
Not an expert (yet), could this be when vector is calling the kube-apiserver?

**Comment by StephenWakely** [comment]
#8024 and #7823 has reduced the test times significantly. There is always going to be areas where improvement can occur, but I think we have achieved a sufficient speedup for this issue to be closed now.
