### ISSUE TITLE
Fix the kubernetes end to end tests to run on multinode clusters

### ISSUE THREAD

**Issue by StephenWakely** [timberio/vector#7541]
Multinode clusters cause issues. 

Vector only picks up logs from the node it has been installed on. With a multi-node instance, the pod could be installed on one node and the tests are checking the Vector that has been installed on another node. The tests then never finish. I believe the helm charts install a Vector on each node, so the tests should be able to determine which node the test pod has been installed on and then talk to the Vector on that node. 

Untill we make this change these tests will only run on single node clusters.

**Comment by spencergilbert** [comment]
This can be tested locally more easily with `kind` as it can start multinode clusters - I think `minikube` is limited to the single node
