### ISSUE TITLE
Make component boxes clickable

### ISSUE THREAD

**Issue by zsherman** [timberio/vector#7570]
Right now only the titles are links, this can be confusing as seen in the GIF and the entire div should be a link instead. ![Screen Recording 2021-05-24 at 02.36.28 PM.gif](https://images.zenhubusercontent.com/544ec7ad7c6ccc6277a58d13/5eb24df8-93f2-44ac-b8df-d53468017e8e)

**Comment by lucperkins** [comment]
Addressed in #7368
