### ISSUE TITLE
Investigate why `bench-remap-functions` can share benchmark binary between runs.

### ISSUE THREAD

**Issue by tobz** [timberio/vector#7582]
As mentioned in [#7573](https://github.com/timberio/vector/pull/7573#issuecomment-847501492), we observed that one of our benchmark targets -- `bench-remap-functions` -- doesn't seem to recompile when we run it in the CI benchmarking suite.  Its siblings -- after switching from `master` to whatever the PR branch is -- do seem to atleast relink themselves, but don't do the full dependency recompilation, etc.

What we know:
- the given runs in that PR had no `Cargo.lock` changes at all, so the Github Actions cache key should not have changed and should have been providing benefits to all benchmark jobs equally
- `bench-remap-functions` is the only benchmark target where we override the `--manifest-path` argument to point it at the correct/nested `lib/vrl/stdlib/Cargo.toml` versus reading the top-level `Cargo.toml`

**Comment by tobz** [comment]
I believe the culprit is our use of `built`, which is a build-time code generator that does things like collect feature flags, `rustc` version, Git commit SHA, and more, and expose them to the code itself via an include-able source file.

When the output of the plugin changes, so does the fingerprint for that file, which is a dependency for `vector`, and thus the benchmarks believe they need to be recompiled.  This doesn't happen for `bench-remap-functions` because we point directly to it, skipping `build.rs` at the top of the repository.

This is actually an interesting problem because it means we're needlessly rebuilding the benchmark binaries between `master`/PR runs simply because the Git commit SHA changed, even though, functionally, it's not germane at all to the benchmarks themselves... only ancillary code like logging output or `vector --help`.

Going to close this as we've now narrowed down the problem, and we'll attempt to address the usage of `built` in a follow-up issue/PR.

**Comment by jszwedko** [comment]
👍 nice find.
