### ISSUE TITLE
Run as an embedded library "In process source"

### ISSUE THREAD

**Issue by avnerbarr** [timberio/vector#7600]
I want to collect logs from many client devices and send them to a centralized server for further processing.  (The application is written in rust and could embed vector as a crate in theory)

If I understand correctly, the current architecture that would be supported for this use case is to have the application write to a central log file, install a private vector instance tied to my application and configured with a "file" source pointing to the application log file with a sink sending the logs to downstream to an HTTP endpoint (or a vector sink instance running on a remote server?).

It would be more viable in my use case to embed vector as an in-process "logging backend" configured to collect the application logs (i.e. `info!` or `vector!` etc.) and forward them to the remote server using the configured behavior.

Is this possible?

**Comment by leebenson** [comment]
This is somewhat related to #4085.

Offering Vector as a library / crate is something we're considering internally. We don't have a definitive roadmap for it yet, but when there's a consensus and some movement, we'll let you know.

Will keep this issue open as it's more specific to hosting as a Rust crate vs. #4085, which is more open-ended.

**Comment by jszwedko** [comment]
Thanks @avnerbarr ! We actually have an issue for this already, #4085, so I'll close this in-lieu of that one, but feel free to follow along there or add any additional details. I know @wperron has been trying to use the existing, unpublished, vector crate and might have some tips to share.

**Comment by leebenson** [comment]
Ha, sorry @jszwedko, cross-over post there. Feel free to re-open or keep it closed-- we can track in #4085 if needed.

**Comment by jszwedko** [comment]
Doh, sorry @leebenson 😄 I posted before I saw your comment. I think we can just track in #4085 for now.
