### ISSUE TITLE
Clarify "sinks" and "ElasticSearch" sink documentation

### ISSUE THREAD

**Issue by Shogobg** [timberio/vector#7616]
In [sinks.cue](https://github.com/timberio/vector/blob/9b5d3b6efcf88c8dbe5901bee8ecb91149474096/docs/reference/components/sinks.cue#L164-L188), the `only_fields` and `except_fields` have the same description. This change fixes the description to show the correct function.

In [elasticsearch.cue](https://github.com/timberio/vector/blob/9b5d3b6efcf88c8dbe5901bee8ecb91149474096/docs/reference/components/sinks/elasticsearch.cue#L240), i've added a clarification that the operation will not update the document, but replace it. Usually updates will "patch" a partial document, but the `index` action replaces the full document, so if a partial document is sent, it will overwrite the existing one.

Fix a broken link in CONTRIBUTING.md

**Comment by jszwedko** [comment]
Closed by #7617
