### ISSUE TITLE
HTTP test server needs to provide gRPC headers to indicate response status

### ISSUE THREAD

**Issue by StephenWakely** [timberio/vector#7624]
In order to test end to end acknowledgement properly the HTTP test server needs to be able to provide the required gRPC headers to indicate the response status. Currently the header is missing and we get this error:

```
message: "grpc-status header missing, mapped from HTTP status code 200"
```

There is some useful information about the protocol [here](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md).

**Comment by bruceg** [comment]
The test server probably also needs to either copy the HTTP version from the incoming request or take an additional parameter for what version to report since the gRPC client is issuing queries with version `HTTP/2.0` but the test server is responding with `HTTP/1.1`
