### ISSUE TITLE
Tutorial on https://vector.dev/docs/setup/installation/platforms/docker/ failed

### ISSUE THREAD

**Issue by DmitriyPanteleev** [timberio/vector#7630]
The tutorial on:

https://vector.dev/docs/setup/installation/platforms/docker/

Here's what went wrong:

ERROR source{component_kind="source" component_name=logs component_type=docker_logs}: vector::sources::docker_logs: Listing currently running containers failed. error=error trying to connect: No such file or directory (os error 2)
May 28 08:54:25.059  INFO vector: Vector has started. version="0.13.1" git_version="v0.13.1" released="Thu, 29 Apr 2021 14:20:13 +0000" arch="x86_64"

**Comment by jszwedko** [comment]
👍 thanks @DmitriyPanteleev . The tutorial should include mounting the docker socket into the container. You can do that via `-v /var/lib/docker.sock:/var/lib/docker.sock`.

**Comment by DmitriyPanteleev** [comment]
Yes. I figured it out on my own. But it shoud be in documentation/tutorial.
Thank you anyway.
