### ISSUE TITLE
Multi-byte log line delimiters

### ISSUE THREAD

**Issue by marcbowes** [timberio/vector#764]
Currently the file source only supports delimiting by EOF or \n:

https://github.com/timberio/vector/blob/e190e96e925d819d7460fab64f37fdb4241b88ad/lib/file-source/src/file_watcher.rs#L108

It would be super useful to be able to combine multiple lines into one log entry.

**Comment by lukesteensen** [comment]
Thanks for the opening this @marcbowes! There has been some related discussion at #388, but I'd be curious to hear more about your use case.

Would it be sufficient to allow overriding that `b'\n'` with a static multi-byte sting? Or would you want something more like a regex pattern for detecting message boundaries?

**Comment by marcbowes** [comment]
Oh sorry I suck at searching..

A static string would be sufficient. That other issue nails it. I'd be fine with either a "this is the static EOL" or "this is the static beginning of entry", both are workable for my use-case.
