### ISSUE TITLE
Avoid trying to decompress 0-byte files

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#7710]
A user reported an issue they are seeing with the `aws_s3` source where it fails to consume 0-byte gzip files and so does not consume the SQS message.

The error looks like:

```
WARN source{component_kind="source" component_name=input-us-east-1 component_type=aws_s3}: vector::internal_events::aws_s3::source: Failed to process SQS. self.message_id=0ffbafee-acd2-4512-a084-d696ef84038a self.error=Failed to read all of s3://***-prod-alb-logs-us-east-1/***/sand/AWSLogs/***/elasticloadbalancing/us-east-1/2021/06/01/***_elasticloadbalancing_us-east-1_app.awseb-AWSEB-B69UZE6O2334.df3b790b2ac0dace_20210601T1950Z_10.27.1.124_52kw5m7g.log.gz: unexpected end of file
```

We should skip decompression if the file is 0-bytes.

We probably have this issue in other places where we do decompression as well (like the `file` source).

**Comment by ktff** [comment]
> We probably have this issue in other places where we do decompression as well (like the file source).

`file` source maybe has a similar bug. I'll check it separately.

**Comment by ktff** [comment]
> file source maybe has a similar bug. I'll check it separately.

Nope, it's fine.
