### ISSUE TITLE
Addition of aggregated summary metrics does not make sense

### ISSUE THREAD

**Issue by bruceg** [timberio/vector#7723]
> This looks like we're taking two quantiles that are, say, individually representing something like `50ms at the 50th percentile`, and then doing `50 + 50`.... but I can't think of a situation where this behavior would ever be correct.

_Originally posted by @tobz in https://github.com/timberio/vector/pull/7699#discussion_r644162929_

**Comment by bruceg** [comment]
Since these cannot reasonably be added, I think an "incremental" kind of these would also be invalid. If so, the only valid thing to do is handle/convert them to absolute metrics and drop the earlier value. Does that make sense @tobz?

**Comment by tobz** [comment]
Thinking this through: yes, keeping the latest is the only thing that makes sense to me as well.

Anytime someone is aggregating metrics before they hit Vector, the best we can do is forward them as-is.  This might change if those aggregations are mergeable themselves: for example, if upstreams sent us a [DDSketch](https://blog.acolyer.org/2019/09/06/ddsketch/) with known alpha/min value/etc, we could continually merge those.

**Comment by bruceg** [comment]
We do a check on the boundaries on aggregated histograms, for which the buckets ranges are exact values not relative values, so I reason those are safe to add/subtract. It's just the summaries, as the effective boundaries of the quantiles will change based on the summarized data.

**Comment by tobz** [comment]
Ah yeah, you're totally right about us being able to support histogram merging so long as buckets match. 👍🏻
