### ISSUE TITLE
Nginx VRL parsing function does not correctly parse some Nginx error logs

### ISSUE THREAD

**Issue by simonrozsival** [timberio/vector#7726]
### Vector Version

```
vector 0.13.1 (v0.13.1 x86_64-apple-darwin 2021-04-29)
```

### Expected Behavior

The `parse_nginx_log(.message, "error")` function should correctly parse any nginx error log.

### Actual Behavior

In the following example log the `referrer` key is not recognized at all and `host` is equal to `65.21.190.83:31256", referrer: "http://65.21.190.83:31256/`.

### Example Data

```
2021/06/03 09:30:50 [error] 32#32: *6 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 10.244.0.0, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "65.21.190.83:31256", referrer: "http://65.21.190.83:31256/"
```

### References

The Nginx implementation is here: https://github.com/nginx/nginx/blob/master/src/http/ngx_http_request.c#L3811 - you can see that it's not just `referrer` that is not accounted for in https://github.com/timberio/vector/blob/master/lib/vrl/stdlib/src/log_util.rs#L98, it's also `subrequest` and `upstream`.

**Comment by jszwedko** [comment]
Thanks @simonrozsival . I think this is the same as https://github.com/timberio/vector/issues/7236 . Would you agree?

**Comment by simonrozsival** [comment]
Hi @jszwedko ! It's not the same. The other issue is related to the "combined" format while this one is the "error" format. They both have very different structure and are parsed using completely different regular expressions.

**Comment by jszwedko** [comment]
Ah, gotcha, yeah, I see. Thanks! I put this in the next milestone so I expect we can address this soon.

**Comment by simonrozsival** [comment]
Thanks!

**Comment by JeanMertz** [comment]
Fixed in #7852.

**Comment by alpi-ua** [comment]
I assume that having issue with parse_nginx_log  when "upstream" comes to error log.
```
parse_nginx_log!(
s'2021/06/29 22:44:05 [warn] 1662631#0: *5440 an upstream response is buffered to a temporary file /var/lib/nginx/tmp/proxy/8/09/0000000098 while reading upstream, client: 11.22.33.44, server: server.com, request: "POST /some/post HTTP/1.1", upstream: "http://upstream/address", host: "host"', "error")
function call error for "parse_nginx_log" at (0:320): failed parsing log line
```
Anyway I can parse this exactly string with parse_regex combined from  [https://github.com/timberio/vector/blob/master/lib/vrl/stdlib/src/log_util.rs#L98](log_util.rs) 
```
message=s'2021/06/29 22:44:05 [warn] 1662631#0: *5440 an upstream response is buffered to a temporary file /var/lib/nginx/tmp/proxy/8/09/0000000098 while reading upstream, client: 11.22.33.44, server: server.com, request: "POST /some/post HTTP/1.1", upstream: "http://upstream/address", host: "host"', "error"'

parse_regex!(message,
r'(?x)^\s*(?P<timestamp>.+)\s+\[(?P<severity>\w+)\]\s+(?P<pid>\d+)\#(?P<tid>\d+):(\s+\*(?P<cid>\d+))?\s+(?P<message>[^,]*)(,\s+client:\s+(?P<client>[^,]+))?(,\s+server:\s+(?P<server>[^,]+))?(,\s+request:\s+"(?P<request>[^"]+)")?(,\s+upstream:\s+"(?P<upstream>[^"]+)")?(,\s+host:\s+"(?P<host>[^"]+)")?(,\s+referrer:\s+"(?P<referrer>[^"]+)")?\s*$')

{ "cid": "5440", "client": "11.22.33.44", "host": "host", "message": "an upstream response is buffered to a temporary file /var/lib/nginx/tmp/proxy/8/09/0000000098 while reading upstream", "pid": "1662631", "referrer": null, "request": "POST /some/post HTTP/1.1", "server": "server.com", "severity": "warn", "tid": "0", "timestamp": "2021/06/29 22:44:05", "upstream": "http://upstream/address" }
```
Without upstream group, upstream info where coming to request group.

It would be nice to update "error" format with the upstream.

vector --version
`vector 0.15.0 (x86_64-unknown-linux-gnu 2b8fcd8 2021-06-29)`

**Comment by alpi-ua** [comment]
btw, you got a typo here
![image](https://user-images.githubusercontent.com/14225967/123883311-6f6e2580-d951-11eb-8899-0f7e4cb93da4.png)

![image](https://user-images.githubusercontent.com/14225967/123883514-d8ee3400-d951-11eb-9182-46bd86c636e5.png)

**Comment by jszwedko** [comment]
@alpi-ua I do see that one fails to parse as of 99acfcb97. Thanks for reporting! I reopened this to address.

@jdrouet would you mind looking at this again?. In addition to fixing the parsing of https://github.com/timberio/vector/issues/7726#issuecomment-870997984 would you mind seeing if there are any other gaps we might be missing?
