### ISSUE TITLE
Add new CI build step to track Vector binary compilation time

### ISSUE THREAD

**Issue by tobz** [timberio/vector#7730]
As part of [RFC 7694](https://github.com/timberio/vector/blob/master/rfcs/2021-06-01-7694-improve-monitor-build-performance.md), we want to track the build performance of Vector over time so that we can understand if we're regressing or improving.

Once #7729 is complete, we should add a new CI step which simply builds Vector in release mode, from scratch, no caching or anything: a full measure of the "brand new user clones the repo and builds Vector" scenario.  In doing so, we'll also track the time taken to build Vector and submit it to Datadog for long-term storage and analysis.

**Comment by bruceg** [comment]
Is it worth also tracking check time and non-release build time, as well as incremental rebuild time (ie `touch lib/vector-core/src/lib.rs && cargo …`) for all three?

**Comment by jszwedko** [comment]
@tobz is this still in-flight? I believe we have an internal dashboard for this now, yes?

**Comment by tobz** [comment]
Oh, woops: this is donezo. 🚀
