### ISSUE TITLE
Tutorial step disappears on all tutorials

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#7744]
I think this may have changed with the 0.14.0 release.

For example, if you go to https://vector.dev/guides/integrate/sources/splunk_hec/aws_s3/#tutorial the tutorial step briefly appears, but then disappears.

**Comment by ruifigueiredo** [comment]
With chrome and firefox the steps are not visible, but with safari the info appears.

**Comment by spencergilbert** [comment]
The tutorial is visible for me with chrome 🤔 I feel like this has happened before and I resolved for myself by clearing cache/cookies/etc

**Comment by jszwedko** [comment]
Hrm, that is odd, now I see them too. I had tried hard-refreshing before. Maybe it needs to rebuild some cache after deploys. Given the new site is imminent, I'll just close this.
