### ISSUE TITLE
Keep directory name inside release archives consistent with the archive name

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#776]
Doing

```sh
curl -sSf https://packages.timber.io/vector/latest/vector-latest-x86_64-unknown-linux-musl.tar.gz | tar xzf -
```
creates directory named `vector-0.3.0-94-ge3e31d0` and doing

```sh
curl -sSf https://packages.timber.io/vector/nightly/vector-nightly-x86_64-unknown-linux-musl.tar.gz | tar xzf -
```
creates directory named `vector-0.3.0-201-gd723a95`.

It makes it harder to use such archives, for example, for building Docker images, as the target directory name cannot be inferred from the archive name.

I think it could have been easier to use if the directory name was the same as the archive without extension, i.e. `vector-latest-x86_64-unknown-linux-musl` for `vector-latest-x86_64-unknown-linux-musl.tar.gz` and `vector-nightly-x86_64-unknown-linux-musl` for `vector-nightly-x86_64-unknown-linux-musl.tar.gz`. It would also be consistent with practices of other open source projects, such as Linux kernel or Rust.

**Comment by binarylogic** [comment]
Ah, yep, that was not intentional, thanks for letting us know. We'll get this fixed.

**Comment by binarylogic** [comment]
This has been resolved. A list of packages can be found at:

https://packages.timber.io/vector

The directory now matches the file name. I went ahead and removed the version from the file name. If we find this causes problems we can add it back, but this was a simple first step to correct this.
