### ISSUE TITLE
Update `udp` source to use new `UdpFramed`

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#777]
Now that https://github.com/tokio-rs/tokio/pull/1444 has been merged we can reduce the usage of double framed outputs in the `udp` source. This should allow us to use `BytesDelimitedCodec` just like how it is used in the `tcp` source.

cc @ktff

**Comment by ktff** [comment]
Yes, with an exception that we will need a wrapper around `BytesDelimitedCodec` which will map `Wrapper::decode -> BytesDelimitedCodec::decode_eof`

**Comment by LucioFranco** [comment]
@ktff not sure I follow what you mean there? Could you explain more?

**Comment by ktff** [comment]
@LucioFranco  `BytesDelimitedCodec::decode` waits for newline before decoding a message. While `udp` source has one more message after that. Which stretches until eof.

**Comment by LucioFranco** [comment]
@ktff ah ok, would it make sense to change BytesDelimitedCodec to support reading up to a newline or a certain length say the end of the packet?

**Comment by ktff** [comment]
@LucioFranco Nope, since the size of the packet can vary, it would have to change it's behavior on eof which would break other code.

**Comment by ktff** [comment]
It is, I'll implement it tomorrow.
