### ISSUE TITLE
Support tls.verify_certificate for splunk_hec sink

### ISSUE THREAD

**Issue by asafdl** [timberio/vector#7775]
splunk hec recieves http requests and is certainly able to read the insecure flag, but the vector agent config file does not allow it: https://vector.dev/docs/reference/configuration/sinks/splunk_hec/#transport-layer-security-tls

**Comment by jszwedko** [comment]
@asafdl agreed, we should support this. I had opened https://github.com/timberio/vector/issues/6132 which should cover this too. I'll close this in-lieu of that one, but feel free to add any additional notes there.
