### ISSUE TITLE
Add option to add array of ca files via helm chart

### ISSUE THREAD

**Issue by asafdl** [timberio/vector#7804]
### Current Vector Version

vector 0.13.1 (v0.13.1 x86_64-unknown-linux-gnu 2021-04-29)

### Use-cases

Add multiple CA files for tls requests 

### Attempted Solutions

tls.ca_file allows to enter path to file or a string certificate, if I have multiple files there's no way to load them all from chart

### Proposal

instead of reading a path or string, it should be reading an array

**Comment by spencergilbert** [comment]
Issue moved to [timberio/helm-charts #10](https://github.com/timberio/helm-charts/issues/10) via [**ZenHub**](https://www.zenhub.com/)
