### ISSUE TITLE
Sources, transforms, sinks links in your footer resulted in a 404 error

### ISSUE THREAD

**Issue by natea** [timberio/vector#7820]
### Vector Version

```
...
```

### Vector Configuration File

```toml
...
```

**Comment by jszwedko** [comment]
This is due to poor redirect behavior by docusaraus; if you refresh it should take you to the right page. We are close to releasing a new version of the site. I'll leave this open to ensure the same issue doesn't exist there.

**Comment by jszwedko** [comment]
This is fixed in the new version of the website.
