### ISSUE TITLE
Add `tls.verification_mode`

### ISSUE THREAD

**Issue by spencergilbert** [timberio/vector#7822]
Similar to [filebeat](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-ssl.html#client-verification-mode), we should allow users to specify how vector verifies certs. This is somewhat possible today with the `tls. verify_hostname` setting, but allowing `none` would make it easier to connect against self-signed certs.

**Comment by jszwedko** [comment]
👍 Would this be the same as #6132 ?

**Comment by spencergilbert** [comment]
🙄 _maybe_
