### ISSUE TITLE
`parse_key_value` not correctly parsing quoted value

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#7839]
Reported by user here: https://github.com/timberio/vector/discussions/7772#discussioncomment-857602

Vector version:

```
vector 0.14.0 (x86_64-apple-darwin 5f3a319 2021-06-03)
```

It looks like `parse_key_value`, in this particular case, is not correctly parsing a quoted field value.

```
$ parse_key_value!("time=\"2021.2021-06-11 09:54:11Z\", severity=[php7:emerg] , process=1700689 , message=\"PHP Parse error:  syntax error, unexpected '->' (T_OBJECT_OPERATOR) in /var/www/prod/releases/master-c7225365fd9faa26262cffeeb57b31bd7448c94a/source/index.php on line 14\"")
{ ", message": "PHP Parse error:  syntax error, unexpected '->' (T_OBJECT_OPERATOR) in /var/www/prod/releases/master-c7225365fd9faa26262cffeeb57b31bd7448c94a/source/index.php on line 14", ", process": "1700689", "09:54:11Z", severity": "[php7:emerg]", "time": "\"2021.2021-06-11" }
```

Here the `time` key didn't read the whole value even though it is quoted.

**Comment by jszwedko** [comment]
@prognant would you mind taking a look at this since you were working in that code recently?

**Comment by prognant** [comment]
In the example provided I don't think there is any problem if the `field_delimiter` is set to `,`:

```
parse_key_value!("time=\"2021.2021-06-11 09:54:11Z\", severity=[php7:emerg] , process=1700689 , message=\"PHP Parse error:  syntax error, unexpected '->' (T_OBJECT_OPERATOR) in /var/www/prod/releases/master-c7225365fd9faa26262cffeeb57b31bd7448c94a/source/index.php on line 14\"", field_delimiter: "," )
{ "message": "PHP Parse error:  syntax error, unexpected '->' (T_OBJECT_OPERATOR) in /var/www/prod/releases/master-c7225365fd9faa26262cffeeb57b31bd7448c94a/source/index.php on line 14", "process": "1700689", "severity": "[php7:emerg]", "time": "2021.2021-06-11 09:54:11Z" }

Pretty print
{
  "message": "PHP Parse error:  syntax error, unexpected '->' (T_OBJECT_OPERATOR) in /var/www/prod/releases/master-c7225365fd9faa26262cffeeb57b31bd7448c94a/source/index.php on line 14",
  "process": "1700689",
  "severity": "[php7:emerg]",
  "time": "2021.2021-06-11 09:54:11Z"
}
```

**Comment by jszwedko** [comment]
Doh, you are right, thank you 😄 I missed that the field delimiter was not being set. I'll close this out.

cc/ @SirUrban in case I'm misunderstanding the issue they were having.

**Comment by hhromic** [comment]
Hi, I just hit the same problem and I have evidence that indeed there is something wrong with quotes.

Consider the following VRL examples:
```
# no quotes, parsing seems OK
$ parse_key_value!(s'user=DOMAIN\account ip=1.2.3.4', whitespace:"strict")
{ "ip": "1.2.3.4", "user": "DOMAIN\\account" }

# quotes in key "user" are added to the value but not in key "ip" -> the "\" is wreaking havoc!
$ parse_key_value!(s'user="DOMAIN\account" ip="1.2.3.4"', whitespace:"strict")
{ "ip": "1.2.3.4", "user": "\"DOMAIN\\account\"" }

# if we add more words inside the quotes, it gets worse
$ parse_key_value!(s'user="DOMAIN\account space" ip="1.2.3.4 space"', whitespace:"strict")
{ "space" ip": "1.2.3.4 space", "user": "\"DOMAIN\\account" }

# ... but key=value previously to the offending "user" key is OK
$ parse_key_value!(s'app="my-app" user="DOMAIN\account space" ip="1.2.3.4 space"', whitespace:"strict")
{ "app": "my-app", "space" ip": "1.2.3.4 space", "user": "\"DOMAIN\\account" }

# if we remove the "\" from the value, the quotes (and everything) works right
$ parse_key_value!(s'user="DOMAIN+account space" ip="1.2.3.4 space"', whitespace:"strict")
{ "ip": "1.2.3.4 space", "user": "DOMAIN+account space" }
```

**Comment by prognant** [comment]
There is definitely something off when using the escape character (without escaping something however...) in a quoted string:
E.g. those two assertion should have the same outcome
```
$ parse_key_value!(s'key="a\a"', whitespace:"strict")
{ "key": "\"a\\a\"" }

$ parse_key_value!(s'key=a\a', whitespace:"strict")
{ "key": "a\\a" }
```
And indeed space does not help (btw standalone key are not helping here...):
```
$ parse_key_value!(s'key="a \ a"', whitespace:"strict")
{ "\": true, "a"": true, "key": "\"a" }
```

So I'll have a look, hopefully a fix will follow soon cc @jszwedko

**Comment by prognant** [comment]
I struggled a bit to pinpoint the exact issue:
* Standalone `\` are breaking everything 
* [`parse_delimited`](https://github.com/timberio/vector/blob/master/lib/vrl/stdlib/src/parse_key_value.rs#L312-L344) is failing with any quoted expression containing a standalone `\`
* then `parse_value` & `parse_key` fall back on [`parse_undelimited`](https://github.com/timberio/vector/blob/master/lib/vrl/stdlib/src/parse_key_value.rs#L361-L386)
* And :
  * if there is field delimiter inside the quoted string (space by default) then the quote string gets cut
  * If not the quoted string is read with it quotation char (hence the `\"` in the problematic string aforementioned)  

Other considerations:
* The escape parser is reading escaped character but not removing `\` as it uses [escaped](https://github.com/timberio/vector/blob/master/lib/vrl/stdlib/src/parse_key_value.rs#L329-L333)
* We may use [escaped_transform](https://docs.rs/nom/6.2.1/nom/bytes/complete/fn.escaped_transform.html) to remove legit `\` as escaping is handled correctly (at least it is in `encode_key_value`)

**Comment by Nicarim** [comment]
Hey, I'm having same issue with following string
I'm testing it by doing it in VRL:
```
.message = "time=\"2020-01-09T00:00:00Z\" level=error msg=\"stripe create customer error: {\\\"code\\\":\\\"resource_missing\\\",\\\"doc_url\\\":\\\"https://stripe.com/docs/error-codes/resource-missing\\\",\\\"status\\\":400,\\\"message\\\":\\\"No such token: '11\\\\\\\\r\\\\\\\\n\\\\\\\\n'\\\",\\\"param\\\":\\\"source\\\",\\\"request_id\\\":\\\"req_redacted\\\",\\\"type\\\":\\\"invalid_request_error\\\"}\\n\" file=redacted.go func=\"stripe.(*client).CreateCustomer\" line=1 request_id=redacted"

$ .parsed = parse_key_value!(.message)
{ "create customer error: {\"code\":\"resource_missing\",\"doc_url\":\"https://stripe.com/docs/error-codes/resource-missing\",\"status\":400,\"message\":\"No such token: '11\\\\r\\\\n\\\\n'\",\"param\":\"source\",\"request_id\":\"req_redacted\",\"type\":\"invalid_request_error\"}\n" file": "redacted.go", "func": "stripe.(*client).CreateCustomer", "level": "error", "line": "1", "msg": "\"stripe", "request_id": "redacted", "time": "2020-01-09T00:00:00Z" }
```

What's weird is that trying to remove all `\` from string still doesn't fix the issue - do you have any recommendations?

**Comment by prognant** [comment]
Thanks for the testing the PR 👍
