### ISSUE TITLE
Sending logs from Azure Event Hub (Kafka) with the correct timestamp to Loki

### ISSUE THREAD

**Issue by sareykaj** [timberio/vector#7883]
Hi,
I am struggeling with the configuration to adjust the timestamp which is associated to the log event that is sent to Loki.

**Use Case**:
- Stream Gateway Logs from Azure API-Management to Azure Event Hubs
- Collect the Logs from Azure Event Hubs
- Transform log entries (JSON) for my needs
- Push the log entries to Loki with the **original timestamp** of the log entry (which is the `time` property from Azure APIM)

For the last three operations I have Vector in a docker container running in Kubernetes with the following config:

```
[log_schema]
  timestamp_key = "timestamp" 

[api]
  enabled = false # optional, default
  address = "127.0.0.1:8080" # optional, default
  playground = false # optional, default

[sources.kafka]
  type = "kafka"
  bootstrap_servers = "xxxxx.servicebus.windows.net:9093"
  group_id = "xxxx"
  topics = [ "apim-logs" ]
  sasl.enabled = true
  sasl.mechanism = "PLAIN"
  sasl.password = "xxxxxxxx"
  sasl.username = "$$ConnectionString"
  [sources.kafka.librdkafka_options]
    "security.protocol" = "sasl_ssl"

[transforms.tokenize]
  type = "remap" # required
  inputs = ["kafka"] # required
  source = '''
  . = parse_json!(.message).records
  '''

[transforms.toloki]
  type = "remap" # required
  inputs = ["tokenize"] # required
  source = '''
  .timestamp = .time
  .customerUID = .properties.traceRecords[0].message
  .forwardedFor = .properties.traceRecords[1].message
  .requestId = .properties.traceRecords[2].message
  .apiId = .properties.apiId
  .apiRevision = .properties.apiRevision
  .apimSubscriptionId = .properties.apimSubscriptionId
  .backendId = .properties.backendId
  .backendMethod = .properties.backendMethod
  .backendProtocol = .properties.backendProtocol
  .backendResponseCode = .properties.backendResponseCode
  .backendTime = .properties.backendTime
  .backendUrl = .properties.backendUrl
  .cache = .properties.cache
  .clientProtocol = .properties.clientProtocol
  .clientTlsVersion = .properties.clientTlsVersion
  .method = .properties.method
  .operationId = .properties.operationId
  .productId = .properties.productId
  .requestSize = .properties.requestSize
  .responseCode = .properties.responseCode
  .responseSize = .properties.responseSize
  .url = .properties.url
  del(.properties)
  del(.category)
  del(.operationName)
  del(.resourceId)
  '''

[sinks.out]
  type = "loki"
  inputs = [ "toloki" ]
  endpoint = "http://loki.istio-system.svc.cluster.local:3100"
  remove_timestamp = false
  encoding.codec = "json"
  healthcheck.enabled = true  
  labels.forwarder = "apim"
  labels.component = "apim"
```

In my understanding, the "ts" property is the timestamp associated to the event in loki. So my expectation would be that:
`ts = timestamp = time`. But `ts` still has the value of the processing time in Vector.

![grafana-loki](https://user-images.githubusercontent.com/3009927/122236029-73fcfd80-cebe-11eb-9222-599fb9b7f24a.png)

**Comment by jszwedko** [comment]
> It might be that `.time` needs to be converted into a _timestamp_ type explicitly with [to_timestamp](https://vector.dev/docs/reference/vrl/functions/#to_timestamp).

This is my guess as well. Could you try `  .timestamp = to_timestamp(.time)`?

Ref: https://github.com/timberio/vector/issues/4774

**Comment by sareykaj** [comment]
Yes. That did the trick. Thanks a lot :-)

**Comment by spencergilbert** [comment]
Nice! Glad I could help, I remember spending a while trying to figure out why it didn't work 🙂
