### ISSUE TITLE
Checkpoint files during shutdown

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#7898]
While investigating https://github.com/timberio/vector/issues/7896 @spencergilbert and I observed that the `FileServer` seems to immediately cease checkpointing once shutdown is started:

https://github.com/timberio/vector/blob/56619b87eaadf69276530df9bff40d895445c604/lib/file-source/src/file_server.rs#L138-L173

We think this may be causing the test failure we saw if the vector pod running in the test failed to write its checkpoints before it was restarted.

@lukesteensen is my understanding here right? Is there a reason we have it like this? I would have expected us to stop reading files but also flush the checkpoints one more time during shutdown.

**Comment by spencergilbert** [comment]
If this is the cause behind the k8s ci failures we should back out the sleep I added [here](https://github.com/timberio/vector/pull/7897) once resolved
