### ISSUE TITLE
Configs parsing errors on `x86_64-unknown-linux-musl`

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#791]
The build for `x86_64-unknown-linux-musl` cannot parse configs.

Example:

`vector.toml`:
```toml
[sources.stdin]
  type = "stdin"

[sinks.console]
  type = "console"
  inputs = ["stdin"]
```

```sh
$ curl -sSf https://packages.timber.io/vector/nightly/vector-nightly-x86_64-unknown-linux-musl.tar.gz | tar xzf -
$ ./vector-0.3.0-201-gd723a95/bin/vector --config vector.toml 
Aug 23 18:27:21.282  INFO vector: Log level "info" is enabled.
Aug 23 18:27:21.282  INFO vector: Loading config. path="vector.toml"
Aug 23 18:27:21.283 ERROR log: Configuration error: unknown variant `stdin`, there are no variants for key `sources.stdin.type`  log.target="vector" log.module_path="vector" log.file="src/main.rs" log.line=299
Aug 23 18:27:21.283 ERROR vector: Configuration error: unknown variant `stdin`, there are no variants for key `sources.stdin.type`
```

I'm not sure what exactly causes this, but it should not be MUSL itself, as the build for Alpine from #669 works.

**Comment by lukesteensen** [comment]
That is very weird. I wonder if there's something that causes [typetag](https://github.com/dtolnay/typetag) to fail to register the different trait implementations?

**Comment by a-rodin** [comment]
`typetag` uses crate `impl` which is proc macro, so it seems to have something to do with [support of proc macro](https://github.com/rust-lang/rust/blob/beta/src/librustc_codegen_utils/link.rs#L162) for fully static builds.

It looks like proc macro requires working dynamic linker, even for static builds, but `-static` flag is always added to Rust linker’s flags. I will try to remove always added `-static` flag for Rust linker and see would it help or not.
