### ISSUE TITLE
website docs outdated: Installation/Manual/From Source

### ISSUE THREAD

**Issue by tshepang** [timberio/vector#7920]
In https://vector.dev/docs/setup/installation/manual/from-source/#configuring, I see this:
> A full spec is located at config/vector.spec.toml and examples are located in config/vector/examples/*. You can learn more about configuring Vector in the Configuration section.

But current docs says this:
> Example configurations are located in `config/vector/examples/*`. You can learn more about configuring
Vector in the [Configuration][docs.setup.configuration] section.

**Comment by jszwedko** [comment]
@tshepang thanks! I'm not sure I understand the issue here though. The link appears to be correct, yes? It goes to https://vector.dev/docs/reference/configuration/

The `[Configuration][docs.setup.configuration]` is the un-rendered form of the link. Building the website replaces it with the actual link.

**Comment by tshepang** [comment]
What is rendered on website does not match what's in the repo... the former starts with "A full spec", the latter with "Example configurations".

**Comment by jszwedko** [comment]
Ah I see; I was distracted by the difference in rendered links. Yeah, I don't think think the files in this repo that correspond to those pages are actually used. The ones I see rendered are in the private website repo. This should be fixed by #7368 which will move all configuration into this repo.

**Comment by tshepang** [comment]
Looks like some newer content is lost... 173bf3a146e73a59806e4bae7131fdf019dc520d introduced a change which was reverted by that large PR.

**Comment by binarylogic** [comment]
cc @lucperkins. We should audit for other overwritten changes as a result.
