### ISSUE TITLE
Debian -  Wrong default data directory and shell redundancy for vector user

### ISSUE THREAD

**Issue by xluffy** [timberio/vector#7945]
### Current Vector Version

```
0.14.0
```

### Use-cases

When I install vector deb package for Ubuntu 20.04. A new user is created automatically. But have some issue with this user.

Check at 

```
> cat /etc/passwd
vector:x:999:999::/home/vector:/bin/sh
```

- This user has a shell `/bin/sh`, for a user service, I think we don't need to create a user with sh shell, we don't want some attackers can get shell. 
- I think vector data directory should put at`/var/lib/vector` instead of `/home/vector`

### Proposal

- Create a `vector` user without shell
- Set default data directory to `/var/lib/vector`

<img width="1236" alt="MacBook-Pro ❐ init ● 3 bash 2021-06-21 09-02-20" src="https://user-images.githubusercontent.com/1505720/122697381-6a351a80-d26f-11eb-9652-47870c2fbd07.png">

**Comment by spencergilbert** [comment]
Then seems sensible to me 🤔 any objections or thoughts @jszwedko

**Comment by jszwedko** [comment]
Yeah, agreed. I'll see if I can get to this one.
