### ISSUE TITLE
Missing SSL CA certificates on `x86_64-unknown-linux-musl`

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#795]
Using `http` sink with HTTPS endpoints yields errors like

```
Aug 25 09:41:59.499  WARN sink{name="http"}: vector::sinks::util::retries: retrying after erro
r: error trying to connect: error:14007086:SSL routines:CONNECT_CR_CERT:certificate verify failed:../ssl/ssl_c
lnt.c:1121: (self signed certificate in certificate chain)
```

It means that there are no CA certificates that Vector can use. I think one possible solution to this problem would be to bundle CA certificates inside Vector executable to make it self-contained. However, it is not clear what would be the best way to implement it.

**Comment by LucioFranco** [comment]
@a-rodin do we just need a well known ca root? but I think bundling them is fine to do as well.

**Comment by a-rodin** [comment]
@LucioFranco Yes, what is needed is a CA root. In fact I ran it on a system that had CA certificates installed in `/etc/ssl/certs`, but still was getting this error. I think this might have something to do with configuration of LibreSSL which cannot find system-wide certificates.

The idea about bundling came to my mind because it allows to build, for example, Docker images  based on `scratch` and  having just a single executable inside. On the other hand, with bundling it would be necessary to update Vector binary to keep bundled CA certificates up-to-date.

**Comment by a-rodin** [comment]
It turns out that it is necessary to use [openssl-probe](https://github.com/alexcrichton/openssl-probe) crate to find system SSL certificates.

**Comment by LucioFranco** [comment]
@a-rodin yeah, that makes sense.
