### ISSUE TITLE
Lower `glob_minimum_cooldown` to 5s for k8s e2e tests

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#8009]
I recently merged #7980 to put the default back to the released value in 0.14.0 until we can take a look in #7840 however this results in the tests taking 5 hours rather than 15 minutes so it'd be nice to drop the cooldown just for the tests at least until we can evaluate and settle on a new default.

cc/ @spencergilbert @StephenWakely

**Comment by spencergilbert** [comment]
The big issue here is we can't set this in the "top level" configurations we use in testing because a couple of tests set the `kubernetesLogsSource` config for labels and selectors...

We actually concat these together rather than passing them both into helm with `-f`
