### ISSUE TITLE
Tutorial on https://vector.dev/docs/setup/installation/operating-systems/windows/ failed

### ISSUE THREAD

**Issue by ismoil-nosr** [timberio/vector#8016]
The tutorial on:
https://vector.dev/docs/setup/installation/operating-systems/windows/

Please specify in example Windows path, not linux. It took me 2 days to realize I need to double backslash
```yaml
# Host-level logs
[sources.logs]
type = "file"
# include = [ "/var/log/**/*.log" ] <--- NOT THIS
include = [ "C:\\Server\\example.com\logs\\*.log" ] # But THIS please
```

Thank you in advance

**Comment by spencergilbert** [comment]
Thanks, I'll get that corrected
