### ISSUE TITLE
https://vector.dev DNS_PROBE_FINISHED_NXDOMAIN

### ISSUE THREAD

**Issue by 3ks** [timberio/vector#8065]
I got `DNS_PROBE_FINISHED_NXDOMAIN` when I visite [vector.dev](https://vector.dev).

If you have some changes, fixed it, plz!

**Comment by binarylogic** [comment]
We are working on this now. Thanks for your patience.

**Comment by jszwedko** [comment]
We have a mirror here in the interim: https://vector-backup.netlify.app/

**Comment by JeanMertz** [comment]
See #8088.

**Comment by binarylogic** [comment]
This is resolved, please see https://github.com/timberio/vector/issues/8088#issuecomment-871678369
