### ISSUE TITLE
Ensure that the chart on artifacthub and kubeapps is up-to-date

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#8071]
It looks like it hasn't been updated since 0.11:

https://hub.kubeapps.com/charts/vector/vector
https://artifacthub.io/packages/helm/vector/vector

We should deploy the newest version and ensure it is updated (hopefully automatically) as part of each release.

It'd be nice to have some documentation for this in the vector repository too.

**Comment by spencergilbert** [comment]
TIL we publish to those...

**Comment by spencergilbert** [comment]
We're going to punt on kubeapps for now

**Comment by spencergilbert** [comment]
We've stopped publishing the `vector` chart after the 0.11 release

**Comment by spencergilbert** [comment]
Actually this seems intended @jszwedko - https://github.com/timberio/vector/blob/master/scripts/release-helm.sh#L54

Since `vector` also packages the unreleased aggregator chart, it's probably not wrong to consider it unreleased/nightly as well.

**Comment by jszwedko** [comment]
Talked with @spencergilbert and it seems this is indeed operating correctly: we are only publishing the `vector-agent` chart as stable right now. The `vector` and `vector-aggregator` charts are published only as nightlies as we haven't yet officially released them.

hub.kubeapps.com seems to be unmaintained: the repository submission form 404s.

I'll close this out.
