### ISSUE TITLE
Document that `internal_metrics` creates metrics with namespace of `vector`

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#8073]
Spun off from https://github.com/timberio/vector/issues/8056#issuecomment-870423183

Currently it isn't clear that the `internal_metrics` source sets the namespace to `vector` on metrics it creates.

**Comment by binarylogic** [comment]
I'd say this should just be an option with a default of `vector`. That basically self documents this.

**Comment by jszwedko** [comment]
> I'd say this should just be an option with a default of `vector`. That basically self documents this.

Agreed, good idea 👍
