### ISSUE TITLE
vector.dev Chat and documentation is down

### ISSUE THREAD

**Issue by gartemiev** [timberio/vector#8087]
Hi, your vector.dev domain is completely unreachable:
```
$ host vector.dev
$ 
```
Can you please check and tell what's going on? 

If you are about closing this product - We'll need to migrate to another solution then.

**Comment by JeanMertz** [comment]
Hi @gartemiev,

Sorry for the inconvenience. We are having some DNS issues, but the website will be back online soon.

Meanwhile, you can go to https://vector-backup.netlify.app

cc https://github.com/timberio/vector/issues/8065

**Comment by JeanMertz** [comment]
See #8088.

**Comment by binarylogic** [comment]
This is resolved, please see https://github.com/timberio/vector/issues/8088#issuecomment-871678369
