### ISSUE TITLE
vector.dev is temporarily unreachable

### ISSUE THREAD

**Issue by JeanMertz** [timberio/vector#8088]
Our website (https://vector.dev) is down due to ongoing DNS issues. We are working towards resolving those issues.

Meanwhile, you can use the following backup URL:

**https://vector-backup.netlify.app/**

**Comment by stappersg** [comment]
Wishing the team success with the repair.

Please keep us posted.

**Comment by chzmnky** [comment]
Good luck, I hope you're able to resolve this issue quickly.

The timing of this could not have been worse as it's cause our company great embarrassment with a potential customer who is laughing at us for proposing a solution that doesn't have a working website. I'll continue to fight hard for this as I think it's a phenomenal application, but this will have a very unfortunate impact on your reputation.

**Comment by binarylogic** [comment]
@chzmnky does https://vector-backup.netlify.app/ temporarily solve the issue for you? Yes, it is unfortunate, but the mirror should unblock access to docs. Is there anything else we can do? This is top priority for us.

**Comment by chzmnky** [comment]
@binarylogic, let me say that this kind of responsiveness is exactly the right thing you can do - thank you very much for directing me to a temporary location while you're working on the issue.

Let me throw it back at you the other direction. Is there anything that I as a community member might be able to do to assist you guys in getting things back on track?

**Comment by binarylogic** [comment]
This is resolved and vector.dev is now back online. We apologize for any inconvenience this may have caused. We've set up the appropriate alerts to prevent this in the future.

@chzmnky there's nothing you could have done, this was on us and won't happen again.

**Comment by stappersg** [comment]
Thanks for the repair.

> there's nothing you could have done, this was on us and won't happen again.

Please do  share the learning experience.

**Comment by binarylogic** [comment]
We lost management access to the domain as part of our acquisition with Datadog and the domain DNS became invalid. It was completely my fault. We've restored access and setup synthetic alerts to monitor this going forward.

**Comment by chzmnky** [comment]
I feel your pain, having dealt with these types of issues in past (DNS resolution, not being acquired by Datadog ;) Kudos on getting things back up and running.
