### ISSUE TITLE
Allow `--config` to be optional and let vector search for the config

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#812]
In the case of docker, I want to copy a config into `/etc/vector/vector.toml` and not have to supply the --config argument. This should allow seamless usage with automated systems.

**Comment by binarylogic** [comment]
Can you explain why this is needed in the case of docker? Is there not a way to provide command-line arguments?

**Comment by LucioFranco** [comment]
@binarylogic In the simple case of docker, I would like to use a volume link to pass the config in and just "run" the container without any specific commands or customizing the container.

Vector, in general, should just search the default paths for a config before failing. I think this provides a much better UX and we already have default config directories.

**Comment by ktff** [comment]
This a good enhancement of little work and noticeable benefit.

This case also happens in Kubernetes where the location of configuration occurs in two places. With this only one occurrence will remain, and as a bonus no arguments will need to be passed.
