### ISSUE TITLE
Tag `internal_metrics` metrics with host

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#8158]
Currently metrics reported by `internal_metrics` have no host information associated.  Being able to differentiate different vector instances upstream in, for example, Datadog will typically be needed. Users can apply tags afterwards with `remap`, but I think it'd be useful to automatically tag all metrics with `host` as we do with, for example, logs from the `stdin` source.

**Comment by bruceg** [comment]
Noting that the `host_metrics` source also tags all metrics with the current hostname.
