### ISSUE TITLE
Upgrade prost to 0.8

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#8208]
Tracking issue for upgrade.

Currently blocked by pulsar: https://github.com/wyyerd/pulsar-rs/pull/166

Will also fix https://github.com/timberio/vector/issues/8184

**Comment by Geal** [comment]
@jszwedko pulsar 4.0 has an updated prost (and a fix for instability of producers)

**Comment by jszwedko** [comment]
Thanks @Geal !

**Comment by jszwedko** [comment]
Covered by https://github.com/timberio/vector/pull/8401
