### ISSUE TITLE
New `gcp_cloud_storage` sink

### ISSUE THREAD

**Issue by trK54Ylmz** [timberio/vector#822]
Do you have any intention to add support for Google Cloud Storage as sink?

**Comment by binarylogic** [comment]
Thanks @trK54Ylmz. Yep! We're starting to focus on GCP services and will add this to the list. We'll update as we make progress.

**Comment by DannyLee12** [comment]
Happy to take this on as a new contributor?

Then happy to move onto other GCP Sources and sinks.

**Comment by binarylogic** [comment]
@DannyLee12 we'd love to have you do this. Let me know if you're planning on it and I can assign the issue.
