### ISSUE TITLE
Use of `statsd` tags with `aws_cloudwatch_metrics` 

### ISSUE THREAD

**Issue by gumieri** [timberio/vector#823]
Hi!

I've tried the `aws_cloudwatch_metrics` sink which is yet with no documentation, so excuse me if what I'm saying is already possible.

I'm interested of using vector to collect metrics from my Go web server application and sending it to the CloudWatch Metrics for scaling purposes. And I'm also interested in sending it to our data lake for the Science Data team. Because of the simplicity of the Vector I fell in love with it.

So I've tried the `aws_cloudwatch_metrics` and at the moment I was unable to use the "Dimensions" from it. I don't know if `statsd` is the best option for that but is what I'm using.

What I would suggest is to do something similar to the "[CloudWatch Agent](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-custom-metrics-statsd.html)":
```
MetricName:value|type|@sample_rate|#tag1:
  value,tag1...
```
Tags being the `key:value` for the "Dimensions".

**Comment by loony-bean** [comment]
Thanks @gumieri! Support for tags has been added few weeks ago, it's available in the `master` branch. Docs are in progress, sorry for the trouble.

You should be able to ingest StatsD metrics in DataDog [format](https://docs.datadoghq.com/developers/dogstatsd/datagram_shell/#datagram-format), which is I believe what CloudWatch Agent is using for tags. CloudWatch metrics sink then recognises the tags, and puts them into Dimensions.

Hope that helps!

**Comment by gumieri** [comment]
Thank you! I'm going to try it!

And thank you all for the great work!
