### ISSUE TITLE
Dnstap integration test is failing on CI

### ISSUE THREAD

**Issue by StephenWakely** [timberio/vector#8240]
For example [here](https://github.com/timberio/vector/runs/3047993826). We are seeing:

```
failures:

---- sources::dnstap::integration_tests::test_dnstap_raw_event stdout ----
Jul 12 15:24:59.565  INFO vector::sources::util::framestream: Unix socket receive buffer size modified to 425984.
Jul 12 15:24:59.565  INFO vector::sources::util::framestream: Unix socket buffer send size modified to 425984.
Jul 12 15:24:59.565  INFO vector::sources::util::framestream: Socket permissions updated to 0o777.
Jul 12 15:24:59.566  INFO vector::sources::util::framestream: Listening... path="/home/runner/work/vector/vector/tests/data/dnstap/socket/dnstap.sock1" type="unix"
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `2`', src/sources/dnstap/mod.rs:331:13
```

According to @jszwedko it is possible this test has been more flakey since #7788.

@j-bai do you have any ideas what could be causing this?

**Comment by j-bai** [comment]
Hi @StephenWakely , I've talked with @yunkunzhu, who had developed the test, and he will take a look at the issue.

**Comment by jszwedko** [comment]
Thanks @j-bai . Just a note that it doesn't always fail but I was able to get it to fail by running it in a loop until it did.

**Comment by j-bai** [comment]
Update on the progress: we have basically pinned down the direct cause of the test failure, and are working on a fix right now. We  should be able to create a PR on it soon.

**Comment by binarylogic** [comment]
Thanks @j-bai, we really appreciate you helping to maintain this!

**Comment by yunkunzhu** [comment]
Hi folks, the pull request has been created to fix this issue: https://github.com/timberio/vector/pull/8302. Thank you.
