### ISSUE TITLE
Allow the journald source to specifying include_matches/exclude_matches options

### ISSUE THREAD

**Issue by watawuwu** [timberio/vector#8255]
### Current Vector Version

```
$ vector --version
vector 0.14.0 (x86_64-apple-darwin 5f3a319 2021-06-03)
```

### Use-cases

There are include_units and exclude_units options in `Journald Source`.
These options are useful for specifying units, but not for specifying kernel/dmesg.

This means that if user uses include_units and exclude_units, user will not be able to collect kernel/dmesg.

I would like to narrow down the units to be collected to include the kernel log!

```toml
[sources.my_source_id]
type = "journald"
include_units = ["kubelet", "containerd"] # kernel/dmesg cannot be specified
```

### Attempted Solutions

I can use `Filter Transform` to achieve the same thing without include_matches/exclude_matches.

```
[transforms.node_filter]
type = "filter"
inputs = ["node"]
condition = '''
includes(["kubelet.service", "containerd.service"], ._SYSTEMD_UNIT) || ._TRANSPORT == "kernel"
'''
```

However, I believe that there are many users who would like to use these options, as the same options are available in other log collector.

- Fluent Bit
  - https://docs.fluentbit.io/manual/pipeline/inputs/Systemd
  - `systemd_Filter  _SYSTEMD_UNIT=kubelet.service`
  - `Systemd_Filter  _TRANSPORT=kernel`
- Fluentd(systemd plugin )
  - https://github.com/fluent-plugin-systemd/fluent-plugin-systemd
  - `matches [{ "_SYSTEMD_UNIT": "kubelet.service" }]`
  - `matches [{ "_TRANSPORT": "kernel" }]`
- Beats(Journalbeat)
  - https://www.elastic.co/guide/en/beats/journalbeat/master/configuration-journalbeat-options.html
  - ```
    include_matches:
    - "_SYSTEMD_UNIT=kubelet.service"
    - "_TRANSPORT=kernel"
    ```
- splunk(Journald input)
  - https://docs.splunk.com/Documentation/Splunk/8.2.1/Data/CollecteventsfromJournalD
  - `journalctl-filter =_SYSTEMD_UNIT=kubelet.service,_TRANSPORT=kernel`


### Proposal

<!---
If you have an idea for a way to address the problem via a change to Vector features, please describe it below.

In this section, it's helpful to include specific examples of how what you are suggesting might look in configuration files, or on the command line, since that allows us to understand the full picture of what you are proposing.

If you're not sure of some details, don't worry! When we evaluate the feature request we may suggest modifications as necessary to work within the design constraints of Vector.
-->

I propose to add `include_matches/exclude_matches` options to specify kernel/dmesg. These options allow user to specify the [Journal Field](https://manpages.debian.org/testing/systemd/systemd.journal-fields.7.en.html) and its value.

#### Configuration

An example of a configuration file is shown below.

```toml
[sources.my_source_id]
type = "journald"
# include_matches type: HasMap<String, HashSet<String>>
include_matches._TRANSPORT = ["kernel"]
```

By adding this option, you can reduce the amount of log collection by excluding certain `PRIORITIY`.

```
[sources.my_source_id]
type = "journald"
exclude_matches.PRIORITY = ["DEBUG", "INFO"]
```

`include_units/exclude_units` and `include_matches/exclude_matches` can be used simultaneously. Internally, `include_units/exclude_units` is handled the same way as `(include|exclude)_matches._ SYSTEMD_UNIT = ["xx",...]`.

```
[sources.my_source_id]
type = "journald"
# Ok!!
include_units = ["kubelet", "containerd"] # eqaul include_matches._SYSTEMD_UNIT = ["kubelet.service", "containerd.service"]
include_matches._TRANSPORT = ["kernel"]
```
This specification allows for backward compatibility.

remap(vrl) is very flexible and useful.
So, if you want to activate remap in the future, or if you want to keep source simple, this proposal may be redundant.

Please comment on this proposal!
If the response is good, I can implement it myself.

### References

- #6508
- #3680

### Notes
- About systemd 'ProtectKernelLogs=yes`
  - I haven't checked, but according to the [comments](https://github.com/timberio/vector/issues/3680#issuecomment-796001318), user can't do kernel/dmesg if user are running vector from systemd. I can collect kenrel/dmesg messages because running vector by container.

**Comment by jszwedko** [comment]
@bruceg would you mind taking a look at this proposal? I think you are most familiar with the journald source.

**Comment by bruceg** [comment]
@jszwedko I think this makes sense, and would be fairly low complexity to implement from what I can tell.

**Comment by jszwedko** [comment]
👍 thanks for taking a look @bruceg 

@watawuwu we'd be happy to review a PR implementing the proposal if you like!
