### ISSUE TITLE
Working example for manual x86_64-unknown-linux-musl build with docker

### ISSUE THREAD

**Issue by moschroe** [timberio/vector#826]
I wanted to build vector for x86_64-unknown-linux-musl locally, using the builder image created using `scripts/ci-docker-images/builder-x86_64-unknown-linux-musl/Dockerfile`.

I had to guess the invocation by reading `.circleci/config.yml` since I do not run circleci on my workstation, so this it what I came up with:
`docker run --rm -ti -v "$(readlink -f .):/tmp/build" --user 0 --env 'VERSION=0.3.0' --env RUST_LTO=lto --env 'TARGET=x86_64-unknown-linux-musl' --workdir /tmp/build builder-x86_64-unknown-linux-musl:latest make build-archive`
That seems to have worked, the build succeeded.

`setup/installation/manual/from-source` says this:

> You can view an example of this in the musl builder Docker image.

I think it would be good to have the above documented or at least referenced at that place.

**Comment by LucioFranco** [comment]
I think that would be a good idea to document! I think it could go in some advanced build section.

**Comment by a-rodin** [comment]
This can be done after #946 to not force the users to build the toolchain locally.

**Comment by a-rodin** [comment]
After https://app.circleci.com/jobs/github/timberio/vector/42402 is merged, It would possible to build the current `master` branch locally by running

```bash
PASS_FEATURES="jemallocator rdkafka rdkafka/cmake_build leveldb leveldb/leveldb-sys-3 shiplift/unix-socket openssl/vendored" ./scripts/docker-run.sh builder-x86_64-unknown-linux-musl make build
```

The caveat is that the process would take around 2 hours on a 4-core machine because of the need to build LLVM.

**Comment by a-rodin** [comment]
After https://github.com/timberio/vector/issues/1320 is done, the approach from the comment above can even lose its downside of the slow compilation times.
