### ISSUE TITLE
`Event` should know how big it is

### ISSUE THREAD

**Issue by blt** [timberio/vector#8272]
Consider that in #8263 I've [demonstrated](https://github.com/timberio/vector/issues/8263#issuecomment-879417074) that the byte size measurement of the blackhole sink is a non-trivial cost center for vector. The `Event` should evolve a `len` or `byte_size` or similar method that tallies up the in-memory byte size of the `Event`. This implies we'd need to maintain this value as we manipulate the event.

**Comment by jszwedko** [comment]
There was some discussion around this in https://github.com/timberio/vector/pull/4705 . I think we can just grow a dedicated counting method as you suggest.
