### ISSUE TITLE
No "latest-<distro>" tags available through docker hub

### ISSUE THREAD

**Issue by rwfeatherf5** [timberio/vector#829]
Hey, going though the getting started guide and it seems the recommendations for docker in [the docs](https://github.com/timberio/vector/blob/master/docs/setup/installation/platforms/docker.md) don't match current available tags. Apologies if I'm missing something.

Running `docker run -v $PWD/vector.toml:/etc/vector/vector.toml:ro timberio/vector:latest-alpine` gets me:

```
Unable to find image 'timberio/vector:latest-alpine' locally
docker: Error response from daemon: manifest for timberio/vector:latest-alpine not found: manifest unknown: manifest unknown.
See 'docker run --help'.
```

https://hub.docker.com/r/timberio/vector/tags at the time of writing only has a single "latest" image, none of the distro specific ones.

![image](https://user-images.githubusercontent.com/54560579/64215362-30600d80-ce69-11e9-9374-d9a00e171ee7.png)

Not a big deal, I would made a PR to update the docs myself but I'm just kicking the tires right now and its not clear what's out of date: the docs, or the Docker releases.

**Comment by LucioFranco** [comment]
@rwfeatherf5 hi! I believe this change was introduced after our last actual release of `0.3` so the ci job to build the latest containers has not run yet. I believe we should be getting `0.4` out soon.

**Comment by binarylogic** [comment]
Thanks for reporting @rwfeatherf5 , this has been resolved. The `0.4.0-*` and `latest-*` images have been updated as well:

https://cloud.docker.com/u/timberio/repository/docker/timberio/vector
