### ISSUE TITLE
Website configuration examples for filter component has `null` for `inputs` and `type`

### ISSUE THREAD

**Issue by ross** [timberio/vector#8304]
### Vector Version

Website as of 2021-07-14T00:30:58Z

### Expected Behavior

Configuration example for the filter component should have valid `inputs` and `type`.

URL: https://vector.dev/docs/reference/configuration/transforms/filter/#examples

### Actual Behavior

```json
{
  "condition": ".level == \"debug\"",
  "inputs": null,
  "type": null
}
```

This is closely related to https://github.com/timberio/vector/issues/8305.

**Comment by lucperkins** [comment]
Fixed by #8274
