### ISSUE TITLE
pushing to aws elasticsearch

### ISSUE THREAD

**Issue by iam4x** [timberio/vector#833]
Hi 👋 	

I'm trying to setup vector as replacement of our EC2 ELK stack with running vector + AWS ElasticSearch service.

When I'm pushing data to AWS ElasticSearch with the sink I'm having errors from elasticsearch:

```
[2019-09-05T03:41:17,601][WARN ][r.suppressed ] [5c6c32c7526a79f917cbc594e5e7bcde] path: __PATH__ params:
{}

com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 31)): only regular white space (\r, \n, \t) is allowed between tokens
at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@56b4b262; line: 1, column: 2]
```

To debug, I tried to use the `console` sink and it works as expected. I'm seeing a good JSON.

Here's my `vector.toml` config as example:

```
data_dir = "/var/lib/vector"

[sources.api_log_files]
  type = "file"
  exclude = []
  include = ["/var/log/mobileclub/*.log"]

[transforms.first_pattern_grok]
  type = "grok_parser"
  inputs = ["api_log_files"]
  pattern = "%{TIMESTAMP_ISO8601:timestamp} %{WORD:level} \\[%{UUID:requestId}] \\[Auth]: %{NOTSPACE:user} as %{WORD:role}"

[sinks.elasticsearch]
   type = "elasticsearch"
   inputs = ["first_pattern_grok"]
   host = "XXXX"
   doc_type = "_doc" # default
   index = "vector-%F" # default
```

I'm suspecting colorized string to be the culprit, for instance here's a JSON logged in the console:

```
{"message":"2019-09-05T10:49:46.642Z \u001b[32mINFO\u001b[39m [3248d8e2-5882-43f7-a5af-927f2769f7ba] Started GET /graphql - {\"params\":{},\"body\":{\"query\":\"undefined\"}}","timestamp":"2019-09-05T10:49:48.069807300Z","file":"/var/log/mobileclub/api.log","host":"cee4e211c10b"}
```

Would it be possible to remove colorized strings with a transform from Vector?

**Comment by lukesteensen** [comment]
Hi @iam4x! Sorry for the trouble you're having here.

Could you try setting `compression = "none"` in your sink config? We use gzip by default but that may not be supported by the AWS ES service.

**Comment by mre** [comment]
The error message mentions character code 31, which is the "unit separator". [Here](https://unix.stackexchange.com/a/128021) is an explanation. @iam4x, if `compression = "none"` doesn't help, it could also be related to invalid input data that contains control characters.

**Comment by iam4x** [comment]
Alright thank you, `compression = "none"` and removing the unix colors from the logs worked  👍
