### ISSUE TITLE
Nightly v0.15 breaks the CentOS 7 compatibility?

### ISSUE THREAD

**Issue by Yohann-44** [timberio/vector#8336]
### Vector Version

```
vector 0.15.0 nightly
```

### Vector Configuration File

```toml

```

### Expected Behavior

When I install the v0.15 nightly, the program works fine expect for the unit file. So I can't use the systemd. I use CentOS7 and the systemd v219. This systemd aren't compatible with the sandboxes. 

I didn't have any problem with the Vector v0.14. Maybe, it's a bug or a dependency should be added?

### Actual Behavior
No dependency specified during installation

**Comment by spencergilbert** [comment]
Presumably would be caused by https://github.com/timberio/vector/commit/136cb6c7148a302c550254d7abb446ab121359f5#diff-eb88b3e980d44c368e57f48428bd5d4be1d8fc62cbc2c3ac6a4e86c8a4b52444

**Comment by jszwedko** [comment]
Apologies for the breakage @Yohann-44 . We've replaced the old unit file until we are able to do more testing with the new one.
