### ISSUE TITLE
Add Docker image based on `scratch`

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#834]
Some people package their statically built executables for Docker using the `scratch` base image. Although it has both advantages and disadvantages (see for example [this discussion](https://www.reddit.com/r/golang/comments/7fs0lb/if_you_are_compiling_go_binaries_then_just_use/)), those who want the Vector image to have smallest possible size would like it.

This can be implemented by packaging the executable for `x86_64-unknown-linux-musl` and, if not bundled inside binary itself, CA certificates for it (#795).

**Comment by binarylogic** [comment]
Noting: we discussed this today and @a-rodin has reservations on doing this. The size difference between this and our `alpine` release would be negligible. @a-rodin do you mind providing more detail and then closing this?

**Comment by a-rodin** [comment]
Yeah, the size overhead of `alpine` image is around 2 megabytes, which is roughly 20% of the size of Vector binary. So the benefits of using `scratch` are negligible, especially if we anyway need to provide such dependencies as SSL CA certificates and timezone data.
