### ISSUE TITLE
Package RPM: useradd group vector exists

### ISSUE THREAD

**Issue by Yohann-44** [timberio/vector#8361]
### Vector Version

```
v0.15 
```

### Vector Configuration File

```toml

```

### Expected Behavior

I use the RPM package but it seems that there is an error in the installation.

### Actual Behavior
In your configuration RPM ( vector/distribution/rpm/vector.spec), you have changed the command line to add the user by creating directly the group with the same name of the user (line 66).
In the RPM package, just before the previous command line (line 64), you have already create the group. So, the installation fails.

### Example Data

```
Downloading packages:
vector-0.15.0-1.x86_64.rpm                                                                      |  38 MB  00:00:02     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : vector-0.15.0-1.x86_64                                                                              1/1 
useradd: group vector exists - if you want to add this user to that group, use -g.
chown: invalid user: 'vector'
usermod: user 'vector' does not exist
  Verifying  : vector-0.15.0-1.x86_64                                                                              1/1 
```

**Comment by jszwedko** [comment]
Ah, apologies for this @Yohann-44 . We'll fix that.

**Comment by shumphrey** [comment]
Given the nature of this bug, is the intention to release 0.15.1 on the 27th of July as per milestone or before?

**Comment by jszwedko** [comment]
Apologies for the delay, this is targeted for 0.15.1 which'll be released on Tuesday.
