### ISSUE TITLE
Support parsing empty lines in file source

### ISSUE THREAD

**Issue by her-eytan** [timberio/vector#8363]
### Current Vector Version
```
0.15
```

### Use-cases
Streaming files from one location to another. File source discards empty lines, resulting in destination files being different than source files.

Suppose we have the following toml config:
```
[sources.my_file_source]
	type = "file"
	include = ["path/to/file"]

[sinks.out_file]
	type = "file"
	inputs = ["my_file_source"]
	path = "/path/to/destination"
	encoding.codec = "text"
```

then, an input file like:
```
1
2

3


4
```

will be transformed into:
```
1
2
3
4
```

### Proposal
Add an "allow_empty" option to file source, which will allow emitting empty lines.

### References
Proposed solution by @ross:
https://github.com/timberio/vector/compare/master...ross:file-source-allow-empty?expand=1

**Comment by jszwedko** [comment]
Thanks for this report @her-eytan ! I think this is actually a bug and that empty lines should not be ignored. I'll mark it as such.

**Comment by ross** [comment]
If it doesn't need to be an option the fix is just a 3-line delete :grin:
