### ISSUE TITLE
Drop/Filter a Specific event based on conditions without receiving it in Vector

### ISSUE THREAD

**Issue by mehta-ankit** [timberio/vector#8365]
### Current Vector Version

```
vector 0.15.0
```

### Use-cases

We use `aws_s3` as a source for our vector aggregator and have set multiple SQS Queue's as source for it (using `sqs.queue_url` config). Each queue can be in different regions (us-east-1, us-east-2). Our vector-aggregator is deployed in K8s clusters only in us-east-1 region.

For privacy/security concerns we do not want to pull certain sensitive logs outside their region. This means if we use transform/filter logic we would be filtering on log events in vector deployment itself (which could mean us-east-2 log was moved outside its region before filtering it). Is there a way to do this without receiving it in Vector ??

Discord thread link: 

- https://discord.com/channels/742820443487993987/753400475545501836/866697346359492638
- https://discord.com/channels/742820443487993987/753400475545501836/866705831559299102

### Attempted Solutions

Haven't tried it but one solution could be to deploy Vector aggregator to each region so filtering can happen at the regional level and then log events can be sent to its Sink (loki in our use case)

### Proposal

If possible a way to not pull logs that we do not want to (could be based on some conditional logic on the log event at the source).

**Comment by jszwedko** [comment]
Hi @mehta-ankit !

Vector actually expects to have the buckets be in the same region as the corresponding SQS queue containing the notifications so I think you'll find you need to deploy a separate vector instance to each region anyway.

**Comment by jszwedko** [comment]
@mehta-ankit Ah, right, apologies, you could do it that way with multiple `sources`; one per region.

Can you describe the problem a bit more? Do you not want to pull from specific buckets? Or specific object prefixes? What filters would you like to apply?

**Comment by mehta-ankit** [comment]
@jszwedko So the issue i was trying to bring up was that since filtering happens on Vector pod itself, if Vector is deployed in 1 region and pulling logs from all other regions it means that to figure out sensitive vs non sensitive logs we will have to pull them out of their regions. This breaks some controls and requirements users can have.

So i was trying to see if Vector can on the fly figure out some filtering when reading from S3 level (but i do believe it kind of does not make sense 😆 ). Spencer mentioned at least open an issue, hence i did that.

For now we are looking to solve this either by running vector aggregators in each region to do filtering (so logs dnt leave their region) or make the bucket structure sensitive/non-sensitive to Central vector in one single region can only read non sensitive logs.

**Comment by jszwedko** [comment]
@mehta-ankit gotcha, yeah, I think I understand. Just to rephrase:

You want to do some sort of pattern matching on the logs to split them into sensitive and not-sensitive. You'd like to have Vector only process the not-sensitive logs.

> For now we are looking to solve this either by running vector aggregators in each region to do filtering (so logs dnt leave their region) or make the bucket structure sensitive/non-sensitive to Central vector in one single region can only read non sensitive logs.

I think these are the best approaches. You can either run the an aggregator in each region or ensure the logs are split into separate buckets or prefixes and have Vector only pull from the non-sensitive set.

I could see maybe using Athena to query the S3 buckets to only fetch lines that match certain filters but Vector doesn't currently have support for querying Athena.

**Comment by mehta-ankit** [comment]
Yes @jszwedko you got my concern absolutely right 👍🏽 . Thanks

Also thanks for showing confidence in our approach 😃 .

**Question**: With Athena, would we run it one per region and then if allowed (if vector allows Athena as a source) we could point central Vector to Athena as a source. Right ?

**Comment by jszwedko** [comment]
@mehta-ankit great!

> **Question**: With Athena, would we run it one per region and then if allowed (if vector allows Athena as a source) we could point central Vector to Athena as a source. Right ?


Right, I think it'd be a similar situation where you'd have one Vector `source` per region but the query itself would happen within Athena in the target region and then only the results streamed out.

**Comment by mehta-ankit** [comment]
@jszwedko So at this point i believe we can close this issue, unless you want to keep it open for some reason (maybe to link it to another issue to add support for Athena(or any other such service)).

**Comment by jszwedko** [comment]
@mehta-ankit 👍 I opened https://github.com/timberio/vector/issues/8423 to track adding an Athena source. I'll close this issue out. Thanks for the discussion!
