### ISSUE TITLE
FEATURE REQUEST: Read from UDS Socket

### ISSUE THREAD

**Issue by tdesrochers** [timberio/vector#837]
We currently utilize another shipper and it has the ability to read from Unix Domain Sockets (UDS).  This is helpful when reading from Journal/Kernel and other sockets that get created for logging. 

https://nxlog.co/documentation/nxlog-user-guide/im_uds.html
https://www.elastic.co/guide/en/logstash/current/plugins-inputs-unix.htmlhttps://docs.fluentd.org/input/unix

This feature would keep Vector in line with some of the larger players in the market

**Comment by binarylogic** [comment]
@tdesrochers thanks! I'm going to close this in favor of https://github.com/timberio/vector/issues/837. Let me know if this isn't the same thing.

Appreciate the feedback!

**Comment by binarylogic** [comment]
Ah sorry, meant https://github.com/timberio/vector/issues/339
