### ISSUE TITLE
Vector does not fully send large logs.

### ISSUE THREAD

**Issue by k8s-comandante** [timberio/vector#8398]
Hello everyone!
I use a bundle of vector - loki - grafana to monitor logs in kubernetes.
Service logs are written to json, on the vector side I have a json log parser configured and sent to loki, when viewing the logs in Grafana I see incomplete messages, who can tell me where to look? Continuation of logs further ... no.

![photo_2021-07-16 11 38 33](https://user-images.githubusercontent.com/64585375/126434121-fe74897f-7c95-434a-9873-650ca0c77b6a.jpeg)

**Comment by jszwedko** [comment]
Hi @k8s-comandante !

Could you share the Vector config you are using? I'd recommend testing by sending the lines to a `file` sink to verify if they are cut off there as well. That would help narrow down where the truncation could be happening.

Have you verified the lines are not cut off in the source log files?

I see that Loki has a [`max_line_size` configuration](https://grafana.com/docs/loki/latest/configuration/). Do you have that configured?

**Comment by k8s-comandante** [comment]
@jszwedko thanks a lot for the help, the problem was from the side of the logs in the container.

**Comment by jszwedko** [comment]
Thanks for following up @k8s-comandante ! I'll close this, but don't hesitate to let us know if you run into any other issues.
