### ISSUE TITLE
Allow newly added `host` and `pid` tags on internal logs and metrics to be disabled

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#8407]
A user reported that they were using the `prometheus_scrape` sink and allowing `telegraph` to set the `host` to the IP of machine Vector was running on. The addition of the `host` tag on `internal_metrics` broke this flow.

Users can delete the added tag via:

```
del(.tags.host)
```

But they requested to be able to disable it on the component as well.

**Comment by spencergilbert** [comment]
Mentioned in slack, copying here for permanence - I think adopting a common ability to toggle fields/tags across sources makes sense. For example, the `kubernetes_logs` source sets a number of fields on events and users may want to opt out of some of them. Today it can be done on the `kubernetes_logs` source by setting the (example) `annotation_fields.container_image = ""` which (somewhat unintentionally) stops Vector from enriching the event with that field.

We could expose a similar `tags` key on metrics sources to and instruct users to set the key to `""` or `null` (depending on config language) to opt out of particular tags. I like the idea of having a unified interface for this, and perhaps a common `fields` for logs makes sense as well.

**Comment by jszwedko** [comment]
Closed by

https://github.com/timberio/vector/pull/8444
https://github.com/timberio/vector/pull/8440
