### ISSUE TITLE
Spec out raise reliability confidence project

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#843]
We need a high-level plan/specification for how we want to complete this project. Afterwards, we'll create all of the issues representing this work.

**Comment by lukesteensen** [comment]
@LucioFranco 

> One of the things I was thinking about is how we might be able to integrate this into our workflow? How do you see us reviewing reports and ensuring new PRs don't change behavior in unexpected ways?

I don't think we should expect to be able to gate all PRs on "passing" this environment. Ideally, issues found in this environment would be translated to the normal test suite to protect against regressions (similar to fuzzing or property-based tests). We can definitely have the ability to run these envs with arbitrary versions of vector (e.g. one built from a PR), but that'd probably be something we decide to do for particularly relevant PRs only.

---

@a-rodin 

> In addition, I think it might be worth to fuzz Vector with AFL/libfuzz to find possible crashes or vulnerabilities on malformed input data.

Definitely agree this would be interesting. The requirements are a bit different (probably simpler), but we should be able to reuse most all of the same infrastructure.

Fun fact: we've already done some targetted fuzzing of the `tokenizer` parser and added some unit test based on crashes it found. This is another approach that I think can be super effective (i.e. more focused fuzzing of individual parser components).

> It could be interesting to monitor not only gaps/reordering, but also how often the same data happens to be sent two or more times according to Vector's "at least once" delivery guarantees.

Agreed! The goal will be a general purpose diff of the input and output, so duplicates should be caught as well.

**Comment by loony-bean** [comment]
This is good! Maybe we can add test coverage reporting into the plan?

**Comment by LucioFranco** [comment]
@loony-bean I'm not too sure we would get much out of coverage reporting, I've seen it be very flaky in rust projects and hard to tune to make it a productive addition imo.

**Comment by binarylogic** [comment]
@lukesteensen I think this is done, but we never created issues for the work here. Let's do this on Monday and close this out.
