### ISSUE TITLE
Manage the underlying EKS infrastructure for CI

### ISSUE THREAD

**Issue by spencergilbert** [timberio/vector#8433]
> Testing with Terraform and eksctl, it would take ~10-15minutes to create a clean EKS cluster. That seems like too long for a "run on every PR" CI job, but less of an issue if we just run it for releases/tags or nightly.

> A middle-road here could be having the cluster re-terraformed regularly (daily/weekly/etc)

> There is no clean way to truly isolate workloads on the same cluster, there will be some contamination due to co-location on the nodes. If our requirement is zero contamination we'd need cleanly built clusters (imho)

> For the local usage, it should be trivial - we can already run the e2e tests at an arbitrary cluster. You'd just need to get an appropriate kubeconfig for the remote cluster

**Comment by spencergilbert** [comment]
@jszwedko I guess to minimize scope here we can just start with a static cluster and introduce rebuilds down the line if we begin to encounter issues due to any cross-contamination - does that sound reasonable to you?

**Comment by jszwedko** [comment]
> @jszwedko I guess to minimize scope here we can just start with a static cluster and introduce rebuilds down the line if we begin to encounter issues due to any cross-contamination - does that sound reasonable to you?

👍 that sounds good to me. We'll probably just need to update the tests to use separate namespaces to not step on each other.
