### ISSUE TITLE
`splunk_hec` source does not tolerate trailing spaces/newlines in event data

### ISSUE THREAD

**Issue by hhromic** [timberio/vector#8459]
### Vector Version

```
vector 0.15.0 (x86_64-unknown-linux-gnu 994d812 2021-07-16)
```

### Vector Configuration File

```yaml
sources:
  splunk:
    type: splunk_hec

sinks:
  blockhole:
    type: blackhole
    inputs:
      - splunk
```

### Expected Behavior

When sending [batched events](https://docs.splunk.com/Documentation/Splunk/latest/Data/FormateventsforHTTPEventCollector#Example_3:_Batched_data) to the Vector Splunk HEC Source, they should be processed and an OK response returned.

For example:
```
$ curl http://localhost:8088/services/collector/event -d '{"event":"one"}{"event":"two"}{"event":"three"}'
[123,34,116,101,120,116,34,58,34,83,117,99,99,101,115,115,34,44,34,99,111,100,101,34,58,48,125]
```

### Actual Behavior

When there are trailing spaces in the batched data, Vector returns an HTTP 400 error (*invalid data format*):
```
$ curl http://localhost:8088/services/collector/event -d '{"event":"one"}{"event":"two"}{"event":"three"} '
"{\"text\":\"Invalid data format\",\"code\":6,\"invalid-event-number\":3}"
```

The errors reported on the Vector side are:
```
Jul 26 18:48:33.102 ERROR source{component_kind="source" component_name=splunk component_type=splunk_hec}: vector::internal_events::splunk_hec::source: Invalid request body. error=Custom { kind: UnexpectedEof, error: Error("EOF while parsing a value", line: 1, column: 1) } internal_log_rate_secs=10
Jul 26 18:48:33.102 ERROR source{component_kind="source" component_name=splunk component_type=splunk_hec}: vector::internal_events::splunk_hec::source: Error processing request. error=InvalidDataFormat { event: 3 } internal_log_rate_secs=10
```

Note that *leading* spaces are processed without a problem:
```
$ curl http://localhost:8088/services/collector/event -d ' {"event":"one"} {"event":"two"} {"event":"three"}'
[123,34,116,101,120,116,34,58,34,83,117,99,99,101,115,115,34,44,34,99,111,100,101,34,58,48,125]
```

It can be argued that non-batched data is also affected:
```
$ curl http://localhost:8088/services/collector/event -d '{"event":"one"} '
"{\"text\":\"Invalid data format\",\"code\":6,\"invalid-event-number\":1}"
```

### Additional Context

We are trying to use the official [Splunk Kafka Connector](https://github.com/splunk/kafka-connect-splunk) to send data to Vector from Kafka and we stumbled upon this problem. These are the errors seen in Kafka Connect:
```
[2021-07-26 16:51:53,278] ERROR failed to post events resp="{\"text\":\"Invalid data format\",\"code\":6,\"invalid-event-number\":500}", status=400 (com.splunk.hecclient.Indexer),
[2021-07-26 16:51:52,875] ERROR failed to post events resp="{\"text\":\"Invalid data format\",\"code\":6,\"invalid-event-number\":500}", status=400 (com.splunk.hecclient.Indexer),
[2021-07-26 16:56:41,061] ERROR failed to post events resp="{\"text\":\"Invalid data format\",\"code\":6,\"invalid-event-number\":500}", status=400 (com.splunk.hecclient.Indexer)
```

Note that by default the Splunk Kafka Connector sends batches of size `500`.
It seems that this connector is sending events with a trailing space.

On the Vector side we receive these error messages:
```
Jul 26 16:56:30.783 ERROR source{component_kind="source" component_name=splunk component_type=splunk_hec}: vector::internal_events::splunk_hec::source: Internal log [Error processing request.] has been rate limited 798 times.,
Jul 26 16:56:30.783 ERROR source{component_kind="source" component_name=splunk component_type=splunk_hec}: vector::internal_events::splunk_hec::source: Error processing request. error=InvalidDataFormat { event: 500 } internal_log_rate_secs=10,
Jul 26 16:56:30.796 ERROR source{component_kind="source" component_name=splunk component_type=splunk_hec}: vector::internal_events::splunk_hec::source: Internal log [Invalid request body.] has been rate limited 799 times.,
Jul 26 16:56:30.796 ERROR source{component_kind="source" component_name=splunk component_type=splunk_hec}: vector::internal_events::splunk_hec::source: Invalid request body. error=Custom { kind: UnexpectedEof, error: Error("EOF while parsing a value", line: 2, column: 0) } internal_log_rate_secs=10,
Jul 26 16:56:30.803 ERROR source{component_kind="source" component_name=splunk component_type=splunk_hec}: vector::internal_events::splunk_hec::source: Internal log [Invalid request body.] is being rate limited.
```

**Comment by jszwedko** [comment]
Thanks fro this report @hhromic ! Seemingly it should be an easy fix.

**Comment by hhromic** [comment]
I went to check the Splunk Connector's source code and found out events are separated by newlines:
https://github.com/splunk/kafka-connect-splunk/blob/92ef8baf577bac2eb4fb611e313e4458f28d9905/src/main/java/com/splunk/hecclient/Event.java#L66

So I checked for this particular separator in Vector and it seems to be working fine:
```
$ echo -en '\n{"event":"one"}\n\n{"event":"two"}\n\n\n' | curl http://localhost:8088/services/collector/event -d@-
[123,34,116,101,120,116,34,58,34,83,117,99,99,101,115,115,34,44,34,99,111,100,101,34,58,48,125]
```

I will see if I can capture the raw request that the connector sends to have the exact offending payload.

**Comment by hhromic** [comment]
> So I checked for this particular separator in Vector and it seems to be working fine:
> 
> ```
> $ echo -en '\n{"event":"one"}\n\n{"event":"two"}\n\n\n' | curl http://localhost:8088/services/collector/event -d@-
> [123,34,116,101,120,116,34,58,34,83,117,99,99,101,115,115,34,44,34,99,111,100,101,34,58,48,125]
> ```
> 

I can confirm now that the above `curl` invocation is **wrong**. I should have used `--data-binary` instead:
```
$ echo -en '\n{"event":"one"}\n\n{"event":"two"}\n\n\n' | curl http://localhost:8088/services/collector/event --data-binary @-
"{\"text\":\"Invalid data format\",\"code\":6,\"invalid-event-number\":2}"
```

Therefore I can fully confirm now (after inspecting the requests made by the Splunk Kafka Connector) that the problem are trailing spaces and/or trailing new-lines (the case of the Splunk Connector).

Here is a simple Python program that sends a request using the same payload as the Splunk Connector:
```python
from urllib.request import Request, urlopen

payload = b'{"time":1626886217.296000,"index":"my_index","event":{"field":"value"}}\n{"time":1626886218.318000,"index":"my_index","event":{"field":"value"}}\n{"time":1626886218.318000,"index":"my_index","event":{"field":"value"}}\n{"time":1626886218.318000,"index":"my_index","event":{"field":"value"}}\n{"time":1626886218.319000,"index":"my_index","event":{"field":"value"}}\n'

request = Request("http://localhost:8088/services/collector/event", payload)

with urlopen(request) as response:
    print(response.info())
```

This will fail when sent to Vector:
```
urllib.error.HTTPError: HTTP Error 400: Bad Request
```
And Vector will error out the following as stated before:
```
Jul 27 16:29:00.703 ERROR source{component_kind="source" component_name=splunk component_type=splunk_hec}: vector::internal_events::splunk_hec::source: Invalid request body. error=Custom { kind: UnexpectedEof, error: Error("EOF while parsing a value", line: 2, column: 0) } internal_log_rate_secs=10
Jul 27 16:29:00.703 ERROR source{component_kind="source" component_name=splunk component_type=splunk_hec}: vector::internal_events::splunk_hec::source: Error processing request. error=InvalidDataFormat { event: 5 } internal_log_rate_secs=10
```

Hope this is sufficient to easily debug the issue on Vector :)

**Comment by jszwedko** [comment]
Awesome, thank you for the reproduction script! That should make it even easier to fix and verify.

**Comment by hhromic** [comment]
@jszwedko I noticed that this issue was unstaged from the (already released) `0.16.0` release. Do you think it would be possible to address it in a minor patch release? Unfortunately the `splunk_hec` source is currently unusable with the official Splunk Kafka Connect Plugin due to this problem :(

I mean no rush, but hoping you could take a look on this in your tight agenda guys :) 🤞

**Comment by jszwedko** [comment]
Thanks for the prompt @hhromic ! I added it to the next milestone. We usually reserve patch releases for only regressions, but we should be able to get it into the next minor release.

**Comment by hhromic** [comment]
@jszwedko much appreciated!
More co-workers have been taking interest in Vector since we demonstrated it some time ago. Congratulations again for all the hard work and really useful piece of software that Vector is.

**Comment by hhromic** [comment]
@jszwedko I just tested now the `timberio/vector:nightly-distroless-libc` Docker image which contains your fix.
Can fully confirm that all is working perfectly fine now! 🚀 🎊 💯 

Thanks for your dedication and committment to the community, much appreciated.

**Comment by jszwedko** [comment]
Awesome, thanks for verifying @hhromic !
