### ISSUE TITLE
Support maxUnavailable as a percentage in the vector-agent Helm Chart

### ISSUE THREAD

**Issue by sidewinder12s** [timberio/vector#8461]
### Current Vector Version

```
master
```

### Use-cases

Support maxUnavailable as a percentage in the vector-agent Helm Chart. Right now it only supports integers.

### Attempted Solutions

Tried to set a percentage, does not work.

### Proposal

Update the maxUnavailable parameter to support percentages (most likely just need to ensure we use a string) or remove it and just make the entire rolling update config values that users pass in.

### References

Could do something similar to what the aws-vpc-cni plugin has done: https://github.com/aws/eks-charts/blob/master/stable/aws-vpc-cni/templates/daemonset.yaml#L9

**Comment by spencergilbert** [comment]
Issue moved to [timberio/helm-charts #7](https://github.com/timberio/helm-charts/issues/7) via [**ZenHub**](https://www.zenhub.com/)
