### ISSUE TITLE
Move static pod Label into podLabels default value of vault-agent helm chart

### ISSUE THREAD

**Issue by sidewinder12s** [timberio/vector#8463]
### Current Vector Version

```
master
```

### Use-cases

I'd like Vector to collect it's own logs for shipment when using the vector-agent helm chart.

### Attempted Solutions

This is set statically within the Chart where it cannot be overridden without forking.

### Proposal

Move `vector.dev/exclude: "true"` Daemonset Label into `podLabels` as a default value.

This keeps the existing behavior but will allow users to override/extend if desired.

**Comment by spencergilbert** [comment]
I think our preferred method of self collection would be enabling the [`internal_logs` source](https://vector.dev/docs/reference/configuration/sources/internal_logs/) which should better avoid any looping (collecting messaging vector writes to stdout and continuing to do so, nesting deeper and deeper into a `message` key).

@sidewinder12s I think this source would better fit the use case

**Comment by spencergilbert** [comment]
Issue moved to [timberio/helm-charts #6](https://github.com/timberio/helm-charts/issues/6) via [**ZenHub**](https://www.zenhub.com/)
