### ISSUE TITLE
Move helm chart into `timberio/helm-charts`

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#8477]
Copying notes:

* Move charts to github.com/timberio/helm-charts
* Keep CI integration tests in Vector
* Update README on to include Vector
* Migrate chart releases to fall in  line with Datadog
* Update Vector website docs to use new repo URL
* Add CI checks in new helm-charts repo (CT)
* Upgrade guide/highlight to use new charts

**Comment by spencergilbert** [comment]
Many of these will come "for free" when we migrate to their repository, as can be seen in my initial PR work [here](https://github.com/spencergilbert/dd-helm-charts/actions/runs/1073001683)

Once the RFC is approved and merged, I'll flesh out this epic identifying what issues will be needed to resolve the noted requirements.
