### ISSUE TITLE
Add support for gzipped files to file source

### ISSUE THREAD

**Issue by mre** [timberio/vector#848]
We have a few pipelines which read gzipped files, transform them and send the result to Elasticsearch. It would be great to have the same functionality in vector.

In Logstash, this is done automatically if the input file is of type `gzip`.
For further reference, [here](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-file.html#plugins-inputs-file-mode) is the logstash file input plugin that supports gzip.

**Comment by mre** [comment]
AFAICT there are two libraries we could use for gzip support, [flate2-rs] and [deflate].
While deflate is a pure Rust implementation of the flate algorithm, flate2-rs is arguably a bit faster according to some rudimentary benchmarks on the deflate `README.md` and has more contributors so far. The disadvantage is that flate2-rs requires C-bindings. 
So if we go for flate2-rs, we should put gzip support behind a feature flag.

[flate2-rs]: https://github.com/alexcrichton/flate2-rs
[deflate]: https://github.com/sile/libflate

**Comment by lukesteensen** [comment]
This is interesting! I'm curious how they go about determining which files are gzipped and which aren't. Looking for an extension would be simple but maybe not the most reliable. Or do they rely on it being configured?

We actually already bring in the `flate2` crate for the gzipping we do ourselves for some sinks.

**Comment by mre** [comment]
> Looking for an extension would be simple but maybe not the most reliable. 

Yup, they just check the file extension:

https://github.com/logstash-plugins/logstash-input-file/blob/9d698b1d766655e868aa788b5b104b7a3e91b27d/lib/filewatch/watched_file.rb#L186-L188

> Or do they rely on it being configured?

Not sure if I understand. Here's a typical configuration:

 
```
input {
  file {
    path => "/path/to/files*gz"
    mode => "read"
    start_position => "beginning"
    file_completed_action => "log_and_delete"
    stat_interval => 60
  }
}
```

So we could go ahead and start with the extension detection for now and then move to more sophisticated mechanisms later?

**Comment by mre** [comment]
So @jorgelbg and me were talking about that yesterday and it doesn't seem to be that easy.
The main issue is the definition of `FileWatcher`:

https://github.com/timberio/vector/blob/503bbc0494eca9b2d62267b4a29adc3c2ce27ff4/lib/file-source/src/file_watcher.rs#L15-L23

It has a `reader: io::BufReader<fs::File>` field. In order to also support `flate2`'s `GzDecoder` (or preferably `MultiGzDecoder`), we would need to make that more generic.
One option would be `reader: io::BufReader<impl Read>`, but Rust does not allow `impl Trait` for struct fields yet. 
`reader: Box<dyn BufRead>` would be possible however.

We could hide that `Box` behind a `FileReader` type, which abstracts away the decompression support. I see a few options here:

1. We create a `FileReader` **struct**, which ends up being a "shim" around compressed/uncompressed files and has the methods `open`, `metadata` and `seek`. The latter two might simply do nothing in the case of compressed files.
2. We create a `FileReader` **enum**, which is defined as
    ```rust
    pub enum File {
      Local(fs::File),
      GZip(flate2::read::GzDecoder),
    }
    ```
    similar to [mini-fs](https://github.com/germangb/mini-fs/blob/0a53948bd23917350bddd0c2eac14e53e895d2da/src/lib.rs#L85-L94). For operations on a variant of that enum, one could use a `match` statement and execute a match arm accordingly. 

Option 1 might avoid additional conditions in the `FileWatcher` at the cost of being an incomplete abstraction.  
Option 2 might be straightforward and less error prone but also more explicit and requires a few more `match` statements in the `FileWatcher`.

Maybe there are even more options which we haven't considered yet.

**Comment by lukesteensen** [comment]
As far as I can tell, the `reader` field is only ever used in `read_until_with_max_size` (as `&mut BufRead`), and to `seek` in `new` and `update_path`.

It doesn't seem that any of the gzip decoders are `Seek`, but luckily we only ever seek _before_ assigning a newly created reader to the struct field. So we could pretty easily do the seeking before putting the reader in a `Box` and assigning it to a `reader: Box<dyn BufRead>` field.

At a higher level, I am a little concerned about not being able to track file positions in gzipped file. We'd want to be very clear in the documentation about what kind of behavior this would imply and the resulting limitations.

We may also want to tweak behavior for these files in other ways, since I assume they won't be "tailed" the way we do normal file. Once EOF is reached, they should be dropped and not picked back up again.

**Comment by mre** [comment]
I gave it a shot. Please have a look over on the pull request. 😊
