### ISSUE TITLE
`make generate` fails on new transform

### ISSUE THREAD

**Issue by mre** [timberio/vector#849]
While creating a new transform, I ran into the following issue when generating the documentation with `make generate`:

```
Traceback (most recent call last):
        3: from scripts/generate.rb:101:in `<main>'
        2: from scripts/generate.rb:101:in `each'
        1: from scripts/generate.rb:109:in `block in <main>'
scripts/generate.rb:109:in `read': No such file or directory @ rb_sysopen - /tmp/vector/docs/usage/configuration/transforms/split.md (Errno::ENOENT)
````

Creating an empty file before running `make generate` fixes the problem for me.
I think we should check [here](https://github.com/timberio/vector/blob/master/scripts/generate.rb#L117) if the file exists.

**Comment by binarylogic** [comment]
Thanks for reporting! Should be all good now.
