### ISSUE TITLE
Default vector configuration file

### ISSUE THREAD

**Issue by Trigzorgs** [timberio/vector#8521]
### Current Vector Version

```
vector 0.15.1 (x86_64-unknown-linux-gnu c5e4732 2021-07-27)
```

### Reasons behind request

Since updating to vector version 0.15.1, we are no long able to have a single vector.toml configuration file, containing default setting for our vector setups such as:
```
...
data_dir = "/data/vector/"
api.enabled = true
...
```

We use this file normally for these kind of settings, because we have multiple .toml files fir different pipelines going through our vectors. But as of updating to 0.15.1, we are no longler able to, becuase a "source" and "sink" needs to be defined in the config, and we get this error when starting the vector service:

```
Jul 30 09:02:42 **** systemd[1]: Starting Vector...
Jul 30 09:02:42 **** vector[573100]: Failed to load ["/etc/vector/vector.toml"]
Jul 30 09:02:42 **** vector[573100]: ------------------------------------------
Jul 30 09:02:42 **** vector[573100]: x No sources defined in the config.
Jul 30 09:02:42 **** vector[573100]: x No sinks defined in the config.
```
### Proposal

A common configuration file, for default configs.

**Comment by jszwedko** [comment]
Hi @Trigzorgs !

Thanks for the report.

I'm not aware of any changes to this behavior in 0.15.1 or 0.15.0. Which version was it working for you? The SystemD unit file has never specified a config to load so `vector` has always loaded the default `/etc/vector/vector.toml`. You could instruct it to load multiple files via including `VECTOR_CONFIG="/etc/vector/*.toml"` in `/etc/default/vector`.

**Comment by Trigzorgs** [comment]
Hi @jszwedko 

I have been running with the following in the systemD unit file since vector 0.10.0:

```
ExecStart=/usr/bin/vector --quiet --quiet -c /etc/vector/vector.toml /etc/vector/sources/*/*.toml
```

 I have tried upgrading to 0.15.1 from two different version 0.13.1 and 0.14.1 where it worked for both previously

**Comment by pgassmann** [comment]
@Trigzorgs could this be the same issue?

- #8560 

The issue is the `ExecPreStart=` command. If you just override `ExecStart`, the validate command still fails

**Comment by Trigzorgs** [comment]
@pgassmann  This does indeed seem to be the issue, I tried your workaround by disabling the validations. And i can now start the service, without any complaints

**Comment by spencergilbert** [comment]
Thanks for the report! We'll track and resolve in https://github.com/timberio/vector/issues/8560
