### ISSUE TITLE
`encoding.codec` options do not appear to be rendering on site

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#8530]
Example: https://vector.dev/docs/reference/configuration/sinks/aws_kinesis_firehose/#encoding.codec

<img width="688" alt="Screen Shot 2021-07-30 at 12 26 01 PM" src="https://user-images.githubusercontent.com/316880/127702439-67b2eb89-e393-4c36-b1a9-b04c3b1909f0.png">

**Comment by binarylogic** [comment]
@jszwedko I'm not following. What exactly is the problem?

**Comment by spencergilbert** [comment]
coded options:

- json
- text
- ndjson
- etc

**Comment by jszwedko** [comment]
> @jszwedko I'm not following. What exactly is the problem?

The available options for `encoding.codec` are not listed.

**Comment by dre-sctg** [comment]
![image](https://user-images.githubusercontent.com/61747040/132864719-67b8c8e6-e08e-4e46-9756-436e32d0f339.png)
The expectation would be to see under `encoding.codec` a list of the enums options, as shown for `encoding.timestamp_format`. Or at least a link to somewhere in the documentation. 
I'd love to help with this if possible.

**Comment by dre-sctg** [comment]
I don't have a lot of experience with this codebase, but I'd assume that it should be enough to append an enum block to https://github.com/timberio/vector/blob/6c94aad0f55b8e50b624f50c9d656f26637c2bb9/website/cue/reference/components/sinks.cue#L163 ?
Is there a place where I can lookup currently available options?

**Comment by spencergilbert** [comment]
`#EncodingCodec: "json" | "logfmt" | "ndjson" | "text"`
https://github.com/timberio/vector/blob/master/website/cue/reference.cue#L54

I'm not sure if it's an HTML rendering issue, or an issue with the CUE docs 🤔

**Comment by DavidWeid** [comment]
Should it exist here? This seems to be where the information and copy for this section is coming from: https://github.com/timberio/vector/blob/master/website/cue/reference/components/sinks.cue#L160-L168

**Comment by spencergilbert** [comment]
I noticed on the `source` side we have the encoding enum displayed here: https://vector.dev/docs/reference/configuration/sources/http/#encoding

**Comment by DavidWeid** [comment]
would this be the desired result? 
<img width="1440" alt="Screen Shot 2021-09-10 at 11 57 40 AM" src="https://user-images.githubusercontent.com/44077321/132882889-d2df541f-4f21-4d78-b864-c72ecaa28948.png">

**Comment by spencergilbert** [comment]
@jszwedko / @lucperkins can correct me, but I believe so!

**Comment by lucperkins** [comment]
@DavidWeid Looks good to me!
