### ISSUE TITLE
metric sum with batch to `aws_cloudwatch_metrics` or a aggregation transform

### ISSUE THREAD

**Issue by gumieri** [timberio/vector#856]
Hi.

The CloudWatch Metrics (PutMetricData) have some hard limits:

- 20 items (MetricDatum) per request;
- 40 KB for HTTP POST requests.

I am trying to use the Vector in production for counting requests according some categories inside my application, but it receives 10k rpm. So I need to batch it all before sending it to CloudWatch.

I am having this error using the `aws_cloudwatch_metrics`:
```
Sep 11 20:25:07 xxxxxxxxxxxxxxxxxxxxxxxxxxxxx vector[21662]: Sep 11 20:25:07.470 ERROR sink{name="cloudwatch_metrics"}: log: encountered non-retriable error. error=unknown error  log.target="vector::sinks::util::retries" log.module_path="vector::sinks::util::retries" log.file="src/sinks/util/retries.rs" log.line=86
Sep 11 20:25:07 xxxxxxxxxxxxxxxxxxxxxxxxxxxxx vector[21662]: Sep 11 20:25:07.470 ERROR sink{name="cloudwatch_metrics"}: vector::sinks::util::retries: encountered non-retriable error. error=unknown error
Sep 11 20:25:07 xxxxxxxxxxxxxxxxxxxxxxxxxxxxx vector[21662]: Sep 11 20:25:07.471 ERROR sink{name="cloudwatch_metrics"}: log: request failed. error=unknown error  log.target="vector::sinks::util" log.module_path="vector::sinks::util" log.file="src/sinks/util/mod.rs" log.line=200
Sep 11 20:25:07 xxxxxxxxxxxxxxxxxxxxxxxxxxxxx vector[21662]: Sep 11 20:25:07.471 ERROR sink{name="cloudwatch_metrics"}: vector::sinks::util: request failed. error=unknown error
```
My config for the sink:
```toml
[sinks.cloudwatch_metrics]
  inputs = ["log_to_metric"]
  type = "aws_cloudwatch_metrics"
  namespace = "Application"
  region = "sa-east-1"
  batch_size = 10000
  batch_timeout = 60

[sinks.cloudwatch_metrics.buffer]
  type = "memory"
  when_full = "block"
  num_items = 5000
```

Is there a way to sum the counting values from the metrics according it tags before sinking it?

If not, does the vector would have the responsibility for doing it?

If so, what would be more interesting? Creating a transform to aggreate it data or something in the sink and its buffer/batch configuration?

**Comment by binarylogic** [comment]
Thanks @gumieri, we appreciate the detailed information. I think it's worth having the team weigh in and produce a spec for resolving this. Ideally, you would not have to worry about this since the default CloudWatch metrics limit seem to be liberal:

> 40 KB for HTTP POST requests. PutMetricData can handle 150 transactions per second (TPS), which is the maximum number of operation requests you can make per second without being throttled.
>
> You can request a limit increase.

We'll also think about a way you can control and specify loss of precision.

**Comment by lukesteensen** [comment]
One thing we could do that might not be that invasive is to "dedup" each batch of events that arrive in the sink before sending them. It wouldn't work for every data type right now, but counters and gauges are two that allow for relatively straightforward merging.

That could either happen in the sink itself, before encoding, or we could build a smarter batch type that we know how to either insert or update existing values based on the type/name/tag combo. A batch type would likely work better with the various batching configs.

**Comment by loony-bean** [comment]
@gumieri We have merged the deduplication/aggregation of metrics in the buffer. For instance, if the buffer contains 100 Counters with 1.0 value (and having the same name and tags), it will emit only a single Counter that will carry the value of 100.0

Looking forward your feedback!

**Comment by gumieri** [comment]
I am really amazed by the work of your team and the attention I received on this and another Issue that I opened. I feel these are Issues without much significance, but even so your team was very considerate of me and are even delivering it with great agility. thank you very much!

At the moment I am using the Vector in production for feeding a Prometheus/Grafana and it is being amazing.
Now with this feature of aggregation to `aws_cloudwatch_metrics` I will be able to optimize the actual cost of some very important metrics. Thank you! :heart: 

I will not be able to test this feature this month, but ASAP I will be back with the feedback. :wink:

**Comment by gumieri** [comment]
Hi @loony-bean, I've tried to run (`make run`) the master branch (commit ref: `55766802be0a`) but I've seen no changes. Should I try in a different branch or change something in the `vector.toml` config?

**Comment by loony-bean** [comment]
Thanks for pointing out @gumieri!
Apparently there is a bug in the implementation, I'm looking into this

**Comment by loony-bean** [comment]
Hi @gumieri, did you get a chance to check the new version?

**Comment by gumieri** [comment]
Hi! I've done some tests (in production haha…) with the version when I saw the fix merged.
The behaviour was correct! I think we can close this issue. :slightly_smiling_face:
