### ISSUE TITLE
SQS Ability to add deduplicationId support

### ISSUE THREAD

**Issue by ocrlgv** [timberio/vector#8561]
I'm using json as metrics being pushed to SQS (as logs) but currently require a method to inject the deduplication ID to prevent 2 systems sending the same metric.

### Use-cases
We currently have a legacy system which runs on multiple machines and records metrics to an internal database. currently the system runs a periodic cron that collects the metrics and sends to the monitoring/metrics system.
Unfortunately this cron runs on multiple hosts so the same metric is sent. sending from 1 host is also not ideal if it dies or fails.
Using a field from the db eg trasaction_id or record row id would force deduplication.
We cannot rely on the SQS content based deduplication.

### Attempted Solutions
content based deduplication but isn't ideal

### Proposal
provide a means to add a deduplication field (log is json and contains dedupe field)

**Comment by spencergilbert** [comment]
Have you tried using [reduce](https://vector.dev/docs/reference/configuration/transforms/reduce/) to remove your duplicate events?

**Comment by ocrlgv** [comment]
no, but trying to limit the amount vector needs to perform as for me the setup is already getting complicated with a lot of transforms. if the storage has that ability then why not pass on that responsibility to it.
I can try out the reduce for now.

**Comment by ocrlgv** [comment]
ok, we can't use `reduce` because that is assuming vector is a single instance but if scaling to a cluster of 2 or more and 2 or more vector instances receive the same message, they will submit into SQS a duplicate.

**Comment by spencergilbert** [comment]
Looking at our deps today, should be able to use include this by allowing users to configure: https://rusoto.github.io/rusoto/rusoto_sqs/struct.SendMessageRequest.html#structfield.message_deduplication_id
