### ISSUE TITLE
Lua transformer type loss

### ISSUE THREAD

**Issue by karlseguin** [timberio/vector#857]
Seems like int/floats get converted back into strings if manipulated via lua. Not sure if this is avoidable. My current solution is to run a coercer to get it back into an an int.

Reproduced with:
```
data_dir = "/tmp/"

[sources.input]
  type = "stdin"

[transforms.tokenizer]
  type = "tokenizer"
  inputs = ["input"]
  field_names = ["time"]
  field = "message"
  drop_field = true
[transforms.tokenizer.types]
    time = "int"

[transforms.lua]
  type = "lua"
  inputs = ["tokenizer"]
  source = """
    event['time'] = event['time'] + 1
  """

[sinks.output]
  inputs = ["lua"]
  type = "console"
  target = "stdout"
```

Run: `echo 1 | vector --config config.toml`

Expect: `{"time":2, ....`
Actual: `{"time":"2.0",...`

**Comment by lukesteensen** [comment]
This is an unfortunate shortcoming of our existing lua transform. Using the coercer is a good workaround, but this is something we plan to address. Thank you for opening the issue!
