### ISSUE TITLE
vector windows data_dir=/var/lib/vector does not exist

### ISSUE THREAD

**Issue by AymanMagdy** [timberio/vector#8588]
As using the vector.msi reading from a file and pipe the data to ES. There's a weird issue that appears regarding checking for the data dir while I have hashed that variable. After a quick search, I found this is an issue regarding validation.

[api]
enabled = true
address = "127.0.0.1:8000"

#data_dir = /var/lib/vector

[sources."auth_log"]
type = "file" # required
include = ["C:\\Users\\ayman\\AppData\\Roaming\\Microsoft\\Windows\\PowerShell\\PSReadLine\\ConsoleHost_history.txt"] 
read_from = "beginning" # optional, default

[sinks.console]
inputs = ["auth_log"]
type = "console"
encoding.codec = "json"

[sinks.elasticsearch]
inputs       = ["auth_log"]            # take from source.system.logs
type         = "elasticsearch"
host         = "localhost:9243"   # local or external host
healthcheck.enabled = true # optional, default

Error Message:
ERROR vector::topology: Configuration error. error=Source "auth_log": data_dir "/var/lib/vector/" does not exist

Expected to read the data from the provided file source.

**Comment by AymanMagdy** [comment]
[Solved]

For those trying to use vector with windows, create a new dir under ' C:\ ' called ' /var/lib/vector ' as vector writes the data coming from the defined source in vector.toml to that path with a new file called 'checkpoint.json' that contains the checkouts into the defined input source.

**Comment by AymanMagdy** [comment]
I recommend enhancing this feature by creating the needed dir /var/lib/vector for Windows OS by Vector itself.

**Comment by spencergilbert** [comment]
👍 That's correct - [data_dir](https://vector.dev/docs/reference/configuration/global-options/#data_dir) has a default value (the equivalent for Windows)

**Comment by jszwedko** [comment]
Note we also have https://github.com/timberio/vector/issues/7108 to try to pick a better default data directory on Windows rather than the unix-y `/var/lib/vector`.

**Comment by AymanMagdy** [comment]
> 👍 That's correct - [data_dir](https://vector.dev/docs/reference/configuration/global-options/#data_dir) has a default value (the equivalent for Windows)

I think this needs to be modified and to be changed to a valid dir name for windows use.
Or to create a default dir `/whatever/name/is` in the vector setup.
