### ISSUE TITLE
Remove x86_64-unknown-linux-gnu target in favor of x86_64-unknown-linux-musl

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#860]
I'd like to audit the [current `x86_64-unknown-linux-gnu` build step](https://github.com/timberio/vector/blob/bf81efdddf801232aa44ab76184e1368f1ce4f78/.circleci/config.yml#L156) since I originally set this up. I am by no means an expert in this domain and would prefer someone who is to audit what's going to ensure our releases for this target are correct. Specifically, the questions I have:

1. We're using the `timberiodev/vector-builder-x86_64-unknown-linux-gnu` Docker image which is [based on](https://github.com/timberio/vector/blob/master/scripts/ci-docker-images/builder-x86_64-unknown-linux-gnu/Dockerfile) the `japaric/x86_64-unknown-linux-gnu:latest` Docker image. Is this even necessary? If possible, it would be nice to drop our dependency on the `japaric` image.
2. Are the libraries linked up to date? Previously I tried updating them and received errors running the binary on older Debian distribution because the linked versions were greater than what was available on the machine.
3. I don't know what I don't know, and I'm sure there are other things we can improve with this process.

Before we begin I want to clarify exactly what we're doing here with a light specification. An expert in this domain should know exactly what to look for as well the steps to take.

**Comment by a-rodin** [comment]
> We're using the timberiodev/vector-builder-x86_64-unknown-linux-gnu Docker image which is based on the japaric/x86_64-unknown-linux-gnu:latest Docker image. Is this even necessary? 

We can use `ubuntu:12.04`, which is the base image of `japaric/x86_64-unknown-linux-gnu:latest`, directly as our base image.

> Are the libraries linked up to date?

The libraries are not up to date and that's exactly what we need for a non-specific `x86_64-unknown-linux-gnu` build. Glibc is backward compatible, but not forward compatible, which means that we need to link to the oldest version we want to support to ensure that the resulting binary will run with that version or any newer version of Glibc. It potentially can cause some performance degradation on newer systems if there are some newer Glibc features that could have been used and increased performance, but an alternative would be to have `.tar.gz` archives which in my opinion would make things too complex for the user. However, we can link with the newest available version when we build disc-specific `.deb` and `.rpm` packages.

So I think we can done just one thing  about `x86_64-unknown-linux-gnu` build: replace `japaric/x86_64-unknown-linux-gnu:latest` by `ubuntu:12.04`. Additionally it would be helpful to check if there significant performance degradation for builds with old Glibc version when they are run on systems with newer Glibc version.

I'm also thinking what if we just stopped providing `x86_64-unknown-linux-gnu` archive at all and provided only `x86_64-unknown-linux-musl` archive for Linux to reduce users confusion.

**Comment by binarylogic** [comment]
I've updated this issue to represent the removal of the `unknown-linux-gnu` build.

**Comment by a-rodin** [comment]
@binarylogic We need a deprecation strategy for URL https://packages.timber.io/vector/latest/vector-x86_64-unknown-linux-gnu.tar.gz, because people may rely on it.

We probably need to serve `vector-x86_64-unknown-linux-musl.tar.gz` archive on this URL, but I'm not sure about the cleanest way to achieve this. If we put 301 HTTP redirect, it might break things for those who download using `curl` without `-L` option, on the other hand, just having a copy of `vector-x86_64-unknown-linux-musl.tar.gz` named as `vector-x86_64-unknown-linux-gnu.tar.gz` is less clean, but wouldn't break the things (as S3 doesn't support symlinks, we can't put a symlink there).

An alternative approach would be to keep https://packages.timber.io/vector/latest/vector-x86_64-unknown-linux-gnu.tar.gz URL alive, but don't update it, so that it would still contain Vector 0.5.0 event after 0.6.0 is released.

**Comment by binarylogic** [comment]
@lukesteensen I'm curious what you think here. I'm of the mindset that it's ok for this URL to break given that we're in `0.X`. We can add a notice in the release notes.

**Comment by lukesteensen** [comment]
Do we have numbers on how many downloads that URL is getting? If it's a lot then it might be worth more effort.

I like the idea of serving the musl version in its place, at least temporarily. In that case, I think a redirect would be reasonable. Leaving the old version under `latest/` seems a little more confusing to me.

Either way, a call out in the release notes is a very good idea and should cover anyone that the redirect throws off.

**Comment by binarylogic** [comment]
Sounds good. @a-rodin let's setup a permanent redirect.
