### ISSUE TITLE
Look into unlocking from PackageCloud

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#862]
Currently, we use [Package Cloud](https://packagecloud.io/) for our distribution of `rpm` and `deb` packages. I think this service is simple and excellent but we're locked in. Notice the [Debian installation instructions](https://docs.vector.dev/setup/installation/package-managers/apt#install).

I think it's worth lightly looking into the possibility of avoiding this lock-in. If there is an easy alternative path then it might be worth taking. Otherwise, we can document our decision here and move on.

**Comment by a-rodin** [comment]
One quick and simple solution is to just have a single `.deb` and a single `.rpm` file without dependencies for all Debian/RPM-based distributions correspondingly that would contain statically linked Vector and then allow the users to download and install it without package manager, similarly to how [Slack](https://slack.com/intl/en-us/downloads/linux) and [Skype](https://www.skype.com/en/get-skype/) are distributed.

The one-liners could have been changed then to something like

```sh
wget https://packages.timber.io/vector/vector-0.3.0-amd64.deb && sudo dpkg -i vector-0.3.0-amd64.deb
```

It is also slightly more transparent to the user what is going to happen after running such one-liner. The downside is that no automatic updates would be possible.

A more complex approach would be to maintain self-hosted repositories for supported distributions, similarly to how [Docker does it](https://docs.docker.com/install/linux/docker-ce/debian/).

Tangentially, security-concerned users might prefer installation from an official repository of their distribution. It might paid off to start pushing Vector to official Debian and Fedora repositories  earlier, as it takes time to pass all bureaucratic and packaging quality checks and go the path `experimental` → `unstable` → `testing`→ `stable`/`stable-backports`/`oldstable-backports` (in case of Debian).

**Comment by binarylogic** [comment]
Thanks @a-rodin. I had a pretty bad customer service experience with Package Cloud so I'd definitely like to move off of them. After further research, there are a lot of better, and cheaper, alternatives out there:

* [Gemfury](https://gemfury.com/) - Paid. Offers both APT and YUM repository hosting. Allows for custom domains. Does not support GPG.
* [Aptly](https://github.com/aptly-dev/aptly) - Open-source. Appears to do what we want. I think we can use this on top of S3.

Alternatively, as @a-rodin mentioned, we could drop repository management for now. I'm curious if this really matters nowadays? Especially for a service like Vector that isn't a library or dependency of other packages. It seems just as easy, if not preferred, to download the package files directly and use `dpkg` or `yum` to install them directly.

**Comment by a-rodin** [comment]
@binarylogic 
> I'm curious if this really matters nowadays?

I think in our case it is mostly about ability to provide automatic updates. Btw, if we provide automatic updates, we might also consider to have separate sections (like `deb [arch=amd64] https://packages.timber.io/linux/debian buster vector_0_4`) for each major version to not break things for users running `apt-get upgrade` if we plan do backwards-incompatible changes.

> Aptly - Open-source. Appears to do what we want. I think we can use this on top of S3.

Aptly looks good to me, I like that it is in the official Debian repository. If we find problems with it, it is possible to fall back to just creating a script that would run `dpkg-scanpackages` and create repository structure with `Contents` and `Releases` files which  can be put to S3.

It also seems like for YUM the things are generally simpler, so repository creation can be accomplished using official [repocreate](http://yum.baseurl.org/wiki/RepoCreate.html) tool.
