### ISSUE TITLE
No spacing between code blocks and surrounding text in titles

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#8625]
Example:

<img width="683" alt="Screen Shot 2021-08-06 at 10 41 05 AM" src="https://user-images.githubusercontent.com/316880/128550763-2a64f582-e6f8-46b7-bb17-39967572245e.png">

https://vector.dev/highlights/2021-07-14-0-15-upgrade-guide/

**Comment by lucperkins** [comment]
Yeah, [Tailwind's typography library](https://github.com/tailwindlabs/tailwindcss-typography) sadly leaves a lot to be desired. I'm hoping the website team can make a big dent here.

**Comment by DavidWeid** [comment]
This currently occurs with all header (h3) tags with a sub-element such as a `code` or `em` block.
