### ISSUE TITLE
Add another chrono format to convert timestamp to string

### ISSUE THREAD

**Issue by xcaptain** [timberio/vector#867]
The current https://docs.vector.dev/usage/configuration/transforms/coercer support to convert string to timestamp,  would be better if we can add a second option to convert string to timestamp like:

```
localtime = "timestamp|%+|%F"
```

this situation is common like nginx produces [iso 8601 timestamp](http://nginx.org/en/docs/http/ngx_http_log_module.html#var_time_iso8601) but the storage(like clickhouse) would prefer a local time, so would be better to format timestamp to string again

**Comment by xcaptain** [comment]
This should be easy to implement, if you want I can make a pull request

**Comment by binarylogic** [comment]
Interesting, thanks for reporting. That makes sense and we would welcome a pull request for this.

**Comment by xcaptain** [comment]
Using lua script solved this problem

function convertIso8601(s)
  local p='(%d+)-(%d+)-(%d+)T(%d+):(%d+):(%d+)'
  local year,month,day,hour,min,sec,tz=s:match(p)
  return os.date("%Y-%m-%d %T",os.time({day=day,month=month,year=year,hour=hour,min=min,sec=sec}))
end

event['localtime'] = convertIso8601(event['localtime'])
