### ISSUE TITLE
Create a Vector component specification

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#8728]
📢 It's high-time we create a specification for Vector components! 📢 All Vector components should adhere to a set of common behavior. Things like error handling, telemetry, and back pressure are crucial behavioral elements that must be consistent across component types. For example, issues #8693, #8368, and #8709 highlight inconsistencies in telemetry that make debugging and observability difficult. It's not enough to simply list the metrics that each component type should emit, we must be precise about what each metric means as evident by the inconsistencies in `bytes_out_total`.

This should serve as the initial work for #3900 so that we can align on the scope.

**Comment by jszwedko** [comment]
Another question that came up that could be covered by this is when to retry requests: https://github.com/timberio/vector/pull/8758
