### ISSUE TITLE
vector failed to execute when target musl

### ISSUE THREAD

**Issue by xcaptain** [timberio/vector#877]
I'm using to `cargo build --release --target=x86_64-unknown-linux-musl` to build the project but the result won't execute, but the default target works

![图片](https://user-images.githubusercontent.com/4054836/65029038-9f605a80-d96f-11e9-987c-3c5f8d25a594.png)

**Comment by mre** [comment]
Hum... that doesn't look like a problem with vector, though.
It seems to build just fine so I wonder where it was copying the binary into.
You can try a `cargo clean` which will remove the `target` folder and then another build.
Then you can inspect your `target` folder and see which subfolders it created.

You can verify that you have the correct toolchains with

```
rustc --print target-list
```

**Comment by binarylogic** [comment]
Hi @xcaptain , is there any reason our pre-built binary won't work for you?

https://packages.timber.io/vector/nightly/vector-nightly-x86_64-unknown-linux-musl.tar.gz

That should be the latest `musl` build ^

**Comment by xcaptain** [comment]
@mre Can you build with `cargo build --release --target=x86_64-unknown-linux-musl` and run the binary using rustc 1.37 stable? I will check again to see if it's related to my build environment

**Comment by mre** [comment]
@xcaptain, sorry that I didn't report back.
Maybe this could help you: https://github.com/timberio/vector/issues/826.
