### ISSUE TITLE
Regex parsing error. Transforming file to elasticsearch

### ISSUE THREAD

**Issue by fujianan** [timberio/vector#878]
I read this page
(https://docs.vector.dev/usage/configuration/transforms/regex_parser#config-file)

![image](https://user-images.githubusercontent.com/22000011/65037383-27e6f700-d980-11e9-9795-175119a519bf.png)

/var/log/apache2/access.log
![image](https://user-images.githubusercontent.com/22000011/65037236-cb83d780-d97f-11e9-846d-1d7c2936da67.png)
my configuration:
```
data_dir = "/var/lib/vector"
[sources.apache_logs]
  type         = "file"
[transforms.apache_parser]
  inputs = ["apache_logs"]
  type = "regex_parser"
  field = "message"
  regex = '^(?P<host>[\w\.]+) - (?P<user>[\w]+) (?P<bytes_in>[\d]+) \[(?P<timestamp>.*)\] "(?P<method>[\w]+) (?P<path>.*)" (?P<status>[\d]+) (?P<bytes_out>[\d]+)$'
[transforms.apache_parser.types]
  bytes_in = "int"
  timestamp = "timestamp|%m/%d/%Y:%H:%M:%S %z"
  status = "int"
  bytes_out = "int"
[sinks.elasticsearch_sink]
  type = "elasticsearch"
  inputs =  ["apache_parser"]
  host = "http://10.80.0.130:9200"
  doc_type = "_doc"
  healthcheck = true
  index = "vector-%Y.%m.%d"
  provider = "default"
  batch_size = 10490000
  batch_timeout = 10
  request_in_flight_limit = 5
  request_timeout_secs = 60
  [sinks.elasticsearch_sink.buffer]
    type = "memory"
    when_full = "block"
    max_size = 104900000
    num_items = 500
  [sinks.elasticsearch_sink.headers]
    X-Powered-By = "Vector"
  [sinks.elasticsearch_sink.query]
    X-Powered-By = "Vector"
[sinks.print]
  type         = "console"
  inputs       = ["apache_logs"]
```
What went wrong? How can I fix it?

**Comment by mre** [comment]
Hey @fujianan,

the regular expression can not parse your Apache logs.

Namely, this regular expression
```
'^(?P<host>[\w\.]+) - (?P<user>[\w]+) (?P<bytes_in>[\d]+) \[(?P<timestamp>.*)\] "(?P<method>[\w]+) (?P<path>.*)" (?P<status>[\d]+) (?P<bytes_out>[\d]+)$'
```

does not match:

```
{"message": "..."}
```

It looks like you are using a different Apache log format.
You can switch back to the original log format of Apache in your Apache config (`apache.conf`). Search for `LogFormat` in there and remove any custom settings.
Alternatively you can adjust the regular expression above to match your current log format.
You can try [regex101](https://regex101.com/) to test your regular expressions.

**Comment by fujianan** [comment]
ok, i got it 
but i I have a new problem.
They are my apache logs:
```
127.0.0.1 - fujianan 2000 [19/06/2019:17:20:49] "GET /test" 200 4286
127.0.0.2 - fujianan 1000 [19/06/2019:17:20:49] "GET /test" 200 4286
127.0.0.3 - fujianan 2000 [19/06/2019:17:20:49] "GET /test" 200 4286
127.0.0.4 - fujianan 1000 [19/06/2019:17:20:49] "GET /test" 200 4286
```
transform to Elasticsearch 405 method not allowed
Is the elasticsearch  index created automatically  or I need to create index ahead of time

![image](https://user-images.githubusercontent.com/22000011/65104232-5c4fc700-da03-11e9-9720-660e8331605e.png)

**Comment by binarylogic** [comment]
Hi @fujianan, what turned out to be the issue? In regards to index creation, that is configurable on the Elasticsearch side.

**Comment by fujianan** [comment]
> Hi @fujianan, what turned out to be the issue? In regards to index creation, that is configurable on the Elasticsearch side.

Hi @binarylogic 
I delete configuration as follow
```
  [sinks.elasticsearch_sink.headers]
    X-Powered-By = "Vector"
  [sinks.elasticsearch_sink.query]
    X-Powered-By = "Vector"
```
elasticsearch can show index data
thanks
