### ISSUE TITLE
Code block CSS is broken in lists

### ISSUE THREAD

**Issue by lucperkins** [timberio/vector#8827]
For an example of this issue, see [this page](https://vector.dev/docs/setup/installation/platforms/docker/):

<img width="734" alt="Screen Shot 2021-08-22 at 2 33 38 PM" src="https://user-images.githubusercontent.com/1523104/130370681-63cc645c-e66c-4d08-8e42-639dc95edb50.png">

To be clear, I think that this may have been broken *before* the changes in #8786. In general, the Tailwind Typography library has lots of edge-case-y bugs like this. Hoping that it seems some love soon.

**Comment by jszwedko** [comment]
https://github.com/timberio/vector/issues/8785 notes this too.
