### ISSUE TITLE
Allow to set custom CA for elasticsearch sink

### ISSUE THREAD

**Issue by e11it** [timberio/vector#887]
Currently there is only one way to connect to elastic behind ssl is to add CA to the system trust store.

Could you please add  option to setup custom CA. And option to allow not verified ssl connection.
Same Logstash options: cacert, ssl_certificate_verification.
(https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-options)

**Comment by binarylogic** [comment]
Thanks @e11it . @bruceg I've assigned this to you since it's related to your other work. Let me know if you need more information or would not prefer to do this.

**Comment by bruceg** [comment]
Can I test this without an instance with an X-Pack license? Everything I am reading online says that HTTPS support is only present in X-Pack.

**Comment by spencergilbert** [comment]
@bruceg I'm happy to set up a test cluster with vector

**Comment by binarylogic** [comment]
Thanks @spencergilbert. @bruceg we used [search guard](https://search-guard.com/) in the past to secure an Elasticsearch cluster, but if this is just for manual testing, we are happy to pay for a cluster hosted on [elastic.co](https://www.elastic.co/pricing). If this is for testing/CI, we can help set up search guard. Let me know how we can help..

**Comment by spencergilbert** [comment]
Also since es6.6 (i think) xpack is provided, in a limited way, on the free basic license. As long as you're running a recent version of es you should be able to configure ssl

**Comment by e11it** [comment]
It's also possible to use opendistro distr for testing (https://opendistro.github.io/)

Https enabled by default in the Opendistro docker image. Here is default cert : https://github.com/opendistro-for-elasticsearch/security/blob/master/tools/install_demo_configuration.sh .

**Comment by bruceg** [comment]
Fixed through PR #953
