### ISSUE TITLE
Incorrect 'Release' link on documentation website

### ISSUE THREAD

**Issue by abraxxa** [timberio/vector#8870]
I hope this is the correct repo for this, if not please link me to the correct one.

The left menu on https://vector.dev/docs/ links to https://github.com/timberio/vector/blob/master/RELEASING.md instead of https://github.com/timberio/vector/blob/master/docs/RELEASING.md.

**Comment by spencergilbert** [comment]
Thanks good catch! We've done some reorganizing of the repo recently and missed this link, I'll get it fixed today.
