### ISSUE TITLE
Parse_ruby_hash not handling underscores

### ISSUE THREAD

**Issue by Hendric-Eckelt** [timberio/vector#8872]
Hi,
The `parse_ruby_hash!` function doesn't seem to handle underscores. It fails for me when any key contains an underscore, which makes it unusable since Ruby uses snake case as naming convention.

### Vector Version

```
0.15.2
```

### Vector Configuration File

I've created a minimal example that fails when running a unit test on it.

```json
  "transforms": {
    "ruby_hash_parser": {
      "type": "remap",
      "inputs": ["rails_log"],
      "source": ".params = parse_ruby_hash!(\"{my_param => 123}\")"
    }
  },
```

### Expected Behavior

Should convert the hash to `"params": {"my_param":123}`

### Actual Behavior

Fails with the following error
```
WARN vector::internal_events::remap: Mapping failed with event. error="function call error for \"parse_ruby_hash\" at (270:307): 0: at line 1, in Tag:\n{my_param => 123}\n   ^\n\n1: at line 1, in map:\n{my_param => 123}\n^\n\n" internal_log_rate_secs=30
```

**Comment by jszwedko** [comment]
@jdrouet do you mind taking this one? I imagine it is a small tweak.

We should check / add tests for other characters too like integers and `@`s. I noticed the current tests do not include these characters in identifiers.

Example hash with extra types of characters that should parse:

```
{ 4 => "hello", 5.4 => 5, :foo => "bar", nil => "world", "foo_bar" => "baz", "@hello" => "world"}
```
