### ISSUE TITLE
Mapping conflicts in index pattern in AWS Elasticsearch after first deployment of vector into EKS

### ISSUE THREAD

**Issue by gartemiev** [timberio/vector#8919]
![image](https://user-images.githubusercontent.com/22891552/131094094-b45c77c6-aa59-4a49-941d-e57defeaabd0.png)

This happens with this key:
![image](https://user-images.githubusercontent.com/22891552/131094281-5b38de5a-3f35-46bc-86a0-f189dfea3036.png)

**Comment by gartemiev** [comment]
@spencergilbert , 

this solution which you provided with in #8058 regarding [transforms.dedot_labels] is the only easy way to prevent those conflicts? Are there any other simple solutions for it because [transforms.dedot_labels] looks a bit difficult and may cause additional load during processing I am afraid?

**Comment by spencergilbert** [comment]
Outside of Vector you could define mappings in Elasticsearch.

Inside of Vector the `lua` transform is the only way today, but we are looking at introducing iteration to VRL which could also help solve it.
