### ISSUE TITLE
same topic,Why does kibana show data lose?

### ISSUE THREAD

**Issue by fujianan** [timberio/vector#896]
first, I have already used vector replace logstash that transform kafka data  to elasticsearch
this is use vector tranfrom kafka data to elasticsearch
index: vector-tri-*
![image](https://user-images.githubusercontent.com/22000011/65237810-f56b0480-db0d-11e9-84dd-9e4e1bfe8e5b.png)

this is use logstash transform kafka data to elasticsearch
index: kubernetes-tri-*
![image](https://user-images.githubusercontent.com/22000011/65237938-2f3c0b00-db0e-11e9-9ccf-c93805afb2b2.png)

As we can see, kibana shows data lose
How can i fix it  or optimize the vector 

this is my vector configuration:
```
data_dir = "/var/lib/vector"
[sources.kafka_source]
  type = "kafka"
  bootstrap_servers = "10.80.0.167:9093,10.80.1.150:9093,10.80.2.150:9093"
  group_id = "vector-indexer"
  topics = ["^(beats|filebeat-kubernetes)-.+"]
  auto_offset_reset = "largest"
[transforms.kafka_parser]
  inputs       = ["kafka_source"]
  type         = "json_parser"
  drop_invalid = true
[sinks.elasticsearch_sink]
  type = "elasticsearch"
  inputs = ["kafka_parser"]
  host = "http://10.80.0.130:9200"
  healthcheck = true
  index = "vector-{{ kubernetes.annotations.filebeat_index }}-%Y.%m.%d"
```

**Comment by mre** [comment]
Hey @fujianan,
are you sure that date that you're reading is valid JSON?
A common pitfall is having a non-JSON prefix (like a timestamp).
Can you also post your working logstash config here for reference?

**Comment by binarylogic** [comment]
Thanks for reporting. Yes, I would look at the logs to see if that sheds any light. There definitely should not be any data loss. I'm adding this to our reliability milestone to add a long running test for Elasticsearch as well.

**Comment by binarylogic** [comment]
@fujianan if you wouldn't mind providing more info we can help. I'd also try out the latest Vector version to ensure you have all relevant bug fixes. Feel free to reopen if this is still happening.
