### ISSUE TITLE
Docker build of Vector v0.16 from source causes out of memory issue and/or takes close to 1 hour

### ISSUE THREAD

**Issue by csongpaxos** [timberio/vector#8967]
I am trying to do a Docker build of vector from source. The Dockerfile has these lines:

```
FROM rust 
...
RUN mkdir -p vector && \
      curl -sSfL --proto '=https' --tlsv1.2 https://github.com/timberio/vector/archive/v0.16.tar.gz | \
      tar xzf - -C vector --strip-components=1

RUN cd vector && make build
```

The `make build` step takes a really long time and ends up showing an out of memory issue. Increasing memory for Docker works, but it takes close to 1 hour to run this file.

Docker settings used (that took 3247.7s)
4 CPUS
4 GB Memory
2 GB Swap
64 GB Disk image size

Am I doing something incorrectly? Is there a way to optimize this so that it builds a lot faster?

**Comment by lsharir** [comment]
Also experienced long build times using the same method

**Comment by jszwedko** [comment]
Hi @csongpaxos !

Vector builds typically take significantly more memory than that. I would try with 16 or 32 GB and 4-8 vCPUs. 

We should really document this in https://github.com/timberio/vector/blob/master/docs/DEVELOPING.md though. We can use this issue to track that.

**Comment by spencergilbert** [comment]
Building on Mac is also problematic due to how Docker interacts with Apple's filesystem.

**Comment by csongpaxos** [comment]
Is there something wrong with how our Dockerfile is set up? Are there sample Dockerfiles that we should be using?
We are trying to follow the instructions here but are unsure if what we have is correct: https://vector.dev/docs/setup/installation/manual/from-source/#docker 

If building on a mac is problematic, should we try building on a linux box e.g. on an ec2?

```
FROM rust
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install cmake -y
RUN apt-get install -y  libsasl2-dev
RUN apt-get install -y libclang-dev
RUN mkdir -p vector && \
      curl -sSfL --proto '=https' --tlsv1.2 https://github.com/timberio/vector/archive/v0.16.tar.gz | \
      tar xzf - -C vector --strip-components=1

RUN cd vector && make build
```

**Comment by jszwedko** [comment]
Apologies @csongpaxos . I think those instructions our out-of-date. I'll update them.

I'll see if I can put together a minimal Dockefile for building vector. You can checkout the Dockerfile we use for `make environment` (which sets up an image with all of the development dependencies, including some not necessary for building Vector itself): https://github.com/timberio/vector/blob/master/scripts/environment/Dockerfile .

**Comment by jszwedko** [comment]
Actually, the `Dockerfile` you came up with seems to work just fine :)

You can build on Mac, it's just slower since Docker is running in a VM. If you have an EC2 instance handy, building there will be faster.

**Comment by jszwedko** [comment]
I opened https://github.com/timberio/vector/pull/9008 to update the instructions to build via `cross` (which will build in Docker). I think that should close this issue, but let me know if you still have any troubles!
