### ISSUE TITLE
vector cpu 100%

### ISSUE THREAD

**Issue by wgb1990** [timberio/vector#8977]
I use vector as the aggregator to consume Kafka data, and then distribute it to Kafka and Loki. At present, it is found that the CPU consumption is relatively high, basically maintained at about 1C, but my data volume is not large, about 4000 events per second.
top :
![image](https://user-images.githubusercontent.com/7124162/131478838-aefbacdd-2921-460a-aa3b-14580a980527.png)

vector properties
api:
  enabled: true
  address: '0.0.0.0:8686'
sources:
  metrics:
    type: internal_metrics
    scrape_interval_secs: 2
  apps_log:
    type: kafka
    bootstrap_servers: 'xxx'
    group_id: dw-log-forward-vector-gid
    topics:
      - dw-log-forward

transforms:
  remap_message:
    type: remap
    inputs:
      - apps_log
    source: |
      . = parse_json!(string!(.message))
      .eventTime = to_int!(.timestamp)
  output_loki:
    type: remap
    inputs:
      - remap_message
    source: |
      .aggregator = get_env_var!("POD_NAME")
      del(.domain)
      del(.eventTime)
    
  output:
    type: route
    inputs:
      - remap_message
    route:
      java_gc_log: .collectorType == "gc"
      java_error_log: .level == "ERROR"      

sinks:
  prometheus_exporter:
    type: prometheus_exporter
    inputs:
      - metrics
    address: '0.0.0.0:9598'
    default_namespace: service

  kafka_gc:
    type: kafka
    inputs: 
      - output.java_gc_log
    bootstrap_servers: 'xxx' 
    compression: gzip
    encoding: 
      codec: json
      timestamp: unix
    healthcheck: 
      enabled: true
    topic: java_gc_log

  kafka_error:
    type: kafka
    inputs: 
      - output.java_error_log
    bootstrap_servers: 'xxx' 
    compression: gzip
    encoding: 
      codec: json
      timestamp: unix
    healthcheck: 
      enabled: true
    topic: exception_log_prd

  loki:
    type: loki
    inputs:
      - output_loki
    endpoint: 'http://xxx:3100'
    tenant_id: "{{ tenantId }}"
    remove_label_fields: true
    batch:
      max_bytes: 10490000  
      max_events: 8000  
      timeout_secs: 5
    out_of_order_action: "rewrite_timestamp"
    buffer:
      type: "memory"
      max_events: 102400
    request:   
      concurrency: 102400
    labels:
      service: "{{ service }}"
      hostname: "{{ hostname }}"
      level: "{{ level }}"
      collectorType: "{{ collectorType }}"
      aggregator: "{{ aggregator }}"
    encoding:
      codec: json
      timestamp_format: rfc3339
    healthcheck:
      enabled: true

perf 
![image](https://user-images.githubusercontent.com/7124162/131478489-bbc8d57d-9a78-4923-8054-cde11dde1d12.png)

FlameGraph
![image](https://user-images.githubusercontent.com/7124162/131478928-060982f2-6bb4-42ae-95f5-797dea06dc3c.png)

**Comment by xdatcloud** [comment]
Hi, can you paste vector properties with formatted style?  Use syntax of [quoting code](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code).
