### ISSUE TITLE
Missing `template` designation on some docs

### ISSUE THREAD

**Issue by spencergilbert** [timberio/vector#9003]
Ex: https://vector.dev/docs/reference/configuration/sinks/elasticsearch/#index

It would be good to explicitly mark this option as template-able, it's marked as such in CUE but doesn't appear to be rendered in the final HTML.

**Comment by jszwedko** [comment]
This is how we had rendered it before:

<img width="815" alt="Screen Shot 2021-09-02 at 9 52 03 AM" src="https://user-images.githubusercontent.com/316880/131876361-a8604144-5249-4605-b43e-2faa60273a2a.png">

The link would go to  https://vector.dev/docs/reference/configuration/template-syntax/
