### ISSUE TITLE
Documentation fields are not indicated as templateable

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#9029]
Fields that are templateable are not shown as such. For example, the [`group_name` option in the `aws_cloudwatch_logs` sink](https://vector.dev/docs/reference/configuration/sinks/aws_cloudwatch_logs/#group_name) has no indication that it is templateable. This is a very important and powerful feature that was surfaced in a design partner meeting and blocked their integration.

**Comment by spencergilbert** [comment]
Dup: https://github.com/timberio/vector/issues/9003
