### ISSUE TITLE
Test `sources::socket::test::tcp_with_tls_intermediate_ca` is flaky 

### ISSUE THREAD

**Issue by blt** [timberio/vector#9046]
Noticed as a part of #8884 and confirmed locally on a Linux system with current master -- 97f8eb75b7475f66780da348ae894a079d9c60cc -- the referenced test does not reliably pass. It does now and again, implying that it's flaky rather than broken.

**Comment by pablosichert** [comment]
Related: #9053

**Comment by blt** [comment]
Resolved by #9053
