### ISSUE TITLE
Disallow `.` in component IDs

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#9049]
We are planning to introduce multiple streams coming out of a component. For example:

1. An `error` stream for events that failed to process in the `remap` transform.
2. Possibly a `miss` stream in the `filter` transform.
3. Possibly an `else` stream for evens that do not match any routes in the `route` transform.

To allow for these sub-streams, we should reserve the `.` character so that we can provide outputs like `route.else` or `remap.failed`, etc.

**Comment by jszwedko** [comment]
I believe @jdrouet may have already implemented this as part of the pipelines work since pipelines are also separated by a `.` when rendered.

**Comment by lukesteensen** [comment]
Yep, looks like this was completed with #9083.
