### ISSUE TITLE
Document AWS Elasticsearch unsupported settings

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#907]
Following up on https://github.com/timberio/vector/issues/833#issuecomment-533999279, we need to document that:

1. `compression` is not supported for AWS' ElasticSearch service.
2. ANSI colors are not supported in logs.

**Comment by zcapper** [comment]
This would be super helpful. I lost more than a few hours trying to debug this same issue.

In case someone else is Googling for this, the exact error was:
```
vector::sinks::util::retries: retrying after response. reason=500 Internal Server Error: 
{
  "error": {
    "root_cause": [
      {
        "type": "json_parse_exception",
        "reason": "Illegal character ((CTRL-CHAR, code 31)): only regular white space (\\r, \\n, \\t) is allowed between tokens\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@5f28ada1; line: 1, column: 2]"
      }
    ],
    "type": "json_parse_exception",
    "reason": "Illegal character ((CTRL-CHAR, code 31)): only regular white space (\\r, \\n, \\t) is allowed between tokens\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@5f28ada1; line: 1, column: 2]"
  },
  "status": 500
}
```

**Comment by binarylogic** [comment]
Ah! Sorry about this. We'll be sure to get this in the docs today. That's exactly the kind of experience we are hoping to avoid with our docs.

**Comment by binarylogic** [comment]
@bruceg, we should consider enforcing this at the code level, but we need to detect that the downstream ES service is _AWS_ ES. I'm curious what you think the best way to accomplish this is. Some ideas:

1. Using `auth.strategy`. If I recall, authentication is not always required and if that's the case, this won't work. I also slightly dislike this strategy because it's not explicitly the same.
2. Use the `host` value. This is a little better, but it's possible these domains could change, or a user could be using a proxy of some sort.
3. Interact with the service to reflect something back that would indicate an AWS Elasticsearch cluster. I dislike this the most for obvious reasons (network request, won't make the below requirements possible).

If I had to pick, I'd go with option 2 for now, assuming the host is common across all ES clusters. Once we are able to reliably detect AWS Elasticsearch we should:

- [ ] Raise a configuration error if `compression` is set.
- [ ] Strip ANSI characters from logs as part of this sink. The user should _not_ be required to use the `ansi_stripper` transform.

**Comment by jszwedko** [comment]
I realize I'm lacking context, but a few thoughts:

I think it is pretty common to alias domains (e.g. adding a Route53 record for `elasticsearch.internal`) so I think option 2 would have a number of false negatives.

I think option 3 (something like "feature detection") would be the most robust as:

* the user could be running a reverse proxy to support gzip compression even though the upstream does not
* It is possible that AWS will add compression support in the future

I am wondering if it is possible to run ES from source and also have compression disabled.

Alternatively, I think this is also something I'd commonly just expect to see documented next to the `compression` option (like "Note: Ensure that your server has compression enabled. AWS Elasticsearch does not support this").

You could consider parsing the error response and outputting something like "this could be caused by...." to help point people towards possible culprits.

**Comment by jszwedko** [comment]
You might also consider if `compression: none` is a safer default as the lowest-common-denominator even if users would typically want to enable it.

**Comment by binarylogic** [comment]
Yep, that is the default. I'll update the docs in the interim. I'm curious what you think about the above requirements @bruceg? Maybe it does make more sense to just be clearer in the docs for this.

**Comment by bruceg** [comment]
`compression` currently defaults to `gzip` if it is unset, unless there are AWS credentials set up. This was my first attempt at dealing with this incompatibility.

Using the `host` should produce no false positives, but if domain aliases are common, it will still leave a lot of false negatives. It's not clear that this actually helps a lot.

I'm not sure how a feature detection test would actually work, short of submitting some work and then retrying without compression if it fails.

I'd tend to agree to make no compression the default to prevent this kind of issue, and to clearly document the failure case with AWS.

**Comment by binarylogic** [comment]
This should be pretty clear now: https://vector.dev/docs/reference/sinks/elasticsearch/
