### ISSUE TITLE
Metrics batch

### ISSUE THREAD

**Issue by loony-bean** [timberio/vector#920]
Vector has a detailed Metric type that allows it to recognise and ingest metrics from different sources. However when it comes to sending metrics into external services via sinks, we face a situation when external service supports only a subset of metric types, and we need to make some sort of stateful transformation of metrics before Vector can forward it.  This mostly relates to Set and relative Gauge metric types, which are usually not directly supported.

Besides that metrics aggregation could be used to handle high volumes of metrics. Unlike logs, metrics data cannot benefit from compression, but users tolerate some precision lost due to aggregation, because they do not usually need high resolution (sub seconds) metrics. 

To illustrate, existing CloudWatch metrics sink requires addressing both mentioned issues, see #747, #856. Same applies for the new integrations in the roadmap, such as InfluxDB, Graphite, DataDog, etc.

### Current state (CloudWatch metrics example)

This is how we forward CW metrics now: incoming data is sliced into batches, and these batches are encoded as API objects and forwarded to the API. Because the API has a limit of allowing not more than 20 metric objects in single request, the batch size of 20 is recommended (and really is the maximum possible value).

```
[c][c][c][g][g][g][h][h][h][s][s][s].... -> [c][c][c][g] -> Datum([c][c][c][g]) -> CW
                                            [g][g][h][h]    Datum([g][g][h][h])
                                            [h][s][s][s]    Datum([h][s][s][s])
                                                ....                ...

   data stream                                  batch              encode         send
```

_NB: c, g, h, s are metric types, representing some Counters, Gauges, Histograms and Sets._

### Solution

The idea is to add two independent steps into the pipeline:
1. `Aggregate` will 'group by' same metrics together, and replace batches of metrics with their aggregates. Metrics might change their type during the process, e.g. the batch of Set metrics will become a single Gauge observation containing the number of unique objects seen in the batch. By 'same metrics' we mean metrics with same name and tags.
2. `Split` will divide the list of metrics into chunks of smaller size. The difference between `batch` and `split` is that batch logic is defined by user, and split is meant to respect API or networking limitations, and might not even be visible to user. For example, it makes sense for user to configure 5min aggregation interval, and not bother about AWS API limits or MTU sizes, etc. Split might be useful with or without prior aggregation.

```
[c][c][c][g][g][g][h][h][h][s][s][s].... -> [c][c][c][g] -> [c][g] -> [c] -> Datum([c]) -> CW
                                            [g][g][h][h]    [g][h]    [g]    Datum([g])
                                            [h][s][s][s]    [h][g]    [g]    Datum([g])
                                                ....         ....     ...       ...

   data stream                                  batch      aggregate split     encode     send
```

For aggregation a new Batch type needs to be added. Splitting should be implemented in every sink independently with respect to external limitations.

### Questions

1. The possible issue with the `split` is that it is not clear where to apply service configuration such as retry logic, etc. Should it refer to the behaviour at the edge of the Service, where say the actual HTTP calls are made?
2. Should we reuse existing batch configuration options, namely `batch_size` and `batch_timeout`? One possible pitfall is that in metrics context `batch_size` will mean an upper limit, and not the lower limit like for logs batches. Another point is that many aggregators out there are using either size or time based intervals - but not both at the same time. Also we might want to add some kind of flag that will enable/disable aggregation.

**Comment by lukesteensen** [comment]
> Metrics might change their type during the process, e.g. the batch of Set metrics will become a single Gauge observation containing the number of unique objects seen in the batch.

Why is this? I would expect sets to be merged with a simple union, for example. For metric types that can't be merged, I think it's fine to batch them normally for now.

> The difference between `batch` and `split` is that batch logic is defined by user, and split is meant to respect API or networking limitations, and might not even be visible to user.

I'm very skeptical of adding in another concept here. Batching is intended to accomplish the same things you say here for `split`, and I worry that a second layer of invisible batching will be very confusing both for implementors and users. The existing batching infrastructure should be able to handle everything you want to accomplish with `split`, so why not keep things simpler?

---

The new `Batch` type is all we should need here, if my thinking is correct. For each incoming event, it would scan its existing elements for any that could be merged into the new data point. If there are none it would be appended normally, otherwise the old and new would be merged into a single event and appended. We could start off very conservatively and only implement merging for simple cases like counters/gauges/sets for the time being.

**Comment by binarylogic** [comment]
Thanks for the excellent writeup @loony-bean.

> For example, it makes sense for user to configure 5min aggregation interval, and not bother about AWS API limits or MTU sizes

If I understand this correctly, the `aws_cloudwatch_metrics` sink would "just work™" regardless of metric volume? This would have prevented the issue described in #856. I don't completely understand the internals of `Batch` and `split`, but I think it's cumbersome to require users to guess at an aggregation window that will prevent rate limited responses, especially when we know the limitations of the downstream service.

**Comment by loony-bean** [comment]
> Why is this? I would expect sets to be merged with a simple union, for example. For metric types that can't be merged, I think it's fine to batch them normally for now.

My thinking is that metrics batch type will have `type Output = Vec<Event>` (please check the ref PR). We have only streaming events (observations) in our current type system, where `Set` is just a `String` with attributes. That way if we'd need to return something on finish from the batch, then aggregating multiple `Set`s into single `Gauge` will make the most sense.

The good thing is that if the batch will produce only streaming metrics, then aggregations will be completely transparent for downstream sinks. For instance the same encoders will be used for streaming and 'aggregated' metrics.

**Comment by loony-bean** [comment]
> I'm very skeptical of adding in another concept here. Batching is intended to accomplish the same things you say here for `split`, and I worry that a second layer of invisible batching will be very confusing both for implementors and users

I agree with that.

**Comment by lukesteensen** [comment]
> `Set` is just a `String` with attributes

I keep forgetting this, sorry :smile:

I think what I'd propose then is to start off by ignoring histograms and sets (both names make me think they're mergeable but they currently are not). This will let us get the overall structure in place without worrying too much about complicated aggregations. Then, as a follow-up, we can look into expanding those two metrics types to hold multiple values (making them mergeable).

**Comment by binarylogic** [comment]
@loony-bean did #930 close this? If not, what's left?

**Comment by loony-bean** [comment]
@binarylogic If you don't mind, I'd close this issue as outdated, because the initial proposal is not what we have agreed to implement, and we have created follow up issues which are relevant.
