### ISSUE TITLE
kafka_sink reading bootstrap servers config as string, expected a sequence

### ISSUE THREAD

**Issue by absolute-fustercluck** [timberio/vector#925]
I am trying to create a kafka sink with a standalone confluent server and Vector is complaining about my config, which I basically copy and pasted from here. 

```
[root@d-kafka-b-gingersnaps-1b bin]# ./vector -v -c /etc/vector/audit.toml
 INFO vector: Log level "debug" is enabled.
 INFO vector: Loading config. path="/etc/vector/audit.toml"
 INFO vector: Vector is starting. version="0.3.0" git_version="v0.3.0" released="Tue, 02 Jul 2019 08:18:51 GMT" arch="x86_64"
ERROR vector::topology: Configuration error: invalid type: string "10.10.7.186:9093", expected a sequence for key `sinks.kafka_sink`

```
Here is my config

```
# Set global options
data_dir = "/var/lib/vector"

[sources.audit_logs]
  type         = "file"
  include      = ["/var/log/audit/*.log"]
  ignore_older = 86400

[sinks.kafka_sink]
  type = "kafka"
  inputs = ["audit_logs"]
  bootstrap_servers = "10.10.x.x:9093"
  topic = "auditd-test"
  encoding = "json"
```

I am running this on 4.20.8-1.el7

**Comment by lukesteensen** [comment]
> invalid type: string "10.10.7.186:9093", expected a sequence for key `sinks.kafka_sink`

This means that we're expecting an array for `bootstrap_servers` instead of a string, so changing it to `["10.10.x.x:9093"]` should fix your issue.

It does seem like this is documented incorrectly in a few places, so sorry about that! I'll push a fix.

**Comment by absolute-fustercluck** [comment]
Thanks for the prompt help here
