### ISSUE TITLE
Update tracing dependencies

### ISSUE THREAD

**Issue by loony-bean** [timberio/vector#929]
We might need to update `tracing` deps in accordance with the recent [changes](https://github.com/tokio-rs/tracing/pull/323).

I've run into this while trying to run `cargo outdated`:
```sh
$ cargo outdated
error: no matching package named `tracing-env-logger` found
location searched: https://github.com/tokio-rs/tracing
required by package `vector v0.4.0-dev (/var/folders/8q/vw_18tzd78l41qtzpv8zmn6m0000gq/T/cargo-outdatedPT9OD8)`
```

**Comment by LucioFranco** [comment]
This should be folded into https://github.com/timberio/vector/issues/628 as it will require a new version of tracing.
