### ISSUE TITLE
Reload config on file change

### ISSUE THREAD

**Issue by ktff** [timberio/vector#938]
### Context
In cloud environments it's beneficial to avoid permanent storage, and in some cases such storage is not even available. This is in conflict with the need to preserve checkpoints between vector runs which are used to avoid missing a log and logging it multiple times. This issue can be mitigated somewhat by being able to update vector topology without restarting vector.    

### Behavior
Maintain state of Vector as it is written in the config file.

---

### Use case
As a user, I would want to change configuration of Vector without having to worry if I will loose some logs because I have to restart it, regardless of the environment. 

### Example
In Kubernetes, if I change `vector.toml` part of `yaml` file and apply it, Kubernetes will update `vector.toml` file in all Vector containers, but will not restart them. Which will currently result in Vector not changing. But with this feature, applying changed `yaml` file will work as expected and change the behavior of Vector on the fly. 

### Other
This would also enhance UX regarding updating configuration as a two step process of changing config file and restarting Vector becomes a one step process. Just change the file and save. Vector will do the rest.

---

### Implementation
As I see, Vector is already able to dynamically update itself. All that is necessary is to listen for file changes on the configuration file and trigger such update.

**Comment by binarylogic** [comment]
This makes sense to me. I wouldn't mind having @lukesteensen approving before we begin work on this. @lukesteensen can you review and remove the `needs: review` label if this sounds good?

**Comment by LucioFranco** [comment]
> As I see, Vector is already able to dynamically update itself. All that is necessary is to listen for file changes on the configuration file and trigger such update.

This is correct, it should be a simple `inotify` api and read the new config file.  We probably also want to limit how often we run the reload to avoid spurious reloads.

**Comment by binarylogic** [comment]
@LucioFranco is inotify the best way to do this? Would it make more sense to hash the config contents and compare on an interval?

**Comment by LucioFranco** [comment]
@binarylogic inotify should work well for this and the api is simpler than using our own implementation. I would suggest that we start with it mainly to reduce complexity.

**Comment by lukesteensen** [comment]
We already have the ability to reload the config without restarting the process via SIGHUP. I think it's actually better for the reload to be an explicit action, as it reduces the chance of confusion. Are there examples of similar tools that watch the file system like this? In my experience, most require an explicit action to reload.

**Comment by LucioFranco** [comment]
I agree, I’d rather see if we could explicitly trigger the update. Though I’m not sure how to achieve this through kube.

**Comment by ktff** [comment]
Then this could be behind a flag in the configuration. Which would be by default turned off. 

And since running `kubectl apply` is an explicit trigger to update, in the supplied `.yaml` that flag could be on.

**Comment by binarylogic** [comment]
@ktff that sounds good. @lukesteensen @LucioFranco let me know if you object, otherwise I'd like @ktff to work on this.

**Comment by lukesteensen** [comment]
An opt-in feature sounds fine to me.

**Comment by darklajid** [comment]
Sorry for the necromancy, but https://github.com/vectordotdev/vector/blob/master/src/config/watcher.rs#L99 links here saying "Windows isn't supported", yet this bug doesn't seem to have any context why that's the case. The notify crate does support Windows - is it worth opening a new bug for that or to update this bug with context, given that it is linked to from source and error message?
