### ISSUE TITLE
Display git version for nightly builds

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#951]
When the `vector --version` command is run it would be helpful if _nightly_ builds printed a version like `0.4.0-31-g089bb5a`. Actual releases would continue to display the released version (`0.4.0`). This is helpful for debugging.

**Comment by a-rodin** [comment]
Just displaying git version can be done using [built](https://crates.io/crates/built) crate the we are already using [here](https://github.com/timberio/vector/blob/b541bb1a4097d22f3efa9d74ccaf28cabcbe6466/src/main.rs#L187). But

**Comment by LucioFranco** [comment]
> So I propose to display version info with style used by rustup's rustc when the build happens inside a git repository and just a simple version when build happens not from a git repository (for example, from a source archive). If the build happens inside CI, then *-dev versions should be displayed as *-nightly, otherwise they should be displayed as it.

👍 on this.
