### ISSUE TITLE
Unify the different TLS option sets

### ISSUE THREAD

**Issue by bruceg** [timberio/vector#955]
There are a number of sinks that support TLS that have different sets of options for configuring the same settings. These are:

1. `elasticsearch` sink:
   - `tls.ca_path`
   - `tls.crt_path`
   - `tls.key_path`
   - `tls.key_pass`
   - `tls.verify_certificate`
1. `http` sink: no CA or identity options, no `tls` prefix
   - `verify_certificate`
1. `kafka` sink: no `verify_certificate`
   - `tls.enabled`
   - `tls.ca_path`
   - `tls.crt_path`
   - `tls.key_path`
   - `tls.key_phrase`
1. `tcp` sink:
   - `tls.enabled`
   - `tls.ca_file`
   - `tls.crt_file`
   - `tls.key_file`
   - `tls.key_phrase`
   - `tls.verify`

These should be unified into one standard set of options and used consistently on all sinks that support TLS. `struct TlsOptions` is a start to this, but this cannot proceed without breaking compatibility with existing configuration, or writing messy workarounds.

Ref pull #953

**Comment by LucioFranco** [comment]
> but this cannot proceed without breaking compatibility with existing configuration, or writing messy workarounds.

breaking is fine, we are still below `1.0` 😄 

I am curious if we want to tackle TLS with rusoto as well? There is a possibility that we can unify all our "IO" parts into one component that is shared across all our sinks.

**Comment by bruceg** [comment]
Rusoto works on a different layer I think. We could potentially unify all the HTTPS parts with rusoto, but I don't know how much gain it would be. AFAICT only the elasticsearch sink works both with and without AWS support.

**Comment by bruceg** [comment]
@binarylogic Since this will result in identical options in several files in `.meta/sinks`, is there any chance of an "include" option or a macro mechanism there to avoid the repetition?

**Comment by binarylogic** [comment]
Yep. I have a pretty bad way of accomplishing this right now, which is to define common options in the `Sink` class:

https://github.com/timberio/vector/blob/2d5736e8f1e57ffe573c07cfcdc77e0c67dc84e9/scripts/util/metadata/sink.rb#L44

I'd much prefer to represent this in the `.toml` file itself, but that will require extending `.toml` in some way. I'd say you have 2 options for now:

1. Add options as I've done in the `Sink` class. Perhaps you could add a `tls` attribute to `Sink` that would automatically add these options. In other words, adding `tls: true` in the sink's `.toml` file would trigger this.
2. Copy / paste the options across all sinks.

In the future, we can work on a better way to accomplish this.

**Comment by bruceg** [comment]
Is there a preference between `_file`, `_filename`, or `_path` (for `ca`, `crt`, and `key`)?
Also, between `key_pass`, `key_password`, `key_phrase`, or `key_passphrase`?
