### ISSUE TITLE
Add an APT repository

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#962]
For context please see https://github.com/timberio/vector/issues/862

We initially offered `apt` support through PackageCloud but had a pretty bad experience with them. We've since moved off of them, updating our installation instructions to install the `.dpkg` directly. At some point in the future, I'd like to support `apt` in a way that does not lock us into a provider. We discussed using aptly [here](https://github.com/timberio/vector/issues/862#issuecomment-536319460).

**Comment by binarylogic** [comment]
I'm deferring this until we get more demand. Users can install the `.rpm` package directly, which can be done with one line:

https://vector.dev/docs/setup/installation/package-managers/rpm

If you'd prefer a repository we'd love to hear about it so we can prioritize.

**Comment by antifuchs** [comment]
Extremely into the idea of a package repository - users gain several advantages from it, and for you, the support story will get much better too (as upgrades, especially security ones, get streamlined):

* repositories are by default code-signed, which means users can trust that the files they got are the files you mean
* upgrades are easy & automatic, while allowing for version pinning
* the install process is somewhat more trustworthy / automatable than "download this file from the internet"

**Comment by binarylogic** [comment]
Thanks @antifuchs, we are too. We actually started by using [package cloud](https://packagecloud.io/), but our experience was not great. We plan to solve this before 1.0.

**Comment by lskillen** [comment]
Hey folks, we'd be happy to support you over on @cloudsmith-io - No need to request an open-source account, just create an open-source repository and away you go. :-)

**Comment by Hoverbear** [comment]
@lskillen So cool that you folks offer OSS accounts! Thanks for supporting the community!
