### ISSUE TITLE
Docker image and installation docs are incorrect

### ISSUE THREAD

**Issue by jamtur01** [timberio/vector#973]
Looks like the default configuration isn't valid anymore.

```
docker run timberio/vector:latest                                                                                                            (3s 297ms)
Unable to find image 'timberio/vector:latest' locally
latest: Pulling from timberio/vector
fc7181108d40: Pull complete
0a5f0e392ce5: Pull complete
99c63968bf9f: Pull complete
1c49c904e5bd: Pull complete
4e3cbecb16e3: Pull complete
479eb2c0e022: Pull complete
06d5878972bc: Pull complete
Digest: sha256:f31a0dc54b2297ea13c20af2719b5007ea2d950bc3d04c3c6983924a6d3faec2
Status: Downloaded newer image for timberio/vector:latest
 INFO vector: Log level "info" is enabled.
 INFO vector: Loading config. path="/vector/config/vector.toml"
 INFO vector: Vector is starting. version="0.3.0-dev" git_version="" released="Sat, 29 Jun 2019 21:45:14 GMT" arch="x86_64"
ERROR vector::topology: Configuration error: missing field `inputs` for key `sinks.print`
```

**Comment by jamtur01** [comment]
Also looks like `latest` is not the latest (it's 0.0.3) and that the Docker Hub and Docker installation docs are out-of-date too (the latest-alpine and latest-debian images don't exist for example nor do most of the other image tags in the docs).

**Comment by binarylogic** [comment]
@LucioFranco any idea what's going on here? I thought you worked on https://github.com/timberio/vector/issues/861 and addressed this in that process?

**Comment by binarylogic** [comment]
Thanks for reporting @jamtur01, this has been resolved. The `0.4.0-*` and `latest-*` images have been updated as well:

https://cloud.docker.com/u/timberio/repository/docker/timberio/vector
