### ISSUE TITLE
Docker image behavior inconsistent

### ISSUE THREAD

**Issue by jamtur01** [timberio/vector#974]
The behavior of two `timberio/vector:0.4.0-debian` and `timberio/vector:0.4.0-alpine` images is inconsistent.

For the `timberio/vector:0.4.0-debian` image:

```
docker run -ti timberio/vector:0.4.0-debian
containerid$ ...
```

The `timberio/vector:0.4.0-alpine` image:

```
error: The following required arguments were not provided:
    --config <FILE>

USAGE:
    vector [FLAGS] [OPTIONS] --config <FILE>

For more information try --help
```

Not sure if this is intentional or a bug.

**Comment by binarylogic** [comment]
Thanks @jamtur01 and sorry for the trouble. We'll correct this on Monday and add tests to ensure this doesn't regress.

**Comment by binarylogic** [comment]
Thanks for reporting @jamtur01, this has been resolved. The `0.4.0-*` and `latest-*` images have been updated as well:

https://cloud.docker.com/u/timberio/repository/docker/timberio/vector
