### ISSUE TITLE
Default configuration shouldn't assume Apache

### ISSUE THREAD

**Issue by jamtur01** [timberio/vector#975]
This is more of a suggestion than a bug. The current default configuration loads logs from Apache and outputs to console. I'd recommend using a configuration that will work out of the box without assuming Apache. For example, perhaps stdin to stdout with the text transformed some way? That way you see some working operations.

**Comment by binarylogic** [comment]
👍 agree, thanks for letting us know.

**Comment by binarylogic** [comment]
Thanks for reporting @jamtur01, this has been resolved. The `0.4.0-*` and `latest-*` images have been updated as well:

https://cloud.docker.com/u/timberio/repository/docker/timberio/vector
