### ISSUE TITLE
The Vector install script requires `sudo` when running `dpkg`

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#998]
I have a CI check that tests if the install script works. This check is run on Debian so the script tries to use `dpkg`. The issue is that `sudo` is required to execute `dpkg`:

```
>>> Downloading Vector via https://packages.timber.io/vector/latest/vector-amd64.deb ✓
>>> Installing Vector via dpkg...
>>> command failed: dpkg -i /tmp/tmp.q9R28fTHDj/vector-amd64.deb
--------------------------------------------------------------------------------
dpkg: error: requested operation requires superuser privilege
Exited with code 1
```

Our installation instructions advertise the following command:

```bash
curl https://sh.vector.dev -sSf | sh
```

I'm curious what the best course of action is here?

1. I could prefix [this command](https://github.com/timberio/vector/blob/df6018be6c1c964692d3ea071f4d95fb21f1cb14/distribution/install.sh#L236) with `sudo`, but that feels incorrect.
2. We could update the advertised install command to include `sudo`?
3. We could install Vector through the archive and manually move the files into their appropriate locations.

I'm curious what `dpkg` is doing that requires `sudo`.

**Comment by lukesteensen** [comment]
Installing a package is generally something that requires `sudo`. I don't think most of the `curl | sh`-style installers use actual packages under the hood, and people are rightly a little suspicious of `curl | sudo sh`.

We could potentially split these up, encouraging everyone who can to just use the deb/rpm directly (i.e. `curl`/`wget` and `dpkg -i` doesn't need it's own script) and then have the script use the archive and do things manually. But really using the packages is by far the easiest way both for us and for users to get vector installed. With ansible the entire process is:

```yaml
- name: Install vector
  apt:
    deb: "https://packages.timber.io/vector/nightly/latest/vector-amd64.deb"
```
